-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/cc_discrepancy_ra.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.cc_discrepancy_ra AS SELECT
    ROUND(cc_discrepancy.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(cc_discrepancy.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    cc_discrepancy.iplan_order_num,
    cc_discrepancy.extract_date_time,
    ROUND(cc_discrepancy.ar_amt, 3, 'ROUND_HALF_EVEN') AS ar_amt,
    cc_discrepancy.actv_desc,
    cc_discrepancy.actv_due_date,
    cc_discrepancy.activity_kpi_name,
    cc_discrepancy.actv_owner_desc,
    cc_discrepancy.actv_subject_desc,
    cc_discrepancy.admit_source_cd,
    ROUND(cc_discrepancy.attending_physician_id, 0, 'ROUND_HALF_EVEN') AS attending_physician_id,
    cc_discrepancy.attending_physician_name,
    cc_discrepancy.authorization_cd,
    cc_discrepancy.billing_contact_name,
    cc_discrepancy.billing_name,
    cc_discrepancy.billing_status_cd,
    cc_discrepancy.calc_date,
    cc_discrepancy.cancel_bill_ind,
    cc_discrepancy.cc_pat_type_cd,
    cc_discrepancy.coid,
    ROUND(cc_discrepancy.collection_amt, 3, 'ROUND_HALF_EVEN') AS collection_amt,
    cc_discrepancy.collection_date,
    cc_discrepancy.company_code,
    cc_discrepancy.comparison_method_desc,
    cc_discrepancy.credit_balance_age_desc,
    cc_discrepancy.credit_category_name,
    cc_discrepancy.crt_placed_activity_date,
    cc_discrepancy.discharge_date,
    cc_discrepancy.discrepancy_group_name,
    cc_discrepancy.first_actv_create_date,
    ROUND(cc_discrepancy.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    cc_discrepancy.iplan_id,
    cc_discrepancy.insurance_provider_name,
    cc_discrepancy.last_actv_completion_age_num,
    cc_discrepancy.last_actv_completion_date,
    cc_discrepancy.last_owner_change_date,
    cc_discrepancy.last_project_change_date,
    cc_discrepancy.last_reason_change_date,
    cc_discrepancy.last_reason_change_date_2,
    cc_discrepancy.last_reason_change_date_3,
    cc_discrepancy.last_reason_change_date_4,
    cc_discrepancy.last_status_change_date,
    cc_discrepancy.max_type_5_trans_date,
    cc_discrepancy.model_issue_desc,
    ROUND(cc_discrepancy.monbot_acct_payer_id, 0, 'ROUND_HALF_EVEN') AS monbot_acct_payer_id,
    cc_discrepancy.non_fin_dcrp_age_num,
    cc_discrepancy.non_fin_dcrp_date,
    cc_discrepancy.overpayment_age_num,
    cc_discrepancy.overpayment_date,
    cc_discrepancy.pa_acct_status_desc,
    cc_discrepancy.pa_actual_los_num,
    cc_discrepancy.pa_discharge_status_cd,
    cc_discrepancy.pa_drg_cd,
    cc_discrepancy.pa_financial_class_num,
    cc_discrepancy.pa_pat_type_desc,
    cc_discrepancy.pa_service_cd,
    ROUND(cc_discrepancy.pa_total_acct_bal_amt, 3, 'ROUND_HALF_EVEN') AS pa_total_acct_bal_amt,
    cc_discrepancy.pat_birth_date,
    cc_discrepancy.pat_name,
    cc_discrepancy.payor_category_name,
    ROUND(cc_discrepancy.payor_due_amt, 3, 'ROUND_HALF_EVEN') AS payor_due_amt,
    ROUND(cc_discrepancy.payor_financial_class_id, 0, 'ROUND_HALF_EVEN') AS payor_financial_class_id,
    cc_discrepancy.payor_group_name,
    cc_discrepancy.payor_pat_cd,
    cc_discrepancy.project_name,
    cc_discrepancy.rate_schedule_name,
    cc_discrepancy.rate_schedule_eff_begin_date,
    cc_discrepancy.rate_schedule_eff_end_date,
    cc_discrepancy.reason_code,
    cc_discrepancy.reason_code_2,
    cc_discrepancy.reason_code_3,
    cc_discrepancy.reason_code_4,
    cc_discrepancy.remit_drg_code,
    ROUND(cc_discrepancy.sec_establishment_id, 0, 'ROUND_HALF_EVEN') AS sec_establishment_id,
    cc_discrepancy.service_begin_date,
    cc_discrepancy.ssc_name,
    cc_discrepancy.status_category_desc,
    cc_discrepancy.status_desc,
    cc_discrepancy.status_kpi_name,
    cc_discrepancy.status_phase_desc,
    cc_discrepancy.stratification_group_name,
    ROUND(cc_discrepancy.total_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_billed_charge_amt,
    ROUND(cc_discrepancy.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
    ROUND(cc_discrepancy.total_denial_amt, 3, 'ROUND_HALF_EVEN') AS total_denial_amt,
    ROUND(cc_discrepancy.total_expected_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_expected_adjustment_amt,
    ROUND(cc_discrepancy.total_expected_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_expected_payment_amt,
    ROUND(cc_discrepancy.total_pat_resp_amt, 3, 'ROUND_HALF_EVEN') AS total_pat_resp_amt,
    ROUND(cc_discrepancy.total_pmt_amt, 3, 'ROUND_HALF_EVEN') AS total_pmt_amt,
    ROUND(cc_discrepancy.total_var_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_var_adjustment_amt,
    cc_discrepancy.underpayment_age_num,
    cc_discrepancy.underpayment_date,
    cc_discrepancy.unit_num,
    cc_discrepancy.user_completed_actv_age_num,
    cc_discrepancy.user_completed_actv_date,
    cc_discrepancy.user_completed_actv_desc,
    cc_discrepancy.user_completed_actv_ownr_34_id,
    cc_discrepancy.user_completed_actv_subj_desc,
    cc_discrepancy.var_creation_age_num,
    cc_discrepancy.var_creation_date,
    cc_discrepancy.var_resolution_age_num,
    cc_discrepancy.var_resolution_date,
    cc_discrepancy.valid_over_pmt_actv_age_num,
    cc_discrepancy.valid_over_pmt_actv_date,
    cc_discrepancy.valid_over_pmt_actv_desc,
    cc_discrepancy.valid_over_pmt_actv_ownr_desc,
    cc_discrepancy.valid_over_pmt_actv_subj_desc,
    cc_discrepancy.valid_under_pmt_actv_age_num,
    cc_discrepancy.valid_under_pmt_actv_date,
    cc_discrepancy.valid_under_pmt_actv_desc,
    cc_discrepancy.valid_under_pmt_actv_ownr_id,
    cc_discrepancy.valid_under_pmt_actv_subj_desc,
    cc_discrepancy.validation_group_name,
    cc_discrepancy.work_queue_name,
    cc_discrepancy.source_system_code,
    cc_discrepancy.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwra_base_views.cc_discrepancy
;
