-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/collection_encounter_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.collection_encounter_detail
   OPTIONS(description='A daily inventory pull from Artiva system, that has the collections related work orders.')
  AS SELECT
      ROUND(collection_encounter_detail.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      collection_encounter_detail.reporting_date,
      collection_encounter_detail.day_interval_sid,
      collection_encounter_detail.liability_sequence_number,
      collection_encounter_detail.artiva_instance_code,
      collection_encounter_detail.company_code,
      collection_encounter_detail.coid,
      collection_encounter_detail.unit_num,
      ROUND(collection_encounter_detail.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      collection_encounter_detail.patient_type_code,
      collection_encounter_detail.account_status_code,
      collection_encounter_detail.lob_grp_code,
      collection_encounter_detail.iplan_id,
      ROUND(collection_encounter_detail.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      collection_encounter_detail.discharge_age_month_sid,
      collection_encounter_detail.last_worked_age_month_sid,
      collection_encounter_detail.delinquent_days_age_sid,
      collection_encounter_detail.encounter_financial_class_code,
      collection_encounter_detail.liability_financial_class_code,
      collection_encounter_detail.hic_claim_num,
      collection_encounter_detail.claim_num,
      collection_encounter_detail.check_num_an,
      collection_encounter_detail.medical_record_num,
      collection_encounter_detail.early_out_hold_ind,
      collection_encounter_detail.vendor_id,
      collection_encounter_detail.prev_vendor_id,
      collection_encounter_detail.liability_phase_status_desc,
      collection_encounter_detail.prev_liability_phase_desc,
      collection_encounter_detail.phase_change_date,
      collection_encounter_detail.status_desc,
      collection_encounter_detail.prior_status_desc,
      collection_encounter_detail.denial_status_code,
      collection_encounter_detail.bad_debt_reason_code,
      collection_encounter_detail.encounter_date,
      collection_encounter_detail.wait_date,
      collection_encounter_detail.denial_date,
      collection_encounter_detail.claim_submit_date,
      collection_encounter_detail.final_bill_date,
      collection_encounter_detail.early_out_date,
      collection_encounter_detail.liability_last_billed_date,
      collection_encounter_detail.liability_last_worked_date,
      collection_encounter_detail.last_worked_age_days_cnt,
      collection_encounter_detail.prev_pool_assignment_id,
      collection_encounter_detail.prev_pool_date,
      collection_encounter_detail.current_pool_assignment_id,
      collection_encounter_detail.pool_responsible_dept_name,
      collection_encounter_detail.inclusion_flag,
      collection_encounter_detail.action_code,
      collection_encounter_detail.result_code,
      collection_encounter_detail.last_action_date,
      collection_encounter_detail.last_action_time,
      collection_encounter_detail.last_action_updt_by_user_id,
      collection_encounter_detail.service_code,
      collection_encounter_detail.delinquent_days_cnt,
      ROUND(collection_encounter_detail.cc_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_activity_type_id,
      ROUND(collection_encounter_detail.cc_prev_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_prev_activity_type_id,
      ROUND(collection_encounter_detail.total_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_billed_charge_amt,
      ROUND(collection_encounter_detail.non_bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS non_bill_charge_amt,
      ROUND(collection_encounter_detail.encounter_balance_amt, 3, 'ROUND_HALF_EVEN') AS encounter_balance_amt,
      ROUND(collection_encounter_detail.original_balance_amt, 3, 'ROUND_HALF_EVEN') AS original_balance_amt,
      ROUND(collection_encounter_detail.current_balance_amt, 3, 'ROUND_HALF_EVEN') AS current_balance_amt,
      collection_encounter_detail.liability_level_code,
      ROUND(collection_encounter_detail.total_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_adjustment_amt,
      ROUND(collection_encounter_detail.total_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_payment_amt,
      ROUND(collection_encounter_detail.placement_amt, 3, 'ROUND_HALF_EVEN') AS placement_amt,
      collection_encounter_detail.placement_date,
      collection_encounter_detail.placement_level_num,
      collection_encounter_detail.appeal_flag,
      collection_encounter_detail.appeal_source_system_code,
      collection_encounter_detail.denial_code,
      collection_encounter_detail.appeal_disp_code,
      collection_encounter_detail.appeal_level_num,
      collection_encounter_detail.appeal_seq_num,
      ROUND(collection_encounter_detail.appeal_source_system_id, 0, 'ROUND_HALF_EVEN') AS appeal_source_system_id,
      collection_encounter_detail.appeal_sent_date,
      collection_encounter_detail.appeal_follow_up_date,
      collection_encounter_detail.appeal_closing_date,
      ROUND(collection_encounter_detail.appeal_amt, 3, 'ROUND_HALF_EVEN') AS appeal_amt,
      collection_encounter_detail.admission_date,
      collection_encounter_detail.discharge_date,
      collection_encounter_detail.last_claim_status_rspn_date,
      collection_encounter_detail.last_claim_status_rspn_code,
      collection_encounter_detail.last_claim_status_rspn_type_code,
      collection_encounter_detail.last_claim_status_rspn_pblm_code,
      collection_encounter_detail.last_claim_status_rspn_scat_id,
      collection_encounter_detail.user_alert_comment_text,
      collection_encounter_detail.user_alert_edit_date_time,
      collection_encounter_detail.alert_created_by_user_id,
      collection_encounter_detail.user_alert_expr_date,
      collection_encounter_detail.billing_history_ind,
      ROUND(collection_encounter_detail.insgn_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS insgn_account_balance_amt,
      ROUND(collection_encounter_detail.episode_id, 0, 'ROUND_HALF_EVEN') AS episode_id,
      ROUND(collection_encounter_detail.patient_id, 0, 'ROUND_HALF_EVEN') AS patient_id,
      collection_encounter_detail.notice_of_admission_date,
      collection_encounter_detail.notice_of_election_date,
      collection_encounter_detail.erisa_ind,
      collection_encounter_detail.hosp_dc_screening_status_flag,
      collection_encounter_detail.screening_letter_include_ind,
      collection_encounter_detail.elig_program_id,
      collection_encounter_detail.elig_screening_date,
      collection_encounter_detail.web_status_flag,
      collection_encounter_detail.source_system_code,
      collection_encounter_detail.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.collection_encounter_detail
  ;
