-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/collection_encounter_detail_crnt.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.collection_encounter_detail_crnt
   OPTIONS(description='A daily inventory pull from Artiva system, that has the collections related work orders which has current refreshed data.\rThis structure is the exact copy of the existing Edwpbs.Collection_Encounter_Detail')
  AS SELECT
      ROUND(collection_encounter_detail_crnt.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      collection_encounter_detail_crnt.reporting_date,
      collection_encounter_detail_crnt.day_interval_sid,
      collection_encounter_detail_crnt.liability_sequence_number,
      collection_encounter_detail_crnt.artiva_instance_code,
      collection_encounter_detail_crnt.company_code,
      collection_encounter_detail_crnt.coid,
      collection_encounter_detail_crnt.unit_num,
      ROUND(collection_encounter_detail_crnt.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      collection_encounter_detail_crnt.patient_type_code,
      collection_encounter_detail_crnt.account_status_code,
      collection_encounter_detail_crnt.lob_grp_code,
      collection_encounter_detail_crnt.iplan_id,
      ROUND(collection_encounter_detail_crnt.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      collection_encounter_detail_crnt.discharge_age_month_sid,
      collection_encounter_detail_crnt.last_worked_age_month_sid,
      collection_encounter_detail_crnt.delinquent_days_age_sid,
      collection_encounter_detail_crnt.encounter_financial_class_code,
      collection_encounter_detail_crnt.liability_financial_class_code,
      collection_encounter_detail_crnt.hic_claim_num,
      collection_encounter_detail_crnt.claim_num,
      collection_encounter_detail_crnt.check_num_an,
      collection_encounter_detail_crnt.medical_record_num,
      collection_encounter_detail_crnt.early_out_hold_ind,
      collection_encounter_detail_crnt.vendor_id,
      collection_encounter_detail_crnt.prev_vendor_id,
      collection_encounter_detail_crnt.liability_phase_status_desc,
      collection_encounter_detail_crnt.prev_liability_phase_desc,
      collection_encounter_detail_crnt.phase_change_date,
      collection_encounter_detail_crnt.status_desc,
      collection_encounter_detail_crnt.prior_status_desc,
      collection_encounter_detail_crnt.denial_status_code,
      collection_encounter_detail_crnt.bad_debt_reason_code,
      collection_encounter_detail_crnt.encounter_date,
      collection_encounter_detail_crnt.wait_date,
      collection_encounter_detail_crnt.denial_date,
      collection_encounter_detail_crnt.claim_submit_date,
      collection_encounter_detail_crnt.final_bill_date,
      collection_encounter_detail_crnt.early_out_date,
      collection_encounter_detail_crnt.liability_last_billed_date,
      collection_encounter_detail_crnt.liability_last_worked_date,
      collection_encounter_detail_crnt.last_worked_age_days_cnt,
      collection_encounter_detail_crnt.prev_pool_assignment_id,
      collection_encounter_detail_crnt.prev_pool_date,
      collection_encounter_detail_crnt.current_pool_assignment_id,
      collection_encounter_detail_crnt.pool_responsible_dept_name,
      collection_encounter_detail_crnt.inclusion_flag,
      collection_encounter_detail_crnt.action_code,
      collection_encounter_detail_crnt.result_code,
      collection_encounter_detail_crnt.last_action_date,
      collection_encounter_detail_crnt.last_action_time,
      collection_encounter_detail_crnt.last_action_updt_by_user_id,
      collection_encounter_detail_crnt.service_code,
      collection_encounter_detail_crnt.delinquent_days_cnt,
      ROUND(collection_encounter_detail_crnt.cc_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_activity_type_id,
      ROUND(collection_encounter_detail_crnt.cc_prev_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_prev_activity_type_id,
      ROUND(collection_encounter_detail_crnt.total_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_billed_charge_amt,
      ROUND(collection_encounter_detail_crnt.non_bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS non_bill_charge_amt,
      ROUND(collection_encounter_detail_crnt.encounter_balance_amt, 3, 'ROUND_HALF_EVEN') AS encounter_balance_amt,
      ROUND(collection_encounter_detail_crnt.original_balance_amt, 3, 'ROUND_HALF_EVEN') AS original_balance_amt,
      ROUND(collection_encounter_detail_crnt.current_balance_amt, 3, 'ROUND_HALF_EVEN') AS current_balance_amt,
      collection_encounter_detail_crnt.liability_level_code,
      ROUND(collection_encounter_detail_crnt.total_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_adjustment_amt,
      ROUND(collection_encounter_detail_crnt.total_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_payment_amt,
      ROUND(collection_encounter_detail_crnt.placement_amt, 3, 'ROUND_HALF_EVEN') AS placement_amt,
      collection_encounter_detail_crnt.placement_date,
      collection_encounter_detail_crnt.placement_level_num,
      collection_encounter_detail_crnt.appeal_flag,
      collection_encounter_detail_crnt.appeal_source_system_code,
      collection_encounter_detail_crnt.denial_code,
      collection_encounter_detail_crnt.appeal_disp_code,
      collection_encounter_detail_crnt.appeal_level_num,
      collection_encounter_detail_crnt.appeal_seq_num,
      ROUND(collection_encounter_detail_crnt.appeal_source_system_id, 0, 'ROUND_HALF_EVEN') AS appeal_source_system_id,
      collection_encounter_detail_crnt.appeal_sent_date,
      collection_encounter_detail_crnt.appeal_follow_up_date,
      collection_encounter_detail_crnt.appeal_closing_date,
      ROUND(collection_encounter_detail_crnt.appeal_amt, 3, 'ROUND_HALF_EVEN') AS appeal_amt,
      collection_encounter_detail_crnt.admission_date,
      collection_encounter_detail_crnt.discharge_date,
      collection_encounter_detail_crnt.last_claim_status_rspn_date,
      collection_encounter_detail_crnt.last_claim_status_rspn_code,
      collection_encounter_detail_crnt.last_claim_status_rspn_type_code,
      collection_encounter_detail_crnt.last_claim_status_rspn_pblm_code,
      collection_encounter_detail_crnt.last_claim_status_rspn_scat_id,
      collection_encounter_detail_crnt.user_alert_comment_text,
      collection_encounter_detail_crnt.user_alert_edit_date_time,
      collection_encounter_detail_crnt.alert_created_by_user_id,
      collection_encounter_detail_crnt.user_alert_expr_date,
      collection_encounter_detail_crnt.billing_history_ind,
      ROUND(collection_encounter_detail_crnt.insgn_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS insgn_account_balance_amt,
      ROUND(collection_encounter_detail_crnt.episode_id, 0, 'ROUND_HALF_EVEN') AS episode_id,
      ROUND(collection_encounter_detail_crnt.patient_id, 0, 'ROUND_HALF_EVEN') AS patient_id,
      collection_encounter_detail_crnt.notice_of_admission_date,
      collection_encounter_detail_crnt.notice_of_election_date,
      collection_encounter_detail_crnt.erisa_ind,
      collection_encounter_detail_crnt.hosp_dc_screening_status_flag,
      collection_encounter_detail_crnt.screening_letter_include_ind,
      collection_encounter_detail_crnt.elig_program_id,
      collection_encounter_detail_crnt.elig_screening_date,
      collection_encounter_detail_crnt.web_status_flag,
      collection_encounter_detail_crnt.source_system_code,
      collection_encounter_detail_crnt.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.collection_encounter_detail_crnt
  ;
