-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/discrepancy_inventory_analysis.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.discrepancy_inventory_analysis
   OPTIONS(description='Monthly Discrepancy Inventory for all customers to evaluate the Cost year logic calculation')
  AS SELECT
      discrepancy_inventory_analysis.date_sid,
      ROUND(discrepancy_inventory_analysis.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      ROUND(discrepancy_inventory_analysis.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      discrepancy_inventory_analysis.iplan_insurance_order_num,
      discrepancy_inventory_analysis.log_id,
      discrepancy_inventory_analysis.ar_bill_thru_date,
      discrepancy_inventory_analysis.discrepancy_creation_date,
      ROUND(discrepancy_inventory_analysis.patient_sid, 0, 'ROUND_HALF_EVEN') AS patient_sid,
      discrepancy_inventory_analysis.payor_sequence_sid,
      discrepancy_inventory_analysis.unit_num_sid,
      discrepancy_inventory_analysis.eor_log_date,
      discrepancy_inventory_analysis.log_sequence_num,
      discrepancy_inventory_analysis.year_created_sid,
      discrepancy_inventory_analysis.cost_year_sid,
      discrepancy_inventory_analysis.cost_year_end_date,
      discrepancy_inventory_analysis.payor_financial_class_sid,
      discrepancy_inventory_analysis.payor_sid,
      discrepancy_inventory_analysis.patient_type_sid,
      discrepancy_inventory_analysis.discrepancy_age_month_sid,
      discrepancy_inventory_analysis.discharge_age_month_sid,
      discrepancy_inventory_analysis.scenario_sid,
      ROUND(discrepancy_inventory_analysis.reason_code_1_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_1_sid,
      ROUND(discrepancy_inventory_analysis.reason_code_2_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_2_sid,
      ROUND(discrepancy_inventory_analysis.reason_code_3_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_3_sid,
      ROUND(discrepancy_inventory_analysis.reason_code_4_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_4_sid,
      discrepancy_inventory_analysis.source_sid,
      ROUND(discrepancy_inventory_analysis.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
      discrepancy_inventory_analysis.coid,
      discrepancy_inventory_analysis.company_code,
      discrepancy_inventory_analysis.resolve_reason_code,
      discrepancy_inventory_analysis.discharge_date,
      discrepancy_inventory_analysis.ra_remit_date,
      discrepancy_inventory_analysis.reason_assignment_date_1,
      discrepancy_inventory_analysis.reason_assignment_date_2,
      discrepancy_inventory_analysis.reason_assignment_date_3,
      discrepancy_inventory_analysis.reason_assignment_date_4,
      ROUND(discrepancy_inventory_analysis.account_balance_amt, 3, 'ROUND_HALF_EVEN') AS account_balance_amt,
      discrepancy_inventory_analysis.primary_reason_code_change_cnt,
      discrepancy_inventory_analysis.discrepancy_days,
      discrepancy_inventory_analysis.discrepancy_resolved_date,
      discrepancy_inventory_analysis.discrepany_type_code,
      discrepancy_inventory_analysis.discrepancy_type_sid,
      discrepancy_inventory_analysis.same_store_sid,
      discrepancy_inventory_analysis.dollar_strtf_sid,
      ROUND(discrepancy_inventory_analysis.var_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_beg_amt,
      ROUND(discrepancy_inventory_analysis.var_new_amt, 3, 'ROUND_HALF_EVEN') AS var_new_amt,
      ROUND(discrepancy_inventory_analysis.var_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_resolved_amt,
      ROUND(discrepancy_inventory_analysis.var_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_othr_cor_amt,
      ROUND(discrepancy_inventory_analysis.var_end_amt, 3, 'ROUND_HALF_EVEN') AS var_end_amt,
      ROUND(discrepancy_inventory_analysis.exp_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_crnt_amt,
      ROUND(discrepancy_inventory_analysis.exp_rate_amt, 3, 'ROUND_HALF_EVEN') AS exp_rate_amt,
      discrepancy_inventory_analysis.var_beg_cnt,
      discrepancy_inventory_analysis.var_new_cnt,
      discrepancy_inventory_analysis.var_resolved_cnt,
      discrepancy_inventory_analysis.var_othr_cor_cnt,
      discrepancy_inventory_analysis.var_end_cnt,
      discrepancy_inventory_analysis.exp_crnt_cnt,
      discrepancy_inventory_analysis.exp_rate_cnt,
      discrepancy_inventory_analysis.resolved_days,
      discrepancy_inventory_analysis.end_days,
      discrepancy_inventory_analysis.source_system_code,
      discrepancy_inventory_analysis.dw_last_update_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.discrepancy_inventory_analysis
  ;
