-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_rcom_pars_denial.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.fact_rcom_pars_denial
   OPTIONS(description='This is Monthly Denial Inventory for HCA and Parallon Customers.')
  AS SELECT
      ROUND(fact_rcom_pars_denial.patient_sid, 0, 'ROUND_HALF_EVEN') AS patient_sid,
      fact_rcom_pars_denial.date_sid,
      fact_rcom_pars_denial.payor_sid,
      fact_rcom_pars_denial.payor_financial_class_sid,
      fact_rcom_pars_denial.payor_sequence_sid,
      fact_rcom_pars_denial.patient_type_sid,
      fact_rcom_pars_denial.appeal_disp_sid,
      fact_rcom_pars_denial.appeal_code_sid,
      fact_rcom_pars_denial.discharge_age_month_sid,
      fact_rcom_pars_denial.denial_orig_age_month_sid,
      fact_rcom_pars_denial.appeal_age_month_sid,
      fact_rcom_pars_denial.service_code_sid,
      fact_rcom_pars_denial.unit_num_sid,
      fact_rcom_pars_denial.los_sid,
      fact_rcom_pars_denial.drg_sid,
      fact_rcom_pars_denial.admission_type_sid,
      fact_rcom_pars_denial.denial_type_sid,
      fact_rcom_pars_denial.appeal_root_cause_sid,
      fact_rcom_pars_denial.scenario_sid,
      fact_rcom_pars_denial.source_sid,
      ROUND(fact_rcom_pars_denial.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      fact_rcom_pars_denial.iplan_id,
      ROUND(fact_rcom_pars_denial.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      fact_rcom_pars_denial.coid,
      fact_rcom_pars_denial.company_code,
      fact_rcom_pars_denial.same_store_sid,
      fact_rcom_pars_denial.resolved_denial_age_month_id,
      fact_rcom_pars_denial.resolved_discharge_age_month_id,
      fact_rcom_pars_denial.dollar_strf_sid,
      fact_rcom_pars_denial.person_role_code,
      fact_rcom_pars_denial.patient_full_name,
      fact_rcom_pars_denial.patient_birth_date,
      ROUND(fact_rcom_pars_denial.beginning_balance_amt, 3, 'ROUND_HALF_EVEN') AS beginning_balance_amt,
      fact_rcom_pars_denial.beginning_balance_count,
      ROUND(fact_rcom_pars_denial.beginning_appeal_amt, 3, 'ROUND_HALF_EVEN') AS beginning_appeal_amt,
      ROUND(fact_rcom_pars_denial.ending_balance_amt, 3, 'ROUND_HALF_EVEN') AS ending_balance_amt,
      fact_rcom_pars_denial.ending_balance_count,
      ROUND(fact_rcom_pars_denial.account_balance_amt, 3, 'ROUND_HALF_EVEN') AS account_balance_amt,
      ROUND(fact_rcom_pars_denial.write_off_denial_account_amt, 3, 'ROUND_HALF_EVEN') AS write_off_denial_account_amt,
      fact_rcom_pars_denial.write_off_denial_account_count,
      ROUND(fact_rcom_pars_denial.new_denial_account_amt, 3, 'ROUND_HALF_EVEN') AS new_denial_account_amt,
      fact_rcom_pars_denial.new_denial_account_count,
      ROUND(fact_rcom_pars_denial.not_true_denial_amt, 3, 'ROUND_HALF_EVEN') AS not_true_denial_amt,
      fact_rcom_pars_denial.not_true_denial_count,
      ROUND(fact_rcom_pars_denial.corrections_account_amt, 3, 'ROUND_HALF_EVEN') AS corrections_account_amt,
      fact_rcom_pars_denial.corrections_account_count,
      ROUND(fact_rcom_pars_denial.overturned_account_amt, 3, 'ROUND_HALF_EVEN') AS overturned_account_amt,
      fact_rcom_pars_denial.overturned_account_count,
      ROUND(fact_rcom_pars_denial.cc_corrections_account_amt, 3, 'ROUND_HALF_EVEN') AS cc_corrections_account_amt,
      fact_rcom_pars_denial.cc_corrections_account_cnt,
      ROUND(fact_rcom_pars_denial.cc_overturned_account_amt, 3, 'ROUND_HALF_EVEN') AS cc_overturned_account_amt,
      fact_rcom_pars_denial.cc_overturned_account_cnt,
      ROUND(fact_rcom_pars_denial.trans_next_party_amt, 3, 'ROUND_HALF_EVEN') AS trans_next_party_amt,
      fact_rcom_pars_denial.trans_next_party_count,
      ROUND(fact_rcom_pars_denial.unworked_conversion_amt, 3, 'ROUND_HALF_EVEN') AS unworked_conversion_amt,
      fact_rcom_pars_denial.unworked_conversion_count,
      fact_rcom_pars_denial.resolved_accounts_count,
      ROUND(fact_rcom_pars_denial.below_threshold_amt, 3, 'ROUND_HALF_EVEN') AS below_threshold_amt,
      fact_rcom_pars_denial.below_threshold_count,
      fact_rcom_pars_denial.appeal_closing_date,
      fact_rcom_pars_denial.appeal_level_origination_date,
      fact_rcom_pars_denial.appeal_deadline_date,
      fact_rcom_pars_denial.appeal_level_num,
      fact_rcom_pars_denial.work_again_date,
      fact_rcom_pars_denial.attending_physician_name,
      ROUND(fact_rcom_pars_denial.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      fact_rcom_pars_denial.last_update_id,
      fact_rcom_pars_denial.last_update_date,
      fact_rcom_pars_denial.appeal_origination_date,
      fact_rcom_pars_denial.discharge_date,
      fact_rcom_pars_denial.resolved_days,
      fact_rcom_pars_denial.open_days,
      fact_rcom_pars_denial.overturned_days,
      fact_rcom_pars_denial.final_bill_count,
      ROUND(fact_rcom_pars_denial.final_bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS final_bill_charge_amt,
      ROUND(fact_rcom_pars_denial.denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS denied_charge_amt,
      ROUND(fact_rcom_pars_denial.cash_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS cash_adjustment_amt,
      ROUND(fact_rcom_pars_denial.contractual_allow_adj_amt, 3, 'ROUND_HALF_EVEN') AS contractual_allow_adj_amt,
      ROUND(fact_rcom_pars_denial.cc_appeal_num, 0, 'ROUND_HALF_EVEN') AS cc_appeal_num,
      fact_rcom_pars_denial.cc_appeal_detail_seq_num,
      ROUND(fact_rcom_pars_denial.cc_appeal_crnt_bal_amt, 3, 'ROUND_HALF_EVEN') AS cc_appeal_crnt_bal_amt,
      fact_rcom_pars_denial.pa_vendor_code,
      fact_rcom_pars_denial.prepay_mc_flag,
      fact_rcom_pars_denial.pe_date,
      fact_rcom_pars_denial.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.fact_rcom_pars_denial
  ;
