-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_transfusion_product_detail_cdm.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.fact_transfusion_product_detail_cdm AS SELECT
    ROUND(fact_transfusion_product_detail.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(fact_transfusion_product_detail.transfusion_unit_sk, 0, 'ROUND_HALF_EVEN') AS transfusion_unit_sk,
    ROUND(fact_transfusion_product_detail.transfusion_event_sk, 0, 'ROUND_HALF_EVEN') AS transfusion_event_sk,
    fact_transfusion_product_detail.empi_text,
    ROUND(fact_transfusion_product_detail.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    fact_transfusion_product_detail.patient_market_urn,
    fact_transfusion_product_detail.medical_record_num,
    fact_transfusion_product_detail.age_sid,
    fact_transfusion_product_detail.age_num,
    fact_transfusion_product_detail.gender_sid,
    fact_transfusion_product_detail.patient_race_code,
    fact_transfusion_product_detail.drg_code,
    fact_transfusion_product_detail.drg_group_name,
    fact_transfusion_product_detail.drg_med_surg_ind,
    fact_transfusion_product_detail.drg_filter_text,
    ROUND(fact_transfusion_product_detail.attending_phys_dw_id, 0, 'ROUND_HALF_EVEN') AS attending_phys_dw_id,
    fact_transfusion_product_detail.attending_phys_num,
    fact_transfusion_product_detail.attending_phys_nppes_txmy_code,
    fact_transfusion_product_detail.attending_phy_specialty_desc,
    ROUND(fact_transfusion_product_detail.admitting_phys_dw_id, 0, 'ROUND_HALF_EVEN') AS admitting_phys_dw_id,
    ROUND(fact_transfusion_product_detail.consulting_phys_dw_id, 0, 'ROUND_HALF_EVEN') AS consulting_phys_dw_id,
    ROUND(fact_transfusion_product_detail.hospitalist_phys_dw_id, 0, 'ROUND_HALF_EVEN') AS hospitalist_phys_dw_id,
    ROUND(fact_transfusion_product_detail.ordering_phys_dw_id, 0, 'ROUND_HALF_EVEN') AS ordering_phys_dw_id,
    fact_transfusion_product_detail.ordering_phys_num,
    fact_transfusion_product_detail.ordering_phy_practice_area_code,
    fact_transfusion_product_detail.ordering_phy_practice_area_desc,
    fact_transfusion_product_detail.admission_date,
    fact_transfusion_product_detail.discharge_date,
    fact_transfusion_product_detail.length_of_stay_cnt,
    fact_transfusion_product_detail.final_billed_date,
    ROUND(fact_transfusion_product_detail.final_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS final_billed_charge_amt,
    fact_transfusion_product_detail.admission_source_sid,
    fact_transfusion_product_detail.admission_patient_type_code,
    fact_transfusion_product_detail.arrival_mode_code,
    fact_transfusion_product_detail.discharge_status_sid,
    fact_transfusion_product_detail.patient_type_code_pos1,
    fact_transfusion_product_detail.admitting_diagnosis_code,
    fact_transfusion_product_detail.admitting_diagnosis_type_code,
    fact_transfusion_product_detail.principal_diagnosis_code,
    fact_transfusion_product_detail.principal_diagnosis_type_code,
    fact_transfusion_product_detail.principal_procedure_code,
    fact_transfusion_product_detail.principal_procedure_type_code,
    fact_transfusion_product_detail.mortality_sw,
    fact_transfusion_product_detail.adverse_event_sw,
    fact_transfusion_product_detail.adverse_diagnosis_code,
    fact_transfusion_product_detail.org_coid_sid,
    fact_transfusion_product_detail.unit_num,
    fact_transfusion_product_detail.sub_unit_num,
    fact_transfusion_product_detail.lob_sid,
    fact_transfusion_product_detail.company_code,
    fact_transfusion_product_detail.coid,
    fact_transfusion_product_detail.transfusion_start_date_time,
    fact_transfusion_product_detail.transfusion_end_date_time,
    fact_transfusion_product_detail.event_sw,
    ROUND(fact_transfusion_product_detail.point_of_care_location_sk, 0, 'ROUND_HALF_EVEN') AS point_of_care_location_sk,
    fact_transfusion_product_detail.blood_location_mnem_cs,
    fact_transfusion_product_detail.product_urn,
    fact_transfusion_product_detail.product_mnemonic,
    fact_transfusion_product_detail.product_name,
    fact_transfusion_product_detail.product_unit_num_text,
    fact_transfusion_product_detail.unit_status_code,
    fact_transfusion_product_detail.barcode_verified_ind,
    fact_transfusion_product_detail.product_blood_type_text,
    fact_transfusion_product_detail.product_expired_date_time,
    fact_transfusion_product_detail.transfusion_issued_date_time,
    fact_transfusion_product_detail.transfusion_status_date_time,
    fact_transfusion_product_detail.pre_hgb_lab_test_date_time,
    ROUND(fact_transfusion_product_detail.pre_hgb_lab_test_val, 4, 'ROUND_HALF_EVEN') AS pre_hgb_lab_test_val,
    fact_transfusion_product_detail.pre_hgb_product_mnemonic_cs,
    fact_transfusion_product_detail.pre_hgb_six_hr_sw,
    fact_transfusion_product_detail.pre_hgb_24_hr_sw,
    fact_transfusion_product_detail.pre_hgb_bucket_val,
    fact_transfusion_product_detail.post_hgb_six_hr_lab_test_date_time,
    ROUND(fact_transfusion_product_detail.post_hgb_six_hr_lab_test_val, 4, 'ROUND_HALF_EVEN') AS post_hgb_six_hr_lab_test_val,
    fact_transfusion_product_detail.post_hgb_six_hr_product_mnem_cs,
    fact_transfusion_product_detail.post_hgb_six_hr_sw,
    fact_transfusion_product_detail.post_hgb_six_hr_bucket_val,
    fact_transfusion_product_detail.post_hgb_24_hr_lab_test_date_time,
    ROUND(fact_transfusion_product_detail.post_hgb_24_hr_lab_test_val, 4, 'ROUND_HALF_EVEN') AS post_hgb_24_hr_lab_test_val,
    fact_transfusion_product_detail.post_hgb_24_hr_product_mnem_cs,
    fact_transfusion_product_detail.source_system_code,
    fact_transfusion_product_detail.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwcdm_base_views.fact_transfusion_product_detail
;
