-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_pms_detail_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.fact_pms_detail_eom AS SELECT
    fact_pms_detail_eom.claim_dw_id,
    fact_pms_detail_eom.coid,
    fact_pms_detail_eom.company_code,
    fact_pms_detail_eom.claim_src_sys_key,
    fact_pms_detail_eom.claim_line_src_sys_key,
    fact_pms_detail_eom.line_item_num,
    fact_pms_detail_eom.seq_num,
    fact_pms_detail_eom.gl_dept_num,
    fact_pms_detail_eom.practice_dw_id,
    fact_pms_detail_eom.patient_dw_id,
    fact_pms_detail_eom.encounter_dw_id,
    fact_pms_detail_eom.referring_provider_dw_id,
    fact_pms_detail_eom.rendering_provider_dw_id,
    fact_pms_detail_eom.claim_provider_dw_id,
    fact_pms_detail_eom.rev_claim_provider_dw_id,
    fact_pms_detail_eom.servicing_provider_dw_id,
    fact_pms_detail_eom.resource_provider_dw_id,
    fact_pms_detail_eom.supervising_provider_dw_id,
    fact_pms_detail_eom.primary_iplan_dw_id,
    fact_pms_detail_eom.secondary_iplan_dw_id,
    fact_pms_detail_eom.tertiary_iplan_dw_id,
    fact_pms_detail_eom.liability_owner_dw_id,
    fact_pms_detail_eom.liability_owner_type,
    fact_pms_detail_eom.liability_chng_date,
    fact_pms_detail_eom.claim_date,
    fact_pms_detail_eom.from_service_date,
    fact_pms_detail_eom.to_service_date,
    fact_pms_detail_eom.start_entry_date,
    fact_pms_detail_eom.end_entry_date,
    fact_pms_detail_eom.reporting_year,
    fact_pms_detail_eom.pos_code,
    fact_pms_detail_eom.tos_code,
    fact_pms_detail_eom.modifier_1_code,
    fact_pms_detail_eom.modifier_2_code,
    fact_pms_detail_eom.modifier_3_code,
    fact_pms_detail_eom.dx_1_code,
    fact_pms_detail_eom.dx_2_code,
    fact_pms_detail_eom.dx_3_code,
    fact_pms_detail_eom.dx_4_code,
    fact_pms_detail_eom.dhs_ind,
    fact_pms_detail_eom.pctc_ind,
    fact_pms_detail_eom.claim_line_deleted_sw,
    fact_pms_detail_eom.claim_deleted_sw,
    fact_pms_detail_eom.medicare_fee_sid,
    fact_pms_detail_eom.local_medicare_fee_sid,
    fact_pms_detail_eom.national_medicare_fee_sid,
    fact_pms_detail_eom.procedure_code,
    fact_pms_detail_eom.unit_qty,
    fact_pms_detail_eom.charge_amt,
    fact_pms_detail_eom.insurance_pmt_amt,
    fact_pms_detail_eom.patient_pmt_amt,
    fact_pms_detail_eom.adjustment_amt,
    fact_pms_detail_eom.contractual_adj_amt,
    fact_pms_detail_eom.denial_amt,
    fact_pms_detail_eom.claim_bal_amt,
    fact_pms_detail_eom.rvu_amt,
    fact_pms_detail_eom.rvu_adj_amt,
    fact_pms_detail_eom.wrvu_amt,
    fact_pms_detail_eom.wrvu_adj_amt,
    fact_pms_detail_eom.nonfac_prof_comp_pct,
    fact_pms_detail_eom.nonfac_tech_comp_pct,
    fact_pms_detail_eom.national_fee_sched_amt,
    fact_pms_detail_eom.local_fee_sched_amt,
    fact_pms_detail_eom.source_system_code,
    fact_pms_detail_eom.dw_last_update_date_time,
    fact_pms_detail_eom.locality_code,
    fact_pms_detail_eom.carrier_num
  FROM
    `hca-hin-dev-cur-parallon`.edwps_base_views.fact_pms_detail_eom
;
