-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_patient.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.fact_patient AS SELECT
    ROUND(fact_patient.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    fact_patient.company_code,
    fact_patient.coid,
    fact_patient.unit_num,
    fact_patient.sub_unit_num,
    fact_patient.admission_patient_type_code,
    ROUND(fact_patient.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    fact_patient.patient_type_code_pos1,
    fact_patient.admission_date,
    fact_patient.discharge_date,
    fact_patient.final_bill_date,
    ROUND(fact_patient.financial_class_code, 0, 'ROUND_HALF_EVEN') AS financial_class_code,
    fact_patient.account_status_code,
    fact_patient.admission_source_code,
    fact_patient.admission_type_code,
    fact_patient.drg_code_payor,
    fact_patient.drg_code_hcfa,
    fact_patient.drg_hcfa_icd10_code,
    fact_patient.drg_desc_hcfa,
    ROUND(fact_patient.drg_payment_weight_amt, 5, 'ROUND_HALF_EVEN') AS drg_payment_weight_amt,
    fact_patient.drg_code_classic,
    fact_patient.rdrg_code_pos4,
    fact_patient.social_security_num,
    ROUND(fact_patient.patient_person_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_person_dw_id,
    fact_patient.patient_empi_num,
    fact_patient.patient_discharge_month_age,
    ROUND(fact_patient.patient_address_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_address_dw_id,
    fact_patient.patient_zip_code,
    fact_patient.resp_party_zip_code,
    ROUND(fact_patient.employer_dw_id, 0, 'ROUND_HALF_EVEN') AS employer_dw_id,
    fact_patient.facility_physician_num_attend,
    fact_patient.facility_physician_num_admit,
    fact_patient.facility_physician_num_pcp,
    ROUND(fact_patient.payor_dw_id_ins1, 0, 'ROUND_HALF_EVEN') AS payor_dw_id_ins1,
    fact_patient.iplan_id_ins1,
    ROUND(fact_patient.ins_contract_id_ins1, 0, 'ROUND_HALF_EVEN') AS ins_contract_id_ins1,
    ROUND(fact_patient.major_payor_id_ins1, 0, 'ROUND_HALF_EVEN') AS major_payor_id_ins1,
    fact_patient.masterfacts_schema_id,
    fact_patient.ins_product_code_ins1,
    fact_patient.ins_product_name_ins1,
    fact_patient.sub_payor_group_code,
    ROUND(fact_patient.payor_dw_id_ins2, 0, 'ROUND_HALF_EVEN') AS payor_dw_id_ins2,
    fact_patient.iplan_id_ins2,
    ROUND(fact_patient.payor_dw_id_ins3, 0, 'ROUND_HALF_EVEN') AS payor_dw_id_ins3,
    fact_patient.iplan_id_ins3,
    fact_patient.calculated_los,
    ROUND(fact_patient.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
    ROUND(fact_patient.total_billed_charges, 3, 'ROUND_HALF_EVEN') AS total_billed_charges,
    ROUND(fact_patient.total_anc_charges, 3, 'ROUND_HALF_EVEN') AS total_anc_charges,
    ROUND(fact_patient.total_rb_charges, 3, 'ROUND_HALF_EVEN') AS total_rb_charges,
    ROUND(fact_patient.total_payments, 3, 'ROUND_HALF_EVEN') AS total_payments,
    ROUND(fact_patient.total_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_adjustment_amt,
    ROUND(fact_patient.total_contract_allow_amt, 3, 'ROUND_HALF_EVEN') AS total_contract_allow_amt,
    ROUND(fact_patient.total_write_off_bad_debt_amt, 3, 'ROUND_HALF_EVEN') AS total_write_off_bad_debt_amt,
    ROUND(fact_patient.total_write_off_other_amt, 3, 'ROUND_HALF_EVEN') AS total_write_off_other_amt,
    ROUND(fact_patient.total_write_off_other_adj_amt, 3, 'ROUND_HALF_EVEN') AS total_write_off_other_adj_amt,
    ROUND(fact_patient.total_uninsured_discount_amt, 3, 'ROUND_HALF_EVEN') AS total_uninsured_discount_amt,
    fact_patient.last_write_off_date,
    ROUND(fact_patient.total_charity_write_off_amt, 3, 'ROUND_HALF_EVEN') AS total_charity_write_off_amt,
    fact_patient.last_charity_write_off_date,
    ROUND(fact_patient.total_patient_liability_amt, 3, 'ROUND_HALF_EVEN') AS total_patient_liability_amt,
    ROUND(fact_patient.total_patient_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_patient_payment_amt,
    fact_patient.last_patient_payment_date,
    fact_patient.exempt_indicator,
    fact_patient.casemix_exempt_indicator,
    ROUND(fact_patient.expected_pmt, 3, 'ROUND_HALF_EVEN') AS expected_pmt,
    fact_patient.primary_icd_version_code,
    fact_patient.diag_code_admit,
    fact_patient.diag_code_final,
    fact_patient.proc_code_01,
    fact_patient.proc_code_02,
    fact_patient.proc_code_03,
    fact_patient.proc_code_04,
    fact_patient.proc_code_05,
    fact_patient.proc_code_06,
    fact_patient.proc_code_07,
    fact_patient.proc_code_08,
    fact_patient.proc_code_09,
    fact_patient.proc_code_10,
    fact_patient.proc_code_11,
    fact_patient.proc_code_12,
    fact_patient.proc_code_13,
    fact_patient.proc_code_14,
    fact_patient.proc_code_15,
    fact_patient.icd10_diag_admit_code,
    fact_patient.icd10_diag_final_code,
    fact_patient.icd10_proc_code_01,
    fact_patient.icd10_proc_code_02,
    fact_patient.icd10_proc_code_03,
    fact_patient.icd10_proc_code_04,
    fact_patient.icd10_proc_code_05,
    fact_patient.icd10_proc_code_06,
    fact_patient.icd10_proc_code_07,
    fact_patient.icd10_proc_code_08,
    fact_patient.icd10_proc_code_09,
    fact_patient.icd10_proc_code_10,
    fact_patient.icd10_proc_code_11,
    fact_patient.icd10_proc_code_12,
    fact_patient.icd10_proc_code_13,
    fact_patient.icd10_proc_code_14,
    fact_patient.icd10_proc_code_15,
    fact_patient.dss_op_cpt_hier,
    fact_patient.aps_op_cpt_reimb_hier_id,
    fact_patient.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpf_base_views.fact_patient
;
