-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/mcare_bad_debt_crossover_dtl.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.mcare_bad_debt_crossover_dtl
   OPTIONS(description='This table contains all the relevant information on the  accounts having Medicare responsibility.')
  AS SELECT
      mcare_bad_debt_crossover_dtl.reporting_date,
      ROUND(mcare_bad_debt_crossover_dtl.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      mcare_bad_debt_crossover_dtl.company_code,
      mcare_bad_debt_crossover_dtl.coid,
      mcare_bad_debt_crossover_dtl.unit_num,
      ROUND(mcare_bad_debt_crossover_dtl.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      mcare_bad_debt_crossover_dtl.admission_date,
      mcare_bad_debt_crossover_dtl.discharge_date,
      mcare_bad_debt_crossover_dtl.final_bill_date,
      mcare_bad_debt_crossover_dtl.reason_desc,
      mcare_bad_debt_crossover_dtl.account_payer_status_desc,
      mcare_bad_debt_crossover_dtl.project_name,
      mcare_bad_debt_crossover_dtl.account_status_code,
      mcare_bad_debt_crossover_dtl.patient_type_code,
      mcare_bad_debt_crossover_dtl.iplan_id_ins1,
      mcare_bad_debt_crossover_dtl.iplan_id_ins2,
      mcare_bad_debt_crossover_dtl.iplan_id_ins3,
      mcare_bad_debt_crossover_dtl.plan_desc_ins1,
      ROUND(mcare_bad_debt_crossover_dtl.plan_desc_ins2, 0, 'ROUND_HALF_EVEN') AS plan_desc_ins2,
      mcare_bad_debt_crossover_dtl.plan_desc_ins3,
      ROUND(mcare_bad_debt_crossover_dtl.financial_class_code_ins1, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins1,
      ROUND(mcare_bad_debt_crossover_dtl.financial_class_code_ins2, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins2,
      ROUND(mcare_bad_debt_crossover_dtl.financial_class_code_ins3, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins3,
      mcare_bad_debt_crossover_dtl.bill_code_ins1,
      mcare_bad_debt_crossover_dtl.bill_code_ins2,
      mcare_bad_debt_crossover_dtl.bill_code_ins3,
      mcare_bad_debt_crossover_dtl.procedure_code,
      ROUND(mcare_bad_debt_crossover_dtl.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
      ROUND(mcare_bad_debt_crossover_dtl.total_expt_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_expt_payment_amt,
      ROUND(mcare_bad_debt_crossover_dtl.total_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_payment_amt,
      ROUND(mcare_bad_debt_crossover_dtl.total_variance_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_variance_adjustment_amt,
      ROUND(mcare_bad_debt_crossover_dtl.total_pat_responsibility_amt, 3, 'ROUND_HALF_EVEN') AS total_pat_responsibility_amt,
      ROUND(mcare_bad_debt_crossover_dtl.primary_mcare_responsibility_amt, 3, 'ROUND_HALF_EVEN') AS primary_mcare_responsibility_amt,
      ROUND(mcare_bad_debt_crossover_dtl.patient_payment_amt, 3, 'ROUND_HALF_EVEN') AS patient_payment_amt,
      ROUND(mcare_bad_debt_crossover_dtl.primary_payment_amt, 3, 'ROUND_HALF_EVEN') AS primary_payment_amt,
      ROUND(mcare_bad_debt_crossover_dtl.secondary_payment_amt, 3, 'ROUND_HALF_EVEN') AS secondary_payment_amt,
      mcare_bad_debt_crossover_dtl.latest_primary_payment_date,
      mcare_bad_debt_crossover_dtl.ep_payment_create_date,
      mcare_bad_debt_crossover_dtl.ep_payment_effective_post_date,
      mcare_bad_debt_crossover_dtl.era_create_date,
      mcare_bad_debt_crossover_dtl.check_date,
      mcare_bad_debt_crossover_dtl.service_carc_claim_carc_flag,
      mcare_bad_debt_crossover_dtl.service_carc_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_23_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_45_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_97_ind,
      mcare_bad_debt_crossover_dtl.calc_claim_carc_23_45_97_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_23_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_45_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_97_ind,
      mcare_bad_debt_crossover_dtl.addl_service_carc_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_22_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_26_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_27_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_29_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_31_ind,
      mcare_bad_debt_crossover_dtl.service_carc_denial_cd_109_ind,
      mcare_bad_debt_crossover_dtl.calc_addl_claim_carc_ind,
      mcare_bad_debt_crossover_dtl.addl_claim_carc_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_22_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_26_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_27_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_29_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_31_ind,
      mcare_bad_debt_crossover_dtl.claim_carc_denial_cd_109_ind,
      mcare_bad_debt_crossover_dtl.source_system_code,
      mcare_bad_debt_crossover_dtl.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.mcare_bad_debt_crossover_dtl
  ;
