-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/payment_compliance_appeal_asst_inventory.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.payment_compliance_appeal_asst_inventory
   OPTIONS(description='Denials and Appeals Inventory from Appeal Assistant tool for corporate payment compliance reporting and reconciliation')
  AS SELECT
      ROUND(payment_compliance_appeal_asst_inventory.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      payment_compliance_appeal_asst_inventory.last_appeal_attempt_key_num,
      payment_compliance_appeal_asst_inventory.appeal_form_downloaded_flag,
      payment_compliance_appeal_asst_inventory.reporting_date,
      payment_compliance_appeal_asst_inventory.inventory_date,
      payment_compliance_appeal_asst_inventory.appeal_status_desc,
      payment_compliance_appeal_asst_inventory.appeal_level_num,
      payment_compliance_appeal_asst_inventory.iplan_id,
      payment_compliance_appeal_asst_inventory.iplan_insurance_order_num,
      payment_compliance_appeal_asst_inventory.major_payor_group_id,
      payment_compliance_appeal_asst_inventory.coid,
      payment_compliance_appeal_asst_inventory.company_code,
      ROUND(payment_compliance_appeal_asst_inventory.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      payment_compliance_appeal_asst_inventory.unit_num,
      payment_compliance_appeal_asst_inventory.patient_type_code,
      payment_compliance_appeal_asst_inventory.meditech_acct_num,
      payment_compliance_appeal_asst_inventory.appeal_disp_desc,
      payment_compliance_appeal_asst_inventory.denial_code,
      payment_compliance_appeal_asst_inventory.denial_code_group_name,
      payment_compliance_appeal_asst_inventory.denial_src_system_code,
      payment_compliance_appeal_asst_inventory.service_code,
      payment_compliance_appeal_asst_inventory.denial_key_num,
      payment_compliance_appeal_asst_inventory.denial_src_disp_desc,
      payment_compliance_appeal_asst_inventory.appeal_rule_key_num,
      payment_compliance_appeal_asst_inventory.appeal_rule_id,
      payment_compliance_appeal_asst_inventory.patient_full_name,
      payment_compliance_appeal_asst_inventory.patient_birth_date,
      ROUND(payment_compliance_appeal_asst_inventory.payor_financial_class_code, 0, 'ROUND_HALF_EVEN') AS payor_financial_class_code,
      payment_compliance_appeal_asst_inventory.claim_id,
      payment_compliance_appeal_asst_inventory.hic_claim_num,
      payment_compliance_appeal_asst_inventory.application_name,
      payment_compliance_appeal_asst_inventory.appeal_folder_status,
      payment_compliance_appeal_asst_inventory.appeal_key_num,
      payment_compliance_appeal_asst_inventory.appeal_workflow_comment,
      payment_compliance_appeal_asst_inventory.appeal_guid,
      payment_compliance_appeal_asst_inventory.appeal_evnt_error_desc,
      payment_compliance_appeal_asst_inventory.appeal_evnt_error_reason_desc,
      payment_compliance_appeal_asst_inventory.src_appeal_num,
      payment_compliance_appeal_asst_inventory.onbase_document_id,
      payment_compliance_appeal_asst_inventory.acct_selected_ind,
      payment_compliance_appeal_asst_inventory.hpf_acct_ind,
      payment_compliance_appeal_asst_inventory.hpf_page_total_num,
      payment_compliance_appeal_asst_inventory.acct_sent_to_print_ind,
      payment_compliance_appeal_asst_inventory.sent_to_print_page_total_num,
      payment_compliance_appeal_asst_inventory.acct_confirmed_print_ind,
      payment_compliance_appeal_asst_inventory.confirmed_print_page_total_num,
      payment_compliance_appeal_asst_inventory.acct_onbase_upload_ind,
      payment_compliance_appeal_asst_inventory.onbase_upload_page_total_num,
      payment_compliance_appeal_asst_inventory.hpf_required_ind,
      payment_compliance_appeal_asst_inventory.hpf_downloaded_flag,
      payment_compliance_appeal_asst_inventory.hpf_page_cnt,
      ROUND(payment_compliance_appeal_asst_inventory.appeal_amt, 3, 'ROUND_HALF_EVEN') AS appeal_amt,
      ROUND(payment_compliance_appeal_asst_inventory.denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS denied_charge_amt,
      ROUND(payment_compliance_appeal_asst_inventory.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      payment_compliance_appeal_asst_inventory.account_processed_cnt,
      payment_compliance_appeal_asst_inventory.appeal_level_origination_date_time,
      payment_compliance_appeal_asst_inventory.appeal_origination_date,
      payment_compliance_appeal_asst_inventory.admission_date,
      payment_compliance_appeal_asst_inventory.discharge_date,
      payment_compliance_appeal_asst_inventory.onbase_upload_date_time,
      payment_compliance_appeal_asst_inventory.sent_to_print_date_time,
      payment_compliance_appeal_asst_inventory.confirmed_print_date_time,
      payment_compliance_appeal_asst_inventory.appeal_evnt_modified_date_time,
      payment_compliance_appeal_asst_inventory.appeal_evnt_type_key_num,
      payment_compliance_appeal_asst_inventory.appeal_evnt_log_key_num,
      payment_compliance_appeal_asst_inventory.appeal_status_modified_date_time,
      payment_compliance_appeal_asst_inventory.appeal_evnt_error_date_time,
      payment_compliance_appeal_asst_inventory.appeal_evnt_error_category_name,
      payment_compliance_appeal_asst_inventory.appeal_rule_template_name,
      payment_compliance_appeal_asst_inventory.template_download_date_time,
      payment_compliance_appeal_asst_inventory.hpf_selection_date_time,
      payment_compliance_appeal_asst_inventory.hpf_download_date_time,
      payment_compliance_appeal_asst_inventory.appeal_form_viewed_date_time,
      payment_compliance_appeal_asst_inventory.appeal_form_download_date_time,
      payment_compliance_appeal_asst_inventory.appeal_created_by_user_id,
      payment_compliance_appeal_asst_inventory.appeal_created_date_time,
      payment_compliance_appeal_asst_inventory.appeal_uploaded_date_time,
      payment_compliance_appeal_asst_inventory.appeal_uploaded_by_user_id,
      payment_compliance_appeal_asst_inventory.template_download_by_user_id,
      payment_compliance_appeal_asst_inventory.source_system_code,
      payment_compliance_appeal_asst_inventory.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.payment_compliance_appeal_asst_inventory
  ;
