-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/payor_audit_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.payor_audit_detail
   OPTIONS(description='Table that captures the Patient Account details and Audit information that is requested for all accounts by Payors and tracked in application during our billing cycles.')
  AS SELECT
      payor_audit_detail.audit_record_sid,
      ROUND(payor_audit_detail.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      payor_audit_detail.reporting_date,
      payor_audit_detail.daily_month_code,
      payor_audit_detail.account_create_timestamp,
      payor_audit_detail.appeal_create_timestamp,
      payor_audit_detail.doc_ctrl_num,
      payor_audit_detail.last_appeal_update_timestamp,
      payor_audit_detail.last_appeal_update_user_id,
      payor_audit_detail.work_queue_desc,
      payor_audit_detail.company_code,
      payor_audit_detail.coid,
      payor_audit_detail.unit_num,
      ROUND(payor_audit_detail.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      payor_audit_detail.month_id,
      payor_audit_detail.audit_create_date,
      payor_audit_detail.audit_create_user_id,
      payor_audit_detail.financial_class_code,
      payor_audit_detail.major_payor_code,
      payor_audit_detail.insurance_order_num,
      payor_audit_detail.iplan_id,
      payor_audit_detail.letter_date,
      payor_audit_detail.category_desc,
      payor_audit_detail.worklist_desc,
      payor_audit_detail.workflow_type_desc,
      payor_audit_detail.audit_start_date,
      payor_audit_detail.audit_initiation_date,
      payor_audit_detail.medical_rec_requestor_entity_desc,
      payor_audit_detail.audit_type_desc,
      payor_audit_detail.other_audit_desc,
      payor_audit_detail.service_start_date,
      payor_audit_detail.service_end_date,
      payor_audit_detail.medical_record_due_date,
      payor_audit_detail.audit_location_desc,
      payor_audit_detail.audit_eligibility_desc,
      payor_audit_detail.audit_fee_required_ind,
      payor_audit_detail.previous_audit_status_desc,
      payor_audit_detail.audit_work_queue_desc,
      payor_audit_detail.audit_status_desc,
      payor_audit_detail.audit_status_date,
      payor_audit_detail.last_audit_status_update_date,
      payor_audit_detail.last_audit_status_update_user_id,
      payor_audit_detail.post_audit_type_desc,
      payor_audit_detail.work_again_date,
      payor_audit_detail.corporate_status_desc,
      payor_audit_detail.corporate_status_date,
      payor_audit_detail.letter_result_desc,
      payor_audit_detail.final_audit_outcome_desc,
      payor_audit_detail.final_audit_outcome_date,
      payor_audit_detail.corp_doc_control_code,
      payor_audit_detail.ssc_doc_control_code,
      payor_audit_detail.missing_doc_cnt,
      payor_audit_detail.audit_schedule_date,
      payor_audit_detail.medical_rec_release_method_desc,
      payor_audit_detail.medical_rec_tracking_num,
      payor_audit_detail.medical_rec_release_request_date,
      payor_audit_detail.medical_rec_sent_date,
      payor_audit_detail.medical_rec_missing_notification_date,
      payor_audit_detail.payor_reference_id,
      ROUND(payor_audit_detail.collected_audit_fee_amt, 3, 'ROUND_HALF_EVEN') AS collected_audit_fee_amt,
      payor_audit_detail.additional_project_name,
      payor_audit_detail.recurring_account_sw,
      ROUND(payor_audit_detail.risk_amt, 3, 'ROUND_HALF_EVEN') AS risk_amt,
      ROUND(payor_audit_detail.charge_reviewed_amt, 3, 'ROUND_HALF_EVEN') AS charge_reviewed_amt,
      ROUND(payor_audit_detail.current_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS current_total_charge_amt,
      ROUND(payor_audit_detail.current_total_charge_discrepancy_amt, 3, 'ROUND_HALF_EVEN') AS current_total_charge_discrepancy_amt,
      ROUND(payor_audit_detail.expected_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS expected_payor_payment_amt,
      ROUND(payor_audit_detail.current_payor_payment_discrepancy_amt, 3, 'ROUND_HALF_EVEN') AS current_payor_payment_discrepancy_amt,
      ROUND(payor_audit_detail.initial_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS initial_payor_payment_amt,
      ROUND(payor_audit_detail.current_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS current_payor_payment_amt,
      payor_audit_detail.pre_audit_drg_code,
      payor_audit_detail.pre_audit_drg_desc,
      payor_audit_detail.payor_drg_code,
      payor_audit_detail.payer_drg_desc,
      payor_audit_detail.claim_guid,
      payor_audit_detail.post_audit_drg,
      payor_audit_detail.post_audit_drg_desc,
      payor_audit_detail.appeal_create_user_id,
      payor_audit_detail.appeal_level_1_due_date,
      payor_audit_detail.appeal_level_1_letter_sent_date,
      payor_audit_detail.appeal_level_1_followup_date,
      payor_audit_detail.appeal_level_1_response_date,
      payor_audit_detail.appeal_level_1_decision_desc,
      payor_audit_detail.appeal_level_2_due_date,
      payor_audit_detail.appeal_level_2_letter_sent_date,
      payor_audit_detail.appeal_level_2_followup_date,
      payor_audit_detail.appeal_level_2_response_date,
      payor_audit_detail.appeal_level_2_decision_desc,
      payor_audit_detail.appeal_level_3_due_date,
      payor_audit_detail.appeal_level_3_letter_sent_date,
      payor_audit_detail.appeal_level_3_followup_date,
      payor_audit_detail.appeal_level_3_response_date,
      payor_audit_detail.appeal_level_3_decision_desc,
      payor_audit_detail.appeal_level_4_due_date,
      payor_audit_detail.appeal_level_4_letter_sent_date,
      payor_audit_detail.appeal_level_4_followup_date,
      payor_audit_detail.appeal_level_4_response_date,
      payor_audit_detail.appeal_level_4_decision_desc,
      payor_audit_detail.appeal_level_5_due_date,
      payor_audit_detail.appeal_level_5_letter_sent_date,
      payor_audit_detail.appeal_level_5_followup_date,
      payor_audit_detail.appeal_level_5_response_date,
      payor_audit_detail.appeal_level_5_decision_desc,
      payor_audit_detail.source_system_code,
      payor_audit_detail.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.payor_audit_detail
  ;
