-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/physician_current.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.physician_current AS SELECT
    ROUND(physician_current.hcp_dw_id, 0, 'ROUND_HALF_EVEN') AS hcp_dw_id,
    physician_current.gl_provider_dept_num,
    physician_current.coid,
    physician_current.company_code,
    physician_current.ancillary_dept_num,
    physician_current.assigned_start_date,
    physician_current.budget_coid,
    physician_current.budget_oh_dept_num,
    physician_current.budget_start_date,
    physician_current.coid_dept_name,
    physician_current.coid_dept_start_date,
    physician_current.coid_dept_term_date,
    physician_current.coid_start_date,
    physician_current.community_status,
    physician_current.compensation_type,
    physician_current.src_sys_compensation_type_key,
    physician_current.contract_expiration_date,
    physician_current.contract_renewal_date,
    physician_current.development_type_name,
    physician_current.src_sys_development_key,
    physician_current.birth_date,
    physician_current.effective_date,
    physician_current.provider_first_name,
    ROUND(physician_current.fte, 3, 'ROUND_HALF_EVEN') AS fte,
    physician_current.is_budget_ind,
    physician_current.is_hospitalist_ind,
    physician_current.is_multiple_provider_dept_ind,
    physician_current.provider_last_name,
    physician_current.provider_middle_initial,
    physician_current.new_replaced_ind,
    physician_current.new_replaced_name,
    physician_current.overhead_allocation,
    physician_current.original_start_date,
    ROUND(physician_current.npi, 3, 'ROUND_HALF_EVEN') AS npi,
    physician_current.practice_address_1,
    physician_current.practice_address_2,
    physician_current.practice_city,
    physician_current.practice_fax,
    physician_current.practice_manager_first_name,
    physician_current.practice_manager_last_name,
    physician_current.practice_name,
    physician_current.src_sys_practice_num,
    physician_current.practice_phone,
    physician_current.practice_state,
    physician_current.practice_zip,
    physician_current.projected_termination_date,
    physician_current.provider_head_count,
    physician_current.src_sys_provider_key,
    physician_current.relationship_ind,
    physician_current.social_security_num,
    physician_current.specialty_code,
    physician_current.specialty_name,
    physician_current.specialty_type,
    physician_current.termination_reason_name,
    physician_current.termination_type_name,
    physician_current.termination_type_id,
    physician_current.termination_results,
    physician_current.upin,
    physician_current.status,
    physician_current.pe_date,
    physician_current.data_source_code,
    physician_current.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwps_base_views.physician_current
;
