-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/prebill_denial_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.prebill_denial_detail
   OPTIONS(description='PreBill Denial Inventory for Parallon Customers. This is will have a monthly data and daily data for 7 days rolling.')
  AS SELECT
      prebill_denial_detail.company_code,
      prebill_denial_detail.coid,
      prebill_denial_detail.rptg_date,
      prebill_denial_detail.account_id,
      ROUND(prebill_denial_detail.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      prebill_denial_detail.unit_num,
      prebill_denial_detail.facility_tax_id,
      prebill_denial_detail.med_rec_num,
      prebill_denial_detail.birth_date,
      prebill_denial_detail.admit_date,
      prebill_denial_detail.discharge_date,
      prebill_denial_detail.provider_num_code,
      prebill_denial_detail.work_group_id,
      prebill_denial_detail.work_group_name,
      ROUND(prebill_denial_detail.financial_class_code, 0, 'ROUND_HALF_EVEN') AS financial_class_code,
      ROUND(prebill_denial_detail.national_provider_id, 0, 'ROUND_HALF_EVEN') AS national_provider_id,
      prebill_denial_detail.iplan_ins1_id,
      prebill_denial_detail.iplan_id_ins1_name,
      prebill_denial_detail.iplan_ins2_id,
      prebill_denial_detail.iplan_id_ins2_name,
      prebill_denial_detail.pdu_initiated_date,
      prebill_denial_detail.status_code,
      prebill_denial_detail.status_desc,
      prebill_denial_detail.final_bill_date,
      prebill_denial_detail.bill_hold_start_date,
      prebill_denial_detail.bill_hold_end_date,
      prebill_denial_detail.xu_date,
      prebill_denial_detail.physician_advisor_vendor_name,
      prebill_denial_detail.denial_record_code,
      prebill_denial_detail.auth_code,
      prebill_denial_detail.auth_type_code,
      prebill_denial_detail.auth_date,
      prebill_denial_detail.initial_auth_status_code,
      prebill_denial_detail.current_deadline_date,
      prebill_denial_detail.certification_end_date,
      prebill_denial_detail.admitting_physician_name,
      prebill_denial_detail.attending_physician_name,
      ROUND(prebill_denial_detail.attending_physician_tax_id, 0, 'ROUND_HALF_EVEN') AS attending_physician_tax_id,
      prebill_denial_detail.service_code,
      prebill_denial_detail.admitting_dx_code,
      prebill_denial_detail.rebill_requested_date,
      prebill_denial_detail.review_reason1_desc,
      prebill_denial_detail.review_reason2_desc,
      prebill_denial_detail.review_reason3_desc,
      prebill_denial_detail.review_reason4_desc,
      prebill_denial_detail.denial_reason1_desc,
      prebill_denial_detail.denial_reason2_desc,
      prebill_denial_detail.denial_reason3_desc,
      prebill_denial_detail.denial_reason4_desc,
      prebill_denial_detail.root_cause1_desc,
      prebill_denial_detail.root_cause2_desc,
      prebill_denial_detail.root_cause3_desc,
      prebill_denial_detail.root_cause4_desc,
      prebill_denial_detail.pdu_iqreview1_ind,
      prebill_denial_detail.pdu_iqreview2_ind,
      prebill_denial_detail.pdu_iqreview3_ind,
      prebill_denial_detail.pdu_iqreview4_ind,
      prebill_denial_detail.agreed1_ind,
      prebill_denial_detail.agreed2_ind,
      prebill_denial_detail.agreed3_ind,
      prebill_denial_detail.agreed4_ind,
      prebill_denial_detail.sum_day_cnt,
      prebill_denial_detail.final_day_denied_cnt,
      ROUND(prebill_denial_detail.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      ROUND(prebill_denial_detail.expected_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS expected_reimbursement_amt,
      ROUND(prebill_denial_detail.actual_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS actual_reimbursement_amt,
      prebill_denial_detail.determination_reason_code,
      prebill_denial_detail.determination_reason_desc,
      prebill_denial_detail.alos_day_cnt,
      prebill_denial_detail.no_certification_required_cnt,
      prebill_denial_detail.ssc_certed_day_cnt,
      prebill_denial_detail.cm_certed_day_cnt,
      prebill_denial_detail.post_discharge_day_cnt,
      prebill_denial_detail.inhouse_final_denied_day_cnt,
      prebill_denial_detail.post_discharge_overturned_day_cnt,
      prebill_denial_detail.denial_revenue_day1_cnt,
      prebill_denial_detail.denial_revenue_day2_cnt,
      prebill_denial_detail.denial_revenue_day3_cnt,
      prebill_denial_detail.denial_revenue_day4_cnt,
      prebill_denial_detail.total_approved_day_cnt,
      prebill_denial_detail.total_denied_day_cnt,
      prebill_denial_detail.ptp_outcome_desc,
      prebill_denial_detail.ptp_requested_date,
      prebill_denial_detail.final_case_closure_date,
      prebill_denial_detail.clinical_submitted_note_desc,
      prebill_denial_detail.clinical_submitted_date,
      prebill_denial_detail.payor_response_desc,
      prebill_denial_detail.denial_reconsideration_response,
      prebill_denial_detail.reconsideration_submit_date,
      prebill_denial_detail.interqual_completed_ind,
      prebill_denial_detail.analyst_reviewed_date,
      prebill_denial_detail.analyst_payor_contact_date,
      prebill_denial_detail.analyst_work_again_date,
      prebill_denial_detail.analyst_worked_user_id,
      prebill_denial_detail.nurse_initial_review_date,
      prebill_denial_detail.nurse_payor_contact_date,
      prebill_denial_detail.nurse_work_again_date,
      prebill_denial_detail.nurse_worked_user_id,
      prebill_denial_detail.denial_initial_review_date,
      prebill_denial_detail.denial_payor_contact_date,
      prebill_denial_detail.denial_work_again_date,
      prebill_denial_detail.denial_worked_user_id,
      prebill_denial_detail.verified_user_id,
      prebill_denial_detail.verification_date,
      prebill_denial_detail.modified_date,
      prebill_denial_detail.modified_user_id,
      prebill_denial_detail.created_date,
      prebill_denial_detail.created_user_id,
      prebill_denial_detail.assigned_user_id,
      prebill_denial_detail.manual_review_reason_desc,
      prebill_denial_detail.ar_status_code,
      prebill_denial_detail.denial_probability_desc,
      prebill_denial_detail.pilot_acct_ind,
      prebill_denial_detail.pilot_acct_user_review_1_txt,
      prebill_denial_detail.pilot_acct_user_review_2_txt,
      prebill_denial_detail.pilot_acct_user_review_3_txt,
      prebill_denial_detail.pilot_acct_user_review_4_txt
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.prebill_denial_detail
  ;
