-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/registration_iplan_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.registration_iplan_pf AS SELECT
    ROUND(registration_iplan.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(registration_iplan.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    registration_iplan.iplan_insurance_order_num,
    registration_iplan.payor_name,
    registration_iplan.payor_mail_to_name,
    registration_iplan.coid,
    registration_iplan.company_code,
    registration_iplan.iplan_id,
    registration_iplan.eff_from_date,
    registration_iplan.eff_to_date,
    ROUND(registration_iplan.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    registration_iplan.person_role_code,
    registration_iplan.pat_relationship_to_ins_code,
    registration_iplan.policy_num,
    registration_iplan.group_name,
    registration_iplan.group_num,
    registration_iplan.hic_claim_num,
    registration_iplan.signed_pat_rel_on_file_ind,
    registration_iplan.signed_assn_benf_on_file_ind,
    registration_iplan.treatment_authorization_num,
    registration_iplan.verification_date,
    registration_iplan.precertification_date,
    registration_iplan.recertification_day_count,
    registration_iplan.edit_code,
    registration_iplan.dependent_maximum_age_num,
    registration_iplan.student_max_age_num,
    ROUND(registration_iplan.deductible_amt, 3, 'ROUND_HALF_EVEN') AS deductible_amt,
    ROUND(registration_iplan.coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS coinsurance_amt,
    registration_iplan.source_system_code,
    registration_iplan.dw_load_date,
    registration_iplan.dw_change_date,
    registration_iplan.health_plan_patient_id,
    registration_iplan.health_plan_id,
    registration_iplan.auto_post_ind,
    ROUND(registration_iplan.gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS gross_reimbursement_amt,
    registration_iplan.gross_reimbursement_date,
    ROUND(registration_iplan.expected_contractual_amt, 3, 'ROUND_HALF_EVEN') AS expected_contractual_amt,
    registration_iplan.expected_contractual_date,
    registration_iplan.coins_amt_source_ind,
    ROUND(registration_iplan.calc_coins_amt, 3, 'ROUND_HALF_EVEN') AS calc_coins_amt,
    registration_iplan.calc_coins_amt_source_ind,
    registration_iplan.calc_coins_date,
    ROUND(registration_iplan.gross_reimbursement_var_amt, 3, 'ROUND_HALF_EVEN') AS gross_reimbursement_var_amt,
    registration_iplan.gross_reimbursement_var_date,
    ROUND(registration_iplan.partb_professional_fee_amt, 3, 'ROUND_HALF_EVEN') AS partb_professional_fee_amt,
    ROUND(registration_iplan.blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS blood_deductible_amt,
    registration_iplan.outpatient_pps_flag_tricare,
    registration_iplan.outpatient_pps_flag,
    registration_iplan.irf_flag,
    registration_iplan.snf_flag,
    registration_iplan.psych_flag,
    registration_iplan.log_format_ind,
    ROUND(registration_iplan.non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS non_covered_charge_amt,
    ROUND(registration_iplan.copay_amt, 3, 'ROUND_HALF_EVEN') AS copay_amt,
    ROUND(registration_iplan.auto_post_amt, 3, 'ROUND_HALF_EVEN') AS auto_post_amt,
    registration_iplan.major_payor_group_id,
    registration_iplan.ub04_pat_relation_to_ins_code,
    registration_iplan.medicare_inpatient_outlier_ind,
    registration_iplan.precertification_ind,
    registration_iplan.icn
  FROM
    `hca-hin-dev-cur-parallon`.edwpf_base_views.registration_iplan
;
