-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/reimbursement_discrepancy_eom_hist.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.reimbursement_discrepancy_eom_hist
   OPTIONS(description='Maintains the History of Reimbursement Discrepancy End Of Month snapshot.')
  AS SELECT
      reimbursement_discrepancy_eom_hist.company_code,
      reimbursement_discrepancy_eom_hist.coid,
      ROUND(reimbursement_discrepancy_eom_hist.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      ROUND(reimbursement_discrepancy_eom_hist.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      reimbursement_discrepancy_eom_hist.iplan_insurance_order_num,
      reimbursement_discrepancy_eom_hist.eor_log_date,
      reimbursement_discrepancy_eom_hist.log_id,
      reimbursement_discrepancy_eom_hist.log_sequence_num,
      reimbursement_discrepancy_eom_hist.discrepancy_resolved_date,
      reimbursement_discrepancy_eom_hist.eff_from_date,
      ROUND(reimbursement_discrepancy_eom_hist.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      reimbursement_discrepancy_eom_hist.iplan_id,
      reimbursement_discrepancy_eom_hist.length_of_stay_days_num,
      reimbursement_discrepancy_eom_hist.eor_drg_code,
      reimbursement_discrepancy_eom_hist.eor_hipps_code,
      ROUND(reimbursement_discrepancy_eom_hist.eor_payment_amt, 3, 'ROUND_HALF_EVEN') AS eor_payment_amt,
      reimbursement_discrepancy_eom_hist.remittance_date,
      reimbursement_discrepancy_eom_hist.ra_log_date,
      reimbursement_discrepancy_eom_hist.ra_payment_date,
      reimbursement_discrepancy_eom_hist.ra_drg_code,
      reimbursement_discrepancy_eom_hist.ra_hipps_code,
      reimbursement_discrepancy_eom_hist.ra_covered_days_num,
      ROUND(reimbursement_discrepancy_eom_hist.ra_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_non_covered_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS ra_gross_reimbursement_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS ra_ded_coins_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS ra_contractual_allowance_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_copay_amt, 3, 'ROUND_HALF_EVEN') AS ra_copay_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ra_coinsurance_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_billed_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_deductible_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_total_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_deductible_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_blood_deductible_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_lab_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_therapy_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_primary_payor_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_outlier_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_capital_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_denied_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_apc_service_amt,
      ROUND(reimbursement_discrepancy_eom_hist.ra_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_fee_schedule_amt,
      ROUND(reimbursement_discrepancy_eom_hist.over_under_payment_amt, 3, 'ROUND_HALF_EVEN') AS over_under_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.actual_payment_amt, 3, 'ROUND_HALF_EVEN') AS actual_payment_amt,
      reimbursement_discrepancy_eom_hist.discrepancy_origination_date,
      reimbursement_discrepancy_eom_hist.discrepancy_day_count,
      reimbursement_discrepancy_eom_hist.resolve_reason_code,
      reimbursement_discrepancy_eom_hist.discrepancy_status_code,
      reimbursement_discrepancy_eom_hist.var_covered_days_num,
      ROUND(reimbursement_discrepancy_eom_hist.var_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_total_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_non_covered_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_net_billed_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_reimbursement_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_deductible_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS var_coinsurance_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS var_ded_coins_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_blood_deductible_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_insurance_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_primary_payor_pmt_amt, 3, 'ROUND_HALF_EVEN') AS var_primary_payor_pmt_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_capital_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_lab_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_outlier_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_therapy_payment_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS var_contractual_allowance_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_copay_amt, 3, 'ROUND_HALF_EVEN') AS var_copay_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_covered_charge_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS var_net_apc_service_amt,
      ROUND(reimbursement_discrepancy_eom_hist.var_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS var_net_fee_schedule_amt,
      reimbursement_discrepancy_eom_hist.inpatient_outpatient_ind,
      reimbursement_discrepancy_eom_hist.primary_reason_assignment_cnt,
      reimbursement_discrepancy_eom_hist.discrepancy_reason_code_1,
      reimbursement_discrepancy_eom_hist.reason_assignment_date_1,
      reimbursement_discrepancy_eom_hist.discrepancy_reason_code_2,
      reimbursement_discrepancy_eom_hist.reason_assignment_date_2,
      reimbursement_discrepancy_eom_hist.discrepancy_reason_code_3,
      reimbursement_discrepancy_eom_hist.reason_assignment_date_3,
      reimbursement_discrepancy_eom_hist.discrepancy_reason_code_4,
      reimbursement_discrepancy_eom_hist.reason_assignment_date_4,
      reimbursement_discrepancy_eom_hist.comments,
      reimbursement_discrepancy_eom_hist.work_date,
      reimbursement_discrepancy_eom_hist.last_racf_id,
      reimbursement_discrepancy_eom_hist.last_racf_date,
      reimbursement_discrepancy_eom_hist.data_source_code,
      ROUND(reimbursement_discrepancy_eom_hist.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
      reimbursement_discrepancy_eom_hist.ar_bill_thru_date,
      ROUND(reimbursement_discrepancy_eom_hist.cc_calc_id, 0, 'ROUND_HALF_EVEN') AS cc_calc_id,
      ROUND(reimbursement_discrepancy_eom_hist.cc_account_activity_id, 0, 'ROUND_HALF_EVEN') AS cc_account_activity_id,
      ROUND(reimbursement_discrepancy_eom_hist.cc_reason_id, 0, 'ROUND_HALF_EVEN') AS cc_reason_id,
      ROUND(reimbursement_discrepancy_eom_hist.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
      reimbursement_discrepancy_eom_hist.last_update_date,
      reimbursement_discrepancy_eom_hist.dw_last_update_date_time,
      reimbursement_discrepancy_eom_hist.source_system_code
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.reimbursement_discrepancy_eom_hist
  ;
