-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/remittance_payment.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.remittance_payment
   OPTIONS(description='This is the check payment information recevied by Electronic Payment team from each payor by facility/provider.It also includes Control elements associated with the payer')
  AS SELECT
      remittance_payment.payment_guid,
      remittance_payment.check_num_an,
      remittance_payment.check_date,
      ROUND(remittance_payment.check_amt, 3, 'ROUND_HALF_EVEN') AS check_amt,
      remittance_payment.interchange_sender_id,
      remittance_payment.provider_level_adj_id,
      remittance_payment.remittance_payor_sid,
      remittance_payment.remittance_payee_sid,
      remittance_payment.audit_date,
      remittance_payment.delete_ind,
      remittance_payment.delete_date,
      remittance_payment.coid,
      remittance_payment.company_code,
      remittance_payment.unit_num,
      remittance_payment.era_create_date,
      remittance_payment.bill_process_date,
      remittance_payment.ep_effective_post_date,
      remittance_payment.ep_create_date,
      ROUND(remittance_payment.bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS bill_charge_amt,
      ROUND(remittance_payment.covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS covered_charge_amt,
      ROUND(remittance_payment.ep_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_non_covered_charge_amt,
      ROUND(remittance_payment.ep_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ep_coinsurance_amt,
      ROUND(remittance_payment.ep_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS ep_contractual_adj_amt,
      ROUND(remittance_payment.ep_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_deductible_amt,
      ROUND(remittance_payment.ep_denial_amt, 3, 'ROUND_HALF_EVEN') AS ep_denial_amt,
      ROUND(remittance_payment.drg_amt, 3, 'ROUND_HALF_EVEN') AS drg_amt,
      ROUND(remittance_payment.federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS federal_specific_drg_amt,
      ROUND(remittance_payment.ep_calc_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_blood_deductible_amt,
      ROUND(remittance_payment.ep_calc_hcpcs_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_hcpcs_charge_amt,
      ROUND(remittance_payment.ep_calc_hcpcs_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_hcpcs_payment_amt,
      ROUND(remittance_payment.apc_amt, 3, 'ROUND_HALF_EVEN') AS apc_amt,
      ROUND(remittance_payment.capital_amt, 3, 'ROUND_HALF_EVEN') AS capital_amt,
      ROUND(remittance_payment.disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS disproportionate_share_amt,
      ROUND(remittance_payment.indirect_teaching_amt, 3, 'ROUND_HALF_EVEN') AS indirect_teaching_amt,
      ROUND(remittance_payment.interest_amt, 3, 'ROUND_HALF_EVEN') AS interest_amt,
      ROUND(remittance_payment.claim_payment_amt, 3, 'ROUND_HALF_EVEN') AS claim_payment_amt,
      ROUND(remittance_payment.ep_lab_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_lab_charge_amt,
      ROUND(remittance_payment.ep_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_lab_payment_amt,
      ROUND(remittance_payment.ep_nonpayable_professional_fee_amt, 3, 'ROUND_HALF_EVEN') AS ep_nonpayable_professional_fee_amt,
      ROUND(remittance_payment.outlier_amt, 3, 'ROUND_HALF_EVEN') AS outlier_amt,
      ROUND(remittance_payment.patient_liability_amt, 3, 'ROUND_HALF_EVEN') AS patient_liability_amt,
      ROUND(remittance_payment.ep_primary_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_primary_insurance_payment_amt,
      ROUND(remittance_payment.ep_therapy_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_therapy_charge_amt,
      ROUND(remittance_payment.ep_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_therapy_payment_amt,
      ROUND(remittance_payment.ins_covered_day_cnt, 2, 'ROUND_HALF_EVEN') AS ins_covered_day_cnt,
      remittance_payment.ep_calc_covered_day_cnt,
      remittance_payment.noncovered_day_cnt,
      remittance_payment.claim_cnt,
      remittance_payment.ep_discharge_cnt,
      remittance_payment.cost_report_day_cnt,
      remittance_payment.remittance_seq_num,
      remittance_payment.ep_plb_key_num,
      ROUND(remittance_payment.boa_lockbox_num, 0, 'ROUND_HALF_EVEN') AS boa_lockbox_num,
      remittance_payment.interchange_receiver_id,
      remittance_payment.interchange_sender_qualifier_code,
      remittance_payment.interchange_sender_code,
      remittance_payment.interchange_receiver_id_qualifier_code,
      remittance_payment.interchange_receiver_code,
      remittance_payment.transmission_sending_code,
      remittance_payment.transmission_receiving_code,
      remittance_payment.bill_type_code,
      remittance_payment.payor_default_logging_type_code,
      remittance_payment.ep_payor_batch_code,
      remittance_payment.rac_ind,
      remittance_payment.payor_live_ind,
      remittance_payment.lab_transaction_breakout_ind,
      remittance_payment.comment_transaction_ind,
      remittance_payment.internal_denial_transaction_ind,
      remittance_payment.discharge_date_replacement_ind,
      remittance_payment.total_charges_replacement_ind,
      remittance_payment.patient_type_replacement_ind,
      remittance_payment.drg_replacement_ind,
      remittance_payment.apply_secondary_rule_ind,
      remittance_payment.apply_recover_rule_ind,
      remittance_payment.apply_mother_baby_rule_ind,
      remittance_payment.apply_total_charges_rule_ind,
      remittance_payment.apply_noncovered_charges_rule_ind,
      remittance_payment.apply_er_patient_rule_ind,
      remittance_payment.apply_recover_true_up_rule_ind,
      remittance_payment.apply_non_recover_true_up_rule_ind,
      remittance_payment.calculated_covered_days_ind,
      remittance_payment.alternate_sn_format_ind,
      remittance_payment.plb_recovery_transaction_ind,
      remittance_payment.duplicate_direct_payer_ind,
      remittance_payment.not_post_payer_ind,
      remittance_payment.source_system_code,
      remittance_payment.dw_last_update_date_time
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs.remittance_payment
  ;
