-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/remittance_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.remittance_pf AS SELECT
    remittance.company_code,
    remittance.coid,
    ROUND(remittance.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(remittance.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    remittance.remittance_advice_num,
    remittance.ra_log_date,
    remittance.log_id,
    remittance.log_sequence_num,
    ROUND(remittance.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    remittance.iplan_id,
    remittance.cc_ep_iplan_id,
    remittance.ar_bill_thru_date,
    remittance.payment_date,
    remittance.ra_reference_num,
    ROUND(remittance.cc_remittance_header_id, 0, 'ROUND_HALF_EVEN') AS cc_remittance_header_id,
    ROUND(remittance.cc_remittance_id, 0, 'ROUND_HALF_EVEN') AS cc_remittance_id,
    ROUND(remittance.cc_replaced_by_remittance_id, 0, 'ROUND_HALF_EVEN') AS cc_replaced_by_remittance_id,
    remittance.ra_transaction_date,
    remittance.ra_drg_code,
    remittance.ra_hipps_code,
    remittance.ra_covered_days_num,
    ROUND(remittance.ra_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_charge_amt,
    ROUND(remittance.ra_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_non_covered_charge_amt,
    ROUND(remittance.ra_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_billed_charge_amt,
    ROUND(remittance.ra_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_deductible_amt,
    ROUND(remittance.ra_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ra_coinsurance_amt,
    ROUND(remittance.ra_net_benefit_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_benefit_amt,
    ROUND(remittance.ra_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_insurance_payment_amt,
    remittance.ra_reversal_code,
    remittance.outlier_ind,
    remittance.cc_visit_cnt,
    remittance.cc_covered_days_visit_cnt,
    ROUND(remittance.cc_discharge_fraction_pct, 4, 'ROUND_HALF_EVEN') AS cc_discharge_fraction_pct,
    ROUND(remittance.cc_reimbursement_rate_pct, 4, 'ROUND_HALF_EVEN') AS cc_reimbursement_rate_pct,
    ROUND(remittance.cc_non_replaced_blood_unit_qty, 2, 'ROUND_HALF_EVEN') AS cc_non_replaced_blood_unit_qty,
    ROUND(remittance.cc_prescription_qty, 2, 'ROUND_HALF_EVEN') AS cc_prescription_qty,
    ROUND(remittance.cc_patient_responsible_amt, 3, 'ROUND_HALF_EVEN') AS cc_patient_responsible_amt,
    remittance.cc_patient_qualifier_code,
    remittance.cc_claim_status_code,
    remittance.cc_patient_status_code,
    remittance.cc_claim_filing_ind_code,
    remittance.cc_medicare_format_code,
    remittance.cc_claim_frequency_code,
    remittance.cc_payer_claim_control_num,
    remittance.cc_recieve_date,
    remittance.cc_service_start_date,
    remittance.cc_service_end_date,
    remittance.cc_coverage_expiration_date,
    remittance.cc_payer_patient_id,
    remittance.cc_payer_member_id,
    ROUND(remittance.cc_source_type_id, 0, 'ROUND_HALF_EVEN') AS cc_source_type_id,
    remittance.active_ind,
    remittance.dw_last_update_date_time,
    remittance.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpf_base_views.remittance
;
