SELECT 'J_MHB_Ref_MHB_Unit'||','||CAST(Count(*) AS VARCHAR (20))||','
AS SOURCE_STRING FROM
(
SEL RDC.RDC_SID RDC_SID ,VWUNIT.UNIT_ID MHB_Unit_Id,COALESCE(CF.COMPANY_CODE, 'H') Company_Code
,COALESCE(CF.COID,'99999') Coid,VWUNIT.UNITNAME MHB_Unit_Name,VWUNIT.UNITCODE MHB_Unit_Short_Name
,VWUNIT.ABBREVIATION MHB_Alt_Unit_Name,VWUNIT.SUBTYPE MHB_Sub_Type_Name
,'B' AS SOURCE_SYSTEM_CODE,CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME
FROM EDWCI_STAGING.VWUNITS VWUNIT
INNER JOIN EDWCI_BASE_VIEWS.REF_MHB_REGIONAL_DATA_CENTER RDC
ON SUBSTR(TRIM(VWUNIT.DATABASENAME), POSITION('_' IN TRIM(VWUNIT.DATABASENAME))+1) = RDC.RDC_DESC
LEFT JOIN EDW_PUB_VIEWS.CLINICAL_FACILITY CF 
ON  TRIM(CF.FACILITY_MNEMONIC_CS) = TRIM(VWUNIT.FACILITYCODE)
LEFT JOIN EDWCI_BASE_VIEWS.Ref_MHB_Unit UN
ON RDC.RDC_SID = UN.RDC_SID
AND VWUNIT.UNIT_ID = UN.MHB_Unit_Id
WHERE	UN.RDC_SID IS NULL
) Q