SELECT 'J_MHB_Ref_MHB_Dynamic_Role'||','||CAST(Count(*) AS VARCHAR (20))||','
AS SOURCE_STRING FROM
(
SELECT (SEL	COALESCE(MAX(DYNAMIC_ROLE_SID),0) 
FROM	EDWCI_BASE_VIEWS.REF_MHB_DYNAMIC_ROLE)+ROW_NUMBER() OVER (
ORDER BY RDC_SID, DYNAMICROLE_NAME, DYNAMICROLE_LABEL)  as DYNAMIC_ROLE_SID,
RDC_SID AS RDC_SID,
DYNAMICROLE_NAME AS MHB_Dynamic_Role_Parent_Name,
DYNAMICROLE_LABEL AS MHB_Dynamic_Role_Child_Name,
'B' AS Source_System_Code,
current_timestamp(0) AS DW_Last_Update_Date_Time
FROM	
(
	SELECT	DYNAMICROLE_NAME  , DYNAMICROLE_LABEL, RDC.RDC_SID 
FROM	(
	SELECT	DYNAMICROLE_NAME, DYNAMICROLE_LABEL, DATABASENAME 
	FROM	EDWCI_STAGING.VWDYNAMICROLEDETACHMENT 
	GROUP BY 1,2,3
	UNION 
	SELECT	DYNAMICROLE_NAME  , DYNAMICROLE_LABEL, DATABASENAME 
	FROM	EDWCI_STAGING.VWDYNAMICROLEATTACHMENT 
	GROUP BY 1,2,3
	) VWDYNAMICROLE
INNER JOIN EDWCI_BASE_VIEWS.REF_MHB_REGIONAL_DATA_CENTER RDC
	ON SUBSTR(TRIM(VWDYNAMICROLE.DATABASENAME), POSITION('_' IN TRIM(VWDYNAMICROLE.DATABASENAME))+1) = RDC.RDC_DESC
LEFT JOIN EDWCI_BASE_VIEWS.REF_MHB_DYNAMIC_ROLE DR
	ON VWDYNAMICROLE.DYNAMICROLE_NAME = DR.MHB_DYNAMIC_ROLE_PARENT_NAME
	AND VWDYNAMICROLE.DYNAMICROLE_LABEL = DR.MHB_DYNAMIC_ROLE_CHILD_NAME
	AND RDC.RDC_SID= DR.RDC_SID
WHERE	DR.DYNAMIC_ROLE_SID IS NULL
) Y
) Q