-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_views/cc_denial.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_views_dataset_name }}.cc_denial
   OPTIONS(description='EDWRA table for holding all denial data at the SSC level, patient account.')
  AS SELECT
      a.patient_dw_id,
      a.payor_dw_id,
      a.iplan_order_num,
      a.extract_date_time,
      a.max_appeal_num,
      a.max_seq_num,
      a.accounting_period_desc,
      a.ar_amt,
      a.actv_due_date,
      a.actv_desc,
      a.actv_subject_title_desc,
      a.actv_owner_name,
      a.admit_source_code,
      a.admit_type_ind,
      a.appeal_orig_amt,
      a.appeal_seq_create_date,
      a.appeal_seq_deadline_date,
      a.appeal_close_date,
      a.appeal_seq_creator_34_id,
      a.appeal_owner_34_id,
      a.appeal_modifier_34_id,
      a.appeal_code,
      a.appeal_desc,
      a.appeal_create_date,
      a.appeal_deadline_rmd_days_num,
      a.appeal_level_num,
      a.appeal_sent_actv_age_num,
      a.appeal_sent_actv_date,
      a.appeal_sent_actv_desc,
      a.appeal_sent_actv_ownr_34_id,
      a.appeal_sent_actv_subject_desc,
      a.appeal_sent_date,
      a.appeal_seq_num,
      a.appeal_sent_kpi_name,
      a.artiva_open_activity_due_date,
      a.attending_physician_id,
      a.attending_physician_name,
      a.authorization_code,
      CASE
        WHEN rtrim(session_user()) = rtrim(pn.userid) THEN '***'
        ELSE a.billing_name
      END AS billing_name,
      CASE
        WHEN rtrim(session_user()) = rtrim(pn.userid) THEN '***'
        ELSE a.billing_contact_name
      END AS billing_contact_name,
      a.billing_status_code,
      a.calc_base_desc,
      a.calc_date,
      a.cancel_bill_ind,
      a.cash_adjustment_amt,
      a.cash_adjustment_mtd_amt,
      a.cash_adjustment_net_amt,
      a.category_to_date_amt,
      a.cc_patient_type_code,
      a.company_code,
      a.coid,
      a.comparison_method_desc,
      a.covered_charge_amt,
      a.current_appeal_amt,
      a.current_appeal_balance_amt,
      a.deadline_kpi_name,
      a.denial_age_num,
      a.disp_code,
      a.disp_code_mod_date,
      a.disp_code_mod_user_id,
      a.disp_desc,
      a.discharge_date,
      a.expected_amt,
      a.external_appeal_code,
      a.facility_name,
      a.first_actv_create_date,
      a.first_denial_date,
      a.followup_kpi_name,
      a.iplan_id,
      a.insurance_provider_name,
      a.last_actv_completion_age_num,
      a.last_actv_completion_date,
      a.last_owner_change_date,
      a.last_project_change_date,
      a.last_reason_change_date,
      a.last_remit_received_date,
      a.last_status_change_date,
      a.last_user_act_create_age_num,
      a.legacy_appeal_initiation_date,
      a.major_payor_group_code,
      a.monbot_acct_payer_id,
      a.mtd_writeoff_amt,
      a.net_denial_write_off_amt,
      a.new_appeal_ind,
      a.otd_net_amt,
      a.otd_to_date_mtd_amt,
      a.pa_financial_class_num,
      a.pa_service_code,
      a.pa_account_status_desc,
      a.pa_discharge_status_code,
      a.pa_patient_type_desc,
      a.pa_latest_iplan_change_date,
      a.pa_drg_code,
      a.pa_actual_los_cnt,
      a.pa_denial_update_date,
      a.pa_account_total_bal_amt,
      a.pat_acct_num,
      CASE
        WHEN rtrim(session_user()) = rtrim(pn.userid) THEN '***'
        ELSE a.patient_name
      END AS patient_name,
      a.patient_birth_date,
      a.payor_category_name,
      a.payor_patient_code,
      a.payor_financial_class_num,
      a.payor_group_name,
      a.payor_due_amt,
      a.prior_appeal_response_date,
      a.project_name,
      a.rate_schedule_name,
      a.rate_schedule_eff_begin_date,
      a.rate_schedule_eff_end_date,
      a.reason_code,
      a.remit_drg_code,
      a.root_cause_desc,
      a.root_cause_dtl_desc,
      a.root_code,
      a.schema_id,
      a.service_begin_date,
      a.ssc_id,
      a.ssc_name,
      a.status_desc,
      a.status_category_desc,
      a.status_phase_desc,
      a.stratification_group_name,
      a.status_kpi_name,
      a.sub_unit_num,
      a.total_billed_charge_amt,
      a.total_charge_amt,
      a.total_denial_amt,
      a.total_expected_payment_amt,
      a.total_expected_adjustment_amt,
      a.total_pat_resp_actual_amt,
      a.total_payment_amt,
      a.total_var_adjustment_amt,
      a.unit_num,
      a.vendor_code,
      a.web_disp_code,
      a.web_disp_type_code,
      a.write_off_amt,
      a.work_queue_name,
      a.daily_denial_inventory_count,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_base_views_dataset_name }}.cc_denial AS a
      INNER JOIN {{ params.param_parallon_ra_base_views_dataset_name }}.secref_facility AS b ON rtrim(a.company_code) = rtrim(b.company_code)
       AND rtrim(a.coid) = rtrim(b.co_id)
       AND rtrim(b.user_id) = rtrim(session_user())
      LEFT OUTER JOIN (
        SELECT
            security_mask_and_exception.userid,
            security_mask_and_exception.masked_column_code
          FROM
            `{{ params.param_parallon_cur_project_id }}`.edw_sec_base_views.security_mask_and_exception
          WHERE rtrim(security_mask_and_exception.userid) = rtrim(session_user())
           AND rtrim(security_mask_and_exception.masked_column_code) = 'PN'
      ) AS pn ON rtrim(pn.userid) = rtrim(session_user())
  ;
