-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_views/cc_eor_eapg_calculation.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_views_dataset_name }}.cc_eor_eapg_calculation
   OPTIONS(description='Concuity APG calculation output for calculations using enhanced all payer grouping or EAPG.')
  AS SELECT
      a.patient_dw_id,
      a.payor_dw_id,
      a.insurance_order_num,
      a.eor_log_date,
      a.log_id,
      a.log_sequence_num,
      a.eff_from_date,
      a.apg_calc_num,
      a.adjustment_eapg_wgt,
      a.adjustment_factor_qty,
      a.agency_edit_code,
      a.ancillary_eapg_rate_amt,
      a.auto_rate_ehnc_splmt_amt,
      a.base_rate_amt,
      a.calc_method_id,
      a.calc_profile_id,
      a.ce_rule_id,
      a.ce_service_id,
      a.cers_term_id,
      a.claim_payment_status_code,
      a.claim_process_code,
      a.company_code,
      a.coid,
      a.cost_to_charge_ratio,
      a.creation_date,
      a.eapg_action_code,
      a.eapg_bilateral_discount_code,
      a.eapg_cah_wgt,
      a.eapg_category_code,
      a.eapg_code,
      a.eapg_code_version_text,
      a.eapg_payment_action_code,
      a.eapg_unassigned_code,
      a.eapg_type_code,
      a.eapg_wgt,
      a.fee_file_id,
      a.full_eapg_wgt,
      a.grouper_version_code,
      a.hospital_type_text,
      a.icd_version_desc,
      a.iplan_id,
      a.jw_modifier_ind,
      a.lab_payment_amt,
      a.li_adj_eapg_wgt,
      a.li_alternate_payment_amt,
      a.li_eapg_payment_amt,
      a.li_lab_payment_amt,
      a.li_procedure_fee_amt,
      a.li_redistributed_charge_amt,
      a.li_user_defined_adj_amt,
      a.modifier_1_code,
      a.modifier_2_code,
      a.modifier_3_code,
      a.modifier_4_code,
      a.modifier_5_code,
      a.no_outlier_payment_amt,
      a.noncov_charge_rank_1_amt,
      a.noncov_charge_rank_2_amt,
      a.noncov_charge_rank_3_amt,
      a.noncov_rank_1_qty,
      a.noncov_rank_2_qty,
      a.noncov_rank_3_qty,
      a.outlier_adj_amt,
      a.pape_outlier_component_amt,
      a.pape_payment_amt,
      a.pape_rate_amt,
      a.pat_acct_num,
      a.payment_pct,
      a.pkg_ind,
      a.pkg_per_diem_ind,
      a.procedure_code,
      a.provider_policy_adj_amt,
      a.reimbursement_type_code,
      a.repeat_anclry_discount_code,
      a.revenue_code,
      a.service_date,
      a.service_unit_paid_qty,
      a.service_unit_qty,
      a.sgnf_clnc_proc_csdt_ind,
      a.sgnf_proc_csdt_ind,
      a.sgnf_proc_dc_cand_ind,
      a.state_file_id,
      a.termn_proc_dc_ind,
      a.total_charge_amt,
      a.total_claim_payment_amt,
      a.total_covered_charge_amt,
      a.total_eapg_payment_amt,
      a.total_expected_payment_amt,
      a.total_payment_amt,
      a.unit_num,
      a.user_defined_adj_amt,
      a.visit_adj_eapg_wgt,
      a.visit_adj_pape_otlr_cmpnt_amt,
      a.visit_adj_pape_payment_amt,
      a.visit_atp_code,
      a.visit_atp_payment_amt,
      a.visit_eapg_payment_amt,
      a.visit_full_eapg_wgt,
      a.visit_id,
      a.visit_no_outlier_payment_amt,
      a.smart_act_red_fac_ind,
      a.hcd_dvc_add_on_pymt_ind,
      a.smart_actl_red_amt,
      a.cost_otlr_pymt_amt,
      a.li_cost_otlr_pymt_amt,
      a.li_cost_otlr_thld_amt,
      a.li_eapg_cost,
      a.rehab_base_rate,
      a.psych_base_rate,
      a.clm_rec_type_code,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_base_views_dataset_name }}.cc_eor_eapg_calculation AS a
      INNER JOIN {{ params.param_parallon_ra_base_views_dataset_name }}.secref_facility AS b ON rtrim(a.company_code) = rtrim(b.company_code)
       AND rtrim(a.coid) = rtrim(b.co_id)
       AND rtrim(b.user_id) = rtrim(session_user())
  ;
