-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_views/cc_reimbursement_discrepancy.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_views_dataset_name }}.cc_reimbursement_discrepancy
   OPTIONS(description='Concuity daily reimbursement discrepancies.')
  AS SELECT
      a.company_code,
      a.coid,
      a.patient_dw_id,
      a.payor_dw_id,
      a.iplan_insurance_order_num,
      a.eor_log_date,
      a.log_id,
      a.log_sequence_num,
      a.eff_from_date,
      a.unit_num,
      a.pat_acct_num,
      a.iplan_id,
      a.length_of_stay_days_num,
      a.eor_drg_code,
      a.eor_hipps_code,
      a.eor_payment_amt,
      a.ar_bill_thru_date,
      a.remittance_date,
      a.work_date,
      a.ra_log_date,
      a.ra_payment_date,
      a.ra_drg_code,
      a.ra_hipps_code,
      a.ra_covered_days_num,
      a.ra_total_charge_amt,
      a.ra_payment_amt,
      a.ra_copay_amt,
      a.ra_coinsurance_amt,
      a.ra_contractual_allowance_amt,
      a.ra_net_billed_charge_amt,
      a.ra_gross_reimbursement_amt,
      a.ra_non_covered_charge_amt,
      a.ra_deductible_coinsurance_amt,
      a.ra_deductible_amt,
      a.ra_total_deductible_amt,
      a.ra_blood_deductible_amt,
      a.ra_lab_payment_amt,
      a.ra_therapy_payment_amt,
      a.ra_primary_payor_payment_amt,
      a.ra_outlier_payment_amt,
      a.ra_capital_payment_amt,
      a.ra_denied_charge_amt,
      a.ra_net_apc_service_amt,
      a.ra_net_fee_schedule_amt,
      a.discrepancy_origination_date,
      a.actual_payment_amt,
      a.pa_total_account_balance_amt,
      a.over_under_payment_amt,
      a.discrepancy_day_cnt,
      a.var_covered_days_num,
      a.var_copay_amt,
      a.var_total_charge_amt,
      a.var_covered_charge_amt,
      a.var_non_covered_charge_amt,
      a.var_net_billed_charge_amt,
      a.var_gross_reimbursement_amt,
      a.var_deductible_amt,
      a.var_coinsurance_amt,
      a.var_deductible_coinsurance_amt,
      a.var_blood_deductible_amt,
      a.var_insurance_payment_amt,
      a.var_primary_payor_payment_amt,
      a.var_capital_payment_amt,
      a.var_lab_payment_amt,
      a.var_outlier_payment_amt,
      a.var_therapy_payment_amt,
      a.var_contractual_allowance_amt,
      a.var_net_apc_service_amt,
      a.var_net_fee_schedule_amt,
      a.inpatient_outpatient_ind,
      a.reason_code_3,
      a.calc_id,
      a.account_activity_id,
      a.reason_id,
      a.account_payer_status_id,
      a.dw_last_update_date_time,
      a.source_system_code
    FROM
      {{ params.param_parallon_ra_base_views_dataset_name }}.cc_reimbursement_discrepancy AS a
      INNER JOIN {{ params.param_parallon_ra_base_views_dataset_name }}.secref_facility AS b ON rtrim(a.company_code) = rtrim(b.company_code)
       AND rtrim(a.coid) = rtrim(b.co_id)
       AND rtrim(b.user_id) = rtrim(session_user())
  ;
