-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_views/pass_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_views_dataset_name }}.pass_eom AS SELECT
    bv.patient_dw_id,
    bv.company_code,
    bv.coid,
    bv.unit_num,
    bv.processing_zone_code,
    bv.stack_code,
    bv.rptg_period,
    bv.pat_acct_num,
    bv.facility_name,
    CASE
      WHEN rtrim(session_user()) = rtrim(z.userid) THEN '***'
      ELSE bv.patient_full_name
    END AS patient_full_name,
    bv.financial_class_code,
    bv.financial_class_desc,
    bv.patient_type_code,
    bv.derived_patient_type_code,
    bv.account_status_code,
    bv.admission_date,
    bv.discharge_date,
    bv.final_bill_date,
    bv.ar_bill_thru_date,
    bv.length_of_stay_days_num,
    bv.collector_org_code,
    bv.collector_org_type_code,
    bv.collector_org_short_name,
    bv.log_id,
    bv.log_name,
    bv.ip_contract_model_code,
    bv.iplan_id_ins1,
    bv.payor_name_ins1,
    bv.release_ind_ins1,
    bv.payor_balance_amt_ins1,
    bv.payor_liability_amt_ins1,
    bv.payor_payment_amt_ins1,
    bv.payor_adjustment_amt_ins1,
    bv.payor_contract_allow_amt_ins1,
    bv.pa_syst_adj_current_amt_ins1,
    bv.pa_new_actv_current_amt_ins1,
    bv.iplan_id_ins2,
    bv.payor_name_ins2,
    bv.release_ind_ins2,
    bv.payor_balance_amt_ins2,
    bv.payor_liability_amt_ins2,
    bv.payor_payment_amt_ins2,
    bv.payor_adjustment_amt_ins2,
    bv.payor_contract_allow_amt_ins2,
    bv.pa_syst_adj_current_amt_ins2,
    bv.pa_new_actv_current_amt_ins2,
    bv.iplan_id_ins3,
    bv.payor_name_ins3,
    bv.release_ind_ins3,
    bv.payor_balance_amt_ins3,
    bv.payor_liability_amt_ins3,
    bv.payor_payment_amt_ins3,
    bv.payor_adjustment_amt_ins3,
    bv.payor_contract_allow_amt_ins3,
    bv.pa_syst_adj_current_amt_ins3,
    bv.pa_new_actv_current_amt_ins3,
    bv.patient_balance_amt,
    bv.patient_liability_amt,
    bv.patient_payment_amt,
    bv.patient_adjustment_amt,
    bv.patient_contract_allow_amt,
    bv.total_billed_charge_amt,
    bv.total_rb_charge_amt,
    bv.total_anc_charge_amt,
    bv.total_write_off_bad_debt_amt,
    bv.total_write_off_other_amt,
    bv.total_adjustment_amt,
    bv.total_contract_allow_amt,
    bv.total_combined_adj_alw_amt,
    bv.total_payment_amt,
    bv.total_account_balance_amt,
    bv.prelim_account_balance_amt,
    bv.eor_gross_reimbursement_amt,
    bv.eor_contract_allow_amt,
    bv.eor_auto_post_amt,
    bv.discharge_to_eom_day_cnt,
    bv.current_month_amt,
    bv.sub_unit_num,
    bv.sub_unit_name,
    bv.drg_code,
    bv.icd_version_ind,
    bv.drg_payment_weight_amt,
    bv.drg_code_hcfa,
    bv.drg_code_classic,
    bv.drg_code_pre_hac,
    bv.drg_code_pre_hac_tricare,
    bv.denial_code_ins1,
    bv.financial_class_code_ins1,
    bv.denial_code_ins2,
    bv.financial_class_code_ins2,
    bv.denial_code_ins3,
    bv.financial_class_code_ins3,
    bv.prorated_release_amt_ins1,
    bv.prorated_release_amt_ins2,
    bv.prorated_release_amt_ins3,
    bv.prorated_release_date_ins1,
    bv.prorated_release_date_ins2,
    bv.prorated_release_date_ins3,
    bv.logging_ind,
    bv.auto_post_ind,
    bv.unbill_pre_admit_ind,
    bv.insured_employer_name,
    bv.insured_role_code,
    bv.apr_severity_of_illness,
    bv.apr_risk_of_mortality
  FROM
    {{ params.param_parallon_ra_base_views_dataset_name }}.pass_eom AS bv
    LEFT OUTER JOIN (
      SELECT
          security_mask_and_exception.userid,
          security_mask_and_exception.masked_column_code
        FROM
          `{{ params.param_parallon_cur_project_id }}`.edw_sec.security_mask_and_exception
        WHERE rtrim(security_mask_and_exception.userid) = rtrim(session_user())
         AND upper(rtrim(security_mask_and_exception.masked_column_code)) = 'PN'
    ) AS z ON rtrim(session_user()) = rtrim(z.userid)
    INNER JOIN {{ params.param_parallon_ra_base_views_dataset_name }}.secref_facility AS sf ON rtrim(bv.coid) = rtrim(sf.co_id)
     AND rtrim(sf.user_id) = rtrim(session_user())
;
