CREATE TABLE IF NOT EXISTS {{ params.param_clm_stage_dataset_name }}.fact_claim
(
  claim_id STRING NOT NULL,
  vendor_cid STRING,
  unit_num STRING,
  bill_type_code STRING,
  bill_provider_sid NUMERIC(29),
  pay_to_provider_sid NUMERIC(29),
  total_charge_amt NUMERIC(32, 3),
  payor_seq_ind STRING,
  iplan_id STRING,
  bill_dt DATE,
  patient_acct_num STRING,
  med_rec_num STRING,
  fed_tax_num STRING,
  stmt_cover_from_dt DATE,
  stmt_cover_to_dt DATE,
  admission_dt DATE,
  admission_hr STRING,
  admission_type_ind STRING,
  admission_source_cd STRING,
  discharge_hr STRING,
  discharge_status_cd STRING,
  accident_st STRING,
  npi NUMERIC(29),
  admit_diag_code STRING,
  drg STRING,
  claim_desc STRING,
  file_link_path_txt STRING,
  claim_file_name STRING,
  dw_last_update_date_time DATETIME,
  source_system_code STRING,
  prefix_pat_acct_num STRING,
  pas_coid STRING,
  financial_class NUMERIC(29),
  patient_type STRING,
  edi_837_type STRING,
  numeric_unit_num NUMERIC(29),
  numeric_patient_acct_num BIGNUMERIC(38),
  service_code STRING,
  taxonomy_code STRING,
  destination_method STRING,
  operationalgroup STRING
)
CLUSTER BY claim_id;
