-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_account_payor.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_account_payor
   OPTIONS(description='Contains all account payer records related to work queue.')
  AS SELECT
      cc_account_payor.patient_dw_id,
      cc_account_payor.payor_dw_id,
      cc_account_payor.iplan_order_num,
      cc_account_payor.company_code,
      cc_account_payor.coid,
      cc_account_payor.unit_num,
      cc_account_payor.pat_acct_num,
      cc_account_payor.iplan_id,
      cc_account_payor.employer_name,
      cc_account_payor.insurance_group_name,
      cc_account_payor.insurance_group_num_cd,
      cc_account_payor.insured_name,
      cc_account_payor.insured_gender_cd,
      cc_account_payor.insured_birth_date,
      cc_account_payor.payor_identification_num_cd,
      cc_account_payor.authorization_cd,
      cc_account_payor.billing_name,
      cc_account_payor.billed_date,
      cc_account_payor.billing_address_1,
      cc_account_payor.billing_address_2,
      cc_account_payor.billing_city_name,
      cc_account_payor.billing_state_code,
      cc_account_payor.billing_zip_code,
      cc_account_payor.billing_phone_num_cd,
      cc_account_payor.billing_fax_num,
      cc_account_payor.billing_contact_person_name,
      cc_account_payor.billing_contact_email_name,
      cc_account_payor.relation_to_insured_pat_cd,
      cc_account_payor.drg_version,
      cc_account_payor.pa_denial_date,
      cc_account_payor.first_denial_date,
      cc_account_payor.interest_stop_date,
      cc_account_payor.work_queue_name,
      cc_account_payor.rate_schedule_name,
      cc_account_payor.calc_date,
      cc_account_payor.calc_num,
      cc_account_payor.calc_result_ind,
      cc_account_payor.calc_base_choice_resolved_ind,
      cc_account_payor.calc_lock_ind,
      cc_account_payor.pa_autm_post_ind,
      cc_account_payor.apc_group_ind,
      cc_account_payor.eligible_ind,
      cc_account_payor.account_calc_situation_ind,
      cc_account_payor.allow_contract_code_change_ind,
      cc_account_payor.change_claim_trigger_ind,
      cc_account_payor.manual_trigger_ind,
      cc_account_payor.life_check_eligible_ind,
      cc_account_payor.pa_financial_class_code,
      cc_account_payor.bill_reason_code,
      cc_account_payor.external_appeal_code,
      cc_account_payor.total_exp_payment_amt,
      cc_account_payor.total_payment_amt,
      cc_account_payor.total_denial_amt,
      cc_account_payor.total_pat_responsibility_amt,
      cc_account_payor.est_pat_responsibility_amt,
      cc_account_payor.actual_pat_responsibility_amt,
      cc_account_payor.total_exp_contractual_amt,
      cc_account_payor.total_adjustment_amt,
      cc_account_payor.total_variance_adjustment_amt,
      cc_account_payor.current_exp_payment_amt,
      cc_account_payor.current_exp_contractual_amt,
      cc_account_payor.prof_covered_charge_amt,
      cc_account_payor.prof_exp_payment_amt,
      cc_account_payor.pa_prof_part_b_charge_amt,
      cc_account_payor.pa_blood_deductible_amt,
      cc_account_payor.sqstrtn_reduction_amt,
      cc_account_payor.pa_coinsurance_amt,
      cc_account_payor.autm_post_amt,
      cc_account_payor.coinsurance_amt,
      cc_account_payor.copay_amt,
      cc_account_payor.deductible_amt,
      cc_account_payor.covered_charge_instu_amt,
      cc_account_payor.cmpt_method_choice_id,
      cc_account_payor.calc_base_id,
      cc_account_payor.calc_base_survivor_id,
      cc_account_payor.reason_id,
      cc_account_payor.account_payor_status_id,
      cc_account_payor.appeal_id,
      cc_account_payor.cers_profile_id,
      cc_account_payor.capping_method_id,
      cc_account_payor.cers_term_id,
      cc_account_payor.project_id,
      cc_account_payor.account_payor_id,
      cc_account_payor.creation_date,
      cc_account_payor.update_date,
      cc_account_payor.prepay_mgd_care_sw,
      cc_account_payor.ip_provider_num,
      cc_account_payor.op_provider_num,
      cc_account_payor.payer_type_code,
      cc_account_payor.source_system_code,
      cc_account_payor.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_account_payor
  ;
