-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_account.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_account
   OPTIONS(description='A patient visiting for healthcare services. This can be a single encounter - single claim, a multi-visit - multi claim grouping.')
  AS SELECT
      cc_account.patient_dw_id,
      cc_account.account_id,
      cc_account.company_code,
      cc_account.coid,
      cc_account.unit_num,
      cc_account.pat_acct_num,
      cc_account.linked_pat_account_id,
      cc_account.patient_last_name,
      cc_account.patient_first_name,
      cc_account.patient_middle_name,
      cc_account.patient_name_suffix_text,
      cc_account.social_security_num,
      cc_account.medical_record_num,
      cc_account.admission_date_time,
      cc_account.discharge_date_time,
      cc_account.patient_birth_date,
      cc_account.patient_death_date,
      cc_account.patient_noa_date,
      cc_account.admission_source_code,
      cc_account.admission_type_code,
      cc_account.financial_class_code,
      cc_account.gender_code,
      cc_account.hipps_code,
      cc_account.discharge_status_code,
      cc_account.billing_status_code,
      cc_account.special_bill_ind,
      cc_account.diag_code_admit,
      cc_account.cancel_bill_ind,
      cc_account.ca_extract_stop_ind,
      cc_account.reassignable_ind,
      cc_account.service_code,
      cc_account.final_bill_date,
      cc_account.ar_bill_thru_date,
      cc_account.visit_cnt,
      cc_account.patient_type_code,
      cc_account.cc_patient_type_id,
      cc_account.account_status_code,
      cc_account.marital_status_code,
      cc_account.length_of_stay_days_num,
      cc_account.drg_code,
      cc_account.drg_type,
      cc_account.drg_version,
      cc_account.cc_regroup_drg_code,
      cc_account.cc_regroup_drg_type,
      cc_account.cc_regroup_drg_version,
      cc_account.cc_account_archive_ind,
      cc_account.birth_weight_amt,
      cc_account.pa_total_account_balance_amt,
      cc_account.total_charge_amt,
      cc_account.total_expected_reimb_amt,
      cc_account.total_patient_liability_amt,
      cc_account.total_payment_amt,
      cc_account.total_patient_payment_amt,
      cc_account.total_adjustment_amt,
      cc_account.total_billed_charges_amt,
      cc_account.financial_period_id,
      cc_account.ipf_interrupted_stay_day,
      cc_account.pa_archive_ind,
      cc_account.pa_purge_ind,
      cc_account.updated_login_userid,
      cc_account.last_calc_date_time,
      cc_account.ins_maint_date,
      cc_account.icd10_drg_code,
      cc_account.icd10_drg_version_id,
      cc_account.icd10_drg_severity_level_code,
      cc_account.pa_icd_version_desc,
      cc_account.create_date_time,
      cc_account.update_date_time,
      cc_account.archive_state_ind,
      cc_account.dw_last_update_date_time,
      cc_account.source_system_code
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_account
  ;
