-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_eor_calculation_service.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_eor_calculation_service
   OPTIONS(description='Contains calculation service data related to explanation of reimbursement.')
  AS SELECT
      cc_eor_calculation_service.company_code,
      cc_eor_calculation_service.coid,
      cc_eor_calculation_service.patient_dw_id,
      cc_eor_calculation_service.payor_dw_id,
      cc_eor_calculation_service.iplan_insurance_order_num,
      cc_eor_calculation_service.eor_log_date,
      cc_eor_calculation_service.acct_payor_calc_service_id,
      cc_eor_calculation_service.calc_id,
      cc_eor_calculation_service.ce_service_id,
      cc_eor_calculation_service.service_date,
      cc_eor_calculation_service.unit_num,
      cc_eor_calculation_service.pat_acct_num,
      cc_eor_calculation_service.iplan_id,
      cc_eor_calculation_service.service_qty,
      cc_eor_calculation_service.expected_payment_amt,
      cc_eor_calculation_service.subterm_expected_payment_amt,
      cc_eor_calculation_service.service_charge_amt,
      cc_eor_calculation_service.exclusion_charge_amt,
      cc_eor_calculation_service.noncovered_charge_amt,
      cc_eor_calculation_service.proc_code_type_desc,
      cc_eor_calculation_service.proc_code,
      cc_eor_calculation_service.modifier_1_code,
      cc_eor_calculation_service.modifier_2_code,
      cc_eor_calculation_service.revenue_code_desc,
      cc_eor_calculation_service.calculation_method_desc,
      cc_eor_calculation_service.rate_info_from_day_num,
      cc_eor_calculation_service.rate_info_to_day_num,
      cc_eor_calculation_service.rate_info_amt,
      cc_eor_calculation_service.rate_info_service_desc,
      cc_eor_calculation_service.gov_drg_payment_amt,
      cc_eor_calculation_service.gov_ime_capital_drg_pmt_amt,
      cc_eor_calculation_service.gov_operating_cost_outlier_amt,
      cc_eor_calculation_service.gov_operating_fed_pmt_amt,
      cc_eor_calculation_service.hipps_payment_amt,
      cc_eor_calculation_service.ipf_pps_outlier_per_diem_amt,
      cc_eor_calculation_service.ipf_pps_out_per_diem_addon_amt,
      cc_eor_calculation_service.gov_scp_payment_amt,
      cc_eor_calculation_service.ipf_cost_charge_ratio_amt,
      cc_eor_calculation_service.ipf_fixed_loss_amt,
      cc_eor_calculation_service.ipf_labor_share_amt,
      cc_eor_calculation_service.ipf_labor_share_pct,
      cc_eor_calculation_service.ipf_non_labor_share_amt,
      cc_eor_calculation_service.ipf_teaching_adj_fctr_pct,
      cc_eor_calculation_service.ipf_age_fctr_pct,
      cc_eor_calculation_service.ipf_drg_adj_fctr_pct,
      cc_eor_calculation_service.ipf_comorbidity_fctr_pct,
      cc_eor_calculation_service.ipf_pps_facility_adj_fctr_pct,
      cc_eor_calculation_service.ipf_pps_adj_fctr_pct,
      cc_eor_calculation_service.ipf_pps_los_adj_fctr_pct,
      cc_eor_calculation_service.gov_new_tech_add_on_amt,
      cc_eor_calculation_service.gov_device_offset_red_amt,
      cc_eor_calculation_service.gov_transfer_pct,
      cc_eor_calculation_service.ipf_per_diem_day_num,
      cc_eor_calculation_service.apc_composite_flg,
      cc_eor_calculation_service.dsh_unadj_opr_add_on_amt,
      cc_eor_calculation_service.dsh_uncmps_care_add_on_amt,
      cc_eor_calculation_service.mdh_add_on_amt,
      cc_eor_calculation_service.low_vol_add_on_amt,
      cc_eor_calculation_service.readm_adj_amt,
      cc_eor_calculation_service.val_based_adj_amt,
      cc_eor_calculation_service.drg_fixed_loss_threshold_amt,
      cc_eor_calculation_service.drg_marginal_cost_fctr_pct,
      cc_eor_calculation_service.apc_outlier_pct,
      cc_eor_calculation_service.opps_pct,
      cc_eor_calculation_service.source_system_code,
      cc_eor_calculation_service.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_eor_calculation_service
  ;
