-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_eor.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_eor AS SELECT
    cc_eor.company_code,
    cc_eor.coid,
    cc_eor.patient_dw_id,
    cc_eor.payor_dw_id,
    cc_eor.iplan_insurance_order_num,
    cc_eor.eor_log_date,
    cc_eor.log_id,
    cc_eor.log_sequence_num,
    cc_eor.eff_from_date,
    cc_eor.unit_num,
    cc_eor.pat_acct_num,
    cc_eor.iplan_id,
    cc_eor.financial_class_code,
    cc_eor.final_bill_date,
    cc_eor.ar_bill_thru_date,
    cc_eor.ar_bill_drop_date,
    cc_eor.contract_begin_date,
    cc_eor.eor_transaction_date,
    cc_eor.bill_reason_code,
    cc_eor.eor_drg_code,
    cc_eor.cc_drg_code,
    cc_eor.cc_drg_weight,
    cc_eor.eor_hipps_code,
    cc_eor.cc_cmg_code,
    cc_eor.cc_cmg_weight,
    cc_eor.eor_covered_days_num,
    cc_eor.eor_total_charge_amt,
    cc_eor.expected_insurance_payment_amt,
    cc_eor.pat_resp_non_covered_chg_amt,
    cc_eor.total_actual_pat_resp_amt,
    cc_eor.eor_non_covered_charge_amt,
    cc_eor.eor_cmptd_reimbursement_amt,
    cc_eor.eor_deductible_amt,
    cc_eor.eor_coinsurance_amt,
    cc_eor.eor_copay_amt,
    cc_eor.eor_insurance_payment_amt,
    cc_eor.eor_contractual_allowance_amt,
    cc_eor.eor_cost_of_service_amt,
    cc_eor.month_13_ind,
    cc_eor.outlier_code,
    cc_eor.auto_post_amt,
    cc_eor.auto_post_ind,
    cc_eor.drg_table_id,
    cc_eor.opps_ind,
    cc_eor.inpatient_outpatient_ind,
    cc_eor.visit_count,
    cc_eor.eor_gross_reimbursement_amt,
    cc_eor.eor_net_reimbursement_amt,
    cc_eor.eor_non_bill_charge_amt,
    cc_eor.sqstrtn_red_amt,
    cc_eor.model_name,
    cc_eor.project_desc,
    cc_eor.eor_ipf_interrupted_day_stay,
    cc_eor.calc_success_ind,
    cc_eor.latest_calc_ind,
    cc_eor.interim_bill_ind,
    cc_eor.financial_period_id,
    cc_eor.reason_id,
    cc_eor.calc_id,
    cc_eor.source_system_code,
    cc_eor.dw_last_update_date_time
  FROM
    {{ params.param_parallon_ra_core_dataset_name }}.cc_eor
;
