-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_eor_eapg_grouper.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_eor_eapg_grouper
   OPTIONS(description='Concuity grouper output for enhanced all payer grouping or EAPG.')
  AS SELECT
      cc_eor_eapg_grouper.patient_dw_id,
      cc_eor_eapg_grouper.apg_grouper_num,
      cc_eor_eapg_grouper.action_code,
      cc_eor_eapg_grouper.calc_method_id,
      cc_eor_eapg_grouper.calc_profile_id,
      cc_eor_eapg_grouper.charge_claim_ind,
      cc_eor_eapg_grouper.charge_code_desc,
      cc_eor_eapg_grouper.charge_ind_code,
      cc_eor_eapg_grouper.charge_posted_date_time,
      cc_eor_eapg_grouper.code_type,
      cc_eor_eapg_grouper.coid,
      cc_eor_eapg_grouper.company_code,
      cc_eor_eapg_grouper.creation_date_time,
      cc_eor_eapg_grouper.drug_304b_dc_ind,
      cc_eor_eapg_grouper.eapg_action_code,
      cc_eor_eapg_grouper.eapg_bilateral_discount_code,
      cc_eor_eapg_grouper.eapg_category_code,
      cc_eor_eapg_grouper.eapg_code,
      cc_eor_eapg_grouper.eapg_code_version_text,
      cc_eor_eapg_grouper.eapg_type_code,
      cc_eor_eapg_grouper.eapg_unassigned_code,
      cc_eor_eapg_grouper.eapg_visit_type_code,
      cc_eor_eapg_grouper.icd_version_desc,
      cc_eor_eapg_grouper.jw_modifier_ind,
      cc_eor_eapg_grouper.med_visit_diag_code,
      cc_eor_eapg_grouper.modifier_1_code,
      cc_eor_eapg_grouper.modifier_2_code,
      cc_eor_eapg_grouper.modifier_3_code,
      cc_eor_eapg_grouper.modifier_4_code,
      cc_eor_eapg_grouper.modifier_5_code,
      cc_eor_eapg_grouper.non_cov_charge_rank_1_amt,
      cc_eor_eapg_grouper.non_cov_charge_rank_2_amt,
      cc_eor_eapg_grouper.non_cov_charge_rank_3_amt,
      cc_eor_eapg_grouper.non_cov_rank_1_qty,
      cc_eor_eapg_grouper.non_cov_rank_2_qty,
      cc_eor_eapg_grouper.non_cov_rank_3_qty,
      cc_eor_eapg_grouper.pat_acct_num,
      cc_eor_eapg_grouper.pkg_ind,
      cc_eor_eapg_grouper.pkg_per_diem_ind,
      cc_eor_eapg_grouper.principal_diag_code,
      cc_eor_eapg_grouper.proc_code_used_qty,
      cc_eor_eapg_grouper.repeat_ancl_dc_ind,
      cc_eor_eapg_grouper.revenue_code,
      cc_eor_eapg_grouper.secn_diag_code_used_qty,
      cc_eor_eapg_grouper.secn_diag_used_code_desc,
      cc_eor_eapg_grouper.service_unit_qty,
      cc_eor_eapg_grouper.service_date,
      cc_eor_eapg_grouper.sgnf_clinc_proc_csdt_ind,
      cc_eor_eapg_grouper.sgnf_proc_csdt_ind,
      cc_eor_eapg_grouper.sgnf_proc_dc_cand_ind,
      cc_eor_eapg_grouper.termn_proc_dc_ind,
      cc_eor_eapg_grouper.total_charge_amt,
      cc_eor_eapg_grouper.total_covered_charge_amt,
      cc_eor_eapg_grouper.unit_num,
      cc_eor_eapg_grouper.used_proc_code,
      cc_eor_eapg_grouper.used_visit_diag_code_desc,
      cc_eor_eapg_grouper.visit_cnt,
      cc_eor_eapg_grouper.visit_id,
      cc_eor_eapg_grouper.visit_line_qty,
      cc_eor_eapg_grouper.visit_preventive_med_diag_ind,
      cc_eor_eapg_grouper.source_system_code,
      cc_eor_eapg_grouper.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_eor_eapg_grouper
  ;
