-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_patient_account_audit.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_patient_account_audit
   OPTIONS(description='Display Audits and Refund information tied to a Concuity accounts.')
  AS SELECT
      cc_patient_account_audit.patient_dw_id,
      cc_patient_account_audit.payor_dw_id,
      cc_patient_account_audit.company_code,
      cc_patient_account_audit.coid,
      cc_patient_account_audit.unit_num,
      cc_patient_account_audit.pat_acct_num,
      cc_patient_account_audit.iplan_id,
      cc_patient_account_audit.pat_acct_audit_id,
      cc_patient_account_audit.acct_payor_id,
      cc_patient_account_audit.claim_num,
      cc_patient_account_audit.record_id,
      cc_patient_account_audit.record_type_txt,
      cc_patient_account_audit.corp_control_txt,
      cc_patient_account_audit.ssc_control_txt,
      cc_patient_account_audit.corp_status_date,
      cc_patient_account_audit.audit_eligibility_txt,
      cc_patient_account_audit.audit_status_txt,
      cc_patient_account_audit.pre_audit_type_txt,
      cc_patient_account_audit.post_audit_type_txt,
      cc_patient_account_audit.other_audit_type_desc,
      cc_patient_account_audit.audit_status_date,
      cc_patient_account_audit.prev_audit_drg_nm,
      cc_patient_account_audit.post_audit_drg_nm,
      cc_patient_account_audit.payer_of_audit_txt,
      cc_patient_account_audit.audit_schedule_date,
      cc_patient_account_audit.expt_audit_fee_amt,
      cc_patient_account_audit.act_audit_fee_coll_amt,
      cc_patient_account_audit.audit_location_txt,
      cc_patient_account_audit.final_audit_outcome_txt,
      cc_patient_account_audit.work_again_date,
      cc_patient_account_audit.service_start_date,
      cc_patient_account_audit.service_end_date,
      cc_patient_account_audit.corp_status_desc,
      cc_patient_account_audit.addl_project_desc,
      cc_patient_account_audit.finding_letter_result_txt,
      cc_patient_account_audit.initiation_date,
      cc_patient_account_audit.letter_date,
      cc_patient_account_audit.response_date,
      cc_patient_account_audit.mr_trk_id,
      cc_patient_account_audit.mr_req_txt,
      cc_patient_account_audit.mr_rls_req_to_roi_date,
      cc_patient_account_audit.mr_rls_method_txt,
      cc_patient_account_audit.mr_rls_date,
      cc_patient_account_audit.mr_miss_notf_date,
      cc_patient_account_audit.miss_doc_req_txt,
      cc_patient_account_audit.payer_drg_code,
      cc_patient_account_audit.payer_ref_id,
      cc_patient_account_audit.risk_amt,
      cc_patient_account_audit.disc_amt,
      cc_patient_account_audit.refund_req_amt,
      cc_patient_account_audit.refund_amt,
      cc_patient_account_audit.refund_req_reason_txt,
      cc_patient_account_audit.refund_status_txt,
      cc_patient_account_audit.refund_status_date,
      cc_patient_account_audit.final_refund_outcome_txt,
      cc_patient_account_audit.creation_date,
      cc_patient_account_audit.creation_user_id,
      cc_patient_account_audit.modification_date,
      cc_patient_account_audit.modification_user_id,
      cc_patient_account_audit.map_to_record_type_txt,
      cc_patient_account_audit.map_to_record_id,
      cc_patient_account_audit.refund_prcs_tool_status_txt,
      cc_patient_account_audit.source_system_code,
      cc_patient_account_audit.dw_last_update_date_time
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_patient_account_audit
  ;
