-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_reimbursement_discrepancy.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_reimbursement_discrepancy
   OPTIONS(description='Concuity daily reimbursement discrepancies.')
  AS SELECT
      cc_reimbursement_discrepancy.company_code,
      cc_reimbursement_discrepancy.coid,
      cc_reimbursement_discrepancy.patient_dw_id,
      cc_reimbursement_discrepancy.payor_dw_id,
      cc_reimbursement_discrepancy.iplan_insurance_order_num,
      cc_reimbursement_discrepancy.eor_log_date,
      cc_reimbursement_discrepancy.log_id,
      cc_reimbursement_discrepancy.log_sequence_num,
      cc_reimbursement_discrepancy.eff_from_date,
      cc_reimbursement_discrepancy.unit_num,
      cc_reimbursement_discrepancy.pat_acct_num,
      cc_reimbursement_discrepancy.iplan_id,
      cc_reimbursement_discrepancy.length_of_stay_days_num,
      cc_reimbursement_discrepancy.eor_drg_code,
      cc_reimbursement_discrepancy.eor_hipps_code,
      cc_reimbursement_discrepancy.eor_payment_amt,
      cc_reimbursement_discrepancy.ar_bill_thru_date,
      cc_reimbursement_discrepancy.remittance_date,
      cc_reimbursement_discrepancy.work_date,
      cc_reimbursement_discrepancy.ra_log_date,
      cc_reimbursement_discrepancy.ra_payment_date,
      cc_reimbursement_discrepancy.ra_drg_code,
      cc_reimbursement_discrepancy.ra_hipps_code,
      cc_reimbursement_discrepancy.ra_covered_days_num,
      cc_reimbursement_discrepancy.ra_total_charge_amt,
      cc_reimbursement_discrepancy.ra_payment_amt,
      cc_reimbursement_discrepancy.ra_copay_amt,
      cc_reimbursement_discrepancy.ra_coinsurance_amt,
      cc_reimbursement_discrepancy.ra_contractual_allowance_amt,
      cc_reimbursement_discrepancy.ra_net_billed_charge_amt,
      cc_reimbursement_discrepancy.ra_gross_reimbursement_amt,
      cc_reimbursement_discrepancy.ra_non_covered_charge_amt,
      cc_reimbursement_discrepancy.ra_deductible_coinsurance_amt,
      cc_reimbursement_discrepancy.ra_deductible_amt,
      cc_reimbursement_discrepancy.ra_total_deductible_amt,
      cc_reimbursement_discrepancy.ra_blood_deductible_amt,
      cc_reimbursement_discrepancy.ra_lab_payment_amt,
      cc_reimbursement_discrepancy.ra_therapy_payment_amt,
      cc_reimbursement_discrepancy.ra_primary_payor_payment_amt,
      cc_reimbursement_discrepancy.ra_outlier_payment_amt,
      cc_reimbursement_discrepancy.ra_capital_payment_amt,
      cc_reimbursement_discrepancy.ra_denied_charge_amt,
      cc_reimbursement_discrepancy.ra_net_apc_service_amt,
      cc_reimbursement_discrepancy.ra_net_fee_schedule_amt,
      cc_reimbursement_discrepancy.discrepancy_origination_date,
      cc_reimbursement_discrepancy.actual_payment_amt,
      cc_reimbursement_discrepancy.pa_total_account_balance_amt,
      cc_reimbursement_discrepancy.over_under_payment_amt,
      cc_reimbursement_discrepancy.discrepancy_day_cnt,
      cc_reimbursement_discrepancy.var_covered_days_num,
      cc_reimbursement_discrepancy.var_copay_amt,
      cc_reimbursement_discrepancy.var_total_charge_amt,
      cc_reimbursement_discrepancy.var_covered_charge_amt,
      cc_reimbursement_discrepancy.var_non_covered_charge_amt,
      cc_reimbursement_discrepancy.var_net_billed_charge_amt,
      cc_reimbursement_discrepancy.var_gross_reimbursement_amt,
      cc_reimbursement_discrepancy.var_deductible_amt,
      cc_reimbursement_discrepancy.var_coinsurance_amt,
      cc_reimbursement_discrepancy.var_deductible_coinsurance_amt,
      cc_reimbursement_discrepancy.var_blood_deductible_amt,
      cc_reimbursement_discrepancy.var_insurance_payment_amt,
      cc_reimbursement_discrepancy.var_primary_payor_payment_amt,
      cc_reimbursement_discrepancy.var_capital_payment_amt,
      cc_reimbursement_discrepancy.var_lab_payment_amt,
      cc_reimbursement_discrepancy.var_outlier_payment_amt,
      cc_reimbursement_discrepancy.var_therapy_payment_amt,
      cc_reimbursement_discrepancy.var_contractual_allowance_amt,
      cc_reimbursement_discrepancy.var_net_apc_service_amt,
      cc_reimbursement_discrepancy.var_net_fee_schedule_amt,
      cc_reimbursement_discrepancy.inpatient_outpatient_ind,
      cc_reimbursement_discrepancy.reason_code_3,
      cc_reimbursement_discrepancy.calc_id,
      cc_reimbursement_discrepancy.account_activity_id,
      cc_reimbursement_discrepancy.reason_id,
      cc_reimbursement_discrepancy.account_payer_status_id,
      cc_reimbursement_discrepancy.dw_last_update_date_time,
      cc_reimbursement_discrepancy.source_system_code
    FROM
      {{ params.param_parallon_ra_core_dataset_name }}.cc_reimbursement_discrepancy
  ;
