-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/cc_remittance.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.cc_remittance AS SELECT
    cc_remittance.company_code,
    cc_remittance.coid,
    cc_remittance.patient_dw_id,
    cc_remittance.payor_dw_id,
    cc_remittance.remittance_advice_num,
    cc_remittance.ra_log_date,
    cc_remittance.log_id,
    cc_remittance.log_sequence_num,
    cc_remittance.remittance_header_id,
    cc_remittance.remittance_id,
    cc_remittance.unit_num,
    cc_remittance.pat_acct_num,
    cc_remittance.iplan_insurance_order_num,
    cc_remittance.iplan_id,
    cc_remittance.ra_ep_iplan_id,
    cc_remittance.ar_bill_thru_date,
    cc_remittance.ra_drg_code,
    cc_remittance.ra_drg_weight,
    cc_remittance.ra_hipps_code,
    cc_remittance.ra_covered_days_num,
    cc_remittance.ra_visit_cnt,
    cc_remittance.ra_covered_days_visit_cnt,
    cc_remittance.outlier_ind,
    cc_remittance.ra_discharge_fraction_pct,
    cc_remittance.ra_reimbursement_rate_pct,
    cc_remittance.ra_non_replaced_blood_unit_qty,
    cc_remittance.ra_prescription_qty,
    cc_remittance.ra_total_charge_amt,
    cc_remittance.ra_non_covered_charge_amt,
    cc_remittance.ra_net_billed_charge_amt,
    cc_remittance.ra_deductible_amt,
    cc_remittance.ra_coinsurance_amt,
    cc_remittance.ra_net_benefit_amt,
    cc_remittance.ra_insurance_payment_amt,
    cc_remittance.ra_patient_responsible_amt,
    cc_remittance.ra_patient_qualifier_code,
    cc_remittance.ra_claim_status_code,
    cc_remittance.ra_patient_status_code,
    cc_remittance.ra_claim_filing_ind_code,
    cc_remittance.ra_medicare_format_code,
    cc_remittance.ra_facility_type_code,
    cc_remittance.ra_claim_frequency_code,
    cc_remittance.ra_payer_claim_control_num,
    cc_remittance.ra_receive_date,
    cc_remittance.ra_service_start_date,
    cc_remittance.ra_service_end_date,
    cc_remittance.ra_coverage_expiration_date,
    cc_remittance.ra_payer_patient_id,
    cc_remittance.ra_payer_member_id,
    cc_remittance.ra_replaced_by_remit_id,
    cc_remittance.ra_source_type_id,
    cc_remittance.active_ind,
    cc_remittance.dw_last_update_date_time,
    cc_remittance.source_system_code
  FROM
    {{ params.param_parallon_ra_core_dataset_name }}.cc_remittance
;
