-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/denial_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.denial_eom AS SELECT
    denial_eom.company_code,
    denial_eom.coid,
    denial_eom.patient_dw_id,
    denial_eom.payor_dw_id,
    denial_eom.iplan_insurance_order_num,
    denial_eom.pe_date,
    denial_eom.denial_status_code,
    denial_eom.unit_num,
    denial_eom.pat_acct_num,
    denial_eom.iplan_id,
    denial_eom.patient_type_code,
    denial_eom.patient_financial_class_code,
    denial_eom.payor_financial_class_code,
    denial_eom.disposition_num,
    denial_eom.appeal_origination_date,
    denial_eom.appeal_level_origination_date,
    denial_eom.appeal_closing_date,
    denial_eom.appeal_deadline_date,
    denial_eom.appeal_level_num,
    denial_eom.beginning_balance_amt,
    denial_eom.beginning_balance_count,
    denial_eom.beginning_appeal_amt,
    denial_eom.new_denial_account_amt,
    denial_eom.new_denial_account_count,
    denial_eom.not_true_denial_amt,
    denial_eom.write_off_denial_account_amt,
    denial_eom.unworked_conversion_amt,
    denial_eom.unworked_new_accounts_count,
    denial_eom.overturned_account_amt,
    denial_eom.corrections_account_amt,
    denial_eom.trans_next_party_amt,
    denial_eom.ending_balance_amt,
    denial_eom.total_charge_amt,
    denial_eom.account_balance_amt,
    denial_eom.resolved_accounts_count,
    denial_eom.attending_physician_name,
    denial_eom.service_code,
    denial_eom.medical_record_num,
    denial_eom.discharge_date,
    denial_eom.last_update_id,
    denial_eom.last_update_date,
    denial_eom.work_again_date,
    denial_eom.source_system_code,
    denial_eom.denied_charges,
    denial_eom.cc_cash_adjustment_amt,
    denial_eom.cc_contractual_allow_adj_amt,
    denial_eom.cc_root_cause_id,
    denial_eom.cc_denial_cat_code,
    denial_eom.cc_disposition_code,
    denial_eom.pa_vendor_code
  FROM
    {{ params.param_auth_base_views_dataset_name }}.denial_eom
;
