-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_base_views/fact_facility.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_parallon_ra_base_views_dataset_name }}.fact_facility AS SELECT
    fact_facility.coid,
    fact_facility.coid_level_num,
    fact_facility.coid_name,
    fact_facility.coid_status_code,
    fact_facility.coid_type_code,
    fact_facility.coid_type_name,
    fact_facility.company_code,
    fact_facility.cons_facility_code,
    fact_facility.cons_facility_level_num,
    fact_facility.cons_facility_name,
    fact_facility.cons_facility_type_code,
    fact_facility.cons_facility_type_name,
    fact_facility.cons_income_category_code,
    fact_facility.corporate_code,
    fact_facility.corporate_level_num,
    fact_facility.corporate_name,
    fact_facility.corporate_type_code,
    fact_facility.corporate_type_name,
    fact_facility.division_code,
    fact_facility.division_level_num,
    fact_facility.division_name,
    fact_facility.division_type_code,
    fact_facility.division_type_name,
    fact_facility.financial_jv_code,
    fact_facility.fiscal_year_end_month,
    fact_facility.gl_consolidation_ind,
    fact_facility.gl_standard_chart_id,
    fact_facility.group_code,
    fact_facility.group_level_num,
    fact_facility.group_name,
    fact_facility.group_type_code,
    fact_facility.group_type_name,
    fact_facility.income_category,
    fact_facility.income_category_code,
    fact_facility.lob_code,
    fact_facility.lob_name,
    fact_facility.market_code,
    fact_facility.market_level_num,
    fact_facility.market_name,
    fact_facility.market_type_code,
    fact_facility.market_type_name,
    fact_facility.medicare_year_end_month,
    fact_facility.own_managed_code,
    fact_facility.own_percentage,
    fact_facility.sector_code,
    fact_facility.sector_level_num,
    fact_facility.sector_name,
    fact_facility.sector_type_code,
    fact_facility.sector_type_name,
    fact_facility.state_code,
    fact_facility.sub_lob_code,
    fact_facility.sub_lob_name,
    fact_facility.unit_num,
    fact_facility.data_source_code,
    fact_facility.pas_coid,
    fact_facility.pas_status,
    fact_facility.company_code_operations
  FROM
    {{ params.param_auth_base_views_dataset_name }}.fact_facility
;
