/* Author: Srinivas Pochampally
   Date  : 08/01/2023
   Table : Employee Action Details 
   Desc  : Delete the duplication data from above table and open the corresponding last closed record. 
*/

-- Update Part 1 

UPDATE `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
SET Valid_to_date = '9999-12-31T23:59:59',
    dw_last_update_date_time = valid_from_date
WHERE STRUCT (  employee_action_sid,
                eff_from_date,
                valid_from_date,
                valid_to_date,
                action_code,
                employee_sid,
                COALESCE(employee_num,0) AS employee_num,
                action_sequence_num,
                action_from_date,
                action_to_date,
                COALESCE(trim(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
                COALESCE(trim(from_dept_code),'') AS from_dept_code,
                COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
                COALESCE(trim(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
                COALESCE(trim(from_job_code),'') AS from_job_code,
                COALESCE(trim(from_location_code),'') AS from_location_code,
                COALESCE(trim(from_overtime_plan_code),'') AS from_overtime_plan_code,
                COALESCE(trim(from_position_code),'') AS from_position_code,
                COALESCE(from_position_level_num,0) AS from_position_level_num,
                COALESCE(trim(from_process_level_code),'') AS from_process_level_code,
                COALESCE(from_payment_frequency,0) AS from_payment_frequency,
                COALESCE(trim(from_payment_grade_code),'') AS from_payment_grade_code,
                COALESCE(from_payment_step_num,0) AS from_payment_step_num,
                COALESCE(trim(from_salary_class_code),'') AS from_salary_class_code,
                COALESCE(trim(from_schedule_code),'') AS from_schedule_code,
                COALESCE(from_standard_hour,0) AS from_standard_hour,
                COALESCE(trim(from_supervisor_code),'') AS from_supervisor_code,
                COALESCE(trim(from_union_code),'') AS from_union_code,
                COALESCE(trim(from_user_level),'') AS from_user_level,
                COALESCE(trim(from_excemption_flag),'') AS from_excemption_flag,
                COALESCE(trim(from_expense_account_unit),'') AS from_expense_account_unit,
                COALESCE(from_expense_company,0) AS from_expense_company,
                COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
                COALESCE(trim(hr_code_desc),'') AS hr_code_desc,
                last_update_date,
                last_transfer_eff_date,
                COALESCE(trim(reason_desc),'') AS reason_desc,
                COALESCE(to_payment_frequency,0) AS to_payment_frequency,
                COALESCE(trim(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
                COALESCE(trim(to_dept_code),'') AS to_dept_code,
                COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
                COALESCE(trim(to_employee_schedule_code),'') AS to_employee_schedule_code,
                COALESCE(trim(to_job_code),'') AS to_job_code,
                COALESCE(trim(to_location_code),'') AS to_location_code,
                COALESCE(trim(to_overtime_plan_code),'') AS to_overtime_plan_code,
                COALESCE(trim(to_position_code),'') AS to_position_code,
                COALESCE(to_position_level_num,0) AS to_position_level_num,
                COALESCE(trim(to_process_level_code),'') AS to_process_level_code,
                COALESCE(trim(to_pay_grade_code),'') AS to_pay_grade_code,
                COALESCE(to_pay_step_num,0) AS to_pay_step_num,
                COALESCE(trim(to_salary_class_code),'') AS to_salary_class_code,
                COALESCE(trim(to_schedule_code),'') AS to_schedule_code,
                COALESCE(to_standard_hour,0) AS to_standard_hour,
                COALESCE(trim(to_supervisor_code),'') AS to_supervisor_code,
                COALESCE(trim(to_union_code),'') AS to_union_code,
                COALESCE(trim(to_user_level),'') AS to_user_level,
                COALESCE(trim(to_exemption_flag),'') AS to_exemption_flag,
                COALESCE(trim(to_expense_account_unit),'') AS to_expense_account_unit,
                COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
                COALESCE(trim(transfer_termination_flag),'') AS transfer_termination_flag,
                COALESCE(to_expense_company_num,0) AS to_expense_company_num,
                COALESCE(trim(active_dw_ind),'') AS active_dw_ind,
                lawson_company_num,
                process_level_code,
                security_key_text,
                COALESCE(trim(delete_ind),'') AS delete_ind,
                source_system_code ) 
        IN ( Select STRUCT (employee_action_sid,
                eff_from_date,
                MAX(valid_from_date),
                MAX(valid_to_date),
                action_code,
                employee_sid,
                COALESCE(employee_num,0) AS employee_num,
                action_sequence_num,
                action_from_date,
                action_to_date,
                COALESCE(trim(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
                COALESCE(trim(from_dept_code),'') AS from_dept_code,
                COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
                COALESCE(trim(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
                COALESCE(trim(from_job_code),'') AS from_job_code,
                COALESCE(trim(from_location_code),'') AS from_location_code,
                COALESCE(trim(from_overtime_plan_code),'') AS from_overtime_plan_code,
                COALESCE(trim(from_position_code),'') AS from_position_code,
                COALESCE(from_position_level_num,0) AS from_position_level_num,
                COALESCE(trim(from_process_level_code),'') AS from_process_level_code,
                COALESCE(from_payment_frequency,0) AS from_payment_frequency,
                COALESCE(trim(from_payment_grade_code),'') AS from_payment_grade_code,
                COALESCE(from_payment_step_num,0) AS from_payment_step_num,
                COALESCE(trim(from_salary_class_code),'') AS from_salary_class_code,
                COALESCE(trim(from_schedule_code),'') AS from_schedule_code,
                COALESCE(from_standard_hour,0) AS from_standard_hour,
                COALESCE(trim(from_supervisor_code),'') AS from_supervisor_code,
                COALESCE(trim(from_union_code),'') AS from_union_code,
                COALESCE(trim(from_user_level),'') AS from_user_level,
                COALESCE(trim(from_excemption_flag),'') AS from_excemption_flag,
                COALESCE(trim(from_expense_account_unit),'') AS from_expense_account_unit,
                COALESCE(from_expense_company,0) AS from_expense_company,
                COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
                COALESCE(trim(hr_code_desc),'') AS hr_code_desc,
                last_update_date,
                last_transfer_eff_date,
                COALESCE(trim(reason_desc),'') AS reason_desc,
                COALESCE(to_payment_frequency,0) AS to_payment_frequency,
                COALESCE(trim(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
                COALESCE(trim(to_dept_code),'') AS to_dept_code,
                COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
                COALESCE(trim(to_employee_schedule_code),'') AS to_employee_schedule_code,
                COALESCE(trim(to_job_code),'') AS to_job_code,
                COALESCE(trim(to_location_code),'') AS to_location_code,
                COALESCE(trim(to_overtime_plan_code),'') AS to_overtime_plan_code,
                COALESCE(trim(to_position_code),'') AS to_position_code,
                COALESCE(to_position_level_num,0) AS to_position_level_num,
                COALESCE(trim(to_process_level_code),'') AS to_process_level_code,
                COALESCE(trim(to_pay_grade_code),'') AS to_pay_grade_code,
                COALESCE(to_pay_step_num,0) AS to_pay_step_num,
                COALESCE(trim(to_salary_class_code),'') AS to_salary_class_code,
                COALESCE(trim(to_schedule_code),'') AS to_schedule_code,
                COALESCE(to_standard_hour,0) AS to_standard_hour,
                COALESCE(trim(to_supervisor_code),'') AS to_supervisor_code,
                COALESCE(trim(to_union_code),'') AS to_union_code,
                COALESCE(trim(to_user_level),'') AS to_user_level,
                COALESCE(trim(to_exemption_flag),'') AS to_exemption_flag,
                COALESCE(trim(to_expense_account_unit),'') AS to_expense_account_unit,
                COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
                COALESCE(trim(transfer_termination_flag),'') AS transfer_termination_flag,
                COALESCE(to_expense_company_num,0) AS to_expense_company_num,
                COALESCE(trim(active_dw_ind),'') AS active_dw_ind,
                lawson_company_num,
                process_level_code,
                security_key_text,
                COALESCE(trim(delete_ind),'') AS delete_ind,
                source_system_code )
                --dw_last_update_date_time 
                FROM  `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
                WHERE STRUCT (  employee_action_sid,
                                eff_from_date,
                                action_code,
                                employee_sid,
                                COALESCE(employee_num,0) AS employee_num,
                                action_sequence_num,
                                action_from_date,
                                action_to_date,
                                COALESCE(trim(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
                                COALESCE(trim(from_dept_code),'') AS from_dept_code,
                                COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
                                COALESCE(trim(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
                                COALESCE(trim(from_job_code),'') AS from_job_code,
                                COALESCE(trim(from_location_code),'') AS from_location_code,
                                COALESCE(trim(from_overtime_plan_code),'') AS from_overtime_plan_code,
                                COALESCE(trim(from_position_code),'') AS from_position_code,
                                COALESCE(from_position_level_num,0) AS from_position_level_num,
                                COALESCE(trim(from_process_level_code),'') AS from_process_level_code,
                                COALESCE(from_payment_frequency,0) AS from_payment_frequency,
                                COALESCE(trim(from_payment_grade_code),'') AS from_payment_grade_code,
                                COALESCE(from_payment_step_num,0) AS from_payment_step_num,
                                COALESCE(trim(from_salary_class_code),'') AS from_salary_class_code,
                                COALESCE(trim(from_schedule_code),'') AS from_schedule_code,
                                COALESCE(from_standard_hour,0) AS from_standard_hour,
                                COALESCE(trim(from_supervisor_code),'') AS from_supervisor_code,
                                COALESCE(trim(from_union_code),'') AS from_union_code,
                                COALESCE(trim(from_user_level),'') AS from_user_level,
                                COALESCE(trim(from_excemption_flag),'') AS from_excemption_flag,
                                COALESCE(trim(from_expense_account_unit),'') AS from_expense_account_unit,
                                COALESCE(from_expense_company,0) AS from_expense_company,
                                COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
                                COALESCE(trim(hr_code_desc),'') AS hr_code_desc,
                                last_update_date,
                                last_transfer_eff_date,
                                COALESCE(trim(reason_desc),'') AS reason_desc,
                                COALESCE(to_payment_frequency,0) AS to_payment_frequency,
                                COALESCE(trim(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
                                COALESCE(trim(to_dept_code),'') AS to_dept_code,
                                COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
                                COALESCE(trim(to_employee_schedule_code),'') AS to_employee_schedule_code,
                                COALESCE(trim(to_job_code),'') AS to_job_code,
                                COALESCE(trim(to_location_code),'') AS to_location_code,
                                COALESCE(trim(to_overtime_plan_code),'') AS to_overtime_plan_code,
                                COALESCE(trim(to_position_code),'') AS to_position_code,
                                COALESCE(to_position_level_num,0) AS to_position_level_num,
                                COALESCE(trim(to_process_level_code),'') AS to_process_level_code,
                                COALESCE(trim(to_pay_grade_code),'') AS to_pay_grade_code,
                                COALESCE(to_pay_step_num,0) AS to_pay_step_num,
                                COALESCE(trim(to_salary_class_code),'') AS to_salary_class_code,
                                COALESCE(trim(to_schedule_code),'') AS to_schedule_code,
                                COALESCE(to_standard_hour,0) AS to_standard_hour,
                                COALESCE(trim(to_supervisor_code),'') AS to_supervisor_code,
                                COALESCE(trim(to_union_code),'') AS to_union_code,
                                COALESCE(trim(to_user_level),'') AS to_user_level,
                                COALESCE(trim(to_exemption_flag),'') AS to_exemption_flag,
                                COALESCE(trim(to_expense_account_unit),'') AS to_expense_account_unit,
                                COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
                                COALESCE(trim(transfer_termination_flag),'') AS transfer_termination_flag,
                                COALESCE(to_expense_company_num,0) AS to_expense_company_num,
                                --COALESCE(trim(active_dw_ind),'') AS active_dw_ind,
                                lawson_company_num,
                                process_level_code,
                                security_key_text,
                                COALESCE(trim(delete_ind),'') AS delete_ind,
                                source_system_code  ) IN ( SELECT STRUCT (  employee_action_sid,
                                                                            eff_from_date,
                                                                            action_code,
                                                                            employee_sid,
                                                                            COALESCE(employee_num,0) AS employee_num,
                                                                            action_sequence_num,
                                                                            action_from_date,
                                                                            action_to_date,
                                                                            COALESCE(trim(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
                                                                            COALESCE(trim(from_dept_code),'') AS from_dept_code,
                                                                            COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
                                                                            COALESCE(trim(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
                                                                            COALESCE(trim(from_job_code),'') AS from_job_code,
                                                                            COALESCE(trim(from_location_code),'') AS from_location_code,
                                                                            COALESCE(trim(from_overtime_plan_code),'') AS from_overtime_plan_code,
                                                                            COALESCE(trim(from_position_code),'') AS from_position_code,
                                                                            COALESCE(from_position_level_num,0) AS from_position_level_num,
                                                                            COALESCE(trim(from_process_level_code),'') AS from_process_level_code,
                                                                            COALESCE(from_payment_frequency,0) AS from_payment_frequency,
                                                                            COALESCE(trim(from_payment_grade_code),'') AS from_payment_grade_code,
                                                                            COALESCE(from_payment_step_num,0) AS from_payment_step_num,
                                                                            COALESCE(trim(from_salary_class_code),'') AS from_salary_class_code,
                                                                            COALESCE(trim(from_schedule_code),'') AS from_schedule_code,
                                                                            COALESCE(from_standard_hour,0) AS from_standard_hour,
                                                                            COALESCE(trim(from_supervisor_code),'') AS from_supervisor_code,
                                                                            COALESCE(trim(from_union_code),'') AS from_union_code,
                                                                            COALESCE(trim(from_user_level),'') AS from_user_level,
                                                                            COALESCE(trim(from_excemption_flag),'') AS from_excemption_flag,
                                                                            COALESCE(trim(from_expense_account_unit),'') AS from_expense_account_unit,
                                                                            COALESCE(from_expense_company,0) AS from_expense_company,
                                                                            COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
                                                                            COALESCE(trim(hr_code_desc),'') AS hr_code_desc,
                                                                            last_update_date,
                                                                            last_transfer_eff_date,
                                                                            COALESCE(trim(reason_desc),'') AS reason_desc,
                                                                            COALESCE(to_payment_frequency,0) AS to_payment_frequency,
                                                                            COALESCE(trim(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
                                                                            COALESCE(trim(to_dept_code),'') AS to_dept_code,
                                                                            COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
                                                                            COALESCE(trim(to_employee_schedule_code),'') AS to_employee_schedule_code,
                                                                            COALESCE(trim(to_job_code),'') AS to_job_code,
                                                                            COALESCE(trim(to_location_code),'') AS to_location_code,
                                                                            COALESCE(trim(to_overtime_plan_code),'') AS to_overtime_plan_code,
                                                                            COALESCE(trim(to_position_code),'') AS to_position_code,
                                                                            COALESCE(to_position_level_num,0) AS to_position_level_num,
                                                                            COALESCE(trim(to_process_level_code),'') AS to_process_level_code,
                                                                            COALESCE(trim(to_pay_grade_code),'') AS to_pay_grade_code,
                                                                            COALESCE(to_pay_step_num,0) AS to_pay_step_num,
                                                                            COALESCE(trim(to_salary_class_code),'') AS to_salary_class_code,
                                                                            COALESCE(trim(to_schedule_code),'') AS to_schedule_code,
                                                                            COALESCE(to_standard_hour,0) AS to_standard_hour,
                                                                            COALESCE(trim(to_supervisor_code),'') AS to_supervisor_code,
                                                                            COALESCE(trim(to_union_code),'') AS to_union_code,
                                                                            COALESCE(trim(to_user_level),'') AS to_user_level,
                                                                            COALESCE(trim(to_exemption_flag),'') AS to_exemption_flag,
                                                                            COALESCE(trim(to_expense_account_unit),'') AS to_expense_account_unit,
                                                                            COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
                                                                            COALESCE(trim(transfer_termination_flag),'') AS transfer_termination_flag,
                                                                            COALESCE(to_expense_company_num,0) AS to_expense_company_num,
                                                                            --COALESCE(trim(active_dw_ind),'') AS active_dw_ind,
                                                                            lawson_company_num,
                                                                            process_level_code,
                                                                            security_key_text,
                                                                            COALESCE(trim(delete_ind),'') AS delete_ind,
                                                                            source_system_code)
                                                            FROM `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
                                                            WHERE DATE(valid_to_date) = '9999-12-31' 
                                                                and source_system_code='A'
                                                            GROUP BY employee_action_sid,
                                                                    eff_from_date,
                                                                    action_code,
                                                                    employee_sid,
                                                                    employee_num,
                                                                    action_sequence_num,
                                                                    action_from_date,
                                                                    action_to_date,
                                                                    from_auxiliary_status_code,
                                                                    from_dept_code,
                                                                    from_employee_pay_rate_amount,
                                                                    from_employee_work_schedule_code,
                                                                    from_job_code,
                                                                    from_location_code,
                                                                    from_overtime_plan_code,
                                                                    from_position_code,
                                                                    from_position_level_num,
                                                                    from_process_level_code,
                                                                    from_payment_frequency,
                                                                    from_payment_grade_code,
                                                                    from_payment_step_num,
                                                                    from_salary_class_code,
                                                                    from_schedule_code,
                                                                    from_standard_hour,
                                                                    from_supervisor_code,
                                                                    from_union_code,
                                                                    from_user_level,
                                                                    from_excemption_flag,
                                                                    from_expense_account_unit,
                                                                    from_expense_company,
                                                                    from_expense_sub_account_num,
                                                                    hr_code_desc,
                                                                    last_update_date,
                                                                    last_transfer_eff_date,
                                                                    reason_desc,
                                                                    to_payment_frequency,
                                                                    to_auxiliary_status_code,
                                                                    to_dept_code,
                                                                    to_employee_pay_rate_amt,
                                                                    to_employee_schedule_code,
                                                                    to_job_code,
                                                                    to_location_code,
                                                                    to_overtime_plan_code,
                                                                    to_position_code,
                                                                    to_position_level_num,
                                                                    to_process_level_code,
                                                                    to_pay_grade_code,
                                                                    to_pay_step_num,
                                                                    to_salary_class_code,
                                                                    to_schedule_code,
                                                                    to_standard_hour,
                                                                    to_supervisor_code,
                                                                    to_union_code,
                                                                    to_user_level,
                                                                    to_exemption_flag,
                                                                    to_expense_account_unit,
                                                                    to_expense_sub_account_num,
                                                                    transfer_termination_flag,
                                                                    to_expense_company_num,
                                                                    active_dw_ind,
                                                                    lawson_company_num,
                                                                    process_level_code,
                                                                    security_key_text,
                                                                    delete_ind,
                                                                    source_system_code
                                                            Having Count(*) > 1 )
                                AND Date(valid_to_date) <> '9999-12-31'
                                AND source_system_code='A'
                        GROUP BY employee_action_sid,
                            eff_from_date,
                                                                    action_code,
                                                                    employee_sid,
                                                                    employee_num,
                                                                    action_sequence_num,
                                                                    action_from_date,
                                                                    action_to_date,
                                                                    from_auxiliary_status_code,
                                                                    from_dept_code,
                                                                    from_employee_pay_rate_amount,
                                                                    from_employee_work_schedule_code,
                                                                    from_job_code,
                                                                    from_location_code,
                                                                    from_overtime_plan_code,
                                                                    from_position_code,
                                                                    from_position_level_num,
                                                                    from_process_level_code,
                                                                    from_payment_frequency,
                                                                    from_payment_grade_code,
                                                                    from_payment_step_num,
                                                                    from_salary_class_code,
                                                                    from_schedule_code,
                                                                    from_standard_hour,
                                                                    from_supervisor_code,
                                                                    from_union_code,
                                                                    from_user_level,
                                                                    from_excemption_flag,
                                                                    from_expense_account_unit,
                                                                    from_expense_company,
                                                                    from_expense_sub_account_num,
                                                                    hr_code_desc,
                                                                    last_update_date,
                                                                    last_transfer_eff_date,
                                                                    reason_desc,
                                                                    to_payment_frequency,
                                                                    to_auxiliary_status_code,
                                                                    to_dept_code,
                                                                    to_employee_pay_rate_amt,
                                                                    to_employee_schedule_code,
                                                                    to_job_code,
                                                                    to_location_code,
                                                                    to_overtime_plan_code,
                                                                    to_position_code,
                                                                    to_position_level_num,
                                                                    to_process_level_code,
                                                                    to_pay_grade_code,
                                                                    to_pay_step_num,
                                                                    to_salary_class_code,
                                                                    to_schedule_code,
                                                                    to_standard_hour,
                                                                    to_supervisor_code,
                                                                    to_union_code,
                                                                    to_user_level,
                                                                    to_exemption_flag,
                                                                    to_expense_account_unit,
                                                                    to_expense_sub_account_num,
                                                                    transfer_termination_flag,
                                                                    to_expense_company_num,
                                                                    active_dw_ind,
                                                                    lawson_company_num,
                                                                    process_level_code,
                                                                    security_key_text,
                                                                    delete_ind,
                                                                    source_system_code )   ;                                  
                                                    


/* Delete the duplicate records */ 

 DELETE
FROM
  `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
WHERE
  STRUCT ( employee_action_sid,
    eff_from_date,
    action_code,
    employee_sid,
    COALESCE(employee_num,0) AS employee_num,
    action_sequence_num,
    action_from_date,
    action_to_date,
    COALESCE(TRIM(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
    COALESCE(TRIM(from_dept_code),'') AS from_dept_code,
    COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
    COALESCE(TRIM(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
    COALESCE(TRIM(from_job_code),'') AS from_job_code,
    COALESCE(TRIM(from_location_code),'') AS from_location_code,
    COALESCE(TRIM(from_overtime_plan_code),'') AS from_overtime_plan_code,
    COALESCE(TRIM(from_position_code),'') AS from_position_code,
    COALESCE(from_position_level_num,0) AS from_position_level_num,
    COALESCE(TRIM(from_process_level_code),'') AS from_process_level_code,
    COALESCE(from_payment_frequency,0) AS from_payment_frequency,
    COALESCE(TRIM(from_payment_grade_code),'') AS from_payment_grade_code,
    COALESCE(from_payment_step_num,0) AS from_payment_step_num,
    COALESCE(TRIM(from_salary_class_code),'') AS from_salary_class_code,
    COALESCE(TRIM(from_schedule_code),'') AS from_schedule_code,
    COALESCE(from_standard_hour,0) AS from_standard_hour,
    COALESCE(TRIM(from_supervisor_code),'') AS from_supervisor_code,
    COALESCE(TRIM(from_union_code),'') AS from_union_code,
    COALESCE(TRIM(from_user_level),'') AS from_user_level,
    COALESCE(TRIM(from_excemption_flag),'') AS from_excemption_flag,
    COALESCE(TRIM(from_expense_account_unit),'') AS from_expense_account_unit,
    COALESCE(from_expense_company,0) AS from_expense_company,
    COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
    COALESCE(TRIM(hr_code_desc),'') AS hr_code_desc,
    last_update_date,
    last_transfer_eff_date,
    COALESCE(TRIM(reason_desc),'') AS reason_desc,
    COALESCE(to_payment_frequency,0) AS to_payment_frequency,
    COALESCE(TRIM(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
    COALESCE(TRIM(to_dept_code),'') AS to_dept_code,
    COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
    COALESCE(TRIM(to_employee_schedule_code),'') AS to_employee_schedule_code,
    COALESCE(TRIM(to_job_code),'') AS to_job_code,
    COALESCE(TRIM(to_location_code),'') AS to_location_code,
    COALESCE(TRIM(to_overtime_plan_code),'') AS to_overtime_plan_code,
    COALESCE(TRIM(to_position_code),'') AS to_position_code,
    COALESCE(to_position_level_num,0) AS to_position_level_num,
    COALESCE(TRIM(to_process_level_code),'') AS to_process_level_code,
    COALESCE(TRIM(to_pay_grade_code),'') AS to_pay_grade_code,
    COALESCE(to_pay_step_num,0) AS to_pay_step_num,
    COALESCE(TRIM(to_salary_class_code),'') AS to_salary_class_code,
    COALESCE(TRIM(to_schedule_code),'') AS to_schedule_code,
    COALESCE(to_standard_hour,0) AS to_standard_hour,
    COALESCE(TRIM(to_supervisor_code),'') AS to_supervisor_code,
    COALESCE(TRIM(to_union_code),'') AS to_union_code,
    COALESCE(TRIM(to_user_level),'') AS to_user_level,
    COALESCE(TRIM(to_exemption_flag),'') AS to_exemption_flag,
    COALESCE(TRIM(to_expense_account_unit),'') AS to_expense_account_unit,
    COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
    COALESCE(TRIM(transfer_termination_flag),'') AS transfer_termination_flag,
    COALESCE(to_expense_company_num,0) AS to_expense_company_num,
    --COALESCE(TRIM(active_dw_ind),'') AS active_dw_ind,
    lawson_company_num,
    process_level_code,
    security_key_text,
    COALESCE(TRIM(delete_ind),'') AS delete_ind,
    source_system_code ) IN (
                              SELECT
                                STRUCT ( employee_action_sid,
                                  eff_from_date,
                                  action_code,
                                  employee_sid,
                                  COALESCE(employee_num,0) AS employee_num,
                                  action_sequence_num,
                                  action_from_date,
                                  action_to_date,
                                  COALESCE(TRIM(from_auxiliary_status_code),'') AS from_auxiliary_status_code,
                                  COALESCE(TRIM(from_dept_code),'') AS from_dept_code,
                                  COALESCE(from_employee_pay_rate_amount,0) AS from_employee_pay_rate_amount,
                                  COALESCE(TRIM(from_employee_work_schedule_code),'') AS from_employee_work_schedule_code,
                                  COALESCE(TRIM(from_job_code),'') AS from_job_code,
                                  COALESCE(TRIM(from_location_code),'') AS from_location_code,
                                  COALESCE(TRIM(from_overtime_plan_code),'') AS from_overtime_plan_code,
                                  COALESCE(TRIM(from_position_code),'') AS from_position_code,
                                  COALESCE(from_position_level_num,0) AS from_position_level_num,
                                  COALESCE(TRIM(from_process_level_code),'') AS from_process_level_code,
                                  COALESCE(from_payment_frequency,0) AS from_payment_frequency,
                                  COALESCE(TRIM(from_payment_grade_code),'') AS from_payment_grade_code,
                                  COALESCE(from_payment_step_num,0) AS from_payment_step_num,
                                  COALESCE(TRIM(from_salary_class_code),'') AS from_salary_class_code,
                                  COALESCE(TRIM(from_schedule_code),'') AS from_schedule_code,
                                  COALESCE(from_standard_hour,0) AS from_standard_hour,
                                  COALESCE(TRIM(from_supervisor_code),'') AS from_supervisor_code,
                                  COALESCE(TRIM(from_union_code),'') AS from_union_code,
                                  COALESCE(TRIM(from_user_level),'') AS from_user_level,
                                  COALESCE(TRIM(from_excemption_flag),'') AS from_excemption_flag,
                                  COALESCE(TRIM(from_expense_account_unit),'') AS from_expense_account_unit,
                                  COALESCE(from_expense_company,0) AS from_expense_company,
                                  COALESCE(from_expense_sub_account_num,0) AS from_expense_sub_account_num,
                                  COALESCE(TRIM(hr_code_desc),'') AS hr_code_desc,
                                  last_update_date,
                                  last_transfer_eff_date,
                                  COALESCE(TRIM(reason_desc),'') AS reason_desc,
                                  COALESCE(to_payment_frequency,0) AS to_payment_frequency,
                                  COALESCE(TRIM(to_auxiliary_status_code),'') AS to_auxiliary_status_code,
                                  COALESCE(TRIM(to_dept_code),'') AS to_dept_code,
                                  COALESCE(to_employee_pay_rate_amt,0) AS to_employee_pay_rate_amt,
                                  COALESCE(TRIM(to_employee_schedule_code),'') AS to_employee_schedule_code,
                                  COALESCE(TRIM(to_job_code),'') AS to_job_code,
                                  COALESCE(TRIM(to_location_code),'') AS to_location_code,
                                  COALESCE(TRIM(to_overtime_plan_code),'') AS to_overtime_plan_code,
                                  COALESCE(TRIM(to_position_code),'') AS to_position_code,
                                  COALESCE(to_position_level_num,0) AS to_position_level_num,
                                  COALESCE(TRIM(to_process_level_code),'') AS to_process_level_code,
                                  COALESCE(TRIM(to_pay_grade_code),'') AS to_pay_grade_code,
                                  COALESCE(to_pay_step_num,0) AS to_pay_step_num,
                                  COALESCE(TRIM(to_salary_class_code),'') AS to_salary_class_code,
                                  COALESCE(TRIM(to_schedule_code),'') AS to_schedule_code,
                                  COALESCE(to_standard_hour,0) AS to_standard_hour,
                                  COALESCE(TRIM(to_supervisor_code),'') AS to_supervisor_code,
                                  COALESCE(TRIM(to_union_code),'') AS to_union_code,
                                  COALESCE(TRIM(to_user_level),'') AS to_user_level,
                                  COALESCE(TRIM(to_exemption_flag),'') AS to_exemption_flag,
                                  COALESCE(TRIM(to_expense_account_unit),'') AS to_expense_account_unit,
                                  COALESCE(to_expense_sub_account_num,0) AS to_expense_sub_account_num,
                                  COALESCE(TRIM(transfer_termination_flag),'') AS transfer_termination_flag,
                                  COALESCE(to_expense_company_num,0) AS to_expense_company_num,
                                  --COALESCE(TRIM(active_dw_ind),'') AS active_dw_ind,
                                  lawson_company_num,
                                  process_level_code,
                                  security_key_text,
                                  COALESCE(TRIM(delete_ind),'') AS delete_ind,
                                  source_system_code)
                              FROM
                                `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
                              WHERE
                                DATE(valid_to_date) = '9999-12-31'
                                AND source_system_code='A'
                              GROUP BY
                                employee_action_sid,
                                eff_from_date,
                                action_code,
                                employee_sid,
                                employee_num,
                                action_sequence_num,
                                action_from_date,
                                action_to_date,
                                from_auxiliary_status_code,
                                from_dept_code,
                                from_employee_pay_rate_amount,
                                from_employee_work_schedule_code,
                                from_job_code,
                                from_location_code,
                                from_overtime_plan_code,
                                from_position_code,
                                from_position_level_num,
                                from_process_level_code,
                                from_payment_frequency,
                                from_payment_grade_code,
                                from_payment_step_num,
                                from_salary_class_code,
                                from_schedule_code,
                                from_standard_hour,
                                from_supervisor_code,
                                from_union_code,
                                from_user_level,
                                from_excemption_flag,
                                from_expense_account_unit,
                                from_expense_company,
                                from_expense_sub_account_num,
                                hr_code_desc,
                                last_update_date,
                                last_transfer_eff_date,
                                reason_desc,
                                to_payment_frequency,
                                to_auxiliary_status_code,
                                to_dept_code,
                                to_employee_pay_rate_amt,
                                to_employee_schedule_code,
                                to_job_code,
                                to_location_code,
                                to_overtime_plan_code,
                                to_position_code,
                                to_position_level_num,
                                to_process_level_code,
                                to_pay_grade_code,
                                to_pay_step_num,
                                to_salary_class_code,
                                to_schedule_code,
                                to_standard_hour,
                                to_supervisor_code,
                                to_union_code,
                                to_user_level,
                                to_exemption_flag,
                                to_expense_account_unit,
                                to_expense_sub_account_num,
                                transfer_termination_flag,
                                to_expense_company_num,
                                active_dw_ind,
                                lawson_company_num,
                                process_level_code,
                                security_key_text,
                                delete_ind,
                                source_system_code
                              HAVING
                                COUNT(*) > 1 
                            )
  AND DATE(valid_to_date) = '9999-12-31'
  AND source_system_code='A'
  AND active_dw_ind = 'Y';                            

-- Update Part 2 

UPDATE `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
SET active_dw_ind = 'Y'
WHERE DATE(valid_to_date) = '9999-12-31' 
AND source_system_code='A'
AND active_dw_ind = 'N';

-- Update Part 3 

UPDATE `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
SET valid_to_date = '9999-12-31T23:59:59' 
WHERE source_system_code = 'A' 
AND date(valid_to_date) = '2023-05-05' 
AND struct(employee_action_sid, employee_sid, employee_num) 
        IN (SELECT struct(employee_action_sid, employee_sid, employee_num) 
            FROM `hca-hin-dev-cur-hr.edwhr_base_views.employee_action_detail`
            WHERE source_system_code = 'A' 
            AND date(valid_to_date) = '9999-12-31');
/*
-- Verification
Select 'GCP-Count', Source_system_code,  Count(*) from  `hca-hin-prod-cur-hr.edwhr.employee_action_detail`
WHERE DATE(valid_to_date) = '9999-12-31' 
Group By Source_system_code;

Select 'TD-Count', Source_system_code,  Count(*) from  `hca-hin-dev-cur-hr.edwhr_base_views.employee_action_detail`
WHERE DATE(valid_to_date) = '9999-12-31' 
Group By Source_system_code;
*/

----------------END------------------------------------------------------------------------