CREATE OR REPLACE VIEW edwpsc_views.`ccu_factmtxinventory`
AS SELECT
  `ccu_factmtxinventory`.ccumtxinventorykey,
  `ccu_factmtxinventory`.sourcesystem,
  `ccu_factmtxinventory`.owner,
  `ccu_factmtxinventory`.regionkey,
  `ccu_factmtxinventory`.coid,
  `ccu_factmtxinventory`.ccugolivestatus,
  `ccu_factmtxinventory`.ccugolivedate,
  `ccu_factmtxinventory`.assignedtovendor,
  `ccu_factmtxinventory`.vendorname,
  `ccu_factmtxinventory`.vendorassigneddate,
  `ccu_factmtxinventory`.practicekey,
  `ccu_factmtxinventory`.facilitykey,
  `ccu_factmtxinventory`.encounterid,
  `ccu_factmtxinventory`.servicedate,
  `ccu_factmtxinventory`.patientkey,
  `ccu_factmtxinventory`.servicingproviderkey,
  `ccu_factmtxinventory`.servicingproviderspecialty,
  `ccu_factmtxinventory`.servicingproviderspecialtycategory,
  `ccu_factmtxinventory`.visitstatusdescription,
  `ccu_factmtxinventory`.encounterlockeddate,
  `ccu_factmtxinventory`.inventorytype,
  `ccu_factmtxinventory`.claimvsencounterflag,
  `ccu_factmtxinventory`.sourcelastupdateddatetime,
  `ccu_factmtxinventory`.groupassignment,
  `ccu_factmtxinventory`.servicedateconsolidationdateflag,
  `ccu_factmtxinventory`.pos,
  `ccu_factmtxinventory`.encountermtxkey,
  `ccu_factmtxinventory`.loaddate,
  `ccu_factmtxinventory`.worked,
  `ccu_factmtxinventory`.workeddate,
  `ccu_factmtxinventory`.encounterlastmodifieddate,
  `ccu_factmtxinventory`.dayssincemodifieddate,
  `ccu_factmtxinventory`.dayssinceservicedate,
  `ccu_factmtxinventory`.busincessdayssinceservicedate,
  `ccu_factmtxinventory`.busincessdayssincelastmodified,
  `ccu_factmtxinventory`.procedurecategory1,
  `ccu_factmtxinventory`.procedurecategory2,
  `ccu_factmtxinventory`.cptcodes,
  `ccu_factmtxinventory`.ccunoncustomerconfigkey,
  `ccu_factmtxinventory`.ccunoncustomernpiconfigkey,
  `ccu_factmtxinventory`.dwlastupdatedatetime,
  `ccu_factmtxinventory`.insertedby,
  `ccu_factmtxinventory`.inserteddtm,
  `ccu_factmtxinventory`.modifiedby,
  `ccu_factmtxinventory`.modifieddtm,
  `ccu_factmtxinventory`.cptmodifiers,
  `ccu_factmtxinventory`.icdcodes
  FROM
    edwpsc_base_views.`ccu_factmtxinventory`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`ccu_factmtxinventory`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;