CREATE OR REPLACE VIEW edwpsc_views.`ccu_factpvinventory`
AS SELECT
  `ccu_factpvinventory`.ccupvinventorykey,
  `ccu_factpvinventory`.regionkey,
  `ccu_factpvinventory`.facilitykey,
  `ccu_factpvinventory`.coid,
  `ccu_factpvinventory`.assignedtovendor,
  `ccu_factpvinventory`.vendorname,
  `ccu_factpvinventory`.vendorassigneddate,
  `ccu_factpvinventory`.servicedate,
  `ccu_factpvinventory`.servicingproviderkey,
  `ccu_factpvinventory`.servicingproviderspecialty,
  `ccu_factpvinventory`.servicingproviderspecialtycategory,
  `ccu_factpvinventory`.vendorassigned,
  `ccu_factpvinventory`.claimlastupdateddate,
  `ccu_factpvinventory`.dayssinceclaimlastupdateddate,
  `ccu_factpvinventory`.claimnumber,
  `ccu_factpvinventory`.totalchargesamt,
  `ccu_factpvinventory`.totalbalanceamt,
  `ccu_factpvinventory`.totalinsurancebalanceamt,
  `ccu_factpvinventory`.holdcode,
  `ccu_factpvinventory`.encounterid,
  `ccu_factpvinventory`.sourcesystem,
  `ccu_factpvinventory`.owner,
  `ccu_factpvinventory`.inventorytype,
  `ccu_factpvinventory`.dwlastupdatedatetime,
  `ccu_factpvinventory`.groupassignment,
  `ccu_factpvinventory`.claimkey,
  `ccu_factpvinventory`.visittypekey,
  `ccu_factpvinventory`.visitstatuskey,
  `ccu_factpvinventory`.patientkey,
  `ccu_factpvinventory`.loaddate,
  `ccu_factpvinventory`.worked,
  `ccu_factpvinventory`.workeddate,
  `ccu_factpvinventory`.ccunoncustomerconfigkey,
  `ccu_factpvinventory`.insertedby,
  `ccu_factpvinventory`.inserteddtm,
  `ccu_factpvinventory`.modifiedby,
  `ccu_factpvinventory`.modifieddtm,
  `ccu_factpvinventory`.encounterkey,
  `ccu_factpvinventory`.sourcelastupdateddatetime,
  `ccu_factpvinventory`.ccunoncustomernpiconfigkey,
  `ccu_factpvinventory`.procedurecategory1,
  `ccu_factpvinventory`.procedurecategory2,
  `ccu_factpvinventory`.cptcodes,
  `ccu_factpvinventory`.busincessdayssinceservicedate,
  `ccu_factpvinventory`.dayssinceservicedate,
  `ccu_factpvinventory`.busincessdayssincelastmodified,
  `ccu_factpvinventory`.cptmodifiers,
  `ccu_factpvinventory`.icdcodes
  FROM
    edwpsc_base_views.`ccu_factpvinventory`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`ccu_factpvinventory`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;