CREATE OR REPLACE VIEW edwpsc_views.`ccu_factmedaxioninventory`
AS SELECT
  `ccu_factmedaxioninventory`.ccumedaxioninventorykey,
  `ccu_factmedaxioninventory`.sourcesystem,
  `ccu_factmedaxioninventory`.owner,
  `ccu_factmedaxioninventory`.regionkey,
  `ccu_factmedaxioninventory`.coid,
  `ccu_factmedaxioninventory`.ccugolivestatus,
  `ccu_factmedaxioninventory`.ccugolivedate,
  `ccu_factmedaxioninventory`.assignedtovendor,
  `ccu_factmedaxioninventory`.vendorname,
  `ccu_factmedaxioninventory`.vendorassigneddate,
  `ccu_factmedaxioninventory`.practicekey,
  `ccu_factmedaxioninventory`.facilitykey,
  `ccu_factmedaxioninventory`.encounterid,
  `ccu_factmedaxioninventory`.servicedate,
  `ccu_factmedaxioninventory`.patientkey,
  `ccu_factmedaxioninventory`.servicingproviderkey,
  `ccu_factmedaxioninventory`.servicingproviderspecialty,
  `ccu_factmedaxioninventory`.servicingproviderspecialtycategory,
  `ccu_factmedaxioninventory`.visitstatusdescription,
  `ccu_factmedaxioninventory`.encounterlockeddate,
  `ccu_factmedaxioninventory`.inventorytype,
  `ccu_factmedaxioninventory`.claimvsencounterflag,
  `ccu_factmedaxioninventory`.sourcelastupdateddatetime,
  `ccu_factmedaxioninventory`.groupassignment,
  `ccu_factmedaxioninventory`.servicedateconsolidationdateflag,
  `ccu_factmedaxioninventory`.pos,
  `ccu_factmedaxioninventory`.encountermedaxionkey,
  `ccu_factmedaxioninventory`.loaddate,
  `ccu_factmedaxioninventory`.worked,
  `ccu_factmedaxioninventory`.workeddate,
  `ccu_factmedaxioninventory`.encounterlastmodifieddate,
  `ccu_factmedaxioninventory`.dayssincemodifieddate,
  `ccu_factmedaxioninventory`.dayssinceservicedate,
  `ccu_factmedaxioninventory`.busincessdayssinceservicedate,
  `ccu_factmedaxioninventory`.busincessdayssincelastmodified,
  `ccu_factmedaxioninventory`.procedurecategory1,
  `ccu_factmedaxioninventory`.procedurecategory2,
  `ccu_factmedaxioninventory`.cptcodes,
  `ccu_factmedaxioninventory`.ccunoncustomerconfigkey,
  `ccu_factmedaxioninventory`.ccunoncustomernpiconfigkey,
  `ccu_factmedaxioninventory`.dwlastupdatedatetime,
  `ccu_factmedaxioninventory`.insertedby,
  `ccu_factmedaxioninventory`.inserteddtm,
  `ccu_factmedaxioninventory`.modifiedby,
  `ccu_factmedaxioninventory`.modifieddtm,
  `ccu_factmedaxioninventory`.cptmodifiers,
  `ccu_factmedaxioninventory`.icdcodes
  FROM
    edwpsc_base_views.`ccu_factmedaxioninventory`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`ccu_factmedaxioninventory`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;