CREATE OR REPLACE VIEW edwpsc_views.`ccu_factpvcodequality`
AS SELECT
  `ccu_factpvcodequality`.codequalitykey,
  `ccu_factpvcodequality`.claimkey,
  `ccu_factpvcodequality`.claimnumber,
  `ccu_factpvcodequality`.regionkey,
  `ccu_factpvcodequality`.practiceid,
  `ccu_factpvcodequality`.coid,
  `ccu_factpvcodequality`.servicedate,
  `ccu_factpvcodequality`.claimcreatedate,
  `ccu_factpvcodequality`.initialcoderprebilleditdate,
  `ccu_factpvcodequality`.firstinsurancebilldate,
  `ccu_factpvcodequality`.minfirstdenialeradate,
  `ccu_factpvcodequality`.numberofinsurancebills,
  `ccu_factpvcodequality`.coderprebilleditcount,
  `ccu_factpvcodequality`.psscactgrp_initial_combined,
  `ccu_factpvcodequality`.pssccat_initial_combined,
  `ccu_factpvcodequality`.psscsubcatdesc_initial_combined,
  `ccu_factpvcodequality`.payer1iplanname,
  `ccu_factpvcodequality`.qualitycategory,
  `ccu_factpvcodequality`.totalchargesamt,
  `ccu_factpvcodequality`.paymentamt,
  `ccu_factpvcodequality`.contractualadjamt,
  `ccu_factpvcodequality`.financialadjamt,
  `ccu_factpvcodequality`.financialadjcategory_combined,
  `ccu_factpvcodequality`.financialadjname_combined,
  `ccu_factpvcodequality`.firstdenialcategories,
  `ccu_factpvcodequality`.firstdenialcarccodes,
  `ccu_factpvcodequality`.firstdenialrarccodes,
  `ccu_factpvcodequality`.firstdenialpayername,
  `ccu_factpvcodequality`.claimcreatedby34id,
  `ccu_factpvcodequality`.claimcreatedbyuser,
  `ccu_factpvcodequality`.claimcreatedbydept,
  `ccu_factpvcodequality`.claimcreatedbycompany,
  `ccu_factpvcodequality`.claimcount,
  `ccu_factpvcodequality`.dwlastupdatedatetime,
  `ccu_factpvcodequality`.sourcesystemcode,
  `ccu_factpvcodequality`.hashnomatch,
  `ccu_factpvcodequality`.insertedby,
  `ccu_factpvcodequality`.inserteddtm,
  `ccu_factpvcodequality`.modifiedby,
  `ccu_factpvcodequality`.modifieddtm,
  `ccu_factpvcodequality`.lastchangedby,
  `ccu_factpvcodequality`.changeddate
  FROM
    edwpsc_base_views.`ccu_factpvcodequality`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`ccu_factpvcodequality`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;