CREATE OR REPLACE VIEW edwpsc_views.`ecw_factsnapshottransactioncharge`
AS SELECT
  `ecw_factsnapshottransactioncharge`.transactionchargesmrykey,
  `ecw_factsnapshottransactioncharge`.monthid,
  `ecw_factsnapshottransactioncharge`.snapshotdate,
  `ecw_factsnapshottransactioncharge`.regionkey,
  `ecw_factsnapshottransactioncharge`.coid,
  `ecw_factsnapshottransactioncharge`.gldepartment,
  `ecw_factsnapshottransactioncharge`.claimkey,
  `ecw_factsnapshottransactioncharge`.claimnumber,
  `ecw_factsnapshottransactioncharge`.patientkey,
  `ecw_factsnapshottransactioncharge`.patientid,
  `ecw_factsnapshottransactioncharge`.servicingproviderkey,
  `ecw_factsnapshottransactioncharge`.servicingproviderid,
  `ecw_factsnapshottransactioncharge`.renderingproviderkey,
  `ecw_factsnapshottransactioncharge`.renderingproviderid,
  `ecw_factsnapshottransactioncharge`.facilitykey,
  `ecw_factsnapshottransactioncharge`.facilityid,
  `ecw_factsnapshottransactioncharge`.claimdatekey,
  `ecw_factsnapshottransactioncharge`.servicedatekey,
  `ecw_factsnapshottransactioncharge`.iplan1iplankey,
  `ecw_factsnapshottransactioncharge`.iplan1id,
  `ecw_factsnapshottransactioncharge`.financialclasskey,
  `ecw_factsnapshottransactioncharge`.transactionamt,
  `ecw_factsnapshottransactioncharge`.transactiondatemonthid,
  `ecw_factsnapshottransactioncharge`.cptcodekey,
  `ecw_factsnapshottransactioncharge`.cptcode,
  `ecw_factsnapshottransactioncharge`.cptunitchangeamt,
  `ecw_factsnapshottransactioncharge`.dwlastupdatedatetime,
  `ecw_factsnapshottransactioncharge`.sourcesystemcode,
  `ecw_factsnapshottransactioncharge`.insertedby,
  `ecw_factsnapshottransactioncharge`.inserteddtm,
  `ecw_factsnapshottransactioncharge`.modifiedby,
  `ecw_factsnapshottransactioncharge`.modifieddtm,
  `ecw_factsnapshottransactioncharge`.transactiontype,
  `ecw_factsnapshottransactioncharge`.cptid,
  `ecw_factsnapshottransactioncharge`.cptmodifier1,
  `ecw_factsnapshottransactioncharge`.cptmodifier2,
  `ecw_factsnapshottransactioncharge`.cptmodifier3,
  `ecw_factsnapshottransactioncharge`.cptmodifier4,
  `ecw_factsnapshottransactioncharge`.cptunitsonline,
  `ecw_factsnapshottransactioncharge`.cpttos,
  `ecw_factsnapshottransactioncharge`.cptchargeschangeamt,
  `ecw_factsnapshottransactioncharge`.cptstartdos,
  `ecw_factsnapshottransactioncharge`.cptenddos,
  `ecw_factsnapshottransactioncharge`.cptseqnum,
  `ecw_factsnapshottransactioncharge`.transactionid,
  `ecw_factsnapshottransactioncharge`.transactiondatekey,
  `ecw_factsnapshottransactioncharge`.claimdatemonthid,
  `ecw_factsnapshottransactioncharge`.servicedatemonthid,
  `ecw_factsnapshottransactioncharge`.claimlinechargekey,
  `ecw_factsnapshottransactioncharge`.transactionsamemonthflag
  FROM
    edwpsc_base_views.`ecw_factsnapshottransactioncharge`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`ecw_factsnapshottransactioncharge`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;