CREATE OR REPLACE VIEW edwpsc_views.`epic_factsnapshottransactioncharge`
AS SELECT
  `epic_factsnapshottransactioncharge`.transactionchargesmrykey,
  `epic_factsnapshottransactioncharge`.monthid,
  `epic_factsnapshottransactioncharge`.snapshotdate,
  `epic_factsnapshottransactioncharge`.regionkey,
  `epic_factsnapshottransactioncharge`.practicekey,
  `epic_factsnapshottransactioncharge`.practiceid,
  `epic_factsnapshottransactioncharge`.coid,
  `epic_factsnapshottransactioncharge`.gldepartment,
  `epic_factsnapshottransactioncharge`.claimkey,
  `epic_factsnapshottransactioncharge`.claimnumber,
  `epic_factsnapshottransactioncharge`.visitnumber,
  `epic_factsnapshottransactioncharge`.transactionnumber,
  `epic_factsnapshottransactioncharge`.patientkey,
  `epic_factsnapshottransactioncharge`.patientid,
  `epic_factsnapshottransactioncharge`.servicingproviderkey,
  `epic_factsnapshottransactioncharge`.servicingproviderid,
  `epic_factsnapshottransactioncharge`.renderingproviderkey,
  `epic_factsnapshottransactioncharge`.renderingproviderid,
  `epic_factsnapshottransactioncharge`.facilitykey,
  `epic_factsnapshottransactioncharge`.facilityid,
  `epic_factsnapshottransactioncharge`.claimdatekey,
  `epic_factsnapshottransactioncharge`.servicedatekey,
  `epic_factsnapshottransactioncharge`.iplan1iplankey,
  `epic_factsnapshottransactioncharge`.iplan1id,
  `epic_factsnapshottransactioncharge`.financialclasskey,
  `epic_factsnapshottransactioncharge`.transactionamt,
  `epic_factsnapshottransactioncharge`.transactiondatemonthid,
  `epic_factsnapshottransactioncharge`.cptcodekey,
  `epic_factsnapshottransactioncharge`.cptcode,
  `epic_factsnapshottransactioncharge`.cptunitchangeamt,
  `epic_factsnapshottransactioncharge`.transactiontype,
  `epic_factsnapshottransactioncharge`.cptid,
  `epic_factsnapshottransactioncharge`.cptmodifier1,
  `epic_factsnapshottransactioncharge`.cptmodifier2,
  `epic_factsnapshottransactioncharge`.cptmodifier3,
  `epic_factsnapshottransactioncharge`.cptmodifier4,
  `epic_factsnapshottransactioncharge`.cptunitsonline,
  `epic_factsnapshottransactioncharge`.cpttos,
  `epic_factsnapshottransactioncharge`.cptchargeschangeamt,
  `epic_factsnapshottransactioncharge`.cptstartdos,
  `epic_factsnapshottransactioncharge`.cptenddos,
  `epic_factsnapshottransactioncharge`.cptseqnum,
  `epic_factsnapshottransactioncharge`.transactionid,
  `epic_factsnapshottransactioncharge`.transactiondatekey,
  `epic_factsnapshottransactioncharge`.claimdatemonthid,
  `epic_factsnapshottransactioncharge`.servicedatemonthid,
  `epic_factsnapshottransactioncharge`.sourcesystemcode,
  `epic_factsnapshottransactioncharge`.dwlastupdatedatetime,
  `epic_factsnapshottransactioncharge`.transactionsamemonthflag
  FROM
    edwpsc_base_views.`epic_factsnapshottransactioncharge`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`epic_factsnapshottransactioncharge`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;