CREATE OR REPLACE VIEW edwpsc_views.`epic_factsnapshottransactionpayment`
AS SELECT
  `epic_factsnapshottransactionpayment`.transactionpaymentkey,
  `epic_factsnapshottransactionpayment`.monthid,
  `epic_factsnapshottransactionpayment`.snapshotdate,
  `epic_factsnapshottransactionpayment`.regionkey,
  `epic_factsnapshottransactionpayment`.practicekey,
  `epic_factsnapshottransactionpayment`.practiceid,
  `epic_factsnapshottransactionpayment`.coid,
  `epic_factsnapshottransactionpayment`.gldepartment,
  `epic_factsnapshottransactionpayment`.claimkey,
  `epic_factsnapshottransactionpayment`.claimnumber,
  `epic_factsnapshottransactionpayment`.visitnumber,
  `epic_factsnapshottransactionpayment`.transactionnumber,
  `epic_factsnapshottransactionpayment`.patientkey,
  `epic_factsnapshottransactionpayment`.patientid,
  `epic_factsnapshottransactionpayment`.servicingproviderkey,
  `epic_factsnapshottransactionpayment`.servicingproviderid,
  `epic_factsnapshottransactionpayment`.renderingproviderkey,
  `epic_factsnapshottransactionpayment`.renderingproviderid,
  `epic_factsnapshottransactionpayment`.facilitykey,
  `epic_factsnapshottransactionpayment`.facilityid,
  `epic_factsnapshottransactionpayment`.claimdatekey,
  `epic_factsnapshottransactionpayment`.claimdatemonthid,
  `epic_factsnapshottransactionpayment`.servicedatekey,
  `epic_factsnapshottransactionpayment`.servicedatemonthid,
  `epic_factsnapshottransactionpayment`.iplan1iplankey,
  `epic_factsnapshottransactionpayment`.iplan1id,
  `epic_factsnapshottransactionpayment`.financialclasskey,
  `epic_factsnapshottransactionpayment`.paymenttypekey,
  `epic_factsnapshottransactionpayment`.checkdatekey,
  `epic_factsnapshottransactionpayment`.checktype,
  `epic_factsnapshottransactionpayment`.encounterid,
  `epic_factsnapshottransactionpayment`.encounterkey,
  `epic_factsnapshottransactionpayment`.paymentdetailid,
  `epic_factsnapshottransactionpayment`.paymentid,
  `epic_factsnapshottransactionpayment`.checkamt,
  `epic_factsnapshottransactionpayment`.posteddatekey,
  `epic_factsnapshottransactionpayment`.transactiontype,
  `epic_factsnapshottransactionpayment`.transactiontypedesc,
  `epic_factsnapshottransactionpayment`.transactionid,
  `epic_factsnapshottransactionpayment`.transactionamt,
  `epic_factsnapshottransactionpayment`.transactiondatekey,
  `epic_factsnapshottransactionpayment`.transactiondatemonthid,
  `epic_factsnapshottransactionpayment`.paymentfromiplankey,
  `epic_factsnapshottransactionpayment`.paymentfromiplanid,
  `epic_factsnapshottransactionpayment`.checknumber,
  `epic_factsnapshottransactionpayment`.dwlastupdatedatetime,
  `epic_factsnapshottransactionpayment`.sourcesystemcode,
  `epic_factsnapshottransactionpayment`.insertedby,
  `epic_factsnapshottransactionpayment`.inserteddtm,
  `epic_factsnapshottransactionpayment`.transactionsamemonthflag
  FROM
    edwpsc_base_views.`epic_factsnapshottransactionpayment`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`epic_factsnapshottransactionpayment`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;