CREATE OR REPLACE VIEW edwpsc_views.`pv_factsnapshottransactionpayment`
AS SELECT
  `pv_factsnapshottransactionpayment`.transactionpaymentkey,
  `pv_factsnapshottransactionpayment`.monthid,
  `pv_factsnapshottransactionpayment`.snapshotdate,
  `pv_factsnapshottransactionpayment`.regionkey,
  `pv_factsnapshottransactionpayment`.practicekey,
  `pv_factsnapshottransactionpayment`.practiceid,
  `pv_factsnapshottransactionpayment`.coid,
  `pv_factsnapshottransactionpayment`.gldepartment,
  `pv_factsnapshottransactionpayment`.claimkey,
  `pv_factsnapshottransactionpayment`.claimnumber,
  `pv_factsnapshottransactionpayment`.patientkey,
  `pv_factsnapshottransactionpayment`.patientid,
  `pv_factsnapshottransactionpayment`.servicingproviderkey,
  `pv_factsnapshottransactionpayment`.servicingproviderid,
  `pv_factsnapshottransactionpayment`.renderingproviderkey,
  `pv_factsnapshottransactionpayment`.renderingproviderid,
  `pv_factsnapshottransactionpayment`.facilitykey,
  `pv_factsnapshottransactionpayment`.facilityid,
  `pv_factsnapshottransactionpayment`.claimdatekey,
  `pv_factsnapshottransactionpayment`.claimdatemonthid,
  `pv_factsnapshottransactionpayment`.servicedatekey,
  `pv_factsnapshottransactionpayment`.servicedatemonthid,
  `pv_factsnapshottransactionpayment`.iplan1iplankey,
  `pv_factsnapshottransactionpayment`.iplan1id,
  `pv_factsnapshottransactionpayment`.financialclasskey,
  `pv_factsnapshottransactionpayment`.paymenttypekey,
  `pv_factsnapshottransactionpayment`.checkdatekey,
  `pv_factsnapshottransactionpayment`.checktype,
  `pv_factsnapshottransactionpayment`.encounterid,
  `pv_factsnapshottransactionpayment`.encounterkey,
  `pv_factsnapshottransactionpayment`.paymentdetailid,
  `pv_factsnapshottransactionpayment`.paymentid,
  `pv_factsnapshottransactionpayment`.checkamt,
  `pv_factsnapshottransactionpayment`.posteddatekey,
  `pv_factsnapshottransactionpayment`.transactiontype,
  `pv_factsnapshottransactionpayment`.transactionid,
  `pv_factsnapshottransactionpayment`.transactionamt,
  `pv_factsnapshottransactionpayment`.transactiondatekey,
  `pv_factsnapshottransactionpayment`.transactiondatemonthid,
  `pv_factsnapshottransactionpayment`.paymentfromiplankey,
  `pv_factsnapshottransactionpayment`.paymentfromiplanid,
  `pv_factsnapshottransactionpayment`.checknumber,
  `pv_factsnapshottransactionpayment`.dwlastupdatedatetime,
  `pv_factsnapshottransactionpayment`.sourcesystemcode,
  `pv_factsnapshottransactionpayment`.insertedby,
  `pv_factsnapshottransactionpayment`.inserteddtm,
  `pv_factsnapshottransactionpayment`.modifiedby,
  `pv_factsnapshottransactionpayment`.modifieddtm
  FROM
    edwpsc_base_views.`pv_factsnapshottransactionpayment`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`pv_factsnapshottransactionpayment`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;