CREATE OR REPLACE VIEW edwpsc_views.`pv_factsnapshotpaymentclaim`
AS SELECT
  `pv_factsnapshotpaymentclaim`.paymentclaimkey,
  `pv_factsnapshotpaymentclaim`.monthid,
  `pv_factsnapshotpaymentclaim`.snapshotdate,
  `pv_factsnapshotpaymentclaim`.coid,
  `pv_factsnapshotpaymentclaim`.regionkey,
  `pv_factsnapshotpaymentclaim`.practicekey,
  `pv_factsnapshotpaymentclaim`.practiceid,
  `pv_factsnapshotpaymentclaim`.claimkey,
  `pv_factsnapshotpaymentclaim`.claimnumber,
  `pv_factsnapshotpaymentclaim`.gldepartment,
  `pv_factsnapshotpaymentclaim`.patientid,
  `pv_factsnapshotpaymentclaim`.servicingproviderkey,
  `pv_factsnapshotpaymentclaim`.servicingproviderid,
  `pv_factsnapshotpaymentclaim`.renderingproviderkey,
  `pv_factsnapshotpaymentclaim`.renderingproviderid,
  `pv_factsnapshotpaymentclaim`.facilitykey,
  `pv_factsnapshotpaymentclaim`.facilityid,
  `pv_factsnapshotpaymentclaim`.claimdatekey,
  `pv_factsnapshotpaymentclaim`.servicedatekey,
  `pv_factsnapshotpaymentclaim`.iplan1iplankey,
  `pv_factsnapshotpaymentclaim`.iplan1id,
  `pv_factsnapshotpaymentclaim`.financialclasskey,
  `pv_factsnapshotpaymentclaim`.encounterid,
  `pv_factsnapshotpaymentclaim`.contractualadjustmentamt,
  `pv_factsnapshotpaymentclaim`.allowedamt,
  `pv_factsnapshotpaymentclaim`.deductibleamt,
  `pv_factsnapshotpaymentclaim`.coinsuranceamt,
  `pv_factsnapshotpaymentclaim`.memberbalanceamt,
  `pv_factsnapshotpaymentclaim`.paymentamt,
  `pv_factsnapshotpaymentclaim`.withheldamt,
  `pv_factsnapshotpaymentclaim`.checkamt,
  `pv_factsnapshotpaymentclaim`.paymentcreateddatekey,
  `pv_factsnapshotpaymentclaim`.paymentmodifieddatekey,
  `pv_factsnapshotpaymentclaim`.paymenttypekey,
  `pv_factsnapshotpaymentclaim`.paymentid,
  `pv_factsnapshotpaymentclaim`.paymentdetailid,
  `pv_factsnapshotpaymentclaim`.checkdatekey,
  `pv_factsnapshotpaymentclaim`.checknumber,
  `pv_factsnapshotpaymentclaim`.checktype,
  `pv_factsnapshotpaymentclaim`.payerid,
  `pv_factsnapshotpaymentclaim`.posteddatekey,
  `pv_factsnapshotpaymentclaim`.paymentfromiplankey,
  `pv_factsnapshotpaymentclaim`.paymentfromiplanid,
  `pv_factsnapshotpaymentclaim`.paymentmemo,
  `pv_factsnapshotpaymentclaim`.paymentlock,
  `pv_factsnapshotpaymentclaim`.paymentdetailmodifieddatekey,
  `pv_factsnapshotpaymentclaim`.dwlastupdatedatetime
  FROM
    edwpsc_base_views.`pv_factsnapshotpaymentclaim`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`pv_factsnapshotpaymentclaim`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;