CREATE OR REPLACE VIEW edwpsc_views.`pv_factsnapshottransactioncharge`
AS SELECT
  `pv_factsnapshottransactioncharge`.transactionchargesmrykey,
  `pv_factsnapshottransactioncharge`.monthid,
  `pv_factsnapshottransactioncharge`.snapshotdate,
  `pv_factsnapshottransactioncharge`.regionkey,
  `pv_factsnapshottransactioncharge`.practicekey,
  `pv_factsnapshottransactioncharge`.practiceid,
  `pv_factsnapshottransactioncharge`.coid,
  `pv_factsnapshottransactioncharge`.gldepartment,
  `pv_factsnapshottransactioncharge`.claimkey,
  `pv_factsnapshottransactioncharge`.claimnumber,
  `pv_factsnapshottransactioncharge`.patientkey,
  `pv_factsnapshottransactioncharge`.patientid,
  `pv_factsnapshottransactioncharge`.servicingproviderkey,
  `pv_factsnapshottransactioncharge`.servicingproviderid,
  `pv_factsnapshottransactioncharge`.renderingproviderkey,
  `pv_factsnapshottransactioncharge`.renderingproviderid,
  `pv_factsnapshottransactioncharge`.facilitykey,
  `pv_factsnapshottransactioncharge`.facilityid,
  `pv_factsnapshottransactioncharge`.claimdatekey,
  `pv_factsnapshottransactioncharge`.servicedatekey,
  `pv_factsnapshottransactioncharge`.iplan1iplankey,
  `pv_factsnapshottransactioncharge`.iplan1id,
  `pv_factsnapshottransactioncharge`.financialclasskey,
  `pv_factsnapshottransactioncharge`.transactionamt,
  `pv_factsnapshottransactioncharge`.transactiondatemonthid,
  `pv_factsnapshottransactioncharge`.cptcodekey,
  `pv_factsnapshottransactioncharge`.cptcode,
  `pv_factsnapshottransactioncharge`.cptunitchangeamt,
  `pv_factsnapshottransactioncharge`.dwlastupdatedatetime,
  `pv_factsnapshottransactioncharge`.sourcesystemcode,
  `pv_factsnapshottransactioncharge`.insertedby,
  `pv_factsnapshottransactioncharge`.inserteddtm,
  `pv_factsnapshottransactioncharge`.modifiedby,
  `pv_factsnapshottransactioncharge`.modifieddtm,
  `pv_factsnapshottransactioncharge`.transactiontype,
  `pv_factsnapshottransactioncharge`.cptid,
  `pv_factsnapshottransactioncharge`.cptmodifier1,
  `pv_factsnapshottransactioncharge`.cptmodifier2,
  `pv_factsnapshottransactioncharge`.cptmodifier3,
  `pv_factsnapshottransactioncharge`.cptmodifier4,
  `pv_factsnapshottransactioncharge`.cptunitsonline,
  `pv_factsnapshottransactioncharge`.cpttos,
  `pv_factsnapshottransactioncharge`.cptchargeschangeamt,
  `pv_factsnapshottransactioncharge`.cptstartdos,
  `pv_factsnapshottransactioncharge`.cptenddos,
  `pv_factsnapshottransactioncharge`.cptseqnum,
  `pv_factsnapshottransactioncharge`.transactionid,
  `pv_factsnapshottransactioncharge`.transactiondatekey,
  `pv_factsnapshottransactioncharge`.claimdatemonthid,
  `pv_factsnapshottransactioncharge`.servicedatemonthid
  FROM
    edwpsc_base_views.`pv_factsnapshottransactioncharge`
  INNER JOIN edwpsc_base_views.secref_facility
  ON LPAD(TRIM(secref_facility.co_id, ' '), 5, '0') = LPAD(TRIM(`pv_factsnapshottransactioncharge`.coid, ' '), 5, '0')
  AND TRIM(secref_facility.user_id, ' ') = TRIM(session_user(), ' ')
;