SELECT
	cmpy,
	to_char(CAST(eff_dt AS DATE),'YYYY-MM-DD') AS eff_dt,
	posn,
	dept,
	job_cd,
	loc_cd,
	to_char(CAST(lst_updt_dt AS DATE),'YYYY-MM-DD') AS lst_updt_dt,
	lst_updt_user_id,
	pers_posn_chng_resn,
	to_char(CAST(pers_posn_end_dt AS DATE),'YYYY-MM-DD') AS pers_posn_end_dt,
	posn_desc,
	posn_stts,
	prcs_lvl,
	supv,
	supv_lnk,
	user_lvl,
	to_char(CAST(create_date AS DATE),'YYYY-MM-DD') AS create_date,
	to_char(CAST(create_time AS DATE),'YYYY-MM-DD') AS create_time,
	create_user,
	schd,
	'v_currtimestamp' AS dw_last_update_date_time
FROM
	(
	SELECT
		t1.cmpy,
		t1.eff_dt,
		t1.posn,
		t1.dept,
		t1.job_cd,
		t1.loc_cd,
		t1.lst_updt_dt,
		t1.lst_updt_user_id,
		t1.pers_posn_chng_resn,
		t1.pers_posn_end_dt,
		t1.posn_desc,
		t1.posn_stts,
		t1.prcs_lvl,
		t1.supv,
		t1.supv_lnk,
		t1.user_lvl,
		t1.create_date,
		t1.create_time,
		t1.create_user,
		t1.schd
	FROM
		orafs.vw_esaf_personnel_position t1
UNION
	SELECT
		t2.cmpy,
		t2.eff_dt,
		t2.posn,
		t2.dept,
		t2.job_cd,
		t2.loc_cd,
		t2.lst_updt_dt,
		t2.lst_updt_user_id,
		t2.pers_posn_chng_resn,
		t2.pers_posn_end_dt,
		t2.posn_desc,
		t2.posn_stts,
		t2.prcs_lvl,
		t2.supv,
		t2.supv_lnk,
		t2.user_lvl,
		t2.create_date,
		t2.create_time,
		t2.create_user,
		t2.schd
	FROM
		oracorp.vw_esaf_personnel_position t2)