SELECT
	CMPY,
	SUPV_CD,
	ACTV_FLG,
	to_char(CAST(EFF_DT AS DATE), 'YYYY-MM-DD') AS EFF_DT,
	EMPL,
	SUPV_CD_DESC,
	SUPV_RPT_TO,
	'v_currtimestamp' AS dw_last_update_date_time
FROM
	(
	SELECT
		T1.CMPY,
		T1.SUPV_CD,
		T1.ACTV_FLG,
		T1.EFF_DT,
		T1.EMPL,
		T1.SUPV_CD_DESC,
		T1.SUPV_RPT_TO
	FROM
		ORAFS.VW_ESAF_SUPERVISOR T1
UNION
	SELECT
		T2.CMPY,
		T2.SUPV_CD,
		T2.ACTV_FLG,
		T2.EFF_DT,
		T2.EMPL,
		T2.SUPV_CD_DESC,
		T2.SUPV_RPT_TO
	FROM
		ORACORP.VW_ESAF_SUPERVISOR T2
)