export JOBNAME='J_CN_REG_CANCER_PATIENT_DETAIL'

export AC_EXP_SQL_STATEMENT="Select 'J_CN_REG_CANCER_PATIENT_DETAIL'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from
(
SELECT
ROW_NUMBER() OVER( ORDER BY MET.PATIENT_MARKET_URN_TEXT,MET.NETWORK_MNEMONIC_CS ASC) AS CANCER_PATIENT_DETAIL_SK,
COALESCE(CP.CANCER_PATIENT_DRIVER_SK,CPP.CANCER_PATIENT_DRIVER_SK,CPN.CANCER_PATIENT_DRIVER_SK) AS CANCER_PATIENT_DRIVER_SK,
MET.CR_PATIENT_ID AS CR_PATIENT_ID,
INAV.NAV_PATIENT_ID AS CN_PATIENT_ID,
CPID.PATIENT_DW_ID AS CP_PATIENT_ID,
COALESCE(MET.COID,CPID.COID,INAV.COID) AS COID,
COALESCE(MET.COMPANY_CODE,CPID.COMPANY_CODE,INAV.COMPANY_CODE) AS COMPANY_CODE,
COALESCE(MET.NETWORK_MNEMONIC_CS,CPID.NETWORK_MNEMONIC_CS,INAV.NETWORK_MNEMONIC_CS) AS NETWORK_MNEMONIC_CS,
COALESCE(MET.PATIENT_MARKET_URN_TEXT,CPID.PATIENT_MARKET_URN,INAV.EMPI_TEXT) AS PATIENT_MARKET_URN_TEXT,
COALESCE(MET.MEDICAL_RECORD_NUM,CPID.MEDICAL_RECORD_NUM,INAV.MEDICAL_RECORD_NUM) AS MEDICAL_RECORD_NUM,
MET.RELATION_NAME AS RELATIONSHIP_NAME,
COALESCE(MET.ADDRESS_LINE_1_TEXT,CPID.ADDRESS_LINE_1_TEXT,INAV.ADDRESS_LINE_1_TEXT) AS ADDRESS_LINE_1_TEXT,
COALESCE(MET.ADDRESS_LINE_2_TEXT,CPID.ADDRESS_LINE_2_TEXT,INAV.ADDRESS_LINE_2_TEXT) AS ADDRESS_LINE_2_TEXT,
COALESCE(MET.CITY_NAME,CPID.CITY_NAME,INAV.CITY_NAME) AS CITY_NAME,
INAV.DEATH_DATE,
COALESCE(MET.PATIENT_BIRTH_DATE,CPID.PATIENT_BIRTH_DATE,INAV.PATIENT_BIRTH_DATE) AS PATIENT_BIRTH_DATE,
COALESCE(MET.PATIENT_EMAIL_ADDRESS_TEXT,INAV.PATIENT_EMAIL_ADDRESS_TEXT) AS PATIENT_EMAIL_ADDRESS_TEXT,

COALESCE(MET.GENDER_CODE,CPID.GENDER_CODE,INAV.GENDER_CODE) AS GENDER_CODE,

COALESCE(MET.STATE_CODE,CPID.STATE_CODE,INAV.STATE_CODE) AS STATE_CODE,
COALESCE(MET.ZIP_CODE,CPID.ZIP_CODE,INAV.ZIP_CODE) AS ZIP_CODE,
COALESCE(MET.PHONE_NUM_TYPE_CODE,INAV.PHONE_NUM_TYPE_CODE) AS PHONE_NUM_TYPE_CODE,
COALESCE(MET.PHONE_NUM,INAV.PHONE_NUM) AS PHONE_NUM,
																				  
INAV.PREFERRED_LANGUAGE_TEXT,
---INAV.PREFERRED_NAME,
MET.INSURANCE_TYPE_NAME,
MET.PREFERRED_CONTACT_METHOD_TEXT,
MET.INSURANCE_COMPANY_NAME,
MET.RACE_NAME,
MET.PATIENT_SYSTEM_ID,
MET.VITAL_STATUS_NAME,
COALESCE(MET.SOURCE_SYSTEM_CODE,CPID.SOURCE_SYSTEM_CODE,INAV.SOURCE_SYSTEM_CODE) AS SOURCE_SYSTEM_CODE,
CURRENT_TIMESTAMP(0) as DW_LAST_UPDATE_DATE_TIME 

FROM
(
SELECT DISTINCT CP.PATIENT_MARKET_URN_TEXT,
CP.CR_PATIENT_ID
,CP.COID
,CP.COMPANY_CODE
,CP.MEDICAL_RECORD_NUM
,REL.LOOKUP_DESC AS RELATION_NAME  
,DF.NETWORK_MNEMONIC_CS
,DF.FACILITY_MNEMONIC_CS
,CPPN.PHONE_NUM_TYPE_CODE AS PHONE_NUM_TYPE_CODE
,CPPN.PHONE_NUM AS PHONE_NUM
,CPA.ADDRESS_LINE_1_TEXT AS ADDRESS_LINE_1_TEXT           
,CPA.ADDRESS_LINE_2_TEXT   AS ADDRESS_LINE_2_TEXT        
,CPA.CITY_NAME AS CITY_NAME
,CP.PATIENT_BIRTH_DATE   AS PATIENT_BIRTH_DATE          
,CP.PATIENT_EMAIL_ADDRESS_TEXT    AS PATIENT_EMAIL_ADDRESS_TEXT
,CP.PATIENT_FIRST_NAME AS PATIENT_FIRST_NAME
,CASE WHEN GN.LOOKUP_DESC='MALE' THEN 'M' 
WHEN GN.LOOKUP_DESC='FEMALE' THEN 'F' ELSE 'U' END AS GENDER_CODE            
,CP.PATIENT_LAST_NAME AS PATIENT_LAST_NAME
,CP.PATIENT_MIDDLE_NAME AS PATIENT_MIDDLE_NAME
,ST.LOOKUP_CODE AS STATE_CODE            
,CPA.ZIP_CODE AS ZIP_CODE
,ICI.LOOKUP_DESC AS INSURANCE_TYPE_NAME
,CPC.PREFERRED_CONTACT_METHOD_TEXT AS PREFERRED_CONTACT_METHOD_TEXT
,ITI.LOOKUP_DESC AS INSURANCE_COMPANY_NAME
,RC.LOOKUP_DESC AS RACE_NAME
,CP.PATIENT_SYSTEM_ID      AS        PATIENT_SYSTEM_ID 
,VS.LOOKUP_DESC AS VITAL_STATUS_NAME
,CP.SOURCE_SYSTEM_CODE
 FROM EDWCR_base_views.CR_PATIENT CP
  INNER JOIN (SELECT  FACILITY_MNEMONIC_CS,NETWORK_MNEMONIC_CS,COID,FACILITY_ACTIVE_IND FROM EDW_PUB_Views.Clinical_facility 
  QUALIFY ROW_NUMBER() OVER(PARTITION BY COID ORDER BY FACILITY_ACTIVE_IND DESC )=1 ) DF ON CP.COID =DF.COID
 LEFT OUTER JOIN EDWCR_base_views.CR_PATIENT_ADDRESS CPA
 ON CP.CR_PATIENT_ID = CPA.CR_PATIENT_ID
  LEFT OUTER JOIN EDWCR_base_views.CR_PATIENT_CONTACT CPC
 ON CP.CR_PATIENT_ID = CPC.CR_PATIENT_ID
 LEFT OUTER JOIN EDWCR_base_views.CR_PATIENT_PHONE_NUM CPPN
 ON CP.CR_PATIENT_ID = CPPN.CR_PATIENT_ID
 AND CPC.PATIENT_CONTACT_ID=CPPN.PATIENT_CONTACT_ID
 LEFT OUTER JOIN EDWCR_base_views.CR_PATIENT_INSURANCE CPI
 ON CP.CR_PATIENT_ID = CPI.CR_PATIENT_ID

 
 LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=1) VS
 ON CP.VITAL_STATUS_ID=VS.MASTER_LOOKUP_SID
 
 LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=2) RC
 ON CP.PATIENT_RACE_ID=RC.MASTER_LOOKUP_SID
 
  LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=3) GN
 ON CP.PATIENT_GENDER_ID=GN.MASTER_LOOKUP_SID
 
    LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=4) REL
 ON CPC.CONTACT_RELATION_ID=REL.MASTER_LOOKUP_SID
 
   LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=13) ITI
 ON CPI.INSURANCE_TYPE_ID=ITI.MASTER_LOOKUP_SID
 
   LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=14) ICI
 ON CPI.INSURANCE_COMPANY_ID=ICI.MASTER_LOOKUP_SID
 
   LEFT OUTER JOIN 
 (SEL MASTER_LOOKUP_SID,LOOKUP_CODE,LOOKUP_DESC FROM EDWCR_base_views.REF_LOOKUP_CODE WHERE LOOKUP_ID=23) ST
 ON CPA.STATE_ID=ST.MASTER_LOOKUP_SID
 )
  MET
FULL OUTER JOIN
  (
  SELECT  
PATIENT_MARKET_URN,
CRIO.NETWORK_MNEMONIC_CS,
PATIENT_DW_ID,CRIO.COID,
MEDICAL_RECORD_NUM,
CRIO.ADDRESS_LINE_1_TEXT      ,
DF1.FACILITY_MNEMONIC_CS,
COMPANY_CODE
, CRIO.ADDRESS_LINE_2_TEXT           
, CRIO.CITY_NAME
, CRIO.BIRTH_DATE   AS PATIENT_BIRTH_DATE                 
, CRIO .FIRST_NAME     AS PATIENT_FIRST_NAME
, CRIO.GENDER_CODE
, CRIO.LAST_NAME     AS PATIENT_LAST_NAME
, CRIO.STATE_CODE                    
, CRIO.ZIP_CODE
,CRIO.SOURCE_SYSTEM_CODE
FROM EDWCR_base_views.CANCER_PATIENT_ID_OUTPUT CRIO
 INNER JOIN (SELECT  FACILITY_MNEMONIC_CS,NETWORK_MNEMONIC_CS,COID,FACILITY_ACTIVE_IND FROM EDW_PUB_Views.Clinical_facility 
  QUALIFY ROW_NUMBER() OVER(PARTITION BY COID ORDER BY FACILITY_ACTIVE_IND DESC )=1 ) DF1 ON CRIO.COID =DF1.COID

QUALIFY ROW_NUMBER() OVER (PARTITION BY COALESCE(PATIENT_MARKET_URN,MEDICAL_RECORD_NUM||FACILITY_MNEMONIC_CS,Patient_DW_ID) ORDER BY REPORT_ASSIGNED_DATE_TIME DESC)=1																																						 
 
  ) CPID
  ON coalesce(MET.PATIENT_MARKET_URN_TEXT,MET.MEDICAL_RECORD_NUM||MET.FACILITY_MNEMONIC_CS) = COALESCE(CPID.PATIENT_MARKET_URN,CPID.MEDICAL_RECORD_NUM||CPID.FACILITY_MNEMONIC_CS)
  AND MET.NETWORK_MNEMONIC_CS = CPID.NETWORK_MNEMONIC_CS
FULL OUTER JOIN (
SELECT  
CP.NAV_PATIENT_ID,
CPT.PATIENT_MARKET_URN,
DF2.NETWORK_MNEMONIC_CS,CPT.COID,DF2.FACILITY_MNEMONIC_CS,
CPT.COMPANY_CODE,
CPT.EMPI_TEXT,
CPT.MEDICAL_RECORD_NUM,
CPA.ADDRESS_LINE_1_TEXT
,CPA.ADDRESS_LINE_2_TEXT
,CPA.CITY_NAME
,CP.DEATH_DATE
,CP.BIRTH_DATE AS PATIENT_BIRTH_DATE
,CP.PATIENT_EMAIL_TEXT AS PATIENT_EMAIL_ADDRESS_TEXT
,CP.FIRST_NAME AS PATIENT_FIRST_NAME
,CP.GENDER_CODE
,CP.LAST_NAME AS PATIENT_LAST_NAME
,CP.MIDDLE_NAME AS PATIENT_MIDDLE_NAME
,CPP.PHONE_NUM
,CPP.PHONE_NUM_TYPE_CODE
,CP.PREFERRED_LANGUAGE_TEXT
,CP.PREFERRED_NAME
,CPA.STATE_CODE
,CPA.ZIP_CODE
,CP.SOURCE_SYSTEM_CODE
FROM EDWCR_base_views.CN_PERSON CP

LEFT OUTER JOIN EDWCR_base_views.CN_PATIENT CPT
ON CP.NAV_PATIENT_ID = CPT.NAV_PATIENT_ID
INNER JOIN (SELECT  FACILITY_MNEMONIC_CS,NETWORK_MNEMONIC_CS,COID,FACILITY_ACTIVE_IND FROM EDW_PUB_Views.Clinical_facility 
  QUALIFY ROW_NUMBER() OVER(PARTITION BY COID ORDER BY FACILITY_ACTIVE_IND DESC )=1 ) DF2 ON CPT.COID =DF2.COID
LEFT OUTER JOIN EDWCR_base_views.CN_PATIENT_ADDRESS CPA
ON CP.NAV_PATIENT_ID= CPA.NAV_PATIENT_ID
LEFT OUTER JOIN EDWCR_base_views.CN_PATIENT_PHONE_NUM CPP
ON CP.NAV_PATIENT_ID= CPP.NAV_PATIENT_ID

QUALIFY ROW_NUMBER () OVER(PARTITION BY COALESCE(CPT.PATIENT_MARKET_URN,CPT.MEDICAL_RECORD_NUM||DF2.FACILITY_MNEMONIC_CS,CP.Nav_Patient_ID) ORDER BY CP.NAV_PATIENT_ID DESC)=1																																							 
 
) INAV
        ON COALESCE(TRIM(MET.NETWORK_MNEMONIC_CS)||MET.PATIENT_MARKET_URN_TEXT,MET.MEDICAL_RECORD_NUM||MET.FACILITY_MNEMONIC_CS) 
  = COALESCE(INAV.PATIENT_MARKET_URN,INAV.MEDICAL_RECORD_NUM||INAV.FACILITY_MNEMONIC_CS)
    AND MET.NETWORK_MNEMONIC_CS=INAV.NETWORK_MNEMONIC_CS
 LEFT OUTER JOIN (Select CR_PATIENT_ID,CANCER_PATIENT_DRIVER_SK from EDWCR_BASE_VIEWS.CANCER_PATIENT_DRIVER
QUALIFY ROW_NUMBER() OVER(PARTITION BY CR_PATIENT_ID ORDER BY CANCER_PATIENT_DRIVER_SK ASC )=1) CP
  ON MET.CR_PATIENT_ID=CP.CR_PATIENT_ID
 LEFT OUTER JOIN (Select CN_PATIENT_ID,CANCER_PATIENT_DRIVER_SK from EDWCR_BASE_VIEWS.CANCER_PATIENT_DRIVER 
QUALIFY ROW_NUMBER() OVER(PARTITION BY CN_PATIENT_ID ORDER BY CANCER_PATIENT_DRIVER_SK ASC )=1) CPN
  ON INAV.NAV_PATIENT_ID=CPN.CN_PATIENT_ID
  LEFT OUTER JOIN (Select CP_PATIENT_ID,CANCER_PATIENT_DRIVER_SK from EDWCR_BASE_VIEWS.CANCER_PATIENT_DRIVER 
QUALIFY ROW_NUMBER() OVER(PARTITION BY CP_PATIENT_ID ORDER BY CANCER_PATIENT_DRIVER_SK ASC )=1) CPP
  ON CPID.PATIENT_DW_ID=CPP.CP_PATIENT_ID
)A"


export AC_ACT_SQL_STATEMENT="Select 'J_CN_REG_CANCER_PATIENT_DETAIL'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from ${NCR_TGT_SCHEMA}.CANCER_PATIENT_DETAIL"
