export JOBNAME='J_CN_PATIENT_HEME_DISEASE_ASSESS_DETAIL'

export AC_EXP_SQL_STATEMENT="select 'J_CN_PATIENT_HEME_DISEASE_ASSESS_DETAIL' || ',' || CAST(COUNT(*) AS VARCHAR(20)) || ',' 
AS SOURCE_STRING from EDWCR_STAGING.Patient_Heme_Disease_Assessment_STG"

export AC_ACT_SQL_STATEMENT="select 'J_CN_PATIENT_HEME_DISEASE_ASSESS_DETAIL' || ',' || CAST(COUNT(*) AS VARCHAR(20)) || ',' 
AS SOURCE_STRING from EDWCR_BASE_VIEWS.CN_Patient_Heme_Disease_Assess_Detail"

