export ODBC_EXP_DB='METRIQ'

export JOBNAME='J_CR_PATIENT_DIAGNOSIS_DETAIL'

export AC_EXP_SQL_STATEMENT="Select 'J_CR_PATIENT_DIAGNOSIS_DETAIL_STG'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from ${NCR_STG_SCHEMA}.CR_PATIENT_DIAGNOSIS_DETAIL_STG"
export AC_ACT_SQL_STATEMENT="Select 'J_CR_PATIENT_DIAGNOSIS_DETAIL_STG'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from ${NCR_TGT_SCHEMA}.CR_PATIENT_DIAGNOSIS_DETAIL"