export ODBC_EXP_DB='METRIQ'

export JOBNAME='J_CR_PATIENT_CONTACT_STG'

export AC_EXP_SQL_STATEMENT="SELECT 'J_CR_PATIENT_CONTACT_STG' + ','+ CAST(COUNT(*) AS VARCHAR(20))+',' AS SOURCE_STRING FROM
(
SELECT 
C.CONTACTID,
PATIENTID,
RELATION,
TYPE,
CONTACTCODE,
CNTFIRSTNAME,
CNTLASTNAME,
CNTMIDDLENAME,
REMARKS

   FROM MREGISTRY.DBO.CONTACTS C
INNER JOIN 
(SELECT CONTACTID,COUNT(*) CNT FROM MREGISTRY.DBO.CONTACTS
GROUP BY CONTACTID
HAVING COUNT(*)=1) A
ON C.CONTACTID=A.CONTACTID
UNION ALL
SELECT CONTACTID,
PATIENTID,
RELATION,
TYPE,
CONTACTCODE,
CNTFIRSTNAME,
CNTLASTNAME,
CNTMIDDLENAME,
REMARKS
 FROM 
(SELECT *,ROW_NUMBER() OVER(PARTITION BY CONTACTID ORDER BY CONTACTSHOSPID DESC) RN
FROM MREGISTRY.DBO.CONTACTS WHERE CONTACTID IN (
SELECT  C.CONTACTID   FROM MREGISTRY.DBO.CONTACTS C
INNER JOIN 
(SELECT CONTACTID,COUNT(*) CNT FROM MREGISTRY.DBO.CONTACTS
GROUP BY CONTACTID
HAVING COUNT(*)>1) A
ON C.CONTACTID=A.CONTACTID
INNER JOIN MREGISTRY.DBO.CONTACTS C1
ON C.CONTACTID=C1.CONTACTID
AND C1.CONTACTSHOSPID IS NULL
)
) B
WHERE B.RN=1
)CNTS"

export AC_ACT_SQL_STATEMENT="Select 'J_CR_PATIENT_CONTACT_STG'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING 
from 
EDWCR_STAGING.CR_PATIENT_CONTACT_STG"
