export ODBC_EXP_DB='METRIQ'

export JOBNAME='J_CR_PATIENT_MEDICAL_ONCOLOGY'

export AC_EXP_SQL_STATEMENT="Select 'J_CR_PATIENT_MEDICAL_ONCOLOGY'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from ${NCR_STG_SCHEMA}.CR_PATIENT_MEDICAL_ONCOLOGY_WRK"
export AC_ACT_SQL_STATEMENT="Select 'J_CR_PATIENT_MEDICAL_ONCOLOGY'||','|| cast(count(*) as varchar(20))||',' as SOURCE_STRING from ${NCR_TGT_SCHEMA}.CR_PATIENT_MEDICAL_ONCOLOGY"
