
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCLAIMCODES ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCLAIMCODES (HCCLCCID, HCCLID, HCCLLDESC, HCCLLOADDATE, HCCLMODIFIEDDATE, HCCLSDESC, HCCLSTARTDATE, HCCLSTOPDATE, PSCLACTIVE, PSCLNTEFLG, PSCLUFM, PSCLUFMFLG)
SELECT TRIM(source.HCCLCCID), TRIM(source.HCCLID), TRIM(source.HCCLLDESC), source.HCCLLOADDATE, source.HCCLMODIFIEDDATE, TRIM(source.HCCLSDESC), source.HCCLSTARTDATE, source.HCCLSTOPDATE, TRIM(source.PSCLACTIVE), TRIM(source.PSCLNTEFLG), TRIM(source.PSCLUFM), TRIM(source.PSCLUFMFLG)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCCLAIMCODES as source;
