
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSSUBCATCHKLST AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSSUBCATCHKLST AS source
ON target.PSSCID = source.PSSCID
WHEN MATCHED THEN
  UPDATE SET
  target.PSSCID = TRIM(source.PSSCID),
 target.PSSCACCOUNTID = TRIM(source.PSSCACCOUNTID),
 target.PSSCACTGRP = TRIM(source.PSSCACTGRP),
 target.PSSCCAT = TRIM(source.PSSCCAT),
 target.PSSCCATTYPE = TRIM(source.PSSCCATTYPE),
 target.PSSCCCAT = TRIM(source.PSSCCCAT),
 target.PSSCCDTE = TRIM(source.PSSCCDTE),
 target.PSSCCOMPLETE = TRIM(source.PSSCCOMPLETE),
 target.PSSCCRTDTE = TRIM(source.PSSCCRTDTE),
 target.PSSCCTIME = TRIM(source.PSSCCTIME),
 target.PSSCCUSER = TRIM(source.PSSCCUSER),
 target.PSSCDOC1 = TRIM(source.PSSCDOC1),
 target.PSSCDOC2 = TRIM(source.PSSCDOC2),
 target.PSSCDOC3 = TRIM(source.PSSCDOC3),
 target.PSSCDOC4 = TRIM(source.PSSCDOC4),
 target.PSSCENCNTRID = TRIM(source.PSSCENCNTRID),
 target.PSSCFUFLAG = TRIM(source.PSSCFUFLAG),
 target.PSSCFUFLAGUSER = TRIM(source.PSSCFUFLAGUSER),
 target.PSSCINSTRUCT = TRIM(source.PSSCINSTRUCT),
 target.PSSCPAYERID = TRIM(source.PSSCPAYERID),
 target.PSSCPRIORITY = TRIM(source.PSSCPRIORITY),
 target.PSSCQDTE = TRIM(source.PSSCQDTE),
 target.PSSCQTIME = TRIM(source.PSSCQTIME),
 target.PSSCQUSER = TRIM(source.PSSCQUSER),
 target.PSSCRDTE = TRIM(source.PSSCRDTE),
 target.PSSCRTIME = TRIM(source.PSSCRTIME),
 target.PSSCRUSER = TRIM(source.PSSCRUSER),
 target.PSSCSOURCE = TRIM(source.PSSCSOURCE),
 target.PSSCSTATUS = TRIM(source.PSSCSTATUS),
 target.PSSCSUBCAT = TRIM(source.PSSCSUBCAT),
 target.PSSCSUBCATDESC = TRIM(source.PSSCSUBCATDESC),
 target.PSSCSUBCATTYPE = TRIM(source.PSSCSUBCATTYPE),
 target.PSSCORGPYRID = TRIM(source.PSSCORGPYRID),
 target.PSSCORIGROUTE = TRIM(source.PSSCORIGROUTE),
 target.PSSCCOIDREROUTE = TRIM(source.PSSCCOIDREROUTE),
 target.DwLastUpdateDateTime = source.DwLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSSCID, PSSCACCOUNTID, PSSCACTGRP, PSSCCAT, PSSCCATTYPE, PSSCCCAT, PSSCCDTE, PSSCCOMPLETE, PSSCCRTDTE, PSSCCTIME, PSSCCUSER, PSSCDOC1, PSSCDOC2, PSSCDOC3, PSSCDOC4, PSSCENCNTRID, PSSCFUFLAG, PSSCFUFLAGUSER, PSSCINSTRUCT, PSSCPAYERID, PSSCPRIORITY, PSSCQDTE, PSSCQTIME, PSSCQUSER, PSSCRDTE, PSSCRTIME, PSSCRUSER, PSSCSOURCE, PSSCSTATUS, PSSCSUBCAT, PSSCSUBCATDESC, PSSCSUBCATTYPE, PSSCORGPYRID, PSSCORIGROUTE, PSSCCOIDREROUTE, DwLastUpdateDateTime)
  VALUES (TRIM(source.PSSCID), TRIM(source.PSSCACCOUNTID), TRIM(source.PSSCACTGRP), TRIM(source.PSSCCAT), TRIM(source.PSSCCATTYPE), TRIM(source.PSSCCCAT), TRIM(source.PSSCCDTE), TRIM(source.PSSCCOMPLETE), TRIM(source.PSSCCRTDTE), TRIM(source.PSSCCTIME), TRIM(source.PSSCCUSER), TRIM(source.PSSCDOC1), TRIM(source.PSSCDOC2), TRIM(source.PSSCDOC3), TRIM(source.PSSCDOC4), TRIM(source.PSSCENCNTRID), TRIM(source.PSSCFUFLAG), TRIM(source.PSSCFUFLAGUSER), TRIM(source.PSSCINSTRUCT), TRIM(source.PSSCPAYERID), TRIM(source.PSSCPRIORITY), TRIM(source.PSSCQDTE), TRIM(source.PSSCQTIME), TRIM(source.PSSCQUSER), TRIM(source.PSSCRDTE), TRIM(source.PSSCRTIME), TRIM(source.PSSCRUSER), TRIM(source.PSSCSOURCE), TRIM(source.PSSCSTATUS), TRIM(source.PSSCSUBCAT), TRIM(source.PSSCSUBCATDESC), TRIM(source.PSSCSUBCATTYPE), TRIM(source.PSSCORGPYRID), TRIM(source.PSSCORIGROUTE), TRIM(source.PSSCCOIDREROUTE), source.DwLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSSCID
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSSUBCATCHKLST
      GROUP BY PSSCID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSSUBCATCHKLST');
ELSE
  COMMIT TRANSACTION;
END IF;
