
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESPAUTILPAYORS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESPAUTILPAYORS (PSPESPATMPPAYID, PSPESPATMPPAYKEY, PSPESPATMPPAYPROCFLG, PSPESPATMPPAYSPAID, PSPESPATMPPAYOVRFLG)
SELECT TRIM(source.PSPESPATMPPAYID), TRIM(source.PSPESPATMPPAYKEY), TRIM(source.PSPESPATMPPAYPROCFLG), source.PSPESPATMPPAYSPAID, TRIM(source.PSPESPATMPPAYOVRFLG)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPESPAUTILPAYORS as source;
