
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRSPECIALTY ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRSPECIALTY (PSPEPRSPACTIVEIND, PSPEPRSPGAFID, PSPEPRSPKEY, PSPEPRSPNAME, PSPEPRSPPERFID, PSPEPRSPSTATUS, PSPEPRSPTAXONOMY, PSPEPRSPTYPE)
SELECT TRIM(source.PSPEPRSPACTIVEIND), TRIM(source.PSPEPRSPGAFID), TRIM(source.PSPEPRSPKEY), TRIM(source.PSPEPRSPNAME), TRIM(source.PSPEPRSPPERFID), TRIM(source.PSPEPRSPSTATUS), TRIM(source.PSPEPRSPTAXONOMY), TRIM(source.PSPEPRSPTYPE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRSPECIALTY as source;
