
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCUSERSTATS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCUSERSTATS (HCUSUSERID, HCUSYEAR, HCUSMONTH, HCUSDAY, HCUSDEPT, HCUSFACILITY, HCUSSUBUNIT, HCUSPAYER, HCUSACCTVIEWED, HCUSACCTWRKD, HCUSBRKNNUM, HCUSCALLS, HCUSCONTACTS, HCUSINSFOUND, HCUSINSPTP, HCUSINSPTPNUM, HCUSLTRS, HCUSPAYMENTS, HCUSPLACED, HCUSPTPAMT, HCUSPTPNUM, HCUSRECALL, HCUSSETTLEAMT, HCUSSETTLENUM, HCUSTIME)
SELECT TRIM(source.HCUSUSERID), source.HCUSYEAR, source.HCUSMONTH, TRIM(source.HCUSDAY), TRIM(source.HCUSDEPT), TRIM(source.HCUSFACILITY), TRIM(source.HCUSSUBUNIT), TRIM(source.HCUSPAYER), source.HCUSACCTVIEWED, source.HCUSACCTWRKD, source.HCUSBRKNNUM, source.HCUSCALLS, source.HCUSCONTACTS, source.HCUSINSFOUND, source.HCUSINSPTP, source.HCUSINSPTPNUM, source.HCUSLTRS, source.HCUSPAYMENTS, source.HCUSPLACED, source.HCUSPTPAMT, source.HCUSPTPNUM, source.HCUSRECALL, source.HCUSSETTLEAMT, source.HCUSSETTLENUM, TRIM(source.HCUSTIME)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCUSERSTATS as source;
