
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRALTPROVIDERS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRALTPROVIDERS (PSPEPRALTACTIVEIND, PSPEPRALTDTEFRM, PSPEPRALTDTETO, PSPEPRALTGAFID, PSPEPRALTID, PSPEPRALTKEY, PSPEPRALTLONGNM, PSPEPRALTPERFID, PSPEPRALTPROVID, PSPEPRALTTYPE)
SELECT TRIM(source.PSPEPRALTACTIVEIND), source.PSPEPRALTDTEFRM, source.PSPEPRALTDTETO, TRIM(source.PSPEPRALTGAFID), TRIM(source.PSPEPRALTID), TRIM(source.PSPEPRALTKEY), TRIM(source.PSPEPRALTLONGNM), TRIM(source.PSPEPRALTPERFID), TRIM(source.PSPEPRALTPROVID), TRIM(source.PSPEPRALTTYPE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRALTPROVIDERS as source;
