
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCACTIONCODE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCACTIONCODE (HCACTACTGRPID, HCACTCALLSTAT, HCACTCONTACTSTAT, HCACTDESC, HCACTFOLLIM, HCACTHELPID, HCACTID, HCACTNEWSTAT, HCACTNOTETEXT, HCACTPHASE, HCACTRESCNT, HCACTSECCODE, HCACTWAITDATE, HCACTWKFLWS, HCACTWORKED)
SELECT TRIM(source.HCACTACTGRPID), TRIM(source.HCACTCALLSTAT), TRIM(source.HCACTCONTACTSTAT), TRIM(source.HCACTDESC), source.HCACTFOLLIM, TRIM(source.HCACTHELPID), TRIM(source.HCACTID), TRIM(source.HCACTNEWSTAT), TRIM(source.HCACTNOTETEXT), TRIM(source.HCACTPHASE), source.HCACTRESCNT, TRIM(source.HCACTSECCODE), source.HCACTWAITDATE, TRIM(source.HCACTWKFLWS), TRIM(source.HCACTWORKED)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCACTIONCODE as source;
