
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECMSGS AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEECMSGS AS source
ON target.PSPEECMSGECTID = source.PSPEECMSGECTID AND target.PSPEECMSGID = source.PSPEECMSGID
WHEN MATCHED THEN
  UPDATE SET
  target.PSPEECMSGCNT = TRIM(source.PSPEECMSGCNT),
 target.PSPEECMSGDATE = source.PSPEECMSGDATE,
 target.PSPEECMSGECTID = TRIM(source.PSPEECMSGECTID),
 target.PSPEECMSGEDITOR = TRIM(source.PSPEECMSGEDITOR),
 target.PSPEECMSGEXPORTDTE = source.PSPEECMSGEXPORTDTE,
 target.PSPEECMSGID = source.PSPEECMSGID,
 target.PSPEECMSGNEW = TRIM(source.PSPEECMSGNEW),
 target.PSPEECMSGPORTALID = TRIM(source.PSPEECMSGPORTALID),
 target.PSPEECMSGSOURCE = TRIM(source.PSPEECMSGSOURCE),
 target.PSPEECMSGTEXT = TRIM(source.PSPEECMSGTEXT),
 target.PSPEECMSGTIME = source.PSPEECMSGTIME,
 target.PSPEECMSGTYPE = TRIM(source.PSPEECMSGTYPE),
 target.PSPEECMSGUSER = TRIM(source.PSPEECMSGUSER),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSPEECMSGCNT, PSPEECMSGDATE, PSPEECMSGECTID, PSPEECMSGEDITOR, PSPEECMSGEXPORTDTE, PSPEECMSGID, PSPEECMSGNEW, PSPEECMSGPORTALID, PSPEECMSGSOURCE, PSPEECMSGTEXT, PSPEECMSGTIME, PSPEECMSGTYPE, PSPEECMSGUSER, DWLastUpdateDateTime)
  VALUES (TRIM(source.PSPEECMSGCNT), source.PSPEECMSGDATE, TRIM(source.PSPEECMSGECTID), TRIM(source.PSPEECMSGEDITOR), source.PSPEECMSGEXPORTDTE, source.PSPEECMSGID, TRIM(source.PSPEECMSGNEW), TRIM(source.PSPEECMSGPORTALID), TRIM(source.PSPEECMSGSOURCE), TRIM(source.PSPEECMSGTEXT), source.PSPEECMSGTIME, TRIM(source.PSPEECMSGTYPE), TRIM(source.PSPEECMSGUSER), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSPEECMSGECTID, PSPEECMSGID
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECMSGS
      GROUP BY PSPEECMSGECTID, PSPEECMSGID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECMSGS');
ELSE
  COMMIT TRANSACTION;
END IF;
