
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIPINGIN ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIPINGIN (PSPEPPIPGKEY, PSPEPPIPGACTIVE, PSPEPPIPGEFFDTE, PSPEPPIPGGIN, PSPEPPIPGPERFID, PSPEPPIPGPIN, PSPEPPIPGPPIID, PSPEPPIPGTERMDTE)
SELECT TRIM(source.PSPEPPIPGKEY), TRIM(source.PSPEPPIPGACTIVE), source.PSPEPPIPGEFFDTE, TRIM(source.PSPEPPIPGGIN), TRIM(source.PSPEPPIPGPERFID), TRIM(source.PSPEPPIPGPIN), TRIM(source.PSPEPPIPGPPIID), source.PSPEPPIPGTERMDTE
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPPIPINGIN as source;
