
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEINSTITUTION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEINSTITUTION (PSPEINADDR1, PSPEINADDR2, PSPEINAFFILIATIONS, PSPEINBOARDS, PSPEINCITY, PSPEINCONTACT, PSPEINCOUNTRY, PSPEINEDUCATION, PSPEINFAX, PSPEINHOMEPGURL, PSPEINID, PSPEININSURANCE, PSPEINLICENSES, PSPEINKEY, PSPEINNAME, PSPEINPLANS, PSPEINPRIMPHONE, PSPEINST, PSPEINTYPE, PSPEINZIP)
SELECT TRIM(source.PSPEINADDR1), TRIM(source.PSPEINADDR2), TRIM(source.PSPEINAFFILIATIONS), TRIM(source.PSPEINBOARDS), TRIM(source.PSPEINCITY), TRIM(source.PSPEINCONTACT), TRIM(source.PSPEINCOUNTRY), TRIM(source.PSPEINEDUCATION), TRIM(source.PSPEINFAX), TRIM(source.PSPEINHOMEPGURL), TRIM(source.PSPEINID), TRIM(source.PSPEININSURANCE), TRIM(source.PSPEINLICENSES), TRIM(source.PSPEINKEY), TRIM(source.PSPEINNAME), TRIM(source.PSPEINPLANS), TRIM(source.PSPEINPRIMPHONE), TRIM(source.PSPEINST), TRIM(source.PSPEINTYPE), TRIM(source.PSPEINZIP)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEINSTITUTION as source;
