
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCRESULTCODE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCRESULTCODE (HCRESACTGRPID, HCRESCALLSTAT, HCRESCONTACTSTAT, HCRESDESC, HCRESFOLLIM, HCRESHELPID, HCRESID, HCRESNEWSTAT, HCRESNOTETEXT, HCRESPHASE, HCRESSECCODE, HCRESWAITDATE, HCRESWKFLWS, HCRESWORKED)
SELECT TRIM(source.HCRESACTGRPID), TRIM(source.HCRESCALLSTAT), TRIM(source.HCRESCONTACTSTAT), TRIM(source.HCRESDESC), source.HCRESFOLLIM, TRIM(source.HCRESHELPID), TRIM(source.HCRESID), TRIM(source.HCRESNEWSTAT), TRIM(source.HCRESNOTETEXT), TRIM(source.HCRESPHASE), TRIM(source.HCRESSECCODE), source.HCRESWAITDATE, TRIM(source.HCRESWKFLWS), TRIM(source.HCRESWORKED)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCRESULTCODE as source;
