
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCDDETAILLOG AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCCDDETAILLOG AS source
ON target.HCCDID = source.HCCDID
WHEN MATCHED THEN
  UPDATE SET
  target.HCCDACID = TRIM(source.HCCDACID),
 target.HCCDCLCAT = TRIM(source.HCCDCLCAT),
 target.HCCDCLDTE = TRIM(source.HCCDCLDTE),
 target.HCCDCLSCODE = TRIM(source.HCCDCLSCODE),
 target.HCCDCLSUBCAT = TRIM(source.HCCDCLSUBCAT),
 target.HCCDCOMPDTE = TRIM(source.HCCDCOMPDTE),
 target.HCCDCONSVY = TRIM(source.HCCDCONSVY),
 target.HCCDCSS = TRIM(source.HCCDCSS),
 target.HCCDDATASRC = TRIM(source.HCCDDATASRC),
 target.HCCDENID = TRIM(source.HCCDENID),
 target.HCCDEXPDTE = TRIM(source.HCCDEXPDTE),
 target.HCCDFACID = TRIM(source.HCCDFACID),
 target.HCCDFINCLASS = TRIM(source.HCCDFINCLASS),
 target.HCCDID = TRIM(source.HCCDID),
 target.HCCDMPAYERID = TRIM(source.HCCDMPAYERID),
 target.HCCDPAYERID = TRIM(source.HCCDPAYERID),
 target.HCCDREQDTE = TRIM(source.HCCDREQDTE),
 target.HCCDSTATUS = TRIM(source.HCCDSTATUS),
 target.HCCDTYPE = TRIM(source.HCCDTYPE),
 target.HCCDVERSION = TRIM(source.HCCDVERSION),
 target.PSCDNOIET = TRIM(source.PSCDNOIET),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (HCCDACID, HCCDCLCAT, HCCDCLDTE, HCCDCLSCODE, HCCDCLSUBCAT, HCCDCOMPDTE, HCCDCONSVY, HCCDCSS, HCCDDATASRC, HCCDENID, HCCDEXPDTE, HCCDFACID, HCCDFINCLASS, HCCDID, HCCDMPAYERID, HCCDPAYERID, HCCDREQDTE, HCCDSTATUS, HCCDTYPE, HCCDVERSION, PSCDNOIET, DWLastUpdateDateTime)
  VALUES (TRIM(source.HCCDACID), TRIM(source.HCCDCLCAT), TRIM(source.HCCDCLDTE), TRIM(source.HCCDCLSCODE), TRIM(source.HCCDCLSUBCAT), TRIM(source.HCCDCOMPDTE), TRIM(source.HCCDCONSVY), TRIM(source.HCCDCSS), TRIM(source.HCCDDATASRC), TRIM(source.HCCDENID), TRIM(source.HCCDEXPDTE), TRIM(source.HCCDFACID), TRIM(source.HCCDFINCLASS), TRIM(source.HCCDID), TRIM(source.HCCDMPAYERID), TRIM(source.HCCDPAYERID), TRIM(source.HCCDREQDTE), TRIM(source.HCCDSTATUS), TRIM(source.HCCDTYPE), TRIM(source.HCCDVERSION), TRIM(source.PSCDNOIET), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT HCCDID
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCDDETAILLOG
      GROUP BY HCCDID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCDDETAILLOG');
ELSE
  COMMIT TRANSACTION;
END IF;
