
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPOOLADDINFO ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPOOLADDINFO (POOL, PSPOOLDEPT, PSPOOLTYPE, PoolSubGroup, PoolFunction, PoolSLA, PSPOOLVENDOR, PSPOOLITMPRHR, PSPOOLVNDESC, PSPOOLLOB, PSPOOLMANAGER, PSPOOLPAYGRP, PSPOOLRESDEPT, PSPOOLTIER, PSPOOLESCPOOLFLG, PSPOOLCONCTRLNUM, PSPOOLEFFECTDTE, PSPOOLLABORSTDNAME)
SELECT TRIM(source.POOL), TRIM(source.PSPOOLDEPT), TRIM(source.PSPOOLTYPE), TRIM(source.PoolSubGroup), TRIM(source.PoolFunction), source.PoolSLA, TRIM(source.PSPOOLVENDOR), source.PSPOOLITMPRHR, TRIM(source.PSPOOLVNDESC), TRIM(source.PSPOOLLOB), TRIM(source.PSPOOLMANAGER), TRIM(source.PSPOOLPAYGRP), TRIM(source.PSPOOLRESDEPT), TRIM(source.PSPOOLTIER), TRIM(source.PSPOOLESCPOOLFLG), TRIM(source.PSPOOLCONCTRLNUM), source.PSPOOLEFFECTDTE, TRIM(source.PSPOOLLABORSTDNAME)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPOOLADDINFO as source;
