
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCERRORS AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSOCERRORS AS source
ON target.PSOCEKEY = source.PSOCEKEY
WHEN MATCHED THEN
  UPDATE SET
  target.PSOCEKEY = source.PSOCEKEY,
 target.PSOCEACTIONID = TRIM(source.PSOCEACTIONID),
 target.PSOCEACTIONNAME = TRIM(source.PSOCEACTIONNAME),
 target.PSOCECATEGORY = TRIM(source.PSOCECATEGORY),
 target.PSOCECROSSERROR = TRIM(source.PSOCECROSSERROR),
 target.PSOCECROSSROLL = TRIM(source.PSOCECROSSROLL),
 target.PSOCEERRORDTE = source.PSOCEERRORDTE,
 target.PSOCEERRORID = TRIM(source.PSOCEERRORID),
 target.PSOCEERRORMESSAGE = TRIM(source.PSOCEERRORMESSAGE),
 target.PSOCEINERROR = TRIM(source.PSOCEINERROR),
 target.PSOCELOADDTE = source.PSOCELOADDTE,
 target.PSOCENOTES = TRIM(source.PSOCENOTES),
 target.PSOCEOCID = source.PSOCEOCID,
 target.PSOCEORIGDTE = source.PSOCEORIGDTE,
 target.PSOCERSREASID = TRIM(source.PSOCERSREASID),
 target.PSOCERSREASON = TRIM(source.PSOCERSREASON),
 target.PSOCERSTEPID = TRIM(source.PSOCERSTEPID),
 target.PSOCERSTEPNAME = TRIM(source.PSOCERSTEPNAME),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSOCEKEY, PSOCEACTIONID, PSOCEACTIONNAME, PSOCECATEGORY, PSOCECROSSERROR, PSOCECROSSROLL, PSOCEERRORDTE, PSOCEERRORID, PSOCEERRORMESSAGE, PSOCEINERROR, PSOCELOADDTE, PSOCENOTES, PSOCEOCID, PSOCEORIGDTE, PSOCERSREASID, PSOCERSREASON, PSOCERSTEPID, PSOCERSTEPNAME, DWLastUpdateDateTime)
  VALUES (source.PSOCEKEY, TRIM(source.PSOCEACTIONID), TRIM(source.PSOCEACTIONNAME), TRIM(source.PSOCECATEGORY), TRIM(source.PSOCECROSSERROR), TRIM(source.PSOCECROSSROLL), source.PSOCEERRORDTE, TRIM(source.PSOCEERRORID), TRIM(source.PSOCEERRORMESSAGE), TRIM(source.PSOCEINERROR), source.PSOCELOADDTE, TRIM(source.PSOCENOTES), source.PSOCEOCID, source.PSOCEORIGDTE, TRIM(source.PSOCERSREASID), TRIM(source.PSOCERSREASON), TRIM(source.PSOCERSTEPID), TRIM(source.PSOCERSTEPNAME), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSOCEKEY
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCERRORS
      GROUP BY PSOCEKEY
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCERRORS');
ELSE
  COMMIT TRANSACTION;
END IF;
