
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESPAUTILITY ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESPAUTILITY (PSPESPACOUNTY, PSPESPACRTDTE, PSPESPACRTTIME, PSPESPAKEY, PSPESPALBN, PSPESPAPROCESSFLG, PSPESPASPECIALTY, PSPESPASSPDIVISION, PSPESPASTATE, PSPESPATAXID, PSPESPATAXONOMY)
SELECT TRIM(source.PSPESPACOUNTY), source.PSPESPACRTDTE, source.PSPESPACRTTIME, source.PSPESPAKEY, TRIM(source.PSPESPALBN), TRIM(source.PSPESPAPROCESSFLG), TRIM(source.PSPESPASPECIALTY), TRIM(source.PSPESPASSPDIVISION), TRIM(source.PSPESPASTATE), TRIM(source.PSPESPATAXID), TRIM(source.PSPESPATAXONOMY)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPESPAUTILITY as source;
