
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCTRANSACTIONS AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSOCTRANSACTIONS AS source
ON target.PSOCTRKEY = source.PSOCTRKEY
WHEN MATCHED THEN
  UPDATE SET
  target.PSOCTRKEY = source.PSOCTRKEY,
 target.PSOCTRCAT = TRIM(source.PSOCTRCAT),
 target.PSOCTRDATE = source.PSOCTRDATE,
 target.PSOCTRLOADDTE = source.PSOCTRLOADDTE,
 target.PSOCTRMOD1 = TRIM(source.PSOCTRMOD1),
 target.PSOCTRMOD2 = TRIM(source.PSOCTRMOD2),
 target.PSOCTRMOD3 = TRIM(source.PSOCTRMOD3),
 target.PSOCTRMOD4 = TRIM(source.PSOCTRMOD4),
 target.PSOCTROCID = source.PSOCTROCID,
 target.PSOCTRORIGDTE = source.PSOCTRORIGDTE,
 target.PSOCTRPROCCD = TRIM(source.PSOCTRPROCCD),
 target.PSOCTRPROCCDID = TRIM(source.PSOCTRPROCCDID),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSOCTRKEY, PSOCTRCAT, PSOCTRDATE, PSOCTRLOADDTE, PSOCTRMOD1, PSOCTRMOD2, PSOCTRMOD3, PSOCTRMOD4, PSOCTROCID, PSOCTRORIGDTE, PSOCTRPROCCD, PSOCTRPROCCDID, DWLastUpdateDateTime)
  VALUES (source.PSOCTRKEY, TRIM(source.PSOCTRCAT), source.PSOCTRDATE, source.PSOCTRLOADDTE, TRIM(source.PSOCTRMOD1), TRIM(source.PSOCTRMOD2), TRIM(source.PSOCTRMOD3), TRIM(source.PSOCTRMOD4), source.PSOCTROCID, source.PSOCTRORIGDTE, TRIM(source.PSOCTRPROCCD), TRIM(source.PSOCTRPROCCDID), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSOCTRKEY
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCTRANSACTIONS
      GROUP BY PSOCTRKEY
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCTRANSACTIONS');
ELSE
  COMMIT TRANSACTION;
END IF;
