
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPELOCATION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPELOCATION (PSPELOCADDR1, PSPELOCADDR2, PSPELOCALTEXT, PSPELOCCITY, PSPELOCCOUNTY, PSPELOCDESC, PSPELOCECWFACID, PSPELOCFAX, PSPELOCFULLADDR, PSPELOCKEY, PSPELOCMGREMAIL, PSPELOCOFFMGRNAME, PSPELOCPHONE, PSPELOCSTATE, PSPELOCTAXID, PSPELOCZIP)
SELECT TRIM(source.PSPELOCADDR1), TRIM(source.PSPELOCADDR2), TRIM(source.PSPELOCALTEXT), TRIM(source.PSPELOCCITY), TRIM(source.PSPELOCCOUNTY), TRIM(source.PSPELOCDESC), TRIM(source.PSPELOCECWFACID), TRIM(source.PSPELOCFAX), TRIM(source.PSPELOCFULLADDR), TRIM(source.PSPELOCKEY), TRIM(source.PSPELOCMGREMAIL), TRIM(source.PSPELOCOFFMGRNAME), TRIM(source.PSPELOCPHONE), TRIM(source.PSPELOCSTATE), TRIM(source.PSPELOCTAXID), TRIM(source.PSPELOCZIP)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPELOCATION as source;
