
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSCOID ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSCOID (PSCOIDKEY, PSCOIDSITEID, PSCOIDCOMPANY, PSCOIDDIVISION, PSCOIDGROUP, PSCOIDMARKET, PSCOIDNUMBER, PSCOIDREGION, PSCOIDLOCATIONCODE, PSCOIDDEPTCODE, PSCOIDPRACTICE, PSCOIDPROVIDER34, PSCOIDPROVIDERID, PSCOIDPROVTRMDTE, PSCOIDPROVTRMTYPE, PSCOIDPRACCLSDTE, PSCOIDPRACCLSTYPE, PSCOIDIETREROUTE, PSCOIDIETSRCEDEPT)
SELECT TRIM(source.PSCOIDKEY), TRIM(source.PSCOIDSITEID), TRIM(source.PSCOIDCOMPANY), TRIM(source.PSCOIDDIVISION), TRIM(source.PSCOIDGROUP), TRIM(source.PSCOIDMARKET), TRIM(source.PSCOIDNUMBER), TRIM(source.PSCOIDREGION), TRIM(source.PSCOIDLOCATIONCODE), TRIM(source.PSCOIDDEPTCODE), TRIM(source.PSCOIDPRACTICE), TRIM(source.PSCOIDPROVIDER34), TRIM(source.PSCOIDPROVIDERID), TRIM(source.PSCOIDPROVTRMDTE), TRIM(source.PSCOIDPROVTRMTYPE), TRIM(source.PSCOIDPRACCLSDTE), TRIM(source.PSCOIDPRACCLSTYPE), TRIM(source.PSCOIDIETREROUTE), TRIM(source.PSCOIDIETSRCEDEPT)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSCOID as source;
