
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCSTATUS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCSTATUS (HCSTACMSG, HCSTATID, HCSTBILLABLE, HCSTDESC, HCSTESCCD, HCSTESCDAYS, HCSTESCDAYSCRIPT, HCSTESCFILTER, HCSTESCSCRIPT, HCSTESCSTATSCRIPT, HCSTLINKFLG, HCSTPHASE, HCSTUPDRELACCTS, HCSTWORKED)
SELECT TRIM(source.HCSTACMSG), TRIM(source.HCSTATID), TRIM(source.HCSTBILLABLE), TRIM(source.HCSTDESC), TRIM(source.HCSTESCCD), source.HCSTESCDAYS, TRIM(source.HCSTESCDAYSCRIPT), TRIM(source.HCSTESCFILTER), TRIM(source.HCSTESCSCRIPT), TRIM(source.HCSTESCSTATSCRIPT), TRIM(source.HCSTLINKFLG), TRIM(source.HCSTPHASE), TRIM(source.HCSTUPDRELACCTS), TRIM(source.HCSTWORKED)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCSTATUS as source;
