
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPREDUCATION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPREDUCATION (PSPEPREDCERTNUM, PSPEPREDDEGREE, PSPEPREDENDDTE, PSPEPREDGAFID, PSPEPREDINID, PSPEPREDKEY, PSPEPREDPERFID, PSPEPREDPROGRAM, PSPEPREDSPECIALTY, PSPEPREDSTDTE, PSPEPREDTITLE)
SELECT TRIM(source.PSPEPREDCERTNUM), TRIM(source.PSPEPREDDEGREE), source.PSPEPREDENDDTE, TRIM(source.PSPEPREDGAFID), TRIM(source.PSPEPREDINID), TRIM(source.PSPEPREDKEY), TRIM(source.PSPEPREDPERFID), TRIM(source.PSPEPREDPROGRAM), TRIM(source.PSPEPREDSPECIALTY), source.PSPEPREDSTDTE, TRIM(source.PSPEPREDTITLE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPREDUCATION as source;
