
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSIETHIST AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSIETHIST AS source
ON target.PSIHID = source.PSIHID
WHEN MATCHED THEN
  UPDATE SET
  target.PSIHID = TRIM(source.PSIHID),
 target.PSIHABREVERRMSG = TRIM(source.PSIHABREVERRMSG),
 target.PSIHACCOUNTID = TRIM(source.PSIHACCOUNTID),
 target.PSIHACTIVE = TRIM(source.PSIHACTIVE),
 target.PSIHCARC = TRIM(source.PSIHCARC),
 target.PSIHCAT = TRIM(source.PSIHCAT),
 target.PSIHCATCD = TRIM(source.PSIHCATCD),
 target.PSIHCATTYPE = TRIM(source.PSIHCATTYPE),
 target.PSIHSUBCAT = TRIM(source.PSIHSUBCAT),
 target.PSIHTYPE = TRIM(source.PSIHTYPE),
 target.PSIHCHGTYPE = TRIM(source.PSIHCHGTYPE),
 target.PSIHCLMSTATUS = TRIM(source.PSIHCLMSTATUS),
 target.PSIHCROSSWALK = TRIM(source.PSIHCROSSWALK),
 target.PSIHCRTDTE = TRIM(source.PSIHCRTDTE),
 target.PSIHDELETE = TRIM(source.PSIHDELETE),
 target.PSIHDELETEDTE = TRIM(source.PSIHDELETEDTE),
 target.PSIHEFFDTE = TRIM(source.PSIHEFFDTE),
 target.PSIHELIGREJ = TRIM(source.PSIHELIGREJ),
 target.PSIHELIGREQDTE = TRIM(source.PSIHELIGREQDTE),
 target.PSIHELIGRESPDTE = TRIM(source.PSIHELIGRESPDTE),
 target.PSIHENCNTRID = TRIM(source.PSIHENCNTRID),
 target.PSIHERRDATA = TRIM(source.PSIHERRDATA),
 target.PSIHERRDTE = TRIM(source.PSIHERRDTE),
 target.PSIHERRFLD = TRIM(source.PSIHERRFLD),
 target.PSIHERRFLDNM = TRIM(source.PSIHERRFLDNM),
 target.PSIHERRINDEX = TRIM(source.PSIHERRINDEX),
 target.PSIHESC = TRIM(source.PSIHESC),
 target.PSIHEXPDTE = TRIM(source.PSIHEXPDTE),
 target.PSIHEXTCLOSURE = TRIM(source.PSIHEXTCLOSURE),
 target.PSIHNTEERRNM = TRIM(source.PSIHNTEERRNM),
 target.PSIHNTEHOLD = TRIM(source.PSIHNTEHOLD),
 target.PSIHSCSTATNTE = TRIM(source.PSIHSCSTATNTE),
 target.PSIHPAYERID = TRIM(source.PSIHPAYERID),
 target.PSIHPROCCD = TRIM(source.PSIHPROCCD),
 target.PSIHRARC = TRIM(source.PSIHRARC),
 target.PSIHRECFNDDTE = TRIM(source.PSIHRECFNDDTE),
 target.PSIHRELDTE = TRIM(source.PSIHRELDTE),
 target.PSIHREXPDTE = TRIM(source.PSIHREXPDTE),
 target.PSIHROUTE = TRIM(source.PSIHROUTE),
 target.PSIHRPTTYPE = TRIM(source.PSIHRPTTYPE),
 target.PSIHRTIME = TRIM(source.PSIHRTIME),
 target.PSIHRULEID = TRIM(source.PSIHRULEID),
 target.PSIHRULENM = TRIM(source.PSIHRULENM),
 target.PSIHSCID = TRIM(source.PSIHSCID),
 target.DwLastUpdateDateTime = source.DwLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSIHID, PSIHABREVERRMSG, PSIHACCOUNTID, PSIHACTIVE, PSIHCARC, PSIHCAT, PSIHCATCD, PSIHCATTYPE, PSIHSUBCAT, PSIHTYPE, PSIHCHGTYPE, PSIHCLMSTATUS, PSIHCROSSWALK, PSIHCRTDTE, PSIHDELETE, PSIHDELETEDTE, PSIHEFFDTE, PSIHELIGREJ, PSIHELIGREQDTE, PSIHELIGRESPDTE, PSIHENCNTRID, PSIHERRDATA, PSIHERRDTE, PSIHERRFLD, PSIHERRFLDNM, PSIHERRINDEX, PSIHESC, PSIHEXPDTE, PSIHEXTCLOSURE, PSIHNTEERRNM, PSIHNTEHOLD, PSIHSCSTATNTE, PSIHPAYERID, PSIHPROCCD, PSIHRARC, PSIHRECFNDDTE, PSIHRELDTE, PSIHREXPDTE, PSIHROUTE, PSIHRPTTYPE, PSIHRTIME, PSIHRULEID, PSIHRULENM, PSIHSCID, DwLastUpdateDateTime)
  VALUES (TRIM(source.PSIHID), TRIM(source.PSIHABREVERRMSG), TRIM(source.PSIHACCOUNTID), TRIM(source.PSIHACTIVE), TRIM(source.PSIHCARC), TRIM(source.PSIHCAT), TRIM(source.PSIHCATCD), TRIM(source.PSIHCATTYPE), TRIM(source.PSIHSUBCAT), TRIM(source.PSIHTYPE), TRIM(source.PSIHCHGTYPE), TRIM(source.PSIHCLMSTATUS), TRIM(source.PSIHCROSSWALK), TRIM(source.PSIHCRTDTE), TRIM(source.PSIHDELETE), TRIM(source.PSIHDELETEDTE), TRIM(source.PSIHEFFDTE), TRIM(source.PSIHELIGREJ), TRIM(source.PSIHELIGREQDTE), TRIM(source.PSIHELIGRESPDTE), TRIM(source.PSIHENCNTRID), TRIM(source.PSIHERRDATA), TRIM(source.PSIHERRDTE), TRIM(source.PSIHERRFLD), TRIM(source.PSIHERRFLDNM), TRIM(source.PSIHERRINDEX), TRIM(source.PSIHESC), TRIM(source.PSIHEXPDTE), TRIM(source.PSIHEXTCLOSURE), TRIM(source.PSIHNTEERRNM), TRIM(source.PSIHNTEHOLD), TRIM(source.PSIHSCSTATNTE), TRIM(source.PSIHPAYERID), TRIM(source.PSIHPROCCD), TRIM(source.PSIHRARC), TRIM(source.PSIHRECFNDDTE), TRIM(source.PSIHRELDTE), TRIM(source.PSIHREXPDTE), TRIM(source.PSIHROUTE), TRIM(source.PSIHRPTTYPE), TRIM(source.PSIHRTIME), TRIM(source.PSIHRULEID), TRIM(source.PSIHRULENM), TRIM(source.PSIHSCID), source.DwLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSIHID
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSIETHIST
      GROUP BY PSIHID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSIETHIST');
ELSE
  COMMIT TRANSACTION;
END IF;
