
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCLSUBCATEGORY ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgHCCLSUBCATEGORY (HCCCACTGRP, HCCCCAID, HCCCID, HCCCLDESC, HCCCLOADDATE, HCCCMODIFIEDDATE, HCCCSDESC, HCCCSTARTDATE, HCCCSTOPDATE, PSCCCSTYP, PSCCFOLLOWUPSUBCAT, PSCCIET, PSCCPRIORITY, PSCCSOURCE)
SELECT TRIM(source.HCCCACTGRP), TRIM(source.HCCCCAID), TRIM(source.HCCCID), TRIM(source.HCCCLDESC), source.HCCCLOADDATE, source.HCCCMODIFIEDDATE, TRIM(source.HCCCSDESC), source.HCCCSTARTDATE, source.HCCCSTOPDATE, TRIM(source.PSCCCSTYP), TRIM(source.PSCCFOLLOWUPSUBCAT), TRIM(source.PSCCIET), source.PSCCPRIORITY, TRIM(source.PSCCSOURCE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgHCCLSUBCATEGORY as source;
