
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRLICENSE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRLICENSE (PSPEPRLIAWARDDTE, PSPEPRLIENROLLSTAT, PSPEPRLIENSTASDTE, PSPEPRLIEXPDTE, PSPEPRLIGAFID, PSPEPRLIINID, PSPEPRLIKEY, PSPEPRLINUMBER, PSPEPRLIPERFID, PSPEPRLIPUBSTASDTE, PSPEPRLIPUBSTAT, PSPEPRLIPUBSTLITERAL, PSPEPRLISTATE, PSPEPRLISTATUS, PSPEPRLITYPE)
SELECT TRIM(source.PSPEPRLIAWARDDTE), TRIM(source.PSPEPRLIENROLLSTAT), source.PSPEPRLIENSTASDTE, source.PSPEPRLIEXPDTE, TRIM(source.PSPEPRLIGAFID), TRIM(source.PSPEPRLIINID), TRIM(source.PSPEPRLIKEY), TRIM(source.PSPEPRLINUMBER), TRIM(source.PSPEPRLIPERFID), source.PSPEPRLIPUBSTASDTE, TRIM(source.PSPEPRLIPUBSTAT), TRIM(source.PSPEPRLIPUBSTLITERAL), TRIM(source.PSPEPRLISTATE), TRIM(source.PSPEPRLISTATUS), TRIM(source.PSPEPRLITYPE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRLICENSE as source;
