
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRBOARD ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRBOARD (PSPEPRBDCERTBOARD, PSPEPRBDCERTDTE, PSPEPRBDCERTMAINT, PSPEPRBDCERTNUM, PSPEPRBDEXPDTE, PSPEPRBDGAFID, PSPEPRBDKEY, PSPEPRBDLCERT, PSPEPRBDPERFID, PSPEPRBDRECERTDTE, PSPEPRBDREVDTE, PSPEPRBDSTATUS)
SELECT TRIM(source.PSPEPRBDCERTBOARD), source.PSPEPRBDCERTDTE, TRIM(source.PSPEPRBDCERTMAINT), TRIM(source.PSPEPRBDCERTNUM), source.PSPEPRBDEXPDTE, TRIM(source.PSPEPRBDGAFID), TRIM(source.PSPEPRBDKEY), TRIM(source.PSPEPRBDLCERT), TRIM(source.PSPEPRBDPERFID), source.PSPEPRBDRECERTDTE, source.PSPEPRBDREVDTE, TRIM(source.PSPEPRBDSTATUS)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRBOARD as source;
