
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECONBASE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECONBASE (PSPEECOBDATE, PSPEECOBDESC, PSPEECOBECTID, PSPEECOBEXPORTDTE, PSPEECOBHANDLE, PSPEECOBID, PSPEECOBNEW, PSPEECOBPORTALECTID, PSPEECOBPORTALID, PSPEECOBPORTALKEY, PSPEECOBPPIID, PSPEECOBSOURCE, PSPEECOBTIME, PSPEECOBUSER)
SELECT source.PSPEECOBDATE, TRIM(source.PSPEECOBDESC), TRIM(source.PSPEECOBECTID), source.PSPEECOBEXPORTDTE, TRIM(source.PSPEECOBHANDLE), source.PSPEECOBID, TRIM(source.PSPEECOBNEW), TRIM(source.PSPEECOBPORTALECTID), TRIM(source.PSPEECOBPORTALID), TRIM(source.PSPEECOBPORTALKEY), TRIM(source.PSPEECOBPPIID), TRIM(source.PSPEECOBSOURCE), source.PSPEECOBTIME, TRIM(source.PSPEECOBUSER)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEECONBASE as source;
