
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIASSIGNMENTS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIASSIGNMENTS (PSPEASGADDPAYID, PSPEASGASSOCCOID, PSPEASGASSOCTAXID, PSPEASGGAFID, PSPEASGGIN, PSPEASGKEY, PSPEASGORIGENASGKEY, PSPEASGPAYORID, PSPEASGPERFID, PSPEASGPHYSADDR, PSPEASGSTDTE)
SELECT TRIM(source.PSPEASGADDPAYID), TRIM(source.PSPEASGASSOCCOID), TRIM(source.PSPEASGASSOCTAXID), TRIM(source.PSPEASGGAFID), TRIM(source.PSPEASGGIN), source.PSPEASGKEY, TRIM(source.PSPEASGORIGENASGKEY), TRIM(source.PSPEASGPAYORID), TRIM(source.PSPEASGPERFID), TRIM(source.PSPEASGPHYSADDR), source.PSPEASGSTDTE
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPPIASSIGNMENTS as source;
