
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAPPLICATIONS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAPPLICATIONS (PSPEAPPACTIONGROUP, PSPEAPPACTIVE, PSPEAPPAMTFIELD1, PSPEAPPAMTFIELD2, PSPEAPPCHRFIELD1, PSPEAPPCHRFIELD10, PSPEAPPCHRFIELD2, PSPEAPPCHRFIELD3, PSPEAPPCHRFIELD4, PSPEAPPCHRFIELD5, PSPEAPPCHRFIELD6, PSPEAPPCHRFIELD7, PSPEAPPCHRFIELD8, PSPEAPPCHRFIELD9, PSPEAPPDESC, PSPEAPPDTEFIELD1, PSPEAPPDTEFIELD2, PSPEAPPENABLEINS, PSPEAPPEXTFILE, PSPEAPPKEY)
SELECT TRIM(source.PSPEAPPACTIONGROUP), TRIM(source.PSPEAPPACTIVE), TRIM(source.PSPEAPPAMTFIELD1), TRIM(source.PSPEAPPAMTFIELD2), TRIM(source.PSPEAPPCHRFIELD1), TRIM(source.PSPEAPPCHRFIELD10), TRIM(source.PSPEAPPCHRFIELD2), TRIM(source.PSPEAPPCHRFIELD3), TRIM(source.PSPEAPPCHRFIELD4), TRIM(source.PSPEAPPCHRFIELD5), TRIM(source.PSPEAPPCHRFIELD6), TRIM(source.PSPEAPPCHRFIELD7), TRIM(source.PSPEAPPCHRFIELD8), TRIM(source.PSPEAPPCHRFIELD9), TRIM(source.PSPEAPPDESC), TRIM(source.PSPEAPPDTEFIELD1), TRIM(source.PSPEAPPDTEFIELD2), TRIM(source.PSPEAPPENABLEINS), TRIM(source.PSPEAPPEXTFILE), source.PSPEAPPKEY
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEAPPLICATIONS as source;
