
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECQUESRESP ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECQUESRESP (PSPEECQRECTID, PSPEECQREXPORTDTE, PSPEECQRGUID, PSPEECQRID, PSPEECQRLOADDTE, PSPEECQRPPIID, PSPEECQRQUESTION, PSPEECQRQUESTIONDTE, PSPEECQRQUESTIONTIME, PSPEECQRQUESTIONUSER, PSPEECQRQUESTYPE, PSPEECQRRESPONSE, PSPEECQRRESPONSEDTE, PSPEECQRRESPONSETIME, PSPEECQRRESPONSEUSER, PSPEECQRSOURCE, PSPEECQRSQUESTION, PSPEECQRSRESPONSE)
SELECT TRIM(source.PSPEECQRECTID), source.PSPEECQREXPORTDTE, TRIM(source.PSPEECQRGUID), source.PSPEECQRID, source.PSPEECQRLOADDTE, TRIM(source.PSPEECQRPPIID), TRIM(source.PSPEECQRQUESTION), source.PSPEECQRQUESTIONDTE, source.PSPEECQRQUESTIONTIME, TRIM(source.PSPEECQRQUESTIONUSER), TRIM(source.PSPEECQRQUESTYPE), TRIM(source.PSPEECQRRESPONSE), source.PSPEECQRRESPONSEDTE, source.PSPEECQRRESPONSETIME, TRIM(source.PSPEECQRRESPONSEUSER), TRIM(source.PSPEECQRSOURCE), TRIM(source.PSPEECQRSQUESTION), TRIM(source.PSPEECQRSRESPONSE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEECQUESRESP as source;
