
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRVERIFICATION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRVERIFICATION (PSPEPRVAFID, PSPEPRVAVIID, PSPEPRVBARCODE, PSPEPRVBDID, PSPEPRVEDID, PSPEPRVGAFID, PSPEPRVHOWV, PSPEPRVINSID, PSPEPRVLICID, PSPEPRVPERFID, PSPEPRVVERIFIED, PSPEPRVVERIFYDTE, PSPEPRVVERIFYUSER, PSPEPRVKEY)
SELECT TRIM(source.PSPEPRVAFID), TRIM(source.PSPEPRVAVIID), TRIM(source.PSPEPRVBARCODE), TRIM(source.PSPEPRVBDID), TRIM(source.PSPEPRVEDID), TRIM(source.PSPEPRVGAFID), TRIM(source.PSPEPRVHOWV), TRIM(source.PSPEPRVINSID), TRIM(source.PSPEPRVLICID), TRIM(source.PSPEPRVPERFID), TRIM(source.PSPEPRVVERIFIED), source.PSPEPRVVERIFYDTE, TRIM(source.PSPEPRVVERIFYUSER), TRIM(source.PSPEPRVKEY)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRVERIFICATION as source;
