
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPETIMEPPI AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPETIMEPPI AS source
ON target.PSPETIMEKEY = source.PSPETIMEKEY
WHEN MATCHED THEN
  UPDATE SET
  target.PSPETIMEAVIID = source.PSPETIMEAVIID,
 target.PSPETIMEDATE = source.PSPETIMEDATE,
 target.PSPETIMEETIME = source.PSPETIMEETIME,
 target.PSPETIMEKEY = source.PSPETIMEKEY,
 target.PSPETIMEPERFID = TRIM(source.PSPETIMEPERFID),
 target.PSPETIMEPPIID = TRIM(source.PSPETIMEPPIID),
 target.PSPETIMESTIME = source.PSPETIMESTIME,
 target.PSPETIMETIME = source.PSPETIMETIME,
 target.PSPETIMETTIME = source.PSPETIMETTIME,
 target.PSPETIMEUSER = TRIM(source.PSPETIMEUSER),
 target.PSPETIMEWORKED = TRIM(source.PSPETIMEWORKED),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSPETIMEAVIID, PSPETIMEDATE, PSPETIMEETIME, PSPETIMEKEY, PSPETIMEPERFID, PSPETIMEPPIID, PSPETIMESTIME, PSPETIMETIME, PSPETIMETTIME, PSPETIMEUSER, PSPETIMEWORKED, DWLastUpdateDateTime)
  VALUES (source.PSPETIMEAVIID, source.PSPETIMEDATE, source.PSPETIMEETIME, source.PSPETIMEKEY, TRIM(source.PSPETIMEPERFID), TRIM(source.PSPETIMEPPIID), source.PSPETIMESTIME, source.PSPETIMETIME, source.PSPETIMETTIME, TRIM(source.PSPETIMEUSER), TRIM(source.PSPETIMEWORKED), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSPETIMEKEY
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPETIMEPPI
      GROUP BY PSPETIMEKEY
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPETIMEPPI');
ELSE
  COMMIT TRANSACTION;
END IF;
