
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESYSALERTS ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPESYSALERTS (PSPESYSALRACTDTE, PSPESYSALRACTIVE, PSPESYSALRCRTDTE, PSPESYSALRCRTTIM, PSPESYSALRCRTUSER, PSPESYSALREXPDTE, PSPESYSALRGRPAVIFLG, PSPESYSALRGRPID, PSPESYSALRKEY, PSPESYSALRPROVID, PSPESYSALRSDESC, PSPESYSALRTEXT)
SELECT source.PSPESYSALRACTDTE, TRIM(source.PSPESYSALRACTIVE), source.PSPESYSALRCRTDTE, source.PSPESYSALRCRTTIM, TRIM(source.PSPESYSALRCRTUSER), source.PSPESYSALREXPDTE, TRIM(source.PSPESYSALRGRPAVIFLG), TRIM(source.PSPESYSALRGRPID), source.PSPESYSALRKEY, TRIM(source.PSPESYSALRPROVID), TRIM(source.PSPESYSALRSDESC), TRIM(source.PSPESYSALRTEXT)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPESYSALERTS as source;
