
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAVI ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAVI (PSPEAVIAPPRECVDTE, PSPEAVIAPPSENTDTE, PSPEAVIATTESTDTE, PSPEAVICRCOMPDTE, PSPEAVICREDCOMP, PSPEAVICRGRPKEY, PSPEAVICRSTARTDTE, PSPEAVICRSTASOFDTE, PSPEAVICRSTATUS, PSPEAVIDESC, PSPEAVIENTDESC, PSPEAVIFACID, PSPEAVIGAFID, PSPEAVIKEY, PSPEAVIORIGDATE, PSPEAVIPERFID, PSPEAVIRFCCOMPDTE, PSPEAVISTCHGDTE, PSPEAVITAXID, PSPEAVITYPE)
SELECT source.PSPEAVIAPPRECVDTE, source.PSPEAVIAPPSENTDTE, source.PSPEAVIATTESTDTE, source.PSPEAVICRCOMPDTE, TRIM(source.PSPEAVICREDCOMP), TRIM(source.PSPEAVICRGRPKEY), source.PSPEAVICRSTARTDTE, source.PSPEAVICRSTASOFDTE, TRIM(source.PSPEAVICRSTATUS), TRIM(source.PSPEAVIDESC), TRIM(source.PSPEAVIENTDESC), TRIM(source.PSPEAVIFACID), TRIM(source.PSPEAVIGAFID), source.PSPEAVIKEY, source.PSPEAVIORIGDATE, TRIM(source.PSPEAVIPERFID), source.PSPEAVIRFCCOMPDTE, source.PSPEAVISTCHGDTE, TRIM(source.PSPEAVITAXID), TRIM(source.PSPEAVITYPE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEAVI as source;
