
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECREQTYPE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEECREQTYPE (PSPEECREQACTGRP, PSPEECREQASSIGNEDTO, PSPEECREQAUTOGRP, PSPEECREQAUTOPROV, PSPEECREQAVITYPE, PSPEECREQCLOSEACTGRP, PSPEECREQDESC, PSPEECREQESC1, PSPEECREQESC2, PSPEECREQFOECTTYPE, PSPEECREQLOCKED, PSPEECREQPPITYPE, PSPEECREQPRI, PSPEECREQRTE, PSPEECREQSIGREQ, PSPEECREQSPANPPI, PSPEECREQTYP, PSPEECRTID, PSPEECREQYC, PSPEECREQYF, PSPEECREQTYPEIND)
SELECT TRIM(source.PSPEECREQACTGRP), TRIM(source.PSPEECREQASSIGNEDTO), TRIM(source.PSPEECREQAUTOGRP), TRIM(source.PSPEECREQAUTOPROV), TRIM(source.PSPEECREQAVITYPE), TRIM(source.PSPEECREQCLOSEACTGRP), TRIM(source.PSPEECREQDESC), TRIM(source.PSPEECREQESC1), TRIM(source.PSPEECREQESC2), TRIM(source.PSPEECREQFOECTTYPE), TRIM(source.PSPEECREQLOCKED), TRIM(source.PSPEECREQPPITYPE), TRIM(source.PSPEECREQPRI), TRIM(source.PSPEECREQRTE), TRIM(source.PSPEECREQSIGREQ), TRIM(source.PSPEECREQSPANPPI), TRIM(source.PSPEECREQTYP), TRIM(source.PSPEECRTID), TRIM(source.PSPEECREQYC), TRIM(source.PSPEECREQYF), TRIM(source.PSPEECREQTYPEIND)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEECREQTYPE as source;
