
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSENHOLDRULEHIST ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSENHOLDRULEHIST (PSENHRHKEY, PSENHRHACTDTE, PSENHRHCPIDID, PSENHRHENCNTRID, PSENHRHFINCLASS, PSENHRHHOLDCODE, PSENHRHHOLDDESC, PSENHRHHRUID, PSENHRHRELDTE)
SELECT source.PSENHRHKEY, source.PSENHRHACTDTE, TRIM(source.PSENHRHCPIDID), source.PSENHRHENCNTRID, TRIM(source.PSENHRHFINCLASS), TRIM(source.PSENHRHHOLDCODE), TRIM(source.PSENHRHHOLDDESC), source.PSENHRHHRUID, source.PSENHRHRELDTE
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSENHOLDRULEHIST as source;
