
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRINSURANCE ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRINSURANCE (PSPEPRINAGENT, PSPEPRINCARRIER, PSPEPRINCONEMAIL, PSPEPRINCONFAX, PSPEPRINCONNAME, PSPEPRINCONPHONE, PSPEPRINCOVTYPE, PSPEPRINEFFDTE, PSPEPRINEXPDTE, PSPEPRINGAFID, PSPEPRININFORCEIND, PSPEPRININID, PSPEPRINKEY, PSPEPRINPERFID, PSPEPRINPOLNUM, PSPEPRINPRIMLIMAGG, PSPEPRINPRIMLIMIT, PSPEPRINPRIVLIMIT, PSPEPRINRETRODTE)
SELECT TRIM(source.PSPEPRINAGENT), TRIM(source.PSPEPRINCARRIER), TRIM(source.PSPEPRINCONEMAIL), TRIM(source.PSPEPRINCONFAX), TRIM(source.PSPEPRINCONNAME), TRIM(source.PSPEPRINCONPHONE), TRIM(source.PSPEPRINCOVTYPE), source.PSPEPRINEFFDTE, source.PSPEPRINEXPDTE, TRIM(source.PSPEPRINGAFID), TRIM(source.PSPEPRININFORCEIND), TRIM(source.PSPEPRININID), TRIM(source.PSPEPRINKEY), TRIM(source.PSPEPRINPERFID), TRIM(source.PSPEPRINPOLNUM), source.PSPEPRINPRIMLIMAGG, source.PSPEPRINPRIMLIMIT, TRIM(source.PSPEPRINPRIVLIMIT), source.PSPEPRINRETRODTE
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRINSURANCE as source;
