
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCACTIONHIST AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSOCACTIONHIST AS source
ON target.PSOCACTHID = source.PSOCACTHID
WHEN MATCHED THEN
  UPDATE SET
  target.PSOCACTHACTID = TRIM(source.PSOCACTHACTID),
 target.PSOCACTHAMTFLD1 = TRIM(source.PSOCACTHAMTFLD1),
 target.PSOCACTHAMTFLD2 = TRIM(source.PSOCACTHAMTFLD2),
 target.PSOCACTHAMTFLDVAL1 = source.PSOCACTHAMTFLDVAL1,
 target.PSOCACTHAMTFLDVAL2 = source.PSOCACTHAMTFLDVAL2,
 target.PSOCACTHDTE = source.PSOCACTHDTE,
 target.PSOCACTHDTEFLD1 = TRIM(source.PSOCACTHDTEFLD1),
 target.PSOCACTHDTEFLD2 = TRIM(source.PSOCACTHDTEFLD2),
 target.PSOCACTHDTEFLD3 = TRIM(source.PSOCACTHDTEFLD3),
 target.PSOCACTHDTEFLDVAL1 = source.PSOCACTHDTEFLDVAL1,
 target.PSOCACTHDTEFLDVAL2 = source.PSOCACTHDTEFLDVAL2,
 target.PSOCACTHDTEFLDVAL3 = source.PSOCACTHDTEFLDVAL3,
 target.PSOCACTHFLD1 = TRIM(source.PSOCACTHFLD1),
 target.PSOCACTHFLD10 = TRIM(source.PSOCACTHFLD10),
 target.PSOCACTHFLD11 = TRIM(source.PSOCACTHFLD11),
 target.PSOCACTHFLD12 = TRIM(source.PSOCACTHFLD12),
 target.PSOCACTHFLD2 = TRIM(source.PSOCACTHFLD2),
 target.PSOCACTHFLD3 = TRIM(source.PSOCACTHFLD3),
 target.PSOCACTHFLD4 = TRIM(source.PSOCACTHFLD4),
 target.PSOCACTHFLD5 = TRIM(source.PSOCACTHFLD5),
 target.PSOCACTHFLD6 = TRIM(source.PSOCACTHFLD6),
 target.PSOCACTHFLD7 = TRIM(source.PSOCACTHFLD7),
 target.PSOCACTHFLD8 = TRIM(source.PSOCACTHFLD8),
 target.PSOCACTHFLD9 = TRIM(source.PSOCACTHFLD9),
 target.PSOCACTHFLDVAL1 = TRIM(source.PSOCACTHFLDVAL1),
 target.PSOCACTHFLDVAL10 = TRIM(source.PSOCACTHFLDVAL10),
 target.PSOCACTHFLDVAL11 = TRIM(source.PSOCACTHFLDVAL11),
 target.PSOCACTHFLDVAL12 = TRIM(source.PSOCACTHFLDVAL12),
 target.PSOCACTHFLDVAL2 = TRIM(source.PSOCACTHFLDVAL2),
 target.PSOCACTHFLDVAL3 = TRIM(source.PSOCACTHFLDVAL3),
 target.PSOCACTHFLDVAL4 = TRIM(source.PSOCACTHFLDVAL4),
 target.PSOCACTHFLDVAL5 = TRIM(source.PSOCACTHFLDVAL5),
 target.PSOCACTHFLDVAL6 = TRIM(source.PSOCACTHFLDVAL6),
 target.PSOCACTHFLDVAL7 = TRIM(source.PSOCACTHFLDVAL7),
 target.PSOCACTHFLDVAL8 = TRIM(source.PSOCACTHFLDVAL8),
 target.PSOCACTHFLDVAL9 = TRIM(source.PSOCACTHFLDVAL9),
 target.PSOCACTHNOTE = TRIM(source.PSOCACTHNOTE),
 target.PSOCACTHNOTELINE = TRIM(source.PSOCACTHNOTELINE),
 target.PSOCACTHOCID = source.PSOCACTHOCID,
 target.PSOCACTHPOOLID = TRIM(source.PSOCACTHPOOLID),
 target.PSOCACTHRESID = TRIM(source.PSOCACTHRESID),
 target.PSOCACTHSTAT = TRIM(source.PSOCACTHSTAT),
 target.PSOCACTHTIME = source.PSOCACTHTIME,
 target.PSOCACTHUSERDEPT = TRIM(source.PSOCACTHUSERDEPT),
 target.PSOCACTHUSERDNAME = TRIM(source.PSOCACTHUSERDNAME),
 target.PSOCACTHUSERID = TRIM(source.PSOCACTHUSERID),
 target.PSOCACTHWINDOW = TRIM(source.PSOCACTHWINDOW),
 target.PSOCACTHID = source.PSOCACTHID,
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSOCACTHACTID, PSOCACTHAMTFLD1, PSOCACTHAMTFLD2, PSOCACTHAMTFLDVAL1, PSOCACTHAMTFLDVAL2, PSOCACTHDTE, PSOCACTHDTEFLD1, PSOCACTHDTEFLD2, PSOCACTHDTEFLD3, PSOCACTHDTEFLDVAL1, PSOCACTHDTEFLDVAL2, PSOCACTHDTEFLDVAL3, PSOCACTHFLD1, PSOCACTHFLD10, PSOCACTHFLD11, PSOCACTHFLD12, PSOCACTHFLD2, PSOCACTHFLD3, PSOCACTHFLD4, PSOCACTHFLD5, PSOCACTHFLD6, PSOCACTHFLD7, PSOCACTHFLD8, PSOCACTHFLD9, PSOCACTHFLDVAL1, PSOCACTHFLDVAL10, PSOCACTHFLDVAL11, PSOCACTHFLDVAL12, PSOCACTHFLDVAL2, PSOCACTHFLDVAL3, PSOCACTHFLDVAL4, PSOCACTHFLDVAL5, PSOCACTHFLDVAL6, PSOCACTHFLDVAL7, PSOCACTHFLDVAL8, PSOCACTHFLDVAL9, PSOCACTHNOTE, PSOCACTHNOTELINE, PSOCACTHOCID, PSOCACTHPOOLID, PSOCACTHRESID, PSOCACTHSTAT, PSOCACTHTIME, PSOCACTHUSERDEPT, PSOCACTHUSERDNAME, PSOCACTHUSERID, PSOCACTHWINDOW, PSOCACTHID, DWLastUpdateDateTime)
  VALUES (TRIM(source.PSOCACTHACTID), TRIM(source.PSOCACTHAMTFLD1), TRIM(source.PSOCACTHAMTFLD2), source.PSOCACTHAMTFLDVAL1, source.PSOCACTHAMTFLDVAL2, source.PSOCACTHDTE, TRIM(source.PSOCACTHDTEFLD1), TRIM(source.PSOCACTHDTEFLD2), TRIM(source.PSOCACTHDTEFLD3), source.PSOCACTHDTEFLDVAL1, source.PSOCACTHDTEFLDVAL2, source.PSOCACTHDTEFLDVAL3, TRIM(source.PSOCACTHFLD1), TRIM(source.PSOCACTHFLD10), TRIM(source.PSOCACTHFLD11), TRIM(source.PSOCACTHFLD12), TRIM(source.PSOCACTHFLD2), TRIM(source.PSOCACTHFLD3), TRIM(source.PSOCACTHFLD4), TRIM(source.PSOCACTHFLD5), TRIM(source.PSOCACTHFLD6), TRIM(source.PSOCACTHFLD7), TRIM(source.PSOCACTHFLD8), TRIM(source.PSOCACTHFLD9), TRIM(source.PSOCACTHFLDVAL1), TRIM(source.PSOCACTHFLDVAL10), TRIM(source.PSOCACTHFLDVAL11), TRIM(source.PSOCACTHFLDVAL12), TRIM(source.PSOCACTHFLDVAL2), TRIM(source.PSOCACTHFLDVAL3), TRIM(source.PSOCACTHFLDVAL4), TRIM(source.PSOCACTHFLDVAL5), TRIM(source.PSOCACTHFLDVAL6), TRIM(source.PSOCACTHFLDVAL7), TRIM(source.PSOCACTHFLDVAL8), TRIM(source.PSOCACTHFLDVAL9), TRIM(source.PSOCACTHNOTE), TRIM(source.PSOCACTHNOTELINE), source.PSOCACTHOCID, TRIM(source.PSOCACTHPOOLID), TRIM(source.PSOCACTHRESID), TRIM(source.PSOCACTHSTAT), source.PSOCACTHTIME, TRIM(source.PSOCACTHUSERDEPT), TRIM(source.PSOCACTHUSERDNAME), TRIM(source.PSOCACTHUSERID), TRIM(source.PSOCACTHWINDOW), source.PSOCACTHID, source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSOCACTHID
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCACTIONHIST
      GROUP BY PSOCACTHID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSOCACTIONHIST');
ELSE
  COMMIT TRANSACTION;
END IF;
