
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRLOCATION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRLOCATION (PSPEPRLOCACTIVE, PSPEPRLOCADDRTYP, PSPEPRLOCCOID, PSPEPRLOCFRMDTE, PSPEPRLOCGAFID, PSPEPRLOCGRPLOCID, PSPEPRLOCKEY, PSPEPRLOCPERFID, PSPEPRLOCSILENT, PSPEPRLOCTERMED, PSPEPRLOCTODTE, PSPEPRLOCLOADDTE, PSPEPRLOCNPI, PSPEPRLOCTHLOC)
SELECT TRIM(source.PSPEPRLOCACTIVE), TRIM(source.PSPEPRLOCADDRTYP), TRIM(source.PSPEPRLOCCOID), source.PSPEPRLOCFRMDTE, TRIM(source.PSPEPRLOCGAFID), TRIM(source.PSPEPRLOCGRPLOCID), TRIM(source.PSPEPRLOCKEY), TRIM(source.PSPEPRLOCPERFID), TRIM(source.PSPEPRLOCSILENT), TRIM(source.PSPEPRLOCTERMED), source.PSPEPRLOCTODTE, source.PSPEPRLOCLOADDTE, TRIM(source.PSPEPRLOCNPI), TRIM(source.PSPEPRLOCTHLOC)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRLOCATION as source;
