
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRAFFILIATION ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPRAFFILIATION (PSPEPRAFACTIVE, PSPEPRAFCATEGORY, PSPEPRAFFINISHDTE, PSPEPRAFGAFID, PSPEPRAFINID, PSPEPRAFINSTYPE, PSPEPRAFKEY, PSPEPRAFPERFID, PSPEPRAFSPECIALTY, PSPEPRAFSTARTDTE, PSPEPRAFTYPE)
SELECT TRIM(source.PSPEPRAFACTIVE), TRIM(source.PSPEPRAFCATEGORY), source.PSPEPRAFFINISHDTE, TRIM(source.PSPEPRAFGAFID), TRIM(source.PSPEPRAFINID), TRIM(source.PSPEPRAFINSTYPE), TRIM(source.PSPEPRAFKEY), TRIM(source.PSPEPRAFPERFID), TRIM(source.PSPEPRAFSPECIALTY), source.PSPEPRAFSTARTDTE, TRIM(source.PSPEPRAFTYPE)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPRAFFILIATION as source;
