
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgGCPOOLGENINFO ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgGCPOOLGENINFO (POOL, GCPDESC, TOTAL_BUILD_TIME, BEGINNING_BALANCE, ACCOUNTS_REMAINING, RECORDS_ADDED, BUILD_START_DATE, BUILD_START_TIME, BUILD_FINISH_DATE, BUILD_FINISH_TIME, SNAPSHOT_DATE)
SELECT TRIM(source.POOL), TRIM(source.GCPDESC), source.TOTAL_BUILD_TIME, source.BEGINNING_BALANCE, source.ACCOUNTS_REMAINING, source.RECORDS_ADDED, TRIM(source.BUILD_START_DATE), TRIM(source.BUILD_START_TIME), TRIM(source.BUILD_FINISH_DATE), TRIM(source.BUILD_FINISH_TIME), source.SNAPSHOT_DATE
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgGCPOOLGENINFO as source;
