
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIHIST AS target
USING {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPPIHIST AS source
ON target.PSPEPPIHKEY = source.PSPEPPIHKEY
WHEN MATCHED THEN
  UPDATE SET
  target.PSPEPPIHACTION = TRIM(source.PSPEPPIHACTION),
 target.PSPEPPIHAVIID = source.PSPEPPIHAVIID,
 target.PSPEPPIHDATE = source.PSPEPPIHDATE,
 target.PSPEPPIHFROMAMTVAL = source.PSPEPPIHFROMAMTVAL,
 target.PSPEPPIHFROMCALC = TRIM(source.PSPEPPIHFROMCALC),
 target.PSPEPPIHFROMDATEVAL = source.PSPEPPIHFROMDATEVAL,
 target.PSPEPPIHFROMVAL = TRIM(source.PSPEPPIHFROMVAL),
 target.PSPEPPIHKEY = source.PSPEPPIHKEY,
 target.PSPEPPIHLPOOL = TRIM(source.PSPEPPIHLPOOL),
 target.PSPEPPIHPERFID = TRIM(source.PSPEPPIHPERFID),
 target.PSPEPPIHPPIID = source.PSPEPPIHPPIID,
 target.PSPEPPIHTIME = source.PSPEPPIHTIME,
 target.PSPEPPIHTOAMTVAL = source.PSPEPPIHTOAMTVAL,
 target.PSPEPPIHTOCALC = TRIM(source.PSPEPPIHTOCALC),
 target.PSPEPPIHTODATEVAL = source.PSPEPPIHTODATEVAL,
 target.PSPEPPIHTOVAL = TRIM(source.PSPEPPIHTOVAL),
 target.PSPEPPIHUSERID = TRIM(source.PSPEPPIHUSERID),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (PSPEPPIHACTION, PSPEPPIHAVIID, PSPEPPIHDATE, PSPEPPIHFROMAMTVAL, PSPEPPIHFROMCALC, PSPEPPIHFROMDATEVAL, PSPEPPIHFROMVAL, PSPEPPIHKEY, PSPEPPIHLPOOL, PSPEPPIHPERFID, PSPEPPIHPPIID, PSPEPPIHTIME, PSPEPPIHTOAMTVAL, PSPEPPIHTOCALC, PSPEPPIHTODATEVAL, PSPEPPIHTOVAL, PSPEPPIHUSERID, DWLastUpdateDateTime)
  VALUES (TRIM(source.PSPEPPIHACTION), source.PSPEPPIHAVIID, source.PSPEPPIHDATE, source.PSPEPPIHFROMAMTVAL, TRIM(source.PSPEPPIHFROMCALC), source.PSPEPPIHFROMDATEVAL, TRIM(source.PSPEPPIHFROMVAL), source.PSPEPPIHKEY, TRIM(source.PSPEPPIHLPOOL), TRIM(source.PSPEPPIHPERFID), source.PSPEPPIHPPIID, source.PSPEPPIHTIME, source.PSPEPPIHTOAMTVAL, TRIM(source.PSPEPPIHTOCALC), source.PSPEPPIHTODATEVAL, TRIM(source.PSPEPPIHTOVAL), TRIM(source.PSPEPPIHUSERID), source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT PSPEPPIHKEY
      FROM {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIHIST
      GROUP BY PSPEPPIHKEY
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIHIST');
ELSE
  COMMIT TRANSACTION;
END IF;
