
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAVICHKLIST ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEAVICHKLIST (PSPEAVICHKAVIID, PSPEAVICHKCOMP, PSPEAVICHKCOMPDTE, PSPEAVICHKGAFID, PSPEAVICHKKEY, PSPEAVICHKORIGQKEY, PSPEAVICHKPERFID, PSPEAVICHKRESPONSE, PSPEAVICHKTASK)
SELECT TRIM(source.PSPEAVICHKAVIID), TRIM(source.PSPEAVICHKCOMP), source.PSPEAVICHKCOMPDTE, TRIM(source.PSPEAVICHKGAFID), source.PSPEAVICHKKEY, TRIM(source.PSPEAVICHKORIGQKEY), TRIM(source.PSPEAVICHKPERFID), TRIM(source.PSPEAVICHKRESPONSE), TRIM(source.PSPEAVICHKTASK)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEAVICHKLIST as source;
