
        
TRUNCATE TABLE {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIACTIONPLAN ;

INSERT INTO {{ params.param_psc_core_dataset_name }}.Artiva_StgPSPEPPIACTIONPLAN (PSPEPPIAPINCFLAG, PSPEPPIAPKEY, PSPEPPIAPORIGDTE, PSPEPPIAPPANELS, PSPEPPIAPPAYID, PSPEPPIAPPPICRTDTE, PSPEPPIAPPPIID, PSPEPPIAPSPATMPID, PSPEPPIAPSUBDTE, PSPEPPIAPREJREASON)
SELECT TRIM(source.PSPEPPIAPINCFLAG), source.PSPEPPIAPKEY, source.PSPEPPIAPORIGDTE, TRIM(source.PSPEPPIAPPANELS), TRIM(source.PSPEPPIAPPAYID), source.PSPEPPIAPPPICRTDTE, source.PSPEPPIAPPPIID, source.PSPEPPIAPSPATMPID, source.PSPEPPIAPSUBDTE, TRIM(source.PSPEPPIAPREJREASON)
FROM {{ params.param_psc_stage_dataset_name }}.Artiva_StgPSPEPPIACTIONPLAN as source;
