SELECT 'J_MHB_PATIENT_VITAL_AUDITS' || ',' || CAST (COUNT (*) AS VARCHAR (20)) || ','
AS SOURCE_STRING FROM (
SEL * FROM
EDWCI.MHB_PATIENT_VITAL_AUDIT
WHERE DW_LAST_UPDATE_DATE_TIME (DATE) = CURRENT_DATE
)Q