SELECT
	F.HCFAPASID as SSC ,
	'AR1' AS Artivainstancecode ,
	L.HCLHENCNTRID AS Encounter_ID ,
	F.CSFAHOSPNUM AS Unit_Num ,
	E.HCENPTACCT AS PatAcct ,
	A.HCACSEQNUM AS Ins_Iplan_Order_Num ,
	A.CSACIPLAN AS IPlan_ID ,
	L.HCLHACCT AS Liabilty_Number ,
	L.HCLHUSERID AS User_Desc ,
	L.HCLHDATE AS Letter_Sent_Date ,
	L.HCLHTIME AS Letter_Sent_Time ,
	L.HCLHID AS Letter_ID , 
	L.HCLHLTRID AS Letter_Code ,
	L.HCLHLTRDESC AS Letter_Desc ,
	L.CSLHLTRDETYN AS Free_Form_Ind ,
	L.HCLHACTION AS Ltr_Action ,
	L.CSLHTRACKNO AS Tracking_Num ,
	L.HCLHBAL AS Acct_Balance ,
                'v_currtimestamp' AS DW_Last_Update_Date_Time

FROM SQLUser.HCENCOUNTER E
	LEFT OUTER JOIN SQLUser.HCFACILITY F ON F.HCFAID = E.HCENFACILITY
	INNER JOIN SQLUser.HCLTRHIST L ON L.HCLHENCNTRID = E.HCENID
	LEFT OUTER JOIN SQLUSER.HCACCOUNT A ON A.HCACENCNTRID = E.HCENID
		AND A.HCACLDACCT = L.HCLHACCT