--AUDIT MISSED OPPORTUNITIES (ERROR DETAIL)					(UPDATED 10/30/2020)
SELECT 
    (CASE 
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' THEN REPLACE((HCFACILITY.HCFAPASID), 'CAPELLA', 'CLIENT-NAS')
        WHEN HCFACILITY.HCFAPASID LIKE '%LIFEPOINT%' THEN REPLACE((HCFACILITY.HCFAPASID), 'LIFEPOINT', 'CLIENT')
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' THEN 'DAL/SAN'
        WHEN HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS PASID -- STUSERAUDITACCT.CSUAAFAPASID    -- PENDING ARTIVA INTEGRATION TO STUSERAUDITACCT TABLE
    , (CASE
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' OR HCFACILITY.HCFAPASID = 'CLIENT-NAS' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-NAS' THEN 'NASHVILLE'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-OPK' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-OPK' THEN 'ORANGEPARK'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-RIC' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-RIC' THEN 'RICHMOND'
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' OR HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS SSC
    , STUSERAUDIT.CSUAMONTHLYREVIEWID, STUSERAUDIT.STUAMONTH, STUSERAUDIT.STUAYEAR, STUSERAUDIT.STUARVWEND, STUSERAUDIT.STUAPHASE, STUSERAUDITACCT.STUAAAUDITID, STUSERAUDITACCT.STUAAID
    , STUSERAUDITSUM.STUSARESID, STUSERAUDITSUM.STUSASORT, STUSERAUDITSUM.STUSADATE, STUSERAUDITSUM.STUSAFIELD
    , STUSERAUDITSUM.STUSAGUIDEID, UPPER(STGUIDEPAGE.STGDPGCAPTION) AS STGDPGCAPTION, STUSERAUDITSUM.STUSAID
--    , STUSERAUDITSUM.STUSALABEL--, STUSERAUDITSUM.STUSAQUESTIONID
    , (CASE 
        WHEN LEN(STUSERAUDITSUM.STUSALABEL) > 109 THEN LEFT(STUSERAUDITSUM.STUSALABEL,109) ELSE STUSERAUDITSUM.STUSALABEL END) AS STUSALABEL
    , LEFT(STUSERAUDITSUM.STUSAVALUE, 499) AS STUSAVALUE
    , (CASE 
        WHEN LEN(STUSERAUDITSUM.CSUSACOMMENT) > 250 THEN REPLACE(REPLACE((LEFT(STUSERAUDITSUM.CSUSACOMMENT,250)), char(10), '|'), char(13), '|') ELSE REPLACE(REPLACE(STUSERAUDITSUM.CSUSACOMMENT, char(10), '|'), char(13), '|') END) AS CSUSACOMMENT
,STUSAPAGEID
,STUSERAUDITACCT.CSUAAFAHOSPNUM AS UNIT,
STUSERAUDITACCT.CSUAAENPTACCT AS ENPATACCT
FROM (((SQLUser.STUSERAUDIT STUSERAUDIT LEFT OUTER JOIN SQLUser.STUSERAUDITACCT STUSERAUDITACCT ON STUSERAUDIT.STUAID=STUSERAUDITACCT.STUAAAUDITID)
    LEFT OUTER JOIN SQLUser.STUSERAUDITSUM STUSERAUDITSUM ON STUSERAUDITACCT.STUAAID = STUSERAUDITSUM.STUSARESID)
        LEFT OUTER JOIN SQLUser.STGUIDEPAGE ON STUSERAUDITSUM.STUSAPAGEID = STGUIDEPAGE.STGDPGID)
        , SQLUser.HCFACILITY HCFACILITY  
WHERE STUSERAUDITACCT.CSUAAFAHOSPNUM = HCFACILITY.CSFAHOSPNUM  AND STUSERAUDIT.STUARVWEND >= '2020-11-01' --AND STUSAVALUE = 'N' --Removed the filter even though provided from User's query
ORDER BY STUSERAUDITACCT.STUAAAUDITID ASC, STUSERAUDITSUM.STUSARESID ASC, STUSERAUDITSUM.STUSASORT ASC