create table if not exists {{ params.param_hr_core_dataset_name }}.bi_executive_current (
employee_sid int64 not null options(description="unique etl generated number for an hca employee number")
, reporting_period string not null options(description="this is the month and year that the data is valid for. data is refreshed on the 15th of each month")
, employee_num int64 options(description="it defines employee number")
, lawson_company_num int64 options(description="unique four digit numeric value of lawson generated hr company maintained in this field")
, group_name string options(description="the name of the group the division rolls up to.")
, division_name string options(description="the name of the division the market rolls up to.")
, market_name string options(description="the name of the market the facility rolls up to.")
, coid_name string options(description="the name of the facility that the employee works for.")
, coid string options(description="the company identifier which uniquely identifies a facility to corporate and all other facilities.")
, company_code string options(description="part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.")
, lob_code string options(description="three character code that identifies the line of business the process level is associated with.")
, hospital_category_code string options(description="it captures current level of facility")
, facility_street_address_1_text string options(description="address line 1 of the facility.")
, facility_street_address_2_text string options(description="address line 2 of the facility.")
, facility_city_name string options(description="city name of the facility.")
, facility_state_code string options(description="the state code is the abbreviated 2 character code associated with the address state for a person or organization.")
, facility_zip_code string options(description="the zip code is the 5 digit location identifier associated with the address for a person or organization.  the zip code of an address generally designates a postal area or region.")
, facility_phone_num string options(description="the phone number of the facility.")
, facility_union_code string options(description="the 5 character union code that represents the employee union.")
, employee_34_login_code string options(description="the user id field will be populated from the actual system user id code when the user adds, changes, or deletes a record.")
, employee_full_name string options(description="it defines employee first name")
, ethnic_origin_code string options(description="it defines employee ethnic origin code")
, ethnic_class_desc string options(description="the ethnicity description of the employee.")
, gender_code string options(description="unique gender code of an employee maintains in this field. f = female m = male ")
, pay_grade_code string options(description="pay grade of an position")
, benefit_salary_amt numeric options(description="the user-defined benefit salary data.")
, anniversary_date date options(description="contains employees anniversary date of employment")
, termination_date date options(description="date on which employee is terminated from an hr company")
, hire_date date options(description="employee hired date captured in this table")
, birth_date date options(description="it defines employees day, month and year on which he/she is born.")
, facility_date date options(description="the date the employee was first hired to a facility.")
, job_experience_date date options(description="the date the employee was first in a similar job.")
, executive_development_program_code string options(description="the development program the executive is in.")
, executive_development_program_ind string options(description="indicates if the executive is in an development program.")
, position_code string options(description="this represents the user defined codes that represents a position in the hr company.")
, position_code_desc string options(description="description of an position code of an hr company")
, position_num int64 options(description="this represents the user defined codes that represents a position in the hr company.")
, job_code string options(description="unique job code of an hr company.")
, dept_code string options(description="unique department code of an hr company")
, dept_name string options(description="this value is the name of an department code")
, process_level_name string options(description="unique name of an hr company facility or process level. this field is spaces name for hr companyrecords")
, process_level_code string options(description="unique process level code of an hr company value mainatined in this field.")
, source_system_code string not null options(description="a one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time datetime not null options(description="datetime of update or load of this record to the enterprise data warehouse.")
)
 cluster by employee_sid, reporting_period
options(description="this table contains the details of executive level employees defined on process level and status code. this table is refreshed monthly and used in tableau reporting.");
