CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.bi_psat_question_level_score_smry (
qtr_id INT64 NOT NULL OPTIONS(description="This is the quarter identifier")
, corporate_code STRING NOT NULL OPTIONS(description="This is the code used to identify the Corporate Office or Company level of the Coid.")
, group_code STRING NOT NULL OPTIONS(description="This is the code used to identify the Group level of the Coid.")
, division_code STRING NOT NULL OPTIONS(description="This is the code used to identify the Division level of the Coid.")
, market_code STRING NOT NULL OPTIONS(description="This is the code used to identify the Market level of the Coid.")
, company_code STRING NOT NULL OPTIONS(description="Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.")
, coid STRING NOT NULL OPTIONS(description="The company identifier which uniquely identifies a facility to corporate and all other facilities.")
, vendor_assigned_unit_text STRING NOT NULL OPTIONS(description="Location unit assigned by the vendor that appears on Centers for Medicare and Medicaid Services website. Not sure of how this is assigned.")
, question_id STRING NOT NULL OPTIONS(description="This is the identifier for the question.")
, qtr_desc_dss STRING OPTIONS(description="Gives the description of the quarter")
, corporate_type_code STRING OPTIONS(description="The type code is the letter level associated with Corporate.")
, corporate_name STRING OPTIONS(description="This is the name assigned in DMR/Company Master for the Corporate.")
, group_type_code STRING OPTIONS(description="The type code is the letter level associated with the Group.")
, group_name STRING OPTIONS(description="This is the name assigned in DMR/Company Master for the Group.")
, division_type_code STRING OPTIONS(description="The type code is the letter level associated with the Division.")
, division_name STRING OPTIONS(description="This is the name assigned in DMR/Company Master for the Division.")
, market_type_code STRING OPTIONS(description="The type code is the letter level associated with the Market.")
, market_name STRING OPTIONS(description="This is the name assigned in DMR/Company Master for the Market.")
, coid_type_code STRING OPTIONS(description="The type code is the letter level associated with the Coid.  In the EDW, the Coid is assigned as the 'Z' Level.")
, coid_name STRING OPTIONS(description="This is the name assigned in DMR/Company Master for the Coid.")
, org_level_code STRING OPTIONS(description="Determines the level of the organization at which the top box scores are aggregated")
, survey_category_code STRING NOT NULL OPTIONS(description="Is the Category Code for the survey. Category number, code and category text define a unique Survey,")
, domain_id INT64 OPTIONS(description="This is the domain identifier assigned by the vendor.")
, domain_desc STRING OPTIONS(description="Description for the domain.")
, measure_id_text STRING OPTIONS(description="This is a grouping for some of the questions; This is a static list maintained by the CSG.")
, question_short_name STRING OPTIONS(description="This defines a short description for the survey question.")
, question_desc STRING OPTIONS(description="It captures description of a survey question")
, aggregated_top_box_score_num INT64 OPTIONS(description="This gives the top box score for the surveys")
, survey_response_cnt INT64 OPTIONS(description="Count of responses ")
, respondent_cnt INT64 OPTIONS(description="Count of respondents.")
, top_box_pct NUMERIC(11,4) OPTIONS(description="Top box percent value for the survey score")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
 CLUSTER BY Qtr_Id, Corporate_Code, Group_Code, Division_Code
OPTIONS(description="This table stores the aggregate top box scores at the question level at different levels of the organization.");
