CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.candidate_background_check
(
report_sid INT64 NOT NULL OPTIONS(description="Unique identifier for each background check report.")
, valid_from_date DATETIME NOT NULL OPTIONS(description="Date on which the record became valid. Load date typically.")
, report_create_date_time DATETIME OPTIONS(description="Date the background check was requested from HR Answers.")
, candidate_first_name STRING OPTIONS(description="First name of the applicant.")
, candidate_middle_name STRING OPTIONS(description="Middle name of the applicant.")
, candidate_last_name STRING OPTIONS(description="Last name of the applicant.")
, social_security_num STRING OPTIONS(description="Domain to mask the Social Security Number during the Security View generation.")
, report_completion_date_time DATETIME OPTIONS(description="Date the background check is complete.")
, report_reopen_date_time DATETIME OPTIONS(description="If the vendor needs to reopen the background check, that date is stored here.")
, process_level_code STRING OPTIONS(description="Unique process level code of an HR company value mainatined in this field.")
, recruitment_requisition_num_text STRING OPTIONS(description="A unique value coming from the source that combines the location code and lawson requisition number.")
, days_elapsed_cnt INT64 OPTIONS(description="Number of days the background investigation has been open.")
, criminal_search_ordered_cnt INT64 OPTIONS(description="Count of how many criminal searches were ordered.")
, criminal_search_pending_cnt INT64 OPTIONS(description="Count of how many criminal searches are still pending.")
, motor_vehicle_record_ordered_cnt INT64 OPTIONS(description="Count of how many motor vehicle records checks were ordered")
, motor_vehicle_record_pending_cnt INT64 OPTIONS(description="Count of how many motor vehicle records checks are still pending.")
, employment_verification_ordered_cnt INT64 OPTIONS(description="Count of how many employment verifications were ordered.")
, employment_verification_pending_cnt INT64 OPTIONS(description="Count of how many employment verifications are still pending.")
, education_verification_ordered_cnt INT64 OPTIONS(description="Count of how many education verifications were ordered.")
, education_verification_pending_cnt INT64 OPTIONS(description="Count of how many education verifications are still pending.")
, license_verification_ordered_cnt INT64 OPTIONS(description="Count of how many license verifications were ordered.")
, license_verification_pending_cnt INT64 OPTIONS(description="Count of how many license verifications are still pending.")
, personal_reference_ordered_cnt INT64 OPTIONS(description="Count of how many personal references were ordered.")
, personal_reference_pending_cnt INT64 OPTIONS(description="Count of how many person references are still pending.")
, sanction_check_ordered_cnt INT64 OPTIONS(description="Count of how many sanction checks were ordered.")
, sanction_check_pending_cnt INT64 OPTIONS(description="Count of how many sanction checks are still pending.")
, report_num INT64 NOT NULL OPTIONS(description="Report number generated from the vendor.")
, valid_to_date DATETIME NOT NULL OPTIONS(description="Date on which the record was invalidated.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY report_sid
OPTIONS(description="Contains the different background checks ordered for each candidate.");