CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.candidate_pathway_microstep_snapshot (
candidate_profile_sid INT64 NOT NULL OPTIONS(description="A unique identifier for each candidate profile.")
, pathway_id INT64 NOT NULL OPTIONS(description="Unique pathway sequence number generated by ETL")
, microstep_num INT64 NOT NULL OPTIONS(description="Unique microstep number for microstep reporting")
, snapshot_date DATE NOT NULL OPTIONS(description="Date the snapshot was taken.")
, microstep_start_date_time DATETIME OPTIONS(description="Date the microstep started. The business will use this to determine if this step meets its SLA.")
, microstep_end_date_time DATETIME OPTIONS(description="Date the microstep ended. The business will use this to determine if this step meets its SLA.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY Candidate_Profile_SID, Pathway_Id, Microstep_Num, Snapshot_Date
OPTIONS(description="This table assigns each onboarding candidate to a pathway and its associated microsteps.");
