CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.employee_performance_detail
(
  employee_performance_sid INT64 NOT NULL OPTIONS(description="A unique identifier for each "),
  valid_from_date DATETIME NOT NULL OPTIONS(description="Start date of the record"),
  employee_talent_profile_sid INT64 OPTIONS(description="Unique numeric number generated for unique combination of Employee Identifier and HR Company Identifier"),
  employee_sid INT64 OPTIONS(description="Unique numeric number generated for unique combination of Employee Identifier and HR Company Identifier"),
  review_period_id INT64 OPTIONS(description="Period for which the review was executed"),
  review_year_num INT64 OPTIONS(description="Year associated with the review period"),
  review_period_start_date DATE OPTIONS(description="Employee review period start date"),
  review_period_end_date DATE OPTIONS(description="End date of the review period"),
  performance_plan_id INT64 OPTIONS(description="Displays the name of the performance management plan"),
  evaluation_workflow_status_id INT64 OPTIONS(description="Indicates the current state of the evaluation workflow process for the employee"),
  manager_full_name STRING OPTIONS(description="Name of the employees manager at the time of the review"),
  manager_employee_num INT64 OPTIONS(description="Employee ID of the employees manager at the time of the review"),
  employee_performance_num INT64 OPTIONS(description="The employees self performance rating expressed as a value on the rating scale used"),
  employee_performance_rating_id INT64 OPTIONS(description="The employees self performance rating converted to a numeric value"),
  performance_rating_num INT64 OPTIONS(description="Displays the managers overall rating as a rating scale value"),
  performance_rating_id INT64 OPTIONS(description="Displays the managers overall rating as a numeric value"),
  employee_smry_competency_num NUMERIC OPTIONS(description="A summary of the employees competency self ratings expressed as a value on the rating scale used"),
  employee_smry_competency_rating_id INT64 OPTIONS(description="A summary of the employees competency self ratings converted to a numeric scale"),
  smry_competency_num NUMERIC OPTIONS(description="Displays the managers average competency rating as a rating scale value"),
  smry_competency_rating_id INT64 OPTIONS(description="Displays the managers average competency rating as a numeric value"),
  employee_smry_goal_num NUMERIC OPTIONS(description="A summary of the employees goal ratings expressed as a value on the rating scale used"),
  employee_smry_goal_rating_id INT64 OPTIONS(description="A summary of the employees goal self ratings converted to numeric value"),
  smry_goal_num NUMERIC OPTIONS(description="Displays the managers weighted average goal rating as a scale value"),
  smry_goal_rating_id INT64 OPTIONS(description="Displays the managers weighted average goal rating as a numeric value"),
  employee_strength_accomplishment_text STRING OPTIONS(description="Notes entered as strengths and accomplishments by the employee on the evaluation form"),
  employee_area_of_improvement_text STRING OPTIONS(description="Notes entered as areas of improvement by the employee on the evaluation form"),
  employee_additional_comment_text STRING OPTIONS(description="Notes entered as additional comments by the employee on the evaluation form"),
  strength_accomplishment_text STRING OPTIONS(description="Displays notes regarding the employees strengths and accomplishments by the manager"),
  areas_of_improvement_text STRING OPTIONS(description="Displays notes regarding the employees areas of improvement by the manager"),
  additional_comment_text STRING OPTIONS(description="Displays additional comments regarding the employee by the manager"),
  employee_num INT64 OPTIONS(description="This is an lawson employee number"),
  lawson_company_num INT64 OPTIONS(description="The number that identifies a company.A company represents a business or legal entity of an organization"),
  process_level_code STRING OPTIONS(description="Unique process level code of an HR company value mainatined in this field."),
  source_system_key STRING OPTIONS(description="A unique record identifier from the source."),
  valid_to_date DATETIME OPTIONS(description="End date of the record"),
  source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY employee_talent_profile_sid
OPTIONS(description="Employee annual performance rating and performance score mainatined in this table");