CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.employee_person (
employee_sid INT64 NOT NULL OPTIONS(description="Unique ETL Generated Number for an HCA Employee Number")
, valid_from_date DATETIME NOT NULL OPTIONS(description="Date on which the record became valid. Load date typically.")
, valid_to_date DATETIME OPTIONS(description="Date on which the record was invalidated.")
, hr_company_sid INT64 OPTIONS(description="It is the unique ETL sequence number generated for HR lawson legal company code.")
, home_phone_country_code STRING OPTIONS(description="It captures internation dialing country code in this field")
, employee_sector_code STRING OPTIONS(description="It describes employee as either  FLD or CORP")
, employee_num INT64 NOT NULL OPTIONS(description="It defines employee number")
, employee_ssn STRING OPTIONS(description="Domain to mask the Social Security Number during the Security View generation.")
, lawson_company_num INT64 NOT NULL OPTIONS(description="Unique four digit numeric value of Lawson generated HR Company maintained in this field")
, employee_first_name STRING OPTIONS(description="It defines employee first name")
, employee_last_name STRING OPTIONS(description="It captures employees last name")
, employee_middle_name STRING OPTIONS(description="It defines middle name of the employee")
, employee_home_phone_num STRING OPTIONS(description="It defines employess active phone number on which employee is reachable")
, employee_work_phone_num STRING OPTIONS(description="It defines employees active work phone number.")
, ethnic_origin_code STRING OPTIONS(description="It defines employee ethnic origin code")
, gender_code STRING OPTIONS(description="Unique Gender code of an employee maintains in this field. F = Female M = Male")
, birth_date DATE OPTIONS(description="It defines employees day, month and year on which he/she is born.")
, email_text STRING OPTIONS(description="Email address of an employee")
, veteran_ind STRING OPTIONS(description="Indicates if the employee is considered a Veteran.")
, disability_ind STRING OPTIONS(description="Indicates if the employee is disabled.")
, benefit_salary_amt NUMERIC(11,2) OPTIONS(description="The user-defined benefit salary data.")
, badge_code STRING OPTIONS(description="Contains employee badge number or if it has been inactivated due to suspension.")
, process_level_code STRING NOT NULL OPTIONS(description="Unique process level code of an HR company value mainatined in this field.")
, delete_ind STRING OPTIONS(description="The indicator is usually a Y/ N (yes/no) designation of a record but can sometimes be other values.  This should not be 1/0 designation.")
, active_dw_ind STRING OPTIONS(description="Y/N character to indicate this record as active in the EDW.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
PARTITION BY DATE(valid_from_date)
CLUSTER BY employee_sid
OPTIONS(description="Contains all employee information needed in the Lawson Payroll system. The Employee information used by the Lawson Human Resource, Personnel.");
