create table if not exists {{ params.param_hr_core_dataset_name }}.employee_disciplinary_action (
employee_sid int64 not null options(description="unique numeric number generated for unique combination of employee identifier and hr company identifier")
, disciplinary_ind string not null options(description="indicates whether the action is a grievance (1) or disciplinary (2) issue.")
, disciplinary_action_num int64 not null options(description="contains the grievance or disciplinary action number.")
, valid_from_date datetime not null options(description="date on which the record became valid. load date typically.")
, valid_to_date datetime options(description="date on which the record was invalidated.")
, disciplinary_desc string options(description="contains the grievance or disciplinary  description.")
, creation_date date options(description="contains the date the grievance or disciplinary action was created")
, action_category_code string options(description="contains the user defined grievance or disciplinary action category name.")
, report_date date options(description="contains the date the grievance or disciplinary action was reported")
, reported_by_employee_num int64 options(description="contains the number of the employee who reported the action")
, reported_by_name string options(description="contains the name of the employee who reported the action")
, action_status_code string options(description="contains the user defined grievance or  disciplinary action status.")
, action_outcome_desc string options(description="contains the user defined  grievance or disciplinary action outcome description")
, action_outcome_date date options(description="contains the date of the grievance or  disciplinary action outcome")
, days_out_cnt int64 options(description="contains the count of days the employee is away from work due to the  grievance or disciplinary action")
, department_sid int64 options(description="contains the department sid where the grievance or disciplinary action occurred")
, location_code string options(description="contains the location where the grievance or disciplinary action occurred")
, job_code_sid int64 options(description="contains the employee job code sid when the grievance or disciplinary action occurred")
, comment_desc string options(description="this field contains the comment narrative.")
, supervisor_employee_num int64 options(description="contains the supervisor number of the employee with the disciplinary action.")
, last_update_date date options(description="last date a record was updated in lawson.")
, last_update_user_34_login_code string options(description="user that made last update to record.")
, employee_num int64 not null options(description="employee number from lawson unique to each employee.")
, lawson_company_num int64 not null options(description="unique four digit numeric value of lawson generated hr company maintained in this field")
, process_level_code string not null options(description="unique process level code of an hr company value maintained in this field.")
, source_system_code string not null options(description="a one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time datetime not null options(description="datetime of update or load of this record to the enterprise data warehouse.")
)
 cluster by employee_sid
options(description="this table contains grievance and disciplinary action information of employee.");
