create table if not exists `{{ params.param_hr_core_dataset_name }}.employee_action_detail`
(
  employee_action_sid INT64 NOT NULL OPTIONS(description=" etl generated unique identifier for an combination of fields action code, company employee identifier, action sequence number & action effective date"),
  eff_from_date DATE NOT NULL OPTIONS(description=" date on which record is initiated"),
  valid_from_date DATETIME NOT NULL OPTIONS(description=" date on which the record became valid. load date typically."),
  valid_to_date DATETIME OPTIONS(description=" date on which the record was invalidated."),
  action_code STRING NOT NULL OPTIONS(description=" unique code value of an action"),
  employee_sid INT64 NOT NULL OPTIONS(description=" unique id generated for combination of employee and hr company code"),
  employee_num INT64 OPTIONS(description=" the lawson identifier for an employee when combined with company."),
  action_sequence_num INT64 NOT NULL OPTIONS(description=" sequence number to identify multiple steps of an action"),
  action_from_date DATE NOT NULL OPTIONS(description=" date on which action is active on employee"),
  action_to_date DATE OPTIONS(description=" date on which action will be completed on an employee"),
  from_auxiliary_status_code STRING OPTIONS(description=" this field maintains auxiliary status code assigned to an employee before execution of action"),
  from_dept_code STRING OPTIONS(description=" this field maintains department code assigned to an employee before execution of action"),
  from_employee_pay_rate_amount NUMERIC OPTIONS(description=" this field maintains pay rate amount assigned to an employee before execution of action"),
  from_employee_work_schedule_code STRING OPTIONS(description=" this field maintains work schedule code assigned to an employee before execution of action"),
  from_job_code STRING OPTIONS(description=" maintains employee job code value"),
  from_location_code STRING OPTIONS(description=" employee working location code value"),
  from_overtime_plan_code STRING OPTIONS(description=" employee overtime plan code value"),
  from_position_code STRING OPTIONS(description=" this field maintains position code assigned to an employee before execution of action"),
  from_position_level_num INT64 OPTIONS(description=" this field maintains position level number assigned to an employee before execution of action"),
  from_process_level_code STRING OPTIONS(description=" employee process level value"),
  from_payment_frequency NUMERIC OPTIONS(description=" employee payment frequency value"),
  from_payment_grade_code STRING OPTIONS(description=" employee payment grade code value"),
  from_payment_step_num NUMERIC OPTIONS(description=" employee payment step number value"),
  from_salary_class_code STRING OPTIONS(description=" employee salary class code value"),
  from_schedule_code STRING OPTIONS(description=" employee pay grade or pay grade and step schedule"),
  from_standard_hour NUMERIC OPTIONS(description=" employee standard working hours for salart payment"),
  from_supervisor_code STRING OPTIONS(description=" employee supervisor code value"),
  from_union_code STRING OPTIONS(description=" employee union code value"),
  from_user_level STRING OPTIONS(description=" employee user level value"),
  from_excemption_flag STRING OPTIONS(description=" employee exemption flag value"),
  from_expense_account_unit STRING OPTIONS(description=" expense account unit code"),
  from_expense_company INT64 OPTIONS(description=" expense hr company code"),
  from_expense_sub_account_num INT64 OPTIONS(description=" expense sub account number"),
  hr_code_desc STRING OPTIONS(description=" this field maintains description of hr code."),
  last_update_date DATE NOT NULL OPTIONS(description=" employee action last updated date"),
  last_transfer_eff_date DATE OPTIONS(description=" employee last transfer date"),
  reason_desc STRING OPTIONS(description=" description of an action"),
  to_payment_frequency NUMERIC OPTIONS(description=" employee changed payment frequency value"),
  to_auxiliary_status_code STRING OPTIONS(description=" auxiliary status code to which employee transferred."),
  to_dept_code STRING OPTIONS(description=" employee transferred to department code value"),
  to_employee_pay_rate_amt NUMERIC OPTIONS(description=" this field maintains employee new pay rate amount."),
  to_employee_schedule_code STRING OPTIONS(description=" this field maintains pay schedule code assigned to an employee after execution of action"),
  to_job_code STRING OPTIONS(description=" this field maintains job code assigned to an employee after execution of action"),
  to_location_code STRING OPTIONS(description=" new location code of an employee"),
  to_overtime_plan_code STRING OPTIONS(description=" new overtime plan code of an employee."),
  to_position_code STRING OPTIONS(description=" new position code of an employee"),
  to_position_level_num INT64 OPTIONS(description=" new position level number of an employee"),
  to_process_level_code STRING OPTIONS(description=" this field maintains process level code assigned to an employee after execution of action"),
  to_pay_grade_code STRING OPTIONS(description=" this field maintains pay grade code assigned to an employee after execution of action"),
  to_pay_step_num NUMERIC OPTIONS(description=" this field maintains pay step number assigned to an employee after execution of action"),
  to_salary_class_code STRING OPTIONS(description=" this field maintains salary class code assigned to an employee after execution of action"),
  to_schedule_code STRING OPTIONS(description=" this field maintains schedulel code assigned to an employee after execution of action"),
  to_standard_hour NUMERIC OPTIONS(description=" this field maintains standard hour assigned to an employee after execution of action"),
  to_supervisor_code STRING OPTIONS(description=" this field maintains supervisor code assigned to an employee after execution of action"),
  to_union_code STRING OPTIONS(description=" this field maintains union code assigned to an employee after execution of action"),
  to_user_level STRING OPTIONS(description=" this field maintains user  level code assigned to an employee after execution of action"),
  to_exemption_flag STRING OPTIONS(description=" this field maintains execution flag assigned to an employee after execution of action"),
  to_expense_account_unit STRING OPTIONS(description=" expense account changed unit code value"),
  to_expense_sub_account_num INT64 OPTIONS(description=" expense sub account number changed value"),
  transfer_termination_flag STRING OPTIONS(description=" this flag identifies whether employee action is related to transfer or termination."),
  to_expense_company_num INT64 OPTIONS(description=" this field maintains expense company number assigned to an employee after execution of action"),
  active_dw_ind STRING OPTIONS(description=" y/n character to indicate this record as active in the edw."),
  lawson_company_num INT64 NOT NULL OPTIONS(description=" the number that identifies a company.a company represents a business or legal entity of an organization"),
  process_level_code STRING NOT NULL OPTIONS(description=" unique process level code of an hr company value mainatined in this field."),
  security_key_text STRING NOT NULL OPTIONS(description=" it is the key which has concatenation of lawson company code - process level code -department code for data access feature prospective."),
  delete_ind STRING OPTIONS(description=" the indicator is usually a y/ n (yes/no) designation of a record but can sometimes be other values.  this should not be 1/0 designation."),
  source_system_code STRING NOT NULL OPTIONS(description=" a one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description=" datetime of update or load of this record to the enterprise data warehouse.")
)
PARTITION BY DATE(valid_to_date)
CLUSTER BY employee_action_sid, valid_from_date
OPTIONS(
  description="This is the derived table to identify transfer, Add position. Stop Position, Termination pending, Termination completed status of each individual action. It provides pre and post action changes in employee for an HR company."
);