create table if not exists `{{ params.param_hr_core_dataset_name }}.employee_pay_hour_history`
(
  employee_sid INT64 NOT NULL OPTIONS(description="unique numeric number generated for unique combination of employee identifier and hr company identifier"),
  check_id NUMERIC NOT NULL OPTIONS(description="the payment identification number (unique payment identifier used in tracking payment information)."),
  pay_summary_group_code STRING NOT NULL OPTIONS(description="code that groups pay codes together."),
  time_seq_id NUMERIC NOT NULL OPTIONS(description="the sequence number associated with the time record."),
  valid_from_date DATETIME NOT NULL OPTIONS(description="date on which the record became valid. load date typically."),
  valid_to_date DATETIME OPTIONS(description="date on which the record was invalidated."),
  employee_num INT64 NOT NULL OPTIONS(description="it defines employee number"),
  work_hour_amt NUMERIC OPTIONS(description="the number of hours associated with the time record for the employee."),
  hourly_rate_amt NUMERIC OPTIONS(description="the rate assocaited with the time record for the employee."),
  wage_amt NUMERIC OPTIONS(description="the wage amount associated with the time record for the employee."),
  transaction_date DATE OPTIONS(description="the transaction date for the time record."),
  dept_sid INT64 OPTIONS(description="unique etl generated numeric number for each department code of process level code associated with an hr company code."),
  payroll_year_num INT64 OPTIONS(description="contains the payroll year associated with the time record."),
  home_process_level_code STRING OPTIONS(description="process level code associated with the main position of the employee."),
  gl_account_num STRING OPTIONS(description="contains the general ledger account to which the amount is posted."),
  gl_sub_account_num STRING OPTIONS(description="contains the general ledger subaccount to which the amount is posted."),
  gl_company_num INT64 OPTIONS(description="this is the hr company number generated by lawson system to assign it to legal company."),
  account_unit_num STRING OPTIONS(description="it is the home accounting unit code of a hr company."),
  pay_period_end_date DATE OPTIONS(description="contains the period end date associated with the time record."),
  lawson_company_num INT64 NOT NULL OPTIONS(description="unique four digit numeric value of lawson generated hr company maintained in this field"),
  process_level_code STRING NOT NULL OPTIONS(description="unique process level code of an hr company value maintained in this field."),
  delete_ind STRING OPTIONS(description="the indicator is usually a y/ n (yes/no) designation of a record but can sometimes be other values.  this should not be 1/0 designation."),
  active_dw_ind STRING OPTIONS(description="y/n character to indicate this record as active in the edw."),
  source_system_code STRING NOT NULL OPTIONS(description="a one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="datetime of update or load of this record to the enterprise data warehouse.")
)
PARTITION BY DATE(valid_from_date)
CLUSTER BY employee_sid, check_id, pay_summary_group_code, time_seq_id
OPTIONS(
  description="contains the detail pay hours for each employee."
);