create table if not exists `{{ params.param_hr_core_dataset_name }}.fact_hr_metric`
(
  employee_sid INT64 NOT NULL OPTIONS(description="Unique numeric number generated for unique combination of Employee Identifier and HR Company Identifier"),
  requisition_sid INT64 NOT NULL OPTIONS(description="Unique id of an lawson generated requisition."),
  position_sid INT64 NOT NULL OPTIONS(description="Unique ETL generated sequence number for each user defined codes that represents a position in the HR company."),
  date_id DATE NOT NULL OPTIONS(description="The month the metric was calculated for the given dimensions."),
  analytics_msr_sid INT64 NOT NULL OPTIONS(description="This is the system assigned number to uniquely identfiy a row in the hierarchy."),
  dept_sid INT64 OPTIONS(description="Unique ETL Generated Numeric number for each department code of Process level code associated with an HR Company Code."),
  job_class_sid INT64 OPTIONS(description="Description of an Job Class code of HR Company"),
  job_code_sid INT64 OPTIONS(description="Unique Job code of an HR Company."),
  location_code STRING OPTIONS(description="Unique list of location codes are maintained in this table. Location codes are mainatined for Employee working location and also for Process level location."),
  coid STRING OPTIONS(description="The company identifier which uniquely identifies a facility to corporate and all other facilities."),
  company_code STRING OPTIONS(description="Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes"),
  functional_dept_num STRING OPTIONS(description="The number assigned in QMIRS for the input of departmental rollups."),
  sub_functional_dept_num STRING OPTIONS(description="Rollup of an account number under a specific department performed by the QMIRS source system."),
  auxiliary_status_sid INT64 OPTIONS(description="Denotes whether an employee is FT, PT, PRN, or Temp."),
  employee_status_sid INT64 OPTIONS(description="Denotes whether an employee is active, on LOA, termed, etc."),
  key_talent_id INT64 OPTIONS(description="It is the unique sequence number generated by ETL for each Job code and Facility level combination"),
  integrated_lob_id INT64 OPTIONS(description="This field captures ETL generated unique sequence number for each LOB description"),
  action_code STRING OPTIONS(description="Unique list of action code associated with the personnel action are maintained in this field."),
  action_reason_text STRING OPTIONS(description="Reason description of an Action taken on Employee"),
  lawson_company_num INT64 NOT NULL OPTIONS(description="The number that identifies a company.A company represents a business or legal entity of an organization"),
  process_level_code STRING NOT NULL OPTIONS(description="Unique process level code of an HR company value mainatined in this field."),
  work_schedule_code STRING OPTIONS(description="Code that describes the weekly schedule of the requisition."),
  recruiter_owner_user_sid INT64 OPTIONS(description="A link to Recruitment_User to identify who is the owner of the requisition."),
  requisition_approval_date DATE OPTIONS(description="The date that a requisition receives its final approval."),
  employee_num INT64 OPTIONS(description="This is an lawson employee number"),
  metric_numerator_qty NUMERIC OPTIONS(description="This is the metric value that has met the target for the measure."),
  metric_denominator_qty NUMERIC OPTIONS(description="This is the total population against which the metric is being tracked."),
  source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY employee_sid, requisition_sid, position_sid, date_id
OPTIONS(
  description="Contains facts used for HR reporting from source systems including Lawson, HRA, Finance, Performance Improvement."
);