create table if not exists `{{ params.param_hr_core_dataset_name }}.fact_submission`
(
  submission_sid INT64 NOT NULL OPTIONS(description="A unique identifier for each submission "),
  candidate_profile_num NUMERIC OPTIONS(description="A unique identifier for each candidate profile from the source."),
  candidate_num INT64 OPTIONS(description="The unique number for a candidate coming from the source."),
  candidate_profile_sid INT64 OPTIONS(description="A unique identifier for each candidate profile."),
  candidate_sid INT64 OPTIONS(description="Unique identifier for each candidate."),
  submission_uid STRING OPTIONS(description="A combination of Coid and the cost center dept_sid or dept_code."),
  dept_sid INT64 OPTIONS(description="Unique ETL Generated Numeric number for each department code of Process level code associated with an HR Company Code."),
  company_code STRING OPTIONS(description="Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes."),
  coid STRING OPTIONS(description="The company identifier which uniquely identifies a facility to corporate and all other facilities."),
  coid_dept_uid STRING OPTIONS(description="A combination of the dept_sid for the cost center and the coid"),
  creation_date DATE OPTIONS(description="Date the submission profile was created by the candidate."),
  creation_date_time DATETIME OPTIONS(description="Date time the submission profile was created by the candidate."),
  completion_date DATE OPTIONS(description="Date the submission profile was completed by the candidate."),
  completion_date_time DATETIME OPTIONS(description="Date time the submission profile was completed by the candidate."),
  recruitment_source_desc STRING OPTIONS(description="A description of the recruiting source. Ex. internet, job board, etc."),
  recruitment_source_type_desc STRING OPTIONS(description="A description of the recruiting source type."),
  recruitment_source_auto_filled_sw INT64 OPTIONS(description="Numeric boolean to where 0 = false/no and 1 = true/yes"),
  profile_medium_desc STRING OPTIONS(description="A description of the medium in which a profile was submitted to HCA."),
  recruitment_requisition_num_text STRING OPTIONS(description="A unique value coming from the source that combines the location code and Lawson requisition number."),
  recruitment_requisition_sid INT64 OPTIONS(description="A unique identifier for each requisition coming from the recruitment system."),
  lawson_requisition_num INT64 OPTIONS(description="A unique identifier for the Lawson requisition from Lawson."),
  ghr_requisition_num INT64 OPTIONS(description="The requisition_num for GHR records"),
  matched_from_requisition_num INT64 OPTIONS(description="Contains the requisition number that a candidate originally applied to as recruiters can sometimes move applications to other requisitions."),
  requisition_sid INT64 OPTIONS(description="Unique Id of an Lawson generated requisition."),
  status_code STRING OPTIONS(description="This represents the available code values for the status of the employee or applicant. "),
  first_offer_start_date DATE OPTIONS(description="This is the offer start date from the earliest valid record in the offer table."),
  open_fte_percent NUMERIC OPTIONS(description="FTE percent of opened requisition"),
  job_schedule_desc STRING OPTIONS(description="The description for the schedule of a job."),
  paid_source_flag STRING OPTIONS(description="An indicator that describes if the source of the submission was from a paid service."),
  last_modified_date DATE OPTIONS(description="Date the submission was last modified."),
  submission_status_name STRING OPTIONS(description="A name for each status of the submission process."),
  current_submission_step_name STRING OPTIONS(description="The spelled out name of the step within the submission process"),
  quality_flag STRING OPTIONS(description="If the Step Name is not New, New Applicant, or HR Reviews, then Yes. Everything else will be a No."),
  motive_name STRING OPTIONS(description="A name for each motive an event can have in the submission process."),
  new_grad_flag STRING OPTIONS(description="Y if the candidate is a registered nurse recent graduate."),
  gender_name STRING OPTIONS(description="Gender of the candidate spelled out"),
  ethnicity_name STRING OPTIONS(description="Ethnicity of the candidate as specified in the application process."),
  veteran_desc STRING OPTIONS(description="Describes whether the candidate is a veteran, and if so, what kind."),
  veteran_spouse_flag STRING OPTIONS(description="Indicates if their spouse is an active duty member of the military or not."),
  disability_flag STRING OPTIONS(description="Indicates whether the candidate has a disability of some kind or not."),
  hrr_duration_cnt INT64 OPTIONS(description="The number of days for HR to review submission"),
  hmr_duration_cnt INT64 OPTIONS(description="Total number of days for hiring manager to review submission"),
  interview_duration_cnt INT64 OPTIONS(description="Total number of days for interview process"),
  offer_duration_cnt INT64 OPTIONS(description="Total number of days to receive the offer"),
  matched_candidate_flag STRING OPTIONS(description="Indicates whether a candidate is a match"),
  candidate_intl_ext_flag STRING OPTIONS(description="Indicates whether the candidate is internal or external or unknown"),
  source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY submission_sid
OPTIONS(
  description="Contains all the information specific to a single application submitted by a candidate.  Candidates can have multiple submissions, but each row on this table should provide the details about one only one of them."
);