create table if not exists `{{ params.param_hr_core_dataset_name }}.gl_lawson_dept_crosswalk`
(
  gl_company_num INT64 NOT NULL OPTIONS(description="this is the hr company number generated by lawson system to assign it to legal company."),
  account_unit_num STRING NOT NULL OPTIONS(description="it is the home accounting unit code of a hr company"),
  process_level_code STRING NOT NULL OPTIONS(description="this field maintains process level code of an hr company number."),
  valid_from_date DATETIME NOT NULL OPTIONS(description="date on which the record became valid. load date typically."),
  valid_to_date DATETIME OPTIONS(description="date on which the record was invalidated."),
  coid STRING NOT NULL OPTIONS(description="the company identifier which uniquely identifies a facility to corporate and all other facilities."),
  unit_num STRING NOT NULL OPTIONS(description="this field maintains unit number of an hr company"),
  dept_num STRING NOT NULL OPTIONS(description="it is the hca department number of an company"),
  lawson_company_num INT64 NOT NULL OPTIONS(description="this is the legal lawson hr company number."),
  security_key_text STRING NOT NULL OPTIONS(description="this is the security key generated based on combination of hr company num, process level code and hr department code. security mechanism will be implemented using security key."),
  company_code STRING OPTIONS(description="this field maintains company code of an lawson company num"),
  source_system_code STRING NOT NULL OPTIONS(description="a one character code indicating the specific source system from which the data originated."),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="datetime of update or load of this record to the enterprise data warehouse.")
)
PARTITION BY DATE(valid_from_date)
CLUSTER BY gl_company_num, account_unit_num, process_level_code
OPTIONS(
  description="this crosswalk table is maintained in lawson system to identify unit code on gl company, process level and gl department number level"
);