CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.hr_workunit_action_queue (
workunit_sid NUMERIC(18,0) NOT NULL OPTIONS(description="Unique identifier generated of the combination of Workunit and Source_System_Code.")
, activity_seq_num INT64 NOT NULL OPTIONS(description="The activity sequence number captured by lawson for the workflow.")
, valid_from_date DATETIME NOT NULL OPTIONS(description="Date on which the record became valid. Load date typically.")
, valid_to_date DATETIME OPTIONS(description="Date on which the record was invalidated.")
, workunit_num NUMERIC(12,0) NOT NULL OPTIONS(description="Categories each activity number into a separate group to help understand the workflow.")
, work_desc STRING OPTIONS(description="Contains the work description and details.")
, action_taken_text STRING OPTIONS(description="Contains the action taken details. Ex. Approve, Deny , etc")
, display_type_num INT64 OPTIONS(description="Contains the display type number.")
, display_name STRING OPTIONS(description="Contains the display name.")
, filter_key_text STRING OPTIONS(description="Contains the filter key text.")
, filter_value_num_text STRING OPTIONS(description="Contains the filter value.")
, time_out_type_num INT64 OPTIONS(description="Contains the Time Out type number.")
, time_out_hour_num INT64 OPTIONS(description="Contains the Time Out number of hours.")
, time_out_action_text STRING OPTIONS(description="Contains the Time Out Action details.")
, timed_out_sw INT64 OPTIONS(description="Indicates whether or not the action has timed out. Numeric boolean to where 0 = false/no and 1 = true/yes")
, last_queue_action_num INT64 OPTIONS(description="Contains the last queue action number.")
, configurator_name STRING OPTIONS(description="Contains the configurator name.")
, lawson_company_num INT64 NOT NULL OPTIONS(description="The number that identifies a company.A company represents a business or legal entity of an organization")
, process_level_code STRING NOT NULL OPTIONS(description="Unique process level code of an HR company value maintained in this field.")
, active_dw_ind STRING NOT NULL OPTIONS(description="Y/N character to indicate this record as active in the EDW.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
PARTITION BY DATE(Valid_From_Date)
CLUSTER BY Workunit_SID, Activity_Seq_Num, Valid_From_Date
OPTIONS(description="This table contains the details on in progress user actions.");
