CREATE TABLE IF NOT EXISTS `{{ params.param_hr_core_dataset_name }}.microstep_pathway_sla`
 ( 
    pathway_id int64 NOT NULL OPTIONS(description="unique pathway identifier generated by etl"),
    microstep_num int64 NOT NULL OPTIONS(description="unique microstep number for microstep reporting"),
    sla_day_cnt int64 OPTIONS(description="service level agreement days  for each step pathway number text"),
    day_type_code string OPTIONS(description="day type like business days (b) or calendar days (c)"),
    source_system_code string NOT NULL OPTIONS(description="a one character code indicating the specific source system from which the data originated."),
    dw_last_update_date_time timestamp NOT NULL OPTIONS(description="timestamp of update or load of this record to the enterprise data warehouse.") )
CLUSTER BY
  pathway_id,
  microstep_num OPTIONS(description="this table contains pathway and micostep association, along with service level agreement day information.");