CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.patient_satisfaction_alt_org_hierarchy (
company_code STRING NOT NULL OPTIONS(description="Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes")
, coid STRING NOT NULL OPTIONS(description="The company identifier which uniquely identifies a facility to corporate and all other facilities.")
, facility_name STRING OPTIONS(description="Name of the facility that appears on the survey sent to patients. This name comes from the DRM file.")
, group_code STRING NOT NULL OPTIONS(description="Five character code for the Group in the organization structure.")
, division_code STRING NOT NULL OPTIONS(description="Five character code for the Division in the organization structure.")
, market_code STRING NOT NULL OPTIONS(description="Five character code for the Market in the organization structure.")
, parent_coid STRING NOT NULL OPTIONS(description="Five character code for the Parent coid in the organization structure.")
, parent_coid_cons_facility_code STRING NOT NULL OPTIONS(description="Five character code for the consolidated facility code in the organization structure.")
, lob_code STRING OPTIONS(description="This is the Line of business code")
, sub_lob_code STRING OPTIONS(description="Gives the sub line of business code")
, client_id INT64 OPTIONS(description="Coid of the facility prefixed with 90 except for some acquired facilities with previous vendor relationships. This is the identifier used by the third party vendor.")
, facility_claim_control_num STRING OPTIONS(description="Medicare provider claim control number.")
, facility_claim_control_num_name STRING OPTIONS(description="Name of the facility as reported to CMS.")
, facility_rollup_sw INT64 OPTIONS(description="Numeric boolean to where 0 = false/no and 1 = true/yes")
, fsed_ind STRING OPTIONS(description="Indicates if the entity is the a free standing ED")
, asd_region_name STRING OPTIONS(description="Name of the ASD region")
, location_mnemonic_cs STRING OPTIONS(description="A 10 character code to uniquely identify the dictionary or reference item within a network.  All networks are setup as with the MIS as shared dictionaries.  The mnemonic is unique at this level.")
, unit_num STRING OPTIONS(description="This field maintains unit number of an HR company")
, survey_start_date DATE OPTIONS(description="The date the survey was open to the participants. This field is maintained by the business.")
, survey_end_date DATE OPTIONS(description="The date the survey was closed to the participants. This field is maintained by the business,")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY Company_Code, Coid
OPTIONS(description="Contains alternate relationship between coid and parent coid. This information comes from DRM and is maintained by the business. This is true only for Patient satisfaction surveys.");
