CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_onboarding_workflow_status
(
workflow_status_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each workflow status")
, workflow_status_text STRING OPTIONS(description="This contains unique workflow status post tour completion")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY workflow_status_id
OPTIONS(description="This table maintains unique workflow status for candidate onboarding")
;