CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_onboarding_workflow
(
workflow_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each workflow name")
, workflow_name STRING OPTIONS(description="Unique event that occurs after tour completion")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY workflow_id
OPTIONS(description="This table maintains unique workflow name for candidate onboarding")
;