CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_email_to_hr_status
(
email_sent_status_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each  email sent status text")
, email_sent_status_text STRING OPTIONS(description="HR email sent status for candidate preboarding and verification tour")
, hr_status_desc STRING OPTIONS(description="This contains status description like, O (pre-boarding tour) and V (verification tour)")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY email_sent_status_id
OPTIONS(description="This table maintains unique status of the steps in candidate onboarding for which email was sent  to human resource.")
;