CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_pathway (
pathway_id INT64 NOT NULL OPTIONS(description="Unique pathway sequence number generated by ETL")
, pathway_num INT64 NOT NULL OPTIONS(description="It contains pathway number ")
, subpathway_code STRING OPTIONS(description="Subpathway code")
, pathway_name STRING OPTIONS(description="Unique pathway name for each pathway number and subpathway")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
)
 CLUSTER BY Pathway_Id
OPTIONS(description="This table maintains unique pathway identifier and name associated with candidates onboarding journey.");
