CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_onboarding_tour_status
(
tour_status_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each tour status")
, tour_status_text STRING OPTIONS(description="This contains the status of tour completion")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY tour_status_id
OPTIONS(description="This table maintains unique candidate onboarding tour status. ");