/*edwhr.ref_bi_key_talent*/
CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_bi_key_talent
(
  key_talent_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each Job code and Facility level combination")
, job_code STRING OPTIONS(description="This field captures Job code associated with a key group")
, facility_level_code STRING OPTIONS(description="This field maintains Facility level of a line of business code assiciated with  key talent group code")
, key_talent_group_text STRING OPTIONS(description="This field maintains key Talent group information.")
, job_title_text STRING OPTIONS(description="This field maintains Job title text associated with key talent group")
, lob_code STRING OPTIONS(description="This field maintains line of business code associated with Key talent group")
, job_code_desc STRING OPTIONS(description="This field maintains job code description")
, process_level_code STRING OPTIONS(description="This field maintains Process level code of a facility")
, match_level_num INT64 OPTIONS(description="This field maintains match level number of a key talent group")
, match_level_desc STRING OPTIONS(description="This field maintains match level desc")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY key_talent_id
OPTIONS(description="This table is the reference table for all key talent group available across all Legal HR company.");
