CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_onboarding_event_type
(
event_type_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each Event type")
, event_type_code STRING NOT NULL OPTIONS(description="This contains unique event type code for the candidate onboarding like T, D.")
, event_type_desc STRING OPTIONS(description="This contains description of event type code.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY event_type_id
OPTIONS(description="This table maintains unique event type information for candidate onboarding");