CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.ref_onboarding_tour
(
tour_id INT64 NOT NULL OPTIONS(description="It is the unique sequence number generated by ETL for each tour name")
, tour_name STRING OPTIONS(description="Contains tour name, which candidate completes for onboarding")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Datetime of update or load of this record to the Enterprise Data Warehouse.")
)
CLUSTER BY tour_id
OPTIONS(description="This table maintains unique onboarding tour name with respect to candidate onboarding");