CREATE TABLE IF NOT EXISTS {{ params.param_hr_core_dataset_name }}.survey_response
(
  survey_question_sid INT64 NOT NULL OPTIONS(description="It is the ETL generated unique sequence number for each survey question.")
, respondent_id NUMERIC NOT NULL OPTIONS(description="This is the respondent identifier that is assigned by the vendor.")
, survey_receive_date DATE NOT NULL OPTIONS(description="The date the survey was received")
, survey_mode_code STRING NOT NULL OPTIONS(description="This is how the survey was conducted, e.g Phone or mail")
, survey_response_sid INT64 NOT NULL OPTIONS(description="It is the ETL generated unique sequence number for each response to a survey question.")
, response_value_text STRING OPTIONS(description="This is the response value to a survey question")
, response_comment_text STRING OPTIONS(description="This is the comment text for open ended questions")
, survey_form_text STRING OPTIONS(description="This is the name of the survey form.")
, company_code STRING OPTIONS(description="Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.")
, coid STRING OPTIONS(description="The company identifier which uniquely identifies a facility to corporate and all other facilities.")
, patient_discharge_date DATE OPTIONS(description="Discharge date of the patient.")
, time_name_child DATE OPTIONS(description="This is the Time frame of the survey; For HCAHPS surveys this is generated bsaed on the discharge date of the patient")
, cms_submit_preliminary_ind STRING OPTIONS(description="The indicator value is generated by HCA based on the exclusion criteria. All responses not in exclusions are set to Y")
, cms_submit_ind STRING OPTIONS(description="This is the final indicator sent from the vendor and determines if the response was submited to Centers for Medicare and Medicaid services")
, adjusted_sample_ind STRING OPTIONS(description="The indicator is usually a Y/ N (yes/no) designation of a record but can sometimes be other values.  This should not be 1/0 designation.")
, top_box_score_num INT64 OPTIONS(description="This is the Topbox score for the survey question.")
, final_record_ind STRING OPTIONS(description="This indicator defines if the response record is the final record. Final data is received in Feb,May,Aug,Nov for the previous quarter data.")
, vendor_assigned_unit_text STRING OPTIONS(description="Location unit assigned by the vendor that appears on Centers for Medicare and Medicaid Services website. Not sure of how this is assigned.")
, source_system_code STRING NOT NULL OPTIONS(description="A one character code indicating the specific source system from which the data originated.")
, dw_last_update_date_time DATETIME NOT NULL OPTIONS(description="Timestamp of update or load of this record to the Enterprise Data Warehouse.")

)
CLUSTER BY survey_question_sid, respondent_id, survey_mode_code, survey_response_sid
OPTIONS(description="This table records the responses for the survey questions.");

