-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_rcom_pars_dcrp_all.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_base_views_dataset_name }}.fact_rcom_pars_dcrp_all
   OPTIONS(description='This is Monthly Discrepancy Inventory for all Customers for all Cost year hierarchies')
  AS SELECT
      fact_rcom_pars_dcrp_all.date_sid,
      ROUND(fact_rcom_pars_dcrp_all.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      ROUND(fact_rcom_pars_dcrp_all.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      fact_rcom_pars_dcrp_all.iplan_insurance_order_num,
      fact_rcom_pars_dcrp_all.log_id,
      fact_rcom_pars_dcrp_all.ar_bill_thru_date,
      fact_rcom_pars_dcrp_all.discrepancy_creation_date,
      ROUND(fact_rcom_pars_dcrp_all.patient_sid, 0, 'ROUND_HALF_EVEN') AS patient_sid,
      fact_rcom_pars_dcrp_all.payor_sequence_sid,
      fact_rcom_pars_dcrp_all.unit_num_sid,
      fact_rcom_pars_dcrp_all.eor_log_date,
      fact_rcom_pars_dcrp_all.log_sequence_num,
      fact_rcom_pars_dcrp_all.year_created_sid,
      fact_rcom_pars_dcrp_all.cost_year_sid,
      fact_rcom_pars_dcrp_all.cost_year_end_date,
      fact_rcom_pars_dcrp_all.payor_financial_class_sid,
      fact_rcom_pars_dcrp_all.payor_sid,
      fact_rcom_pars_dcrp_all.patient_type_sid,
      fact_rcom_pars_dcrp_all.discrepancy_age_month_sid,
      fact_rcom_pars_dcrp_all.discharge_age_month_sid,
      fact_rcom_pars_dcrp_all.scenario_sid,
      ROUND(fact_rcom_pars_dcrp_all.reason_code_1_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_1_sid,
      ROUND(fact_rcom_pars_dcrp_all.reason_code_2_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_2_sid,
      ROUND(fact_rcom_pars_dcrp_all.reason_code_3_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_3_sid,
      ROUND(fact_rcom_pars_dcrp_all.reason_code_4_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_4_sid,
      fact_rcom_pars_dcrp_all.source_sid,
      ROUND(fact_rcom_pars_dcrp_all.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
      fact_rcom_pars_dcrp_all.coid,
      fact_rcom_pars_dcrp_all.company_code,
      fact_rcom_pars_dcrp_all.resolve_reason_code,
      fact_rcom_pars_dcrp_all.discharge_date,
      fact_rcom_pars_dcrp_all.ra_remit_date,
      fact_rcom_pars_dcrp_all.reason_assignment_date_1,
      fact_rcom_pars_dcrp_all.reason_assignment_date_2,
      fact_rcom_pars_dcrp_all.reason_assignment_date_3,
      fact_rcom_pars_dcrp_all.reason_assignment_date_4,
      ROUND(fact_rcom_pars_dcrp_all.account_balance_amt, 3, 'ROUND_HALF_EVEN') AS account_balance_amt,
      fact_rcom_pars_dcrp_all.primary_reason_code_change_cnt,
      fact_rcom_pars_dcrp_all.discrepancy_days,
      fact_rcom_pars_dcrp_all.discrepancy_resolved_date,
      fact_rcom_pars_dcrp_all.discrepany_type_code,
      fact_rcom_pars_dcrp_all.discrepancy_type_sid,
      fact_rcom_pars_dcrp_all.same_store_sid,
      fact_rcom_pars_dcrp_all.dollar_strtf_sid,
      ROUND(fact_rcom_pars_dcrp_all.var_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_beg_amt,
      ROUND(fact_rcom_pars_dcrp_all.var_new_amt, 3, 'ROUND_HALF_EVEN') AS var_new_amt,
      ROUND(fact_rcom_pars_dcrp_all.var_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_resolved_amt,
      ROUND(fact_rcom_pars_dcrp_all.var_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_othr_cor_amt,
      ROUND(fact_rcom_pars_dcrp_all.var_end_amt, 3, 'ROUND_HALF_EVEN') AS var_end_amt,
      ROUND(fact_rcom_pars_dcrp_all.exp_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_crnt_amt,
      ROUND(fact_rcom_pars_dcrp_all.exp_rate_amt, 3, 'ROUND_HALF_EVEN') AS exp_rate_amt,
      fact_rcom_pars_dcrp_all.var_beg_cnt,
      fact_rcom_pars_dcrp_all.var_new_cnt,
      fact_rcom_pars_dcrp_all.var_resolved_cnt,
      fact_rcom_pars_dcrp_all.var_othr_cor_cnt,
      fact_rcom_pars_dcrp_all.var_end_cnt,
      fact_rcom_pars_dcrp_all.exp_crnt_cnt,
      fact_rcom_pars_dcrp_all.exp_rate_cnt,
      fact_rcom_pars_dcrp_all.resolved_days,
      fact_rcom_pars_dcrp_all.end_days,
      fact_rcom_pars_dcrp_all.pe_date,
      fact_rcom_pars_dcrp_all.source_system_code,
      fact_rcom_pars_dcrp_all.dw_last_update_time
    FROM
      {{ params.param_pbs_core_dataset_name }}.fact_rcom_pars_dcrp_all
  ;
