SELECT
SQLUser.HCPAS.HCPSID,
SQLUser.HCFACILITY.CSFAHOSPNUMBER,
SQLUser.HCFACILITY.HCFADESC,
SQLUser.HCENCOUNTER.CSENACCOUNTSTATUS,
SQLUser.HCENCOUNTER.HCENPTACCT,
SQLUser.HCENCOUNTER.HCENADMDTE,
SQLUser.HCENCOUNTER.HCENDSCDTE,
SQLUser.HCENCOUNTER.HCENORIGBAL,
SQLUser.HCENCOUNTER.HCENBAL,
SQLUser.HCENCOUNTER.HCENFINCLASS,
SQLUser.HCENCOUNTER.CSENEARLYOUTHOLD,
SQLUser.HCENCOUNTER.CSENFBILDTE,
---SQLUser.HCPERSON.HCPNTYP,
Null as HCPNTYP,
SQLUser.HCENCOUNTER.CSENBADDEBTTYP,
SQLUser.HCENCOUNTER.HCENTOTADJ*-1 as HCENTOTADJ ,
SQLUser.HCENCOUNTER.HCENTOTPAY,
--SQLUser.HCACCOUNT.CSACPREVPOOL,
CASE
  WHEN LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACPREVPOOL)) = '' or  LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACPREVPOOL)) is Null THEN '0'
  ELSE LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACPREVPOOL))
End CSACPREVPOOL,
SQLUser.HCACCOUNT.HCACPOOL,
SQLUser.HCACCOUNT.HCACWORKDTE,
SQLUser.HCENCOUNTER.HCENLSTWRKDTE,
SQLUser.HCACCOUNT.HCACWAITDATE,
SQLUser.HCACCOUNT.HCACSEQNUM,
HCACCOUNT_INS.HCACPAYNAME,
SQLUser.HCACCOUNT.HCACBAL,
HCACCOUNT_INS.CSACCLMSUBDTE,
--HCACCOUNT_PAT.HCACVENDID,
--Null as HCACVENDID,
---SQLUser.HCENCOUNTER.CSENVENDID as HCACVENDID,
 CASE
  WHEN LTRIM(RTRIM(SQLUser.HCENCOUNTER.CSENVENDID)) = '' THEN Null
  ELSE LTRIM(RTRIM(SQLUser.HCENCOUNTER.CSENVENDID))
End HCACVENDID,
SQLUser.HCACCOUNT.HCACPHASE,
SQLUser.HCACCOUNT.HCACCODE,
HCACCOUNT_INS.HCACDENIEDCD,
HCACCOUNT_INS.HCACDENIEDDATE,
--HCACCOUNT_PAT.CSACEODTE,
Null as CSACEODTE,
--SQLUser.HCACPLHIST.HCACPHPLLVL,
null as HCACPHPLLVL,
---SQLUser.HCACPLHIST.HCACPHPLDTE,
Null as HCACPHPLDTE,
--SQLUser.HCACPLHIST.HCACPHRCLDTE,
Null as HCACPHRCLDTE,
--HCACCOUNT_PAT.HCACVENXTRCLRVDTE,
null as HCACVENXTRCLRVDTE ,
--SQLUser.HCACPLHIST.HCACPHRCLREAS,
Null as HCACPHRCLREAS,
SQLUser.HCACCOUNT.CSACSERIES,
SQLUser.HCACCOUNT.HCACPHCHGDATE,
HCACCOUNT_INS.HCACFINCLASS,
{fn right(HCACCOUNT_INS.HCACPAYERID,5)} AS HCACPAYERID,
--HCVENDOR.HCVENAME,
null as HCVENAME,
--GCPOOL.GCPDESC,
Null as GCPDESC,
ActDate.Last_Action_Date,

--(select Max(SQLUser.CSPERSISTBILLHIST.CSPERSISTBHCLMSUBDTE) from  SQLUser.CSPERSISTBILLHIST)  as MAXDATE
current_date as MAXDATE,

/* New Artiva Fields Added below on 07062018*/
%truncate(SQLUser.HCENCOUNTER.HCENMRN,12) AS Medical_Record_Number ,

%truncate(HCACCOUNT_INS.HCACPOLNUM,20) AS Hic_Number ,  
%truncate(SQLUser.HCENCOUNTER.HCENSRVCD,4) AS Service_Code ,

%truncate(HCACCOUNT_INS.CSACPYRSEQ,1) AS Ins_Level ,
%truncate(HCACCOUNT_INS.HCACDENIEDCD,4) AS Denial_Code ,
HCACCOUNT_INS.HCACDENIEDDATE AS Denial_Date ,
%truncate(HCACCOUNT_INS.CSACAPPEALSFLAG,1) AS Appeals_Flag ,
%truncate(V.HCVENAME,40) AS Vendor_Name ,
%truncate(V2.HCVENAME,40) AS Previous_Vendor_Name ,
%truncate(SQLUser.HCFACILITY.CSFAACTIVE,1) AS Active_Status_Flag ,
SQLUser.HCACCOUNT.CSACPREVPOOLDTE AS Previous_Pool_Date ,
%truncate(SQLUser.HCACCOUNT.HCACPRISTATUS,8) AS Prior_Status_Code ,
%truncate(SQLUser.HCACCOUNT.HCACACTCODE,8) AS Action_Code ,
%truncate(SQLUser.HCACCOUNT.HCACRESCODE,8) AS Result_Code ,
%truncate(SQLUser.HCENCOUNTER.CSENPREVVENDID,8) AS Previous_VendorID ,
%truncate(SQLUser.HCENCOUNTER.CSENMISCVALUE,10) AS Misc_Value ,
%truncate(SQLUser.HCACCOUNT.HCACPHPREVVALUE,20) AS Previous_Liability_Phase ,
SQLUser.HCENCOUNTER.HCENACCTBAL AS Total_Balance_Of_Liabilities ,
SQLUser.HCENCOUNTER.CSENNONBILLCHG AS Non_Billable_Charges ,
%truncate(D.CSAPPSOURCE,1) AS Appeal_System ,
D.CSAPPCLOSEDTE AS Appeal_Close_Date ,
D.CSAPPSENTDTE AS Appeal_Sent_Date ,
D.CSAPPAMT AS Appeal_Amount ,
%truncate(D.CSAPPSOURCEID,30) AS AppealID ,
%truncate(D.CSAPPDENIALCODE,4) AS Appeal_Denial_Code ,
%truncate(D.CSAPPDISPOSITION,10) AS Appeal_System_Desc ,
%truncate(D.CSAPPDISPDESC,30) AS Appeal_Disposition ,
D.CSAPPFOLLOWUPDTE AS Appeal_Follow_Up_Date ,
%truncate(D.CSAPPSOURCELVL,4) AS Appeal_Level ,
%truncate(D.CSAPPSOURCESEQ,4) AS Appeal_Sequence ,
%truncate(D.CSAPPLASTACTIVITY,60) AS Appeal_Concuity_Activity ,
%truncate(D.CSAPPPRLASTACTIVITY,60) AS Appeal_Concuity_Previous_Activ,
P.HCACVEPLDTE AS Placement_Date ,
P.HCACVEPLAMT AS Placement_Amount ,
P.HCACVEPLLVL AS Placement_Level,
%truncate(HCACCOUNT_INS.CSACCLAIM,20) AS Claim_Number,
%truncate(R.CSPOOLINCLUDEFLG,1) AS Inclusion_Flag,
%truncate(R.CSPOOLRESPDEPT,20) AS Responsible_Department,
HCACCOUNT.CSACINSBALLEVEL AS Ins_Liability_Level,
SQLUser.HCACCOUNT.CSACLSTCLRSPDTE as CI_Stat_Last_Response_Date,
SQLUser.HCACCOUNT.CSACLSTCLRSPPROB AS Last_Claim_Status_Rspn_Pblm_Cd,
SQLUser.HCACCOUNT.CSACLSTCLRSPCD as CI_Stat_Last_Resp_Status,
CASE
  WHEN LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACLSTCLRSPSUBCAT)) = '' or  LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACLSTCLRSPSUBCAT)) is Null THEN '0'
  ELSE LTRIM(RTRIM(SQLUser.HCACCOUNT.CSACLSTCLRSPSUBCAT))
End as CI_Stat_Last_Resp_Sub_Cat,
SQLUser.HCACCOUNT.CSACLSTCLRSPTYPE as CI_Stat_Last_Resp_Type,
SQLUser.HCCLAIMCODES.HCCLSDESC as Report_Desc,
SQLUser.HCCLAIMCODES.HCCLID as Claim_Status_Code,
%truncate(SQLUser.HCCLAIMCODES.HCCLCCID,20) as Claim_Status_Relt_Scat_Id,
%truncate(SQLUser.HCCLSUBCATEGORY.HCCCID,6) as Claim_Status_Scat_Id,
SQLUser.HCCLSUBCATEGORY.HCCCSDESC as Claim_Status_Scat_Desc,
Cast(SQLUser.HCCLSUBCATEGORY.HCCCLDESC as Char(255)) as Category_Desc,
%truncate(HCACCOUNT_INS.CSACCHECKNUM,50) as  CSACCHECKNUM,
HCACCOUNT. HCACUSERALERTDTE ,
HCACCOUNT.HCACUSERALERTEXPDTE,
HCACCOUNT.HCACUSERALERT,
SQLUser.HCACCOUNT.CSACBHIND as Billing_History_Indicator ,
SQLUser.HCPAS.CSPSINSIGAMT as PAS_Insignificant_Amt ,
ActDate.Last_Action_Code_Time ,
ActDate.Last_Action_Code_User_ID ,
HCACCOUNT_INS.CSACORIGBAL as CSACORIGBAL,
HCACCOUNT.CSACLOBGROUP as CSACLOBGROUP
,SQLUser.HCENCOUNTER.CSENNOTICEOFADM AS CSENNOTICEOFADM 
,SQLUser.HCENCOUNTER.CSENNOTICEOFEPISODE AS CSENNOTICEOFEPISODE 
,CAST(SQLUser.HCENCOUNTER.CSENEPISODEID AS DECIMAL(15,0))AS CSENEPISODEID 
,CAST(SQLUser.HCENCOUNTER.CSENPATIENTID AS DECIMAL(15,0)) AS CSENPATIENTID 
,SQLUser.HCACCOUNT.CSACERISA AS CSACERISA 
,HCACCOUNT.CSACWEBSTATUSFLAG as CSACWEBSTATUSFLAG
,SQLUser.CSELIGIBILITYHIST.CSEHCOLORADOSCRNFLAG
,SQLUser.CSELIGIBILITYHIST.CSEHINCLINLTR 
,SQLUser.CSELIGIBILITYHIST.CSEHPROGRAMGRPDESC
,SQLUser.CSELIGIBILITYHIST.CSEHSCREENDTE
, 'v_currtimestamp' AS dw_last_update_date_time
FROM 
SQLUser.HCPAS INNER JOIN SQLUser.HCFACILITY ON (SQLUser.HCPAS.HCPSID=SQLUser.HCFACILITY.HCFAPASID)
INNER JOIN SQLUser.HCENCOUNTER ON (SQLUser.HCFACILITY.HCFAID=SQLUser.HCENCOUNTER.HCENFACILITY)
INNER JOIN SQLUser.HCACCOUNT ON (SQLUser.HCENCOUNTER.HCENID=SQLUser.HCACCOUNT.HCACENCNTRID)
INNER JOIN SQLUser.HCACCOUNT  HCACCOUNT_INS ON  SQLUser.HCACCOUNT.HCACID=HCACCOUNT_INS.HCACID
LEFT OUTER JOIN SQLUser.CSAPPEALS D ON D.CSAPPID = HCACCOUNT_INS.CSACAPPID
LEFT OUTER JOIN SQLUser.HCACCOUNT P ON SQLUser.HCENCOUNTER.HCENID=P.HCACENCNTRID

LEFT OUTER JOIN SQLUser.HCVENDOR V ON V.HCVENDID = SQLUser.HCENCOUNTER.CSENVENDID
LEFT OUTER JOIN SQLUser.HCVENDOR V2 ON V2.HCVENDID = SQLUser.HCENCOUNTER.CSENPREVVENDID
LEFT OUTER JOIN SQLUser.CSPOOLOPTIONS R ON SQLUser.HCACCOUNT.HCACLPOOL = R.CSPOOLKEY
LEFT OUTER JOIN SQLUser.CSELIGIBILITYHIST ON SQLUser.CSELIGIBILITYHIST.CSEHENID=SQLUser.HCENCOUNTER.HCENID
LEFT OUTER JOIN
(SELECT
H.HCACTHACNUM,
A.Last_Action_Date,
H.HCACTHTIM as Last_Action_Code_Time,
H.HCACTHUSERID as Last_Action_Code_User_ID
FROM SQLUser.HCACTIONHIST as H
JOIN (SELECT
HCACTHACNUM,
Max(HCACTHDTE) as Last_Action_Date
FROM 
SQLUser.HCACTIONHIST
WHERE
(HCACTHACTID IS NOT NULL OR HCACTHRESID IS NOT NULL)
GROUP BY HCACTHACNUM
) as A
    ON A.HCACTHACNUM = H.HCACTHACNUM
    AND A.Last_Action_Date = H.HCACTHDTE
) as ActDate
    ON SQLUser.HCACCOUNT.HCACID=ActDate.HCACTHACNUM
LEFT JOIN SQLUser.HCCLAIMCODES
                ON SQLUser.HCCLAIMCODES.HCCLID = SQLUser.HCACCOUNT.CSACLSTCLRSPPROB
LEFT JOIN SQLUser.HCCLSUBCATEGORY
                ON SQLUser.HCCLSUBCATEGORY.HCCCID = SQLUser.HCACCOUNT.CSACLSTCLRSPSUBCAT
WHERE
SQLUser.HCENCOUNTER.CSENACCOUNTSTATUS  IN  ( 'CA','AR','AX'  ) and SQLUser.HCENCOUNTER.HCENBAL<>0
--and HCACCOUNT_INS.HCACSEQNUM <> 99
and P.HCACSEQNUM=99
--AND SQLUser.HCENCOUNTER.HCENPTACCT = 973555520