/***************************************************************************************
   C U S T O M   S E C U R I T Y   V I E W
****************************************************************************************/
CREATE OR REPLACE VIEW {{params.param_hr_rstc_views_dataset_name}}.employee_performance_detail AS SELECT
    a.employee_performance_sid,
    a.valid_from_date,
    a.employee_talent_profile_sid,
    a.employee_sid,
    a.review_period_id,
    a.review_year_num,
    a.review_period_start_date,
    a.review_period_end_date,
    a.performance_plan_id,
    a.evaluation_workflow_status_id,
    a.manager_full_name,
    a.manager_employee_num,
    a.employee_performance_num,
    a.employee_performance_rating_id,
    a.performance_rating_num,
    a.performance_rating_id,
    a.employee_smry_competency_num,
    a.employee_smry_competency_rating_id,
    a.smry_competency_num,
    a.smry_competency_rating_id,
    a.employee_smry_goal_num,
    a.employee_smry_goal_rating_id,
    a.smry_goal_num,
    a.smry_goal_rating_id,
    a.employee_strength_accomplishment_text,
    a.employee_area_of_improvement_text,
    a.employee_additional_comment_text,
    a.strength_accomplishment_text,
    a.areas_of_improvement_text,
    a.additional_comment_text,
    a.employee_num,
    a.lawson_company_num,
    a.process_level_code,
    a.source_system_key,
    a.valid_to_date,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    {{params.param_hr_base_views_dataset_name}}.employee_performance_detail AS a
;
