--OPTOUT BY SSC					(UPDATED 10/14/2020)
SELECT 
    (CASE 
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' THEN REPLACE((HCFACILITY.HCFAPASID), 'CAPELLA', 'CLIENT-NAS')
        WHEN HCFACILITY.HCFAPASID LIKE '%LIFEPOINT%' THEN REPLACE((HCFACILITY.HCFAPASID), 'LIFEPOINT', 'CLIENT')
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' THEN 'DAL/SAN'
        WHEN HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS PASID -- STUSERAUDITACCT.CSUAAFAPASID    -- PENDING ARTIVA INTEGRATION TO STUSERAUDITACCT TABLE
    , (CASE
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' OR HCFACILITY.HCFAPASID = 'CLIENT-NAS' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-NAS' THEN 'NASHVILLE'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-OPK' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-OPK' THEN 'ORANGEPARK'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-RIC' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-RIC' THEN 'RICHMOND'
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' OR HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS SSC
    , STUSERAUDIT.CSUAMONTHLYREVIEWID, STUSERAUDIT.STUAMONTH, STUSERAUDIT.STUAYEAR, 
	STUSERAUDIT.STUARVWEND, STUSERAUDIT.STUAPHASE, STUSERAUDIT.STUAID, STUSERAUDITACCT.STUAAID 
    , STUSER_AGENT.HCUADEPT, STUSERAUDIT.STUAUSERID, STUSER_AGENT.UAFULLNAME, 
	STUSERAUDIT.CSUAREVIEWER, STUSERAUDIT.STUASUPERVISORID
    , STUSERAUDITACCT.CSUAAFAHOSPNUM
    , STUSERAUDITACCT.CSUAAENPTACCT
    , STUSERAUDITACCT.CSUAAPYIPLAN
    , STUSERAUDITACCT.CSUAOPTOUTREASON, STUSERAUDITACCT.CSUAAOPTOUTWFPATH
    , (CASE 
        WHEN LEN(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT) > 150 THEN REPLACE(REPLACE((LEFT(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT,150)), char(10), ''), char(13), '') 
        ELSE REPLACE(REPLACE(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT, char(10), ''), char(13), '') END) AS OPTOUTCOMMENT
FROM ((SQLUser.STUSERAUDITACCT STUSERAUDITACCT LEFT OUTER JOIN SQLUser.STUSERAUDIT STUSERAUDIT ON STUSERAUDITACCT.STUAAAUDITID = STUSERAUDIT.STUAID)
    LEFT OUTER JOIN SQLUser.STUSER STUSER_AGENT ON STUSERAUDIT.STUAUSERID = STUSER_AGENT.USERID)
    , SQLUser.HCFACILITY HCFACILITY
WHERE STUSERAUDITACCT.CSUAAFAHOSPNUM = HCFACILITY.CSFAHOSPNUM AND STUSERAUDITACCT.CSUAOPTOUTREASON IS NOT NULL 
    AND STUSERAUDIT.STUARVWEND>={d '2020-11-01'}
ORDER BY STUSERAUDITACCT.STUAAID ASC