-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/facility_iplan_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.facility_iplan_pf AS SELECT
    ROUND(a.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    a.coid,
    a.company_code,
    a.iplan_id,
    a.plan_desc,
    a.payor_name,
    ROUND(a.payor_id, 0, 'ROUND_HALF_EVEN') AS payor_id,
    a.major_payor_group_id,
    a.payor_sub_id,
    a.sub_payor_group_id,
    a.eff_from_date,
    a.eff_to_date,
    ROUND(a.iplan_financial_class_code, 0, 'ROUND_HALF_EVEN') AS iplan_financial_class_code,
    a.iplan_inactive_date,
    a.payment_model_num,
    a.payor_auth_length_stay_days,
    a.length_of_stay_extension_num,
    a.verification_ind,
    a.precertification_ind,
    a.recertification_day_count,
    a.pro_review_ind,
    ROUND(a.charge_benefit_code, 0, 'ROUND_HALF_EVEN') AS charge_benefit_code,
    ROUND(a.op_coinsurance_code, 0, 'ROUND_HALF_EVEN') AS op_coinsurance_code,
    a.emc_process_code,
    a.icd10_conversion_date,
    a.federal_tax_identifier,
    a.subunit_tax_identifier,
    a.govt_rpt_id,
    a.separate_ub82_ind,
    a.hold_claim_ind,
    a.ub92_format_code,
    a.b1500_format_code,
    a.b1500_coding_scheme_code,
    a.ancillary_chg_incl_room_ind,
    ROUND(a.ancillary_maximum_amt, 3, 'ROUND_HALF_EVEN') AS ancillary_maximum_amt,
    a.processor_id,
    a.processor_sub_id,
    a.accelerated_billing_code,
    a.bill_code,
    a.log_id,
    a.type_of_claim_code,
    a.health_plan_id,
    ROUND(a.inpatient_npi, 0, 'ROUND_HALF_EVEN') AS inpatient_npi,
    ROUND(a.outpatient_npi, 0, 'ROUND_HALF_EVEN') AS outpatient_npi,
    a.inpatient_taxonomy_code,
    a.outpatient_taxonomy_code,
    a.hosp_acquired_cond_ind,
    a.notice_of_adm_file,
    a.notice_of_adm_ind,
    a.admit_disch_date_flag,
    a.outpatient_pps_flag,
    a.outpatient_pps_flag_tricare,
    a.outpatient_apc_edit_ind,
    a.meditech_mnemonic,
    a.inpatient_provider_number,
    a.outpatient_provider_number,
    a.part_b_ind,
    a.part_b_ext_benf_ind,
    a.part_b_ext_full_op_benf_ind,
    a.bill_drug_waste_type,
    a.po_modifier_ind,
    a.uninsured_ind,
    a.payer_type_code,
    a.reimbursement_type_code,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.facility_iplan_pf AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
     AND upper(a.coid) = upper(b.co_id)
     AND b.user_id = session_user()
;
