-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/pass_eom_hun.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.pass_eom_hun AS SELECT
    bv.patient_dw_id,
    bv.company_code,
    bv.coid,
    bv.unit_num,
    bv.processing_zone_code,
    bv.stack_code,
    bv.rptg_period,
    bv.pat_acct_num,
    bv.facility_name,
    CASE
      WHEN session_user() = z.userid THEN '***'
      ELSE bv.patient_full_name
    END AS patient_full_name,
    bv.financial_class_code,
    bv.financial_class_desc,
    bv.patient_type_code,
    bv.derived_patient_type_code,
    bv.account_status_code,
    bv.admission_date,
    bv.discharge_date,
    bv.final_bill_date,
    bv.ar_bill_thru_date,
    bv.length_of_stay_days_num,
    bv.collector_org_code,
    bv.collector_org_type_code,
    bv.collector_org_short_name,
    bv.log_id,
    bv.log_name,
    bv.ip_contract_model_code,
    bv.iplan_id_ins1,
    bv.payor_name_ins1,
    bv.release_ind_ins1,
    bv.payor_balance_amt_ins1,
    bv.payor_liability_amt_ins1,
    bv.payor_payment_amt_ins1,
    bv.payor_adjustment_amt_ins1,
    bv.payor_contract_allow_amt_ins1,
    bv.pa_syst_adj_current_amt_ins1,
    bv.pa_new_actv_current_amt_ins1,
    bv.iplan_id_ins2,
    bv.payor_name_ins2,
    bv.release_ind_ins2,
    bv.payor_balance_amt_ins2,
    bv.payor_liability_amt_ins2,
    bv.payor_payment_amt_ins2,
    bv.payor_adjustment_amt_ins2,
    bv.payor_contract_allow_amt_ins2,
    bv.pa_syst_adj_current_amt_ins2,
    bv.pa_new_actv_current_amt_ins2,
    bv.iplan_id_ins3,
    bv.payor_name_ins3,
    bv.release_ind_ins3,
    bv.payor_balance_amt_ins3,
    bv.payor_liability_amt_ins3,
    bv.payor_payment_amt_ins3,
    bv.payor_adjustment_amt_ins3,
    bv.payor_contract_allow_amt_ins3,
    bv.pa_syst_adj_current_amt_ins3,
    bv.pa_new_actv_current_amt_ins3,
    bv.patient_balance_amt,
    bv.patient_liability_amt,
    bv.patient_payment_amt,
    bv.patient_adjustment_amt,
    bv.patient_contract_allow_amt,
    bv.total_billed_charge_amt,
    bv.total_rb_charge_amt,
    bv.total_anc_charge_amt,
    bv.total_write_off_bad_debt_amt,
    bv.total_write_off_other_amt,
    bv.total_adjustment_amt,
    bv.total_contract_allow_amt,
    bv.total_combined_adj_alw_amt,
    bv.total_payment_amt,
    bv.total_account_balance_amt,
    bv.prelim_account_balance_amt,
    bv.eor_gross_reimbursement_amt,
    bv.eor_contract_allow_amt,
    bv.eor_auto_post_amt,
    bv.discharge_to_eom_day_cnt,
    bv.current_month_amt,
    bv.sub_unit_num,
    bv.sub_unit_name,
    bv.drg_code,
    bv.icd_version_ind,
    bv.drg_payment_weight_amt,
    bv.drg_code_hcfa,
    bv.drg_code_classic,
    bv.drg_code_pre_hac,
    bv.drg_code_pre_hac_tricare,
    bv.denial_code_ins1,
    bv.financial_class_code_ins1,
    bv.denial_code_ins2,
    bv.financial_class_code_ins2,
    bv.denial_code_ins3,
    bv.financial_class_code_ins3,
    bv.prorated_release_amt_ins1,
    bv.prorated_release_amt_ins2,
    bv.prorated_release_amt_ins3,
    bv.prorated_release_date_ins1,
    bv.prorated_release_date_ins2,
    bv.prorated_release_date_ins3,
    bv.logging_ind,
    bv.auto_post_ind,
    bv.unbill_pre_admit_ind,
    bv.insured_employer_name,
    bv.insured_role_code,
    bv.apr_severity_of_illness,
    bv.apr_risk_of_mortality
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.pass_eom_hun AS bv
    LEFT OUTER JOIN (
      SELECT
          security_mask_and_exception.userid,
          security_mask_and_exception.masked_column_code
        FROM
          `hca-hin-dev-cur-parallon`.edw_sec.security_mask_and_exception
        WHERE security_mask_and_exception.userid = session_user()
         AND upper(security_mask_and_exception.masked_column_code) = 'PN'
    ) AS z ON session_user() = z.userid
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS sf ON upper(bv.coid) = upper(sf.co_id)
     AND sf.user_id = session_user()
;
