-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/reimbursement_discrepancy_eom_hist.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.reimbursement_discrepancy_eom_hist
   OPTIONS(description='Maintains the History of Reimbursement Discrepancy End Of Month snapshot.')
  AS SELECT
      a.company_code,
      a.coid,
      ROUND(a.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      ROUND(a.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      a.iplan_insurance_order_num,
      a.eor_log_date,
      a.log_id,
      a.log_sequence_num,
      a.discrepancy_resolved_date,
      a.eff_from_date,
      ROUND(a.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      a.iplan_id,
      a.length_of_stay_days_num,
      a.eor_drg_code,
      a.eor_hipps_code,
      ROUND(a.eor_payment_amt, 3, 'ROUND_HALF_EVEN') AS eor_payment_amt,
      a.remittance_date,
      a.ra_log_date,
      a.ra_payment_date,
      a.ra_drg_code,
      a.ra_hipps_code,
      a.ra_covered_days_num,
      ROUND(a.ra_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_charge_amt,
      ROUND(a.ra_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_non_covered_charge_amt,
      ROUND(a.ra_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS ra_gross_reimbursement_amt,
      ROUND(a.ra_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS ra_ded_coins_amt,
      ROUND(a.ra_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_payment_amt,
      ROUND(a.ra_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS ra_contractual_allowance_amt,
      ROUND(a.ra_copay_amt, 3, 'ROUND_HALF_EVEN') AS ra_copay_amt,
      ROUND(a.ra_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ra_coinsurance_amt,
      ROUND(a.ra_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_billed_charge_amt,
      ROUND(a.ra_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_deductible_amt,
      ROUND(a.ra_total_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_deductible_amt,
      ROUND(a.ra_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_blood_deductible_amt,
      ROUND(a.ra_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_lab_payment_amt,
      ROUND(a.ra_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_therapy_payment_amt,
      ROUND(a.ra_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_primary_payor_payment_amt,
      ROUND(a.ra_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_outlier_payment_amt,
      ROUND(a.ra_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_capital_payment_amt,
      ROUND(a.ra_denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_denied_charge_amt,
      ROUND(a.ra_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_apc_service_amt,
      ROUND(a.ra_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_fee_schedule_amt,
      ROUND(a.over_under_payment_amt, 3, 'ROUND_HALF_EVEN') AS over_under_payment_amt,
      ROUND(a.actual_payment_amt, 3, 'ROUND_HALF_EVEN') AS actual_payment_amt,
      a.discrepancy_origination_date,
      a.discrepancy_day_count,
      a.resolve_reason_code,
      a.discrepancy_status_code,
      a.var_covered_days_num,
      ROUND(a.var_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_total_charge_amt,
      ROUND(a.var_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_non_covered_charge_amt,
      ROUND(a.var_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_net_billed_charge_amt,
      ROUND(a.var_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_reimbursement_amt,
      ROUND(a.var_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_deductible_amt,
      ROUND(a.var_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS var_coinsurance_amt,
      ROUND(a.var_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS var_ded_coins_amt,
      ROUND(a.var_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_blood_deductible_amt,
      ROUND(a.var_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_insurance_payment_amt,
      ROUND(a.var_primary_payor_pmt_amt, 3, 'ROUND_HALF_EVEN') AS var_primary_payor_pmt_amt,
      ROUND(a.var_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_capital_payment_amt,
      ROUND(a.var_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_lab_payment_amt,
      ROUND(a.var_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_outlier_payment_amt,
      ROUND(a.var_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_therapy_payment_amt,
      ROUND(a.var_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS var_contractual_allowance_amt,
      ROUND(a.var_copay_amt, 3, 'ROUND_HALF_EVEN') AS var_copay_amt,
      ROUND(a.var_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_covered_charge_amt,
      ROUND(a.var_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS var_net_apc_service_amt,
      ROUND(a.var_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS var_net_fee_schedule_amt,
      a.inpatient_outpatient_ind,
      a.primary_reason_assignment_cnt,
      a.discrepancy_reason_code_1,
      a.reason_assignment_date_1,
      a.discrepancy_reason_code_2,
      a.reason_assignment_date_2,
      a.discrepancy_reason_code_3,
      a.reason_assignment_date_3,
      a.discrepancy_reason_code_4,
      a.reason_assignment_date_4,
      a.comments,
      a.work_date,
      a.last_racf_id,
      a.last_racf_date,
      a.data_source_code,
      ROUND(a.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
      a.ar_bill_thru_date,
      ROUND(a.cc_calc_id, 0, 'ROUND_HALF_EVEN') AS cc_calc_id,
      ROUND(a.cc_account_activity_id, 0, 'ROUND_HALF_EVEN') AS cc_account_activity_id,
      ROUND(a.cc_reason_id, 0, 'ROUND_HALF_EVEN') AS cc_reason_id,
      ROUND(a.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
      a.last_update_date,
      a.dw_last_update_date_time,
      a.source_system_code
    FROM
      `hca-hin-dev-cur-parallon`.edwpbs_base_views.reimbursement_discrepancy_eom_hist AS a
      INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
       AND upper(a.coid) = upper(b.co_id)
       AND b.user_id = session_user()
    WHERE upper(a.discrepancy_status_code) = 'O'
  ;
