-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/resolved_discrepancy_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.resolved_discrepancy_pf AS SELECT
    rd.company_code,
    rd.coid,
    ROUND(rd.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(rd.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    rd.iplan_insurance_order_num,
    rd.eor_log_date,
    rd.log_id,
    rd.log_sequence_num,
    rd.discrepancy_resolved_date,
    rd.eff_from_date,
    ROUND(rd.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    rd.iplan_id,
    rd.length_of_stay_days_num,
    rd.eor_drg_code,
    rd.eor_hipps_code,
    ROUND(rd.eor_payment_amt, 3, 'ROUND_HALF_EVEN') AS eor_payment_amt,
    rd.remittance_date,
    rd.ra_log_date,
    rd.ra_payment_date,
    rd.ra_drg_code,
    rd.ra_hipps_code,
    rd.ra_covered_days_num,
    ROUND(rd.ra_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_charge_amt,
    ROUND(rd.ra_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_non_covered_charge_amt,
    ROUND(rd.ra_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS ra_gross_reimbursement_amt,
    ROUND(rd.ra_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS ra_ded_coins_amt,
    ROUND(rd.ra_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_payment_amt,
    ROUND(rd.ra_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS ra_contractual_allowance_amt,
    ROUND(rd.ra_copay_amt, 3, 'ROUND_HALF_EVEN') AS ra_copay_amt,
    ROUND(rd.ra_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ra_coinsurance_amt,
    ROUND(rd.ra_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_billed_charge_amt,
    ROUND(rd.ra_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_deductible_amt,
    ROUND(rd.ra_total_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_deductible_amt,
    ROUND(rd.ra_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_blood_deductible_amt,
    ROUND(rd.ra_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_lab_payment_amt,
    ROUND(rd.ra_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_therapy_payment_amt,
    ROUND(rd.ra_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_primary_payor_payment_amt,
    ROUND(rd.ra_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_outlier_payment_amt,
    ROUND(rd.ra_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_capital_payment_amt,
    ROUND(rd.ra_denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_denied_charge_amt,
    ROUND(rd.ra_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_apc_service_amt,
    ROUND(rd.ra_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_fee_schedule_amt,
    ROUND(rd.over_under_payment_amt, 3, 'ROUND_HALF_EVEN') AS over_under_payment_amt,
    ROUND(rd.actual_payment_amt, 3, 'ROUND_HALF_EVEN') AS actual_payment_amt,
    rd.discrepancy_origination_date,
    rd.discrepancy_inactive_date,
    rd.discrepancy_day_count,
    rd.resolve_reason_code,
    rd.var_covered_days_num,
    ROUND(rd.var_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_total_charge_amt,
    ROUND(rd.var_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_non_covered_charge_amt,
    ROUND(rd.var_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_net_billed_charge_amt,
    ROUND(rd.var_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_reimbursement_amt,
    ROUND(rd.var_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_deductible_amt,
    ROUND(rd.var_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS var_coinsurance_amt,
    ROUND(rd.var_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS var_ded_coins_amt,
    ROUND(rd.var_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_blood_deductible_amt,
    ROUND(rd.var_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_insurance_payment_amt,
    ROUND(rd.var_primary_payor_pmt_amt, 3, 'ROUND_HALF_EVEN') AS var_primary_payor_pmt_amt,
    ROUND(rd.var_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_capital_payment_amt,
    ROUND(rd.var_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_lab_payment_amt,
    ROUND(rd.var_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_outlier_payment_amt,
    ROUND(rd.var_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_therapy_payment_amt,
    ROUND(rd.var_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS var_contractual_allowance_amt,
    ROUND(rd.var_copay_amt, 3, 'ROUND_HALF_EVEN') AS var_copay_amt,
    ROUND(rd.var_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_covered_charge_amt,
    ROUND(rd.var_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS var_net_apc_service_amt,
    ROUND(rd.var_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS var_net_fee_schedule_amt,
    rd.inpatient_outpatient_ind,
    rd.primary_reason_assignment_cnt,
    rd.discrepancy_reason_code_1,
    rd.reason_assignment_date_1,
    rd.discrepancy_reason_code_2,
    rd.reason_assignment_date_2,
    rd.discrepancy_reason_code_3,
    rd.reason_assignment_date_3,
    rd.discrepancy_reason_code_4,
    rd.reason_assignment_date_4,
    rd.comments,
    rd.work_date,
    rd.last_racf_id,
    rd.last_racf_date,
    rd.data_source_code,
    ROUND(rd.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
    rd.ar_bill_thru_date,
    ROUND(rd.cc_calc_id, 0, 'ROUND_HALF_EVEN') AS cc_calc_id,
    ROUND(rd.cc_account_activity_id, 0, 'ROUND_HALF_EVEN') AS cc_account_activity_id,
    ROUND(rd.cc_reason_id, 0, 'ROUND_HALF_EVEN') AS cc_reason_id,
    ROUND(rd.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
    rd.last_update_date,
    rd.dw_last_update_date_time,
    rd.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.resolved_discrepancy_pf AS rd
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS sf ON upper(rd.coid) = upper(sf.co_id)
     AND sf.user_id = session_user()
;
