CREATE OR REPLACE VIEW {{ params.param_cr_base_views_dataset_name }}.cancer_patient_outcome_timeliness
   OPTIONS(description='Contains consolidated patients navigated by Sarah Cannon through Metriq iNavigate and Cancer Patient ID and tumor information for them')
  AS SELECT
      cancer_patient_outcome_timeliness.cancer_patient_tumor_driver_sk,
      cancer_patient_outcome_timeliness.cancer_patient_driver_sk,
      cancer_patient_outcome_timeliness.cancer_tumor_driver_sk,
      cancer_patient_outcome_timeliness.coid,
      cancer_patient_outcome_timeliness.company_code,
      cancer_patient_outcome_timeliness.length_to_chemo_day_num,
      cancer_patient_outcome_timeliness.length_to_hormone_day_num,
      cancer_patient_outcome_timeliness.length_to_immuno_day_num,
      cancer_patient_outcome_timeliness.length_to_surgery_day_num,
      cancer_patient_outcome_timeliness.length_to_radiation_day_num,
      cancer_patient_outcome_timeliness.length_to_transplant_day_num,
      cancer_patient_outcome_timeliness.length_to_first_treatment_day_num,
      cancer_patient_outcome_timeliness.first_surgery_chemo_elapsed_day_num,
      cancer_patient_outcome_timeliness.first_chemo_surgery_elapsed_day_num,
      cancer_patient_outcome_timeliness.radiation_elapsed_day_num,
      cancer_patient_outcome_timeliness.length_to_surgery_last_contact_day_num,
      cancer_patient_outcome_timeliness.length_to_diagnosis_last_contact_day_num,
      cancer_patient_outcome_timeliness.length_to_diagnosis_last_contact_mth_num,
      cancer_patient_outcome_timeliness.last_contact_date,
      cancer_patient_outcome_timeliness.admission_date,
      cancer_patient_outcome_timeliness.rln10_concordant_ind,
      cancer_patient_outcome_timeliness.rln12_concordant_ind,
      cancer_patient_outcome_timeliness.act_concordant_ind,
      cancer_patient_outcome_timeliness.bcs_concordant_ind,
      cancer_patient_outcome_timeliness.bcsrt_concordant_ind,
      cancer_patient_outcome_timeliness.cbrrt_concordant_ind,
      cancer_patient_outcome_timeliness.cerct_concrodant_ind,
      cancer_patient_outcome_timeliness.cerrt_concrodant_ind,
      cancer_patient_outcome_timeliness.endctrt_concordant_ind,
      cancer_patient_outcome_timeliness.endlrc_concordant_ind,
      cancer_patient_outcome_timeliness.g15rlnc_concordant_ind,
      cancer_patient_outcome_timeliness.lct_concordant_ind,
      cancer_patient_outcome_timeliness.ht_concordant_ind,
      cancer_patient_outcome_timeliness.lnosurg_concordant_ind,
      cancer_patient_outcome_timeliness.mac_concordant_ind,
      cancer_patient_outcome_timeliness.mastrt_concordant_ind,
      cancer_patient_outcome_timeliness.nb_concordant_ind,
      cancer_patient_outcome_timeliness.ovsal_concordant_ind,
      cancer_patient_outcome_timeliness.recrtct_concordance_ind,
      cancer_patient_outcome_timeliness.source_system_code,
      cancer_patient_outcome_timeliness.dw_last_update_date_time
    FROM
      {{ params.param_cr_core_dataset_name }}.cancer_patient_outcome_timeliness
  ;
