CREATE OR REPLACE VIEW {{ params.param_cr_base_views_dataset_name }}.consolidated_patient_encounter
   OPTIONS(description='Contains Encounter IDs from different databases that tie multiple encounters in different care settings to a single EMPI. Currently ties Hospital events, HCAPS events, and Contact Center events to a single patient.')
  AS SELECT
      consolidated_patient_encounter.encounter_id,
      consolidated_patient_encounter.encounter_source_system_code,
      consolidated_patient_encounter.empi_text,
      consolidated_patient_encounter.encounter_database_code,
      consolidated_patient_encounter.encounter_id_type_id,
      consolidated_patient_encounter.encounter_matching_source_id,
      consolidated_patient_encounter.pat_acct_num,
      consolidated_patient_encounter.medical_record_num,
      consolidated_patient_encounter.patient_market_urn,
      consolidated_patient_encounter.encounter_start_date,
      consolidated_patient_encounter.encounter_start_date_time,
      consolidated_patient_encounter.encounter_end_date,
      consolidated_patient_encounter.encounter_end_date_time,
      consolidated_patient_encounter.bill_date,
      consolidated_patient_encounter.discharge_status_code,
      consolidated_patient_encounter.coid,
      consolidated_patient_encounter.company_code,
      consolidated_patient_encounter.sub_unit_num,
      consolidated_patient_encounter.primary_icd_version_code,
      consolidated_patient_encounter.diagnosis_type_code,
      consolidated_patient_encounter.principal_diagnosis_code,
      consolidated_patient_encounter.procedure_type_code,
      consolidated_patient_encounter.principal_procedure_code,
      consolidated_patient_encounter.principal_procedure_date,
      consolidated_patient_encounter.total_billed_charge_amt,
      consolidated_patient_encounter.total_payments_amt,
      consolidated_patient_encounter.patient_age,
      consolidated_patient_encounter.patient_birth_date,
      consolidated_patient_encounter.patient_gender_code,
      consolidated_patient_encounter.patient_person_dw_id,
      consolidated_patient_encounter.patient_address_dw_id,
      consolidated_patient_encounter.patient_zip_code,
      consolidated_patient_encounter.financial_class_code,
      consolidated_patient_encounter.payor_dw_id,
      consolidated_patient_encounter.iplan_id,
      consolidated_patient_encounter.major_payor_dw_id,
      consolidated_patient_encounter.masterfacts_schema_id,
      consolidated_patient_encounter.employer_dw_id,
      consolidated_patient_encounter.patient_to_facility_mileage,
      consolidated_patient_encounter.patient_email_address_text,
      consolidated_patient_encounter.patient_phone_num,
      consolidated_patient_encounter.dw_last_update_date_time
    FROM
      {{ params.param_cp_base_views_dataset_name }}.consolidated_patient_encounter
  ;
