CREATE OR REPLACE VIEW {{ params.param_cr_base_views_dataset_name }}.fact_rad_onc_activity_billing
   OPTIONS(description='Contains fact information of Radiation Oncology for activity billing')
  AS SELECT
      fact_rad_onc_activity_billing.fact_activity_billing_sk,
      fact_rad_onc_activity_billing.physician_sk,
      fact_rad_onc_activity_billing.attending_oncologist_id,
      fact_rad_onc_activity_billing.patient_course_sk,
      fact_rad_onc_activity_billing.hospital_sk,
      fact_rad_onc_activity_billing.activity_sk,
      fact_rad_onc_activity_billing.activity_transaction_sk,
      fact_rad_onc_activity_billing.procedure_code_sk,
      fact_rad_onc_activity_billing.patient_sk,
      fact_rad_onc_activity_billing.activity_category_id,
      fact_rad_onc_activity_billing.site_sk,
      fact_rad_onc_activity_billing.source_fact_activity_billing_id,
      fact_rad_onc_activity_billing.primary_global_charge_amt,
      fact_rad_onc_activity_billing.primary_technical_charge_amt,
      fact_rad_onc_activity_billing.primary_professional_charge_amt,
      fact_rad_onc_activity_billing.other_professional_charge_amt,
      fact_rad_onc_activity_billing.other_technical_charge_amt,
      fact_rad_onc_activity_billing.other_global_charge_amt,
      fact_rad_onc_activity_billing.forecast_charge_amt,
      fact_rad_onc_activity_billing.actual_charge_amt,
      fact_rad_onc_activity_billing.activity_cost_amt,
      fact_rad_onc_activity_billing.activity_billing_code_text,
      fact_rad_onc_activity_billing.service_start_date_time,
      fact_rad_onc_activity_billing.service_end_date_time,
      fact_rad_onc_activity_billing.complete_date_time,
      fact_rad_onc_activity_billing.export_date_time,
      fact_rad_onc_activity_billing.mark_complete_date_time,
      fact_rad_onc_activity_billing.credit_export_date_time,
      fact_rad_onc_activity_billing.credit_date_time,
      fact_rad_onc_activity_billing.credit_note_text,
      fact_rad_onc_activity_billing.modifier_code_text,
      fact_rad_onc_activity_billing.credit_amt,
      fact_rad_onc_activity_billing.scheduled_ind,
      fact_rad_onc_activity_billing.object_status_ind,
      fact_rad_onc_activity_billing.log_id,
      fact_rad_onc_activity_billing.run_id,
      fact_rad_onc_activity_billing.source_system_code,
      fact_rad_onc_activity_billing.dw_last_update_date_time
    FROM
      {{ params.param_cr_core_dataset_name }}.fact_rad_onc_activity_billing
  ;
