SELECT CONCAT(SUM(TOT_COUNT)) AS SOURCE_STRING
FROM
 (SELECT COUNT(*) AS TOT_COUNT
 FROM EDWCR_Staging.CR_PATIENT_TREATMENT_stg
 UNION ALL SELECT COUNT(*) AS TOT_COUNT
 FROM EDWCR_Staging.CR_PATIENT_TREATMENT_STG1)X