SELECT 'J_EP_Remittance_Service_HCPCS_Modifier' || ',' || CAST(COUNT(*) AS VARCHAR(20)) || ',' as Source_String from
( 
SELECT  Service_GUID AS SERVICE_GUID, 'A' AS HCPCS_TYPE_IND, 3 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_1_Code3 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_1_Code3,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'A' AS HCPCS_TYPE_IND, 4 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_1_Code4 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_1_Code4,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'A' AS HCPCS_TYPE_IND, 5 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_1_Code5 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_1_Code5,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'A' AS HCPCS_TYPE_IND, 6 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_1_Code6 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_1_Code6,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'O' AS HCPCS_TYPE_IND, 3 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_6_Code3 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_6_Code3,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'O' AS HCPCS_TYPE_IND, 4 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_6_Code4 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_6_Code4,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'O' AS HCPCS_TYPE_IND, 5 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_6_Code5 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_6_Code5,'') IS NOT IN ('') 
UNION
SELECT  Service_GUID AS SERVICE_GUID, 'O' AS HCPCS_TYPE_IND, 6 AS HCPCS_MODIFIER_SEQ_NUM, Procedure_Modifier_6_Code6 AS HCPCS_MODIFIER_CODE,
'E' AS SOURCE_SYSTEM_CODE, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM EDWPBS_STAGING.Remittance_Service
where Coalesce(Procedure_Modifier_6_Code6,'') IS NOT IN ('')
) a
