SELECT 'j_ADA_Patient_Level_Detail' || ',' ||
coalesce(cast(trim(SUM (IHCH) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (INSFC15) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (INSFC99) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTUNINSUREDDISCOUNT) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALCHARITYEXPANSIONDISCOUNT) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (PLP) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTAL_DISCOUNTS) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (SECONDARYAGYUNINSUREDDISC) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (SECONDARYAGENCYCHARITYEXPANSIONDISCOUNT_INS) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (SEC_PLP) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (SECONDARY_AGENCY_DISCOUNTS)	)as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALNONSECONDARYUNINSUREDDISCOUNT) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALNONSECONDARYCHARITYEXPANSIONDISCOUNT) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTAL_NONSECONDARY_PAT_LIABILITY_PROTECTION_DISCOUNT) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALNONSECONDARYDISCOUNTS) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALSELFPAYAR) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (SECONDARYTOTACCTBAL) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALNONSECONDARYSELFPAYAR) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTALGROSSNONSECONDARYSELFPAYAR) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (TOTPATIENTDUE) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (DNFBSP) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (IHSP) )as varchar (20)),'0')|| ',' || 
coalesce(cast(trim(SUM (DNFBCH) )as varchar (20)),'0')|| ',' as Source_string
FROM(
SELECT    
	SUM(
CASE      WHEN PEOM.FINANCIAL_CLASS_CODE = 15
                AND       ((CAST ((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) > PEOM.RPTG_PERIOD)          
                OR          (PEOM.ACCOUNT_STATUS_CODE = 'UB' 
                AND       PEOM.DISCHARGE_DATE IS NOT NULL 
                AND       CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD  
                AND       
PEOM.TOTAL_ACCOUNT_BALANCE_AMT <> 0)) THEN PEOM.TOTAL_ACCOUNT_BALANCE_AMT 
ELSE       0 
END       ) AS DNFBCH --Discharged_Not_Final_Bill_Charity_Amt
,SUM(
CASE      WHEN ((PEOM.ACCOUNT_STATUS_CODE = 'UB' 
                AND       SUBSTR(PEOM.PATIENT_TYPE_CODE,2,1) <> 'P' 
                AND       PEOM.DISCHARGE_DATE IS NULL
                AND       PEOM.TOTAL_ACCOUNT_BALANCE_AMT <> 0) 
                OR          (PEOM.ACCOUNT_STATUS_CODE = 'UB' 
                AND       PEOM.UNBILL_PRE_ADMIT_IND = 'Y')) 
                AND       PEOM.FINANCIAL_CLASS_CODE = 15 
THEN PEOM.TOTAL_ACCOUNT_BALANCE_AMT 
ELSE       0 
END       ) AS  IHCH	--Inhouse_Charity_Amt
,SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS1 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS1 = 15      
THEN PEOM.PAYOR_BALANCE_AMT_INS1 
ELSE       0 
END       ) + 
SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS2 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS2 = 15      
THEN PEOM.PAYOR_BALANCE_AMT_INS2 
ELSE       0 
END       ) +
SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS3 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS3 = 15      
THEN PEOM.PAYOR_BALANCE_AMT_INS3 
ELSE       0 
END       ) AS INSFC15	--Insured_Charity_Amt
,SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS1 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS1 = 99      
THEN PEOM.PAYOR_BALANCE_AMT_INS1 
ELSE       0 
END       ) +
SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS2 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS2 = 99      
THEN PEOM.PAYOR_BALANCE_AMT_INS2 
ELSE       0 
END       ) +
SUM(
CASE      WHEN CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
                AND       PEOM.ACCOUNT_STATUS_CODE NOT IN ('UB', 'BD') 
                AND       PEOM.PAYOR_BALANCE_AMT_INS3 > 0 
                AND       PEOM.FINANCIAL_CLASS_CODE_INS3 = 99      
THEN PEOM.PAYOR_BALANCE_AMT_INS3 
ELSE       0 
END       ) AS INSFC99	--Insured_Self_Pay_Amt
,SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 
  AND CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
  AND PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
 AND  (PEOM.IPLAN_ID_INS1 IN ('09940','09941','09942','09943','09944',
                                '09945', '09946','09947','09948','09949')  
                AND       FINANCIAL_CLASS_CODE_INS1='99')---ADDED 9943 AND 9948
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS1 + PEOM.PAYOR_ADJUSTMENT_AMT_INS1
ELSE       0 
END       ) +
SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 
  AND CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
AND PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
 AND  (PEOM.IPLAN_ID_INS2 IN ('09940','09941','09942','09943','09944',
                                '09945', '09946','09947','09948','09949') 
                AND       FINANCIAL_CLASS_CODE_INS2='99') -----ADDED 9943 AND 9948
--AND FINANCIAL_CLASS_CODE='99'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS2 + PEOM.PAYOR_ADJUSTMENT_AMT_INS2
ELSE       0 
END       ) +
SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 
  AND CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
AND PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
 AND  (PEOM.IPLAN_ID_INS3 IN ('09940','09941','09942','09943','09944',
                                '09945', '09946','09947','09948','09949') 
                AND       FINANCIAL_CLASS_CODE_INS3='99') -----ADDED 9943 AND 9948
--AND FINANCIAL_CLASS_CODE='99'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS3 + PEOM.PAYOR_ADJUSTMENT_AMT_INS3
ELSE       0 
END       ) AS TOTUNINSUREDDISCOUNT	--Uninsured_Discount_Amt
,SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')             
                AND       CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
                AND       PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
                AND       (PEOM.IPLAN_ID_INS1 IN ('09927')   
                AND       FINANCIAL_CLASS_CODE_INS1='15')
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS1 + PEOM.PAYOR_ADJUSTMENT_AMT_INS1
ELSE       0 
END       ) +SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')             
                AND       CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
                AND       PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
                AND       (PEOM.IPLAN_ID_INS2 IN ('09927') 
                AND       FINANCIAL_CLASS_CODE_INS2='15') 
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS2 + PEOM.PAYOR_ADJUSTMENT_AMT_INS2
ELSE       0 
END       ) +
SUM(
CASE      WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')             
                AND       CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD 
                AND       PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 
                AND       (PEOM.IPLAN_ID_INS3 IN ('09927') 
                AND       FINANCIAL_CLASS_CODE_INS3='15') 
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS3 + PEOM.PAYOR_ADJUSTMENT_AMT_INS3
ELSE       0 
END       ) AS TOTALCHARITYEXPANSIONDISCOUNT	--Charity_Discount_Amt
,SUM(AR_PLP.AR_TRANSACTION_AMT) AS PLP	--Patient_Liab_Prot_Discount_Amt
,TOTUNINSUREDDISCOUNT+TOTALCHARITYEXPANSIONDISCOUNT+PLP AS  TOTAL_DISCOUNTS 	--Total_Discount_Amt
,COALESCE((SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	PEOM.IPLAN_ID_INS1 IN ('09940','09941','09942','09943','09944',
		'09945', '09946', '09947','09948','09949') 
--AND PEOM.COLLECTOR_ORG_CODE IN (858,859,860)	
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'    
	AND	FINANCIAL_CLASS_CODE_INS1='99'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS1 + PEOM.PAYOR_ADJUSTMENT_AMT_INS1
ELSE	0 
END	)+
SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	PEOM.IPLAN_ID_INS2 IN ('09940','09941','09942','09943','09944',
		'09945', '09946', '09947','09948','09949') 
--AND PEOM.COLLECTOR_ORG_CODE IN (858,859,860)	
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'    
	AND	FINANCIAL_CLASS_CODE_INS2='99'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS2 + PEOM.PAYOR_ADJUSTMENT_AMT_INS2
ELSE	0 
END	)+
SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB') 	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD 
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	PEOM.IPLAN_ID_INS3 IN ('09940','09941','09942','09943','09944',
		'09945', '09946', '09947','09948','09949') 
--AND PEOM.COLLECTOR_ORG_CODE IN (858,859,860)	
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'    
	AND	FINANCIAL_CLASS_CODE_INS3='99'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS3 + PEOM.PAYOR_ADJUSTMENT_AMT_INS3
ELSE	0 
END	)), 0.00) AS SECONDARYAGYUNINSUREDDISC	--Secn_Agcy_Unins_Discount_Amt
,COALESCE((SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD	
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	(PEOM.IPLAN_ID_INS1 IN ('09927')   
	AND	 FINANCIAL_CLASS_CODE_INS1='15')
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS1 + PEOM.PAYOR_ADJUSTMENT_AMT_INS1
ELSE	0 
END	)+
SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD	
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	(PEOM.IPLAN_ID_INS2 IN ('09927') 
	AND	 FINANCIAL_CLASS_CODE_INS2='15') 
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS2 + PEOM.PAYOR_ADJUSTMENT_AMT_INS2
ELSE	0 
END	)+
SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA', 'UB')	
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= RPTG_PERIOD	
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
	AND	(PEOM.IPLAN_ID_INS3 IN ('09927') 
	AND	FINANCIAL_CLASS_CODE_INS3='15') 
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'
THEN PEOM.PAYOR_CONTRACT_ALLOW_AMT_INS3 + PEOM.PAYOR_ADJUSTMENT_AMT_INS3
ELSE	0 
END	)), 00) AS	SECONDARYAGENCYCHARITYEXPANSIONDISCOUNT_INS	 	--Secn_Agcy_Charity_Discount_Amt
,SUM(AR_PLP_SEC.AR_TRANSACTION_AMT) AS 	SEC_PLP	--Secn_Agcy_Pat_Liab_Prot_Discount_Amt
 
  ,SECONDARYAGYUNINSUREDDISC+SECONDARYAGENCYCHARITYEXPANSIONDISCOUNT_INS+SEC_PLP AS SECONDARY_AGENCY_DISCOUNTS	--Total_Secn_Agcy_Discount_Amt
 
 ,COALESCE((TOTUNINSUREDDISCOUNT - SECONDARYAGYUNINSUREDDISC), 0.00) AS TOTALNONSECONDARYUNINSUREDDISCOUNT	--Non_Secn_Unins_Disc_Amt
 
 , COALESCE((TOTALCHARITYEXPANSIONDISCOUNT- SECONDARYAGENCYCHARITYEXPANSIONDISCOUNT_INS), 0.00) AS	TOTALNONSECONDARYCHARITYEXPANSIONDISCOUNT 	--Non_Secn_Charity_Discount_Amt
 
   ,COALESCE(PLP-SEC_PLP, 0.00) AS TOTAL_NONSECONDARY_PAT_LIABILITY_PROTECTION_DISCOUNT 	--Non_Secn_Patient_Liab_Prot_Discount_Amt	
 
 ,TOTALNONSECONDARYUNINSUREDDISCOUNT +TOTALNONSECONDARYCHARITYEXPANSIONDISCOUNT+TOTAL_NONSECONDARY_PAT_LIABILITY_PROTECTION_DISCOUNT AS  TOTALNONSECONDARYDISCOUNTS	-- Total_Non_Secn_Discount_Amt --ADA SPCA
 
 
 
 ,COALESCE((SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN ('AR','AX','CA') 
	AND	CAST ((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD	
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0	
--AND PEOM.COLLECTOR_ORG_CODE IN (858,859,860) 
	AND	PEOM.COLLECTOR_ORG_TYPE_CODE='S'
THEN PEOM.TOTAL_ACCOUNT_BALANCE_AMT 
ELSE	0 
END	)), 0.00) AS	SECONDARYTOTACCTBAL 	-- Secn_Agcy_Acct_Bal_Amt
	,SUM(
CASE	WHEN PEOM.ACCOUNT_STATUS_CODE IN('AR','AX','CA') 
	AND	CAST ((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <= PEOM.RPTG_PERIOD
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT > 0 THEN PEOM.PATIENT_BALANCE_AMT 
ELSE	0 
END	) AS TOTPATIENTDUE	--Total_Patient_Due_Amt
		,SUM(
CASE	WHEN ((CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) > PEOM.RPTG_PERIOD) 
	OR	(PEOM.ACCOUNT_STATUS_CODE = 'UB' 
	AND	PEOM.DISCHARGE_DATE IS NOT NULL 
	AND	CAST((PEOM.DISCHARGE_DATE (FORMAT 'YYYYMM')) AS CHAR(6)) <=PEOM.RPTG_PERIOD
	AND	TOTAL_ACCOUNT_BALANCE_AMT <> 0))	AND FINANCIAL_CLASS_CODE = 99 THEN TOTAL_ACCOUNT_BALANCE_AMT 
ELSE	0 
END	) AS 	DNFBSP	--Discharged_Not_Final_Bill_Self_Pay_Amt
,SUM(
CASE	WHEN PEOM.FINANCIAL_CLASS_CODE = 99 
	AND	((PEOM.ACCOUNT_STATUS_CODE = 'UB' 
	AND	SUBSTR(PEOM.PATIENT_TYPE_CODE,2,1) <> 'P' 
	AND	PEOM.DISCHARGE_DATE IS NULL	
	AND	PEOM.TOTAL_ACCOUNT_BALANCE_AMT <> 0) 
	OR	(PEOM.ACCOUNT_STATUS_CODE = 'UB' 
	AND	PEOM.UNBILL_PRE_ADMIT_IND = 'Y')) THEN PEOM.TOTAL_ACCOUNT_BALANCE_AMT 
ELSE	0 
END	) AS	IHSP	--Inhouse_Self_Pay_Amt
, COALESCE((TOTPATIENTDUE+DNFBSP+IHSP+DNFBCH+IHCH+INSFC15+INSFC99), 0.00) AS 	TOTALSELFPAYAR	-- Self_Pay_AR_Amt
, COALESCE((TOTALSELFPAYAR - SECONDARYTOTACCTBAL), 0.00)  AS	TOTALNONSECONDARYSELFPAYAR	--   Non_Secn_Self_Pay_AR_Amt
, TOTALNONSECONDARYSELFPAYAR+TOTALNONSECONDARYDISCOUNTS  AS 	TOTALGROSSNONSECONDARYSELFPAYAR	-- Gross_Non_Secn_Self_Pay_AR_Amt
FROM	EDWPF_BASE_VIEWS.PASS_EOM PEOM
INNER JOIN 
(
select * from EDWPBS_Base_VIEWS.FACILITY_DIMENSION_EOM fd where FD.SUMMARY_7_MEMBER_IND = 'Y' AND FD.COMPANY_CODE = 'H'
Union all 
select * from EDWPBS_Base_VIEWS.FACILITY_DIMENSION_EOM where coid in (select distinct coid from EDWPBS_STAGING.dim_esb_organization_HomeHealth_DND where coid is not null)
) F
	ON	F.UNIT_NUM = PEOM.UNIT_NUM
	
LEFT OUTER JOIN 
(
SELECT COID, PAT_ACCT_NUM, SUM(AR_TRANSACTION_AMT) AR_TRANSACTION_AMT FROM 
(
SELECT  A.COID, A.PAT_ACCT_NUM, SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN 
( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD =  CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )  AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
)  PA
ON PA.COID = A.COID
AND PA.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE 
TRANSACTION_TYPE_CODE IN ('4','5') AND --AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5)  AND
TRANSACTION_CODE IN ('784984','784985') AND IPLAN_ID IN ( 9929, 0) -- AND A.COID=34632
GROUP BY 1,2
UNION ALL
SELECT  A.COID,A.PAT_ACCT_NUM,  SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN 
( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD =  CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )   AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
)  PA
ON PA.COID = A.COID
AND PA.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE  
TRANSACTION_TYPE_CODE IN ('4','5') AND --AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5)  AND
TRANSACTION_CODE IN ('999999') AND IPLAN_ID = 9929  --AND A.COID=34632
GROUP BY 1,2 
UNION ALL
SELECT  A.COID,A.PAT_ACCT_NUM,  SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN 
( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD = CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )   AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
)  PA
ON PA.COID = A.COID
AND PA.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE  
TRANSACTION_TYPE_CODE IN ('4','5') --AND AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5) 
AND IPLAN_ID =9929 
AND   TRANSACTION_CODE IN('920972','920970','920980','920971', '920981', '920982')  -- AND A.COID=34632
GROUP BY 1,2 
) K
GROUP BY 1,2 
) AR_PLP
ON    AR_PLP.COID = PEOM.COID
AND AR_PLP.PAT_ACCT_NUM = PEOM.PAT_ACCT_NUM
LEFT OUTER JOIN 
(
SELECT COID, PAT_ACCT_NUM, SUM(AR_TRANSACTION_AMT) AR_TRANSACTION_AMT FROM 
(
SELECT  A.COID, A.PAT_ACCT_NUM, SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN 
( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD = CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )  AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
AND COLLECTOR_ORG_TYPE_CODE='S')  PE
ON PE.COID = A.COID
AND PE.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE 
TRANSACTION_TYPE_CODE IN ('4','5') AND  --AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5)  AND
TRANSACTION_CODE IN ('784984','784985') AND IPLAN_ID IN ( 9929, 0) 
GROUP BY 1,2
UNION ALL
SELECT  A.COID,A.PAT_ACCT_NUM,  SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN ( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD = CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )  AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
AND COLLECTOR_ORG_TYPE_CODE='S')  PE
ON PE.COID = A.COID
AND PE.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE  
TRANSACTION_TYPE_CODE IN ('4','5') AND   --AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5)  AND
TRANSACTION_CODE IN ('999999') AND IPLAN_ID = 9929 
GROUP BY 1,2 
UNION ALL
SELECT  A.COID,A.PAT_ACCT_NUM,  SUM(AR_TRANSACTION_AMT ) AS AR_TRANSACTION_AMT
--FROM EDWPF_VIEWS.AR_TRANSACTION A
FROM EDWPF_BASE_VIEWS.ar_transaction_MV A
JOIN ( SELECT * FROM EDWPF_BASE_VIEWS.PASS_EOM WHERE RPTG_PERIOD = CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) )  AND  TOTAL_ACCOUNT_BALANCE_AMT > 0
AND COLLECTOR_ORG_TYPE_CODE='S')  PE
ON PE.COID = A.COID
AND PE.PAT_ACCT_NUM = A.PAT_ACCT_NUM
WHERE  
TRANSACTION_TYPE_CODE IN ('4','5') --AND  AR_TRANSACTION_ENTER_DATE <  ( current_date - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE,-1)) + 5) 
AND       IPLAN_ID =9929 
AND       TRANSACTION_CODE IN('920972','920970','920980','920971', '920981', '920982')  
GROUP BY 1,2 
) K1
GROUP BY 1,2 
) AR_PLP_SEC
ON    AR_PLP_SEC.COID = PEOM.COID
AND AR_PLP_SEC.PAT_ACCT_NUM = PEOM.PAT_ACCT_NUM
WHERE    
PEOM.RPTG_PERIOD = CAST( ( ADD_MONTHS(CURRENT_DATE , -1) (FORMAT 'YYYYMM') ) AS CHAR(6) ) 
AND    LEFT(PEOM. PATIENT_TYPE_CODE,1) IN ('O', 'E', 'S', 'I')
--AND PEOM.COID IN (34222)
--AND F.SUMMARY_7_MEMBER_IND = 'Y'  AND F.COMPANY_CODE = 'H'
)Src