--Current Artiva Agency Data
SELECT
	CURRENT_DATE as Rptg_Date
	, 'AR1' AS DataSource
	, FAC.CSFAHOSPNUM as Unit_Num
	, ENC.HCENPTACCT as Pat_Acct_Num
	, ACC.HCACVENDID as Vendor_ID
	, ACC.HCACVEPLDTE as Placement_Date
	, ACC.HCACVEPLTIM as Placed_Time
	, ACC.HCACVEPLAMT as Placement_Amt
	,NULL as Recall_Reason_Code
	, NULL as Recall_Reason_Desc
	, ACC.HCACVERCLDTE as Recall_Date
	, ACC.HCACVERCLTIM as Recall_Time
	, 0 as Recall_Amt
	,'v_currtimestamp' as DW_Last_Update_Date_Time

FROM SQLUser.HCENCOUNTER ENC

LEFT JOIN SQLUser.HCACCOUNT ACC
	ON ENC.HCENID = ACC.HCACENCNTRID

LEFT JOIN SQLUser.HCFACILITY FAC
	ON ENC.HCENFACILITY = FAC.HCFAID
	
LEFT JOIN SQLUser.HCPAS PAS
	ON FAC.HCFAPASID = PAS.HCPSID
	
WHERE ACC.HCACVENDID IS NOT NULL
AND (ACC.HCACVEPLDTE = TODATE((CONVERT(INT,CURRENT_DATE))-1)--yesterday
	OR ACC.HCACVERCLDTE  = TODATE((CONVERT(INT,CURRENT_DATE))-1))--yesterda
	
UNION ALL

--Historical Artiva Agency Data
SELECT
	CURRENT_DATE as Rptg_Date
	,'AR1' AS DataSource
	, FAC.CSFAHOSPNUM as Unit_Num
	, ENC.HCENPTACCT as Pat_Acct_Num
	, PLC.HCACPHVEID as Vendor_ID
	, PLC.HCACPHPLDTE as Placement_Date
	, PLC.HCACPHPLTIM as Placed_Time
	, PLC.HCACPHPLAMT as Placement_Amt
	, REA.HCRRID as Recall_Reason_Code
	, REA.HCRRDESC as Recall_Reason_Desc
	, PLC.HCACPHRCLDTE as Recall_Date
	, PLC.HCACPHRCLTIM as Recall_Time
	, PLC.HCACPHRCLAMT as Recall_Amt
	,'v_currtimestamp' as DW_Last_Update_Date_Time

FROM SQLUser.HCENCOUNTER ENC

LEFT JOIN SQLUser.HCACPLHIST PLC
	ON ENC.HCENID = PLC.HCACPHENID
	
LEFT JOIN SQLUser.HCRCLREAS REA
	ON PLC.HCACPHRCLREAS = REA.HCRRID

LEFT JOIN SQLUser.HCFACILITY FAC
	ON ENC.HCENFACILITY = FAC.HCFAID
	
LEFT JOIN SQLUser.HCPAS PAS
	ON FAC.HCFAPASID = PAS.HCPSID

WHERE PLC.HCACPHVEID IS NOT NULL
AND (PLC.HCACPHPLDTE = TODATE((CONVERT(INT,CURRENT_DATE))-1)--yesterday
				OR PLC.HCACPHRCLDTE = TODATE((CONVERT(INT,CURRENT_DATE))-1))--yesterday