CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.cancer_abstraction_stg (
unique_message_id STRING
, abstraction_action STRING
, abstraction_action_date_time STRING
, abstraction_action_user STRING
, abstraction_changed_primary_site STRING
, abstraction_changed_primary_site_icdo3 STRING
, abstraction_date_time STRING
, abstraction_laterality STRING
, abstraction_laterality_code STRING
, abstraction_report_assigned_to_user_at STRING
, abstraction_topography STRING
, abstraction_topography_icdo3 STRING
, attending_physician STRING
, coid STRING
, document_completion_status STRING
, document_type_identifier STRING
, document_type_name_of_coding_sys STRING
, document_type_text STRING
, etl_firstinsert_datetime STRING
, facility_mnemonic STRING
, ingestion_date_time STRING
, meditech_network_id STRING
, message_created_datetime STRING
, message_event_type STRING
, message_flag STRING
, message_origin_or_requested_date_time STRING
, message_signed_or_observation_date_time STRING
, message_txt STRING
, message_type STRING
, model_predicted_primary_site STRING
, model_predicted_primary_site_icdo3 STRING
, note_type STRING
, patient_account_number STRING
, patient_address_1 STRING
, patient_address_2 STRING
, patient_admission_date STRING
, patient_city STRING
, patient_discharge_date STRING
, patient_dob STRING
, patient_first_name STRING
, patient_gender STRING
, patient_last_name STRING
, patient_mrn STRING
, patient_state STRING
, patient_type_status STRING
, patient_urn STRING
, patient_zip_code STRING
, pcp_phone STRING
, primary_care_physician STRING
, provider_author STRING
, provider_author_degree STRING
, provider_author_first_name STRING
, provider_author_last_name STRING
, provider_author_middle_name STRING
, provider_author_prefix STRING
, provider_author_suffix STRING
, report_assigned_to_user_at STRING
, sarcoma_predicted STRING
, sarcoma_submitted STRING
, sarcoma_suggested STRING
, second_primary_site STRING
, second_primary_site_icdo3 STRING
, site_and_associated_model_output_score STRING
, social_security_number STRING
, submitted_primary_site STRING
, submitted_primary_site_icdo3 STRING
, suggested_primary_site STRING
, suggested_primary_site_icdo3 STRING
, transition_of_care STRING
, tumor_type_benign_brain STRING
, tumor_type_met_to_brain_neuro STRING
, tumor_type_primary_site STRING
, user_name STRING
, user_action STRING
, user_action_criticality STRING
, user_action_date_time STRING
, dw_last_update_date_time DATETIME
)
  ;
