CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.cr_patient_tumor_stg (
tumorid INT64
, patientid INT64
, grade STRING
, casestatflag STRING
, primarysite STRING
, primsitesubcode STRING
, mstdefchemosumm STRING
, mstdefdxstagesumm STRING
, mstdefhormsumm STRING
, mstdefimmunosumm STRING
, mstdefmarginssumm STRING
, mstdefpallsumm STRING
, mstdefrtboost STRING
, mstdefrthosp STRING
, mstdefrtloc STRING
, reasonnochemo STRING
, reasonnohormone STRING
, reasonnoimmuno STRING
, reasonnorad STRING
, mstdefsurgprimsumm STRING
, chemosrgseq STRING
, mstdefrtmod STRING
, mstdefrtvol STRING
, mstdefscopelnsumm STRING
, surgapphosp STRING
, mstdefsurgprimhosp STRING
, cs_tumsize STRING
, mstdefchemodt DATE
, mstdefrtdt DATE
, mstdefimmunodt DATE
, mstdefhormdt DATE
, mstdefrtstopdt DATE
, elapsed1stsurgchem INT64
, elapsed1stsurglstcont INT64
, elapsedchemo1stsurg INT64
, lengthtodtchemo INT64
, lengthtodthorm INT64
, lengthtodtimmuno INT64
, lengthtodtmstdefsurg INT64
, lengthtodtradstarted INT64
, lengthtodttrnsplnt INT64
, lengthtofirsttx INT64
, dtfirstsurg DATE
, elapsedrtstartend INT64
, tumorsizesumm STRING
, dtmstdefsurg DATE
, dateadmis DATE
, survival INT64
, bestcssummstage STRING
, bestcstnmstage STRING
, t14udf116 STRING
, t14udf117 STRING
, t16udf118 STRING
, abstractor STRING
, classcase STRING
, seqprim STRING
, manage_md STRING
, medoncmd STRING
, radoncmd STRING
, primsurgeon STRING
, source_system_code STRING NOT NULL
, dw_last_update_date_time DATETIME NOT NULL
, histology STRING
, cs_ss_factor_1_num_code STRING
, cs_ss_factor_2_num_code STRING
, cs_ss_factor_15_num_code STRING
, cs_ss_factor_16_num_code STRING
, cs_ss_factor_22_num_code STRING
, cs_ss_factor_23_num_code STRING
, cs_ss_factor_25_num_code STRING
, dtca_conf DATE
, presca_conf STRING
, dt2ca_conf DATE
, pres2ca_conf STRING
, dt3ca_conf DATE
, pres3ca_conf STRING
)
  ;
