CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.factactivitybilling_stg (
dimsiteid NUMERIC(29,0)
, factactivitybillingid NUMERIC(29,0)
, dimprocedurecodeid NUMERIC(29,0)
, dimactivityid NUMERIC(29,0)
, dimlkpid_activitycategory NUMERIC(29,0)
, dimresourceid_activity NUMERIC(29,0)
, dimactivitytransactionid NUMERIC(29,0)
, dimpatientid NUMERIC(29,0)
, dimcourseid NUMERIC(29,0)
, dimhospitaldepartmentid NUMERIC(29,0)
, dimdoctorid NUMERIC(29,0)
, dimdoctid_attdoncologist NUMERIC(29,0)
, dimuserid_markcompletedby NUMERIC(29,0)
, dimuserid_exportedby NUMERIC(29,0)
, dimuserid_chargewaivedby NUMERIC(29,0)
, dimuserid_reviewedby NUMERIC(29,0)
, dimuserid_creditedby NUMERIC(29,0)
, dimdateid_fromdtofservice NUMERIC(29,0)
, dimdateid_todateofservice NUMERIC(29,0)
, dimdateid_completeddttime NUMERIC(29,0)
, dimdateid_exporteddatetime NUMERIC(29,0)
, dimdateid_markcompletdttime NUMERIC(29,0)
, dimdateid_crdtexpdttime NUMERIC(29,0)
, dimdateid_crediteddatetime NUMERIC(29,0)
, dimdateid_tempcreationdate NUMERIC(29,0)
, primaryglobalcharge NUMERIC(19,4)
, primarytechnicalcharge NUMERIC(19,4)
, primaryprofessionalcharge NUMERIC(19,4)
, otherprofessionalcharge NUMERIC(19,4)
, othertechnicalcharge NUMERIC(19,4)
, otherglobalcharge NUMERIC(19,4)
, chargeforecast NUMERIC(19,4)
, actualcharge NUMERIC(19,4)
, professionalrvu STRING
, globalrvu STRING
, technicalrvu STRING
, activitycost NUMERIC(19,4)
, workunit STRING
, accountbillingcode STRING
, fromdateofservice STRING
, todateofservice STRING
, completeddatetime STRING
, exporteddatetime STRING
, markedcompleteddatetime STRING
, creditexporteddatetime STRING
, crediteddatetime STRING
, creditnote STRING
, allmodifiercodes STRING
, creditamount STRING
, isscheduled STRING
, diagnosisid STRING
, objectstatus STRING
, activityinstance_objstatus STRING
, actinstproccode_objstatus STRING
, activitycapturerevcount STRING
, activityinstancerevcount STRING
, activitycodemdrevcount STRING
, procedurecoderevcount STRING
, accountbillingcoderevcount STRING
, actinstproccoderevcount STRING
, creditrevcount STRING
, templateid STRING
, templaterevcount STRING
, templatecreationdate STRING
, patientstatus STRING
, inpatientflag STRING
, ctractivityinstanceser STRING
, ctrtemplateser STRING
, ctrtemplatecycleser STRING
, ctractivitycaptureser STRING
, ctractinstproccodeser STRING
, ctraccountbillingcodeser STRING
, ctrcreditser STRING
, ctrdiagnosisser STRING
, ctractivitycategoryser STRING
, ctrresourceser_activity STRING
, ctrattendingoncologistser STRING
, logid STRING
, runid STRING
, dimuserid_completedbyuser STRING
, billeventdescription STRING
, dimlookupid_billeventtype STRING
, billeventunits STRING
, billeventstatus STRING
, billinginventoryid STRING
, billitemdescription STRING
, dimdrugid STRING
, billingaccountid STRING
, diminstitutelocationid STRING
, overrideindicator STRING
, dimdoctorid_referring STRING
, dosewastageamount STRING
, dimlkpid_dosewastageunit STRING
, dimdiagnosiscodeid STRING
, ctrbill_event_id STRING
, moroindicator STRING
, dimuserid_physician STRING
, dw_last_update_date_time DATETIME
)
  ;
