CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.facttreatmenthist_stg (
dimsiteid NUMERIC(29,0)
, facttreatmenthistoryid NUMERIC(29,0)
, dimpatientid NUMERIC(29,0)
, dimcourseid NUMERIC(29,0)
, dimlkpid_treatmentintenttype NUMERIC(29,0)
, dimuserid_completedbyuser NUMERIC(29,0)
, dimlookupid_clinicalstatus NUMERIC(29,0)
, dimplanid NUMERIC(29,0)
, dimlookupid_planstatus NUMERIC(29,0)
, dimuserid_statususer NUMERIC(29,0)
, dimlookupid_fieldtechnique NUMERIC(29,0)
, dimfieldid NUMERIC(29,0)
, dimplannedaddonid1 NUMERIC(29,0)
, dimplannedaddonid2 NUMERIC(29,0)
, dimplannedaddonid3 NUMERIC(29,0)
, dimplannedaddonid4 NUMERIC(29,0)
, dimplannedaddonid5 NUMERIC(29,0)
, dimplanmachineid NUMERIC(29,0)
, dimlookupid_technique NUMERIC(29,0)
, dimlookupid_techniquelabel NUMERIC(29,0)
, dimlkpid_treatmentdeliverytyp NUMERIC(29,0)
, dimactualmachineid NUMERIC(29,0)
, dimtreatmenttransactionid NUMERIC(29,0)
, dimuserid_username1 NUMERIC(29,0)
, dimuserid_username2 NUMERIC(29,0)
, dimuserid_username3 NUMERIC(29,0)
, dimactualaddonid1 NUMERIC(29,0)
, dimactualaddonid2 NUMERIC(29,0)
, dimactualaddonid3 NUMERIC(29,0)
, dimactualaddonid4 NUMERIC(29,0)
, dimactualaddonid5 NUMERIC(29,0)
, dimactualaddonid6 NUMERIC(29,0)
, dimactualaddonid7 NUMERIC(29,0)
, dimactualaddonid8 NUMERIC(29,0)
, dimactualaddonid9 NUMERIC(29,0)
, dimactualaddonid10 NUMERIC(29,0)
, dimuserid_approvaluser NUMERIC(29,0)
, dimuserid_machineauthoriz NUMERIC(29,0)
, dimplannedenergyid NUMERIC(29,0)
, dimactualenergyid NUMERIC(29,0)
, dimdateid_coursecompdttime NUMERIC(29,0)
, dimdateid_firsttreatmentdate NUMERIC(29,0)
, dimdateid_lasttreatmentdate NUMERIC(29,0)
, dimdateid_planapprstatusdate NUMERIC(29,0)
, dimdateid_authorizationdate NUMERIC(29,0)
, dimdateid_correctiondatetime NUMERIC(29,0)
, dimdateid_treatmentendtime NUMERIC(29,0)
, dimdateid_treatmentrcddttime NUMERIC(29,0)
, dimdateid_treatmentstarttime NUMERIC(29,0)
, dimdateid_breakpointdate NUMERIC(29,0)
, completeddatetime STRING
, firsttreatmentdate STRING
, lasttreatmentdate STRING
, statusdate STRING
, isactive NUMERIC(29,0)
, isbrachy NUMERIC(29,0)
, planneddoserate NUMERIC(29,0)
, plannedmu STRING
, authorizationdate STRING
, dimuserid_authorizedby NUMERIC(29,0)
, overrideparameters STRING
, plannedfielddose STRING
, deliveredfielddose STRING
, correctiondatetime STRING
, refpointid STRING
, refpointname STRING
, dosecorrectioncomment STRING
, coursedosedelivered STRING
, coursedoseplanned STRING
, coursedoseremaining STRING
, othercoursedosedelivered STRING
, dosecorrection STRING
, totaldoselimit STRING
, dailydoselimit STRING
, sessiondoselimit STRING
, breakpointdate STRING
, breakpointdose STRING
, breakpointnote STRING
, breakpointnum NUMERIC(29,0)
, notxsessionremaining NUMERIC(29,0)
, notxsessionplanned NUMERIC(29,0)
, notxsessiondelivered NUMERIC(29,0)
, primaryflag NUMERIC(29,0)
, fractionsdelivered NUMERIC(29,0)
, fractionsplanned NUMERIC(29,0)
, fractionsremaining NUMERIC(29,0)
, doseperfraction STRING
, dosedelivered STRING
, doseremaininginfraction STRING
, runningpartial STRING
, dosepredictedmax STRING
, dosepredictedmin STRING
, dosepredicted STRING
, dosepredictedinothercourses STRING
, doseremaining STRING
, doseremainingmax STRING
, doseremainingmin STRING
, actualdoserate NUMERIC(29,0)
, treatmenttime STRING
, deliveredmu STRING
, dosedeliveredtoprimaryrefpt STRING
, pfflag STRING
, pfmusubflag STRING
, piflag STRING
, treatmentendtime STRING
, treatmentrecorddatetime STRING
, treatmentstarttime STRING
, approvaldate STRING
, correlatedeventnumber NUMERIC(29,0)
, eventnumber NUMERIC(29,0)
, fieldmuactual STRING
, fieldstatus STRING
, intendednumofpaintings NUMERIC(29,0)
, isimage NUMERIC(29,0)
, nofractions NUMERIC(29,0)
, nooffractions NUMERIC(29,0)
, noofimage NUMERIC(29,0)
, printflag NUMERIC(29,0)
, radiationnumber NUMERIC(29,0)
, recordstatus STRING
, rvflag NUMERIC(8,0)
, terminationstatus STRING
, distalendenergy STRING
, dosedelta STRING
, fractionnumber NUMERIC(29,0)
, dosedeliveredperfraction STRING
, lastchartqadate STRING
, ctrchartqatreatmentser NUMERIC(29,0)
, ctrphysicianintentser NUMERIC(29,0)
, ctrrefpointlogser NUMERIC(29,0)
, ctrdosecorrectionlogser NUMERIC(29,0)
, ctrtechniqueser NUMERIC(29,0)
, ctrpatientvolumeser NUMERIC(29,0)
, ctrrefpointser NUMERIC(29,0)
, ctrbreakpointser NUMERIC(29,0)
, ctrprescriptionser NUMERIC(29,0)
, treatmentdeliverytype STRING
, logid NUMERIC(29,0)
, runid NUMERIC(29,0)
, dw_last_update_date_time DATETIME
)
  ;
