CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.patient_heme_disease_assessment_stg (
patienthemefactid NUMERIC(29,0)
, patientdimid NUMERIC(29,0)
, tumortypedimid NUMERIC(29,0)
, diagnosisresultid NUMERIC(29,0)
, diagnosisdimid NUMERIC(29,0)
, facilitydimid NUMERIC(29,0)
, coid STRING
, navigatordimid NUMERIC(29,0)
, collectiondate STRING
, source STRING
, samplesourcetype STRING
, testtype STRING
, facilityname STRING
, comments STRING
, initialdiagnosis STRING
, diseasemonitoring STRING
, diseasestatus STRING
, treatementstatus STRING
, karyotype STRING
, cytogenetic STRING
, immunophenotype STRING
, othermolecularmarker STRING
, othermolecularmarkerresult STRING
, ihc STRING
, cbc_wbc STRING
, cbc_hgb STRING
, cbc_plt STRING
, cbc_anc STRING
, cbc_seg STRING
, cbc_bands STRING
, cbc_monocyte STRING
, cbc_blast STRING
, cellularity STRING
, cmp_creatinine STRING
, cmp_uricacid STRING
, cmp_ldh STRING
, cmp_totalprotein STRING
, cmp_albumiun STRING
, cmp_calcium STRING
, cmp_bilirubin STRING
, cmp_ast STRING
, cmp_alt STRING
, cmp_ntprobmpresults STRING
, cmp_troponinresults STRING
, betamicroglobulin STRING
, sflckappa STRING
, sflclambda STRING
, sflc_ratio STRING
, upepspep_mproteinresuls STRING
, meratio STRING
, mp_cebpa STRING
, mp_ckitresult STRING
, mp_dnmt3a STRING
, mp_flt3method STRING
, mp_flt3result STRING
, mp_kit STRING
, mp_npm1 STRING
, mp_othermolecularmarkers STRING
, csf_csfresults STRING
, upepspep_iferesults STRING
, bmplasmacell STRING
, bmday STRING
, fish_molecularmarkers STRING
, fish_philadelphiachromosome STRING
, fish_othermolecularmarkers STRING
, fish_molecularmarkerssign STRING
, hepatitis_heparesult STRING
, hepatitis_hepbresult STRING
, hepatitis_hepcresult STRING
, hivtest_hivresults STRING
, nodallocation STRING
, lymphnode_ihcresults STRING
, lymphnode_lymphnoderesults STRING
, immunoglobulins_iga STRING
, immunoglobulins_igd STRING
, immunoglobulins_ige STRING
, immunoglobulins_igg STRING
, immunoglobulins_igm STRING
, other_othersource STRING
, other_diseaseassessmenttest STRING
, other_result STRING
, hbsource STRING
, lastupdatedatetime STRING
)
  ;
