CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.stg_factpatientdiagnosis (
dimsiteid INT64
, factpatientdiagnosisid INT64
, dimpatientid INT64
, dimdiagnosiscodeid INT64
, dimicdositeid INT64
, dimcelltypeid INT64
, dimlookupid_diagnosisstatus INT64
, dimlookupid_ranking INT64
, dimlookupid_source INT64
, dimlookupid_historicdxflag INT64
, dimlookupid_cellcategory INT64
, dimlookupid_cellgrade INT64
, dimlookupid_laterality INT64
, dimlookupid_stage INT64
, dimlookupid_stagestatus INT64
, dimlookupid_erstatus INT64
, dimlookupid_prstatus INT64
, dimlookupid_her2neumethodtype INT64
, dimlookupid_her2neustatustype INT64
, dimlookupid_her2neumethod2type INT64
, dimlookupid_her2neustatus2type INT64
, dimlookupid_recurrence INT64
, dimlookupid_invasive INT64
, dimlookupid_confirmeddx INT64
, dimlookupid_diagnosistype INT64
, dimlookupid_dxmethodtype INT64
, dimlookupid_icdoversion INT64
, dimdxsiteid_bodysystem INT64
, dimdxsiteid INT64
, dimdateid_diagnosisstatusdate INT64
, dxdate STRING
, diagnosisstatusdate STRING
, diagnosisdescription STRING
, clinicaldescription STRING
, historicdetails STRING
, comments STRING
, pathologycomments STRING
, behaviour STRING
, distantmets STRING
, nodes INT64
, nodespositive INT64
, size_size STRING
, stagecriteria STRING
, stagebasis STRING
, stagescheme STRING
, sphase INT64
, methoddescription STRING
, corestaken INT64
, corespositive INT64
, gleasonprimary INT64
, gleasonsecondary INT64
, gleasontotal INT64
, gleasonscore INT64
, objectstatus STRING
, histologycode STRING
, histologytablename STRING
, tstage STRING
, nstage STRING
, mstage STRING
, summarystage STRING
, datestamp STRING
, ctrdiagnosisid INT64
, ctrdiagnosisser INT64
, logid INT64
, runid INT64
, currententry STRING
, cancerdescription STRING
, cancerstatus STRING
, lesiondescription STRING
, lesionorder INT64
, lesiondimention INT64
, dimlookupid_lesionmeasurable INT64
, primarycancerid INT64
, primarydiagnosisid INT64
, datestaged STRING
, ctrpt_stage_id INT64
, dimdxsiteid_primarycancersite INT64
, patientcancerstagecreatedby STRING
, patientcancerstagedatetime STRING
, ptdxonsetdate STRING
, ptdxlastmodifieddatetime STRING
, ptdxcncrlastmodifieddatetime STRING
, dxsitedatetime STRING
, dw_last_update_date_time DATETIME
)
  ;
