CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.stg_dimplan (
dimsiteid STRING
, dimplanid STRING
, dimcourseid STRING
, dimlookupid_planstatus STRING
, planuid STRING
, nofractions STRING
, treatmentorder STRING
, plansetupid STRING
, plansetupname STRING
, treatmentorientation STRING
, treatmenttechnique STRING
, volumeid STRING
, primaryrefpointid STRING
, primaryrefpointdelivered STRING
, primaryrefpointplanned STRING
, primaryrefpointremaining STRING
, primaryrefpointdeliveredsum STRING
, primaryrefpointplannedsum STRING
, primaryrefpointremainingsum STRING
, nofractionsplanned STRING
, nofractionsremaining STRING
, nofractionstreated STRING
, nofractionsplannedsum STRING
, nofractionsremainingsum STRING
, nofractionstreatedsum STRING
, nosessionremaining STRING
, energymode STRING
, fractionid STRING
, startdelay STRING
, fractionpatterndigitsperday STRING
, fractionpattern STRING
, predecessorid STRING
, planrevision STRING
, nosessionplanned STRING
, plancomment STRING
, planintent STRING
, age STRING
, relationshiptype STRING
, relatedplanuid STRING
, statususername STRING
, hstryusername STRING
, hstrydatetime STRING
, creationdate STRING
, firstdayoftreatment STRING
, lastdayoftreatment STRING
, imrtorrapidarc STRING
, ctrplansetupser STRING
, ctrrtplanser STRING
, ctrrelatedrtplanser STRING
, ctrplansopclassser STRING
, ctrrelatedplansopclassser STRING
, ctrplanrelationshipser STRING
, ctrprimaryrefpointser STRING
, ctrfirstrtplanser STRING
, rttreatmenttechnique STRING
, logid STRING
, runid STRING
, dw_last_update_date_time DATETIME
)
  ;
