CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.stg_dimpatient (
dimsiteid INT64
, dimpatientid INT64
, patientid STRING
, patientid2 STRING
, patientfirstname STRING
, patientlastname STRING
, patientfullname STRING
, patienthonorific STRING
, patientdateofbirth STRING
, patienttype STRING
, patientssn STRING
, patientlanguage STRING
, patientaddressline1 STRING
, patientaddressline2 STRING
, patientfulladdress STRING
, patientaddresscomment STRING
, patienthomephone STRING
, patientworkphone STRING
, patientmobilephone STRING
, patientpagernumber STRING
, patientemailaddress STRING
, patientlocation STRING
, patientinoutstatus STRING
, patientdeathstatus STRING
, patientdeathcause STRING
, patientdeathdate STRING
, clinicaltrial STRING
, patientcomment STRING
, patientnotes STRING
, hstrydatetime STRING
, hstryusername STRING
, patientroomnumber STRING
, patemergencycontactaddress STRING
, patemergencycontactcomment STRING
, patemergencycontactentrusted INT64
, patemergencycontactfullname STRING
, patemergencycontacthomephone STRING
, patemergencycontactmobilephone STRING
, patemergencycontactworkphone STRING
, patemergencycontactrelationshp STRING
, transportationname STRING
, transportationphone STRING
, noalcoholuseperweek INT64
, nopacksperday NUMERIC(2,1)
, noyearsquitalcohol INT64
, noyearsquitsmoking INT64
, noyearsactivesmoker INT64
, hazardmaterialcontactindicator STRING
, alcoholusestatus STRING
, smokingusestatus STRING
, ctrpatientsocialhistoryid INT64
, ctrpatientser INT64
, ctrpt_id STRING
, ctrhospitalser INT64
, ctrprimaryoncologistser INT64
, ctrprimaryreferringphysicanser INT64
, logid INT64
, runid INT64
, patientmiddlename STRING
, universalpatientid STRING
, patientmaritalstatus STRING
, patientoccupation STRING
, patientpresentemployername STRING
, mothername STRING
, fathername STRING
, ethnicity STRING
, religion STRING
, mothermaidenname STRING
, healthcaredpoa STRING
, donotresuscitate STRING
, donothospitalize STRING
, haslivingwill STRING
, isautopsyrequested STRING
, feedingrestrictions STRING
, isorgandonor STRING
, birthplace STRING
, medicationrestrictions STRING
, treatmentrestrictions STRING
, ismotestpatient STRING
, smokingsincedate STRING
, smokingquitdate STRING
, alcoholquitdate STRING
, dw_last_update_date_time DATETIME
)
  ;
