CREATE OR REPLACE TABLE {{ params.param_cr_stage_dataset_name }}.stg_dimtreatmenttransaction (
dimsiteid INT64
, dimtreatmenttransactionid INT64
, dimfieldid INT64
, dimplanid INT64
, dimcourseid INT64
, couchlat STRING
, couchlatoverrideflag STRING
, couchlng STRING
, couchlngoverrideflag STRING
, couchvrt STRING
, couchvrtoverrideflag STRING
, historynote STRING
, energymodeoverrideflag STRING
, metersetoverrideflag STRING
, patsuppitchoverrideflag STRING
, patsuprolloverrideflag STRING
, patsupportpitchangle STRING
, patsupportrollangle STRING
, patientsupportangle STRING
, patientsupportangleoverflag STRING
, ssd STRING
, ssdoverrideflag STRING
, actualcollmode STRING
, actualgantryrtnext STRING
, actualwedgedose STRING
, beamcurrentmodulationid STRING
, beammodifiersset STRING
, beamoffcode STRING
, collmodeoverrideflag STRING
, collrtn STRING
, collrtnoverrideflag STRING
, collx1 STRING
, collx1overrideflag STRING
, collx2 STRING
, collx2overrideflag STRING
, colly1 STRING
, colly1overrideflag STRING
, colly2 STRING
, colly2overrideflag STRING
, couchcorrectionlat STRING
, couchcorrectionlng STRING
, couchcorrectionvrt STRING
, hstrydatetime STRING
, hstrytaskname STRING
, hstryusername STRING
, lastcorrelatedeventnumber STRING
, lasteventnumber STRING
, lastfractionnumber STRING
, lastfractionnumbercalc STRING
, machoverrideflag STRING
, mupdeg STRING
, mupdegoverrideflag STRING
, numofpaintoverrideflag STRING
, offplaneangle STRING
, overrideflag STRING
, radiationhstrytype STRING
, snoutposition STRING
, snoutposoverrideflag STRING
, sobpwidth STRING
, stopangle STRING
, structuresetuid STRING
, tabletopeccangleoverflag STRING
, tabletopeccentricangle STRING
, treatmentrecorduid STRING
, treatmenttimeoverrideflag STRING
, wedgeangle STRING
, wedgeangle2 STRING
, wedgedirection STRING
, wedgedirection2 STRING
, wedgedoseoverrideflag STRING
, wedgenumber1 STRING
, wedgenumber2 STRING
, fieldsetupnote STRING
, psacorrection STRING
, seriesser STRING
, rtplanage STRING
, filename STRING
, fixlightazimuthangle STRING
, fixlightpolarpos STRING
, doserateoverrideflag STRING
, gantryrtn STRING
, gantryrtndirection STRING
, machinenote STRING
, gantryrtnoverrideflag STRING
, ctrradiationhstryser STRING
, ctrtreatmentrecordser STRING
, ctrtreatmentrecordsopclassser STRING
, logid INT64
, runid INT64
, dw_last_update_date_time DATETIME
)
  ;
