Select 'A' as STACK, GLX.CO_ID, GLX.PAT_NO, GLX.ENTERED_TS,
GLX.GL_SRC,
GLX.GL_PROC_TYPE,
GLX.GL_ACCOUNT,
GLX.GL_PROC_AMT,
GLX.GL_SERV_DT,
GLX.PROC_CODE,
GLX.GL_SOURCE,
GLX.FACTOR,
GLX.PAT_TYPE,
GLX.DEPT,
GLX.FIN_CLASS,
GLX.GL_ADJUST_IND,
GLX.FOREIGN_FAC_ID,
GLX.FOREIGN_DEPT,
GLX.FOREIGN_PAT_TYPE,
GLX.FOREIGN_GL_COM,
GLX.FOREIGN_FIN_CLASS,
GLX.PROCESS_IND,
GLX.PEDATE,
ACC.SUB_UNIT_NO,
'v_currtimestamp' as dw_last_update_date_time
FROM A.BRBGLX as GLX
left outer join A.BRBACC as ACC
on GLX.STACK = ACC.STACK
and GLX.CO_ID = ACC.CO_ID
and GLX.PAT_NO = ACC.PAT_NO
where DATE(GLX.ENTERED_TS) =DATE(CURRENT TIMESTAMP) -1 DAY