--AUDIT/ACCOUNT DETAIL LEVEL FOR POWERBI     			(UPDATED 10/28/2020)
SELECT
    (CASE   --CONSOLIDATE LIFEPOINT/CLIENT INTO CLIENT TO DIFFERENTIATE HCA AND ICS AT THE PASID LEVEL
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-NAS' THEN 'CLIENT-NAS'
        WHEN HCFACILITY.HCFAPASID = 'LIFEPOINT-OPK' THEN 'CLIENT-OPK'
        WHEN HCFACILITY.HCFAPASID = 'LIFEPOINT-RIC' THEN 'CLIENT-RIC'
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' THEN 'DAL/SAN'
        WHEN HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS CSUAAFAPASID
    , (CASE
        WHEN HCFACILITY.HCFAPASID = 'CAPELLA' OR HCFACILITY.HCFAPASID = 'CLIENT-NAS' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-NAS' THEN 'NASHVILLE'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-OPK' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-OPK' THEN 'ORANGEPARK'
        WHEN HCFACILITY.HCFAPASID = 'CLIENT-RIC' OR HCFACILITY.HCFAPASID = 'LIFEPOINT-RIC' THEN 'RICHMOND'
        WHEN HCFACILITY.HCFAPASID = 'DALLAS' THEN 'DAL/SAN'
        WHEN HCFACILITY.HCFAPASID = 'SANANTONIO' THEN 'DAL/SAN'
        ELSE HCFACILITY.HCFAPASID END) AS SSC
    , STUSERAUDIT.CSUAMONTHLYREVIEWID, STUSERAUDIT.STUAMONTH, STUSERAUDIT.STUAYEAR, STUSERAUDIT.HCUAREVIEWPERIOD
    , STUSERAUDIT.STUARVWSTART, STUSERAUDIT.STUARVWEND, STUSERAUDITACCT.STUAAUSERID, STUSERAUDIT.STUAID, 
	STUSERAUDITACCT.STUAAAUDITID, STUSERAUDITACCT.STUAAID, STUSERAUDITACCT.CSUAASTATUS --, STUSER.UAFULLNAME, STUSER.UASUPER, SUPERVISOR.UAFULLNAME--, STUAAAUDITID, STUSERAUDITACCT.STUAAID
    , STUSERAUDITACCT.CSUAAFAHOSPNUM AS UNIT
    , STUSERAUDITACCT.CSUAAENPTACCT AS ENPATACCT
    , STUSERAUDITACCT.CSUAAPYIPLAN AS IPLAN
    , HCPAYER.HCPYFINCLASS AS HCPYFINCLASS
    , STUSERAUDITACCT.STUAAEARNEDPOINTS, STUSERAUDITACCT.STUAAPOSSIBLEPOINTS, ROUND(STUSERAUDITACCT.STUAASCORE,2) AS STUAASCORE, STUSERAUDITACCT.STUAACREATEDATE, STUSERAUDITACCT.STUAACOMPLETEFLAG, STUSERAUDITACCT.STUAACOMPLETEDATE
FROM ((SQLUser.STUSERAUDITACCT STUSERAUDITACCT LEFT OUTER JOIN SQLUser.STUSERAUDIT STUSERAUDIT ON STUSERAUDITACCT.STUAAAUDITID = STUSERAUDIT.STUAID)
        LEFT OUTER JOIN SQLUser.HCPAYER HCPAYER ON STUSERAUDITACCT.CSUAAPAYERID = HCPAYER.HCPYID)
    , SQLUser.HCFACILITY HCFACILITY
WHERE STUSERAUDITACCT.CSUAAFAHOSPNUM = HCFACILITY.CSFAHOSPNUM AND STUSERAUDIT.STUARVWEND >= '2020-11-01'
ORDER BY STUSERAUDITACCT.STUAAAUDITID