#   SCRIPT NAME     - HDW_Enwisen_Ref_Email_To_HR_Status.sql                  		#
#   Job NAME         - J_HDW_Enwisen_Ref_Onboarding_Tour_Status                           	#
#   TARGET TABLE    - EDWHR.REF_ONBOARDING_TOUR_STATUS                      			#
#   Developer   	- Syntel                                                              # 
#   Version 		- 1.0 - Initial RELEASE                     				#
#   Description 	- The SCRIPT loads the TARGET with Upsert					#
############################################################################################

bteq << EOF > $1;

.RUN FILE $LOGONDIR/HDW_AC;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

SET QUERY_BAND = 'App=HR_Enwisen_ETL; Job=J_HDW_Enwisen_Ref_Onboarding_Tour_Status;' FOR SESSION;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

/*  Merge the data into EDWHR.REF_ONBOARDING_TOUR_STATUS table  */

MERGE INTO EDWHR.REF_ONBOARDING_TOUR_STATUS TGT
USING (
SELECT
CASE  WHEN TGT.TOUR_STATUS_ID IS  NOT NULL THEN TGT.TOUR_STATUS_ID ELSE
((SELECT  COALESCE(MAX(TOUR_STATUS_ID ),0)  FROM  EDWHR_BASE_VIEWS.REF_ONBOARDING_TOUR_STATUS)
+ ROW_NUMBER() OVER ( ORDER BY TOUR_STATUS_ID  NULLS FIRST,STG.TOUR_STATUS_TEXT)) END AS TOUR_STATUS_ID,
STG.TOUR_STATUS_TEXT AS TOUR_STATUS_TEXT,
STG.SOURCE_SYSTEM_CODE,
CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM
(
SELECT  
TRIM(TOURSTATUS) AS TOUR_STATUS_TEXT,
'W'  AS  SOURCE_SYSTEM_CODE
FROM  EDWHR_STAGING.ENWISEN_AUDIT
WHERE TRIM(TOURSTATUS) IS NOT NULL
GROUP BY 1,2
UNION ALL
SELECT  
TRIM(STATUS_STATE) AS TOUR_STATUS_TEXT,
'B'  AS  SOURCE_SYSTEM_CODE
FROM  EDWHR_STAGING.ATS_RESOURCETRANSITION_BCT_STG
WHERE TRIM(STATUS_STATE) IS NOT NULL
GROUP BY 1,2
)STG

LEFT JOIN EDWHR_BASE_VIEWS.REF_ONBOARDING_TOUR_STATUS TGT
ON TGT.TOUR_STATUS_TEXT = STG.TOUR_STATUS_TEXT
AND TGT.SOURCE_SYSTEM_CODE= STG.SOURCE_SYSTEM_CODE
) SRC
ON TGT.TOUR_STATUS_ID = SRC.TOUR_STATUS_ID
AND TGT.SOURCE_SYSTEM_CODE= SRC.SOURCE_SYSTEM_CODE

WHEN MATCHED THEN 
UPDATE SET 
DW_LAST_UPDATE_DATE_TIME=SRC.DW_LAST_UPDATE_DATE_TIME

WHEN NOT MATCHED THEN
INSERT
(
TGT.TOUR_STATUS_ID,
TGT.TOUR_STATUS_TEXT,
TGT.SOURCE_SYSTEM_CODE,
TGT.DW_LAST_UPDATE_DATE_TIME
)
VALUES
(
SRC.TOUR_STATUS_ID,
SRC.TOUR_STATUS_TEXT,
SRC.SOURCE_SYSTEM_CODE,
SRC.DW_LAST_UPDATE_DATE_TIME
);

.IF ERRORCODE <> 0 Then .Quit ERRORCODE;

/*  Collect Statistics on the Target Table    */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR','REF_ONBOARDING_TOUR_STATUS');
 
.IF ERRORCODE <> 0 THEN .Quit ERRORCODE;


.Logoff;

.exit

EOF

