#   SCRIPT NAME     - HDW_Enwisen_Ref_Email_To_HR_Status.sql                  		#
#   Job NAME         - J_HDW_Enwisen_Ref_Onboarding_Tour                            	#
#   TARGET TABLE    - EDWHR.REF_ONBOARDING_TOUR                       			#
#   Developer   	- Syntel                                                              # 
#   Version 		- 1.0 - Initial RELEASE                     				#
#   Description 	- The SCRIPT loads the TARGET with Upsert					#
############################################################################################

bteq << EOF > $1;

.RUN FILE $LOGONDIR/HDW_AC;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

SET QUERY_BAND = 'App=HR_Enwisen_ETL; Job=J_HDW_Enwisen_Ref_Onboarding_Tour;' FOR SESSION;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

/*  Merge the data into EDWHR.REF_ONBOARDING_TOUR table  */

MERGE INTO EDWHR.REF_ONBOARDING_TOUR TGT
USING (
SELECT
CASE  WHEN TGT.TOUR_ID IS  NOT NULL THEN TGT.TOUR_ID ELSE
((SELECT  COALESCE(MAX(TOUR_ID ),0)  FROM  EDWHR_BASE_VIEWS.REF_ONBOARDING_TOUR)
+ ROW_NUMBER() OVER ( ORDER BY TOUR_ID  NULLS FIRST,STG.TOUR_NAME)) END AS TOUR_ID,
STG.TOUR_NAME AS TOUR_NAME,
STG.SOURCE_SYSTEM_CODE,
CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM
(
SELECT  
TRIM(TOURNAME) AS TOUR_NAME,
'W'  AS  SOURCE_SYSTEM_CODE
FROM  EDWHR_STAGING.ENWISEN_AUDIT
WHERE TRIM(TOURNAME) IS NOT NULL
GROUP BY 1,2
)STG

LEFT JOIN EDWHR_BASE_VIEWS.REF_ONBOARDING_TOUR TGT
ON TGT.TOUR_NAME = STG.TOUR_NAME
AND TGT.SOURCE_SYSTEM_CODE= STG.SOURCE_SYSTEM_CODE
) SRC
ON TGT.TOUR_ID = SRC.TOUR_ID
AND TGT.SOURCE_SYSTEM_CODE= SRC.SOURCE_SYSTEM_CODE

WHEN MATCHED THEN 
UPDATE SET 
DW_LAST_UPDATE_DATE_TIME=SRC.DW_LAST_UPDATE_DATE_TIME

WHEN NOT MATCHED THEN
INSERT
(
TGT.TOUR_ID,
TGT.TOUR_NAME,
TGT.SOURCE_SYSTEM_CODE,
TGT.DW_LAST_UPDATE_DATE_TIME
)
VALUES
(
SRC.TOUR_ID,
SRC.TOUR_NAME,
SRC.SOURCE_SYSTEM_CODE,
SRC.DW_LAST_UPDATE_DATE_TIME
);

.IF ERRORCODE <> 0 Then .Quit ERRORCODE;

/*  Collect Statistics on the Target Table    */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR','REF_ONBOARDING_TOUR');
 
.IF ERRORCODE <> 0 THEN .Quit ERRORCODE;


.Logoff;

.exit

EOF

