#########################################################################################
#   SCRIPT NAME     - HDW_Candidate_Onboarding_Resource.sql                 		    #
#   Job NAME         - J_HDW_Candidate_Onboarding_Resource                         	    #
#   TARGET TABLE    - EDWHR.Candidate_Onboarding_Resource                          	    #
#   Developer   	- Syntel                                  			    #
#   Version 		- 1.0 - Initial RELEASE                     			    #
#   Description 	- The SCRIPT loads the CORE TABLE WITH WRK table records	    #
#                     AND maintain their version AS TYPE 2                              #
#                                               					           #
#			  								           #
#########################################################################################

bteq << EOF > $1;

.RUN FILE $LOGONDIR/HDW_AC;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

SET QUERY_BAND = 'App=HR_Enwisen_ETL; Job=J_HDW_Candidate_Onboarding_Resource;' FOR SESSION;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;


/* BEGIN TRANSACTION BLOCK STARTS HERE */
BT;

UPDATE TGT
FROM EDWHR.CANDIDATE_ONBOARDING_RESOURCE TGT,EDWHR_STAGING.CANDIDATE_ONBOARDING_RESOURCE_WRK STG
SET VALID_TO_DATE = STG.VALID_FROM_DATE - INTERVAL '1' DAY  
,DW_LAST_UPDATE_DATE_TIME = STG.DW_LAST_UPDATE_DATE_TIME
WHERE TGT.RESOURCE_SCREENING_PACKAGE_NUM = STG.RESOURCE_SCREENING_PACKAGE_NUM
AND (
TRIM(COALESCE(TGT.CANDIDATE_SID ,-999)) NOT= TRIM(COALESCE(STG.CANDIDATE_SID,-999))
OR TRIM(COALESCE(TGT.RECRUITMENT_REQUISITION_SID ,-999))  NOT= TRIM(COALESCE(STG.RECRUITMENT_REQUISITION_SID,-999))
OR COALESCE(TRIM(TGT.SOURCE_SYSTEM_CODE),'X') NOT=COALESCE(TRIM(STG.SOURCE_SYSTEM_CODE),'X')
)
AND 
TGT.VALID_TO_DATE = '9999-12-31'
;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

INSERT INTO EDWHR.CANDIDATE_ONBOARDING_RESOURCE
(
RESOURCE_SCREENING_PACKAGE_NUM
,VALID_FROM_DATE
,CANDIDATE_SID
,RECRUITMENT_REQUISITION_SID
,VALID_TO_DATE
,SOURCE_SYSTEM_CODE
,DW_LAST_UPDATE_DATE_TIME
)
SELECT 
STG.RESOURCE_SCREENING_PACKAGE_NUM
,STG.VALID_FROM_DATE
,STG.CANDIDATE_SID
,STG.RECRUITMENT_REQUISITION_SID
,STG.VALID_TO_DATE
,STG.SOURCE_SYSTEM_CODE
,STG.DW_LAST_UPDATE_DATE_TIME
FROM EDWHR_STAGING.CANDIDATE_ONBOARDING_RESOURCE_WRK STG
LEFT JOIN EDWHR_BASE_VIEWS.CANDIDATE_ONBOARDING_RESOURCE TGT
ON  TGT.RESOURCE_SCREENING_PACKAGE_NUM = STG.RESOURCE_SCREENING_PACKAGE_NUM
AND TRIM(COALESCE(TGT.CANDIDATE_SID ,-999)) = TRIM(COALESCE(STG.CANDIDATE_SID,-999))
AND TRIM(COALESCE(TGT.RECRUITMENT_REQUISITION_SID ,-999))  = TRIM(COALESCE(STG.RECRUITMENT_REQUISITION_SID,-999))
AND COALESCE(TRIM(TGT.SOURCE_SYSTEM_CODE),'X') =COALESCE(TRIM(STG.SOURCE_SYSTEM_CODE),'X')
AND TGT.VALID_TO_DATE = '9999-12-31'
WHERE TGT.RESOURCE_SCREENING_PACKAGE_NUM IS NULL ;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;
ET;



.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

/*  COLLECT STATISTICS ON THE TARGET TABLE    */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR','CANDIDATE_ONBOARDING_RESOURCE');
 
.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

.LOGOFF;

.EXIT

EOF
