#   SCRIPT NAME     - HDW_Enwisen_Ref_Email_To_HR_Status.sql                  		#
#   Job NAME         - J_HDW_Enwisen_Ref_Email_To_HR_Status                         	#
#   TARGET TABLE    - EDWHR.Ref_Email_To_HR_Status                    			#
#   Developer   	- Syntel                                                              # 
#   Version 		- 1.0 - Initial RELEASE                     				#
#   Description 	- The SCRIPT loads the TARGET with Upsert					#
############################################################################################

bteq << EOF > $1;

.RUN FILE $LOGONDIR/HDW_AC;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

SET QUERY_BAND = 'App=HR_Enwisen_ETL; Job=J_HDW_Enwisen_Ref_Email_To_HR_Status;' FOR SESSION;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;


CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR_STAGING','ENWISEN_AUDIT');

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

/*  Merge the data into EDWHR.REF_EMAIL_TO_HR_STATUS table  */

MERGE INTO EDWHR.REF_EMAIL_TO_HR_STATUS TGT
USING (
SELECT
CASE  WHEN TGT.EMAIL_SENT_STATUS_ID IS  NOT NULL THEN TGT.EMAIL_SENT_STATUS_ID ELSE
((SELECT  COALESCE(MAX(EMAIL_SENT_STATUS_ID ),0)  FROM  EDWHR_BASE_VIEWS.REF_EMAIL_TO_HR_STATUS)
+ ROW_NUMBER() OVER ( ORDER BY EMAIL_SENT_STATUS_ID  NULLS FIRST,STG.EMAIL_SENT_STATUS_TEXT)) END AS EMAIL_SENT_STATUS_ID,
STG.EMAIL_SENT_STATUS_TEXT AS EMAIL_SENT_STATUS_TEXT,
STG.HR_STATUS_DESC AS HR_STATUS_DESC,
STG.SOURCE_SYSTEM_CODE,
CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME FROM
(
SELECT  
TRIM(HRSTATUS) AS EMAIL_SENT_STATUS_TEXT,
CASE WHEN HRStatus='O' THEN 'Pre-Boarding Tour' 
WHEN HRStatus='V' THEN 'Verification Tour' 
WHEN HRStatus='C' THEN 'Acquisitions' END AS HR_STATUS_DESC,
'W'  AS  SOURCE_SYSTEM_CODE
FROM  EDWHR_STAGING.ENWISEN_AUDIT
WHERE TRIM(HRSTATUS) IS NOT NULL
GROUP BY 1,2,3
)STG

LEFT JOIN EDWHR_BASE_VIEWS.REF_EMAIL_TO_HR_STATUS TGT
ON TGT.EMAIL_SENT_STATUS_TEXT = STG.EMAIL_SENT_STATUS_TEXT
AND TGT.SOURCE_SYSTEM_CODE= STG.SOURCE_SYSTEM_CODE
) SRC
ON TGT.EMAIL_SENT_STATUS_ID = SRC.EMAIL_SENT_STATUS_ID
AND TGT.SOURCE_SYSTEM_CODE= SRC.SOURCE_SYSTEM_CODE

WHEN MATCHED THEN 
UPDATE SET 
HR_STATUS_DESC = SRC.HR_STATUS_DESC,
DW_LAST_UPDATE_DATE_TIME=SRC.DW_LAST_UPDATE_DATE_TIME

WHEN NOT MATCHED THEN
INSERT
(
TGT.EMAIL_SENT_STATUS_ID,
TGT.EMAIL_SENT_STATUS_TEXT,
TGT.HR_STATUS_DESC,
TGT.SOURCE_SYSTEM_CODE,
TGT.DW_LAST_UPDATE_DATE_TIME
)
VALUES
(
SRC.EMAIL_SENT_STATUS_ID,
SRC.EMAIL_SENT_STATUS_TEXT,
SRC.HR_STATUS_DESC,
SRC.SOURCE_SYSTEM_CODE,
SRC.DW_LAST_UPDATE_DATE_TIME
);


.IF ERRORCODE <> 0 Then .Quit ERRORCODE;

/*  Collect Statistics on the Target Table    */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR','REF_EMAIL_TO_HR_STATUS');
 
.IF ERRORCODE <> 0 THEN .Quit ERRORCODE;


.Logoff;

.exit

EOF

