#   SCRIPT NAME     - HDW_Candidate_Onboarding_Resource.sql                  		#
#   Job NAME         - J_HDW_Candidate_Onboarding_Resource                           	#
#   TARGET TABLE    - EDWHR_STAGING.CANDIDATE_ONBOARDING_RESOURCE_WRK       			#
#   Developer   	- Syntel                                                              # 
#   Version 		- 1.0 - Initial RELEASE                     				#
#   Description 	- The SCRIPT loads the Work Table  					#
############################################################################################

bteq << EOF > $1;

.RUN FILE $LOGONDIR/HDW_AC;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

SET QUERY_BAND = 'App=HR_Enwisen_ETL; Job=J_HDW_Candidate_Onboarding_Resource;' FOR SESSION;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

/*  Merge the data into EDWHR.REF_ONBOARDING_TOUR_STATUS table  */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR_STAGING','ATS_RESOURCESCREENPACK_BCT_STG');

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;

DELETE FROM EDWHR_STAGING.CANDIDATE_ONBOARDING_RESOURCE_WRK;

.IF ERRORCODE <> 0 THEN .QUIT ERRORCODE;


INSERT INTO EDWHR_STAGING.CANDIDATE_ONBOARDING_RESOURCE_WRK
(
RESOURCE_SCREENING_PACKAGE_NUM
,VALID_FROM_DATE
,CANDIDATE_SID
,RECRUITMENT_REQUISITION_SID
,VALID_TO_DATE
,SOURCE_SYSTEM_CODE
,DW_LAST_UPDATE_DATE_TIME
)
SELECT
STG.RESOURCESCREENINGPACKAGE AS RESOURCE_SCREENING_PACKAGE_NUM
,CURRENT_DATE AS VALID_FROM_DATE
,CAN. CANDIDATE_SID AS CANDIDATE_SID
,REQ.RECRUITMENT_REQUISITION_SID AS RECRUITMENT_REQUISITION_SID
,DATE '9999-12-31' AS VALID_TO_DATE
,'B' AS SOURCE_SYSTEM_CODE
,CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME
FROM EDWHR_STAGING.ATS_RESOURCESCREENPACK_BCT_STG STG
LEFT JOIN EDWHR_BASE_VIEWS.CANDIDATE CAN
ON CAN.CANDIDATE_NUM=STG.CANDIDATE
AND CAN.VALID_TO_DATE = '9999-12-31'
AND CAN.SOURCE_SYSTEM_CODE = 'B'
LEFT JOIN EDWHR_BASE_VIEWS.RECRUITMENT_REQUISITION REQ
ON REQ.REQUISITION_NUM=STG.JOBREQUISITION
AND REQ.VALID_TO_DATE = '9999-12-31'
AND REQ.SOURCE_SYSTEM_CODE = 'B'
WHERE STG.SCREENINGPACKAGE LIKE 'B%'
GROUP BY 1,2,3,4,5,6,7;

.IF ERRORCODE <> 0 Then .Quit ERRORCODE;

/*  Collect Statistics on the Target Table    */

CALL DBADMIN_PROCS.COLLECT_STATS_TABLE ('EDWHR_STAGING','CANDIDATE_ONBOARDING_RESOURCE_WRK');
 
.IF ERRORCODE <> 0 THEN .Quit ERRORCODE;


.Logoff;

.exit

EOF

