CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_businessaction_bct_stg
(
  businessview STRING,
  businessaction STRING,
  methodname STRING,
  definedbusinesssubject STRING,
  businesssubject STRING,
  actiontype INT64,
  actiontypename STRING,
  iscreate BOOL,
  isupdate BOOL,
  isfunction BOOL,
  isdelete BOOL,
  isimport BOOL,
  ispurge BOOL,
  isrequestaction BOOL,
  isactionextension BOOL,
  hasactionconfiguration BOOL,
  isconfiguration BOOL,
  isparameterized BOOL,
  allowunlimitedconcurrency BOOL,
  synchronicity INT64,
  definedvia INT64,
  details STRING,
  baseaction STRING,
  actionresultoption INT64,
  admincommandoption INT64,
  scheduleconcurrencydefined BOOL,
  scheduleconcurrencyisinitialvalue BOOL,
  scheduleconcurrencytype INT64,
  schedulemisfirestrategydefined BOOL,
  schedulemisfirestrategyisinitialvalue BOOL,
  schedulemisfirestrategy INT64,
  actionlabel STRING
);