CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_v2_jobapplicationworkflowstephistory_stg
(
  _action STRING,
  _asoftimestamp STRING,
  action STRING,
  actiontakenbycandidate INT64,
  atsworkflowcategory STRING,
  atsworkflowstepdescription STRING,
  audit_entry_id STRING,
  candidate INT64,
  candidate_cube_dimension_value STRING,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  createstamp STRING,
  daysinstep FLOAT64,
  hcajobapplicationworkflowstephistorysubstatus STRING,
  hoursinstep FLOAT64,
  hrorganization STRING,
  hrorganization_cube_dimension_value STRING,
  jobapplication INT64,
  jobapplication_action STRING,
  jobapplication_cube_dimension_value STRING,
  jobapplicationworkflowstep STRING,
  jobapplicationworkflowstephistory INT64,
  jobapplicationworkflowstephistory_cube_dimension_value STRING,
  jobrequisition INT64,
  jobrequisition_cube_dimension_value STRING,
  jobrequisitionworkflow STRING,
  jobrequisitionworkflowstep INT64,
  jobrequisitionworkflowstep_cube_dimension_value STRING,
  jobrequisitionworkflowstepatsworkflowstep STRING,
  jobrequisitionworkflowstepatsworkflowstepatsworkflowcategory STRING,
  jobrequisitionworkflowstepworkflow STRING,
  minutesinstep INT64,
  movedby INT64,
  movedbyname STRING,
  movedintimestamp STRING,
  movedouttimestamp STRING,
  repset_variation_id INT64,
  triggeredby STRING,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  updatestamp STRING,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);