CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_jobapplication_cur_stg
(
  action STRING,
  repset_variation_id INT64,
  asoftimestamp DATETIME,
  candidate INT64,
  hrorganization STRING,
  jobapplication INT64,
  jobrequisition INT64,
  acceptancedate DATE,
  acknowledgement STRING,
  acknowledgement_cdv STRING,
  acknowledgementagree INT64,
  acknowledgementsignature STRING,
  acknowledgementsignaturedate DATE,
  allachievementrecordscount INT64,
  allattachmentrecordscount INT64,
  allandsrecocoun INT64,
  allcredentialrecordscount INT64,
  alleducationrecordscount INT64,
  allhistrecocoun INT64,
  allreferencerecordscount INT64,
  applicationdate DATETIME,
  applicationstarted INT64,
  appliedbyrecruiter INT64,
  assessmentordered INT64,
  assignmenttype STRING,
  assignmenttype_cdv STRING,
  atsofferletterbody STRING,
  atsofferlettertemplate STRING,
  atsofferlettertemplate_cdv STRING,
  atsworkflowstepdescription STRING,
  attachedbyrecruiter INT64,
  attachedcandidateapplied INT64,
  behaviorallevel INT64,
  behaviorallevel_state STRING,
  behavioralscore INT64,
  bonus NUMERIC(32, 3),
  bonuscurrencycode STRING,
  bonuscurrencycode_cdv STRING,
  bonusfrequency INT64,
  bonusfrequency_state STRING,
  candidate_cdv STRING,
  candidatedispositionreason STRING,
  candidatedispositionreason_cdv STRING,
  candidatemarkasapplieddate DATETIME,
  candidatemovetohiredate DATE,
  candidatemovetoofferdate DATE,
  candidatemovetoonboarddate DATE,
  candidatemovetoqualifydate DATE,
  candidatescreenedcounted INT64,
  candidatescreeneddate DATE,
  changeempeduhistory INT64,
  changetalentprofile INT64,
  changeworkpreferences INT64,
  collectiveagreement STRING,
  collectiveagreement_cdv STRING,
  collectiveagreementcategory INT64,
  colagrecate_cdv STRING,
  collectiveagreementposition INT64,
  colagreposi_cdv STRING,
  competencyfit NUMERIC(33, 4),
  competencymet INT64,
  consentagreement STRING,
  consentagreement_cdv STRING,
  consentagreementagree INT64,
  consentagreementsignature STRING,
  consentagreementsignaturedate DATE,
  createdresource INT64,
  createdresource_cdv STRING,
  credentialfit NUMERIC(33, 4),
  credentialmet INT64,
  currentdaysincandidatescreened INT64,
  curdaysinhimanarevi INT64,
  currentdaysininterview INT64,
  currentdaysinoffer INT64,
  daysincandidatescreened INT64,
  daysinhiringmanagerreview INT64,
  daysininterview INT64,
  daysinoffer INT64,
  directsupervisor INT64,
  directsupervisor_cdv STRING,
  dispositioncounted INT64,
  dispositiondate DATE,
  educationfit NUMERIC(33, 4),
  educationmet INT64,
  eeocategoriesgender INT64,
  eeocategoriesgender_state STRING,
  eeocategoriesethnicityandrace INT64,
  eeoethnandr_sta STRING,
  eeocategoriesethnicitycode STRING,
  eeohisporlaorig INT64,
  eeocategoriesracesrace1 STRING,
  eeocategoriesracesrace2 STRING,
  eeocategoriesracesrace3 STRING,
  eeocategoriesracesrace4 STRING,
  eeocategoriesracesrace5 STRING,
  eeocategoriesracesrace6 STRING,
  eeocategoriesracesrace7 STRING,
  eeocategoriesracesrace8 STRING,
  eeocategoriesracesrace9 STRING,
  eeocategoriesracesrace10 STRING,
  eeocategoriesdisabilitytype STRING,
  eeocategoriesdisabilityselfid INT64,
  eeodisaselfid_s STRING,
  eeocategoriesnationality STRING,
  eeocategoriesveterancode STRING,
  eeocategoriesreligion STRING,
  eeocategoriesmaritalstatus STRING,
  eeocategoriesbirthdate DATE,
  eeoprotvetestat INT64,
  eeoprotvetestat_sta STRING,
  eeocategoriesdischargedate DATE,
  eeoprotvetevetemultsele1 STRING,
  eeoprotvetevetemultsele2 STRING,
  eeoprotvetevetemultsele3 STRING,
  eeoprotvetevetemultsele4 STRING,
  eeoprotvetevetemultsele5 STRING,
  eeoprotvetevetemultsele6 STRING,
  eeoprotvetevetemultsele7 STRING,
  eeoprotvetevetemultsele8 STRING,
  eeoprotvetevetemultsele9 STRING,
  eeoprotvetevetemultsele10 STRING,
  eeoupdatedbyrecruiter INT64,
  empcontgrouhireemplcontreas STRING,
  empcontgrouhireemplconttype STRING,
  empcontgrouhireemplconttemp STRING,
  empcontgrouhirecontnumb STRING,
  empcontgroudaterangbegidate DATE,
  empcontgroucontdaterangendd DATE,
  empcontgroudaterangnumbofun INT64,
  empcontgroudaterangunittype INT64,
  empcontgrourangunittype_sta STRING,
  empcontgrouemplconttimeunit NUMERIC(32, 3),
  empcontgrouconttimeunittype INT64,
  empcontgroutimeunittype_sta STRING,
  empcontgrouconttimeperutype INT64,
  empcontgroutimeperutype_sta STRING,
  empcontgrouhirecontfte NUMERIC(35, 6),
  empothepayrgrou1datrangbegi1 DATE,
  empothepayrgrou1datrangend1 DATE,
  empothepayrothepayrgrou1cur1 STRING,
  empothepayrpayrgrou1payrate1 NUMERIC(35, 6),
  empothepayrgrou1othpayrperc1 NUMERIC(34, 5),
  empothepayrpayrgrou1othpayt1 STRING,
  empothepayrgrou1othpayrcate1 INT64,
  empothepayr1othpayrcate_sta1 STRING,
  empothepayrgrou1incintopayr1 INT64,
  empothepayrgrou1incintacomp1 INT64,
  empothepayrpayrgrou1infonly1 INT64,
  empothepayrpayrgrou1disinco1 INT64,
  empothepayrgrou2datrangbegi2 DATE,
  empothepayrgrou2datrangend2 DATE,
  empothepayrothepayrgrou2cur2 STRING,
  empothepayrpayrgrou2payrate2 NUMERIC(35, 6),
  empothepayrgrou2othpayrperc2 NUMERIC(34, 5),
  empothepayrpayrgrou2othpayt2 STRING,
  empothepayrgrou2othpayrcate2 INT64,
  empothepayr2othpayrcate_sta2 STRING,
  empothepayrgrou2incintopayr2 INT64,
  empothepayrgrou2incintacomp2 INT64,
  empothepayrpayrgrou2infonly2 INT64,
  empothepayrpayrgrou2disinco2 INT64,
  empothepayrgrou3datrangbegi3 DATE,
  empothepayrgrou3datrangend3 DATE,
  empothepayrothepayrgrou3cur3 STRING,
  empothepayrpayrgrou3payrate3 NUMERIC(35, 6),
  empothepayrgrou3othpayrperc3 NUMERIC(34, 5),
  empothepayrpayrgrou3othpayt3 STRING,
  empothepayrgrou3othpayrcate3 INT64,
  empothepayr3othpayrcate_sta3 STRING,
  empothepayrgrou3incintopayr3 INT64,
  empothepayrgrou3incintacomp3 INT64,
  empothepayrpayrgrou3infonly3 INT64,
  empothepayrpayrgrou3disinco3 INT64,
  empothepayrgrou4datrangbegi4 DATE,
  empothepayrgrou4datrangend4 DATE,
  empothepayrothepayrgrou4cur4 STRING,
  empothepayrpayrgrou4payrate4 NUMERIC(35, 6),
  empothepayrgrou4othpayrperc4 NUMERIC(34, 5),
  empothepayrpayrgrou4othpayt4 STRING,
  empothepayrgrou4othpayrcate4 INT64,
  empothepayr4othpayrcate_sta4 STRING,
  empothepayrgrou4incintopayr4 INT64,
  empothepayrgrou4incintacomp4 INT64,
  empothepayrpayrgrou4infonly4 INT64,
  empothepayrpayrgrou4disinco4 INT64,
  empothepayrgrou5datrangbegi5 DATE,
  empothepayrgrou5datrangend5 DATE,
  empothepayrothepayrgrou5cur5 STRING,
  empothepayrpayrgrou5payrate5 NUMERIC(35, 6),
  empothepayrgrou5othpayrperc5 NUMERIC(34, 5),
  empothepayrpayrgrou5othpayt5 STRING,
  empothepayrgrou5othpayrcate5 INT64,
  empothepayr5othpayrcate_sta5 STRING,
  empothepayrgrou5incintopayr5 INT64,
  empothepayrgrou5incintacomp5 INT64,
  empothepayrpayrgrou5infonly5 INT64,
  empothepayrpayrgrou5disinco5 INT64,
  employmentstartdate DATE,
  excreququestota NUMERIC(33, 4),
  expressinterest INT64,
  expintecandappl INT64,
  expressinterestdate DATETIME,
  extendeddate DATE,
  faiprofscreques INT64,
  failedscreeningcount INT64,
  failedscreeningquestions INT64,
  firstpaycheckdate DATE,
  hcachangewa STRING,
  hcadisabilityq STRING,
  hcaestubq STRING,
  hcafofamilyjob STRING,
  hcafofamilyname STRING,
  hcafofamilyquestion STRING,
  hcafofamilyquestion_state STRING,
  hcafofamilyrep STRING,
  hcafoquestion STRING,
  hcafoquestion_state STRING,
  hcafoquestionyes STRING,
  hcajobapplicationaddfte NUMERIC(35, 6),
  hcajobapplicationaddposition STRING,
  hcaappladdp_sta STRING,
  hcaappladjustardate DATE,
  hcaapplannidate DATE,
  hcaapplannusala NUMERIC(33, 4),
  hcajobapplicationbadgenumber STRING,
  hcaapplbankdetaflatamou3 NUMERIC(31, 2),
  hcaapplbenewaitperi INT64,
  hcaapplbsncperi STRING,
  hcaapplbsncperi_sta STRING,
  hcaapplbsneperi STRING,
  hcaapplbsneperi_sta STRING,
  hcaapplbusirefebusiclasname STRING,
  hcaapplbusirefebusiobjekey STRING,
  hcaapplcandmaidname STRING,
  hcajobapplicationclocknumber STRING,
  hcaapplconfcandacti STRING,
  hcaapplconfcandacti_sta STRING,
  hcaapplconfcandpend INT64,
  hcaapplconfcandsubm INT64,
  hcajobapplicationdepartment STRING,
  hcaappldireleveappr INT64,
  hcaappldiresupeuid STRING,
  hcajobapplicationeid INT64,
  hcajobapplicationemployee INT64,
  hcajobapplicationemployee_cdv STRING,
  hcajobapplicationfacilitydate DATE,
  hcaapplfromworkassi INT64,
  hcaapplfromworkassi_cdv STRING,
  hcajobapplicationfutureequity INT64,
  hcajobapplicationhourlyrate NUMERIC(33, 4),
  hcaapplintepromgran INT64,
  hcaapplintecand STRING,
  hcaapplintecand_sta STRING,
  hcaappljobedate DATE,
  hcajobapplicationmailboxnumber STRING,
  hcajobapplicationnewgrad STRING,
  hcajobapplicationnewgrad_state STRING,
  hcajobapplicationnewhiregrant INT64,
  hcaapploffeexceappr INT64,
  hcaapplorighiredate DATE,
  hcaapplpayraddiamou NUMERIC(31, 2),
  hcajobapplicationpayrule STRING,
  hcaapplrehinewwtype STRING,
  hcaapplrehinewwtype_cdv STRING,
  hcaapplrelobonu NUMERIC(31, 2),
  hcaapplrelobonucurr STRING,
  hcaapplrelobonucurr_cdv STRING,
  hcaapplrelobonufreq INT64,
  hcaapplrelobonufreq_sta STRING,
  hcaapplrelosirva INT64,
  hcaapplrnexdate DATE,
  hcaapplrntrprog STRING,
  hcaapplrntrprog_sta STRING,
  hcaapplrntrprogcompdate DATE,
  hcaapplrntrprogspec STRING,
  hcaapplrntrprogspec_sta STRING,
  hcaapplsecosenidate DATE,
  hcajobapplicationsenioritydate DATE,
  hcajobapplicationsignonbonus NUMERIC(31, 2),
  hcaapplsignonbocurr STRING,
  hcaapplsignonbocurr_cdv STRING,
  hcaapplsignonbofreq INT64,
  hcaapplsignonbofreq_sta STRING,
  hcajobapplicationspecstatusind STRING,
  hcaapplspecstatind_ STRING,
  hcaapplstafleveappr INT64,
  hcaappltempstatthrefte NUMERIC(35, 6),
  hcajobapplicationtimeaccrual STRING,
  hcajobapplicationtimeclock STRING,
  hcajobapplicationtimezone STRING,
  hcaappltimezone_sta STRING,
  hcajobapplicationuid STRING,
  hcaapplunioseni NUMERIC(31, 2),
  hcaappluniosenidate DATE,
  hcaapplvetedutywartcampbadg STRING,
  hcaapplvetearmeforcservmeda STRING,
  hcaapplvetedisa STRING,
  hcaapplvetenoan STRING,
  hcaapplveteprotnots STRING,
  hcaapplveterecesepa STRING,
  hcanurseaddress STRING,
  hcanursecitystate STRING,
  hcanurseliccategory STRING,
  hcanurseliccategory_state STRING,
  hcanurselictype STRING,
  hcanurselictype_state STRING,
  hcanursename STRING,
  hcapimilitary STRING,
  hcapimilitary_state STRING,
  hcapimilitarystatus STRING,
  hcaworkassignment INT64,
  hirecounted INT64,
  hiringmanagerreviewcounted INT64,
  hiringmanagerreviewdate DATE,
  holidayscheduleoverride STRING,
  holidayscheduleoverride_cdv STRING,
  hrorganization_cdv STRING,
  hrorganizationunit INT64,
  hrorganizationunit_cdv STRING,
  hrsdcandidatemessage STRING,
  hrsdcandidatestatus INT64,
  hrsdcandidatestatus_state STRING,
  interviewcompleteddate DATE,
  interviewcounted INT64,
  interviewdate DATE,
  jobapplication_cdv STRING,
  jobpaneoptipanevisi INT64,
  jobpaneresupanevisi INT64,
  jobpanequespanevisi INT64,
  jobpaneworkprefpanevisi INT64,
  jobpanemyhipanevisi INT64,
  jobpanetaleprofpanevisi INT64,
  jobpaneacknpanevisi INT64,
  jobpaneinfopanevisi INT64,
  jobpanesummpanevisi INT64,
  jobprefobje STRING,
  jobprefrelatoor STRING,
  jobprefworktype STRING,
  jobprefsalatype STRING,
  jobprefsalatype_sta STRING,
  jobprefsalacurr STRING,
  jobprefsalaexpe NUMERIC(35, 6),
  jobprefavaideclavai INT64,
  jobprefavaideclavai_sta STRING,
  jobprefavaideclspecdate DATE,
  jobprefavaiavaidaterangbegi DATE,
  jobprefavaiavaidaterangend DATE,
  jobprefjobcprefjobc1 STRING,
  jobprefjobcprefjobc2 STRING,
  jobprefjobcprefjobc3 STRING,
  jobpreflocaofjo1loc111 STRING,
  jobpreflocaofjo1loc212 STRING,
  jobpreflocaofjo1loc313 STRING,
  jobpreflocaofjo1loc414 STRING,
  jobpreflocaofjo2loc121 STRING,
  jobpreflocaofjo2loc222 STRING,
  jobpreflocaofjo2loc323 STRING,
  jobpreflocaofjo2loc424 STRING,
  jobpreflocaofjo3loc131 STRING,
  jobpreflocaofjo3loc232 STRING,
  jobpreflocaofjo3loc333 STRING,
  jobpreflocaofjo3loc434 STRING,
  jobprefpreftrav INT64,
  jobprefpreftrav_sta STRING,
  jobprefpreftravperc NUMERIC(33, 4),
  jobprefprefrelo INT64,
  jobprefprefrelo_sta STRING,
  jobprefprefinteassi INT64,
  jobprefprefinteassi_sta STRING,
  jobprefprefworklifebala STRING,
  jobprefprefpoinofor STRING,
  jobprefprefworkovertime INT64,
  jobprefprefworkovertime_sta STRING,
  jobapplicationpreferencesshift INT64,
  jobprefshif_sta STRING,
  jobposting INT64,
  jobposting_cdv STRING,
  jobrequisition_cdv STRING,
  jobrequisitionworkflowstep INT64,
  jobrequisitionworkflowstep_cdv STRING,
  jobrequisitionworkflowstepdate DATE,
  lastcalculationdate DATE,
  lascontsectdisporde INT64,
  lastinterviewform INT64,
  legalentity STRING,
  legalentity_cdv STRING,
  legalestablishment STRING,
  legalestablishment_cdv STRING,
  location STRING,
  location_cdv STRING,
  meetsrequirementquestionstotal NUMERIC(33, 4),
  monthlybonuscurrencycode STRING,
  monthlybonuscurrencycode_cdv STRING,
  monthlyincentivebonus NUMERIC(32, 3),
  newapplicationcounted INT64,
  noticeperiodaftertrialperiod STRING,
  notperiaftetriaperi_cdv STRING,
  noticeperiodduringtrialperiod STRING,
  notperiduritriaperi_cdv STRING,
  notionalsalary NUMERIC(35, 6),
  notionalsalarycurrencycode STRING,
  notionalsalarycurrencycode_cdv STRING,
  offeraccepted INT64,
  offallogrougrou1datrangbegi1 DATE,
  offallogrougrou1datrangend1 DATE,
  offallogrouallogrou1alltype1 STRING,
  offallogrouemplallogrou1cur1 STRING,
  offallogrouallogrou1allamou1 NUMERIC(32, 3),
  offallogrouallogrou1allperc1 NUMERIC(34, 5),
  offallogrouallogrou1hrounit1 INT64,
  offallogrouemplallogrou1job1 INT64,
  offallogrouallogrou1crepayc1 STRING,
  offallogrougrou1payfreqover1 INT64,
  offallogrou1payfreqover_sta1 STRING,
  offallogrougrou1incintopayr1 INT64,
  offallogrouallogrou1infonly1 INT64,
  offallogrouallogrou1disinco1 INT64,
  offallogrougrou2datrangbegi2 DATE,
  offallogrougrou2datrangend2 DATE,
  offallogrouallogrou2alltype2 STRING,
  offallogrouemplallogrou2cur2 STRING,
  offallogrouallogrou2allamou2 NUMERIC(32, 3),
  offallogrouallogrou2allperc2 NUMERIC(34, 5),
  offallogrouallogrou2hrounit2 INT64,
  offallogrouemplallogrou2job2 INT64,
  offallogrouallogrou2crepayc2 STRING,
  offallogrougrou2payfreqover2 INT64,
  offallogrou2payfreqover_sta2 STRING,
  offallogrougrou2incintopayr2 INT64,
  offallogrouallogrou2infonly2 INT64,
  offallogrouallogrou2disinco2 INT64,
  offallogrougrou3datrangbegi3 DATE,
  offallogrougrou3datrangend3 DATE,
  offallogrouallogrou3alltype3 STRING,
  offallogrouemplallogrou3cur3 STRING,
  offallogrouallogrou3allamou3 NUMERIC(32, 3),
  offallogrouallogrou3allperc3 NUMERIC(34, 5),
  offallogrouallogrou3hrounit3 INT64,
  offallogrouemplallogrou3job3 INT64,
  offallogrouallogrou3crepayc3 STRING,
  offallogrougrou3payfreqover3 INT64,
  offallogrou3payfreqover_sta3 STRING,
  offallogrougrou3incintopayr3 INT64,
  offallogrouallogrou3infonly3 INT64,
  offallogrouallogrou3disinco3 INT64,
  offallogrougrou4datrangbegi4 DATE,
  offallogrougrou4datrangend4 DATE,
  offallogrouallogrou4alltype4 STRING,
  offallogrouemplallogrou4cur4 STRING,
  offallogrouallogrou4allamou4 NUMERIC(32, 3),
  offallogrouallogrou4allperc4 NUMERIC(34, 5),
  offallogrouallogrou4hrounit4 INT64,
  offallogrouemplallogrou4job4 INT64,
  offallogrouallogrou4crepayc4 STRING,
  offallogrougrou4payfreqover4 INT64,
  offallogrou4payfreqover_sta4 STRING,
  offallogrougrou4incintopayr4 INT64,
  offallogrouallogrou4infonly4 INT64,
  offallogrouallogrou4disinco4 INT64,
  offallogrougrou5datrangbegi5 DATE,
  offallogrougrou5datrangend5 DATE,
  offallogrouallogrou5alltype5 STRING,
  offallogrouemplallogrou5cur5 STRING,
  offallogrouallogrou5allamou5 NUMERIC(32, 3),
  offallogrouallogrou5allperc5 NUMERIC(34, 5),
  offallogrouallogrou5hrounit5 INT64,
  offallogrouemplallogrou5job5 INT64,
  offallogrouallogrou5crepayc5 STRING,
  offallogrougrou5payfreqover5 INT64,
  offallogrou5payfreqover_sta5 STRING,
  offallogrougrou5incintopayr5 INT64,
  offallogrouallogrou5infonly5 INT64,
  offallogrouallogrou5disinco5 INT64,
  offallogrougrou6datrangbegi6 DATE,
  offallogrougrou6datrangend6 DATE,
  offallogrouallogrou6alltype6 STRING,
  offallogrouemplallogrou6cur6 STRING,
  offallogrouallogrou6allamou6 NUMERIC(32, 3),
  offallogrouallogrou6allperc6 NUMERIC(34, 5),
  offallogrouallogrou6hrounit6 INT64,
  offallogrouemplallogrou6job6 INT64,
  offallogrouallogrou6crepayc6 STRING,
  offallogrougrou6payfreqover6 INT64,
  offallogrou6payfreqover_sta6 STRING,
  offallogrougrou6incintopayr6 INT64,
  offallogrouallogrou6infonly6 INT64,
  offallogrouallogrou6disinco6 INT64,
  offallogrougrou7datrangbegi7 DATE,
  offallogrougrou7datrangend7 DATE,
  offallogrouallogrou7alltype7 STRING,
  offallogrouemplallogrou7cur7 STRING,
  offallogrouallogrou7allamou7 NUMERIC(32, 3),
  offallogrouallogrou7allperc7 NUMERIC(34, 5),
  offallogrouallogrou7hrounit7 INT64,
  offallogrouemplallogrou7job7 INT64,
  offallogrouallogrou7crepayc7 STRING,
  offallogrougrou7payfreqover7 INT64,
  offallogrou7payfreqover_sta7 STRING,
  offallogrougrou7incintopayr7 INT64,
  offallogrouallogrou7infonly7 INT64,
  offallogrouallogrou7disinco7 INT64,
  offallogrougrou8datrangbegi8 DATE,
  offallogrougrou8datrangend8 DATE,
  offallogrouallogrou8alltype8 STRING,
  offallogrouemplallogrou8cur8 STRING,
  offallogrouallogrou8allamou8 NUMERIC(32, 3),
  offallogrouallogrou8allperc8 NUMERIC(34, 5),
  offallogrouallogrou8hrounit8 INT64,
  offallogrouemplallogrou8job8 INT64,
  offallogrouallogrou8crepayc8 STRING,
  offallogrougrou8payfreqover8 INT64,
  offallogrou8payfreqover_sta8 STRING,
  offallogrougrou8incintopayr8 INT64,
  offallogrouallogrou8infonly8 INT64,
  offallogrouallogrou8disinco8 INT64,
  offallogrougrou9datrangbegi9 DATE,
  offallogrougrou9datrangend9 DATE,
  offallogrouallogrou9alltype9 STRING,
  offallogrouemplallogrou9cur9 STRING,
  offallogrouallogrou9allamou9 NUMERIC(32, 3),
  offallogrouallogrou9allperc9 NUMERIC(34, 5),
  offallogrouallogrou9hrounit9 INT64,
  offallogrouemplallogrou9job9 INT64,
  offallogrouallogrou9crepayc9 STRING,
  offallogrougrou9payfreqover9 INT64,
  offallogrou9payfreqover_sta9 STRING,
  offallogrougrou9incintopayr9 INT64,
  offallogrouallogrou9infonly9 INT64,
  offallogrouallogrou9disinco9 INT64,
  offallogrougrou10darangbegi10 DATE,
  offallogrougrou10darangend10 DATE,
  offallogrouallogrou10altype10 STRING,
  offallogrouemplallogrou10cu10 STRING,
  offallogrouallogrou10alamou10 NUMERIC(32, 3),
  offallogrouallogrou10alperc10 NUMERIC(34, 5),
  offallogrougrou10hrorgaunit10 INT64,
  offallogrouemplallogrou10jo10 INT64,
  offallogrouallogrou10crpayc10 STRING,
  offallogrougrou10pafreqover10 INT64,
  offallogrou10pafreqover_sta10 STRING,
  offallogrougrou10inintopayr10 INT64,
  offallogrouallogrou10inonly10 INT64,
  offallogrouallogrou10diinco10 INT64,
  offercounted INT64,
  offerdate DATE,
  offerdeadlinedate DATE,
  offerdeclined INT64,
  offerdocumentcreateddate DATE,
  offemplallogrou1datrangbegi1 DATE,
  offemplallogrou1datrangend1 DATE,
  offemplalloallogrou1alltype1 STRING,
  offemplalloemplallogrou1cur1 STRING,
  offemplalloallogrou1allamou1 NUMERIC(32, 3),
  offemplalloallogrou1allperc1 NUMERIC(34, 5),
  offemplalloallogrou1hrounit1 INT64,
  offemplalloemplallogrou1job1 INT64,
  offemplalloallogrou1crepayc1 STRING,
  offemplallogrou1payfreqover1 INT64,
  offemplallo1payfreqover_sta1 STRING,
  offemplallogrou1incintopayr1 INT64,
  offemplalloallogrou1infonly1 INT64,
  offemplalloallogrou1disinco1 INT64,
  offemplallogrou2datrangbegi2 DATE,
  offemplallogrou2datrangend2 DATE,
  offemplalloallogrou2alltype2 STRING,
  offemplalloemplallogrou2cur2 STRING,
  offemplalloallogrou2allamou2 NUMERIC(32, 3),
  offemplalloallogrou2allperc2 NUMERIC(34, 5),
  offemplalloallogrou2hrounit2 INT64,
  offemplalloemplallogrou2job2 INT64,
  offemplalloallogrou2crepayc2 STRING,
  offemplallogrou2payfreqover2 INT64,
  offemplallo2payfreqover_sta2 STRING,
  offemplallogrou2incintopayr2 INT64,
  offemplalloallogrou2infonly2 INT64,
  offemplalloallogrou2disinco2 INT64,
  offemplallogrou3datrangbegi3 DATE,
  offemplallogrou3datrangend3 DATE,
  offemplalloallogrou3alltype3 STRING,
  offemplalloemplallogrou3cur3 STRING,
  offemplalloallogrou3allamou3 NUMERIC(32, 3),
  offemplalloallogrou3allperc3 NUMERIC(34, 5),
  offemplalloallogrou3hrounit3 INT64,
  offemplalloemplallogrou3job3 INT64,
  offemplalloallogrou3crepayc3 STRING,
  offemplallogrou3payfreqover3 INT64,
  offemplallo3payfreqover_sta3 STRING,
  offemplallogrou3incintopayr3 INT64,
  offemplalloallogrou3infonly3 INT64,
  offemplalloallogrou3disinco3 INT64,
  offemplallogrou4datrangbegi4 DATE,
  offemplallogrou4datrangend4 DATE,
  offemplalloallogrou4alltype4 STRING,
  offemplalloemplallogrou4cur4 STRING,
  offemplalloallogrou4allamou4 NUMERIC(32, 3),
  offemplalloallogrou4allperc4 NUMERIC(34, 5),
  offemplalloallogrou4hrounit4 INT64,
  offemplalloemplallogrou4job4 INT64,
  offemplalloallogrou4crepayc4 STRING,
  offemplallogrou4payfreqover4 INT64,
  offemplallo4payfreqover_sta4 STRING,
  offemplallogrou4incintopayr4 INT64,
  offemplalloallogrou4infonly4 INT64,
  offemplalloallogrou4disinco4 INT64,
  offemplallogrou5datrangbegi5 DATE,
  offemplallogrou5datrangend5 DATE,
  offemplalloallogrou5alltype5 STRING,
  offemplalloemplallogrou5cur5 STRING,
  offemplalloallogrou5allamou5 NUMERIC(32, 3),
  offemplalloallogrou5allperc5 NUMERIC(34, 5),
  offemplalloallogrou5hrounit5 INT64,
  offemplalloemplallogrou5job5 INT64,
  offemplalloallogrou5crepayc5 STRING,
  offemplallogrou5payfreqover5 INT64,
  offemplallo5payfreqover_sta5 STRING,
  offemplallogrou5incintopayr5 INT64,
  offemplalloallogrou5infonly5 INT64,
  offemplalloallogrou5disinco5 INT64,
  offemplallogrou6datrangbegi6 DATE,
  offemplallogrou6datrangend6 DATE,
  offemplalloallogrou6alltype6 STRING,
  offemplalloemplallogrou6cur6 STRING,
  offemplalloallogrou6allamou6 NUMERIC(32, 3),
  offemplalloallogrou6allperc6 NUMERIC(34, 5),
  offemplalloallogrou6hrounit6 INT64,
  offemplalloemplallogrou6job6 INT64,
  offemplalloallogrou6crepayc6 STRING,
  offemplallogrou6payfreqover6 INT64,
  offemplallo6payfreqover_sta6 STRING,
  offemplallogrou6incintopayr6 INT64,
  offemplalloallogrou6infonly6 INT64,
  offemplalloallogrou6disinco6 INT64,
  offemplallogrou7datrangbegi7 DATE,
  offemplallogrou7datrangend7 DATE,
  offemplalloallogrou7alltype7 STRING,
  offemplalloemplallogrou7cur7 STRING,
  offemplalloallogrou7allamou7 NUMERIC(32, 3),
  offemplalloallogrou7allperc7 NUMERIC(34, 5),
  offemplalloallogrou7hrounit7 INT64,
  offemplalloemplallogrou7job7 INT64,
  offemplalloallogrou7crepayc7 STRING,
  offemplallogrou7payfreqover7 INT64,
  offemplallo7payfreqover_sta7 STRING,
  offemplallogrou7incintopayr7 INT64,
  offemplalloallogrou7infonly7 INT64,
  offemplalloallogrou7disinco7 INT64,
  offemplallogrou8datrangbegi8 DATE,
  offemplallogrou8datrangend8 DATE,
  offemplalloallogrou8alltype8 STRING,
  offemplalloemplallogrou8cur8 STRING,
  offemplalloallogrou8allamou8 NUMERIC(32, 3),
  offemplalloallogrou8allperc8 NUMERIC(34, 5),
  offemplalloallogrou8hrounit8 INT64,
  offemplalloemplallogrou8job8 INT64,
  offemplalloallogrou8crepayc8 STRING,
  offemplallogrou8payfreqover8 INT64,
  offemplallo8payfreqover_sta8 STRING,
  offemplallogrou8incintopayr8 INT64,
  offemplalloallogrou8infonly8 INT64,
  offemplalloallogrou8disinco8 INT64,
  offemplallogrou9datrangbegi9 DATE,
  offemplallogrou9datrangend9 DATE,
  offemplalloallogrou9alltype9 STRING,
  offemplalloemplallogrou9cur9 STRING,
  offemplalloallogrou9allamou9 NUMERIC(32, 3),
  offemplalloallogrou9allperc9 NUMERIC(34, 5),
  offemplalloallogrou9hrounit9 INT64,
  offemplalloemplallogrou9job9 INT64,
  offemplalloallogrou9crepayc9 STRING,
  offemplallogrou9payfreqover9 INT64,
  offemplallo9payfreqover_sta9 STRING,
  offemplallogrou9incintopayr9 INT64,
  offemplalloallogrou9infonly9 INT64,
  offemplalloallogrou9disinco9 INT64,
  offemplallogrou10darangbegi10 DATE,
  offemplallogrou10darangend10 DATE,
  offemplalloallogrou10altype10 STRING,
  offemplalloemplallogrou10cu10 STRING,
  offemplalloallogrou10alamou10 NUMERIC(32, 3),
  offemplalloallogrou10alperc10 NUMERIC(34, 5),
  offemplallogrou10hrorgaunit10 INT64,
  offemplalloemplallogrou10jo10 INT64,
  offemplalloallogrou10crpayc10 STRING,
  offemplallogrou10pafreqover10 INT64,
  offemplallo10pafreqover_sta10 STRING,
  offemplallogrou10inintopayr10 INT64,
  offemplalloallogrou10inonly10 INT64,
  offemplalloallogrou10diinco10 INT64,
  offerextendeddate DATE,
  offernumberofmonths INT64,
  offerpayratetype STRING,
  offerpayratetype_state STRING,
  offersignaturedate DATE,
  offerstatus INT64,
  offerstatus_state STRING,
  onboardcounted INT64,
  paygrade INT64,
  paygrade_cdv STRING,
  paystep INT64,
  paystep_cdv STRING,
  percentfit NUMERIC(33, 4),
  preboardstatus INT64,
  preboardstatus_state STRING,
  preboardupdated DATETIME,
  professionalcategory STRING,
  professionalcategory_cdv STRING,
  qualificationlevel INT64,
  qualificationlevel_state STRING,
  qualificationsmet INT64,
  questionscore INT64,
  recruitingdocumenttemplate STRING,
  recruitingdocumenttemplate_cdv STRING,
  recruitingfitanalysiscounted INT64,
  recruitingrank STRING,
  recruitingrank_cdv STRING,
  referringsource STRING,
  renewaldate DATE,
  renewalnotificationdate DATE,
  replacedemployeeemployee INT64,
  rescinddate DATE,
  routingapprovallevel INT64,
  salary NUMERIC(35, 6),
  salarycurrencycode STRING,
  salarycurrencycode_cdv STRING,
  salaryfrequency INT64,
  salaryfrequency_state STRING,
  screenedoutonlinecounted INT64,
  screeningquestionreviewdate DATE,
  screeningquestionreviewed INT64,
  selectionprocess INT64,
  selectionprocess_state STRING,
  selectionprocess_cdv STRING,
  selectionprocessdatesnapshot DATE,
  sentinterviewemaildate DATE,
  signature STRING,
  signaturedate DATE,
  skillfit NUMERIC(33, 4),
  skillmet INT64,
  skipofferacceptdeclinelogic INT64,
  source_varchar STRING,
  source_cdv STRING,
  specificsource STRING,
  specificsource_cdv STRING,
  status INT64,
  status_state STRING,
  stepandgradeschedule STRING,
  stepandgradeschedule_cdv STRING,
  title_varchar STRING,
  totalcompetency INT64,
  totalcredential INT64,
  totaleducation INT64,
  totalqualifications INT64,
  totalskill INT64,
  trialperiod STRING,
  trialperiod_cdv STRING,
  trialperiodenddateoverride DATE,
  uniqueid STRING,
  useresumefromprofile INT64,
  webserviceimport INT64,
  workingremotely INT64,
  worktype STRING,
  worktype_cdv STRING,
  updatestamp DATETIME,
  createstamp DATETIME,
  atsworkflowstepkey STRING
);