CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_atsworkflow_stg
(
  _action STRING,
  _asoftimestamp STRING,
  active INT64,
  additionalapplicationtaskssummarycontent STRING,
  additionalapplicationtaskssummarylabel STRING,
  additionalapplicationtaskssummarytext STRING,
  additionalapplicationtaskssummarytype INT64,
  additionalapplicationtaskssummarytype_state STRING,
  applicationofferacceptedbycandidate STRING,
  applicationofferdeclinedbycandidate STRING,
  applicationofferdeclineddispositionreason STRING,
  applicationscreenedoutonline STRING,
  applicationscreenedoutonlinedispositionreason STRING,
  applicationstarted STRING,
  applicationsubmittedbycandidate STRING,
  applicationundohire STRING,
  atsworkflow STRING,
  attachcandidateapplicationsubmitted STRING,
  attachcandidatetorequisition STRING,
  automaticallydispositionuponcancel INT64,
  automaticallydispositionuponcancelreason STRING,
  automaticallydispositionuponclose INT64,
  automaticallydispositionuponclosereason STRING,
  automaticallydispositionuponfill INT64,
  automaticallydispositionuponfillreason STRING,
  candidateexpressesinterest STRING,
  closerequisitionuponentering STRING,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  description STRING,
  expressinterestapplicationsubmitted STRING,
  fillrequisitionuponentering STRING,
  hcaatsworkflowacquisitionworkflowdefault INT64,
  hcaatsworkflowmrworkflowdefault INT64,
  hcaatsworkflowproviderworkflowdefault INT64,
  hrorganization STRING,
  lockprofile STRING,
  managefilledopenings INT64,
  managefilledopenings_state STRING,
  offerapproved STRING,
  offersubmittedforapproval STRING,
  positionbudgetoffer STRING,
  positionbudgetonboard STRING,
  positionbudgetwithinhireprocess STRING,
  removepostingsuponentering STRING,
  repset_variation_id INT64,
  synchronizeprofile INT64,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  useasdefault INT64,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);