CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_v2_atsworkflowstep_stg
(
  _action STRING,
  _asoftimestamp STRING,
  active INT64,
  applicationwithdrawndispositionreason STRING,
  applicationwithdrawndispositionreason_cube_dimension_value STRING,
  atsworkflow STRING,
  atsworkflowcategory STRING,
  atsworkflowcategory_cube_dimension_value STRING,
  atsworkflowkey STRING,
  atsworkflowstep STRING,
  atsworkflowstepkey STRING,
  candidateapplicationstatus STRING,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  createstamp STRING,
  description STRING,
  displayorder INT64,
  hcaatsworkflowstepbackgroundtype FLOAT64,
  hcaatsworkflowstepbackgroundtype_state STRING,
  hcaatsworkflowstephiringmanagercanmove INT64,
  hcaatsworkflowstephiringmanagercanmoveinto INT64,
  hcaatsworkflowstephiringmanagercanview INT64,
  hcaatsworkflowstepmassassigninterviewtype STRING,
  hcaatsworkflowstepmassassigninterviewtype_state STRING,
  hcaatsworkflowsteptransferpackage STRING,
  hcaatsworkflowsteptransferpackage_cube_dimension_value STRING,
  hcaatsworkflowsteptransferpackagedt STRING,
  hcaatsworkflowsteptransferpackagedt_cube_dimension_value STRING,
  hrorganization STRING,
  hrorganization_cube_dimension_value STRING,
  repset_variation_id INT64,
  required INT64,
  targetdaysinstep INT64,
  type INT64,
  type_state STRING,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  updatestamp STRING,
  withdrawnbycandidate STRING,
  withdrawnbycandidate_cube_dimension_value STRING,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);