CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_candemploymenthistory_stg
(
  action STRING,
  repset_variation_id INT64,
  asoftimestamp DATETIME,
  candidate INT64,
  hrorganization STRING,
  sequencenumber INT64,
  attachmenttitle STRING,
  attachmentmimetype STRING,
  begindatemonth INT64,
  begindateyear INT64,
  beginpay NUMERIC(35, 6),
  candidate_cdv STRING,
  comments STRING,
  employeraddresscountry STRING,
  empaddrdeliaddraddrline1 STRING,
  empaddrdeliaddraddrline2 STRING,
  empaddrdeliaddraddrline3 STRING,
  empaddrdeliaddraddrline4 STRING,
  employeraddressmunicipality STRING,
  employeraddressstateprovince STRING,
  employeraddresspostalcode STRING,
  employeraddresscounty STRING,
  employeraddressregion STRING,
  employeraddresstype INT64,
  employeraddresstype_state STRING,
  employercontactemail STRING,
  employercontactname STRING,
  empcontphonintepref STRING,
  empcontphonsubsnumb STRING,
  employercontactphoneextension STRING,
  employername STRING,
  enddatemonth INT64,
  enddateyear INT64,
  endpay NUMERIC(35, 6),
  hrorganization_cdv STRING,
  jobtitle STRING,
  paycurrency STRING,
  paycurrency_cdv STRING,
  payratetype STRING,
  payratetype_state STRING,
  permissiontocontact INT64,
  reasonforleaving STRING,
  uniqueid STRING,
  verificationinfoverified INT64,
  verinfoveridate DATE,
  verinfovalimeth STRING,
  createstamp DATETIME,
  updatestamp DATETIME
);
