CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_job_stg
(
  _action STRING,
  _asoftimestamp STRING,
  active INT64,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  createstamp STRING,
  description STRING,
  directtipped INT64,
  exemptfromovertime INT64,
  exemptfromovertime_state STRING,
  hcajobcodecompany INT64,
  hcajobcodejobcode STRING,
  hcajobpatientcare STRING,
  hcajobpatientcare_state STRING,
  hcajobscreeningcategory STRING,
  hcajobscreeningcategory2 STRING,
  hrorganization STRING,
  job INT64,
  jobcategory STRING,
  jobdescriptiondate STRING,
  jobdescriptiondocument_mimetype STRING,
  jobdescriptiondocument_title STRING,
  jobfamily STRING,
  joblevel STRING,
  jobsubcategory STRING,
  m3interfacerecord INT64,
  otherinformation STRING,
  paygrade INT64,
  repset_variation_id INT64,
  responsibilities STRING,
  salarystructure STRING,
  salarystructuregrade INT64,
  shortdescription STRING,
  stepandgradeschedule STRING,
  summary STRING,
  synchronizedtoposition INT64,
  taxcredit INT64,
  tippable INT64,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  updatestamp STRING,
  usedbyatransaction INT64,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);