CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_pfiqueue_stg
(
  _action STRING,
  _asoftimestamp STRING,
  actiontaken STRING,
  addnotify1 STRING,
  addnotify2 STRING,
  addnotifytype1 INT64,
  addnotifytype1_state STRING,
  addnotifytype2 INT64,
  addnotifytype2_state STRING,
  appsdata STRING,
  appsfilter STRING,
  configname STRING,
  currentassignment INT64,
  displayexec STRING,
  displayname STRING,
  displaytype INT64,
  displaytype_state STRING,
  dispstatus INT64,
  dispstatus_state STRING,
  failaction STRING,
  filtervalue STRING,
  hideactions INT64,
  iondisplayexec STRING,
  iondisplayname STRING,
  lastqueueaction INT64,
  notifyall1 INT64,
  notifyall2 INT64,
  pfiactivity INT64,
  pfifilterkey STRING,
  pfiworkunit INT64,
  phonedisplayexec STRING,
  phonedisplayname STRING,
  phonedisplaytype INT64,
  phonedisplaytype_state STRING,
  prologictype INT64,
  prologictype_state STRING,
  prologicval1 STRING,
  prologicval2 STRING,
  reassignhours INT64,
  reassigntask STRING,
  reminded1 INT64,
  reminded2 INT64,
  repset_variation_id INT64,
  routingrule STRING,
  sendnotification INT64,
  tabletdisplayexec STRING,
  tabletdisplayname STRING,
  tabletdisplaytype INT64,
  tabletdisplaytype_state STRING,
  timedout INT64,
  timeoutaction STRING,
  timeouthour FLOAT64,
  timeouttype INT64,
  timeouttype_state STRING,
  uniqueid STRING,
  waithours1 FLOAT64,
  waithours2 FLOAT64,
  workdescription STRING,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);