CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_hcm_resourcetransition_stg
(
  _asoftimestamp STRING,
  audit_entry_id STRING,
  candidate INT64,
  candidate_cube_dimension_value STRING,
  completiondate STRING,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  disabilitydocument_mimetype STRING,
  disabilitydocument_title STRING,
  employee INT64,
  employee_cube_dimension_value STRING,
  formi9startdate INT64,
  formi9startdate_state STRING,
  hidedate STRING,
  hrorganization STRING,
  hrorganization_cube_dimension_value STRING,
  jobapplication INT64,
  jobapplication_cube_dimension_value STRING,
  jobrequisition INT64,
  jobrequisition_cube_dimension_value STRING,
  locationofjob_location_1_ STRING,
  locationofjob_location_2_ STRING,
  locationofjob_location_3_ STRING,
  locationofjob_location_4_ STRING,
  locationofjob_cube_dimension_value STRING,
  presentationnamesnapshot STRING,
  repset_variation_id INT64,
  resourcetransition INT64,
  resourcetransition_cube_dimension_value STRING,
  resourcetransitiontasksetduedate STRING,
  status INT64,
  status_state STRING,
  tasksremaining INT64,
  title STRING,
  totaltasks INT64,
  transitiontaskset STRING,
  transitiontaskset_cube_dimension_value STRING,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  workassignment INT64,
  workassignment_cube_dimension_value STRING,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);