CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_edw_useraction_stg (_asoftimestamp STRING ,
actionname STRING ,
audit_entry_id STRING ,
businessclass STRING ,
businessclass_cube_dimension_value STRING ,
create_stamp_actor STRING ,
create_stamp_timestamp STRING ,
description STRING ,
errortext STRING ,
lpl STRING ,
repset_variation_id INT64 ,
status INT64 ,
status_state STRING ,
_type INT64 ,
type_state STRING ,
update_stamp_actor STRING ,
update_stamp_timestamp STRING ,
useraction STRING ,
useraction_cube_dimension_value STRING ,
usereditortype INT64 ,
usereditortype_state STRING,
infor_lastmodified STRING,
dw_last_update_date_time DATETIME);
