CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_jobappworkflowstephis_bct_stg
(
  action STRING,
  asoftimestamp DATETIME,
  actiontakenbycandidate STRING,
  atsworkflow STRING,
  atsworkflowcategory STRING,
  candidate INT64,
  create_stamp_actor STRING,
  create_stamp_timestamp DATETIME,
  createstamp DATETIME,
  daysinstep FLOAT64,
  hcastephistsubstatus STRING,
  hoursinstep FLOAT64,
  hrorganization INT64,
  jobapplication INT64,
  jobappworkflowstephistory INT64,
  jobrequisition INT64,
  jobrequisitionworkflowstep INT64,
  minutesinstep INT64,
  movedby INT64,
  movedbyname STRING,
  movedintimestamp DATETIME,
  movedouttimestamp DATETIME,
  repset_variation_id INT64,
  triggeredby STRING,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp DATETIME,
  updatestamp DATETIME,
  workflowstep STRING,
  jobreqatsworkflowcategory STRING,
  candidatedispositionreason STRING
);