CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_jobapplicationcredential_stg
(
  _action STRING,
  attachment_mimetype STRING,
  attachment_title STRING,
  candidate INT64,
  candidate_cube_dimension_value STRING,
  comments STRING,
  cost FLOAT64,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  credential STRING,
  credential_cube_dimension_value STRING,
  credentialnumber STRING,
  currency STRING,
  currency_cube_dimension_value STRING,
  daterange_begin STRING,
  daterange_end STRING,
  expirationnotice STRING,
  hcajobapplicationcredentialmultistatelic INT64,
  hcajobapplicationcredentialnewsource STRING,
  hcajobapplicationcredentialnewsource_cube_dimension_value STRING,
  hcajobapplicationcredentialnlif INT64,
  hcajobapplicationcredentiastopemailnotification INT64,
  hrorganization STRING,
  hrorganization_cube_dimension_value STRING,
  jobapplication INT64,
  jobapplication_cube_dimension_value STRING,
  jobapplicationcredential INT64,
  jobapplicationcredential_cube_dimension_value STRING,
  jobrequisition INT64,
  jobrequisition_cube_dimension_value STRING,
  organizationsponsored INT64,
  originalcredentialdate STRING,
  other STRING,
  othersource STRING,
  qualificationsource STRING,
  qualificationsource_cube_dimension_value STRING,
  repset_variation_id INT64,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  usedbyatransaction INT64,
  verificationinfo_validationmethod STRING,
  verificationinfo_verificationdate STRING,
  verificationinfo_verified INT64,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);