CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.ats_cust_hrlocation_stg
(
  _action STRING,
  _asoftimestamp STRING,
  active INT64,
  address_country STRING,
  address_county STRING,
  address_deliveryaddress_addressline1 STRING,
  address_deliveryaddress_addressline2 STRING,
  address_deliveryaddress_addressline3 STRING,
  address_deliveryaddress_addressline4 STRING,
  address_municipality STRING,
  address_postalcode STRING,
  address_region STRING,
  address_stateprovince STRING,
  address_type STRING,
  address_type_state STRING,
  contactname_familyname STRING,
  contactname_givenname STRING,
  contactname_middleinitial STRING,
  create_stamp_actor STRING,
  create_stamp_timestamp STRING,
  description STRING,
  emailaddress STRING,
  fax_extension STRING,
  fax_internationalprefix STRING,
  fax_subscribernumber STRING,
  hcahrlocationnotvalidforposition INT64,
  hcahrlocationpublicfacilitydescription STRING,
  hrlocation STRING,
  hrorganization STRING,
  i9worksiteexception STRING,
  lastincidentdate STRING,
  lastinjurydate STRING,
  locationbanner INT64,
  locationdescription STRING,
  locationlogo INT64,
  locationofjob_location_1_ STRING,
  locationofjob_location_2_ STRING,
  locationofjob_location_3_ STRING,
  locationofjob_location_4_ STRING,
  otherlocation STRING,
  phone_extension STRING,
  phone_internationalprefix STRING,
  phone_subscribernumber STRING,
  repset_variation_id INT64,
  thirdpartyi9worksiteid INT64,
  uniqueid STRING,
  update_stamp_actor STRING,
  update_stamp_timestamp STRING,
  usedbyatransaction INT64,
  infor_lastmodified STRING,
  dw_last_update_date_time DATETIME
)
OPTIONS(
  
);