CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.candidate_background_check_wrk
(
  report_sid INT64 NOT NULL,
  valid_from_date DATETIME NOT NULL,
  report_create_date_time DATETIME,
  candidate_first_name STRING,
  candidate_middle_name STRING,
  candidate_last_name STRING,
  social_security_num STRING,
  report_completion_date_time DATETIME,
  report_reopen_date_time DATETIME,
  process_level_code STRING,
  recruitment_requisition_num_text STRING,
  days_elapsed_cnt INT64,
  criminal_search_ordered_cnt INT64,
  criminal_search_pending_cnt INT64,
  motor_vehicle_record_ordered_cnt INT64,
  motor_vehicle_record_pending_cnt INT64,
  employment_verification_ordered_cnt INT64,
  employment_verification_pending_cnt INT64,
  education_verification_ordered_cnt INT64,
  education_verification_pending_cnt INT64,
  license_verification_ordered_cnt INT64,
  license_verification_pending_cnt INT64,
  personal_reference_ordered_cnt INT64,
  personal_reference_pending_cnt INT64,
  sanction_check_ordered_cnt INT64,
  sanction_check_pending_cnt INT64,
  report_num INT64 NOT NULL,
  valid_to_date DATETIME NOT NULL,
  source_system_code STRING ,
  dw_last_update_date_time DATETIME
);