create table if not exists `{{ params.param_hr_stage_dataset_name }}.employee_wrk3`
(
  lawson_company_num INT64 NOT NULL,
  process_level_code STRING,
  dept_code STRING,
  employee_num INT64 NOT NULL,
  hire_date DATE,
  adjusted_hire_date DATE,
  pay_grade_code STRING,
  anniversary_date DATE,
  termination_date DATE,
  fte_percent NUMERIC,
  pay_grade_schedule_code STRING,
  pay_step_num INT64 NOT NULL,
  pay_rate_amt NUMERIC NOT NULL,
  account_unit_num STRING,
  gl_company_num INT64,
  union_code STRING,
  user_level_code STRING,
  location_code STRING,
  employee_34_login_code STRING,
  eff_from_date DATE NOT NULL,
  eff_to_date DATE NOT NULL,
  active_dw_ind STRING NOT NULL,
  security_key_text STRING NOT NULL,
  remote_sw INT64,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL,
  primary_facility_ind STRING,
  employee_sid_lkp_val STRING,
  employee_prsn_sid_lkp_val STRING,
  hr_company_sid_lkp_val STRING,
  process_level_sid_lkp_val STRING,
  department_sid_lkp_val STRING,
  new_hire_date DATE
)
