CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.employee_performance_detail_wrk
(
  evaluation_record_id STRING,
  employee_sid INT64,
  employee_num INT64,
  valid_from_date DATETIME,
  employee_talent_profile_sid INT64,
  review_period_id INT64,
  review_year_num INT64,
  review_period_start_date DATE,
  review_period_end_date DATE,
  performance_plan_id INT64,
  evaluation_workflow_status_id INT64,
  manager_full_name STRING,
  manager_employee_num INT64,
  employee_performance_num INT64,
  employee_performance_rating_id INT64,
  performance_rating_num INT64,
  performance_rating_id INT64,
  employee_smry_competency_num NUMERIC(31, 2),
  employee_smry_competency_rating_id INT64,
  smry_competency_num NUMERIC(31, 2),
  smry_competency_rating_id INT64,
  employee_smry_goal_num NUMERIC(31, 2),
  employee_smry_goal_rating_id INT64,
  smry_goal_num NUMERIC(31, 2),
  smry_goal_rating_id INT64,
  employee_strength_accomplishment_text STRING,
  employee_area_of_improvement_text STRING,
  employee_additional_comment_text STRING,
  strength_accomplishment_text STRING,
  areas_of_improvement_text STRING,
  additional_comment_text STRING,
  lawson_company_num INT64,
  process_level_code STRING,
  source_system_key STRING,
  valid_to_date DATETIME,
  source_system_code STRING,
  dw_last_update_date_time DATETIME NOT NULL
);
