create table if not exists `{{ params.param_hr_stage_dataset_name }}.employee_action_detail_wrk_5_inc`
(
  employee_num INT64,
  company INT64 NOT NULL,
  employee_action_sid INT64 NOT NULL,
  action_code STRING NOT NULL,
  employee_sid INT64 NOT NULL,
  action_sequence_num INT64 NOT NULL,
  action_from_date DATE NOT NULL,
  from_auxiliary_status_code STRING,
  from_dept_code STRING,
  from_employee_pay_rate_amount NUMERIC,
  from_employee_work_schedule_code STRING,
  from_job_code STRING,
  from_location_code STRING,
  from_overtime_plan_code STRING,
  from_position_code STRING,
  from_position_level_num INT64,
  from_process_level_code STRING,
  from_payment_frequency NUMERIC,
  from_payment_grade_code STRING,
  from_payment_step_num NUMERIC,
  from_salary_class_code STRING,
  from_schedule_code STRING,
  from_standard_hour NUMERIC,
  from_supervisor_code STRING,
  from_union_code STRING,
  from_user_level STRING,
  from_excemption_flag STRING,
  from_expense_account_unit STRING,
  from_expense_company INT64,
  from_expense_sub_account_num INT64,
  hr_code_desc STRING,
  last_update_date DATE NOT NULL,
  last_transfer_eff_date DATE,
  reason_desc STRING,
  to_payment_frequency NUMERIC,
  to_auxiliary_status_code STRING,
  to_dept_code STRING,
  to_employee_pay_rate_amt NUMERIC,
  to_employee_schedule_code STRING,
  to_job_code STRING,
  to_location_code STRING,
  to_overtime_plan_code STRING,
  to_position_code STRING,
  to_position_level_num INT64,
  to_process_level_code STRING,
  to_pay_grade_code STRING,
  to_pay_step_num NUMERIC,
  to_salary_class_code STRING,
  to_schedule_code STRING,
  to_standard_hour NUMERIC,
  to_supervisor_code STRING,
  to_union_code STRING,
  to_user_level STRING,
  to_exemption_flag STRING,
  to_expense_account_unit STRING,
  to_expense_sub_account_num INT64,
  transfer_termination_flag STRING,
  to_expense_company_num INT64,
  lawson_company_num INT64 NOT NULL,
  process_level_code STRING NOT NULL,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
