CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.employee_talent_profile_wrk
(
  employee_talent_profile_sid INT64 NOT NULL,
  employee_sid INT64,
  employee_first_name STRING,
  employee_middle_name STRING,
  employee_last_name STRING,
  employee_num INT64 NOT NULL,
  employee_3_4_login_code STRING,
  job_family_text STRING,
  str1 STRING,
  job_code STRING,
  job_code_sid INT64,
  position_code_text STRING,
  position_code STRING,
  position_sid INT64,
  position_title_text STRING,
  org_hierarchy_text STRING,
  manager_name STRING,
  manager_employee_num INT64,
  travel_willingness_id INT64,
  travel_willingness_pct_range_text STRING,
  travel_location_text STRING,
  relocation_willingness_id INT64,
  relocation_location_text STRING,
  calibrated_performance_rating_id INT64,
  overall_performance_rating_id INT64,
  smry_competency_rating_id INT64,
  smry_goal_rating_id INT64,
  employee_promotability_interest_id INT64,
  potential_performance_id INT64,
  future_role_1_leadership_level_id INT64,
  future_role_1_org_size_id INT64,
  future_role_1_timeframe_id INT64,
  future_role_1_role_id INT64,
  future_role_2_leadership_level_id INT64,
  future_role_2_org_size_id INT64,
  future_role_2_timeframe_id INT64,
  future_role_2_role_id INT64,
  flight_risk_probability_id INT64,
  flight_risk_timeframe_id INT64,
  flight_risk_driver_text STRING,
  flight_risk_secondary_driver_text STRING,
  calibration_session_created_date DATE,
  calibration_session_name STRING,
  calibration_session_last_mod_date_time DATETIME,
  calibration_session_published_date DATE,
  calibration_session_created_by_name STRING,
  company_tenure_text STRING,
  position_tenure_text STRING,
  lawson_company_num INT64 NOT NULL,
  process_level_code STRING NOT NULL,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL,
  calibration_box_id INT64,
  last_pub_calibration_session STRING,
  last_pub_calibration_box_rank STRING
);
