CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.employee_goal_detail_wrk
(
  employee_goal_detail_sid INT64,
  employee_talent_profile_sid INT64,
  employee_sid INT64,
  employee_num INT64,
  employee_goal_year_num INT64,
  goal_name STRING,
  goal_category_id INT64,
  goal_weight_pct INT64,
  expected_result_text STRING,
  goal_measurement_text STRING,
  goal_status_id INT64,
  goal_progress_status_id INT64,
  goal_performance_plan_id INT64,
  goal_due_date DATE,
  user_defined_date DATE,
  review_year_num INT64,
  review_period_end_date DATE,
  review_period_start_date DATE,
  review_period_id INT64,
  manager_goal_performance_rating_id INT64,
  manager_goal_performance_rating_num INT64,
  employee_goal_performance_rating_id INT64,
  employee_goal_performance_rating_num INT64,
  lawson_company_num INT64,
  process_level_code STRING,
  source_system_key STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
);
