CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.hca_pat_resp_detail (
hca_unique STRING
, survey_id NUMERIC(18,0)
, adj_samp STRING
, survey_type STRING
, pg_unit STRING
, dis_date DATE
, rec_date DATE
, resp_mode STRING
, quest_id STRING
, survey STRING
, client_id STRING
, last_name STRING
, middle_name STRING
, first_name STRING
, address_line1 STRING
, address_line2 STRING
, city STRING
, state STRING
, zipcode STRING
, phone STRING
, drg STRING
, gender STRING
, race STRING
, dob DATE
, lang STRING
, mrn STRING
, unique_id STRING
, loc_code STRING
, attending_phys_id STRING
, admission_source STRING
, admission_date DATE
, admission_time STRING
, discharge_date DATE
, discharge_time STRING
, discharge_status STRING
, unit STRING
, service STRING
, payor STRING
, room STRING
, length_of_stay INT64
, bed STRING
, is_hospitalist STRING
, fasttrack STRING
, email STRING
, hospitalist_id_1 STRING
, hospitalist_id_2 STRING
, is_er_admission STRING
, facility_id STRING
, unit_code_id STRING
, patient_type STRING
, medicare_provider_num STRING
, medicare_provider_npi STRING
, facility_name STRING
, nurse_station STRING
, drg_type STRING
, service_category STRING
, mdc STRING
, diag_category STRING
, patient_age STRING
, eligible STRING
, exclusion_flag STRING
, financial_plan STRING
, admission_phys_code STRING
, primary_icd9_code STRING
, icd_code_version STRING
, cpt_code STRING
, iped_flag STRING
, admission_type STRING
, company_code STRING
, diag_1 STRING
, diag_2 STRING
, diag_3 STRING
, diag_4 STRING
, diag_5 STRING
, diag_6 STRING
, diag_7 STRING
, diag_8 STRING
, diag_9 STRING
, diag_10 STRING
, diag_11 STRING
, diag_12 STRING
, diag_13 STRING
, diag_14 STRING
, diag_15 STRING
, bill_generated_date DATE
, surg_proc_code_1 STRING
, surg_proc_code_2 STRING
, surg_proc_code_3 STRING
, surgeon_name_1 STRING
, surgeon_name_2 STRING
, surgeon_name_3 STRING
, attending_phys_name STRING
, hospitalist_flag STRING
, consulting_phys_id STRING
, consulting_phys_name STRING
, coid STRING
, iped STRING
, cpt_flag STRING
, division_coid STRING
, market_coid STRING
, surg_proc_code_1_icd STRING
, surg_proc_code_2_icd STRING
, surg_proc_code_3_icd STRING
, ethnicity STRING
, hipps_code STRING
, mode_of_arrivl STRING
, day_of_week STRING
, cpt_code_2 STRING
, cpt_code_3 STRING
, cpt_code_4 STRING
, cpt_code_5 STRING
, cpt_code_6 STRING
, deceased_flag STRING
, no_publicity STRING
, prim_cpt_svc_date DATE
, ptype STRING
, qtype STRING
, category STRING
, dw_last_update_date_time DATETIME
)
  ;

