create table if not exists `{{ params.param_hr_stage_dataset_name }}.histerr`
(
  action_code STRING NOT NULL,
  action_nbr INT64 NOT NULL,
  company INT64 NOT NULL,
  effect_date DATE NOT NULL,
  employee INT64 NOT NULL,
  fld_nbr INT64 NOT NULL,
  obj_id NUMERIC NOT NULL,
  seq_nbr INT64 NOT NULL,
  action_type STRING,
  act_obj_id NUMERIC,
  annual_hours INT64,
  annual_salary NUMERIC,
  ant_end_date DATE,
  a_value STRING,
  base_currency STRING,
  base_nd INT64,
  base_pay_rate NUMERIC,
  currency_code STRING,
  curr_nd INT64,
  data_type STRING,
  date_stamp DATE,
  date_stamp2 DATE,
  d_value DATE,
  herset5_ss_sw STRING,
  nbr_fte NUMERIC,
  new_value STRING,
  n_value NUMERIC,
  pos_level INT64,
  reason_01 STRING,
  reason_02 STRING,
  salary_class STRING,
  time_stamp TIME,
  time_stamp2 TIME,
  user_id STRING,
  user_id2 STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
