create table if not exists `{{ params.param_hr_stage_dataset_name }}.job_position_wrk`
(
  position_sid INT64 NOT NULL,
  eff_from_date DATE NOT NULL,
  valid_from_date DATETIME NOT NULL,
  link_supervisor_sid INT64 NOT NULL,
  supervisor_sid INT64 NOT NULL,
  job_code_sid INT64 NOT NULL,
  hr_company_sid INT64 NOT NULL,
  lawson_company_num INT64 NOT NULL,
  position_change_reason_code STRING,
  location_code STRING,
  pay_grade_code STRING,
  position_code STRING NOT NULL,
  account_unit_num STRING,
  gl_company_num INT64,
  overtime_plan_code STRING NOT NULL,
  position_code_desc STRING NOT NULL,
  company_position_eff_from_date DATE,
  company_position_eff_to_date DATE,
  pay_grade_schedule_code STRING,
  pay_step_num INT64,
  union_code STRING,
  shift_num INT64,
  eff_to_date DATE NOT NULL,
  valid_to_date DATETIME NOT NULL,
  process_level_code STRING NOT NULL,
  active_dw_ind STRING NOT NULL,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL,
  exempt_emp STRING,
  schedule_work_code STRING,
  user_level_code STRING,
  dept_sid INT64,
  lawson_object_id INT64
)
