create table if not exists `{{ params.param_hr_stage_dataset_name }}.jobcode`
(
  job_code STRING NOT NULL,
  company INT64 NOT NULL,
  academic_rank STRING,
  active_flag STRING,
  annual_hours INT64,
  approved_by INT64,
  base_beg_sal NUMERIC,
  base_currency STRING,
  base_end_sal NUMERIC,
  base_market NUMERIC,
  base_mid_sal NUMERIC,
  base_nd INT64,
  base_pay_rate NUMERIC,
  beg_sal_range NUMERIC,
  ca_wc_class STRING,
  currency_code STRING,
  curr_nd INT64,
  department STRING,
  description STRING,
  desc_date DATE,
  dir_ind_job INT64,
  eeo_cat STRING,
  eeo_sub_code INT64,
  effective_date DATE,
  effect_date DATE,
  end_sal_range NUMERIC,
  eval_date DATE,
  exempt STRING,
  exp_account INT64,
  exp_acct_unit STRING,
  exp_dist_co INT64,
  exp_sub_acct INT64,
  gender_class STRING,
  high_ed_cat INT64,
  high_ed_subcat STRING,
  job_class STRING,
  last_cmt_seq INT64,
  l_atjbc_ss_sw STRING,
  l_index STRING,
  m3_flag STRING,
  market_date DATE,
  market_salary NUMERIC,
  mid_sal_range NUMERIC,
  min_hire_age INT64,
  obj_id NUMERIC,
  occup_group STRING,
  pay_grade STRING,
  pay_rate NUMERIC,
  points NUMERIC,
  column_12 STRING,
  process_level STRING,
  rate_override STRING,
  reports_to INT64,
  r_schedule STRING,
  salary_class STRING,
  tenure_elig STRING,
  tipped STRING,
  wc_class STRING,
  web_type STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
