CREATE TABLE IF NOT EXISTS `{{ params.param_hr_stage_dataset_name }}.kronos_combined_edw_punchdetail_rej`
(
  kronos_clock_library STRING,
  employee_num INT64 NOT NULL,
  kronos_time_id NUMERIC(29) NOT NULL,
  clock_code STRING,
  actual_time_id DATETIME,
  actual_time_out DATETIME,
  actual_elapsed_time_hours NUMERIC(32, 3),
  rounded_time_in DATETIME,
  rounded_time_out DATETIME,
  rounded_elapsed_time_hours NUMERIC(32, 3),
  approval_date DATETIME,
  approver_3_4 STRING,
  shift_start_date DATETIME,
  pay_type STRING,
  long_meal STRING,
  other_dept STRING,
  out_of_ppd STRING,
  short_meal STRING,
  department STRING,
  hr_company INT64,
  process_level STRING,
  ppd_start_date DATETIME,
  ppd_end_date DATETIME,
  posted_ind STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
);