create table if not exists `{{ params.param_hr_stage_dataset_name }}.padict`
(
  fld_nbr INT64 NOT NULL,
  case_flag STRING,
  cmp_field STRING,
  column_heading STRING,
  currency_flag STRING,
  data_type STRING,
  db_file STRING,
  decimals INT64,
  delivered STRING,
  dfl_avail_flag STRING,
  header_size INT64,
  heading_01 STRING,
  heading_02 STRING,
  item_name STRING,
  log_avail_flag STRING,
  min_size INT64,
  pers_action STRING,
  pers_grp STRING,
  prt_type STRING,
  req_avail_flag STRING,
  req_key STRING,
  setup_flag STRING,
  size INT64,
  topic STRING,
  topic_flag STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
