create table if not exists `{{ params.param_hr_stage_dataset_name }}.paemppos`
(
  effect_date DATE NOT NULL,
  pos_level INT64 NOT NULL,
  employee INT64,
  company INT64 NOT NULL,
  acct_category STRING,
  activity STRING,
  annual_hours INT64,
  bargain_unit STRING,
  base_currency STRING,
  base_nd INT64,
  base_pay_rate NUMERIC,
  currency_code STRING,
  curr_nd INT64,
  date_assign DATE,
  date_stamp DATE,
  department STRING,
  end_date DATE,
  exp_account INT64,
  exp_acct_unit STRING,
  exp_company INT64,
  exp_sub_acct INT64,
  fte NUMERIC,
  job_code STRING,
  locat_code STRING,
  l_atpep_ss_sw STRING,
  l_index STRING,
  pay_grade STRING,
  pay_rate NUMERIC,
  pay_step INT64,
  pepset2_ss_sw STRING,
  pepset6_ss_sw STRING,
  pepset7_ss_sw STRING,
  pepset9_ss_sw STRING,
  position STRING,
  pos_eff_dt DATE,
  process_level STRING,
  pro_rate_a_sal NUMERIC,
  r_schedule STRING,
  shift INT64,
  supervisor STRING,
  supervisor_ind STRING,
  time_stamp STRING,
  union_code STRING,
  user_amount NUMERIC,
  user_id STRING,
  user_level STRING,
  work_sched STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
