create table if not exists `{{ params.param_hr_stage_dataset_name }}.pagrdi`
(
  company INT64,
  employee INT64,
  pagrdistep_type STRING,
  griev_dis_nbr INT64,
  description STRING,
  r_date DATE,
  griev_dis_cat STRING,
  report_date DATE,
  reports_by INT64,
  reports_by_name STRING,
  griev_dis_stat STRING,
  outcome STRING,
  outcome_date DATE,
  days_out INT64,
  cost NUMERIC,
  process_level STRING,
  department STRING,
  locat_code STRING,
  job_code STRING,
  shift INT64,
  supervisor_emp INT64,
  union_code STRING,
  bargain_unit STRING,
  contact_nbr INT64,
  contact_name STRING,
  phone_country STRING,
  phone STRING,
  phone_ext STRING,
  r_comment STRING,
  date_stamp DATE,
  time_stamp TIME,
  user_id STRING,
  currency_code STRING,
  curr_ind INT64,
  base_currency STRING,
  base_nd INT64,
  base_amount NUMERIC,
  l_index STRING,
  l_atpgi_ss_sw STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
