create table if not exists `{{ params.param_hr_stage_dataset_name }}.paposition`
(
  effect_date DATE NOT NULL,
  position STRING NOT NULL,
  company INT64 NOT NULL,
  acct_category STRING,
  activity STRING,
  annual_hours INT64,
  bargain_unit STRING,
  base_currency STRING,
  base_nd INT64,
  base_pay_rate NUMERIC,
  chg_reason STRING,
  create_date DATE,
  create_time TIME,
  create_user STRING,
  currency_code STRING,
  curr_nd INT64,
  date_stamp DATE,
  department STRING,
  description STRING,
  encumber_flag STRING,
  end_date DATE,
  exempt_emp STRING,
  exp_account INT64,
  exp_acct_unit STRING,
  exp_company INT64,
  exp_sub_acct INT64,
  job_code STRING,
  locat_code STRING,
  l_atpos_ss_sw STRING,
  l_index STRING,
  obj_id NUMERIC,
  ot_plan_code STRING,
  pay_frequency INT64,
  pay_grade STRING,
  pay_rate NUMERIC,
  pay_step INT64,
  posit_status INT64,
  posset4_ss_sw STRING,
  process_level STRING,
  r_schedule STRING,
  salary_class STRING,
  sec_location STRING,
  sec_lvl INT64,
  shift INT64,
  supervisor STRING,
  supervisor_ind STRING,
  supervisor_lnk STRING,
  time_stamp TIME,
  union_code STRING,
  update_flag STRING,
  user_id STRING,
  user_level STRING,
  work_sched STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
