create table if not exists `{{ params.param_hr_stage_dataset_name }}.pcodesdtl`
(
  code STRING NOT NULL,
  type STRING NOT NULL,
  addr1 STRING,
  addr2 STRING,
  addr3 STRING,
  addr4 STRING,
  city STRING,
  cma_code STRING,
  contact_first STRING,
  contact_last STRING,
  contact_mi STRING,
  country_code STRING,
  county STRING,
  date_stamp DATE,
  email_address STRING,
  facility_name STRING,
  fax_country STRING,
  fax_ext STRING,
  fax_number STRING,
  hipaa_id_nbr STRING,
  hipaa_id_type INT64,
  numeric1 NUMERIC,
  numeric2 NUMERIC,
  phone STRING,
  phone_country STRING,
  phone_ext STRING,
  report_prov STRING,
  state STRING,
  supp_addr1 STRING,
  supp_addr2 STRING,
  supp_addr3 STRING,
  supp_addr4 STRING,
  supp_city STRING,
  supp_cntry_cd STRING,
  supp_state STRING,
  supp_zip STRING,
  time_stamp TIME,
  user1 STRING,
  user2 STRING,
  user_id STRING,
  zip STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
