CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.performance_ratings_report_reject
(
  employee_id STRING,
  rev_period STRING,
  rev_period_start_date DATE,
  rev_period_end_date DATE,
  rev_year STRING,
  plan_name STRING,
  eval_workflow_state STRING,
  manager_record STRING,
  manager_employee_id_record STRING,
  emp_perf_rat_num_val STRING,
  emp_perf_rat_scale_val STRING,
  perf_rat_numeric_val STRING,
  perf_rat_scale_val STRING,
  emp_smry_comp_rat_num_val STRING,
  emp_smry_comp_rat_scale_val STRING,
  sumry_comp_rat_numeric_val STRING,
  sumry_comp_rat_scale_val STRING,
  emp_smry_goal_rat_num_val STRING,
  emp_smry_goal_rat_scale_val STRING,
  smry_goal_rating_num_val STRING,
  smry_goal_rat_scale_val STRING,
  emp_strengths_accomplishments STRING,
  emp_area_improvement STRING,
  employee_additional_comments STRING,
  strengths_accomplishments STRING,
  areas_improvement STRING,
  additional_comments STRING,
  evaluation_record_id STRING,
  dw_last_update_date_time DATETIME NOT NULL,
  reject_reason STRING,
  reject_stg_tbl_nm STRING
);
