create table if not exists `{{ params.param_hr_stage_dataset_name }}.persacthst`
(
  action_nbr INT64 NOT NULL,
  action_code STRING NOT NULL,
  effect_date DATE NOT NULL,
  employee INT64 NOT NULL,
  company INT64 NOT NULL,
  action_type STRING,
  action_upd STRING,
  ant_end_date DATE,
  create_date DATE,
  create_time TIME,
  create_user STRING,
  date_stamp DATE,
  edm_effect_dt DATE,
  edm_end_date DATE,
  error_flag STRING,
  hist_corr_flag STRING,
  l_atpah_ss_sw STRING,
  l_index STRING,
  obj_id NUMERIC,
  pos_level INT64,
  reason_01 STRING,
  reason_02 STRING,
  update_benefit STRING,
  update_req_ded STRING,
  upd_abs_mgmt STRING,
  user_id STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
