CREATE TABLE IF NOT EXISTS {{ params.param_hr_stage_dataset_name }}.precheck_stg
(
  report_number INT64,
  report_created_date STRING,
  report_status STRING,
  applicant_last_name STRING,
  applicant_first_name STRING,
  applicant_middle_name STRING,
  ssn STRING,
  report_reopened_date STRING,
  report_completion_date STRING,
  processlevel STRING,
  requisition STRING,
  account_name STRING,
  elapsed_days STRING,
  criminal_searches_ordered STRING,
  criminal_searches_pending STRING,
  mvr_ordered STRING,
  mvr_pending STRING,
  emp_verifications_ordered STRING,
  emp_verifications_pending STRING,
  edu_verifications_ordered STRING,
  edu_verifications_pending STRING,
  license_verifications_ordered STRING,
  license_verifications_pending STRING,
  personal_references_ordered STRING,
  personal_references_pending STRING,
  sanctioncheck_ordered STRING,
  sanctioncheck_pending STRING,
  percentage_completed STRING,
  resultsurl STRING,
  dw_last_update_date_time DATETIME
); 