create table if not exists `{{ params.param_hr_stage_dataset_name }}.reporting_xfer_termn`
(
  actn_cd STRING NOT NULL,
  actn_num INT64 NOT NULL,
  cmpy INT64 NOT NULL,
  eff_dt DATE NOT NULL,
  empl INT64 NOT NULL,
  dw_cret_dt DATE NOT NULL,
  dw_lst_updt_dt DATE NOT NULL,
  dw_prgm_id STRING NOT NULL,
  xfer_termn_flg STRING,
  lst_updt_dt DATE,
  resn_1 STRING,
  hr_cd_desc STRING,
  lst_xfer_eff_dt DATE,
  from_prcs_lvl STRING,
  from_dept STRING,
  from_job_cd STRING,
  from_posn STRING,
  from_supv STRING,
  from_py_grd STRING,
  from_empl_py_rt NUMERIC(33, 4),
  from_std_hr NUMERIC(31, 2),
  from_aux_stts STRING,
  from_empl_schd STRING,
  from_py_freq INT64,
  from_loc_cd STRING,
  from_sal_cl STRING,
  from_xmpt_flg STRING,
  from_ot_pln_cd STRING,
  from_xpns_acct_unit STRING,
  from_py_stp INT64,
  from_xpns_cmpy INT64,
  from_xpns_sub_acct INT64,
  from_sched STRING,
  from_unon_cd STRING,
  from_user_lvl STRING,
  from_posn_lvl INT64,
  to_prcs_lvl STRING,
  to_dept STRING,
  to_job_cd STRING,
  to_posn STRING,
  to_supv STRING,
  to_py_grd STRING,
  to_empl_py_rt NUMERIC(33, 4),
  to_std_hr NUMERIC(31, 2),
  to_aux_stts STRING,
  to_empl_schd STRING,
  t0_py_freq INT64,
  to_loc_cd STRING,
  to_sal_cl STRING,
  to_xmpt_flg STRING,
  to_ot_pln_cd STRING,
  to_xpns_acct_unit STRING,
  to_py_stp INT64,
  to_xpns_cmpy INT64,
  to_xpns_sub_acct INT64,
  to_schd STRING,
  to_unon_cd STRING,
  to_user_lvl STRING,
  to_posn_lvl INT64
)
