create table if not exists `{{ params.param_hr_stage_dataset_name }}.requisition_wrk0`
(
  row_rank INT64,
  sk NUMERIC,
  eff_from_date DATE,
  date_stamp DATE,
  hr_company_sid INT64,
  application_status_sid INT64,
  lawson_company_num INT64,
  location_code STRING,
  requisition_num INT64,
  requisition_desc STRING,
  requisition_eff_date DATE,
  requisition_open_date DATE,
  requisition_closed_date DATE,
  requisition_origination_date DATE,
  originator_login_3_4_code STRING,
  position_needed_date DATE,
  job_opening_cnt INT64,
  open_fte_percent NUMERIC,
  filled_fte_percent NUMERIC,
  last_update_date DATE,
  replacement_employee_num INT64,
  replacement_employee_sid INT64,
  replacement_flag STRING,
  special_requirement_text STRING,
  work_schedule_code STRING,
  union_code STRING,
  active_dw_ind STRING,
  security_key_text STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME,
  process_level_code STRING
)
