create table if not exists `{{ params.param_hr_stage_dataset_name }}.review`
(
  company INT64 NOT NULL,
  employee STRING,
  seq_nbr INT64,
  sched_date DATE,
  code STRING,
  actual_date DATE,
  rating STRING,
  last_name STRING,
  first_name STRING,
  middle_init STRING,
  by_employee INT64,
  date_stamp DATE,
  time_stamp TIME,
  user_id STRING,
  model_name STRING,
  percentil NUMERIC,
  perf_score NUMERIC,
  perf_weighting NUMERIC,
  goal_score NUMERIC,
  goal_weighting NUMERIC,
  total_score NUMERIC,
  description STRING,
  rev_schedule STRING,
  next_review DATE,
  next_rev_code STRING,
  last_review DATE,
  review_flag INT64,
  apprvl_status INT64,
  auto_add_rev INT64,
  l_index STRING,
  l_atrev_ss_sw STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
