create table if not exists {{ params.param_hr_stage_dataset_name }}.taleo_jobinformation_temp
(
  number NUMERIC(29),
  additionalinformation STRING,
  autodeclinecandidates NUMERIC(29),
  autorejectcandidates NUMERIC(29),
  billratemedian NUMERIC(32, 3),
  billratenottoexceed NUMERIC(32, 3),
  creationdate DATETIME,
  descriptionbaselocale NUMERIC(29),
  descriptionexternalhtml STRING,
  descriptioninternalhtml STRING,
  externalbonusamount BIGNUMERIC(53, 15),
  externalbonustracking NUMERIC(29),
  externalqualificationhtml STRING,
  highquartilesalary BIGNUMERIC(53, 15),
  internalbonusamount BIGNUMERIC(53, 15),
  internalbonustracking NUMERIC(29),
  internalqualificationhtml STRING,
  jobboarddescription STRING,
  jobgrade STRING,
  lastmodifieddate DATETIME,
  lowquartilesalary BIGNUMERIC(53, 15),
  midpointsalary BIGNUMERIC(53, 15),
  numbertohire NUMERIC(29),
  othercosts STRING,
  relocationcosts STRING,
  sourcingbudget STRING,
  title STRING,
  travelcosts STRING,
  unlimitedhire NUMERIC(29),
  bonuscurrency_number NUMERIC(29),
  budgetcurrency_number NUMERIC(29),
  citizenshipstatus_number NUMERIC(29),
  contingentcurrency_number NUMERIC(29),
  creator_userno NUMERIC(29),
  cswworkflow_number NUMERIC(29),
  eejobgroup_number NUMERIC(29),
  eejobcategory_number NUMERIC(29),
  eeestablishment_number NUMERIC(29),
  hiretype_number NUMERIC(29),
  jobfield_number NUMERIC(29),
  jobinformationgroup_number NUMERIC(29),
  joblevel_number NUMERIC(29),
  jobrole_number NUMERIC(29),
  jobschedule_number NUMERIC(29),
  jobshift_number NUMERIC(29),
  jobtype_number NUMERIC(29),
  offerparameter_number NUMERIC(29),
  organization_number NUMERIC(29),
  overtimestatus_number NUMERIC(29),
  primarylocation_number NUMERIC(29),
  program_number NUMERIC(29),
  recruiterowner_userno NUMERIC(29),
  studylevel_number NUMERIC(29),
  willingnesstotravel_number NUMERIC(29),
  matched_from STRING,
  ispostedexternally STRING,
  ispostedinternally STRING,
  postingboardtype STRING,
  postingdate STRING,
  postingstatus STRING,
  unpostingdate STRING,
  jobboardid STRING,
  jobboard STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
);