CREATE TABLE IF NOT EXISTS `{{ params.param_hr_stage_dataset_name }}.time_entry_wrk`
(
  employee_num INT64 NOT NULL,
  kronos_num NUMERIC(29) NOT NULL,
  clock_library_code STRING NOT NULL,
  valid_from_date DATETIME NOT NULL,
  valid_to_date DATETIME,
  clock_code STRING,
  clock_in_time DATETIME,
  clock_out_time DATETIME,
  clocked_hour_num NUMERIC(32, 3),
  rounded_clock_in_time DATETIME,
  rounded_clock_out_time DATETIME,
  rounded_clocked_hour_num NUMERIC(32, 3),
  time_approval_date_time DATETIME,
  time_approver_34_login_code STRING,
  scheduled_shift_date_time DATETIME,
  pay_period_end_date_time DATETIME,
  pay_period_start_date_time DATETIME,
  pay_type_code STRING,
  long_meal_code STRING,
  other_dept_code STRING,
  out_of_pay_period_code STRING,
  short_meal_code STRING,
  dept_code STRING,
  lawson_company_num INT64 NOT NULL,
  process_level_code STRING NOT NULL,
  source_system_code STRING NOT NULL,
  posted_ind STRING,
  dw_last_update_date_time DATETIME NOT NULL
);