create table if not exists `{{ params.param_hr_stage_dataset_name }}.zvuserdata`
(
  company INT64,
  process_level STRING,
  department STRING,
  job_code STRING,
  position_ud STRING,
  effect_date DATE,
  a_field STRING,
  employee INT64,
  first_name STRING,
  middle_name STRING,
  last_name STRING,
  addr1 STRING,
  addr2 STRING,
  city STRING,
  state STRING,
  zip STRING,
  country_code STRING,
  email_address STRING,
  fica_nbr STRING,
  emp_status STRING,
  birthdate DATE,
  wk_phone_nbr STRING,
  comp_nbr STRING,
  end_date DATE,
  hca_span_code STRING,
  term_date DATE,
  date_hired DATE,
  hca_dept INT64,
  dw_last_update_date_time DATETIME NOT NULL
)
