
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.ECW_FactClaim837P AS target
USING {{ params.param_psc_stage_dataset_name }}.ECW_FactClaim837P AS source
ON target.ID = source.ID
WHEN MATCHED THEN
  UPDATE SET
  target.ID = source.ID,
 target.FileName = TRIM(source.FileName),
 target.ISA01Qualifier = TRIM(source.ISA01Qualifier),
 target.ISA02Info = TRIM(source.ISA02Info),
 target.ISA03SecurityInfo = TRIM(source.ISA03SecurityInfo),
 target.ISA04SecurityInfo = TRIM(source.ISA04SecurityInfo),
 target.ISA05QualifierID = TRIM(source.ISA05QualifierID),
 target.ISA06SenderID = TRIM(source.ISA06SenderID),
 target.ISA07QualifierID = TRIM(source.ISA07QualifierID),
 target.ISA08ReceiverID = TRIM(source.ISA08ReceiverID),
 target.ISA09Date = TRIM(source.ISA09Date),
 target.ISA10Time = TRIM(source.ISA10Time),
 target.ISA11StandardsID = TRIM(source.ISA11StandardsID),
 target.ISA12VersionNum = TRIM(source.ISA12VersionNum),
 target.ISA13ContolNum = TRIM(source.ISA13ContolNum),
 target.ISA14AckRequested = TRIM(source.ISA14AckRequested),
 target.ISA15UsageID = TRIM(source.ISA15UsageID),
 target.GS01ID = TRIM(source.GS01ID),
 target.GS02SendersCode = TRIM(source.GS02SendersCode),
 target.GS03ReceiversCode = TRIM(source.GS03ReceiversCode),
 target.GS04Date = TRIM(source.GS04Date),
 target.GS05Time = TRIM(source.GS05Time),
 target.GS06ControlNum = TRIM(source.GS06ControlNum),
 target.GS07ResponsibleAgencyCode = TRIM(source.GS07ResponsibleAgencyCode),
 target.GS08IndustryID = TRIM(source.GS08IndustryID),
 target.ST01ID = TRIM(source.ST01ID),
 target.ST02ControlNum = TRIM(source.ST02ControlNum),
 target.ST03ImplemntaionRef = TRIM(source.ST03ImplemntaionRef),
 target.BHT01Source = TRIM(source.BHT01Source),
 target.BHT02PurposeCode = TRIM(source.BHT02PurposeCode),
 target.BHT03RefID = TRIM(source.BHT03RefID),
 target.BHT04Date = TRIM(source.BHT04Date),
 target.BHT05Time = TRIM(source.BHT05Time),
 target.BHT06Type = TRIM(source.BHT06Type),
 target.SubmitterName01ID = TRIM(source.SubmitterName01ID),
 target.SubmitterName02Type = TRIM(source.SubmitterName02Type),
 target.SubmitterName03Name = TRIM(source.SubmitterName03Name),
 target.SubmitterName04 = TRIM(source.SubmitterName04),
 target.SubmitterName05 = TRIM(source.SubmitterName05),
 target.SubmitterName06 = TRIM(source.SubmitterName06),
 target.SubmitterName07 = TRIM(source.SubmitterName07),
 target.SubmitterName08CodeQualifier = TRIM(source.SubmitterName08CodeQualifier),
 target.SubmitterName09Code = TRIM(source.SubmitterName09Code),
 target.SubmitterNamePER01Contact = TRIM(source.SubmitterNamePER01Contact),
 target.SubmitterNamePER02Name = TRIM(source.SubmitterNamePER02Name),
 target.SubmitterNamePER03Qualifier = TRIM(source.SubmitterNamePER03Qualifier),
 target.SubmitterNamePER04Num = TRIM(source.SubmitterNamePER04Num),
 target.SubmitterNamePER05Qualifier = TRIM(source.SubmitterNamePER05Qualifier),
 target.SubmitterNamePER06Num = TRIM(source.SubmitterNamePER06Num),
 target.SubmitterNamePER07Mail = TRIM(source.SubmitterNamePER07Mail),
 target.SubmitterNamePER08Email = TRIM(source.SubmitterNamePER08Email),
 target.ReceiverName01Code = TRIM(source.ReceiverName01Code),
 target.ReceiverName02Qualifier = TRIM(source.ReceiverName02Qualifier),
 target.ReceiverName03Name = TRIM(source.ReceiverName03Name),
 target.ReceiverName04 = TRIM(source.ReceiverName04),
 target.ReceiverName05 = TRIM(source.ReceiverName05),
 target.ReceiverName06 = TRIM(source.ReceiverName06),
 target.ReceiverName07 = TRIM(source.ReceiverName07),
 target.ReceiverName08Qualifier = TRIM(source.ReceiverName08Qualifier),
 target.ReceiverName09Code = TRIM(source.ReceiverName09Code),
 target.SBRInfo01Seq = TRIM(source.SBRInfo01Seq),
 target.SBRInfo02Rel = TRIM(source.SBRInfo02Rel),
 target.SBRInfo03ID = TRIM(source.SBRInfo03ID),
 target.SBRInfo04 = TRIM(source.SBRInfo04),
 target.SBRInfo05 = TRIM(source.SBRInfo05),
 target.SBRInfo06 = TRIM(source.SBRInfo06),
 target.SBRInfo07 = TRIM(source.SBRInfo07),
 target.SBRInfo08 = TRIM(source.SBRInfo08),
 target.SBRInfo09 = TRIM(source.SBRInfo09),
 target.SubscriberName01Code = TRIM(source.SubscriberName01Code),
 target.SubscriberName02Type = TRIM(source.SubscriberName02Type),
 target.SubscriberName03LastName = TRIM(source.SubscriberName03LastName),
 target.SubscriberName04FirstName = TRIM(source.SubscriberName04FirstName),
 target.SubscriberName05MiddleName = TRIM(source.SubscriberName05MiddleName),
 target.SubscriberName06 = TRIM(source.SubscriberName06),
 target.SubscriberName07 = TRIM(source.SubscriberName07),
 target.SubscriberName08Qualifier = TRIM(source.SubscriberName08Qualifier),
 target.SubscriberName09MemberID = TRIM(source.SubscriberName09MemberID),
 target.SubscriberNameN301Address1 = TRIM(source.SubscriberNameN301Address1),
 target.SubscriberNameN302Address2 = TRIM(source.SubscriberNameN302Address2),
 target.SubscriberNameN401City = TRIM(source.SubscriberNameN401City),
 target.SubscriberNameN402State = TRIM(source.SubscriberNameN402State),
 target.SubscriberNameN403ZipCode = TRIM(source.SubscriberNameN403ZipCode),
 target.SubscriberNameDMG01Format = TRIM(source.SubscriberNameDMG01Format),
 target.SubscriberNameDMG02DOB = TRIM(source.SubscriberNameDMG02DOB),
 target.SubscriberNameDMG03Gender = TRIM(source.SubscriberNameDMG03Gender),
 target.PayerName01Code = TRIM(source.PayerName01Code),
 target.PayerName02Type = TRIM(source.PayerName02Type),
 target.PayerName03Iplan = TRIM(source.PayerName03Iplan),
 target.PayerName04 = TRIM(source.PayerName04),
 target.PayerName05 = TRIM(source.PayerName05),
 target.PayerName06 = TRIM(source.PayerName06),
 target.PayerName07 = TRIM(source.PayerName07),
 target.PayerName08Qualifier = TRIM(source.PayerName08Qualifier),
 target.PayerName09MemberID = TRIM(source.PayerName09MemberID),
 target.PayerNameN301Address1 = TRIM(source.PayerNameN301Address1),
 target.PayerNameN302Address2 = TRIM(source.PayerNameN302Address2),
 target.PayerNameN401City = TRIM(source.PayerNameN401City),
 target.PayerNameN402State = TRIM(source.PayerNameN402State),
 target.PayerNameN403ZipCode = TRIM(source.PayerNameN403ZipCode),
 target.BillingProvider01Code = TRIM(source.BillingProvider01Code),
 target.BillingProvider02Qualifier = TRIM(source.BillingProvider02Qualifier),
 target.BillingProvider03Name = TRIM(source.BillingProvider03Name),
 target.BillingProvider04 = TRIM(source.BillingProvider04),
 target.BillingProvider05 = TRIM(source.BillingProvider05),
 target.BillingProvider06 = TRIM(source.BillingProvider06),
 target.BillingProvider07 = TRIM(source.BillingProvider07),
 target.BillingProvider08Qualifier = TRIM(source.BillingProvider08Qualifier),
 target.BillingProvider09Code = TRIM(source.BillingProvider09Code),
 target.BillingProviderN301Address1 = TRIM(source.BillingProviderN301Address1),
 target.BillingProviderN302Address2 = TRIM(source.BillingProviderN302Address2),
 target.BillingProviderN401City = TRIM(source.BillingProviderN401City),
 target.BillingProviderN402State = TRIM(source.BillingProviderN402State),
 target.BillingProviderN403ZipCode = TRIM(source.BillingProviderN403ZipCode),
 target.BillingProviderREF01EmpID = TRIM(source.BillingProviderREF01EmpID),
 target.BillingProviderREF02RefID = TRIM(source.BillingProviderREF02RefID),
 target.BillingProviderPER01Code = TRIM(source.BillingProviderPER01Code),
 target.BillingProviderPER02Name = TRIM(source.BillingProviderPER02Name),
 target.BillingProviderPER03Qualifier = TRIM(source.BillingProviderPER03Qualifier),
 target.BillingProviderPER04Number = TRIM(source.BillingProviderPER04Number),
 target.PayToAddress01Code = TRIM(source.PayToAddress01Code),
 target.PayToAddress02Qualifier = TRIM(source.PayToAddress02Qualifier),
 target.PayToAddressN301Address1 = TRIM(source.PayToAddressN301Address1),
 target.PayToAddressN302Address2 = TRIM(source.PayToAddressN302Address2),
 target.PayToAddressN401City = TRIM(source.PayToAddressN401City),
 target.PayToAddressN402State = TRIM(source.PayToAddressN402State),
 target.PayToAddressN403ZipCode = TRIM(source.PayToAddressN403ZipCode),
 target.Facility01Code = TRIM(source.Facility01Code),
 target.Facility02Qualifier = TRIM(source.Facility02Qualifier),
 target.Facility03Name = TRIM(source.Facility03Name),
 target.Facility04 = TRIM(source.Facility04),
 target.Facility05 = TRIM(source.Facility05),
 target.Facility06 = TRIM(source.Facility06),
 target.Facility07 = TRIM(source.Facility07),
 target.Facility08Qualifier = TRIM(source.Facility08Qualifier),
 target.Facility09Code = TRIM(source.Facility09Code),
 target.FacilityN301Address1 = TRIM(source.FacilityN301Address1),
 target.FacilityN302Address2 = TRIM(source.FacilityN302Address2),
 target.FacilityN401City = TRIM(source.FacilityN401City),
 target.FacilityN402State = TRIM(source.FacilityN402State),
 target.FacilityN403ZipCode = TRIM(source.FacilityN403ZipCode),
 target.RenderingProvider01Code = TRIM(source.RenderingProvider01Code),
 target.RenderingProvider02Qualifier = TRIM(source.RenderingProvider02Qualifier),
 target.RenderingProvider03Name = TRIM(source.RenderingProvider03Name),
 target.RenderingProvider04 = TRIM(source.RenderingProvider04),
 target.RenderingProvider05 = TRIM(source.RenderingProvider05),
 target.RenderingProvider06 = TRIM(source.RenderingProvider06),
 target.RenderingProvider07 = TRIM(source.RenderingProvider07),
 target.RenderingProvider08Qualifier = TRIM(source.RenderingProvider08Qualifier),
 target.RenderingProvider09Code = TRIM(source.RenderingProvider09Code),
 target.RenderingProviderTaxonomyCode = TRIM(source.RenderingProviderTaxonomyCode),
 target.Claim01Number = TRIM(source.Claim01Number),
 target.Claim02Amt = TRIM(source.Claim02Amt),
 target.Claim03 = TRIM(source.Claim03),
 target.Claim04 = TRIM(source.Claim04),
 target.Claim05Location = TRIM(source.Claim05Location),
 target.Claim06Condition = TRIM(source.Claim06Condition),
 target.Claim07Assigned = TRIM(source.Claim07Assigned),
 target.Claim08Response = TRIM(source.Claim08Response),
 target.Claim09Release = TRIM(source.Claim09Release),
 target.ClaimAuthorizationNum = TRIM(source.ClaimAuthorizationNum),
 target.ClaimOriginalRefNum = TRIM(source.ClaimOriginalRefNum),
 target.ClaimReferralNum = TRIM(source.ClaimReferralNum),
 target.ClaimRHClaimNum = TRIM(source.ClaimRHClaimNum),
 target.ClaimNTE01 = TRIM(source.ClaimNTE01),
 target.ClaimNTE02 = TRIM(source.ClaimNTE02),
 target.ClaimNTE03 = TRIM(source.ClaimNTE03),
 target.ClaimDateDischarge = TRIM(source.ClaimDateDischarge),
 target.ClaimDateDisabilityTo = TRIM(source.ClaimDateDisabilityTo),
 target.ClaimDateDisabilityFrom = TRIM(source.ClaimDateDisabilityFrom),
 target.ClaimDateLastSeen = TRIM(source.ClaimDateLastSeen),
 target.ClaimDateOnSetCurrentIllness = TRIM(source.ClaimDateOnSetCurrentIllness),
 target.ClaimDateAdmissionFrom = TRIM(source.ClaimDateAdmissionFrom),
 target.ClaimDateAccident = TRIM(source.ClaimDateAccident),
 target.ClaimDateInitialTreatment = TRIM(source.ClaimDateInitialTreatment),
 target.ClaimOI01 = TRIM(source.ClaimOI01),
 target.ClaimOI02 = TRIM(source.ClaimOI02),
 target.ClaimOI03 = TRIM(source.ClaimOI03),
 target.ClaimOI04Signature = TRIM(source.ClaimOI04Signature),
 target.ClaimOI05 = TRIM(source.ClaimOI05),
 target.ClaimOI06Release = TRIM(source.ClaimOI06Release),
 target.ClaimDiag01 = TRIM(source.ClaimDiag01),
 target.ClaimDiag02 = TRIM(source.ClaimDiag02),
 target.ClaimDiag03 = TRIM(source.ClaimDiag03),
 target.ClaimDiag04 = TRIM(source.ClaimDiag04),
 target.ClaimDiag05 = TRIM(source.ClaimDiag05),
 target.ClaimDiag06 = TRIM(source.ClaimDiag06),
 target.ClaimDiag07 = TRIM(source.ClaimDiag07),
 target.ClaimDiag08 = TRIM(source.ClaimDiag08),
 target.ClaimDiag09 = TRIM(source.ClaimDiag09),
 target.ClaimDiag10 = TRIM(source.ClaimDiag10),
 target.ClaimDiag11 = TRIM(source.ClaimDiag11),
 target.ClaimDiag12 = TRIM(source.ClaimDiag12),
 target.ClaimDiag13 = TRIM(source.ClaimDiag13),
 target.ClaimDiag14 = TRIM(source.ClaimDiag14),
 target.ClaimDiag15 = TRIM(source.ClaimDiag15),
 target.ClaimDiag16 = TRIM(source.ClaimDiag16),
 target.ClaimDiag17 = TRIM(source.ClaimDiag17),
 target.ClaimLine00SeqNum = TRIM(source.ClaimLine00SeqNum),
 target.ClaimLine01Code = TRIM(source.ClaimLine01Code),
 target.ClaimLine01Mod1 = TRIM(source.ClaimLine01Mod1),
 target.ClaimLine01Mod2 = TRIM(source.ClaimLine01Mod2),
 target.ClaimLine01Mod3 = TRIM(source.ClaimLine01Mod3),
 target.ClaimLine01Mod4 = TRIM(source.ClaimLine01Mod4),
 target.ClaimLine02Amt = TRIM(source.ClaimLine02Amt),
 target.ClaimLine03 = TRIM(source.ClaimLine03),
 target.ClaimLine04Unit = TRIM(source.ClaimLine04Unit),
 target.ClaimLine05 = TRIM(source.ClaimLine05),
 target.ClaimLine06 = TRIM(source.ClaimLine06),
 target.ClaimLine07DiagnosisPointer1 = TRIM(source.ClaimLine07DiagnosisPointer1),
 target.ClaimLine07DiagnosisPointer2 = TRIM(source.ClaimLine07DiagnosisPointer2),
 target.ClaimLine07DiagnosisPointer3 = TRIM(source.ClaimLine07DiagnosisPointer3),
 target.ClaimLine07DiagnosisPointer4 = TRIM(source.ClaimLine07DiagnosisPointer4),
 target.ClaimLineServiceDate = TRIM(source.ClaimLineServiceDate),
 target.ClaimLineRevCode = TRIM(source.ClaimLineRevCode),
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime,
 target.BillingProviderPRVTaxonomyCode = TRIM(source.BillingProviderPRVTaxonomyCode),
 target.RenderingProviderPRVTaxonomyCode = TRIM(source.RenderingProviderPRVTaxonomyCode),
 target.K3ASegment = TRIM(source.K3ASegment),
 target.K3BSegment = TRIM(source.K3BSegment),
 target.K3CSegment = TRIM(source.K3CSegment),
 target.K3DSegment = TRIM(source.K3DSegment),
 target.K3ESegment = TRIM(source.K3ESegment),
 target.K3FSegment = TRIM(source.K3FSegment),
 target.K3GSegment = TRIM(source.K3GSegment),
 target.CLIA = TRIM(source.CLIA),
 target.TaxID = TRIM(source.TaxID),
 target.RefEAMedRecNum = TRIM(source.RefEAMedRecNum),
 target.ClaimLineNTENoteAdd = TRIM(source.ClaimLineNTENoteAdd),
 target.ClaimLineRef6RProviderControlNumber = TRIM(source.ClaimLineRef6RProviderControlNumber),
 target.RefD9Number = TRIM(source.RefD9Number),
 target.RemitType = TRIM(source.RemitType),
 target.NM1DN1Name02 = TRIM(source.NM1DN1Name02),
 target.NM1DN1Name03 = TRIM(source.NM1DN1Name03),
 target.NM1DN1Name04 = TRIM(source.NM1DN1Name04),
 target.NM1DN1Name05 = TRIM(source.NM1DN1Name05),
 target.NM1DN1Name06 = TRIM(source.NM1DN1Name06),
 target.NM1DN1Name07 = TRIM(source.NM1DN1Name07),
 target.NM1DN1Name08 = TRIM(source.NM1DN1Name08)
WHEN NOT MATCHED THEN
  INSERT (ID, FileName, ISA01Qualifier, ISA02Info, ISA03SecurityInfo, ISA04SecurityInfo, ISA05QualifierID, ISA06SenderID, ISA07QualifierID, ISA08ReceiverID, ISA09Date, ISA10Time, ISA11StandardsID, ISA12VersionNum, ISA13ContolNum, ISA14AckRequested, ISA15UsageID, GS01ID, GS02SendersCode, GS03ReceiversCode, GS04Date, GS05Time, GS06ControlNum, GS07ResponsibleAgencyCode, GS08IndustryID, ST01ID, ST02ControlNum, ST03ImplemntaionRef, BHT01Source, BHT02PurposeCode, BHT03RefID, BHT04Date, BHT05Time, BHT06Type, SubmitterName01ID, SubmitterName02Type, SubmitterName03Name, SubmitterName04, SubmitterName05, SubmitterName06, SubmitterName07, SubmitterName08CodeQualifier, SubmitterName09Code, SubmitterNamePER01Contact, SubmitterNamePER02Name, SubmitterNamePER03Qualifier, SubmitterNamePER04Num, SubmitterNamePER05Qualifier, SubmitterNamePER06Num, SubmitterNamePER07Mail, SubmitterNamePER08Email, ReceiverName01Code, ReceiverName02Qualifier, ReceiverName03Name, ReceiverName04, ReceiverName05, ReceiverName06, ReceiverName07, ReceiverName08Qualifier, ReceiverName09Code, SBRInfo01Seq, SBRInfo02Rel, SBRInfo03ID, SBRInfo04, SBRInfo05, SBRInfo06, SBRInfo07, SBRInfo08, SBRInfo09, SubscriberName01Code, SubscriberName02Type, SubscriberName03LastName, SubscriberName04FirstName, SubscriberName05MiddleName, SubscriberName06, SubscriberName07, SubscriberName08Qualifier, SubscriberName09MemberID, SubscriberNameN301Address1, SubscriberNameN302Address2, SubscriberNameN401City, SubscriberNameN402State, SubscriberNameN403ZipCode, SubscriberNameDMG01Format, SubscriberNameDMG02DOB, SubscriberNameDMG03Gender, PayerName01Code, PayerName02Type, PayerName03Iplan, PayerName04, PayerName05, PayerName06, PayerName07, PayerName08Qualifier, PayerName09MemberID, PayerNameN301Address1, PayerNameN302Address2, PayerNameN401City, PayerNameN402State, PayerNameN403ZipCode, BillingProvider01Code, BillingProvider02Qualifier, BillingProvider03Name, BillingProvider04, BillingProvider05, BillingProvider06, BillingProvider07, BillingProvider08Qualifier, BillingProvider09Code, BillingProviderN301Address1, BillingProviderN302Address2, BillingProviderN401City, BillingProviderN402State, BillingProviderN403ZipCode, BillingProviderREF01EmpID, BillingProviderREF02RefID, BillingProviderPER01Code, BillingProviderPER02Name, BillingProviderPER03Qualifier, BillingProviderPER04Number, PayToAddress01Code, PayToAddress02Qualifier, PayToAddressN301Address1, PayToAddressN302Address2, PayToAddressN401City, PayToAddressN402State, PayToAddressN403ZipCode, Facility01Code, Facility02Qualifier, Facility03Name, Facility04, Facility05, Facility06, Facility07, Facility08Qualifier, Facility09Code, FacilityN301Address1, FacilityN302Address2, FacilityN401City, FacilityN402State, FacilityN403ZipCode, RenderingProvider01Code, RenderingProvider02Qualifier, RenderingProvider03Name, RenderingProvider04, RenderingProvider05, RenderingProvider06, RenderingProvider07, RenderingProvider08Qualifier, RenderingProvider09Code, RenderingProviderTaxonomyCode, Claim01Number, Claim02Amt, Claim03, Claim04, Claim05Location, Claim06Condition, Claim07Assigned, Claim08Response, Claim09Release, ClaimAuthorizationNum, ClaimOriginalRefNum, ClaimReferralNum, ClaimRHClaimNum, ClaimNTE01, ClaimNTE02, ClaimNTE03, ClaimDateDischarge, ClaimDateDisabilityTo, ClaimDateDisabilityFrom, ClaimDateLastSeen, ClaimDateOnSetCurrentIllness, ClaimDateAdmissionFrom, ClaimDateAccident, ClaimDateInitialTreatment, ClaimOI01, ClaimOI02, ClaimOI03, ClaimOI04Signature, ClaimOI05, ClaimOI06Release, ClaimDiag01, ClaimDiag02, ClaimDiag03, ClaimDiag04, ClaimDiag05, ClaimDiag06, ClaimDiag07, ClaimDiag08, ClaimDiag09, ClaimDiag10, ClaimDiag11, ClaimDiag12, ClaimDiag13, ClaimDiag14, ClaimDiag15, ClaimDiag16, ClaimDiag17, ClaimLine00SeqNum, ClaimLine01Code, ClaimLine01Mod1, ClaimLine01Mod2, ClaimLine01Mod3, ClaimLine01Mod4, ClaimLine02Amt, ClaimLine03, ClaimLine04Unit, ClaimLine05, ClaimLine06, ClaimLine07DiagnosisPointer1, ClaimLine07DiagnosisPointer2, ClaimLine07DiagnosisPointer3, ClaimLine07DiagnosisPointer4, ClaimLineServiceDate, ClaimLineRevCode, DWLastUpdateDateTime, BillingProviderPRVTaxonomyCode, RenderingProviderPRVTaxonomyCode, K3ASegment, K3BSegment, K3CSegment, K3DSegment, K3ESegment, K3FSegment, K3GSegment, CLIA, TaxID, RefEAMedRecNum, ClaimLineNTENoteAdd, ClaimLineRef6RProviderControlNumber, RefD9Number, RemitType, NM1DN1Name02, NM1DN1Name03, NM1DN1Name04, NM1DN1Name05, NM1DN1Name06, NM1DN1Name07, NM1DN1Name08)
  VALUES (source.ID, TRIM(source.FileName), TRIM(source.ISA01Qualifier), TRIM(source.ISA02Info), TRIM(source.ISA03SecurityInfo), TRIM(source.ISA04SecurityInfo), TRIM(source.ISA05QualifierID), TRIM(source.ISA06SenderID), TRIM(source.ISA07QualifierID), TRIM(source.ISA08ReceiverID), TRIM(source.ISA09Date), TRIM(source.ISA10Time), TRIM(source.ISA11StandardsID), TRIM(source.ISA12VersionNum), TRIM(source.ISA13ContolNum), TRIM(source.ISA14AckRequested), TRIM(source.ISA15UsageID), TRIM(source.GS01ID), TRIM(source.GS02SendersCode), TRIM(source.GS03ReceiversCode), TRIM(source.GS04Date), TRIM(source.GS05Time), TRIM(source.GS06ControlNum), TRIM(source.GS07ResponsibleAgencyCode), TRIM(source.GS08IndustryID), TRIM(source.ST01ID), TRIM(source.ST02ControlNum), TRIM(source.ST03ImplemntaionRef), TRIM(source.BHT01Source), TRIM(source.BHT02PurposeCode), TRIM(source.BHT03RefID), TRIM(source.BHT04Date), TRIM(source.BHT05Time), TRIM(source.BHT06Type), TRIM(source.SubmitterName01ID), TRIM(source.SubmitterName02Type), TRIM(source.SubmitterName03Name), TRIM(source.SubmitterName04), TRIM(source.SubmitterName05), TRIM(source.SubmitterName06), TRIM(source.SubmitterName07), TRIM(source.SubmitterName08CodeQualifier), TRIM(source.SubmitterName09Code), TRIM(source.SubmitterNamePER01Contact), TRIM(source.SubmitterNamePER02Name), TRIM(source.SubmitterNamePER03Qualifier), TRIM(source.SubmitterNamePER04Num), TRIM(source.SubmitterNamePER05Qualifier), TRIM(source.SubmitterNamePER06Num), TRIM(source.SubmitterNamePER07Mail), TRIM(source.SubmitterNamePER08Email), TRIM(source.ReceiverName01Code), TRIM(source.ReceiverName02Qualifier), TRIM(source.ReceiverName03Name), TRIM(source.ReceiverName04), TRIM(source.ReceiverName05), TRIM(source.ReceiverName06), TRIM(source.ReceiverName07), TRIM(source.ReceiverName08Qualifier), TRIM(source.ReceiverName09Code), TRIM(source.SBRInfo01Seq), TRIM(source.SBRInfo02Rel), TRIM(source.SBRInfo03ID), TRIM(source.SBRInfo04), TRIM(source.SBRInfo05), TRIM(source.SBRInfo06), TRIM(source.SBRInfo07), TRIM(source.SBRInfo08), TRIM(source.SBRInfo09), TRIM(source.SubscriberName01Code), TRIM(source.SubscriberName02Type), TRIM(source.SubscriberName03LastName), TRIM(source.SubscriberName04FirstName), TRIM(source.SubscriberName05MiddleName), TRIM(source.SubscriberName06), TRIM(source.SubscriberName07), TRIM(source.SubscriberName08Qualifier), TRIM(source.SubscriberName09MemberID), TRIM(source.SubscriberNameN301Address1), TRIM(source.SubscriberNameN302Address2), TRIM(source.SubscriberNameN401City), TRIM(source.SubscriberNameN402State), TRIM(source.SubscriberNameN403ZipCode), TRIM(source.SubscriberNameDMG01Format), TRIM(source.SubscriberNameDMG02DOB), TRIM(source.SubscriberNameDMG03Gender), TRIM(source.PayerName01Code), TRIM(source.PayerName02Type), TRIM(source.PayerName03Iplan), TRIM(source.PayerName04), TRIM(source.PayerName05), TRIM(source.PayerName06), TRIM(source.PayerName07), TRIM(source.PayerName08Qualifier), TRIM(source.PayerName09MemberID), TRIM(source.PayerNameN301Address1), TRIM(source.PayerNameN302Address2), TRIM(source.PayerNameN401City), TRIM(source.PayerNameN402State), TRIM(source.PayerNameN403ZipCode), TRIM(source.BillingProvider01Code), TRIM(source.BillingProvider02Qualifier), TRIM(source.BillingProvider03Name), TRIM(source.BillingProvider04), TRIM(source.BillingProvider05), TRIM(source.BillingProvider06), TRIM(source.BillingProvider07), TRIM(source.BillingProvider08Qualifier), TRIM(source.BillingProvider09Code), TRIM(source.BillingProviderN301Address1), TRIM(source.BillingProviderN302Address2), TRIM(source.BillingProviderN401City), TRIM(source.BillingProviderN402State), TRIM(source.BillingProviderN403ZipCode), TRIM(source.BillingProviderREF01EmpID), TRIM(source.BillingProviderREF02RefID), TRIM(source.BillingProviderPER01Code), TRIM(source.BillingProviderPER02Name), TRIM(source.BillingProviderPER03Qualifier), TRIM(source.BillingProviderPER04Number), TRIM(source.PayToAddress01Code), TRIM(source.PayToAddress02Qualifier), TRIM(source.PayToAddressN301Address1), TRIM(source.PayToAddressN302Address2), TRIM(source.PayToAddressN401City), TRIM(source.PayToAddressN402State), TRIM(source.PayToAddressN403ZipCode), TRIM(source.Facility01Code), TRIM(source.Facility02Qualifier), TRIM(source.Facility03Name), TRIM(source.Facility04), TRIM(source.Facility05), TRIM(source.Facility06), TRIM(source.Facility07), TRIM(source.Facility08Qualifier), TRIM(source.Facility09Code), TRIM(source.FacilityN301Address1), TRIM(source.FacilityN302Address2), TRIM(source.FacilityN401City), TRIM(source.FacilityN402State), TRIM(source.FacilityN403ZipCode), TRIM(source.RenderingProvider01Code), TRIM(source.RenderingProvider02Qualifier), TRIM(source.RenderingProvider03Name), TRIM(source.RenderingProvider04), TRIM(source.RenderingProvider05), TRIM(source.RenderingProvider06), TRIM(source.RenderingProvider07), TRIM(source.RenderingProvider08Qualifier), TRIM(source.RenderingProvider09Code), TRIM(source.RenderingProviderTaxonomyCode), TRIM(source.Claim01Number), TRIM(source.Claim02Amt), TRIM(source.Claim03), TRIM(source.Claim04), TRIM(source.Claim05Location), TRIM(source.Claim06Condition), TRIM(source.Claim07Assigned), TRIM(source.Claim08Response), TRIM(source.Claim09Release), TRIM(source.ClaimAuthorizationNum), TRIM(source.ClaimOriginalRefNum), TRIM(source.ClaimReferralNum), TRIM(source.ClaimRHClaimNum), TRIM(source.ClaimNTE01), TRIM(source.ClaimNTE02), TRIM(source.ClaimNTE03), TRIM(source.ClaimDateDischarge), TRIM(source.ClaimDateDisabilityTo), TRIM(source.ClaimDateDisabilityFrom), TRIM(source.ClaimDateLastSeen), TRIM(source.ClaimDateOnSetCurrentIllness), TRIM(source.ClaimDateAdmissionFrom), TRIM(source.ClaimDateAccident), TRIM(source.ClaimDateInitialTreatment), TRIM(source.ClaimOI01), TRIM(source.ClaimOI02), TRIM(source.ClaimOI03), TRIM(source.ClaimOI04Signature), TRIM(source.ClaimOI05), TRIM(source.ClaimOI06Release), TRIM(source.ClaimDiag01), TRIM(source.ClaimDiag02), TRIM(source.ClaimDiag03), TRIM(source.ClaimDiag04), TRIM(source.ClaimDiag05), TRIM(source.ClaimDiag06), TRIM(source.ClaimDiag07), TRIM(source.ClaimDiag08), TRIM(source.ClaimDiag09), TRIM(source.ClaimDiag10), TRIM(source.ClaimDiag11), TRIM(source.ClaimDiag12), TRIM(source.ClaimDiag13), TRIM(source.ClaimDiag14), TRIM(source.ClaimDiag15), TRIM(source.ClaimDiag16), TRIM(source.ClaimDiag17), TRIM(source.ClaimLine00SeqNum), TRIM(source.ClaimLine01Code), TRIM(source.ClaimLine01Mod1), TRIM(source.ClaimLine01Mod2), TRIM(source.ClaimLine01Mod3), TRIM(source.ClaimLine01Mod4), TRIM(source.ClaimLine02Amt), TRIM(source.ClaimLine03), TRIM(source.ClaimLine04Unit), TRIM(source.ClaimLine05), TRIM(source.ClaimLine06), TRIM(source.ClaimLine07DiagnosisPointer1), TRIM(source.ClaimLine07DiagnosisPointer2), TRIM(source.ClaimLine07DiagnosisPointer3), TRIM(source.ClaimLine07DiagnosisPointer4), TRIM(source.ClaimLineServiceDate), TRIM(source.ClaimLineRevCode), source.DWLastUpdateDateTime, TRIM(source.BillingProviderPRVTaxonomyCode), TRIM(source.RenderingProviderPRVTaxonomyCode), TRIM(source.K3ASegment), TRIM(source.K3BSegment), TRIM(source.K3CSegment), TRIM(source.K3DSegment), TRIM(source.K3ESegment), TRIM(source.K3FSegment), TRIM(source.K3GSegment), TRIM(source.CLIA), TRIM(source.TaxID), TRIM(source.RefEAMedRecNum), TRIM(source.ClaimLineNTENoteAdd), TRIM(source.ClaimLineRef6RProviderControlNumber), TRIM(source.RefD9Number), TRIM(source.RemitType), TRIM(source.NM1DN1Name02), TRIM(source.NM1DN1Name03), TRIM(source.NM1DN1Name04), TRIM(source.NM1DN1Name05), TRIM(source.NM1DN1Name06), TRIM(source.NM1DN1Name07), TRIM(source.NM1DN1Name08));

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT ID
      FROM {{ params.param_psc_core_dataset_name }}.ECW_FactClaim837P
      GROUP BY ID
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.ECW_FactClaim837P');
ELSE
  COMMIT TRANSACTION;
END IF;
