
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.EPIC_JuncClaimFirstLastKeyMeasure AS target
USING {{ params.param_psc_stage_dataset_name }}.EPIC_JuncClaimFirstLastKeyMeasure AS source
ON target.ClaimKey = source.ClaimKey
WHEN MATCHED THEN
  UPDATE SET
  target.ClaimKey = source.ClaimKey,
 target.ClaimNumber = source.ClaimNumber,
 target.Coid = TRIM(source.Coid),
 target.VisitNumber = source.VisitNumber,
 target.FirstBillKey = source.FirstBillKey,
 target.FirstBillDateKey = source.FirstBillDateKey,
 target.LastBillKey = source.LastBillKey,
 target.LastBillDateKey = source.LastBillDateKey,
 target.NumberOfBills = source.NumberOfBills,
 target.FirstPatientStatementBillKey = source.FirstPatientStatementBillKey,
 target.FirstPatientStatementBillDateKey = source.FirstPatientStatementBillDateKey,
 target.LastPatientStatementBillKey = source.LastPatientStatementBillKey,
 target.LastPatientStatementBillDateKey = source.LastPatientStatementBillDateKey,
 target.NumberOfPatientStatements = source.NumberOfPatientStatements,
 target.FirstInsuranceBillKey = source.FirstInsuranceBillKey,
 target.FirstInsuranceBillDateKey = source.FirstInsuranceBillDateKey,
 target.LastInsuranceBillKey = source.LastInsuranceBillKey,
 target.LastInsuranceBillDateKey = source.LastInsuranceBillDateKey,
 target.NumberOfInsuranceBills = source.NumberOfInsuranceBills,
 target.FirstInsuranceClaimPaymentKey = source.FirstInsuranceClaimPaymentKey,
 target.FirstInsuranceClaimPaymentDateKey = source.FirstInsuranceClaimPaymentDateKey,
 target.LastInsuranceClaimPaymentKey = source.LastInsuranceClaimPaymentKey,
 target.LastInsuranceClaimPaymentDateKey = source.LastInsuranceClaimPaymentDateKey,
 target.TotalInsuranceClaimPaymentAmt = source.TotalInsuranceClaimPaymentAmt,
 target.FirstPatientClaimPaymentKey = source.FirstPatientClaimPaymentKey,
 target.FirstPatientClaimPaymentDateKey = source.FirstPatientClaimPaymentDateKey,
 target.LastPatientClaimPaymentKey = source.LastPatientClaimPaymentKey,
 target.LastPatientClaimPaymentDateKey = source.LastPatientClaimPaymentDateKey,
 target.TotalPatientClaimPaymentAmt = source.TotalPatientClaimPaymentAmt,
 target.LastClaimNoteHistoryKey = source.LastClaimNoteHistoryKey,
 target.LastClaimNote = TRIM(source.LastClaimNote),
 target.LastClaimNoteCreatedByUserKey = source.LastClaimNoteCreatedByUserKey,
 target.LastClaimNoteCreatedDateKey = source.LastClaimNoteCreatedDateKey,
 target.LastClaimNoteCreatedTime = source.LastClaimNoteCreatedTime,
 target.LastClaimStatusUpdatedDateKey = source.LastClaimStatusUpdatedDateKey,
 target.LastClaimStatusUpdatedKey = source.LastClaimStatusUpdatedKey,
 target.LastClaimStatusHistoryChangedByUserKey = source.LastClaimStatusHistoryChangedByUserKey,
 target.LiabilityOwnerType = source.LiabilityOwnerType,
 target.LastPaymentContractualAdjustmentsDateKey = source.LastPaymentContractualAdjustmentsDateKey,
 target.LastAdjustmentsDateKey = source.LastAdjustmentsDateKey,
 target.TotalAdjustmentsRefundsAmt = source.TotalAdjustmentsRefundsAmt,
 target.TotalAdjustmentsDenialsAmt = source.TotalAdjustmentsDenialsAmt,
 target.TotalAdjustmentsBadDebtAmt = source.TotalAdjustmentsBadDebtAmt,
 target.TotalAdjustmentsCharityAmt = source.TotalAdjustmentsCharityAmt,
 target.TotalAdjustmentsUninsuredAmt = source.TotalAdjustmentsUninsuredAmt,
 target.TotalAdjustmentsAdministrationAmt = source.TotalAdjustmentsAdministrationAmt,
 target.TotalAdjustmentsNSFAmt = source.TotalAdjustmentsNSFAmt,
 target.TotalAdjustmentsEscheatAmt = source.TotalAdjustmentsEscheatAmt,
 target.TotalAdjustmentsInterestAmt = source.TotalAdjustmentsInterestAmt,
 target.TotalAdjustmentsContractualAmt = source.TotalAdjustmentsContractualAmt,
 target.TotalPaymentContracualAdjustmentsAmt = source.TotalPaymentContracualAdjustmentsAmt,
 target.TotalFinancialAdjustmentsAmt = source.TotalFinancialAdjustmentsAmt,
 target.ClaimDateKey = source.ClaimDateKey,
 target.ServiceDateKey = source.ServiceDateKey,
 target.LiabilityDateKey = source.LiabilityDateKey,
 target.LiabilityLastBilledClaimDateKey = source.LiabilityLastBilledClaimDateKey,
 target.LastBillTypeKey = source.LastBillTypeKey,
 target.UnBilledStatusKey = source.UnBilledStatusKey,
 target.ARClaimFlag = source.ARClaimFlag,
 target.RHPrimaryMaxSubmissionDateKey = source.RHPrimaryMaxSubmissionDateKey,
 target.RHPrimaryMinSubmissionDateKey = source.RHPrimaryMinSubmissionDateKey,
 target.RHPrimaryMaxReleaseDateKey = source.RHPrimaryMaxReleaseDateKey,
 target.RHPrimaryMinReleaseDateKey = source.RHPrimaryMinReleaseDateKey,
 target.RHPrimarySubmissionCount = source.RHPrimarySubmissionCount,
 target.RHPrimaryReleaseCount = source.RHPrimaryReleaseCount,
 target.RHSecondaryMaxSubmissionDateKey = source.RHSecondaryMaxSubmissionDateKey,
 target.RHSecondaryMinSubmissionDateKey = source.RHSecondaryMinSubmissionDateKey,
 target.RHSecondaryMaxReleaseDateKey = source.RHSecondaryMaxReleaseDateKey,
 target.RHSecondaryMinReleaseDateKey = source.RHSecondaryMinReleaseDateKey,
 target.RHSecondarySubmissionCount = source.RHSecondarySubmissionCount,
 target.RHSecondaryReleaseCount = source.RHSecondaryReleaseCount,
 target.RHMinReleaseDateKey = source.RHMinReleaseDateKey,
 target.RHMaxReleaseDateKey = source.RHMaxReleaseDateKey,
 target.RHMinSubmissionDateKey = source.RHMinSubmissionDateKey,
 target.RHMaxSubmissionDateKey = source.RHMaxSubmissionDateKey,
 target.RHSubmissionCount = source.RHSubmissionCount,
 target.RHReleaseCount = source.RHReleaseCount,
 target.LastRH1201BillClaimStatusKey = TRIM(source.LastRH1201BillClaimStatusKey),
 target.LastRH1201ReleaseStatusKey = TRIM(source.LastRH1201ReleaseStatusKey),
 target.LastRH1201HoldCode = TRIM(source.LastRH1201HoldCode),
 target.LastRH1201HoldCodePrefixKey = TRIM(source.LastRH1201HoldCodePrefixKey),
 target.PrimaryIplanKey = source.PrimaryIplanKey,
 target.LiabilityIplanKey = source.LiabilityIplanKey,
 target.SecondaryIplanKey = source.SecondaryIplanKey,
 target.TertiaryIplanKey = source.TertiaryIplanKey,
 target.CPT1CPTCodeKey = source.CPT1CPTCodeKey,
 target.CPT2CPTCodeKey = source.CPT2CPTCodeKey,
 target.CPT3CPTCodeKey = source.CPT3CPTCodeKey,
 target.CPT4CPTCodeKey = source.CPT4CPTCodeKey,
 target.CPT5CPTCodeKey = source.CPT5CPTCodeKey,
 target.Diag1DiagnosisCodeKey = source.Diag1DiagnosisCodeKey,
 target.Diag2DiagnosisCodeKey = source.Diag2DiagnosisCodeKey,
 target.Diag3DiagnosisCodeKey = source.Diag3DiagnosisCodeKey,
 target.Diag4DiagnosisCodeKey = source.Diag4DiagnosisCodeKey,
 target.Diag5DiagnosisCodeKey = source.Diag5DiagnosisCodeKey,
 target.ArtivaLiabilityPool = TRIM(source.ArtivaLiabilityPool),
 target.ArtivaLiabilityLastWorkedDate = source.ArtivaLiabilityLastWorkedDate,
 target.ArtivaLiabilityLastReviewedDate = source.ArtivaLiabilityLastReviewedDate,
 target.RH277LastResponseStatusCtgyCode = TRIM(source.RH277LastResponseStatusCtgyCode),
 target.RH277LastResponseStatusCode = TRIM(source.RH277LastResponseStatusCode),
 target.RH277LastResponseImportDateKey = source.RH277LastResponseImportDateKey,
 target.RH277LastResponseRespondingPayer = TRIM(source.RH277LastResponseRespondingPayer),
 target.RH1301LastClaimDateWithEdiError = source.RH1301LastClaimDateWithEdiError,
 target.VoidAndRecreateDate = source.VoidAndRecreateDate,
 target.VoidedOriginalClaimStatusKey = source.VoidedOriginalClaimStatusKey,
 target.LastClaimNumber = source.LastClaimNumber,
 target.TotalClaimNumbersCnt = source.TotalClaimNumbersCnt,
 target.ArtivaLiabilityFollowupDate = source.ArtivaLiabilityFollowupDate,
 target.TotalBalanceAmt = source.TotalBalanceAmt,
 target.TotalChargesAmt = source.TotalChargesAmt,
 target.TotalPatientBalanceAmt = source.TotalPatientBalanceAmt,
 target.TotalInsuranceBalanceAmt = source.TotalInsuranceBalanceAmt,
 target.TotalPaymentsAmt = source.TotalPaymentsAmt,
 target.TotalInsurancePaymentsAmt = source.TotalInsurancePaymentsAmt,
 target.TotalPatientPaymentsAmt = source.TotalPatientPaymentsAmt,
 target.TotalPaymentsAndAdjustmentsAmt = source.TotalPaymentsAndAdjustmentsAmt,
 target.TotalAdjustmentsAmt = source.TotalAdjustmentsAmt,
 target.TotalAllowedAmt = source.TotalAllowedAmt,
 target.LastAdjustmentsTransactionDateKey = source.LastAdjustmentsTransactionDateKey,
 target.LastClaimKey = source.LastClaimKey,
 target.LastVoidDateKey = source.LastVoidDateKey,
 target.LastBillMessage = TRIM(source.LastBillMessage),
 target.PrimaryClaimPayerKey = source.PrimaryClaimPayerKey,
 target.PrimaryPayerGroupNumber = TRIM(source.PrimaryPayerGroupNumber),
 target.PrimaryPayerGroupName = TRIM(source.PrimaryPayerGroupName),
 target.SecondaryClaimPayerKey = source.SecondaryClaimPayerKey,
 target.SecondaryPayerGroupNumber = TRIM(source.SecondaryPayerGroupNumber),
 target.SecondaryPayerGroupName = TRIM(source.SecondaryPayerGroupName),
 target.TertiaryClaimPayerKey = source.TertiaryClaimPayerKey,
 target.TertiaryPayerGroupNumber = TRIM(source.TertiaryPayerGroupNumber),
 target.TertiaryPayerGroupName = TRIM(source.TertiaryPayerGroupName),
 target.FirstInsuranceWithVoidsBillDateKey = source.FirstInsuranceWithVoidsBillDateKey,
 target.DeleteFlag = source.DeleteFlag,
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime,
 target.SourceSystemCode = TRIM(source.SourceSystemCode),
 target.InsertedBy = TRIM(source.InsertedBy),
 target.InsertedDTM = source.InsertedDTM,
 target.ModifiedBy = TRIM(source.ModifiedBy),
 target.ModifiedDTM = source.ModifiedDTM,
 target.VirtualVisit = source.VirtualVisit,
 target.FirstPatientLiabilityDateKey = source.FirstPatientLiabilityDateKey,
 target.FirstZeroBalanceDateKey = source.FirstZeroBalanceDateKey,
 target.FirstChargeDebitDateKey = source.FirstChargeDebitDateKey
WHEN NOT MATCHED THEN
  INSERT (ClaimKey, ClaimNumber, Coid, VisitNumber, FirstBillKey, FirstBillDateKey, LastBillKey, LastBillDateKey, NumberOfBills, FirstPatientStatementBillKey, FirstPatientStatementBillDateKey, LastPatientStatementBillKey, LastPatientStatementBillDateKey, NumberOfPatientStatements, FirstInsuranceBillKey, FirstInsuranceBillDateKey, LastInsuranceBillKey, LastInsuranceBillDateKey, NumberOfInsuranceBills, FirstInsuranceClaimPaymentKey, FirstInsuranceClaimPaymentDateKey, LastInsuranceClaimPaymentKey, LastInsuranceClaimPaymentDateKey, TotalInsuranceClaimPaymentAmt, FirstPatientClaimPaymentKey, FirstPatientClaimPaymentDateKey, LastPatientClaimPaymentKey, LastPatientClaimPaymentDateKey, TotalPatientClaimPaymentAmt, LastClaimNoteHistoryKey, LastClaimNote, LastClaimNoteCreatedByUserKey, LastClaimNoteCreatedDateKey, LastClaimNoteCreatedTime, LastClaimStatusUpdatedDateKey, LastClaimStatusUpdatedKey, LastClaimStatusHistoryChangedByUserKey, LiabilityOwnerType, LastPaymentContractualAdjustmentsDateKey, LastAdjustmentsDateKey, TotalAdjustmentsRefundsAmt, TotalAdjustmentsDenialsAmt, TotalAdjustmentsBadDebtAmt, TotalAdjustmentsCharityAmt, TotalAdjustmentsUninsuredAmt, TotalAdjustmentsAdministrationAmt, TotalAdjustmentsNSFAmt, TotalAdjustmentsEscheatAmt, TotalAdjustmentsInterestAmt, TotalAdjustmentsContractualAmt, TotalPaymentContracualAdjustmentsAmt, TotalFinancialAdjustmentsAmt, ClaimDateKey, ServiceDateKey, LiabilityDateKey, LiabilityLastBilledClaimDateKey, LastBillTypeKey, UnBilledStatusKey, ARClaimFlag, RHPrimaryMaxSubmissionDateKey, RHPrimaryMinSubmissionDateKey, RHPrimaryMaxReleaseDateKey, RHPrimaryMinReleaseDateKey, RHPrimarySubmissionCount, RHPrimaryReleaseCount, RHSecondaryMaxSubmissionDateKey, RHSecondaryMinSubmissionDateKey, RHSecondaryMaxReleaseDateKey, RHSecondaryMinReleaseDateKey, RHSecondarySubmissionCount, RHSecondaryReleaseCount, RHMinReleaseDateKey, RHMaxReleaseDateKey, RHMinSubmissionDateKey, RHMaxSubmissionDateKey, RHSubmissionCount, RHReleaseCount, LastRH1201BillClaimStatusKey, LastRH1201ReleaseStatusKey, LastRH1201HoldCode, LastRH1201HoldCodePrefixKey, PrimaryIplanKey, LiabilityIplanKey, SecondaryIplanKey, TertiaryIplanKey, CPT1CPTCodeKey, CPT2CPTCodeKey, CPT3CPTCodeKey, CPT4CPTCodeKey, CPT5CPTCodeKey, Diag1DiagnosisCodeKey, Diag2DiagnosisCodeKey, Diag3DiagnosisCodeKey, Diag4DiagnosisCodeKey, Diag5DiagnosisCodeKey, ArtivaLiabilityPool, ArtivaLiabilityLastWorkedDate, ArtivaLiabilityLastReviewedDate, RH277LastResponseStatusCtgyCode, RH277LastResponseStatusCode, RH277LastResponseImportDateKey, RH277LastResponseRespondingPayer, RH1301LastClaimDateWithEdiError, VoidAndRecreateDate, VoidedOriginalClaimStatusKey, LastClaimNumber, TotalClaimNumbersCnt, ArtivaLiabilityFollowupDate, TotalBalanceAmt, TotalChargesAmt, TotalPatientBalanceAmt, TotalInsuranceBalanceAmt, TotalPaymentsAmt, TotalInsurancePaymentsAmt, TotalPatientPaymentsAmt, TotalPaymentsAndAdjustmentsAmt, TotalAdjustmentsAmt, TotalAllowedAmt, LastAdjustmentsTransactionDateKey, LastClaimKey, LastVoidDateKey, LastBillMessage, PrimaryClaimPayerKey, PrimaryPayerGroupNumber, PrimaryPayerGroupName, SecondaryClaimPayerKey, SecondaryPayerGroupNumber, SecondaryPayerGroupName, TertiaryClaimPayerKey, TertiaryPayerGroupNumber, TertiaryPayerGroupName, FirstInsuranceWithVoidsBillDateKey, DeleteFlag, DWLastUpdateDateTime, SourceSystemCode, InsertedBy, InsertedDTM, ModifiedBy, ModifiedDTM, VirtualVisit, FirstPatientLiabilityDateKey, FirstZeroBalanceDateKey, FirstChargeDebitDateKey)
  VALUES (source.ClaimKey, source.ClaimNumber, TRIM(source.Coid), source.VisitNumber, source.FirstBillKey, source.FirstBillDateKey, source.LastBillKey, source.LastBillDateKey, source.NumberOfBills, source.FirstPatientStatementBillKey, source.FirstPatientStatementBillDateKey, source.LastPatientStatementBillKey, source.LastPatientStatementBillDateKey, source.NumberOfPatientStatements, source.FirstInsuranceBillKey, source.FirstInsuranceBillDateKey, source.LastInsuranceBillKey, source.LastInsuranceBillDateKey, source.NumberOfInsuranceBills, source.FirstInsuranceClaimPaymentKey, source.FirstInsuranceClaimPaymentDateKey, source.LastInsuranceClaimPaymentKey, source.LastInsuranceClaimPaymentDateKey, source.TotalInsuranceClaimPaymentAmt, source.FirstPatientClaimPaymentKey, source.FirstPatientClaimPaymentDateKey, source.LastPatientClaimPaymentKey, source.LastPatientClaimPaymentDateKey, source.TotalPatientClaimPaymentAmt, source.LastClaimNoteHistoryKey, TRIM(source.LastClaimNote), source.LastClaimNoteCreatedByUserKey, source.LastClaimNoteCreatedDateKey, source.LastClaimNoteCreatedTime, source.LastClaimStatusUpdatedDateKey, source.LastClaimStatusUpdatedKey, source.LastClaimStatusHistoryChangedByUserKey, source.LiabilityOwnerType, source.LastPaymentContractualAdjustmentsDateKey, source.LastAdjustmentsDateKey, source.TotalAdjustmentsRefundsAmt, source.TotalAdjustmentsDenialsAmt, source.TotalAdjustmentsBadDebtAmt, source.TotalAdjustmentsCharityAmt, source.TotalAdjustmentsUninsuredAmt, source.TotalAdjustmentsAdministrationAmt, source.TotalAdjustmentsNSFAmt, source.TotalAdjustmentsEscheatAmt, source.TotalAdjustmentsInterestAmt, source.TotalAdjustmentsContractualAmt, source.TotalPaymentContracualAdjustmentsAmt, source.TotalFinancialAdjustmentsAmt, source.ClaimDateKey, source.ServiceDateKey, source.LiabilityDateKey, source.LiabilityLastBilledClaimDateKey, source.LastBillTypeKey, source.UnBilledStatusKey, source.ARClaimFlag, source.RHPrimaryMaxSubmissionDateKey, source.RHPrimaryMinSubmissionDateKey, source.RHPrimaryMaxReleaseDateKey, source.RHPrimaryMinReleaseDateKey, source.RHPrimarySubmissionCount, source.RHPrimaryReleaseCount, source.RHSecondaryMaxSubmissionDateKey, source.RHSecondaryMinSubmissionDateKey, source.RHSecondaryMaxReleaseDateKey, source.RHSecondaryMinReleaseDateKey, source.RHSecondarySubmissionCount, source.RHSecondaryReleaseCount, source.RHMinReleaseDateKey, source.RHMaxReleaseDateKey, source.RHMinSubmissionDateKey, source.RHMaxSubmissionDateKey, source.RHSubmissionCount, source.RHReleaseCount, TRIM(source.LastRH1201BillClaimStatusKey), TRIM(source.LastRH1201ReleaseStatusKey), TRIM(source.LastRH1201HoldCode), TRIM(source.LastRH1201HoldCodePrefixKey), source.PrimaryIplanKey, source.LiabilityIplanKey, source.SecondaryIplanKey, source.TertiaryIplanKey, source.CPT1CPTCodeKey, source.CPT2CPTCodeKey, source.CPT3CPTCodeKey, source.CPT4CPTCodeKey, source.CPT5CPTCodeKey, source.Diag1DiagnosisCodeKey, source.Diag2DiagnosisCodeKey, source.Diag3DiagnosisCodeKey, source.Diag4DiagnosisCodeKey, source.Diag5DiagnosisCodeKey, TRIM(source.ArtivaLiabilityPool), source.ArtivaLiabilityLastWorkedDate, source.ArtivaLiabilityLastReviewedDate, TRIM(source.RH277LastResponseStatusCtgyCode), TRIM(source.RH277LastResponseStatusCode), source.RH277LastResponseImportDateKey, TRIM(source.RH277LastResponseRespondingPayer), source.RH1301LastClaimDateWithEdiError, source.VoidAndRecreateDate, source.VoidedOriginalClaimStatusKey, source.LastClaimNumber, source.TotalClaimNumbersCnt, source.ArtivaLiabilityFollowupDate, source.TotalBalanceAmt, source.TotalChargesAmt, source.TotalPatientBalanceAmt, source.TotalInsuranceBalanceAmt, source.TotalPaymentsAmt, source.TotalInsurancePaymentsAmt, source.TotalPatientPaymentsAmt, source.TotalPaymentsAndAdjustmentsAmt, source.TotalAdjustmentsAmt, source.TotalAllowedAmt, source.LastAdjustmentsTransactionDateKey, source.LastClaimKey, source.LastVoidDateKey, TRIM(source.LastBillMessage), source.PrimaryClaimPayerKey, TRIM(source.PrimaryPayerGroupNumber), TRIM(source.PrimaryPayerGroupName), source.SecondaryClaimPayerKey, TRIM(source.SecondaryPayerGroupNumber), TRIM(source.SecondaryPayerGroupName), source.TertiaryClaimPayerKey, TRIM(source.TertiaryPayerGroupNumber), TRIM(source.TertiaryPayerGroupName), source.FirstInsuranceWithVoidsBillDateKey, source.DeleteFlag, source.DWLastUpdateDateTime, TRIM(source.SourceSystemCode), TRIM(source.InsertedBy), source.InsertedDTM, TRIM(source.ModifiedBy), source.ModifiedDTM, source.VirtualVisit, source.FirstPatientLiabilityDateKey, source.FirstZeroBalanceDateKey, source.FirstChargeDebitDateKey);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT ClaimKey
      FROM {{ params.param_psc_core_dataset_name }}.EPIC_JuncClaimFirstLastKeyMeasure
      GROUP BY ClaimKey
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.EPIC_JuncClaimFirstLastKeyMeasure');
ELSE
  COMMIT TRANSACTION;
END IF;
