Select 
  TumorId, 
  PatientId, 
  Grade, 
  CaseStatFlag, 
  PrimarySite, 
  Primsitesubcode, 
  MstDefChemoSumm, 
  MstDefDxStageSumm, 
  MstDefHormSumm, 
  MstDefImmunoSumm, 
  MstDefMarginsSumm, 
  MstDefPallSumm, 
  MstDefRTBoost, 
  MstDefRTHosp, 
  MstDefRTLoc, 
  ReasonNoChemo, 
  ReasonNoHormone, 
  ReasonNoImmuno, 
  ReasonNoRad, 
  MstDefSurgPrimSumm, 
  CS_SS_Factor_1_Num_Code, 
  CS_SS_Factor_2_Num_Code, 
  CS_SS_Factor_15_Num_Code, 
  CS_SS_Factor_16_Num_Code, 
  CS_SS_Factor_22_Num_Code, 
  CS_SS_Factor_23_Num_Code, 
  CS_SS_FACTOR_25_NUM_CODE, 
  ChemoSrgSeq, 
  MstDefRTMod, 
  MstDefRTVol, 
  MstDefScopeLNSumm, 
  SurgAppHosp, 
  MstDefSurgPrimHosp, 
  CS_TumSize, 
  CASE WHEN YEAR_MstDefChemoDt IS NOT NULL AND MONTH_MstDefChemoDt IS NOT NULL AND DAY_MstDefChemoDt IS NOT NULL AND ISDATE(CONCAT(YEAR_MstDefChemoDt, '-', MONTH_MstDefChemoDt, '-', DAY_MstDefChemoDt)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_MstDefChemoDt, '-', MONTH_MstDefChemoDt, '-', DAY_MstDefChemoDt)) <= GETDATE() THEN CAST(CONCAT(YEAR_MstDefChemoDt, '-', MONTH_MstDefChemoDt, '-', DAY_MstDefChemoDt) AS date) ELSE NULL END AS MstDefChemoDt, 
  CASE WHEN YEAR_MstDefRTDt IS NOT NULL AND MONTH_MstDefRTDt IS NOT NULL AND DAY_MstDefRTDt IS NOT NULL AND ISDATE(CONCAT(YEAR_MstDefRTDt, '-', MONTH_MstDefRTDt, '-', DAY_MstDefRTDt)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_MstDefRTDt, '-', MONTH_MstDefRTDt, '-', DAY_MstDefRTDt)) <= GETDATE() THEN CAST(CONCAT(YEAR_MstDefRTDt, '-', MONTH_MstDefRTDt, '-', DAY_MstDefRTDt) AS date) ELSE NULL END AS MstDefRTDt, 
  CASE WHEN YEAR_MstDefImmunoDt IS NOT NULL AND MONTH_MstDefImmunoDt IS NOT NULL AND DAY_MstDefImmunoDt IS NOT NULL AND ISDATE(CONCAT(YEAR_MstDefImmunoDt, '-', MONTH_MstDefImmunoDt, '-', DAY_MstDefImmunoDt)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_MstDefImmunoDt, '-', MONTH_MstDefImmunoDt, '-', DAY_MstDefImmunoDt)) <= GETDATE() THEN CAST(CONCAT(YEAR_MstDefImmunoDt, '-', MONTH_MstDefImmunoDt, '-', DAY_MstDefImmunoDt) AS date) ELSE NULL END AS MstDefImmunoDt, 
  CASE WHEN YEAR_MstDefHormDt IS NOT NULL AND MONTH_MstDefHormDt IS NOT NULL AND DAY_MstDefHormDt IS NOT NULL AND ISDATE(CONCAT(YEAR_MstDefHormDt, '-', MONTH_MstDefHormDt, '-', DAY_MstDefHormDt)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_MstDefHormDt, '-', MONTH_MstDefHormDt, '-', DAY_MstDefHormDt)) <= GETDATE() THEN CAST(CONCAT(YEAR_MstDefHormDt, '-', MONTH_MstDefHormDt, '-', DAY_MstDefHormDt) AS date) ELSE NULL END AS MstDefHormDt, 
  CASE WHEN YEAR_MstDefRTStopDt IS NOT NULL AND MONTH_MstDefRTStopDt IS NOT NULL AND DAY_MstDefRTStopDt IS NOT NULL AND ISDATE(CONCAT(YEAR_MstDefRTStopDt, '-', MONTH_MstDefRTStopDt, '-', DAY_MstDefRTStopDt)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_MstDefRTStopDt, '-', MONTH_MstDefRTStopDt, '-', DAY_MstDefRTStopDt)) <= GETDATE() THEN CAST(CONCAT(YEAR_MstDefRTStopDt, '-', MONTH_MstDefRTStopDt, '-', DAY_MstDefRTStopDt) AS date) ELSE NULL END AS MstDefRTStopDt, 
  CASE WHEN YEAR_DtFirstSurg IS NOT NULL AND MONTH_DtFirstSurg IS NOT NULL AND DAY_DtFirstSurg IS NOT NULL AND ISDATE(CONCAT(YEAR_DtFirstSurg, '-', MONTH_DtFirstSurg, '-', DAY_DtFirstSurg)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_DtFirstSurg, '-', MONTH_DtFirstSurg, '-', DAY_DtFirstSurg)) <= GETDATE() THEN CAST(CONCAT(YEAR_DtFirstSurg, '-', MONTH_DtFirstSurg, '-', DAY_DtFirstSurg) AS date) ELSE NULL END AS DtFirstSurg, 
  CASE WHEN YEAR_DtMstDefSurg IS NOT NULL AND MONTH_DtMstDefSurg IS NOT NULL AND DAY_DtMstDefSurg IS NOT NULL AND ISDATE(CONCAT(YEAR_DtMstDefSurg, '-', MONTH_DtMstDefSurg, '-', DAY_DtMstDefSurg)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_DtMstDefSurg, '-', MONTH_DtMstDefSurg, '-', DAY_DtMstDefSurg)) <= GETDATE() THEN CAST(CONCAT(YEAR_DtMstDefSurg, '-', MONTH_DtMstDefSurg, '-', DAY_DtMstDefSurg) AS date) ELSE NULL END AS DtMstDefSurg, 
  CASE WHEN YEAR_DateAdmis IS NOT NULL AND MONTH_DateAdmis IS NOT NULL AND DAY_DateAdmis IS NOT NULL AND ISDATE(CONCAT(YEAR_DateAdmis, '-', MONTH_DateAdmis, '-', DAY_DateAdmis)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_DateAdmis, '-', MONTH_DateAdmis, '-', DAY_DateAdmis)) <= GETDATE() THEN CAST(CONCAT(YEAR_DateAdmis, '-', MONTH_DateAdmis, '-', DAY_DateAdmis) AS date) ELSE NULL END AS DateAdmis, 
  CASE WHEN YEAR_DtCA_Conf IS NOT NULL AND MONTH_DtCA_Conf IS NOT NULL AND DAY_DtCA_Conf IS NOT NULL AND ISDATE(CONCAT(YEAR_DtCA_Conf, '-', MONTH_DtCA_Conf, '-', DAY_DtCA_Conf)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_DtCA_Conf, '-', MONTH_DtCA_Conf, '-', DAY_DtCA_Conf)) <= GETDATE() THEN CAST(CONCAT(YEAR_DtCA_Conf, '-', MONTH_DtCA_Conf, '-', DAY_DtCA_Conf) AS date) ELSE NULL END AS DtCA_Conf, 
  CASE WHEN YEAR_Dt2CA_Conf IS NOT NULL AND MONTH_Dt2CA_Conf IS NOT NULL AND DAY_Dt2CA_Conf IS NOT NULL AND ISDATE(CONCAT(YEAR_Dt2CA_Conf, '-', MONTH_Dt2CA_Conf, '-', DAY_Dt2CA_Conf)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_Dt2CA_Conf, '-', MONTH_Dt2CA_Conf, '-', DAY_Dt2CA_Conf)) <= GETDATE() THEN CAST(CONCAT(YEAR_Dt2CA_Conf, '-', MONTH_Dt2CA_Conf, '-', DAY_Dt2CA_Conf) AS date) ELSE NULL END AS Dt2CA_Conf, 
  CASE WHEN YEAR_Dt3CA_Conf IS NOT NULL AND MONTH_Dt3CA_Conf IS NOT NULL AND DAY_Dt3CA_Conf IS NOT NULL AND ISDATE(CONCAT(YEAR_Dt3CA_Conf, '-', MONTH_Dt3CA_Conf, '-', DAY_Dt3CA_Conf)) IS NOT NULL and TRY_CONVERT(DATE, CONCAT(YEAR_Dt3CA_Conf, '-', MONTH_Dt3CA_Conf, '-', DAY_Dt3CA_Conf)) <= GETDATE() THEN CAST(CONCAT(YEAR_Dt3CA_Conf, '-', MONTH_Dt3CA_Conf, '-', DAY_Dt3CA_Conf) AS date) ELSE NULL END AS Dt3CA_Conf, 
  Elapsed1stSurgChem, 
  Elapsed1stSurgLstCont, 
  ElapsedChemo1stSurg, 
  LengthToDtChemo, 
  LengthToDtHorm, 
  LengthToDtImmuno, 
  LengthToDtMstDefSurg, 
  LengthToDtRadStarted, 
  LengthToDtTrnsplnt, 
  LengthToFirstTx, 
  ElapsedRTStartEnd, 
  TumorSizeSumm, 
  Survival, 
  BestCSSummStage, 
  BestCSTNMStage, 
  T14UDF116, 
  T14UDF117, 
  T16UDF118, 
  Abstractor, 
  ClassCase, 
  SeqPrim, 
  Manage_MD, 
  MedOncMD, 
  RadOncMD, 
  PrimSurgeon, 
  Histology, 
  PresCA_Conf, 
  Pres2CA_Conf, 
  Pres3CA_Conf, 
  'M' AS Source_System_Code, 
  'v_currtimestamp' AS DW_Last_Update_Date_Time
from 
  (
    Select 
      Tum.TumorId as TumorId, 
      Tum.PatientId as PatientId, 
      Tum.Grade as Grade, 
      Exta.CaseStatFlag as CaseStatFlag, 
      Tum.PrimarySite as PrimarySite, 
      Tum.Primsitesubcode as Primsitesubcode, 
      Tum.MstDefChemoSumm as MstDefChemoSumm, 
      Tum.MstDefDxStageSumm as MstDefDxStageSumm, 
      Tum.MstDefHormSumm as MstDefHormSumm, 
      Tum.MstDefImmunoSumm as MstDefImmunoSumm, 
      Tum.MstDefMarginsSumm as MstDefMarginsSumm, 
      Tum.MstDefPallSumm as MstDefPallSumm, 
      Tum.MstDefRTBoost as MstDefRTBoost, 
      Tum.MstDefRTHosp as MstDefRTHosp, 
      Tum.MstDefRTLoc as MstDefRTLoc, 
      Extb.ReasonNoChemo as ReasonNoChemo, 
      Extb.ReasonNoHormone as ReasonNoHormone, 
      Extb.ReasonNoImmuno as ReasonNoImmuno, 
      Extb.ReasonNoRad as ReasonNoRad, 
      Tum.MstDefSurgPrimSumm as MstDefSurgPrimSumm, 
      TRIM(TUM.CS_SSFactor1) as CS_SS_Factor_1_Num_Code, 
      TRIM(TUM.CS_SSFactor2) as CS_SS_Factor_2_Num_Code, 
      coalesce(TRIM(TUM.CS_SSFactor15), '') as CS_SS_Factor_15_Num_Code, 
      coalesce(TRIM(TUM.CS_SSFactor16), '') as CS_SS_Factor_16_Num_Code, 
      coalesce(TRIM(TUM.CS_SSFactor22), '') as CS_SS_Factor_22_Num_Code, 
      coalesce(TRIM(TUM.CS_SSFactor23), '') as CS_SS_Factor_23_Num_Code, 
      coalesce(TRIM(TUM.CS_SSFactor25), '') as CS_SS_FACTOR_25_NUM_CODE, 
      Extb.ChemoSrgSeq as ChemoSrgSeq, 
      Tum.MstDefRTMod as MstDefRTMod, 
      Tum.MstDefRTVol as MstDefRTVol, 
      Tum.MstDefScopeLNSumm as MstDefScopeLNSumm, 
      Ext2.SurgAppHosp as SurgAppHosp, 
      Tum.MstDefSurgPrimHosp as MstDefSurgPrimHosp, 
      Tum.CS_TumSize as CS_TumSize, 
      Extb.Elapsed1stSurgChem as Elapsed1stSurgChem, 
      Extb.Elapsed1stSurgLstCont as Elapsed1stSurgLstCont, 
      Extb.ElapsedChemo1stSurg as ElapsedChemo1stSurg, 
      Extb.LengthToDtChemo as LengthToDtChemo, 
      Extb.LengthToDtHorm as LengthToDtHorm, 
      Extb.LengthToDtImmuno as LengthToDtImmuno, 
      Extb.LengthToDtMstDefSurg as LengthToDtMstDefSurg, 
      Extb.LengthToDtRadStarted as LengthToDtRadStarted, 
      Extb.LengthToDtTrnsplnt as LengthToDtTrnsplnt, 
      Extb.LengthToFirstTx as LengthToFirstTx, 
      Extb.ElapsedRTStartEnd as ElapsedRTStartEnd, 
      Exta.TumorSizeSumm as TumorSizeSumm, 
      Tum.Survival as Survival, 
      Tum.BestCSSummStage as BestCSSummStage, 
      TRIM(Tum.BestStage) AS BestCSTNMStage, 
      Tum14.T14UDF116 as T14UDF116, 
      Tum14.T14UDF117 as T14UDF117, 
      Tum16.T16UDF118 as T16UDF118, 
      TRIM(Exta.Abstractor) as Abstractor, 
      Exta.ClassCase as ClassCase, 
      Exta.SeqPrim as SeqPrim, 
      Extb.Manage_MD as Manage_MD, 
      Extb.MedOncMD as MedOncMD, 
      Extb.RadOncMD as RadOncMD, 
      Extb.PrimSurgeon as PrimSurgeon, 
      tum.Histology as Histology, 
      Extb.PresCA_Conf, 
      Extb.Pres2CA_Conf, 
      Extb.Pres3CA_Conf as Pres3CA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DateAdmis))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 7, 2) END ELSE NULL END AS DAY_DateAdmis, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, Dt2CA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 7, 2) END ELSE NULL END AS DAY_Dt2CA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, Dt3CA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 7, 2) END ELSE NULL END AS DAY_Dt3CA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtCA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 7, 2) END ELSE NULL END AS DAY_DtCA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtFirstSurg))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 7, 2) END ELSE NULL END AS DAY_DtFirstSurg, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtMstDefSurg))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 7, 2) END ELSE NULL END AS DAY_DtMstDefSurg, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefChemoDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 7, 2) END ELSE NULL END AS DAY_MstDefChemoDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefHormDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 7, 2) END ELSE NULL END AS DAY_MstDefHormDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefImmunoDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 7, 2) END ELSE NULL END AS DAY_MstDefImmunoDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefRTDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 7, 2) END ELSE NULL END AS DAY_MstDefRTDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefRTStopDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 7, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 7, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 7, 2)) > 31 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 7, 2) END ELSE NULL END AS DAY_MstDefRTStopDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DateAdmis))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DateAdmis)), 5, 2) END ELSE NULL END AS MONTH_DateAdmis, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, Dt2CA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, Dt2CA_Conf)), 5, 2) END ELSE NULL END AS MONTH_Dt2CA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, Dt3CA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, Dt3CA_Conf)), 5, 2) END ELSE NULL END AS MONTH_Dt3CA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtCA_Conf))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtCA_Conf)), 5, 2) END ELSE NULL END AS MONTH_DtCA_Conf, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtFirstSurg))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtFirstSurg)), 5, 2) END ELSE NULL END AS MONTH_DtFirstSurg, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, DtMstDefSurg))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, DtMstDefSurg)), 5, 2) END ELSE NULL END AS MONTH_DtMstDefSurg, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefChemoDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefChemoDt)), 5, 2) END ELSE NULL END AS MONTH_MstDefChemoDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefHormDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefHormDt)), 5, 2) END ELSE NULL END AS MONTH_MstDefHormDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefImmunoDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefImmunoDt)), 5, 2) END ELSE NULL END AS MONTH_MstDefImmunoDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefRTDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTDt)), 5, 2) END ELSE NULL END AS MONTH_MstDefRTDt, 
      CASE  WHEN LEN(RTRIM(CONVERT(numeric, MstDefRTStopDt))) = 8 THEN  CASE  WHEN SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 5, 2) = '99' OR SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 5, 2) = '00' THEN '01' WHEN TRY_CONVERT(INT, SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 5, 2)) > 12 THEN NULL ELSE SUBSTRING(RTRIM(CONVERT(numeric, MstDefRTStopDt)), 5, 2) END ELSE NULL END AS MONTH_MstDefRTStopDt, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, DateAdmis)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,DateAdmis))), 1, 4) ELSE NULL END AS YEAR_DateAdmis, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, Dt2CA_Conf)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,Dt2CA_Conf))), 1, 4) ELSE NULL END AS YEAR_Dt2CA_Conf, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, Dt3CA_Conf)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,Dt3CA_Conf))), 1, 4) ELSE NULL END AS YEAR_Dt3CA_Conf, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, DtCA_Conf)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,DtCA_Conf))), 1, 4) ELSE NULL END AS YEAR_DtCA_Conf, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, DtFirstSurg)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,DtFirstSurg))), 1, 4) ELSE NULL END AS YEAR_DtFirstSurg, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, DtMstDefSurg)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,DtMstDefSurg))), 1, 4) ELSE NULL END AS YEAR_DtMstDefSurg, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, MstDefChemoDt)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,MstDefChemoDt))), 1, 4) ELSE NULL END AS YEAR_MstDefChemoDt, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, MstDefHormDt)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,MstDefHormDt))), 1, 4) ELSE NULL END AS YEAR_MstDefHormDt, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, MstDefImmunoDt)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,MstDefImmunoDt))), 1, 4) ELSE NULL END AS YEAR_MstDefImmunoDt, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, MstDefRTDt)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,MstDefRTDt))), 1, 4) ELSE NULL END AS YEAR_MstDefRTDt, 
      CASE  WHEN LEN(LTRIM(RTRIM(CONVERT(numeric, MstDefRTStopDt)))) = 8 THEN SUBSTRING(LTRIM(RTRIM(CONVERT(numeric,MstDefRTStopDt))), 1, 4) ELSE NULL END AS YEAR_MstDefRTStopDt
    from 
      mRegistry.dbo.Tumor Tum 
      Left Outer Join mRegistry.dbo.TumorExt1b Extb on Tum.Tumorid = Extb.Tumorid 
      Left Outer Join mRegistry.dbo.TumorExt1a Exta on Tum.Tumorid = Exta.Tumorid 
      Left Outer Join mRegistry.dbo.TumorExt2 Ext2 on Tum.Tumorid = Ext2.Tumorid 
      Left Outer Join mRegistry.dbo.TumorExt14 Tum14 on Tum.Tumorid = Tum14.Tumorid 
      Left Outer Join mRegistry.dbo.TumorExt16 Tum16 on Tum.Tumorid = Tum16.Tumorid
  ) mm;