CREATE OR REPLACE VIEW {{ params.param_hr_base_views_dataset_name }}.employee
AS SELECT
    employee.employee_sid,
    employee.valid_from_date,
    employee.valid_to_date,
    employee.process_level_sid,
    employee.dept_sid,
    employee.location_code,
    employee.pay_grade_code,
    employee.union_code,
    employee.user_level_code,
    employee.lawson_company_num,
    employee.process_level_code,
    employee.employee_num,
    employee.account_unit_num,
    employee.gl_company_num,
    employee.dept_code,
    employee.employee_34_login_code,
    employee.adjusted_hire_date,
    employee.anniversary_date,
    employee.termination_date,
    employee.hire_date,
    employee.new_hire_date,
    employee.primary_facility_ind,
    employee.fte_percent,
    employee.pay_grade_schedule_code,
    employee.pay_step_num,
    employee.pay_rate_amt,
    employee.security_key_text,
    employee.remote_sw,
    employee.active_dw_ind,
    employee.delete_ind,
    employee.source_system_code,
    employee.dw_last_update_date_time
  FROM
   {{ params.param_hr_core_dataset_name }}.employee;