CREATE OR REPLACE VIEW {{ params.param_hr_base_views_dataset_name }}.employee_goal_detail
AS SELECT
    employee_goal_detail.employee_goal_detail_sid,
    employee_goal_detail.valid_from_date,
    employee_goal_detail.employee_talent_profile_sid,
    employee_goal_detail.employee_sid,
    employee_goal_detail.employee_goal_year_num,
    employee_goal_detail.goal_name,
    employee_goal_detail.goal_category_id,
    employee_goal_detail.goal_weight_pct,
    employee_goal_detail.expected_result_text,
    employee_goal_detail.goal_measurement_text,
    employee_goal_detail.goal_status_id,
    employee_goal_detail.goal_progress_status_id,
    employee_goal_detail.goal_performance_plan_id,
    employee_goal_detail.goal_due_date,
    employee_goal_detail.user_defined_date,
    employee_goal_detail.review_year_num,
    employee_goal_detail.review_period_end_date,
    employee_goal_detail.review_period_start_date,
    employee_goal_detail.review_period_id,
    employee_goal_detail.manager_goal_performance_rating_id,
    employee_goal_detail.manager_goal_performance_rating_num,
    employee_goal_detail.employee_goal_performance_rating_id,
    employee_goal_detail.employee_goal_performance_rating_num,
    employee_goal_detail.employee_num,
    employee_goal_detail.lawson_company_num,
    employee_goal_detail.process_level_code,
    employee_goal_detail.valid_to_date,
    employee_goal_detail.source_system_key,
    employee_goal_detail.source_system_code,
    employee_goal_detail.dw_last_update_date_time
  FROM
    {{ params.param_hr_core_dataset_name }}.employee_goal_detail;