create or replace view `{{ params.param_hr_base_views_dataset_name }}.fact_hr_metric_snapshot`
AS SELECT
    fact_hr_metric_snapshot.employee_sid,
    fact_hr_metric_snapshot.requisition_sid,
    fact_hr_metric_snapshot.position_sid,
    fact_hr_metric_snapshot.date_id,
    fact_hr_metric_snapshot.analytics_msr_sid,
    fact_hr_metric_snapshot.snapshot_date,
    fact_hr_metric_snapshot.dept_sid,
    fact_hr_metric_snapshot.job_class_sid,
    fact_hr_metric_snapshot.job_code_sid,
    fact_hr_metric_snapshot.location_code,
    fact_hr_metric_snapshot.coid,
    fact_hr_metric_snapshot.company_code,
    fact_hr_metric_snapshot.functional_dept_num,
    fact_hr_metric_snapshot.sub_functional_dept_num,
    fact_hr_metric_snapshot.auxiliary_status_sid,
    fact_hr_metric_snapshot.employee_status_sid,
    fact_hr_metric_snapshot.key_talent_id,
    fact_hr_metric_snapshot.integrated_lob_id,
    fact_hr_metric_snapshot.action_code,
    fact_hr_metric_snapshot.action_reason_text,
    fact_hr_metric_snapshot.lawson_company_num,
    fact_hr_metric_snapshot.process_level_code,
    fact_hr_metric_snapshot.work_schedule_code,
    fact_hr_metric_snapshot.recruiter_owner_user_sid,
    fact_hr_metric_snapshot.requisition_approval_date,
    fact_hr_metric_snapshot.employee_num,
    fact_hr_metric_snapshot.metric_numerator_qty,
    fact_hr_metric_snapshot.metric_denominator_qty,
    fact_hr_metric_snapshot.source_system_code,
    fact_hr_metric_snapshot.dw_last_update_date_time
  FROM
    {{ params.param_hr_core_dataset_name }}.fact_hr_metric_snapshot;