CREATE OR REPLACE VIEW {{ params.param_hr_base_views_dataset_name }}.job_position
AS SELECT
    job_position.position_sid,
    job_position.eff_from_date,
    job_position.valid_from_date,
    job_position.valid_to_date,
    job_position.link_supervisor_sid,
    job_position.supervisor_sid,
    job_position.job_code_sid,
    job_position.hr_company_sid,
    job_position.position_change_reason_code,
    job_position.location_code,
    job_position.pay_grade_code,
    job_position.position_code,
    job_position.account_unit_num,
    job_position.gl_company_num,
    job_position.overtime_plan_code,
    job_position.overtime_exempt_ind,
    job_position.position_code_desc,
    job_position.company_position_eff_from_date,
    job_position.company_position_eff_to_date,
    job_position.pay_grade_schedule_code,
    job_position.pay_step_num,
    job_position.union_code,
    job_position.shift_num,
    job_position.eff_to_date,
    job_position.lawson_object_id,
    job_position.schedule_work_code,
    job_position.user_level_code,
    job_position.dept_sid,
    job_position.lawson_company_num,
    job_position.process_level_code,
    job_position.active_dw_ind,
    job_position.source_system_code,
    job_position.dw_last_update_date_time
  FROM
   {{ params.param_hr_core_dataset_name }}.job_position;