create or replace view `{{ params.param_hr_base_views_dataset_name }}.requisition_process_level`
AS SELECT
requisition_process_level.requisition_sid,
requisition_process_level.valid_from_date,
requisition_process_level.process_level_sid,
requisition_process_level.valid_to_date,
requisition_process_level.requisition_num,
requisition_process_level.lawson_company_num,
requisition_process_level.process_level_code,
requisition_process_level.security_key_text,
requisition_process_level.source_system_code,
requisition_process_level.dw_last_update_date_time
  FROM
    {{ params.param_hr_core_dataset_name }}.requisition_process_level;