create or replace view `{{ params.param_hr_base_views_dataset_name }}.requisition`
AS SELECT
    requisition.requisition_sid,
    requisition.valid_from_date,
    requisition.valid_to_date,
    requisition.hr_company_sid,
    requisition.application_status_sid,
    requisition.lawson_company_num,
    requisition.process_level_code,
    requisition.location_code,
    requisition.requisition_num,
    requisition.requisition_desc,
    requisition.requisition_eff_date,
    requisition.requisition_open_date,
    requisition.requisition_closed_date,
    requisition.requisition_origination_date,
    requisition.originator_login_3_4_code,
    requisition.position_needed_date,
    requisition.job_opening_cnt,
    requisition.open_fte_percent,
    requisition.filled_fte_percent,
    requisition.last_update_date,
    requisition.replacement_employee_num,
    requisition.replacement_employee_sid,
    requisition.replacement_flag,
    requisition.special_requirement_text,
    requisition.work_schedule_code,
    requisition.union_code,
    requisition.active_dw_ind,
    requisition.security_key_text,
    requisition.source_system_code,
    requisition.dw_last_update_date_time
  FROM
    {{ params.param_hr_core_dataset_name }}.requisition;