
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.PV_JuncClaimLineChargeFirstLastKeyMeasure AS target
USING {{ params.param_psc_stage_dataset_name }}.PV_JuncClaimLineChargeFirstLastKeyMeasure AS source
ON target.ClaimLineChargeKey = source.ClaimLineChargeKey
WHEN MATCHED THEN
  UPDATE SET
  target.ClaimLineChargeKey = source.ClaimLineChargeKey,
 target.ClaimKey = source.ClaimKey,
 target.LastClaimKey = source.LastClaimKey,
 target.LastClaimNumber = source.LastClaimNumber,
 target.ClaimNumber = source.ClaimNumber,
 target.LastVoidDateKey = source.LastVoidDateKey,
 target.COID = TRIM(source.COID),
 target.RegionKey = source.RegionKey,
 target.ARClaimFlag = source.ARClaimFlag,
 target.ClaimVoidFlag = source.ClaimVoidFlag,
 target.ClaimDeleteFlag = source.ClaimDeleteFlag,
 target.ClaimTotalBalanceAmt = source.ClaimTotalBalanceAmt,
 target.ClaimTotalChargesAmt = source.ClaimTotalChargesAmt,
 target.CPTCode = TRIM(source.CPTCode),
 target.CPTCodeKey = source.CPTCodeKey,
 target.CPTDeleteFlag = source.CPTDeleteFlag,
 target.CPTOrder = source.CPTOrder,
 target.CPTModifier1 = TRIM(source.CPTModifier1),
 target.CPTModifier2 = TRIM(source.CPTModifier2),
 target.SourceAPrimaryKeyValue = TRIM(source.SourceAPrimaryKeyValue),
 target.CPTCharges = source.CPTCharges,
 target.PaymentAmt = source.PaymentAmt,
 target.AdjustmentAmt = source.AdjustmentAmt,
 target.CalculatedLineBalance = source.CalculatedLineBalance,
 target.CalculatedLineBalanceAdjusted = source.CalculatedLineBalanceAdjusted,
 target.FinancialAdjustmentsAmt = source.FinancialAdjustmentsAmt,
 target.FirstFinancialAdjustmentNonZeroSumDateKey = source.FirstFinancialAdjustmentNonZeroSumDateKey,
 target.LastFinancialAdjustmentNonZeroSumDateKey = source.LastFinancialAdjustmentNonZeroSumDateKey,
 target.AdjustmentRefundAmt = source.AdjustmentRefundAmt,
 target.FirstAdjRefundNonZeroSumDateKey = source.FirstAdjRefundNonZeroSumDateKey,
 target.LastAdjRefundNonZeroSumDateKey = source.LastAdjRefundNonZeroSumDateKey,
 target.AdjustmentDenialAmt = source.AdjustmentDenialAmt,
 target.FirstAdjDenialNonZeroSumDateKey = source.FirstAdjDenialNonZeroSumDateKey,
 target.LastAdjDenialNonZeroSumDateKey = source.LastAdjDenialNonZeroSumDateKey,
 target.AdjustmentBadDebtAmt = source.AdjustmentBadDebtAmt,
 target.FirstAdjBadDebtNonZeroSumDateKey = source.FirstAdjBadDebtNonZeroSumDateKey,
 target.LastAdjBadDebtNonZeroSumDateKey = source.LastAdjBadDebtNonZeroSumDateKey,
 target.AdjustmentCharityAmt = source.AdjustmentCharityAmt,
 target.FirstAdjCharityNonZeroSumDateKey = source.FirstAdjCharityNonZeroSumDateKey,
 target.LastAdjCharityNonZeroSumDateKey = source.LastAdjCharityNonZeroSumDateKey,
 target.AdjustmentUninsuredAmt = source.AdjustmentUninsuredAmt,
 target.FirstAdjUninsuredDiscountNonZeroSumDateKey = source.FirstAdjUninsuredDiscountNonZeroSumDateKey,
 target.LastAdjUninsuredDiscountNonZeroSumDateKey = source.LastAdjUninsuredDiscountNonZeroSumDateKey,
 target.AdjustmentAdministrationAmt = source.AdjustmentAdministrationAmt,
 target.FirstAdjAdministrationNonZeroSumDateKey = source.FirstAdjAdministrationNonZeroSumDateKey,
 target.LastAdjAdministrationNonZeroSumDateKey = source.LastAdjAdministrationNonZeroSumDateKey,
 target.AdjustmentNSFAmt = source.AdjustmentNSFAmt,
 target.FirstAdjNSFNonZeroSumDateKey = source.FirstAdjNSFNonZeroSumDateKey,
 target.LastAdjNSFNonZeroSumDateKey = source.LastAdjNSFNonZeroSumDateKey,
 target.AdjustmentEscheatAmt = source.AdjustmentEscheatAmt,
 target.FirstAdjEscheatNonZeroSumDateKey = source.FirstAdjEscheatNonZeroSumDateKey,
 target.LastAdjEscheatNonZeroSumDateKey = source.LastAdjEscheatNonZeroSumDateKey,
 target.AdjustmentInterestAmt = source.AdjustmentInterestAmt,
 target.FirstAdjInterestNonZeroSumDateKey = source.FirstAdjInterestNonZeroSumDateKey,
 target.LastAdjInterestNonZeroSumDateKey = source.LastAdjInterestNonZeroSumDateKey,
 target.AdjustmentContractualAmt = source.AdjustmentContractualAmt,
 target.FirstAdjContractualNonZeroSumDateKey = source.FirstAdjContractualNonZeroSumDateKey,
 target.LastAdjContractualNonZeroSumDateKey = source.LastAdjContractualNonZeroSumDateKey,
 target.PaymentContracualAdjustmentsAmt = source.PaymentContracualAdjustmentsAmt,
 target.FirstPaymentContractualAdjDateKey = source.FirstPaymentContractualAdjDateKey,
 target.LastPaymentContractualAdjDateKey = source.LastPaymentContractualAdjDateKey,
 target.AdjustmentOtherAmt = source.AdjustmentOtherAmt,
 target.FirstAdjOtherNonZeroSumDateKey = source.FirstAdjOtherNonZeroSumDateKey,
 target.LastAdjOtherNonZeroSumDateKey = source.LastAdjOtherNonZeroSumDateKey,
 target.PatientPaymentAmt = source.PatientPaymentAmt,
 target.InsurancePaymentAmt = source.InsurancePaymentAmt,
 target.MaxAllowedAmt = source.MaxAllowedAmt,
 target.FirstInsuranceClaimPaymentDateKey = source.FirstInsuranceClaimPaymentDateKey,
 target.LastInsuranceClaimPaymentDateKey = source.LastInsuranceClaimPaymentDateKey,
 target.FirstInsuranceClaimLinePaymentCreatedDateKey = source.FirstInsuranceClaimLinePaymentCreatedDateKey,
 target.LastInsuranceClaimLinePaymentCreatedDateKey = source.LastInsuranceClaimLinePaymentCreatedDateKey,
 target.FirstPatientClaimPaymentDateKey = source.FirstPatientClaimPaymentDateKey,
 target.LastPatientClaimPaymentDateKey = source.LastPatientClaimPaymentDateKey,
 target.FirstPatientClaimLinePaymentCreatedDateKey = source.FirstPatientClaimLinePaymentCreatedDateKey,
 target.LastPatientClaimLinePaymentCreatedDateKey = source.LastPatientClaimLinePaymentCreatedDateKey,
 target.InitialDeniedChargesAmt = source.InitialDeniedChargesAmt,
 target.FirstDenialERADateKey = source.FirstDenialERADateKey,
 target.FirstDenialCarcRarcCode = TRIM(source.FirstDenialCarcRarcCode),
 target.FirstDenialCARCCodes = TRIM(source.FirstDenialCARCCodes),
 target.FirstDenialRARCCodes = TRIM(source.FirstDenialRARCCodes),
 target.FirstDenialPayerName = TRIM(source.FirstDenialPayerName),
 target.FirstDenialCarcRarcType = TRIM(source.FirstDenialCarcRarcType),
 target.FirstDenialCARCIsDenial = TRIM(source.FirstDenialCARCIsDenial),
 target.FirstDenialCARCRequiresRarc = TRIM(source.FirstDenialCARCRequiresRarc),
 target.FirstDenialRARCIsDenial = TRIM(source.FirstDenialRARCIsDenial),
 target.FirstDenialCategory = TRIM(source.FirstDenialCategory),
 target.LastDenialERADateKey = source.LastDenialERADateKey,
 target.LastDenialCarcRarcCode = TRIM(source.LastDenialCarcRarcCode),
 target.LastDenialCARCCodes = TRIM(source.LastDenialCARCCodes),
 target.LastDenialRARCCodes = TRIM(source.LastDenialRARCCodes),
 target.LastDenialPayerName = TRIM(source.LastDenialPayerName),
 target.LastDenialCarcRarcType = TRIM(source.LastDenialCarcRarcType),
 target.LastDenialCARCIsDenial = TRIM(source.LastDenialCARCIsDenial),
 target.LastDenialCARCRequiresRarc = TRIM(source.LastDenialCARCRequiresRarc),
 target.LastDenialRARCIsDenial = TRIM(source.LastDenialRARCIsDenial),
 target.LastDenialCategory = TRIM(source.LastDenialCategory),
 target.FirstERACarcRarcCode = TRIM(source.FirstERACarcRarcCode),
 target.FirstERADateKey = source.FirstERADateKey,
 target.FirstERACARCCodes = TRIM(source.FirstERACARCCodes),
 target.FirstERARARCCodes = TRIM(source.FirstERARARCCodes),
 target.FirstERAPayerName = TRIM(source.FirstERAPayerName),
 target.FirstERACategory = TRIM(source.FirstERACategory),
 target.FirstERACarcRarcType = TRIM(source.FirstERACarcRarcType),
 target.FirstERACARCIsDenial = TRIM(source.FirstERACARCIsDenial),
 target.FirstERACARCRequiresRarc = TRIM(source.FirstERACARCRequiresRarc),
 target.FirstERARARCIsDenial = TRIM(source.FirstERARARCIsDenial),
 target.DenialLineCount = source.DenialLineCount,
 target.LastERACarcRarcCode = TRIM(source.LastERACarcRarcCode),
 target.LastERADateKey = source.LastERADateKey,
 target.LastERACARCCodes = TRIM(source.LastERACARCCodes),
 target.LastERARARCCodes = TRIM(source.LastERARARCCodes),
 target.LastERAPayerName = TRIM(source.LastERAPayerName),
 target.DenialLastEraDateKey = source.DenialLastEraDateKey,
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime,
 target.SourceSystemCode = TRIM(source.SourceSystemCode),
 target.InsertedBy = TRIM(source.InsertedBy),
 target.InsertedDTM = source.InsertedDTM,
 target.ModifiedBy = TRIM(source.ModifiedBy),
 target.ModifiedDTM = source.ModifiedDTM,
 target.FirstInitialDenialFlag = source.FirstInitialDenialFlag,
 target.FirstInsuranceClaimLinePaymentNonZeroSumPostedDateKey = source.FirstInsuranceClaimLinePaymentNonZeroSumPostedDateKey,
 target.FirstPatientClaimLinePaymentNonZeroSumPostedDateKey = source.FirstPatientClaimLinePaymentNonZeroSumPostedDateKey,
 target.FirstPaymentContractualAdjNonZeroSumPostedDateKey = source.FirstPaymentContractualAdjNonZeroSumPostedDateKey,
 target.LastERACategory = TRIM(source.LastERACategory),
 target.LastERACarcRarcType = TRIM(source.LastERACarcRarcType),
 target.LastERACARCIsDenial = TRIM(source.LastERACARCIsDenial),
 target.LastERACARCRequiresRarc = TRIM(source.LastERACARCRequiresRarc),
 target.LastERARARCIsDenial = TRIM(source.LastERARARCIsDenial),
 target.CPTModifier3 = TRIM(source.CPTModifier3),
 target.CPTModifier4 = TRIM(source.CPTModifier4),
 target.CPTStartServiceDateKey = source.CPTStartServiceDateKey,
 target.CPTEndServiceDateKey = source.CPTEndServiceDateKey,
 target.FirstDenialOverrideKey = source.FirstDenialOverrideKey,
 target.FirstProcessedDateKey = source.FirstProcessedDateKey,
 target.FirstChargeValueKey = source.FirstChargeValueKey,
 target.LastProcessedDateKey = source.LastProcessedDateKey,
 target.LastChargeValueKey = source.LastChargeValueKey,
 target.InitialIplanKey = source.InitialIplanKey
WHEN NOT MATCHED THEN
  INSERT (ClaimLineChargeKey, ClaimKey, LastClaimKey, LastClaimNumber, ClaimNumber, LastVoidDateKey, COID, RegionKey, ARClaimFlag, ClaimVoidFlag, ClaimDeleteFlag, ClaimTotalBalanceAmt, ClaimTotalChargesAmt, CPTCode, CPTCodeKey, CPTDeleteFlag, CPTOrder, CPTModifier1, CPTModifier2, SourceAPrimaryKeyValue, CPTCharges, PaymentAmt, AdjustmentAmt, CalculatedLineBalance, CalculatedLineBalanceAdjusted, FinancialAdjustmentsAmt, FirstFinancialAdjustmentNonZeroSumDateKey, LastFinancialAdjustmentNonZeroSumDateKey, AdjustmentRefundAmt, FirstAdjRefundNonZeroSumDateKey, LastAdjRefundNonZeroSumDateKey, AdjustmentDenialAmt, FirstAdjDenialNonZeroSumDateKey, LastAdjDenialNonZeroSumDateKey, AdjustmentBadDebtAmt, FirstAdjBadDebtNonZeroSumDateKey, LastAdjBadDebtNonZeroSumDateKey, AdjustmentCharityAmt, FirstAdjCharityNonZeroSumDateKey, LastAdjCharityNonZeroSumDateKey, AdjustmentUninsuredAmt, FirstAdjUninsuredDiscountNonZeroSumDateKey, LastAdjUninsuredDiscountNonZeroSumDateKey, AdjustmentAdministrationAmt, FirstAdjAdministrationNonZeroSumDateKey, LastAdjAdministrationNonZeroSumDateKey, AdjustmentNSFAmt, FirstAdjNSFNonZeroSumDateKey, LastAdjNSFNonZeroSumDateKey, AdjustmentEscheatAmt, FirstAdjEscheatNonZeroSumDateKey, LastAdjEscheatNonZeroSumDateKey, AdjustmentInterestAmt, FirstAdjInterestNonZeroSumDateKey, LastAdjInterestNonZeroSumDateKey, AdjustmentContractualAmt, FirstAdjContractualNonZeroSumDateKey, LastAdjContractualNonZeroSumDateKey, PaymentContracualAdjustmentsAmt, FirstPaymentContractualAdjDateKey, LastPaymentContractualAdjDateKey, AdjustmentOtherAmt, FirstAdjOtherNonZeroSumDateKey, LastAdjOtherNonZeroSumDateKey, PatientPaymentAmt, InsurancePaymentAmt, MaxAllowedAmt, FirstInsuranceClaimPaymentDateKey, LastInsuranceClaimPaymentDateKey, FirstInsuranceClaimLinePaymentCreatedDateKey, LastInsuranceClaimLinePaymentCreatedDateKey, FirstPatientClaimPaymentDateKey, LastPatientClaimPaymentDateKey, FirstPatientClaimLinePaymentCreatedDateKey, LastPatientClaimLinePaymentCreatedDateKey, InitialDeniedChargesAmt, FirstDenialERADateKey, FirstDenialCarcRarcCode, FirstDenialCARCCodes, FirstDenialRARCCodes, FirstDenialPayerName, FirstDenialCarcRarcType, FirstDenialCARCIsDenial, FirstDenialCARCRequiresRarc, FirstDenialRARCIsDenial, FirstDenialCategory, LastDenialERADateKey, LastDenialCarcRarcCode, LastDenialCARCCodes, LastDenialRARCCodes, LastDenialPayerName, LastDenialCarcRarcType, LastDenialCARCIsDenial, LastDenialCARCRequiresRarc, LastDenialRARCIsDenial, LastDenialCategory, FirstERACarcRarcCode, FirstERADateKey, FirstERACARCCodes, FirstERARARCCodes, FirstERAPayerName, FirstERACategory, FirstERACarcRarcType, FirstERACARCIsDenial, FirstERACARCRequiresRarc, FirstERARARCIsDenial, DenialLineCount, LastERACarcRarcCode, LastERADateKey, LastERACARCCodes, LastERARARCCodes, LastERAPayerName, DenialLastEraDateKey, DWLastUpdateDateTime, SourceSystemCode, InsertedBy, InsertedDTM, ModifiedBy, ModifiedDTM, FirstInitialDenialFlag, FirstInsuranceClaimLinePaymentNonZeroSumPostedDateKey, FirstPatientClaimLinePaymentNonZeroSumPostedDateKey, FirstPaymentContractualAdjNonZeroSumPostedDateKey, LastERACategory, LastERACarcRarcType, LastERACARCIsDenial, LastERACARCRequiresRarc, LastERARARCIsDenial, CPTModifier3, CPTModifier4, CPTStartServiceDateKey, CPTEndServiceDateKey, FirstDenialOverrideKey, FirstProcessedDateKey, FirstChargeValueKey, LastProcessedDateKey, LastChargeValueKey, InitialIplanKey)
  VALUES (source.ClaimLineChargeKey, source.ClaimKey, source.LastClaimKey, source.LastClaimNumber, source.ClaimNumber, source.LastVoidDateKey, TRIM(source.COID), source.RegionKey, source.ARClaimFlag, source.ClaimVoidFlag, source.ClaimDeleteFlag, source.ClaimTotalBalanceAmt, source.ClaimTotalChargesAmt, TRIM(source.CPTCode), source.CPTCodeKey, source.CPTDeleteFlag, source.CPTOrder, TRIM(source.CPTModifier1), TRIM(source.CPTModifier2), TRIM(source.SourceAPrimaryKeyValue), source.CPTCharges, source.PaymentAmt, source.AdjustmentAmt, source.CalculatedLineBalance, source.CalculatedLineBalanceAdjusted, source.FinancialAdjustmentsAmt, source.FirstFinancialAdjustmentNonZeroSumDateKey, source.LastFinancialAdjustmentNonZeroSumDateKey, source.AdjustmentRefundAmt, source.FirstAdjRefundNonZeroSumDateKey, source.LastAdjRefundNonZeroSumDateKey, source.AdjustmentDenialAmt, source.FirstAdjDenialNonZeroSumDateKey, source.LastAdjDenialNonZeroSumDateKey, source.AdjustmentBadDebtAmt, source.FirstAdjBadDebtNonZeroSumDateKey, source.LastAdjBadDebtNonZeroSumDateKey, source.AdjustmentCharityAmt, source.FirstAdjCharityNonZeroSumDateKey, source.LastAdjCharityNonZeroSumDateKey, source.AdjustmentUninsuredAmt, source.FirstAdjUninsuredDiscountNonZeroSumDateKey, source.LastAdjUninsuredDiscountNonZeroSumDateKey, source.AdjustmentAdministrationAmt, source.FirstAdjAdministrationNonZeroSumDateKey, source.LastAdjAdministrationNonZeroSumDateKey, source.AdjustmentNSFAmt, source.FirstAdjNSFNonZeroSumDateKey, source.LastAdjNSFNonZeroSumDateKey, source.AdjustmentEscheatAmt, source.FirstAdjEscheatNonZeroSumDateKey, source.LastAdjEscheatNonZeroSumDateKey, source.AdjustmentInterestAmt, source.FirstAdjInterestNonZeroSumDateKey, source.LastAdjInterestNonZeroSumDateKey, source.AdjustmentContractualAmt, source.FirstAdjContractualNonZeroSumDateKey, source.LastAdjContractualNonZeroSumDateKey, source.PaymentContracualAdjustmentsAmt, source.FirstPaymentContractualAdjDateKey, source.LastPaymentContractualAdjDateKey, source.AdjustmentOtherAmt, source.FirstAdjOtherNonZeroSumDateKey, source.LastAdjOtherNonZeroSumDateKey, source.PatientPaymentAmt, source.InsurancePaymentAmt, source.MaxAllowedAmt, source.FirstInsuranceClaimPaymentDateKey, source.LastInsuranceClaimPaymentDateKey, source.FirstInsuranceClaimLinePaymentCreatedDateKey, source.LastInsuranceClaimLinePaymentCreatedDateKey, source.FirstPatientClaimPaymentDateKey, source.LastPatientClaimPaymentDateKey, source.FirstPatientClaimLinePaymentCreatedDateKey, source.LastPatientClaimLinePaymentCreatedDateKey, source.InitialDeniedChargesAmt, source.FirstDenialERADateKey, TRIM(source.FirstDenialCarcRarcCode), TRIM(source.FirstDenialCARCCodes), TRIM(source.FirstDenialRARCCodes), TRIM(source.FirstDenialPayerName), TRIM(source.FirstDenialCarcRarcType), TRIM(source.FirstDenialCARCIsDenial), TRIM(source.FirstDenialCARCRequiresRarc), TRIM(source.FirstDenialRARCIsDenial), TRIM(source.FirstDenialCategory), source.LastDenialERADateKey, TRIM(source.LastDenialCarcRarcCode), TRIM(source.LastDenialCARCCodes), TRIM(source.LastDenialRARCCodes), TRIM(source.LastDenialPayerName), TRIM(source.LastDenialCarcRarcType), TRIM(source.LastDenialCARCIsDenial), TRIM(source.LastDenialCARCRequiresRarc), TRIM(source.LastDenialRARCIsDenial), TRIM(source.LastDenialCategory), TRIM(source.FirstERACarcRarcCode), source.FirstERADateKey, TRIM(source.FirstERACARCCodes), TRIM(source.FirstERARARCCodes), TRIM(source.FirstERAPayerName), TRIM(source.FirstERACategory), TRIM(source.FirstERACarcRarcType), TRIM(source.FirstERACARCIsDenial), TRIM(source.FirstERACARCRequiresRarc), TRIM(source.FirstERARARCIsDenial), source.DenialLineCount, TRIM(source.LastERACarcRarcCode), source.LastERADateKey, TRIM(source.LastERACARCCodes), TRIM(source.LastERARARCCodes), TRIM(source.LastERAPayerName), source.DenialLastEraDateKey, source.DWLastUpdateDateTime, TRIM(source.SourceSystemCode), TRIM(source.InsertedBy), source.InsertedDTM, TRIM(source.ModifiedBy), source.ModifiedDTM, source.FirstInitialDenialFlag, source.FirstInsuranceClaimLinePaymentNonZeroSumPostedDateKey, source.FirstPatientClaimLinePaymentNonZeroSumPostedDateKey, source.FirstPaymentContractualAdjNonZeroSumPostedDateKey, TRIM(source.LastERACategory), TRIM(source.LastERACarcRarcType), TRIM(source.LastERACARCIsDenial), TRIM(source.LastERACARCRequiresRarc), TRIM(source.LastERARARCIsDenial), TRIM(source.CPTModifier3), TRIM(source.CPTModifier4), source.CPTStartServiceDateKey, source.CPTEndServiceDateKey, source.FirstDenialOverrideKey, source.FirstProcessedDateKey, source.FirstChargeValueKey, source.LastProcessedDateKey, source.LastChargeValueKey, source.InitialIplanKey);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT ClaimLineChargeKey
      FROM {{ params.param_psc_core_dataset_name }}.PV_JuncClaimLineChargeFirstLastKeyMeasure
      GROUP BY ClaimLineChargeKey
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.PV_JuncClaimLineChargeFirstLastKeyMeasure');
ELSE
  COMMIT TRANSACTION;
END IF;
