-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_account.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_account
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Data Warehouse Account Id.\r[F:18-N]'),
  company_code STRING NOT NULL OPTIONS(description='Indicates the originating company code used by the Payroll system for reporting Payroll Taxes.  Valid values are:  \'H\' = HCA, \'M\'= Quorum Managed, \'N\' = Non-Affiliated, \'A\' = Lifepoint, and \'P\' = Triad.\r[F:1-AN] '),
  coid STRING NOT NULL OPTIONS(description='The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  unit_num STRING OPTIONS(description='4-digit corporate assigned number which uniquely identifies each facility.\r[F:4/N]'),
  pat_acct_num NUMERIC(29) OPTIONS(description='Unique identification number assigned by the facility to a patient at admit/registration time.\r[F: 12-N]'),
  account_id BIGNUMERIC(38) NOT NULL OPTIONS(description='Concuity\'s ID of the account. Column was expanded to 32 from 18.'),
  linked_pat_account_id BIGNUMERIC(38) OPTIONS(description='Concuity\'s ID of the account to which this account is linked to as the child of a parent-child relationship. Column was expanded to 32 from 18.'),
  patient_last_name STRING OPTIONS(description='The last name of the patient.'),
  patient_first_name STRING OPTIONS(description='The first name of the patient.'),
  patient_middle_name STRING OPTIONS(description='The middle name of the patient.'),
  patient_name_suffix_text STRING OPTIONS(description='The suffix of the patient\'s name indicating the generation. Examples: I, II, III, IV, Jr., Sr.'),
  social_security_num STRING OPTIONS(description='Social security number of the patient.'),
  medical_record_num STRING OPTIONS(description='Identifier of the patient\'s medical record (intended to be unique to the person).'),
  admission_date_time DATETIME OPTIONS(description='The earliest statement from date appearing on the account\'s claims.'),
  discharge_date_time DATETIME OPTIONS(description='The earliest statement from date appearing on the account\'s claims.'),
  patient_birth_date DATE OPTIONS(description='The date of birth of the patient.'),
  patient_death_date DATE OPTIONS(description='The date of death of the patient.'),
  patient_noa_date DATE OPTIONS(description='Patient notice of admission date'),
  admission_source_code STRING OPTIONS(description='UB standard code indicating the source of the admission. Data normally found on the UB, form locator 20.'),
  admission_type_code STRING OPTIONS(description='UB standard code indicating the type of the admission. Data normally found on the UB, form locator 19.'),
  financial_class_code STRING OPTIONS(description='Code indicating the financial classification of the account.'),
  gender_code STRING OPTIONS(description='Identifier of the patient\'s gender.'),
  hipps_code STRING OPTIONS(description='Hospital Insurance Prospective Payment System rate code. The value is meant to contain the Case Mix Group  (CMG) number prefixed with the tier payment level code.'),
  discharge_status_code INT64 OPTIONS(description='UB standard code indicating the status of the patient as of the service_date_end. Data normally found on the UB, form locator 22.'),
  billing_status_code STRING OPTIONS(description='Code indicating the current billing status of the account. Typical values: A - Active/Inhouse; D - Discharged, not billed; B - Billed.'),
  special_bill_ind STRING OPTIONS(description='Implementation-defined data'),
  diag_code_admit STRING OPTIONS(description='Implementation-defined data'),
  cancel_bill_ind STRING OPTIONS(description='Implementation-defined data'),
  ca_extract_stop_ind STRING OPTIONS(description='Is Contractual Adjustment Extract Stopped|Flag to identify whether parameter is CONCUITY_30|0 or 1'),
  reassignable_ind STRING OPTIONS(description='is reassignable| Flag whether account is reassignable by assignment rule| 0 or 1'),
  service_code STRING OPTIONS(description='Implementation-defined data'),
  final_bill_date DATE OPTIONS(description='Implementation-defined data'),
  ar_bill_thru_date DATE OPTIONS(description='Implementation-defined data'),
  visit_cnt INT64 OPTIONS(description='Implementation-defined data'),
  patient_type_code STRING OPTIONS(description='Implementation-defined data'),
  cc_patient_type_id NUMERIC(29) OPTIONS(description='Concuity\'s ID for patient type'),
  account_status_code STRING OPTIONS(description='Implementation-defined data'),
  marital_status_code STRING OPTIONS(description='Implementation-defined data'),
  length_of_stay_days_num NUMERIC(32, 3) OPTIONS(description='Implementation-defined data'),
  drg_code STRING OPTIONS(description='The diagnostic related group (computed by customer, using Diagnoses and Procedures).'),
  drg_type STRING OPTIONS(description='Code identifying the DRG coding methodology (i.e. DRG, APDRG).'),
  drg_version NUMERIC(29) OPTIONS(description='The diagnostic related group version (computed by customer, using Diagnoses and Procedures).'),
  cc_regroup_drg_code STRING OPTIONS(description='Account Regrouped DRG | Stores DRG value related to the payer using DRG Regrouper Software (Account Level).'),
  cc_regroup_drg_type STRING OPTIONS(description='Account Regrouped DRG Type | Stores DRG Type value related to the payer using DRG Regrouper Software(Account Level).'),
  cc_regroup_drg_version NUMERIC(29) OPTIONS(description='Account Regrouped DRG Version | Stores DRG Regrouped Version value related to the Payer(Account Level).'),
  cc_account_archive_ind STRING OPTIONS(description='Is archived|Flag denotes if the account is archived.'),
  birth_weight_amt INT64 OPTIONS(description='Implementation-defined data'),
  pa_total_account_balance_amt NUMERIC(32, 3) OPTIONS(description='Implementation-defined data'),
  total_charge_amt NUMERIC(32, 3) OPTIONS(description='The sum of charges for the account.'),
  total_expected_reimb_amt NUMERIC(32, 3) OPTIONS(description='The sum of expected payment calculations.'),
  total_patient_liability_amt NUMERIC(32, 3) OPTIONS(description='The sum of patient\'s responbibility. Usually includes copayments, coinsurance, deductibles, and patient convenience items.'),
  total_payment_amt NUMERIC(32, 3) OPTIONS(description='The sum of payments and unverified collections for the account.'),
  total_patient_payment_amt NUMERIC(32, 3) OPTIONS(description='Total Patient Payment'),
  total_adjustment_amt NUMERIC(32, 3) OPTIONS(description='Total Patient Adjustment'),
  total_billed_charges_amt NUMERIC(32, 3) OPTIONS(description='Billed Charges|Billed charges is Account Total Charge minus the unbilled charges from the account charge lines.|'),
  financial_period_id NUMERIC(29) OPTIONS(description='MOn accounting period id|Account period identifier|References mon_accounting_period.id'),
  ipf_interrupted_stay_day INT64 OPTIONS(description='IPF_PER_DIEM_BEGIN_DAY|Starting day offset for IPF per diem days|'),
  pa_archive_ind STRING OPTIONS(description='Implementation-defined data'),
  pa_purge_ind STRING OPTIONS(description='Implementation-defined data'),
  updated_login_userid STRING OPTIONS(description='Identifier of the user last modifying the record via the UI.'),
  last_calc_date_time DATETIME OPTIONS(description='The most recent date and time the calculation engine was updated with total account information - charge detail, procedures, diagnosis, etc. If null, indicates the information needs to be resent.'),
  ins_maint_date DATE OPTIONS(description='Implementation-defined data'),
  icd10_drg_code STRING OPTIONS(description='The diagnostic related group (computed by customer, using Diagnoses and Procedures) for the International Classification of Diseases Version 10.'),
  icd10_drg_version_id NUMERIC(29) OPTIONS(description='The diagnostic related group version identifier (computed by customer, using Diagnoses and Procedures) for the International Classification of Diseases Version 10.'),
  icd10_drg_severity_level_code STRING OPTIONS(description='Severity Level Code of the diagnostic related group (computed by customer, using Diagnoses and Procedures) for the International Classification of Diseases Version 10.'),
  pa_icd_version_desc STRING OPTIONS(description='Descriptive text of the International Classification of Diseases Version for the patient\'s account information.'),
  create_date_time DATETIME OPTIONS(description='Date of record creation.'),
  update_date_time DATETIME OPTIONS(description='Date of last record update.'),
  archive_state_ind STRING OPTIONS(description='This column serves to identify if an account is in the archived partition or not'),
  dw_last_update_date_time DATETIME OPTIONS(description='Date & Timestamp of last record update in EDWRA.\r['),
  source_system_code STRING OPTIONS(description='Code assigned to Concuity App in EDWRA.\r[F:1-A]')
)
CLUSTER BY patient_dw_id
OPTIONS(
  description='A patient visiting for healthcare services. This can be a single encounter - single claim, a multi-visit - multi claim grouping.'
);
