-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_account_payor.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_account_payor
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Used to distinguish one PATIENT in the Datawarehouse from another.\r'),
  payor_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Used to distinguish one PAYOR in the Datawarehouse from another.\r'),
  iplan_order_num INT64 NOT NULL OPTIONS(description='Indicates the precedence of payment liability for insurance plans associated with a patient:  primary, secondary, etc.'),
  company_code STRING NOT NULL OPTIONS(description='Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.\r'),
  coid STRING NOT NULL OPTIONS(description='The company identifier which uniquely identifies a facility to corporate and all other facilities.\r'),
  unit_num STRING OPTIONS(description='4-digit corporate assigned number which uniquely identifies each facility.  [F:4/N]'),
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description='Unique identification number assigned by the facility to a patient at admit/registration time.'),
  iplan_id INT64 OPTIONS(description='Unique Identification number for the Insurance Plan'),
  employer_name STRING OPTIONS(description='Employer Name'),
  insurance_group_name STRING OPTIONS(description='Insurance group name'),
  insurance_group_num_cd STRING OPTIONS(description='Insurance group num'),
  insured_name STRING OPTIONS(description='Insured name'),
  insured_gender_cd STRING OPTIONS(description='Insured Gender'),
  insured_birth_date DATE OPTIONS(description='Insured Date of Birth'),
  payor_identification_num_cd STRING OPTIONS(description='Insurance company identification number for insured'),
  authorization_cd STRING OPTIONS(description='Insurance company authorization code'),
  billing_name STRING OPTIONS(description='Insurance company\'s name.\r'),
  billed_date DATE OPTIONS(description='The date of the last billing to the payer.'),
  billing_address_1 STRING OPTIONS(description='Insurance company\'s billing address line 1.\r'),
  billing_address_2 STRING OPTIONS(description='Insurance company\'s billing address line 2.\r'),
  billing_city_name STRING OPTIONS(description='Insurance company\'s billing address city.\r'),
  billing_state_code STRING OPTIONS(description='Insurance company\'s billing address state.\r'),
  billing_zip_code STRING OPTIONS(description='The Zip Code is the 5 digit location identifier associated with the address for a person or organization.  The zip code of an address generally designates a Postal area or region.'),
  billing_phone_num_cd STRING OPTIONS(description='Insurance company\'s billing phone number.\r'),
  billing_contact_person_name STRING OPTIONS(description='Name of contact for insurance company\'s billing office.\r'),
  billing_contact_email_name STRING OPTIONS(description='Electronic mail address for the contact\r'),
  relation_to_insured_pat_cd STRING OPTIONS(description='A code indicating the relationship of the patient to the insured individual. This information can be found in UB form locator 59.\r'),
  drg_version STRING OPTIONS(description='Version of the DRG codes'),
  pa_denial_date DATE OPTIONS(description='Denial Date from Patient Accounting'),
  first_denial_date DATE OPTIONS(description='First chronological occurrence of a date accompanying a user-assignable external appeal code that is sent over in the file 34 data file record\r'),
  interest_stop_date DATE OPTIONS(description='Date until which the interest is to be calculated\r'),
  work_queue_name STRING OPTIONS(description='Name of the work queue in Concuity'),
  rate_schedule_name STRING OPTIONS(description='Name of the rate schedule, against which the account payer was calculated.\r'),
  calc_date DATE OPTIONS(description='Date of the last calculation of expected reimbursement.\r'),
  calc_num INT64 OPTIONS(description='Sequential order of the current calculation of expected payment.\r'),
  calc_result_ind STRING OPTIONS(description='Indicates account latest calc is success (1) or error (0)\r'),
  calc_base_choice_resolved_ind STRING OPTIONS(description='Stores the resolved calc base choice for the account payor record. Valid values are:G,L,and B.'),
  calc_lock_ind STRING OPTIONS(description='Indicates if the calculation information (calc details and total expected, current expected fields) is locked and cannot be overridden.\r'),
  pa_autm_post_ind STRING OPTIONS(description='Indicator for PA Auto Post'),
  apc_group_ind STRING OPTIONS(description='Ambulatory Payment Classification Group Indicator'),
  eligible_ind STRING OPTIONS(description='Indicates if the payer is active and available for functionality on the account.\r'),
  account_calc_situation_ind STRING OPTIONS(description='Account Calculation Situation Indicator'),
  allow_contract_code_change_ind STRING OPTIONS(description='Indicates if the contract code value can be assigned or reassigned via payer-to-contract mapping. If not, most likely indicates a manual override.\r'),
  change_claim_trigger_ind STRING OPTIONS(description='Change Claim Trigger Indicator'),
  manual_trigger_ind STRING OPTIONS(description='Denotes account payor marked for Calc Tonight'),
  life_check_eligible_ind STRING OPTIONS(description='Indicator flag for check eligibility for lifecycle check..\r'),
  pa_financial_class_code STRING OPTIONS(description='Financial Class Originated by Patient Accounting'),
  bill_reason_code STRING OPTIONS(description='Reason Code assigned for billing purposes'),
  external_appeal_code STRING OPTIONS(description='External Appeal Code sent by the client in interface file 34. This code is always stored in the database, and is used to update the appeal code of any open appeal sequence if one exists at the time of the data load.\r'),
  total_exp_payment_amt NUMERIC(32, 3) OPTIONS(description='The sum of the calcuation details as dictated by the contractual agreement between the provider and the payer organization.\r'),
  total_payment_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The sum of payments made by the payer.\r'),
  total_denial_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Total Denials\r'),
  total_pat_responsibility_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The sum of patient\'s responbibility for the payer. Usually includes copayments, coinsurance, deductibles, and patient convenience items.\r'),
  est_pat_responsibility_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The value of patient responsibilty sent in File 34 data load\r'),
  actual_pat_responsibility_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The value of patient responsibilty sent in the EOB\r'),
  total_exp_contractual_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The expected adjustment amount based on the contractual relationship. Calculated field: total charges less total expected payment for the payer.\r'),
  total_adjustment_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Total value of adjustments (not including payments) made.\r'),
  total_variance_adjustment_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The total variance adjustment amount entered by the user while creating a new variance transaction.\r'),
  current_exp_payment_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The current value of the expected payment. Can be different from total_expected_payment by user input via UI.\r'),
  current_exp_contractual_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The current value of the expected contractual allowance. Can be different from expected_contractual by user input via UI.\r'),
  prof_covered_charge_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Professional Covered Charge Payment\r'),
  prof_exp_payment_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Professional Expected Payment\r'),
  pa_prof_part_b_charge_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Professional Part B Charge Amount from PA'),
  pa_blood_deductible_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Blood Deductible Amount from PA'),
  sqstrtn_reduction_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Amount Reduced for Sequestration'),
  pa_coinsurance_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Patient accounting coinsurance coming in from File 34\r'),
  autm_post_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Amount assigned for Auto Post'),
  coinsurance_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Coinsurance Amount'),
  copay_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The Co-Pay amount in which the patient is responsible'),
  deductible_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='The amount of the patients deductible for that payor'),
  covered_charge_instu_amt NUMERIC(32, 3) NOT NULL OPTIONS(description='Indicates the covered charges\r'),
  cmpt_method_choice_id NUMERIC(29) OPTIONS(description='Stores calc comparison method set at account_payer level\r'),
  calc_base_id NUMERIC(29) OPTIONS(description='Identifier assignment for the Calculation used'),
  calc_base_survivor_id BIGNUMERIC(38) OPTIONS(description='Stores the calculation base for the surviving calc record\r'),
  reason_id BIGNUMERIC(38) OPTIONS(description='ID of the current reason for mis-payment.\r'),
  account_payor_status_id BIGNUMERIC(38) OPTIONS(description='Status Identifier for the Account Payor'),
  appeal_id BIGNUMERIC(38) OPTIONS(description='Identifier for the Appeal record'),
  cers_profile_id BIGNUMERIC(38) OPTIONS(description='Rate Schedule Profile Indicator for Calculation'),
  capping_method_id BIGNUMERIC(38) OPTIONS(description='Indicates capping method\r'),
  cers_term_id BIGNUMERIC(38) OPTIONS(description='Rate Schedule Term Identifier'),
  project_id BIGNUMERIC(38) OPTIONS(description='Identifier for Assigned Project'),
  account_payor_id BIGNUMERIC(38) OPTIONS(description='Identifier of the contractual terms the account payor\'s reimbursement terms are dictated by.'),
  creation_date DATE OPTIONS(description='Date record was created'),
  update_date DATE OPTIONS(description='Date record was updated'),
  prepay_mgd_care_sw INT64 OPTIONS(description='PrePayment Managed Care (PPMC) flag in Artiva will mark the account as PrePayment Review "1".'),
  ip_provider_num STRING OPTIONS(description='The financially responsible party identifier of the provider for Inpatients. '),
  op_provider_num STRING OPTIONS(description='The financially responsible party identifier of the provider for Outpatients.'),
  payer_type_code STRING OPTIONS(description='Identify episodic/non-episodic IPLANs for Home Health and Hospice payers'),
  source_system_code STRING OPTIONS(description='Source Origination Indicator'),
  dw_last_update_date_time DATETIME OPTIONS(description='Last time record was updated in the Data Warehouse from the source'),
  billing_fax_num STRING OPTIONS(description='Insurance company\'s billing fax number.\r')
)
CLUSTER BY patient_dw_id, payor_dw_id, iplan_order_num
OPTIONS(
  description='Contains all account payer records related to work queue.'
);
