-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_discrepancy.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_discrepancy
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Used to distinguish one PATIENT in the Datawarehouse from another.'),
  payor_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Used to distinguish one PAYOR in the Datawarehouse from another.'),
  iplan_order_num INT64 NOT NULL OPTIONS(description='Indicates the precedence of payment liability for insurance plans associated with a patient:  primary, secondary, etc.'),
  extract_date_time DATETIME NOT NULL OPTIONS(description='Timestamp when the Data was extracted from the Concuity Production Source'),
  ar_amt NUMERIC(32, 3) OPTIONS(description='Payor Due Amount'),
  actv_desc STRING OPTIONS(description='Description of the most recent activit that is not complete'),
  actv_due_date DATE OPTIONS(description='Due date of the most recent activity that is not complete'),
  activity_kpi_name STRING OPTIONS(description='Severity Category (At Risk, Compliant, Operational Age)'),
  actv_owner_desc STRING OPTIONS(description='Owner of the most recent activit that is not complete'),
  actv_subject_desc STRING OPTIONS(description='Subject of the most recent activit that is not complete'),
  admit_source_cd STRING OPTIONS(description='UB standard code indicating the source of the admission. Data normally found on the UB, form locator 20.'),
  attending_physician_id NUMERIC(29) OPTIONS(description='Identifier of the Attending Physician'),
  attending_physician_name STRING OPTIONS(description='Name of the Attending Physician'),
  authorization_cd STRING OPTIONS(description='Insurance company authorization code'),
  billing_contact_name STRING OPTIONS(description='Name of contact for insurance company\'s billing office.'),
  billing_name STRING OPTIONS(description='Insurance company\'s name for billing purposes.'),
  billing_status_cd STRING OPTIONS(description='Code indicating the current billing status of the account. Typical values: A - Active/Inhouse; D - Discharged, not billed; B - Billed.'),
  calc_base_desc STRING OPTIONS(description='Calculation base description used for the surviving calc record.'),
  calc_date DATE OPTIONS(description='Date of the last calculation of expected reimbursement.'),
  cancel_bill_ind STRING OPTIONS(description='Indicator or a Bill that is cancelled'),
  cc_pat_type_cd STRING OPTIONS(description='Patient Type Code from Concuity'),
  coid STRING NOT NULL OPTIONS(description='The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  collection_amt NUMERIC(32, 3) OPTIONS(description='Amount received from a Payer'),
  collection_date DATE OPTIONS(description='Date the Collection Amount was received from a Payer'),
  company_code STRING NOT NULL OPTIONS(description='Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.'),
  comparison_method_desc STRING OPTIONS(description='Description of the Comparison Method used for Calculation'),
  credit_balance_age_desc STRING OPTIONS(description='Age Classification of the Credit Balance (<60 or >=60)'),
  credit_category_name STRING OPTIONS(description='Credit Classification (No Credit, With Credit)'),
  crt_placed_activity_date DATE OPTIONS(description='The activity date created in the claims reprocessing tool application.'),
  discharge_date DATE OPTIONS(description='Date the Patient was Discharged from Services at the Facility'),
  discrepancy_group_name STRING OPTIONS(description='Classification for the Discrepancy Grouping (Non-Financial, Underpayment, Overpayment)'),
  first_actv_create_date DATE OPTIONS(description='Date the first activity was generated on the account'),
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description='Unique identification number assigned by the facility to a patient at admit/registration time. '),
  iplan_id INT64 OPTIONS(description='Unique identification for the Insurance Plan'),
  insurance_provider_name STRING OPTIONS(description='Name of Insurance Plan'),
  last_actv_completion_age_num INT64 OPTIONS(description='Number of Days (Age) since the last activity on an account was completed '),
  last_actv_completion_date DATE OPTIONS(description='Max date an activity on the account was completed'),
  last_owner_change_date DATE OPTIONS(description='Max date the account had an owner change'),
  last_project_change_date DATE OPTIONS(description='Max date the account had a different project assigment'),
  last_reason_change_date DATE OPTIONS(description='Max date the account had a reason code change'),
  last_reason_change_date_2 DATE OPTIONS(description='Last reason change date for a given record place holder two.'),
  last_reason_change_date_3 DATE OPTIONS(description='Last reason change date for a given record place holder three.'),
  last_reason_change_date_4 DATE OPTIONS(description='Last reason change date for a given record place holder four.'),
  last_remit_received_date DATE OPTIONS(description='Most recent remittance received date'),
  last_status_change_date DATE OPTIONS(description='Max date the account had a status code change'),
  max_type_5_trans_date DATE OPTIONS(description='A maximum type five transaction date for a given record.'),
  model_issue_desc STRING OPTIONS(description='Description of the Identified Modeling Issue (Confirmed Modeling Issue, No Modeling Issue)'),
  monbot_acct_payer_id BIGNUMERIC(38) OPTIONS(description='The source Concuity monbot account payer id.'),
  non_fin_dcrp_age_num INT64 OPTIONS(description='Days since (Age) Non Financial Discrepancy'),
  non_fin_dcrp_date DATE OPTIONS(description='Lifecycle Date for a Non Financial Discrepancy'),
  overpayment_age_num INT64 OPTIONS(description='Days since (Age) overpayment date.'),
  overpayment_date DATE OPTIONS(description='Lifecycle Date for an Overpayment'),
  pa_acct_status_desc STRING OPTIONS(description='Account Status Description from PA'),
  pa_actual_los_num INT64 OPTIONS(description='Length of the visit from Patient Accounting'),
  pa_discharge_status_cd STRING OPTIONS(description='Discharge Status Code from PA'),
  pa_drg_cd STRING OPTIONS(description='DRG Code from PA'),
  pa_financial_class_num INT64 OPTIONS(description='Financial Class Originated by Patient Accounting'),
  pa_pat_type_desc STRING OPTIONS(description='Patient Type Description from PA'),
  pa_service_cd STRING OPTIONS(description='Service Code from PA'),
  pa_total_acct_bal_amt NUMERIC(32, 3) OPTIONS(description='Total Account Balance according to the information available from Patient Accounting'),
  pat_birth_date DATE OPTIONS(description='The date of birth of the patient.'),
  pat_name STRING OPTIONS(description='Concatonation of the last and first name of the patiient'),
  payor_category_name STRING OPTIONS(description='Category of Payor (Government, Managed_Care'),
  payor_due_amt NUMERIC(32, 3) OPTIONS(description='Total Denial Amount'),
  payor_financial_class_id NUMERIC(29) OPTIONS(description='Financial Class from the Payor\'s Perspective'),
  payor_group_name STRING OPTIONS(description='Name of the Payor Group'),
  payor_pat_cd STRING OPTIONS(description='Patient Code from the Payor\'s Perspective'),
  project_name STRING OPTIONS(description='Name of the Project assigned to the account'),
  rate_schedule_name STRING OPTIONS(description='Name of the rate schedule, against which the account payer was calculated.'),
  rate_schedule_eff_begin_date DATE OPTIONS(description='Date the specific rate schedule begins for the account payer for that period'),
  rate_schedule_eff_end_date DATE OPTIONS(description='Date the specific rate schedule ends for the account payer for that period'),
  reason_code STRING OPTIONS(description='Reason Code from Concuity'),
  reason_code_2 STRING OPTIONS(description='Reason code place holder two from Concuity.'),
  reason_code_3 STRING OPTIONS(description='Reason code place holder three from Concuity.'),
  reason_code_4 STRING OPTIONS(description='Reason code place holder four  from Concuity.'),
  remit_drg_code STRING OPTIONS(description='The diagnosis related group code associated with a given remittance record.'),
  schema_id INT64 OPTIONS(description='Identifier for concuity schema/instance, 1 stands for P1, 2 stands for CHP, 3 stands for P2'),
  sec_establishment_id NUMERIC(29) OPTIONS(description='The security establishment id for a given user.  This is used internally to the Concuity application for the security model.'),
  service_begin_date DATE OPTIONS(description='The date when a service began for a patient.'),
  ssc_name STRING OPTIONS(description='The name of a shared service.'),
  status_category_desc STRING OPTIONS(description='Status Category Description (Acitve, Closed)'),
  status_desc STRING OPTIONS(description='Status Description '),
  status_kpi_name STRING OPTIONS(description='Classification of KPI Status (Non-Financial, Compliant, At Risk, Operation, SOX)'),
  status_phase_desc STRING OPTIONS(description='Status Phase Description (Denial, Underpayment, Overpayment, Non-Financial)'),
  stratification_group_name STRING OPTIONS(description='Classification of Category for the Account'),
  total_billed_charge_amt NUMERIC(32, 3) OPTIONS(description='Total Expected Payment Amount'),
  total_charge_amt NUMERIC(32, 3) OPTIONS(description='Total Charge Amount'),
  total_denial_amt NUMERIC(32, 3) OPTIONS(description='Total Denials'),
  total_expected_adjustment_amt NUMERIC(32, 3) OPTIONS(description='Total value of expected adjustments.'),
  total_expected_payment_amt NUMERIC(32, 3) OPTIONS(description='The sum of the calcuation details as dictated by the contractual agreement between the provider and the payer organization.'),
  total_pat_resp_amt NUMERIC(32, 3) OPTIONS(description='The sum of patient\'s responbibility for the payer. Usually includes copayments, coinsurance, deductibles, and patient convenience items.'),
  total_pmt_amt NUMERIC(32, 3) OPTIONS(description='Count of Total Payment'),
  total_var_adjustment_amt NUMERIC(32, 3) OPTIONS(description='The total variance adjustment amount entered by the user while creating a new variance transaction.'),
  underpayment_age_num INT64 OPTIONS(description='Days since (Age) underpayment date.'),
  underpayment_date DATE OPTIONS(description='Lifecycle Date for an Underpayment'),
  unit_num STRING OPTIONS(description='The unit number assigned to a specific facility where services are provided to a patient.'),
  user_completed_actv_age_num INT64 OPTIONS(description='Days Since (Age) of a completed activity generated by a user (not system)'),
  user_completed_actv_date DATE OPTIONS(description='Max date of a completed activity generated by a user (not system)'),
  user_completed_actv_desc STRING OPTIONS(description='Description of the max completed activity generated by a user (not system)'),
  user_completed_actv_ownr_34_id STRING OPTIONS(description='Owner of the max completed activity generated by a user (not system)'),
  user_completed_actv_subj_desc STRING OPTIONS(description='Subject of the max completed activity generated by a user (not system)'),
  var_creation_age_num INT64 OPTIONS(description='Days since (Age) of the Variance'),
  var_creation_date DATE OPTIONS(description='Date a Variance was generated'),
  var_resolution_age_num INT64 OPTIONS(description='Days since (Age)  the variance was resolved'),
  var_resolution_date DATE OPTIONS(description='Date the Variance was resolved'),
  valid_over_pmt_actv_age_num INT64 OPTIONS(description='Activity Age of the Valid Overpayment'),
  valid_over_pmt_actv_date DATE OPTIONS(description='Activity Date of the Valid Overpayment'),
  valid_over_pmt_actv_desc STRING OPTIONS(description='Activity Description of the Valid Overpayment'),
  valid_over_pmt_actv_ownr_desc STRING OPTIONS(description='Activity Owner of the Valid Overpayment'),
  valid_over_pmt_actv_subj_desc STRING OPTIONS(description='Activity Subject Description of the Valid Overpayment'),
  valid_under_pmt_actv_age_num INT64 OPTIONS(description='Activity Age of the Valid Underpayment'),
  valid_under_pmt_actv_date DATE OPTIONS(description='Activity Date of the Valid Underpayment'),
  valid_under_pmt_actv_desc STRING OPTIONS(description='Activity Description of the Valid Underpayment'),
  valid_under_pmt_actv_ownr_id STRING OPTIONS(description='Activity Owner of the Valid Underpayment'),
  valid_under_pmt_actv_subj_desc STRING OPTIONS(description='Activity Subject Description of the Valid Underpayment'),
  validation_group_name STRING OPTIONS(description='Group Validation Category (Validated, Unvalidated, Un-Reason Coded)'),
  work_queue_name STRING OPTIONS(description='Name of the Work Queue the account is currently designated according to the business rules for the revenue / inventory state'),
  source_system_code STRING OPTIONS(description='Code for the Source System'),
  dw_last_update_date_time DATETIME OPTIONS(description='Date of refresh to the datawarehouse')
)
PARTITION BY DATE_TRUNC(extract_date_time, MONTH)
CLUSTER BY patient_dw_id, payor_dw_id, iplan_order_num
OPTIONS(
  description='This EDWRA table contains an inventory of current discrepancies identifed from the Concuity system.  Covers all active SSCs.'
);
