-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_denial_pbi16556.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_denial_pbi16556
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' Used to distinguish one PATIENT in the Datawarehouse from another.'),
  payor_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' Used to distinguish one PAYOR in the Datawarehouse from another.'),
  iplan_order_num INT64 NOT NULL OPTIONS(description=' Indicates the precedence of payment liability for insurance plans associated with a patient:  primary, secondary, etc.'),
  extract_date_time DATETIME NOT NULL OPTIONS(description=' Timestamp when the Data was extracted from the Concuity Production Source.'),
  max_appeal_num INT64 NOT NULL OPTIONS(description=' The number of a unique appeal.'),
  max_seq_num INT64 NOT NULL OPTIONS(description=' The sequence numbering system within each unique appeal.'),
  company_code STRING NOT NULL OPTIONS(description=' Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.'),
  coid STRING NOT NULL OPTIONS(description=' The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description=' Unique identification number assigned by the facility to a patient at admit/registration time.'),
  patient_name STRING OPTIONS(description=' Concatonation of the last and first name of the patiient.'),
  iplan_id INT64 OPTIONS(description=' Unique identification for the Insurance Plan'),
  patient_birth_date DATE OPTIONS(description=' The date of birth of the patient.'),
  insurance_provider_name STRING OPTIONS(description=' Name of Insurance Plan.'),
  payor_group_name STRING OPTIONS(description=' Name of the payor group.'),
  billing_name STRING,
  billing_contact_name STRING,
  authorization_code STRING OPTIONS(description=' Insurance company authorization code'),
  payor_patient_code STRING,
  pa_financial_class_num NUMERIC(29) OPTIONS(description=' Financial Class Number from Patient Accounting.'),
  payor_financial_class_num NUMERIC(29),
  major_payor_group_code STRING OPTIONS(description=' Code of the Major Payor Group'),
  billing_status_code STRING OPTIONS(description=' Code indicating the current billing status of the account. Typical values: A - Active/Inhouse; D - Discharged, not billed; B - Billed.'),
  pa_service_code STRING OPTIONS(description=' Service Code from PA'),
  pa_account_status_desc STRING OPTIONS(description=' Account Status Description from PA'),
  pa_discharge_status_code STRING OPTIONS(description=' Discharge Status Code from PA'),
  pa_patient_type_desc STRING OPTIONS(description=' Patient Type Description from PA'),
  cancel_bill_ind STRING OPTIONS(description=' Indicator or a Bill that is cancelled'),
  admit_source_code STRING OPTIONS(description=' UB standard code indicating the source of the admission. Data normally found on the UB, form locator 20.'),
  admit_type_ind STRING OPTIONS(description=' Indicates the Type of Admission'),
  pa_drg_code STRING OPTIONS(description=' DRG Code from PA'),
  pa_actual_los_cnt INT64 OPTIONS(description=' Length of Stay Day count  from PA'),
  attending_physician_id NUMERIC(29) OPTIONS(description=' Identifier of the Attending Physician'),
  attending_physician_name STRING OPTIONS(description=' Name of the Attending Physician'),
  service_begin_date DATE OPTIONS(description=' Date Patient Services Began'),
  discharge_date DATE OPTIONS(description=' Date the Patient was Discharged from Services at the Facility'),
  pa_denial_update_date DATE OPTIONS(description=' Date Denial was updated in PA'),
  cc_patient_type_code STRING OPTIONS(description=' Patient Type Code from Concuity'),
  rate_schedule_name STRING OPTIONS(description=' Name of the rate schedule, against which the account payer was calculated. Date the specific rate schedule begins for the account payer for that period.  Date the specific rate schedule ends for the account payer for that period.'),
  rate_schedule_eff_begin_date DATE OPTIONS(description=' Date the specific rate schedule begins for the account payer for that period.'),
  rate_schedule_eff_end_date DATE OPTIONS(description=' Date the specific rate schedule ends for the account payer for that period.'),
  work_queue_name STRING OPTIONS(description=' Name of the Work Queue the account is currently designated according to the business rules for the revenue / inventory state.'),
  comparison_method_desc STRING OPTIONS(description=' Description of the Comparison Method used for Calculation'),
  project_name STRING OPTIONS(description=' Name of the Project assigned to the account'),
  accounting_period_desc STRING OPTIONS(description=' Description of the Accounting Period'),
  reason_code STRING OPTIONS(description=' Reason Code from Concuity'),
  status_desc STRING OPTIONS(description=' Status Description from Concuity'),
  status_category_desc STRING OPTIONS(description=' Status Category Description from Concuity (Active, Closed)'),
  status_phase_desc STRING OPTIONS(description=' Status Phase Description from Concity (Denial, Underpayment, Overpayment, Non-Financial)'),
  calc_date DATE OPTIONS(description=' Date of the last calculation of expected reimbursement.'),
  total_charge_amt NUMERIC(32, 3) OPTIONS(description=' Total Charge Amount'),
  total_billed_charge_amt NUMERIC(32, 3) OPTIONS(description=' Total Billed Charge Amount'),
  covered_charge_amt NUMERIC(32, 3) OPTIONS(description=' Covered Charge Amount'),
  total_expected_payment_amt NUMERIC(32, 3) OPTIONS(description=' The sum of the calcuation details as dictated by the contractual agreement between the provider and the payer organization.\r'),
  total_expected_adjustment_amt NUMERIC(32, 3) OPTIONS(description=' Total value of expected adjustments'),
  total_pat_resp_actual_amt NUMERIC(32, 3),
  total_var_adjustment_amt NUMERIC(32, 3) OPTIONS(description=' The total variance adjustment amount entered by the user while creating a new variance transaction.'),
  total_payment_amt NUMERIC(32, 3) OPTIONS(description=' Total Payment Amount'),
  total_denial_amt NUMERIC(32, 3) OPTIONS(description=' Total Denial Amount'),
  appeal_orig_amt NUMERIC(32, 3) OPTIONS(description=' Appeal Origination Amount'),
  current_appeal_amt NUMERIC(32, 3) OPTIONS(description=' Current Appeal Amount'),
  current_appeal_balance_amt NUMERIC(32, 3) OPTIONS(description=' Current Appeal Balance Amount'),
  payor_due_amt NUMERIC(32, 3) OPTIONS(description=' Payor Due Amount'),
  pa_account_total_bal_amt NUMERIC(32, 3) OPTIONS(description=' Total Account Balance Amount from PA'),
  ar_amt NUMERIC(32, 3) OPTIONS(description=' Accounts Receivable Amount'),
  category_to_date_amt NUMERIC(32, 3) OPTIONS(description=' Amount Total to Current Date'),
  net_denial_write_off_amt NUMERIC(32, 3) OPTIONS(description=' Cash Adjustments made on the account'),
  appeal_seq_create_date DATE OPTIONS(description=' Date the Appeal Sequence was created'),
  appeal_seq_deadline_date DATE OPTIONS(description=' Deadline of the Appeal Sequence'),
  appeal_close_date DATE OPTIONS(description=' Close Date of the Appeal'),
  appeal_seq_creator_34_id STRING OPTIONS(description=' User ID of Appeal Creator'),
  appeal_owner_34_id STRING OPTIONS(description=' User ID of the Appeal Owner'),
  appeal_modifier_34_id STRING OPTIONS(description=' User ID of the Appeal Modifier'),
  disp_code STRING OPTIONS(description=' Disposition Code'),
  web_disp_code STRING OPTIONS(description=' Web Disposition Code'),
  disp_desc STRING OPTIONS(description=' Description of the Disposition Code'),
  root_code STRING OPTIONS(description=' Identifier of the Root Cause Code'),
  root_cause_desc STRING OPTIONS(description=' Description of the Root Cause Code'),
  root_cause_dtl_desc STRING OPTIONS(description=' Comments for the Root Cause Code'),
  external_appeal_code STRING OPTIONS(description=' Classification of the Appeal Code'),
  first_denial_date DATE OPTIONS(description=' Date of the initial Denial'),
  denial_age_num INT64 OPTIONS(description=' Age of the Denail from the initial date'),
  first_actv_create_date DATE OPTIONS(description=' Date the first activity was generated on the account.'),
  last_actv_completion_date DATE OPTIONS(description=' Max date an activity on the account was completed.'),
  last_actv_completion_age_num INT64 OPTIONS(description=' Number of Days (Age) since the last activity on an account was completed .'),
  last_user_act_create_age_num INT64 OPTIONS(description=' Age of the last user activity'),
  last_reason_change_date DATE OPTIONS(description=' Max date the account had a reason code change.'),
  last_status_change_date DATE OPTIONS(description=' Max date the account had a status code change.'),
  last_project_change_date DATE OPTIONS(description=' Max date the account had a different project assigment.'),
  last_owner_change_date DATE OPTIONS(description=' Max date the account had an owner change.'),
  appeal_create_date DATE OPTIONS(description=' Date the Appeal was created'),
  actv_due_date DATE OPTIONS(description=' Due Date of the last open activity'),
  actv_desc STRING OPTIONS(description=' Description of the last open activity'),
  actv_subject_title_desc STRING OPTIONS(description=' Subject Title Description of the last open activity'),
  actv_owner_name STRING OPTIONS(description=' Owner Name of the last open activity'),
  appeal_code STRING OPTIONS(description=' Internal Appeal Code Classification'),
  appeal_desc STRING OPTIONS(description=' Internal Appeal Code Description'),
  appeal_sent_actv_ownr_34_id STRING OPTIONS(description=' Activity owner of the sent appeal'),
  appeal_sent_actv_date DATE OPTIONS(description=' Activity Date for the sent appeal'),
  appeal_sent_actv_age_num INT64 OPTIONS(description=' Age of the activity for the sent appeal'),
  appeal_sent_actv_subject_desc STRING OPTIONS(description=' Activity Subject Description for the Sent Appeal'),
  appeal_sent_actv_desc STRING OPTIONS(description=' Activity Description for the Sent Appeal'),
  stratification_group_name STRING OPTIONS(description=' Classification of Category for the Account'),
  status_kpi_name STRING OPTIONS(description=' Classification of KPI Status (Closed Appeal, Compliant, At Risk, Operational, Status Inconsistent with Denial)'),
  followup_kpi_name STRING OPTIONS(description=' Classificaiton of Followup (Compliant, At Risk)'),
  appeal_sent_kpi_name STRING OPTIONS(description=' Appeal Classification'),
  deadline_kpi_name STRING OPTIONS(description=' Appeal Deadline Classification'),
  payor_category_name STRING OPTIONS(description=' Category of Payor (Government, Managed_Care)'),
  write_off_amt NUMERIC(32, 3) OPTIONS(description=' Sum of transactions that are Type A (adjustment) with a category of Cash Adjustment or Contractual Adjustment Allowance'),
  cash_adjustment_amt NUMERIC(32, 3) OPTIONS(description=' Sum of transactions that are Type A (adjustment )with a category of Cash Adjustment'),
  vendor_code STRING OPTIONS(description=' The unique alphanumeric code assigned to each vendor.'),
  source_system_code STRING NOT NULL OPTIONS(description=' Code of the Source System'),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description=' Date of refresh to the datawarehouse.')
)
PARTITION BY DATE(extract_date_time)
CLUSTER BY patient_dw_id, payor_dw_id, iplan_order_num, max_appeal_num
OPTIONS(
  description='EDWRA table for holding all denial data at the SSC level.'
);
