-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_eor.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_eor
(
  company_code STRING NOT NULL OPTIONS(description=' Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.'),
  coid STRING NOT NULL OPTIONS(description=' The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' Used to distinguish one PAYOR from another.'),
  iplan_insurance_order_num INT64 NOT NULL OPTIONS(description=' Indicates the precedence of payment liability for insurance plans associated with a patient:  primary, secondary, etc.'),
  eor_log_date DATE NOT NULL OPTIONS(description=' First date (Month day and year) that this plan information became valid.'),
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL OPTIONS(description=' Sequence number assigned to a record in logging.'),
  eff_from_date DATE NOT NULL,
  unit_num STRING NOT NULL,
  pat_acct_num NUMERIC(29),
  iplan_id INT64 OPTIONS(description=' An identification code assigned to an insurance plan.  The first three digits identify the payor.  The last two uniquely identify a specific plan belonging to that payor.'),
  financial_class_code NUMERIC(29),
  final_bill_date DATE,
  ar_bill_thru_date DATE OPTIONS(description=' The ending service date of the period included on this bill'),
  ar_bill_drop_date DATE OPTIONS(description=' The month, day, and year the billing document was generated.'),
  contract_begin_date DATE OPTIONS(description=' Date that contract began.'),
  eor_transaction_date DATE OPTIONS(description=' Date that contract began.'),
  bill_reason_code STRING,
  eor_drg_code STRING OPTIONS(description=' Code which identifies groups of patient encounters or services for a prospective reimbursement methodology.  These groups generally consist of encounters or services that are similar in severity and/or cost of treatment.'),
  cc_drg_code STRING OPTIONS(description=' Code which identifies groups of patient encounters or services for a prospective reimbursement methodology.  These groups generally consist of encounters or services that are similar in severity and/or cost of treatment.'),
  cc_drg_weight NUMERIC(35, 6),
  eor_hipps_code STRING,
  cc_cmg_code STRING,
  cc_cmg_weight NUMERIC(35, 6),
  eor_covered_days_num INT64 OPTIONS(description=' The number of covered days expected per the explanation of reimbursement.'),
  eor_total_charge_amt NUMERIC(32, 3) OPTIONS(description=' The total dollars and cents of charges for services  that are reimbursed by the reimbursement method.'),
  expected_insurance_payment_amt NUMERIC(32, 3) OPTIONS(description=' The concuity expected payment due from the primary payor.'),
  pat_resp_non_covered_chg_amt NUMERIC(32, 3),
  total_actual_pat_resp_amt NUMERIC(32, 3) OPTIONS(description=' Actual Patient responsibility after deductions applied and total amount paid by insurance plan.'),
  eor_non_covered_charge_amt NUMERIC(32, 3),
  eor_cmptd_reimbursement_amt NUMERIC(32, 3) OPTIONS(description=' This is the reimbursement amount calculated by the Patient Accounting system based on the individual contract specifications.  COMP_REIMB from MLBEXP.'),
  eor_deductible_amt NUMERIC(32, 3) OPTIONS(description=' Deductible/coinsurance amount for which the patient is responsible, calculated for the patient and billing period and expected in explanation of reimbursement.'),
  eor_coinsurance_amt NUMERIC(32, 3),
  eor_copay_amt NUMERIC(32, 3) OPTIONS(description=' Deductible/coinsurance amount for which the patient is responsible, calculated for the patient and billing period and expected in explanation of reimbursement.'),
  eor_insurance_payment_amt NUMERIC(32, 3) OPTIONS(description=' The net payment due from the primary, secondary or tertiary payer.'),
  eor_contractual_allowance_amt NUMERIC(32, 3) OPTIONS(description=' The calculated amount of the account balance that is to be written off with a contractual adjustment per the terms of the contractual agreement.'),
  eor_cost_of_service_amt NUMERIC(32, 3),
  month_13_ind STRING OPTIONS(description=' Indicates that a change has been made in a prior year.'),
  outlier_code STRING,
  auto_post_amt NUMERIC(32, 3),
  auto_post_ind STRING,
  drg_table_id STRING,
  opps_ind STRING,
  inpatient_outpatient_ind STRING,
  visit_count INT64,
  eor_gross_reimbursement_amt NUMERIC(32, 3) OPTIONS(description=' The sum total of all of the individual components of the calculated payment per the Explanation of Reimbursement.\r'),
  eor_net_reimbursement_amt NUMERIC(32, 3) OPTIONS(description=' Gross Reimbursement + Gross Benefit Adjs 1 - 5(Deductible, copay for example) = Net Reimbursement'),
  eor_non_bill_charge_amt NUMERIC(32, 3),
  sqstrtn_red_amt NUMERIC(32, 3),
  model_name STRING,
  project_desc STRING OPTIONS(description=' Project Desc if assgned to the account. First three chars are disc reason code 3 if the account is discrepant - Sourced from Mon_Project'),
  eor_ipf_interrupted_day_stay NUMERIC(29),
  calc_success_ind STRING,
  latest_calc_ind STRING,
  interim_bill_ind STRING,
  financial_period_id NUMERIC(29),
  reason_id NUMERIC(29),
  calc_id BIGNUMERIC(38) OPTIONS(description=' Column was expanded from 18 to 32 positions.'),
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)
PARTITION BY DATE_TRUNC(eor_log_date, MONTH)
CLUSTER BY company_code, coid, patient_dw_id, payor_dw_id;
