-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_eor_calculation_service.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_eor_calculation_service
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  iplan_insurance_order_num INT64 NOT NULL,
  eor_log_date DATE NOT NULL,
  acct_payor_calc_service_id BIGNUMERIC(38) NOT NULL,
  calc_id BIGNUMERIC(38) NOT NULL,
  ce_service_id INT64 NOT NULL,
  service_date DATE,
  unit_num STRING,
  pat_acct_num NUMERIC(29),
  iplan_id INT64,
  service_qty INT64,
  expected_payment_amt NUMERIC(32, 3),
  subterm_expected_payment_amt NUMERIC(31, 2),
  service_charge_amt NUMERIC(32, 3),
  exclusion_charge_amt NUMERIC(32, 3),
  noncovered_charge_amt NUMERIC(32, 3),
  proc_code_type_desc STRING,
  proc_code STRING,
  modifier_1_code STRING,
  modifier_2_code STRING,
  revenue_code_desc STRING,
  calculation_method_desc STRING,
  rate_info_from_day_num INT64,
  rate_info_to_day_num INT64,
  rate_info_amt NUMERIC(32, 3),
  rate_info_service_desc STRING,
  gov_drg_payment_amt NUMERIC(35, 6),
  gov_ime_capital_drg_pmt_amt NUMERIC(35, 6),
  gov_operating_cost_outlier_amt NUMERIC(35, 6),
  gov_operating_fed_pmt_amt NUMERIC(35, 6),
  hipps_payment_amt NUMERIC(31, 2),
  ipf_pps_outlier_per_diem_amt NUMERIC(31, 2),
  ipf_pps_out_per_diem_addon_amt NUMERIC(31, 2),
  gov_scp_payment_amt NUMERIC(31, 2),
  ipf_cost_charge_ratio_amt NUMERIC(35, 6),
  ipf_fixed_loss_amt NUMERIC(35, 6),
  ipf_labor_share_amt NUMERIC(35, 6),
  ipf_labor_share_pct NUMERIC(35, 6),
  ipf_non_labor_share_amt NUMERIC(35, 6),
  ipf_teaching_adj_fctr_pct NUMERIC(35, 6),
  ipf_age_fctr_pct NUMERIC(35, 6),
  ipf_drg_adj_fctr_pct NUMERIC(35, 6),
  ipf_comorbidity_fctr_pct NUMERIC(35, 6),
  ipf_pps_facility_adj_fctr_pct NUMERIC(31, 2),
  ipf_pps_adj_fctr_pct NUMERIC(31, 2),
  ipf_pps_los_adj_fctr_pct NUMERIC(33, 4),
  gov_new_tech_add_on_amt NUMERIC(35, 6),
  gov_device_offset_red_amt NUMERIC(35, 6),
  gov_transfer_pct NUMERIC(35, 6),
  ipf_per_diem_day_num INT64,
  apc_composite_flg INT64,
  dsh_unadj_opr_add_on_amt NUMERIC(31, 2),
  dsh_uncmps_care_add_on_amt NUMERIC(31, 2),
  mdh_add_on_amt NUMERIC(31, 2),
  low_vol_add_on_amt NUMERIC(31, 2),
  readm_adj_amt NUMERIC(31, 2),
  val_based_adj_amt NUMERIC(31, 2),
  drg_fixed_loss_threshold_amt NUMERIC(31, 2),
  drg_marginal_cost_fctr_pct NUMERIC(31, 2),
  apc_outlier_pct NUMERIC(31, 2),
  opps_pct NUMERIC(31, 2),
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)
PARTITION BY DATE_TRUNC(eor_log_date, MONTH)
CLUSTER BY company_code, coid, patient_dw_id, payor_dw_id;
