-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_gr_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_gr_eom
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description='Unique identifier generated in EDW'),
  report_name STRING NOT NULL OPTIONS(description='Name of the government report'),
  period_end_date DATE NOT NULL OPTIONS(description='Reporting period date'),
  report_run_date_time DATETIME NOT NULL OPTIONS(description='Date and time when the report ran'),
  section_name STRING NOT NULL OPTIONS(description='Section name of the report'),
  reporting_period STRING NOT NULL OPTIONS(description='Financial reporting begin and end date'),
  company_code STRING NOT NULL OPTIONS(description='Company code'),
  coid STRING NOT NULL OPTIONS(description='The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  facility_name STRING OPTIONS(description='Name of the facility'),
  unit_num STRING OPTIONS(description='Unit Number'),
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description='Patient Account Number from Meditech'),
  patient_name STRING OPTIONS(description='Patient Name'),
  rate_schedule_name STRING OPTIONS(description='Contract rate schedule name'),
  section_month STRING OPTIONS(description='Section month on the report'),
  cost_report_year STRING OPTIONS(description='Financial report cost year'),
  account_status_code STRING OPTIONS(description='Account status'),
  auto_posted_flag STRING OPTIONS(description='Auto posted flag'),
  cmg_code STRING OPTIONS(description='Calculation case mix group code.'),
  drg_code STRING OPTIONS(description='Calculation diagnostic related group code'),
  ra_drg_code STRING OPTIONS(description='Remittance diagnostic related group code.'),
  cmg_weight_amt NUMERIC(33, 4) OPTIONS(description='Case mix group weight used during calculation.'),
  drg_weight_amt NUMERIC(33, 4) OPTIONS(description='Diagnostic related group weight'),
  prorated_drg_weight_amt NUMERIC(33, 4) OPTIONS(description='Prorated diagnostic related group weight'),
  exp_hipps_cmg_code STRING OPTIONS(description='Calculation health insurance prospective payment system case mix code'),
  ra_hipps_cmg_code STRING OPTIONS(description='Remittance health insurance prospective payment system case mix code'),
  var_drg_flag STRING OPTIONS(description='Flag for if calculation diagnostic related grouping and remittance diagnostic related grouping codes'),
  var_cmg_flag STRING OPTIONS(description='Flag for if calculation CMG and remit CMG codes'),
  discharge_admit_date DATE OPTIONS(description='Field to store admit or discharge date'),
  claim_submit_date DATE OPTIONS(description='Date when the claim was submitted'),
  ra_payment_date DATE OPTIONS(description='First remittance date or payment date'),
  covered_days_los_cnt INT64 OPTIONS(description='Covered days count or length of stay count'),
  days_billed_cnt INT64 OPTIONS(description='Number of days billed'),
  discharge_days_cnt INT64 OPTIONS(description='Count of days from discharge date'),
  ra_covered_days_cnt INT64 OPTIONS(description='Covered days count from remittance'),
  remit_cnt INT64 OPTIONS(description='Count of remittance rows.'),
  var_covered_days_cnt INT64 OPTIONS(description='Covered days variance'),
  account_balance_amt NUMERIC(32, 3) OPTIONS(description='Accrued Capital Subtotal amount '),
  accrued_capital_subtotal_amt NUMERIC(32, 3) OPTIONS(description='Accrued Capital Subtotal amount '),
  accrued_operating_subtotal_amt NUMERIC(32, 3) OPTIONS(description='Accrued Operating Subtotal amount '),
  accrued_payment_amt NUMERIC(32, 3) OPTIONS(description='Accrued Payment amount '),
  apc_charges_amt NUMERIC(32, 3) OPTIONS(description='Ambulatory Payment Classification Charges amount '),
  apc_payment_amt NUMERIC(32, 3) OPTIONS(description='Ambulatory Payment Classification payment amount '),
  drg_arithmetic_los_amt NUMERIC(32, 3) OPTIONS(description='Arithmetic length of stay amount'),
  capital_payment_subtotal_amt NUMERIC(32, 3) OPTIONS(description='Capital Payment Subtotal amount '),
  cmac_charge_amt NUMERIC(32, 3) OPTIONS(description='Maximum allowable charges for a Champus/Tricare account.'),
  cmac_payment_amt NUMERIC(32, 3) OPTIONS(description='Champus maximum allowable charge payment amount'),
  cmg_payment_amt NUMERIC(32, 3) OPTIONS(description='Case mix group payment amount'),
  coinsurance_deductible_amt NUMERIC(32, 3) OPTIONS(description='Coinsurance deductible amount '),
  computed_reimb_amt NUMERIC(32, 3) OPTIONS(description='Computed Reimb amount '),
  cost_outlier_payment_amt NUMERIC(32, 3) OPTIONS(description='Cost Outlier Payment amount '),
  covered_charges_amt NUMERIC(32, 3) OPTIONS(description='Covered Charges amount '),
  drg_payment_amt NUMERIC(32, 3) OPTIONS(description='Diagnostic related group payment amount'),
  ect_payment_amt NUMERIC(32, 3) OPTIONS(description='Electroconvulsive therapy payment amount for a psychiatric facility.'),
  education_payment_amt NUMERIC(32, 3) OPTIONS(description='Education Payment amount '),
  fee_based_payment_amt NUMERIC(32, 3) OPTIONS(description='Fee Based Payment amount '),
  idme_payment_amt NUMERIC(32, 3) OPTIONS(description='Payment amount for a facility using indirect medical education programs.'),
  lab_charge_amt NUMERIC(32, 3) OPTIONS(description='Charge related to a labratory related service.'),
  lab_payment_amt NUMERIC(32, 3) OPTIONS(description='Payment amount related to a labratory related service. '),
  lip_payment_amt NUMERIC(32, 3) OPTIONS(description='Payment amounts that pertain to low income patients.'),
  non_covered_charges_amt NUMERIC(32, 3) OPTIONS(description='Charges that are deemed not covered by insurance.'),
  operating_drg_payment_amt NUMERIC(32, 3) OPTIONS(description='Operating Diagnostic Related Group Payment Amount'),
  operating_dsh_amt NUMERIC(32, 3) OPTIONS(description='Operating Disproportionate Share Hospital Amount'),
  operating_outlier_amt NUMERIC(32, 3) OPTIONS(description='Operating Outlier amount '),
  operating_cost_outlier_amt NUMERIC(32, 3) OPTIONS(description='Operating Cost Outlier amount '),
  other_service_charge_amt NUMERIC(32, 3) OPTIONS(description='Other service charge amount '),
  other_service_payment_amt NUMERIC(32, 3) OPTIONS(description='Other service payment amount '),
  outlier_payment_amt NUMERIC(32, 3) OPTIONS(description='Outlier payment amount '),
  payment_adj_amt NUMERIC(32, 3) OPTIONS(description='Adjusted payment amount '),
  ra_coinsurance_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice coinsurance amount '),
  ra_contractual_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice contractual amount '),
  ra_covered_charge_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice covered charge amount '),
  ra_deductible_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice deductible amount '),
  ra_drg_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice diagnostic amount'),
  ra_idme_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice indirect medical education amount'),
  ra_lab_payment_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice labratory payment amount'),
  ra_operating_dsh_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice operating disproportionate share hospital amount'),
  ra_operating_idme_amt NUMERIC(32, 3) OPTIONS(description='Remittance advice operating indirect medical education amount'),
  ra_operating_outlier_amt NUMERIC(32, 3) OPTIONS(description='The operating outlier amount recieved from a remittance advice record.'),
  ra_outlier_amt NUMERIC(32, 3) OPTIONS(description='The outlier amount recieved from a remittance advice record.'),
  ra_therapy_payment_amt NUMERIC(32, 3) OPTIONS(description='The therapy payment amount recieved from a remittance advice record.'),
  ra_total_capital_amt NUMERIC(32, 3) OPTIONS(description='The total capital amount recieved from a remittance advice record.'),
  ra_total_payment_amt NUMERIC(32, 3) OPTIONS(description='The total payment amount recieved from a remittance advice record.'),
  replace_device_reduction_amt NUMERIC(32, 3) OPTIONS(description='Replace Device Reduction amount '),
  rug_payment_amt NUMERIC(32, 3) OPTIONS(description='Resource utilization group payment amount. '),
  sequestration_amt NUMERIC(32, 3) OPTIONS(description='Sequestration amount '),
  short_stay_outlier_payment_amt NUMERIC(32, 3) OPTIONS(description='Short Stay Outlier Payment amount '),
  tech_add_on_amt NUMERIC(32, 3) OPTIONS(description='Tech Add On amount variance'),
  tech_add_on_payment_amt NUMERIC(32, 3) OPTIONS(description='Tech Add On Payment amount '),
  therapy_charge_amt NUMERIC(32, 3) OPTIONS(description='Therapy related charges amount. '),
  therapy_payment_amt NUMERIC(32, 3) OPTIONS(description='Therapy related payment amount. '),
  total_charge_amt NUMERIC(32, 3) OPTIONS(description='Total charges amount for related services. '),
  total_expected_payment_amt NUMERIC(32, 3) OPTIONS(description='Total expected payment amount. '),
  total_opr_cptl_payment_amt NUMERIC(32, 3) OPTIONS(description='Total operating capital payment amount.'),
  total_payment_amt NUMERIC(32, 3) OPTIONS(description='Total payment amount recieved for services rendered. '),
  transfer_payment_amt NUMERIC(32, 3) OPTIONS(description='Transfer payment amount. '),
  var_coinsurance_amt NUMERIC(32, 3) OPTIONS(description='Coinsurance amount variance'),
  var_contractual_amt NUMERIC(32, 3) OPTIONS(description='Contractual amount variance'),
  var_covered_charges_amt NUMERIC(32, 3) OPTIONS(description='Covered Charges amount variance'),
  var_deductible_amt NUMERIC(32, 3) OPTIONS(description='Deductible amount variance'),
  var_imed_educ_amt NUMERIC(32, 3) OPTIONS(description='Indirect Medical Education amount variance'),
  var_lab_payment_amt NUMERIC(32, 3) OPTIONS(description='Lab Payment amount variance'),
  var_operating_dsh_amt NUMERIC(32, 3) OPTIONS(description='Variance Operating Disproportionate Share Hospital Amount'),
  var_operating_ime_amt NUMERIC(32, 3) OPTIONS(description='Variance Operating Indirect Medical Education Amount'),
  var_operating_outlier_amt NUMERIC(32, 3) OPTIONS(description='Variance Operating Outlier amount'),
  var_outlier_amt NUMERIC(32, 3) OPTIONS(description='Outlier amount variance'),
  var_therapy_payment_amt NUMERIC(32, 3) OPTIONS(description='Therapy Payment amount variance'),
  var_total_capital_amt NUMERIC(32, 3) OPTIONS(description='Total Capital amount variance'),
  var_total_payment_amt NUMERIC(32, 3) OPTIONS(description='Total Payment amount variance'),
  dw_last_update_date_time DATETIME OPTIONS(description='Record last update date and time'),
  source_system_code STRING OPTIONS(description='A one character column that identifies the source system for data.')
)
PARTITION BY DATE_TRUNC(period_end_date, MONTH)
CLUSTER BY patient_dw_id, report_name, report_run_date_time, section_name
OPTIONS(
  description='This table will contain government reimbursment departments reporting month end (2nd through 5th) data. BOBJ produced excel files are the source data for this table.'
);
