-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/cc_remittance.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.cc_remittance
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL OPTIONS(description=' The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' A system generated number used to uniquely identify a patient.'),
  payor_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' Used to distinguish one PAYOR from another.'),
  remittance_advice_num INT64 NOT NULL OPTIONS(description=' The unique identifier associated with a single remittance.'),
  ra_log_date DATE NOT NULL OPTIONS(description=' Date that entry was made in logging.'),
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL OPTIONS(description=' Sequence number assigned to a record in logging.'),
  remittance_header_id BIGNUMERIC(38) NOT NULL OPTIONS(description=' Expanded column from 18 to 32 positions.'),
  remittance_id BIGNUMERIC(38) NOT NULL OPTIONS(description=' Expanded column from 18 to 32 positions.'),
  unit_num STRING,
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description=' A unique number assigned by the hospital to the patient at time of registration.'),
  iplan_insurance_order_num INT64,
  iplan_id INT64 OPTIONS(description=' An identification code assigned to an insurance plan.  The first three digits identify the payor.  The last two uniquely identify a specific plan belonging to that payor.'),
  ra_ep_iplan_id INT64,
  ar_bill_thru_date DATE NOT NULL OPTIONS(description=' The ending service date of the period included on this bill'),
  ra_drg_code STRING OPTIONS(description=' Code identified on the remittance which identifies groups  of patient encounters or services for a prospective reimbursement methodology.  These groups generally consist of encounters or services that are similar in severity and/or cost of treatment.'),
  ra_drg_weight NUMERIC(34, 5),
  ra_hipps_code STRING,
  ra_covered_days_num INT64 OPTIONS(description=' The number of covered days paid per the remit.'),
  ra_visit_cnt INT64,
  ra_covered_days_visit_cnt INT64,
  outlier_ind STRING,
  ra_discharge_fraction_pct NUMERIC(33, 4),
  ra_reimbursement_rate_pct NUMERIC(33, 4),
  ra_non_replaced_blood_unit_qty NUMERIC(31, 2),
  ra_prescription_qty NUMERIC(31, 2),
  ra_total_charge_amt NUMERIC(32, 3) OPTIONS(description=' The total monetary amount of reimbursement remitted.'),
  ra_non_covered_charge_amt NUMERIC(32, 3),
  ra_net_billed_charge_amt NUMERIC(32, 3),
  ra_deductible_amt NUMERIC(32, 3) OPTIONS(description=' Deductible/coinsurance amount for which the patient is responsible, calculated by the payor for the patient and billing period and communicated on the remittance advice.'),
  ra_coinsurance_amt NUMERIC(32, 3),
  ra_net_benefit_amt NUMERIC(32, 3),
  ra_insurance_payment_amt NUMERIC(32, 3) OPTIONS(description=' The net payment received from the primary, secondary or tertiary payer.'),
  ra_patient_responsible_amt NUMERIC(32, 3),
  ra_patient_qualifier_code STRING,
  ra_claim_status_code INT64,
  ra_patient_status_code STRING,
  ra_claim_filing_ind_code STRING,
  ra_medicare_format_code STRING,
  ra_facility_type_code STRING,
  ra_claim_frequency_code STRING,
  ra_payer_claim_control_num STRING,
  ra_receive_date DATE NOT NULL OPTIONS(description=' The ending service date of the period included on this bill'),
  ra_service_start_date DATE,
  ra_service_end_date DATE,
  ra_coverage_expiration_date DATE,
  ra_payer_patient_id STRING,
  ra_payer_member_id STRING,
  ra_replaced_by_remit_id BIGNUMERIC(38),
  ra_source_type_id NUMERIC(29),
  active_ind STRING,
  dw_last_update_date_time DATETIME,
  source_system_code STRING NOT NULL OPTIONS(description=' A one character code indicating the specific source system from which the data originated.')
)
CLUSTER BY patient_dw_id;
