-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/ref_cc_cers_term.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.ref_cc_cers_term
(
  company_code STRING NOT NULL OPTIONS(description='Part of the primary key, identifies the company as HCA or non-HCA facility.'),
  coid STRING NOT NULL OPTIONS(description='The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  cers_term_id BIGNUMERIC(38) NOT NULL OPTIONS(description='Part of the primary key, identifies each row within EDWRA_STAGING.Cers_Term.'),
  cers_profile_id BIGNUMERIC(38) NOT NULL OPTIONS(description='Foregin key tha links Cers_Term record to the parent Cers_Profile.'),
  effective_date_method_id BIGNUMERIC(38) OPTIONS(description='The identifier of the method for calculating which calculation contract terms to apply to individual accounts. Currently, this is limited to admission- or discharge-based.'),
  cers_profile_comparison_id BIGNUMERIC(38) OPTIONS(description='Identifier of the calculation engine rate schedule to compare calculation amounts with.'),
  comparison_calc_method_id BIGNUMERIC(38) OPTIONS(description='Identifier of the method used for comparison calculations.'),
  ipf_transition_calc_method_id BIGNUMERIC(38) OPTIONS(description='Identifies if the record is associated with a psychiatric rehabilitaion facility.'),
  inpatient_reimb_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the inpatient method used within the grouping.'),
  outpatient_reimb_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the outpatient method used within the grouping.'),
  owner_user_id BIGNUMERIC(38) OPTIONS(description='Identifies the user marked as owner.'),
  asc_ranking_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the rank in ascending order.'),
  validated_by_user_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine rate schedule varification user.'),
  drg_calc_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the diagnostic related group method used for calculations.'),
  gov_capital_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the government capital method.'),
  ce_apc_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine ambulatory payment classification profile.'),
  status_id BIGNUMERIC(38) OPTIONS(description='Identifies the status for the calculation engine rate schedule term.'),
  ce_profile_fee_schedule_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine rate schedule profile fee schedule.'),
  cers_parent_term_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine rate schedule parent term.'),
  irf_reimb_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the inpatient rehab facility reimbursement method.'),
  ce_irf_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine inpatient rehabilitation facility profile.'),
  ce_ipf_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine inpatient psychiatric facility profile.'),
  drg_transfer_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the diagnosis related group transfer profile.'),
  snf_reimb_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the skilled nursing facility reimbursement method.'),
  cob_method_id BIGNUMERIC(38) OPTIONS(description='Identifies the coordination of benefits method.'),
  apc_code_source_id BIGNUMERIC(38) OPTIONS(description='Identifies the ambulatory payment classification code source.'),
  comparison_calc_level_id BIGNUMERIC(38) OPTIONS(description='Identifies the comparison calculation level.'),
  gov_newtech_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the government new technology profile.'),
  ce_coins_fs_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine coinsurance financial statement profile.'),
  ce_snf_profile_id BIGNUMERIC(38) OPTIONS(description='Identifies the calculation engine skilled nursing facility profile.'),
  ce_state_tax_profile_id BIGNUMERIC(38) OPTIONS(description='Identifier for State tax profile\r'),
  ce_hierarchy_profile_id BIGNUMERIC(38) OPTIONS(description='Hierarchy profile id\r'),
  inpatient_accrual_method_id BIGNUMERIC(38) OPTIONS(description='Indicates the accrual method id for inpatient\r'),
  outpatient_accrual_method_id BIGNUMERIC(38) OPTIONS(description='Indicates the accrual method id for outpatient\r'),
  ce_tri_er_profile_id BIGNUMERIC(38) OPTIONS(description='Tricare Emergency Room profile ID\r'),
  ce_tri_apc_profile_id BIGNUMERIC(38) OPTIONS(description='Identifier of the Tricare APC profile which applies to the calculation engine rate schedule \r'),
  ce_atp_profile_id BIGNUMERIC(38) OPTIONS(description='Indicates the ATP profile id\r'),
  ce_tri_drg_code_profile_id BIGNUMERIC(38) OPTIONS(description='Tricare DRG Code profile ID\r'),
  coins_calc_pct_sel_id BIGNUMERIC(38) OPTIONS(description='User selection of % value to be used for coinsurance fee schedule calculation. Refers preset_value.id for group coinsurance_calc_percent\r'),
  gov_ime_component_id BIGNUMERIC(38) OPTIONS(description='Government IME Component ID (preset values for IME Components dropdown)\r'),
  cst_share_calc_pct_sel_id BIGNUMERIC(38) OPTIONS(description='User selection of % value to be used for cost sharing calculation. Refers preset_value.id for group '),
  drg_profile_id BIGNUMERIC(38) OPTIONS(description='DRG Profile ID'),
  icd_version_desc STRING OPTIONS(description='Descriptive text of the International Classification of Diseases Version'),
  cob_capped_ind STRING OPTIONS(description='Indicates if the cob value is capped to $0.00.1=yes, 0=No\r'),
  model_ind STRING OPTIONS(description='Modeling Indicator'),
  validated_ind STRING OPTIONS(description='Validation Indicator'),
  generate_contractual_ind STRING OPTIONS(description='Indicator for whether the calculation routine will produce contractual allowances.\r'),
  generate_acct_calc_detail_ind STRING OPTIONS(description='Indicator for whether the caluclation routine produces calculation detail appearing in the CALC DETAIL tab for accounts.\r'),
  drg_breakout_transfer_ind STRING OPTIONS(description='Indicates if rates and services are to breakout transfer patients as a separate category.\r'),
  drg_breakout_expired_ind STRING OPTIONS(description='Indicates if rates and services are to breakout expired patients as a separate category.\r'),
  drg_breakout_ama_ind STRING OPTIONS(description='Indicates if rates and services are to breakout patients leaving against medical advice as a separate category'),
  gov_dsh_ime_cst_outlr_ind STRING OPTIONS(description='Indicates if rates and services are to breakout patients leaving against medical advice as a separate category'),
  gov_include_scp_ind STRING OPTIONS(description='GVT Include SCP\r'),
  ipf_inc_fsc_in_outlier_ind STRING OPTIONS(description='IPF Include FSC In Outlier\r'),
  ipf_inc_fsa_in_outlier_ind STRING OPTIONS(description='IPF Include FSA In Outlier\r'),
  xfer_drg_capped_std_rate_ind STRING OPTIONS(description='Is Transfer DRG Capped To Std Rate\r'),
  apc_exclude_outlier_ind STRING OPTIONS(description='Flag to indicate whether to exclude APC outlier calculation\r'),
  include_gaf_ind STRING OPTIONS(description='Include geographic adjustment factor\r'),
  irf_rural_facility_ind STRING OPTIONS(description='Indicates if IRF rural facility\r'),
  irf_teaching_facility_ind STRING OPTIONS(description='Indicates if IRF teaching facility or not\r'),
  tri_apc_sole_comm_hosp_ind STRING,
  apc_rural_sole_comm_hosp_ind STRING,
  gov_transfer_excluded_ind STRING,
  gov_outlier_excluded_ind STRING,
  gov_disregard_subterm_ind STRING,
  valuated_ind STRING,
  copay_ind STRING,
  pat_resp_used_for_cob_ind STRING,
  apc_rural_hosp_ind STRING,
  effective_begin_date DATE,
  effective_end_date DATE,
  validated_date_time DATETIME,
  cers_term_create_date DATE,
  cers_term_update_date DATE,
  drg_version NUMERIC(29),
  drg_type_code STRING,
  comparison_calc_modifier_amt NUMERIC(32, 3),
  gov_base_rate_amt NUMERIC(32, 3),
  gov_labor_rate_amt NUMERIC(32, 3),
  gov_wage_index_amt NUMERIC(32, 3),
  gov_nonlabor_index_amt NUMERIC(32, 3),
  gov_capital_federal_rate_amt NUMERIC(32, 3),
  gov_geographical_factor_qty NUMERIC(32, 3),
  gov_urban_add_on_factor_qty NUMERIC(32, 3),
  gov_cst_liv_addon_factor_qty NUMERIC(32, 3),
  gov_disp_share_oper_adj_amt NUMERIC(32, 3),
  gov_disp_share_capital_adj_amt NUMERIC(32, 3),
  gov_ind_med_edu_oper_adj_amt NUMERIC(32, 3),
  gov_ind_med_edu_cap_adj_amt NUMERIC(32, 3),
  gov_oper_cst_charge_ratio_qty NUMERIC(32, 3),
  gov_cap_cst_charge_ratio_qty NUMERIC(32, 3),
  gov_drg_threshold_adj_amt NUMERIC(32, 3),
  gov_labor_share_amt NUMERIC(32, 3),
  gov_disprpr_share_red_adj_amt NUMERIC(32, 3),
  gov_oper_cost_of_livng_adj_amt NUMERIC(32, 3),
  apc_federal_rate_amt NUMERIC(32, 3),
  apc_wage_index_amt NUMERIC(32, 3),
  apc_labor_percent_amt NUMERIC(32, 3),
  apc_cost_charge_ratio_amt NUMERIC(32, 3),
  apc_cost_threshold_amt NUMERIC(32, 3),
  apc_cost_outlier_percent_amt NUMERIC(32, 3),
  apc_pro_rata_adj_amt NUMERIC(32, 3),
  apc_coinsurance_limit_amt NUMERIC(32, 3),
  apc_deductible_amt NUMERIC(32, 3),
  gov_scp_rate_amt NUMERIC(32, 3),
  apc_fixed_threshold_amt NUMERIC(32, 3),
  ipf_labor_share_amt NUMERIC(32, 3),
  ipf_nonlabor_share_amt NUMERIC(32, 3),
  ipf_labor_share_percent_amt NUMERIC(32, 3),
  ipf_wage_index_amt NUMERIC(32, 3),
  ipf_teaching_adj_factor_amt NUMERIC(32, 3),
  ipf_cola_adj_factor_amt NUMERIC(32, 3),
  ipf_fixed_loss_amt NUMERIC(32, 3),
  ipf_cost_charge_ratio_amt NUMERIC(32, 3),
  ipf_tefra_amt NUMERIC(32, 3),
  ipf_pps_federal_percent_amt NUMERIC(32, 3),
  ipf_tefra_hosp_percent_amt NUMERIC(32, 3),
  gov_noscaasotc_adj_amt NUMERIC(32, 3),
  irf_std_pmt_conv_factor_amt NUMERIC(32, 3),
  irf_labor_share_amt NUMERIC(32, 3),
  irf_cbsa_wage_index_amt NUMERIC(32, 3),
  irf_lip_adj_amt NUMERIC(32, 3),
  irf_cost_to_charge_ratio_amt NUMERIC(32, 3),
  irf_adj_threshold_amt NUMERIC(32, 3),
  irf_teaching_adj_amt NUMERIC(32, 3),
  snf_cbsa_wage_index_amt NUMERIC(32, 3),
  snf_icd9_042_multiplier_amt NUMERIC(32, 3),
  xfer_add_los_qty NUMERIC(32, 3),
  inpatient_accrual_value_amt NUMERIC(32, 3),
  outpatient_accrual_value_amt NUMERIC(32, 3),
  apc_bilateral_disc_fract_amt NUMERIC(32, 3),
  apc_rural_sch_adj_amt NUMERIC(32, 3),
  apc_terminated_dc_fract_amt NUMERIC(32, 3),
  irf_outlier_percent_amt NUMERIC(32, 3),
  tri_asa_labor_rel_prtn_amt NUMERIC(32, 3),
  tri_asa_nonlabor_rel_prtn_amt NUMERIC(32, 3),
  tri_wage_index_amt NUMERIC(32, 3),
  tri_idme_adj_factor_amt NUMERIC(32, 3),
  tri_shrt_stay_mar_cst_fctr_amt NUMERIC(32, 3),
  tri_er_wage_index_amt NUMERIC(32, 3),
  tri_er_labor_portion_amt NUMERIC(32, 3),
  tri_er_nonlabor_portion_amt NUMERIC(32, 3),
  tri_er_cost_share_percent_amt NUMERIC(32, 3),
  tri_cost_to_chrg_ratio_amt NUMERIC(32, 3),
  tri_noscastic_amt NUMERIC(32, 3),
  tri_labor_share_percent_amt NUMERIC(32, 3),
  tri_nonlabor_share_percent_amt NUMERIC(32, 3),
  tri_apc_wage_index_amt NUMERIC(32, 3),
  tri_apc_cost_chrg_ratio_amt NUMERIC(32, 3),
  tri_apc_sch_adj_amt NUMERIC(32, 3),
  tri_neonate_factor_amt NUMERIC(32, 3),
  gov_subterm_outlier_pct_amt NUMERIC(32, 3),
  copay_amt NUMERIC(32, 3),
  gov_readm_adj_factor_amt NUMERIC(32, 3),
  gov_vbj_adj_factor_amt BIGNUMERIC(48, 10),
  dsh_uncmps_care_addon_amt NUMERIC(32, 3),
  implant_ccr_amt NUMERIC(33, 4) OPTIONS(description='Implant cost to charge ratio'),
  low_vol_adj_fctr_amt NUMERIC(35, 6) OPTIONS(description='A factor applied within the calculation of the Low Volume Add On Amount.'),
  mdh_amt NUMERIC(31, 2) OPTIONS(description='An amount that is applied within the calculation of the add on amount for a Medicare Dependent Hospital.  This amount is used in the case of regular or special pay transfers.'),
  irf_rural_adj_fctr_amt NUMERIC(35, 6) OPTIONS(description='A factor applied in the calculation of payment for services at an Inpatient Rehabilitation Facility that is located in a rural area.'),
  ipf_rural_adj_fctr_amt NUMERIC(35, 6) OPTIONS(description='A factor applied in the calculation of payment for services at an Inpatient Psychiatric Facility that is located in a rural area.'),
  calc_base_choice_set_by_usr_nm STRING,
  loa_profile_desc STRING OPTIONS(description='Leave of absence profile name and description'),
  comparison_calc_method_user_id BIGNUMERIC(38) OPTIONS(description='Identifier of the user that set the method used for comparison calculations.'),
  cers_term_activated_date_time DATETIME OPTIONS(description='Date and time of when the rate schedule contract term was activated'),
  cers_term_updated_by_user_id BIGNUMERIC(38) OPTIONS(description='Calculation Engine Rate Schedule Term row was updated by this user identification number'),
  source_system_code STRING OPTIONS(description='Source system code, Concuity uses a code of N.'),
  dw_last_update_date_time DATETIME OPTIONS(description='Last refresh update date and time for the record in the EDW.')
)
CLUSTER BY company_code, coid, cers_term_id
OPTIONS(
  description='Concuity\'s calculation engine rate schedule term.'
);
