-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra/ref_cc_cers_term_hld.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_core_dataset_name }}.ref_cc_cers_term_hld
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  cers_term_id NUMERIC(29) NOT NULL,
  cers_profile_id NUMERIC(29) NOT NULL,
  effective_date_method_id NUMERIC(29),
  cers_profile_comparison_id NUMERIC(29),
  comparison_calc_method_id NUMERIC(29),
  ipf_transition_calc_method_id NUMERIC(29),
  inpatient_reimb_method_id NUMERIC(29),
  outpatient_reimb_method_id NUMERIC(29),
  owner_user_id NUMERIC(29),
  asc_ranking_method_id NUMERIC(29),
  validated_by_user_id NUMERIC(29),
  drg_calc_method_id NUMERIC(29),
  gov_capital_method_id NUMERIC(29),
  ce_apc_profile_id NUMERIC(29),
  status_id NUMERIC(29),
  ce_profile_fee_schedule_id NUMERIC(29),
  cers_parent_term_id NUMERIC(29),
  irf_reimb_method_id NUMERIC(29),
  ce_irf_profile_id NUMERIC(29),
  ce_ipf_profile_id NUMERIC(29),
  drg_transfer_profile_id NUMERIC(29),
  snf_reimb_method_id NUMERIC(29),
  calc_comparison_method_id NUMERIC(29),
  cob_method_id NUMERIC(29),
  apc_code_source_id NUMERIC(29),
  comparison_calc_level_id NUMERIC(29),
  gov_newtech_profile_id NUMERIC(29),
  ce_coins_fs_profile_id NUMERIC(29),
  ce_snf_profile_id NUMERIC(29),
  ce_state_tax_profile_id NUMERIC(29),
  ce_hierarchy_profile_id NUMERIC(29),
  inpatient_accrual_method_id NUMERIC(29),
  outpatient_accrual_method_id NUMERIC(29),
  ce_tri_er_profile_id NUMERIC(29),
  ce_tri_apc_profile_id NUMERIC(29),
  ce_atp_profile_id NUMERIC(29),
  ce_tri_drg_code_profile_id NUMERIC(29),
  coins_calc_pct_sel_id NUMERIC(29),
  gov_ime_component_id NUMERIC(29),
  cst_share_calc_pct_sel_id NUMERIC(29),
  drg_profile_id NUMERIC(29),
  icd_version_id NUMERIC(29),
  cob_capped_ind STRING,
  model_ind STRING,
  validated_ind STRING,
  generate_contractual_ind STRING,
  generate_acct_calc_detail_ind STRING,
  drg_breakout_transfer_ind STRING,
  drg_breakout_expired_ind STRING,
  drg_breakout_ama_ind STRING,
  gov_dsh_ime_cst_outlr_ind STRING,
  gov_include_scp_ind STRING,
  ipf_inc_fsc_in_outlier_ind STRING,
  ipf_inc_fsa_in_outlier_ind STRING,
  xfer_drg_capped_std_rate_ind STRING,
  apc_exclude_outlier_ind STRING,
  include_gaf_ind STRING,
  irf_rural_facility_ind STRING,
  irf_teaching_facility_ind STRING,
  tri_apc_sole_comm_hosp_ind STRING,
  apc_rural_sole_comm_hosp_ind STRING,
  gov_transfer_excluded_ind STRING,
  gov_outlier_excluded_ind STRING,
  gov_disregard_subterm_ind STRING,
  valuated_ind STRING,
  copay_ind STRING,
  pat_resp_used_for_cob_ind STRING,
  apc_rural_hosp_ind STRING,
  effective_begin_date DATE,
  effective_end_date DATE,
  validated_date_time DATETIME,
  cers_term_create_date DATE,
  cers_term_update_date DATE,
  drg_version NUMERIC(29),
  drg_type_code STRING,
  comparison_calc_modifier_amt NUMERIC(32, 3),
  gov_base_rate_amt NUMERIC(32, 3),
  gov_labor_rate_amt NUMERIC(32, 3),
  gov_wage_index_amt NUMERIC(32, 3),
  gov_nonlabor_index_amt NUMERIC(32, 3),
  gov_capital_federal_rate_amt NUMERIC(32, 3),
  gov_geographical_factor_qty NUMERIC(32, 3),
  gov_urban_add_on_factor_qty NUMERIC(32, 3),
  gov_cst_liv_addon_factor_qty NUMERIC(32, 3),
  gov_disp_share_oper_adj_amt NUMERIC(32, 3),
  gov_disp_share_capital_adj_amt NUMERIC(32, 3),
  gov_ind_med_edu_oper_adj_amt NUMERIC(32, 3),
  gov_ind_med_edu_cap_adj_amt NUMERIC(32, 3),
  gov_oper_cst_charge_ratio_qty NUMERIC(32, 3),
  gov_cap_cst_charge_ratio_qty NUMERIC(32, 3),
  gov_drg_threshold_adj_amt NUMERIC(32, 3),
  gov_labor_share_amt NUMERIC(32, 3),
  gov_disprpr_share_red_adj_amt NUMERIC(32, 3),
  gov_oper_cost_of_livng_adj_amt NUMERIC(32, 3),
  apc_federal_rate_amt NUMERIC(32, 3),
  apc_wage_index_amt NUMERIC(32, 3),
  apc_labor_percent_amt NUMERIC(32, 3),
  apc_cost_charge_ratio_amt NUMERIC(32, 3),
  apc_cost_threshold_amt NUMERIC(32, 3),
  apc_cost_outlier_percent_amt NUMERIC(32, 3),
  apc_pro_rata_adj_amt NUMERIC(32, 3),
  apc_coinsurance_limit_amt NUMERIC(32, 3),
  apc_deductible_amt NUMERIC(32, 3),
  gov_scp_rate_amt NUMERIC(32, 3),
  apc_fixed_threshold_amt NUMERIC(32, 3),
  ipf_labor_share_amt NUMERIC(32, 3),
  ipf_nonlabor_share_amt NUMERIC(32, 3),
  ipf_labor_share_percent_amt NUMERIC(32, 3),
  ipf_wage_index_amt NUMERIC(32, 3),
  ipf_teaching_adj_factor_amt NUMERIC(32, 3),
  ipf_cola_adj_factor_amt NUMERIC(32, 3),
  ipf_fixed_loss_amt NUMERIC(32, 3),
  ipf_cost_charge_ratio_amt NUMERIC(32, 3),
  ipf_tefra_amt NUMERIC(32, 3),
  ipf_pps_federal_percent_amt NUMERIC(32, 3),
  ipf_tefra_hosp_percent_amt NUMERIC(32, 3),
  gov_noscaasotc_adj_amt NUMERIC(32, 3),
  irf_std_pmt_conv_factor_amt NUMERIC(32, 3),
  irf_labor_share_amt NUMERIC(32, 3),
  irf_cbsa_wage_index_amt NUMERIC(32, 3),
  irf_lip_adj_amt NUMERIC(32, 3),
  irf_cost_to_charge_ratio_amt NUMERIC(32, 3),
  irf_adj_threshold_amt NUMERIC(32, 3),
  irf_teaching_adj_amt NUMERIC(32, 3),
  snf_cbsa_wage_index_amt NUMERIC(32, 3),
  snf_icd9_042_multiplier_amt NUMERIC(32, 3),
  xfer_add_los_qty NUMERIC(32, 3),
  inpatient_accrual_value_amt NUMERIC(32, 3),
  outpatient_accrual_value_amt NUMERIC(32, 3),
  apc_bilateral_disc_fract_amt NUMERIC(32, 3),
  apc_rural_sch_adj_amt NUMERIC(32, 3),
  apc_terminated_dc_fract_amt NUMERIC(32, 3),
  irf_outlier_percent_amt NUMERIC(32, 3),
  tri_asa_labor_rel_prtn_amt NUMERIC(32, 3),
  tri_asa_nonlabor_rel_prtn_amt NUMERIC(32, 3),
  tri_wage_index_amt NUMERIC(32, 3),
  tri_idme_adj_factor_amt NUMERIC(32, 3),
  tri_shrt_stay_mar_cst_fctr_amt NUMERIC(32, 3),
  tri_er_wage_index_amt NUMERIC(32, 3),
  tri_er_labor_portion_amt NUMERIC(32, 3),
  tri_er_nonlabor_portion_amt NUMERIC(32, 3),
  tri_er_cost_share_percent_amt NUMERIC(32, 3),
  tri_cost_to_chrg_ratio_amt NUMERIC(32, 3),
  tri_noscastic_amt NUMERIC(32, 3),
  tri_labor_share_percent_amt NUMERIC(32, 3),
  tri_nonlabor_share_percent_amt NUMERIC(32, 3),
  tri_apc_wage_index_amt NUMERIC(32, 3),
  tri_apc_cost_chrg_ratio_amt NUMERIC(32, 3),
  tri_apc_sch_adj_amt NUMERIC(32, 3),
  tri_neonate_factor_amt NUMERIC(32, 3),
  gov_subterm_outlier_pct_amt NUMERIC(32, 3),
  copay_amt NUMERIC(32, 3),
  gov_readm_adj_factor_amt NUMERIC(32, 3),
  gov_vbj_adj_factor_amt NUMERIC(32, 3),
  dsh_uncmps_care_addon_amt NUMERIC(32, 3),
  calc_base_choice_set_by_usr_nm STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)
CLUSTER BY company_code, coid, cers_term_id;
