CREATE TABLE IF NOT EXISTS edwpsc_staging.`3m_factprofeenotbillable`
(
  profeenotbillable3mkey INT64 NOT NULL,
  cacaccountnumber STRING,
  visitnumber STRING,
  visittype STRING,
  facilityid STRING,
  location STRING,
  patientfirstname STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  admitdate DATETIME,
  dischargedate DATETIME,
  servicedatekey DATE,
  servicedatetime DATETIME,
  cacworklistname STRING,
  lookupkey STRING,
  codingstatus STRING,
  codingstatusdatetime DATETIME,
  comment STRING,
  docnotbillablereason STRING,
  coderid STRING,
  careprovider STRING,
  careproviderfirstname STRING,
  careproviderlastname STRING,
  careprovidermiddlename STRING,
  filename STRING,
  filedate DATE,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  coid STRING,
  practiceid STRING,
  dwlastupdatedatetime DATETIME
)
;