CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_rprtadjustmentrequests
(
  snapshotdate DATE,
  adjustmentrequestid INT64,
  adjustmentreqstatus STRING,
  claimnumber STRING,
  encounterid INT64,
  adjustmenttype STRING,
  adjustmentcode STRING,
  adjustmentdescription STRING,
  adjustmentreqdate DATE,
  adjustmentreqexportdate DATE,
  cptcode STRING,
  cptadjustmentamt NUMERIC(33, 4),
  claimadjustmentamt NUMERIC(33, 4),
  requestorid STRING,
  requestordept STRING,
  adjustmentrequsername STRING,
  level2apprdate DATE,
  level2appruserid STRING,
  level2approvername STRING,
  level3apprdate DATE,
  level3appruserid STRING,
  level3approvername STRING,
  level4apprdate DATE,
  level4appruserid STRING,
  level4approvername STRING,
  level5apprdate DATE,
  level5appruserid STRING,
  level5approvername STRING,
  level6apprdate DATE,
  level6appruserid STRING,
  level6approvername STRING,
  finalapprovallevel INT64,
  totaldaystoexport INT64,
  totaldaysto2ndlevel INT64,
  totaldaysto3rdlevel INT64,
  totaldaysto4thlevel INT64,
  totaldaysto5thlevel INT64,
  totaldaysto6thlevel INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;