CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpsprovider
(
  pspraddr STRING,
  psprbillfac STRING,
  psprcity STRING,
  psprclaimprefix STRING,
  psprcredentials STRING,
  psprdeano STRING,
  psprdob DATETIME,
  psprdoctortype STRING,
  psprfirstname STRING,
  psprfullname STRING,
  psprgrpnpi STRING,
  psprid STRING,
  psprinactive STRING,
  psprlastname STRING,
  psprmi STRING,
  psprnotificationnote STRING,
  psprnpi STRING,
  psprorgtype STRING,
  psprprimsvcloc STRING,
  psprprimsvclocadr STRING,
  psprprimsvcloccty STRING,
  psprprimsvclocst STRING,
  psprprimsvcloczip STRING,
  psprspecgrp STRING,
  psprspecialty STRING,
  psprspecialtycode STRING,
  psprst STRING,
  psprtaxid STRING,
  psprtaxonomycd STRING,
  psprupin STRING,
  psprzip STRING,
  psprreferphy STRING
)
;