CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpsccucoidmaster
(
  psccucoidkey NUMERIC(29),
  psccucoidcentstat STRING,
  psccucoidclsdvstdte DATE,
  psccucoidconsoldte DATE,
  psccucoiddiscontdte DATE,
  psccucoiddivision STRING,
  psccucoidenddtecom STRING,
  psccucoidgmecoid STRING,
  psccucoidgroup STRING,
  psccucoidgrpassign STRING,
  psccucoidlmtdsvcs STRING,
  psccucoidlob STRING,
  psccucoidmarket STRING,
  psccucoidname STRING,
  psccucoidnotes STRING,
  psccucoidnum STRING,
  psccucoidpkenviron STRING,
  psccucoidspecialty STRING,
  psccucoidstatus STRING,
  psccucoidsvcscdbyven STRING,
  psccucoidvendenddte DATE,
  psccucoidvendname STRING,
  psccucoidvendplcd STRING,
  psccucoidvendpupdte DATE,
  psccucoidvendsysplcd STRING,
  psccucoidvndassgndte DATE,
  psccucoidworkflow STRING,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;