CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_intradaydata
(
  refreshdate DATETIME NOT NULL,
  reporting_date DATE,
  workcategory STRING NOT NULL,
  sourcesystem STRING NOT NULL,
  pat_acct_num STRING NOT NULL,
  unit_num STRING NOT NULL,
  coid STRING NOT NULL,
  ssc STRING NOT NULL,
  same_store STRING NOT NULL,
  customer_code STRING NOT NULL,
  hca_ind STRING NOT NULL,
  client_email_ind STRING NOT NULL,
  total_billed_charge_amt NUMERIC(32, 3) NOT NULL,
  insurance_payment_amt NUMERIC(33, 4) NOT NULL,
  current_balance_amt NUMERIC(32, 3) NOT NULL,
  balance_threshold STRING NOT NULL,
  stratification STRING NOT NULL,
  report_type STRING NOT NULL,
  inclusion_flag STRING NOT NULL,
  current_pool_category_desc STRING,
  prev_pool_assignment_id STRING,
  prev_pool_assignment_desc STRING,
  iplan_id STRING,
  iplanname STRING,
  major_payor_group_id STRING,
  major_payor_name STRING,
  specialization STRING,
  liability_phase_status_desc STRING,
  encounter_financial_class_code STRING,
  liability_financial_class_code STRING,
  current_pool_assignment_id STRING,
  current_pool_assignment_desc STRING,
  wait_date DATE,
  liability_sequence_number NUMERIC(29),
  patient_type_code STRING,
  account_status_code STRING,
  discharge_date DATE,
  pool_responsible_dept_name STRING,
  last_action_date DATETIME,
  prev_pool_date DATE,
  age_in_pool INT64,
  age_gt_7days STRING,
  age_gt_7days_count INT64,
  action_not_taken INT64,
  numerator STRING,
  day_interval_sid STRING,
  tieramt NUMERIC(33, 4),
  tierlevel STRING,
  current_pool_pspooldept STRING,
  current_pool_pspooltype STRING,
  current_pool_poolsubgroup STRING,
  current_pool_poolfunction STRING,
  current_pool_poolsla INT64,
  current_pool_pspoolvendor STRING,
  current_pool_pspoolitmprhr NUMERIC(31, 2),
  current_pool_pspoolvndesc STRING,
  current_pool_pspoollob STRING,
  current_pool_pspoolmanager STRING,
  current_pool_pspoolpaygrp STRING,
  current_pool_pspoolresdept STRING,
  current_pool_pspooltier STRING,
  current_pool_seqnumber NUMERIC(29),
  current_pool_accountid STRING,
  current_pool_encounterid STRING,
  workedtodayby STRING,
  workedtodaytime TIME,
  workedtodayactionid STRING,
  workedtodayactionvendor STRING,
  workedtodayactionvendorroletype STRING,
  workedtodaystatusid STRING,
  workedtodayresultid STRING,
  workedtodaypoolnumber STRING,
  workedaccount INT64 NOT NULL,
  workedaccountyn STRING NOT NULL,
  workedtodaytieramt NUMERIC(33, 4),
  viewedbutnotworkedaccount INT64 NOT NULL,
  viewedbutnotworkedaccountyn STRING NOT NULL,
  totalaccounts INT64 NOT NULL,
  claimbalance NUMERIC(32, 3),
  viewedtodayid STRING,
  viewedtodaytime TIME,
  viewedtodaydate DATE,
  viewedtodayvendor STRING,
  viewedtodayvendorroletype STRING,
  claim_entered_current_pool_count INT64 NOT NULL,
  pvclaimkey INT64,
  ecwclaimkey INT64,
  current_pool_pspoolconctrlnum STRING,
  pvregionkey INT64,
  ecwregionkey INT64,
  dwlastupdatedatetime DATETIME NOT NULL
)
;