CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpspegrplocation
(
  pspegrplocactive STRING,
  pspegrplocaddrtyp STRING,
  pspegrplocaltname STRING,
  pspegrploccliaexpdte DATETIME,
  pspegrploccliafrdte DATETIME,
  pspegrplocclianum STRING,
  pspegrploccliatyp STRING,
  pspegrplocecwfacid STRING,
  pspegrplocfclose TIME,
  pspegrplocfopen TIME,
  pspegrplocgafid STRING,
  pspegrplockey STRING NOT NULL,
  pspegrploclocid STRING,
  pspegrplocmclose TIME,
  pspegrplocmopen TIME,
  pspegrplocsatclose TIME,
  pspegrplocsatopen TIME,
  pspegrplocsrvfac STRING,
  pspegrplocsunclose TIME,
  pspegrplocsunopen TIME,
  pspegrploctclose TIME,
  pspegrplocthclose TIME,
  pspegrplocthopen TIME,
  pspegrploctopen TIME,
  pspegrplocwclose TIME,
  pspegrplocwopen TIME,
  pspegrplocextcoid STRING,
  pspegrplocloaddte DATETIME,
  pspegrplocnpi STRING,
  PRIMARY KEY (pspegrplockey) NOT ENFORCED
)
;