CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_rprtpesnapshot
(
  snapshotdate DATE,
  coid STRING,
  groupdba STRING,
  groupnpi STRING,
  groupname STRING,
  grouptaxid STRING,
  ppiassociatedlocationaddress STRING,
  ppicpidpayorname STRING,
  ppiclaimsatriskcount INT64,
  ppiclaimsonholdbalance NUMERIC(33, 4),
  ppicompletedate DATE,
  ppieffectivedate DATE,
  ppienrollmentaction STRING,
  ppigin STRING,
  ppiinitialreceivedfrompayordate DATETIME,
  ppikey STRING,
  ppilastnote STRING,
  ppilastnotedate DATE,
  ppileadgroupproviderstartdate DATE,
  ppiphase STRING,
  ppipin STRING,
  ppistatus STRING,
  ppistatusdate DATE,
  ppistatusdescription STRING,
  ppitype STRING,
  ppivoidflag STRING,
  payorsplitbylocationflag STRING,
  practicebillingaddress STRING,
  provideraddresstype STRING,
  providerfullname STRING,
  providerprimaryspecialty STRING,
  providersspactiveflag STRING,
  providertaxonomycode STRING,
  providerterminationdate DATE,
  providerterminationflag STRING,
  providernpi STRING,
  artivappikey INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;