CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpssubcatchklst
(
  psscid STRING,
  psscaccountid STRING,
  psscactgrp STRING,
  pssccat STRING,
  pssccattype STRING,
  psscccat STRING,
  pssccdte STRING,
  pssccomplete STRING,
  pssccrtdte STRING,
  psscctime STRING,
  pssccuser STRING,
  psscdoc1 STRING,
  psscdoc2 STRING,
  psscdoc3 STRING,
  psscdoc4 STRING,
  psscencntrid STRING,
  psscfuflag STRING,
  psscfuflaguser STRING,
  psscinstruct STRING,
  psscpayerid STRING,
  psscpriority STRING,
  psscqdte STRING,
  psscqtime STRING,
  psscquser STRING,
  psscrdte STRING,
  psscrtime STRING,
  psscruser STRING,
  psscsource STRING,
  psscstatus STRING,
  psscsubcat STRING,
  psscsubcatdesc STRING,
  psscsubcattype STRING,
  psscorgpyrid STRING,
  psscorigroute STRING,
  pssccoidreroute STRING,
  dwlastupdatedatetime DATE
)
;