CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpsadjustreq
(
  psaracctid NUMERIC(29),
  psaradjcdlineldreq NUMERIC(29),
  psaradjtype STRING,
  psaradjustcd STRING,
  psarapprllevelfinal NUMERIC(29),
  psarappruser STRING,
  psarapprvllevel NUMERIC(29),
  psarapprvltable STRING,
  psarcil STRING,
  psarcilinstructions STRING,
  psarclmadjamt NUMERIC(31, 2),
  psarclmbalafterapprv NUMERIC(31, 2),
  psarclmnum STRING,
  psarconfirmdte DATETIME,
  psarcptamt NUMERIC(31, 2),
  psarcptcode STRING,
  psarcpttotamt NUMERIC(31, 2),
  psarcurpayer STRING,
  psardesc STRING,
  psardispid NUMERIC(29),
  psarecwclmstatchgto STRING,
  psarencntrid NUMERIC(29),
  psarexportadjamt NUMERIC(31, 2),
  psarexportadjcd STRING,
  psarexportdte DATETIME,
  psargrpid NUMERIC(29),
  psarid NUMERIC(29),
  psarissuenumber STRING,
  psarliabmoveto STRING,
  psarlinenetamt NUMERIC(31, 2),
  psarlinenum STRING,
  psarlinepaidbypyr NUMERIC(31, 2),
  psarmcarersncd NUMERIC(29),
  psarmod1 STRING,
  psarmod2 STRING,
  psarmod3 STRING,
  psaronbasedoc1 STRING,
  psaronbasedoc10 STRING,
  psaronbasedoc2 STRING,
  psaronbasedoc3 STRING,
  psaronbasedoc4 STRING,
  psaronbasedoc5 STRING,
  psaronbasedoc6 STRING,
  psaronbasedoc7 STRING,
  psaronbasedoc8 STRING,
  psaronbasedoc9 STRING,
  psarotherreftxt STRING,
  psarpayeraddrmod STRING,
  psarpayeradr1 STRING,
  psarpayeradr2 STRING,
  psarpayercity STRING,
  psarpayername STRING,
  psarpayerst STRING,
  psarpayerzip STRING,
  psarprevapprovallvl NUMERIC(29),
  psarprevappruser STRING,
  psarreconciled STRING,
  psarrefundreason STRING,
  psarrefundtype STRING,
  psarrejreason STRING,
  psarrejreasonnote STRING,
  psarrejuser STRING,
  psarreqdte DATETIME,
  psarreqphone NUMERIC(29),
  psarreqphonechr STRING,
  psarspcagny STRING,
  psarstatus STRING,
  psartier2date DATETIME,
  psartier3date DATETIME,
  psartier4date DATETIME,
  psartier5date DATETIME,
  psartier6date DATETIME,
  psartransid NUMERIC(29),
  psartrigger NUMERIC(29),
  psartype STRING,
  psarunprocessedrej STRING,
  psaruserid STRING,
  psartier2user STRING,
  psartier3user STRING,
  psartier4user STRING,
  psartier5user STRING,
  psartier6user STRING
)
;