CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpspeecreqchklst
(
  pspeecactgrp STRING,
  pspeecactive STRING,
  pspeecassignedto STRING,
  pspeecaviid STRING,
  pspeeccarrier STRING,
  pspeeccarriernoteflg STRING,
  pspeeccloseactgrp STRING,
  pspeecclosecat STRING,
  pspeecclosedte DATETIME,
  pspeecclosemsg STRING,
  pspeecclosetime DATETIME,
  pspeeccloseuser STRING,
  pspeeccomplete STRING,
  pspeeccreatedte DATETIME,
  pspeeccreatetime TIME,
  pspeecdelete STRING,
  pspeecescalatelevel STRING,
  pspeecescalationdte1 DATETIME,
  pspeecescalationdte2 DATETIME,
  pspeecexportdte DATETIME,
  pspeecid NUMERIC(29) NOT NULL,
  pspeecinstruct STRING,
  pspeecinstructcopied STRING,
  pspeecloaddte DATETIME,
  pspeecmsgedit STRING,
  pspeecnewdocs STRING,
  pspeecnewmsgs STRING,
  pspeecnotes STRING,
  pspeecorigsigreq STRING,
  pspeecpayerid STRING,
  pspeecppiid STRING,
  pspeecpricomplete STRING,
  pspeecpriority STRING,
  pspeecrequestdesc STRING,
  pspeecrequesttype STRING,
  pspeecroute STRING,
  pspeecsource STRING,
  pspeecstatus STRING,
  pspeectguid STRING,
  pspeectportalid STRING,
  pspeectrackingnum STRING,
  pspeectrequestcode STRING,
  pspeecupdatetype STRING,
  pspeeceffdteochg DATETIME,
  pspeecpool STRING,
  pspeeclpool STRING,
  pspeecstchgdate DATETIME,
  PRIMARY KEY (pspeecid) NOT ENFORCED
)
;