CREATE TABLE IF NOT EXISTS edwpsc_staging.artiva_stgpspespautilcso
(
  pspesucsoactive STRING,
  pspesucsobpadr1 STRING,
  pspesucsobpadr2 STRING,
  pspesucsobpattn STRING,
  pspesucsobpcsz STRING,
  pspesucsobprov STRING,
  pspesucsobprto STRING,
  pspesucsobtaxid STRING,
  pspesucsoclinicid STRING,
  pspesucsoclinicnpi STRING,
  pspesucsocpid STRING,
  pspesucsocref STRING,
  pspesucsoecttype STRING,
  pspesucsoeffdte DATETIME,
  pspesucsoexpdte DATETIME,
  pspesucsogrpnpi STRING,
  pspesucsokey STRING NOT NULL,
  pspesucsolgrpid STRING,
  pspesucsolprovid STRING,
  pspesucsoovtreq STRING,
  pspesucsopaytype STRING,
  pspesucsopractid STRING,
  pspesucsopref STRING,
  pspesucsoprocflg STRING,
  pspesucsoprovid STRING,
  pspesucsoprovnpi STRING,
  pspesucsoptaxid STRING,
  pspesucsoptaxo STRING,
  pspesucsorprovid STRING,
  pspesucsorprovnpi STRING,
  pspesucsosfadr1 STRING,
  pspesucsosfadr2 STRING,
  pspesucsosfattn STRING,
  pspesucsosfcsz STRING,
  pspesucsosfrefid STRING,
  pspesucsospaid STRING,
  pspesucsotaxo STRING,
  PRIMARY KEY (pspesucsokey) NOT ENFORCED
)
;