CREATE TABLE IF NOT EXISTS edwpsc_staging.ccu_factpvinventory
(
  ccupvinventorykey INT64 NOT NULL,
  regionkey INT64,
  facilitykey INT64,
  coid STRING,
  assignedtovendor STRING,
  vendorname STRING,
  vendorassigneddate DATE,
  servicedate DATE,
  servicingproviderkey INT64,
  servicingproviderspecialty STRING,
  servicingproviderspecialtycategory STRING,
  vendorassigned STRING,
  claimlastupdateddate DATE,
  dayssinceclaimlastupdateddate INT64,
  claimnumber STRING,
  totalchargesamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  holdcode STRING,
  encounterid INT64,
  sourcesystem STRING,
  owner STRING,
  inventorytype STRING,
  dwlastupdatedatetime DATETIME,
  groupassignment STRING,
  claimkey INT64,
  visittypekey INT64,
  visitstatuskey INT64,
  patientkey INT64,
  loaddate DATE,
  worked INT64,
  workeddate DATE,
  ccunoncustomerconfigkey INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  encounterkey INT64,
  sourcelastupdateddatetime DATETIME,
  ccunoncustomernpiconfigkey INT64,
  procedurecategory1 STRING,
  procedurecategory2 STRING,
  cptcodes STRING,
  busincessdayssinceservicedate INT64,
  dayssinceservicedate INT64,
  busincessdayssincelastmodified INT64,
  cptmodifiers STRING,
  icdcodes STRING
)
;