CREATE TABLE IF NOT EXISTS edwpsc_staging.ccu_rprtepicclaimsummary
(
  ccuclaimsummarykey INT64 NOT NULL,
  sourcesystemcode STRING NOT NULL,
  regionname STRING,
  dosproviderkey INT64,
  dosprovideruname STRING,
  dosproviderid INT64,
  dosproviderlastname STRING,
  dosproviderfirstname STRING,
  claimnumber INT64,
  encounterid INT64,
  billingarea STRING,
  encountercoid STRING,
  claimcoid STRING,
  encounterkey INT64,
  claimkey INT64,
  regionkey INT64,
  encounterdatemin DATE,
  encounterdatemax DATE,
  claimfromservicedatemin DATE,
  claimfromservicedatemax DATE,
  recentchangeddate DATE,
  encounterprocedurecodecombined STRING,
  claimprocedurecodecombined STRING,
  emrcptsvsclaimcpts STRING,
  emrcptsnotonclaim STRING,
  claimcptsnotonemr STRING,
  unitqtychanged STRING,
  emrcodeestvalue NUMERIC(33, 4),
  claimcodeestvalue NUMERIC(33, 4),
  codechangeimpact NUMERIC(33, 4),
  createdby34id STRING,
  createdbyname STRING,
  lastchangedby34combined STRING,
  lastchangedbynamecombined STRING,
  lastchangedbydeptcombined STRING,
  lastchangedbycompanynamecombined STRING,
  ecwbillingnotes STRING,
  patientmrncombined STRING,
  financialnumber STRING,
  patientlastname STRING,
  patientfirstname STRING,
  codechangeimpactdirection STRING,
  inscopecategories STRING,
  lastchangedbydeptflag STRING,
  ccuflag STRING,
  billingnotesconverted STRING,
  encounterdateyyyymm STRING,
  claimfromservicedateyyyymm STRING,
  lasttoucheddateyyyymm STRING,
  encountercoidlob STRING,
  h2uflag STRING,
  visitnumber INT64,
  transactionnumbercombined STRING,
  patientinternalidcombined STRING,
  procedurecodechange STRING,
  encountertype STRING,
  dwlastupdatedatetime DATE NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  encountercoidsublob STRING,
  paytoproviderkey INT64
)
;