CREATE TABLE IF NOT EXISTS edwpsc_staging.ccu_refnoncustomerconfig
(
  ccunoncustomerconfigkey INT64 NOT NULL,
  ccunoncustomerconfiglabel STRING NOT NULL,
  coidoperator STRING NOT NULL,
  coid STRING NOT NULL,
  sourcesystemoperator STRING NOT NULL,
  sourcesystemcode STRING NOT NULL,
  posoperator STRING NOT NULL,
  pos STRING NOT NULL,
  procedurecategory1operator STRING NOT NULL,
  procedurecategory1 STRING NOT NULL,
  visitstatusoperator STRING NOT NULL,
  visitstatus STRING NOT NULL,
  visittypeoperator STRING NOT NULL,
  visittype STRING NOT NULL,
  lockflagoperator STRING NOT NULL,
  lockflag STRING NOT NULL,
  currentinventoryowner STRING NOT NULL,
  currentinventoryowneroperator STRING NOT NULL,
  ccuinventorykeyqryoperator STRING NOT NULL,
  ccuinventorykeyqry STRING NOT NULL,
  inventoryowner STRING NOT NULL,
  inventorytype STRING NOT NULL,
  groupassignment STRING NOT NULL,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  insertedby STRING NOT NULL,
  inserteddtm DATETIME NOT NULL,
  modifiedby STRING NOT NULL,
  modifieddtm DATETIME NOT NULL,
  procedurecategory2operator STRING NOT NULL,
  procedurecategory2 STRING NOT NULL,
  inventorytypeoperator STRING NOT NULL,
  providerspecialty STRING NOT NULL,
  providerspecialtyoperator STRING NOT NULL,
  PRIMARY KEY (coidoperator, coid, sourcesystemoperator, sourcesystemcode, posoperator, pos, procedurecategory1operator, procedurecategory1, procedurecategory2operator, procedurecategory2, visitstatusoperator, visitstatus, visittypeoperator, visittype, lockflagoperator, lockflag) NOT ENFORCED
)
;