CREATE TABLE IF NOT EXISTS edwpsc_staging.ccu_factepiccodechange
(
  codechangekey INT64 NOT NULL,
  encounterkey INT64,
  encounterid INT64,
  regionkey INT64,
  claimkey INT64,
  claimlinechargekey INT64,
  claimnumber INT64,
  claimlinenumber INT64,
  encountercoid STRING,
  claimcoid STRING,
  encountertoscode STRING,
  claimtoscode INT64,
  toscodematch STRING,
  toscodematchtype STRING,
  encounterposcode INT64,
  claimposcode STRING,
  poscodematch STRING,
  poscodematchtype STRING,
  encounterprocedurecode STRING,
  claimprocedurecode STRING,
  procedurecodematch STRING,
  procedurecodematchtype STRING,
  claimmodifier1code STRING,
  encounterunitqty NUMERIC(29),
  claimunitqty NUMERIC(29),
  unitqtymatch STRING,
  unitqtymatchtype STRING,
  claimlineitemnum INT64,
  claimdx1code STRING,
  claimdx2code STRING,
  claimdx3code STRING,
  encounterdate DATE,
  claimfromservicedate DATE,
  encounterdatetofromservicedatematch STRING,
  encounterdatetofromservicedatematchtype STRING,
  encountersmryofcaredate DATE,
  claimstartentrydate DATE,
  claimendentrydate DATE,
  claimdate DATE,
  encounterbillingtypecode STRING,
  encounterclaimmatch STRING,
  claimcreatedbylastname STRING,
  claimcreatedbyfirstname STRING,
  claimcreatedby34id STRING,
  dosproviderid INT64,
  renproviderid STRING,
  createdbylname STRING,
  createdbyfname STRING,
  createdbyuserkey STRING,
  supervisorlname STRING,
  supervisorfname STRING,
  supervisorproviderkey STRING,
  practiceidname STRING,
  renproviderlname STRING,
  renproviderfname STRING,
  renproviderkey STRING,
  dosproviderlname STRING,
  dosproviderfname STRING,
  dosproviderkey STRING,
  claimstatusname STRING,
  claimstatuslastmodifieddate DATE,
  claimstatuslastmodifiedusername STRING,
  encountertype STRING,
  practicename STRING,
  transactionnumber INT64,
  visitnumber INT64,
  patientkey INT64,
  paytoproviderkey INT64,
  serviceareakey INT64,
  dwlastupdatedatetime DATE NOT NULL,
  sourcesystemcode STRING,
  hashnomatch INT64 NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  lastchangedby INT64,
  changeddate DATE,
  isactive BOOL NOT NULL,
  encounterprocedureordernum INT64
)
;