CREATE TABLE IF NOT EXISTS edwpsc_staging.ccu_rprtvendorrollout
(
  ccuvendorrolloutkey INT64 NOT NULL,
  snapshotdate DATE,
  coid STRING,
  coidname STRING,
  groupname STRING,
  divisionname STRING,
  marketname STRING,
  coidspecialty STRING,
  coidcentralizedstatus STRING,
  coidstartdatekey DATE,
  coidtermdatekey DATE,
  coidlob STRING,
  coidsublob STRING,
  coidsystem STRING,
  ppmsflag STRING,
  coidlessthan120daysactive STRING,
  correctcptcount INT64,
  totalcpts INT64,
  percentagecoidcorrect NUMERIC(33, 4),
  correctrate INT64,
  denialcount INT64,
  totalqualitycount INT64,
  percentagecoidindenied NUMERIC(33, 4),
  denialrate INT64,
  ticketpermo NUMERIC(33, 4),
  totalprptickets INT64,
  prpratelow INT64,
  outcomerecommendation STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedyby STRING,
  modifieddtm DATETIME,
  coidexclusionflag STRING,
  dwlastupdatedatetime DATETIME
)
;