CREATE TABLE IF NOT EXISTS edwpsc_staging.cmt_factlockbox
(
  lockboxkey INT64 NOT NULL,
  lockboxfileid INT64 NOT NULL,
  dataimportid INT64 NOT NULL,
  bankname STRING NOT NULL,
  depositdate DATETIME NOT NULL,
  accountnumber STRING NOT NULL,
  checkamount NUMERIC(33, 4) NOT NULL,
  checknumber STRING NOT NULL,
  lockboxnumber INT64 NOT NULL,
  batchnumber STRING NOT NULL,
  batchtotal NUMERIC(33, 4),
  appenddate DATETIME NOT NULL,
  createbatchid STRING,
  bankaccountid INT64 NOT NULL,
  bankaccountnumber STRING NOT NULL,
  accountname STRING NOT NULL,
  routingnumber INT64,
  glaccountsid INT64 NOT NULL,
  legalentityid INT64 NOT NULL,
  depositcoid STRING NOT NULL,
  bankid INT64 NOT NULL,
  enddate DATETIME,
  createdate DATETIME NOT NULL,
  createuserid STRING NOT NULL,
  isbatch BOOL NOT NULL,
  controlsaccountid INT64 NOT NULL,
  iszbt BOOL NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (lockboxkey) NOT ENFORCED
)
;