CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factencounterdiagnosis
(
  encounterdiagnosiskey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  encounterkey INT64,
  encounterid INT64,
  diagnosiscodekey INT64,
  icdcode STRING,
  icdorder INT64,
  icdtype INT64,
  icddescription STRING,
  visitdate DATE,
  primaryflag INT64,
  deleteflag INT64,
  specify STRING,
  notes STRING,
  assessmentonsetdate DATE,
  snomed STRING,
  snomeddescription STRING,
  synonymid INT64,
  axis INT64,
  sourceprimarykeyvalue STRING,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  archivedrecord STRING NOT NULL
)
;