CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refpractice_history
(
  practicekey INT64 NOT NULL,
  practicename STRING,
  practiceprimaryaddressline1 STRING,
  practiceprimaryaddressline2 STRING,
  practiceprimarygeographykey INT64 NOT NULL,
  practicetelephone STRING,
  practicefax STRING,
  practiceemail STRING,
  practicesiteid STRING,
  practicefederaltaxid STRING,
  practicecliaid STRING,
  practiceparenttin STRING,
  practicegroupnpi STRING,
  practicetaxonomycode STRING,
  practicelockboxno STRING,
  practicecob STRING,
  practiceprimarycoid STRING,
  practicestartdatekey DATE NOT NULL,
  practiceenddatekey DATE NOT NULL,
  practicespindowndatekey DATE NOT NULL,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  regionkey INT64,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL
)
;