CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factdftmessage
(
  dftmessagekey INT64 NOT NULL,
  regionkey INT64,
  datereceived DATETIME,
  datemodified DATETIME,
  patientaccountnumber STRING,
  patientlastname STRING,
  patientfirstname STRING,
  patientdobkey DATE,
  messagestatus INT64,
  visitnumber STRING,
  encounterid STRING,
  encounterkey INT64,
  claimid INT64,
  claimkey INT64,
  errormessage STRING,
  messagecontrolid STRING,
  providerid INT64,
  providerkey INT64,
  facilityid INT64,
  facilitykey INT64,
  sentid INT64,
  messagetype STRING,
  reconciledflag INT64,
  practiceid STRING,
  pmid INT64,
  sourceaprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  messagecontrolidshort STRING,
  pmidname STRING,
  chargetransactionid STRING,
  sendingfacility STRING,
  visitlocationfacility STRING,
  visitlocationunit STRING,
  visitlocation STRING,
  coid STRING
)
;