CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factsnapshottransactioncharge
(
  transactionchargesmrykey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  regionkey INT64,
  coid STRING,
  gldepartment STRING,
  claimkey INT64,
  claimnumber INT64,
  patientkey INT64,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid INT64,
  renderingproviderkey INT64,
  renderingproviderid INT64,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1iplankey INT64,
  iplan1id INT64,
  financialclasskey INT64,
  transactionamt NUMERIC(33, 4),
  transactiondatemonthid INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptunitchangeamt NUMERIC(33, 4),
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  transactiontype STRING,
  cptid INT64,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptunitsonline NUMERIC(31, 2),
  cpttos STRING,
  cptchargeschangeamt NUMERIC(31, 2),
  cptstartdos DATETIME,
  cptenddos DATETIME,
  cptseqnum INT64,
  transactionid INT64,
  transactiondatekey DATE,
  claimdatemonthid INT64,
  servicedatemonthid INT64,
  claimlinechargekey INT64,
  transactionsamemonthflag STRING NOT NULL
)
;