CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factencountermeditechexpanse
(
  encountermtxkey INT64 NOT NULL,
  regionkey INT64,
  patientkey INT64,
  accountnumber STRING,
  facilitykey INT64,
  locationkey INT64,
  siteid STRING,
  coid STRING,
  absentproviderkey INT64,
  admittingproviderkey INT64,
  emergencyproviderkey INT64,
  familyproviderkey INT64,
  primarycareproviderkey INT64,
  referringproviderkey INT64,
  supervisingproviderkey INT64,
  visitproviderkey INT64,
  primaryiplankey INT64,
  enccreatedby INT64,
  enccreateddate DATETIME,
  servicedatekey DATETIME,
  registrationstatus STRING,
  registrationtype STRING,
  deleteflag INT64,
  reasonforvisit STRING,
  admitdatetime DATETIME,
  arrivaldatetime DATETIME,
  claimkey INT64,
  claimnumber INT64,
  encounterkey INT64,
  patientid STRING,
  facilityid STRING,
  locationid STRING,
  absentproviderid STRING,
  admittingproviderid STRING,
  emergencyproviderid STRING,
  familyproviderid STRING,
  primarycareproviderid STRING,
  referringproviderid STRING,
  supervisingproviderid STRING,
  visitproviderid STRING,
  primaryiplanid STRING,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (encountermtxkey) NOT ENFORCED
)
;