CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factrhclaimhistory
(
  rhclaimhistorykey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  coid STRING,
  importdatekey DATE,
  rhclaimhistoryclientid STRING,
  rhclaimhistorysubmissiondatekey STRING,
  rhclaimhistorybridgefilenumber STRING,
  rhclaimhistoryclaimid STRING,
  rhclaimhistorypatientcontrolnbr STRING,
  rhclaimhistoryoriginalclaimstatuscode STRING,
  rhclaimhistorypayerindicator STRING,
  rhclaimhistoryoriginalclaimamount STRING,
  rhclaimhistoryoriginalerrorcount STRING,
  rhclaimhistoryreleaseddatekey DATE,
  rhclaimhistoryclaimstate STRING,
  rhclaimhistoryholdcode STRING,
  rhclaimhistorycurrentclaimstatuscode STRING,
  rhclaimhistoryerrorcount STRING,
  rhclaimhistorytotalclaimamount STRING,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  billedtoid INT64,
  fullclaimnumber STRING,
  regionkey INT64,
  PRIMARY KEY (rhclaimhistorykey) NOT ENFORCED
)
;