CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_rprtarcompmor
(
  avgdgr3mo NUMERIC(33, 4),
  balancetype STRING,
  center STRING,
  cohother NUMERIC(33, 4),
  cohpe NUMERIC(33, 4),
  coid STRING NOT NULL,
  coidname STRING,
  gldepartmentnumber STRING,
  hospitalname STRING,
  hospitalcoid STRING,
  coidspecialty STRING,
  daysinlast3months INT64,
  divisionname STRING,
  groupname STRING,
  ins1insurancepayergroupname STRING,
  insurancearbilled NUMERIC(33, 4),
  insurancearunbilledecw NUMERIC(33, 4),
  insurancearunbilledrh NUMERIC(33, 4),
  leftover NUMERIC(33, 4),
  lob STRING,
  marketname STRING,
  patientunidentified NUMERIC(33, 4),
  servicingprovidername STRING,
  servicingprovidernpi STRING,
  servicingprovidertaxonomycode STRING,
  state STRING,
  sublob STRING,
  system STRING,
  totalbalance NUMERIC(33, 4),
  totalcharges NUMERIC(33, 4),
  totalchargeslast3months NUMERIC(33, 4),
  totalinsurancebalance NUMERIC(33, 4),
  totalpatientbalance NUMERIC(33, 4),
  claimagingbucket STRING,
  patientcollections NUMERIC(33, 4),
  patientpsc NUMERIC(33, 4),
  coidstartmonth DATE,
  coidtermmonth DATE,
  servicingproviderstartmonth DATE,
  servicingprovidertermmonth DATE,
  servicingproviderspecialty STRING,
  servicingprovidersubspecialty STRING,
  ins1financialclassnum STRING,
  ins1financialclassname STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  claimcount INT64,
  snapshotdate DATE,
  dwlastupdatedatetime DATETIME
)
;