CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_juncprinsnumber
(
  ecwprinsnumberkey INT64 NOT NULL,
  regionkey INT64,
  insuranceid INT64,
  iplankey INT64,
  providerid INT64,
  providerkey INT64,
  providernumber STRING,
  groupnumber STRING,
  effdate DATETIME,
  usedefaults INT64,
  taxid STRING,
  taxidtype STRING,
  billingfacilityid INT64,
  billingfacilitykey INT64,
  siteid STRING,
  refprovidtype STRING,
  refprovgrpidtype STRING,
  usehcfadefaults INT64,
  hcfa24k STRING,
  hcfa33pin STRING,
  hcfa33grp STRING,
  useemcdefaults INT64,
  ba02 STRING,
  ca028 STRING,
  ba015 STRING,
  hcfa24kidtype STRING,
  hcfa33grpidtype STRING,
  deleteflag INT64,
  sourceprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;