CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_rprtdenialstrending
(
  rprtdenialstrendingkey INT64 NOT NULL,
  snapshotdate DATETIME,
  snapshotyear INT64,
  dosmonth DATETIME,
  dosyear INT64,
  coid STRING,
  specialtycategory STRING,
  specialtyname STRING,
  specialtytype STRING,
  majorpayor STRING,
  financialclassname STRING,
  firstdenialcategory STRING,
  firstdenialcategorycustom STRING,
  adjcode STRING,
  adjname STRING,
  sourcesystem STRING,
  initialdeniedcharges NUMERIC(33, 4),
  initialdeniedchargesdos NUMERIC(33, 4),
  charges NUMERIC(33, 4),
  chargesdos NUMERIC(33, 4),
  finaldenials NUMERIC(33, 4),
  finaldenialsdos NUMERIC(33, 4),
  initialdeniedcharges3month NUMERIC(33, 4),
  initialdeniedcharges6month NUMERIC(33, 4),
  initialdeniedcharges12month NUMERIC(33, 4),
  finaldenials3month NUMERIC(33, 4),
  finaldenials6month NUMERIC(33, 4),
  finaldenials12month NUMERIC(33, 4),
  charges3month NUMERIC(33, 4),
  charges6month NUMERIC(33, 4),
  charges12month NUMERIC(33, 4),
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;