CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refsrtcontractmasterfile
(
  contractmasterfilekey INT64 NOT NULL,
  sowstatus STRING,
  partner STRING,
  invoicecontrolnumber INT64,
  itemnumber INT64,
  clsource STRING,
  activeentry INT64,
  contractcoid INT64,
  lineofbusiness STRING,
  deptartmentnumber INT64,
  itemnumberdescription STRING,
  originalitemnumber INT64,
  owner STRING,
  valescoindicator INT64,
  accrualproductivity NUMERIC(32, 3),
  contractcoiddescription STRING,
  summaryofservice STRING,
  contractlaborproductivityactual NUMERIC(32, 3),
  workflow STRING,
  system STRING,
  deptdescription STRING,
  sownumber INT64,
  servicemodificationschedule INT64,
  projectedstartdate DATE,
  signedcontractdate DATE,
  contractrenewal DATE,
  termeddate DATE,
  invoicename STRING,
  basefterate NUMERIC(31, 2),
  rate NUMERIC(31, 2),
  contracttype STRING,
  contractedproductivityperhour NUMERIC(32, 3),
  hours STRING,
  location STRING,
  qualitypenalty93to9499 NUMERIC(31, 2),
  qualitypenalty90to9299 NUMERIC(31, 2),
  qualitypenaltylt90 NUMERIC(31, 2),
  qualitypenalty85to8999 NUMERIC(31, 2),
  qualitypenalty80to8499 NUMERIC(31, 2),
  qualitypenaltylt7999 NUMERIC(31, 2),
  forecastsubmissions STRING,
  notifications STRING,
  slapenaltysummary STRING,
  legacyinvoicecontrolnumber INT64,
  modifiedbycustom STRING,
  modifiedcustom DATE,
  modifiedreference INT64,
  versionnumber INT64,
  systeminteger INT64,
  duplicaterecord2 STRING,
  iseditable STRING,
  spworkflowstatus STRING,
  assignedto STRING,
  duplicated STRING,
  id INT64,
  sourceaprimarykeyvalue INT64,
  deleteflag INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME NOT NULL,
  modifiedby STRING,
  modifieddtm DATETIME
)
;