CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factsnapshotpaymentclaim
(
  paymentclaimkey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  coid STRING,
  regionkey INT64,
  claimkey INT64,
  claimnumber INT64,
  gldepartment STRING,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid INT64,
  renderingproviderkey INT64,
  renderingproviderid INT64,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1iplankey INT64,
  iplan1id INT64,
  financialclasskey INT64,
  encounterid INT64,
  contractualadjustmentamt NUMERIC(33, 4),
  allowedamt NUMERIC(33, 4),
  deductibleamt NUMERIC(33, 4),
  coinsuranceamt NUMERIC(33, 4),
  memberbalanceamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  withheldamt NUMERIC(33, 4),
  checkamt NUMERIC(33, 4),
  paymentcreateddatekey DATE,
  paymentmodifieddatekey DATE,
  paymenttypekey INT64,
  paymentid INT64,
  paymentdetailid INT64,
  checkdatekey DATE,
  checknumber STRING,
  checktype STRING,
  payerid INT64,
  posteddatekey DATE,
  paymentfromiplankey INT64,
  paymentfromiplanid INT64,
  paymentmemo STRING,
  paymentlock INT64,
  paymentdetailmodifieddatekey DATE,
  dwlastupdatedatetime DATETIME
)
;