CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refnbtallocglphysiciancurredw
(
  coid INT64 NOT NULL,
  coidname STRING,
  providerdepartmentno INT64 NOT NULL,
  providerfirstname STRING,
  providerlastname STRING,
  practicename STRING,
  overheaddepartmentno INT64,
  ancillarydepartmentno INT64,
  practiceestablishedid INT64,
  coiddepartmentspecialtycode STRING,
  provideroriginalstartdate DATETIME,
  budgetstartdate DATETIME,
  actiondate STRING,
  ohallocation INT64,
  coiddepartmentfte NUMERIC(31, 2),
  coiddepartmentisbudgetcc INT64,
  coiddepartmentproviderstatusid INT64,
  coiddepartmentproviderstatus STRING,
  terminationdate STRING,
  coiddeprprovassignedstartdate DATETIME,
  projectedterminationdate DATETIME,
  glperiod STRING NOT NULL,
  allocationtypedescription STRING,
  allocationtypeid INT64,
  compensationtypedescription STRING,
  compensationtypeid INT64,
  providerid INT64,
  appspecialtycategoryid INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;