CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refcoidgldept
(
  coid STRING NOT NULL,
  gldepartmentnumber STRING NOT NULL,
  groupname STRING,
  groupcode STRING,
  divisionname STRING,
  divisioncode STRING,
  marketname STRING,
  marketcode STRING,
  coidname STRING,
  coidwithname STRING,
  centerdescription STRING,
  coidlob STRING,
  sublobname STRING,
  coidstartdatekey DATE,
  coidtermdatekey DATE,
  hospitalcoid STRING NOT NULL,
  hospitalname STRING NOT NULL,
  providername STRING NOT NULL,
  providerstartdatekey DATE,
  providertermdatekey DATE,
  specialtycategory STRING NOT NULL,
  specialtycode STRING NOT NULL,
  specialtyname STRING NOT NULL,
  specialtytype STRING NOT NULL,
  coidprogramtype STRING NOT NULL,
  coidlargepractice STRING NOT NULL,
  provideroriginalstartstatus STRING NOT NULL,
  provideroriginalstartdate DATE NOT NULL,
  appspecialtycategory STRING NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (coid, gldepartmentnumber) NOT ENFORCED
)
;