CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_juncinterfaceclaim
(
  ecwinterfacekey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  messageid INT64 NOT NULL,
  pmid INT64 NOT NULL,
  datereceived DATETIME NOT NULL,
  datemodified DATETIME NOT NULL,
  messagecontent STRING,
  errormessage STRING,
  messagetype STRING,
  patientlastname STRING,
  patientfirstname STRING,
  patientdob STRING,
  patientaccountnumber STRING,
  visitnumber STRING,
  messagestatus INT64 NOT NULL,
  messagecontrolid STRING NOT NULL,
  mfnmsgtype STRING,
  mfnid STRING,
  processflow STRING,
  patientid INT64 NOT NULL,
  ecwencounterid INT64 NOT NULL,
  messsagecontentid INT64,
  pmlistid INT64 NOT NULL,
  pmlistpmid INT64 NOT NULL,
  pmlistname STRING NOT NULL,
  deleteflag INT64 NOT NULL,
  interfaceconfigured INT64 NOT NULL,
  insid INT64 NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (ecwinterfacekey) NOT ENFORCED
)
;