CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factclaimlinepayment
(
  claimlinepaymentkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  claimlinechargeskey INT64,
  claimpaymentskey INT64,
  paymentdetailid INT64,
  allowedamt NUMERIC(33, 4),
  deductibleamt NUMERIC(33, 4),
  coinsuranceamt NUMERIC(33, 4),
  memberresponsibilityamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  contractualadjustmentamt NUMERIC(33, 4),
  withheldamt NUMERIC(33, 4),
  msgcode STRING,
  linetaxamt NUMERIC(33, 4),
  eraadjustmentamt NUMERIC(33, 4),
  createddatekey DATE,
  createdtime TIME,
  createdbyuserkey INT64,
  timestamp DATETIME,
  modifieddatekey DATE,
  modifiedtime TIME,
  modifiedbyuserkey INT64,
  sourceprimarykeyvalue INT64,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  invcptid INT64,
  archivedrecord STRING NOT NULL
)
;