CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factsnapshotar
(
  arkey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  claimnumber INT64,
  regionkey INT64,
  coid STRING,
  gldepartment STRING,
  servicingproviderkey INT64,
  servicingproviderid INT64,
  patientkey INT64,
  patientid INT64,
  facilitykey INT64,
  facilityid INT64,
  renderingproviderkey INT64,
  renderingproviderid INT64,
  claimdatekey DATE,
  claimdatemonthid INT64,
  servicedatekey DATE,
  servicedatemonthid INT64,
  practicekey INT64,
  practiceid INT64,
  claimstatuskey INT64,
  claimstatusdesc STRING,
  financialclasskey INT64,
  liabilityfinancialclass INT64,
  billedfirstsubmitteddatekey DATE,
  billedlastsubmitteddatekey DATE,
  iplan1iplankey INT64,
  iplan1id INT64,
  iplan2iplankey INT64,
  iplan2id INT64,
  iplan3iplankey INT64,
  iplan3id INT64,
  liabilityiplankey INT64,
  liabilityid INT64,
  liabilitydate DATE,
  liabilityownertype INT64,
  lastpaymentdatekey DATE,
  firstinsurancepaymentdatekey DATE,
  lastinsurancepaymentdatekey DATE,
  lastadjustmentdatekey DATE,
  laststatusdatekey DATE,
  totalchargesamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalpatientbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  totalpaymentsamt NUMERIC(33, 4),
  totalpatientpaymentsamt NUMERIC(33, 4),
  totalinsurancepaymentsamt NUMERIC(33, 4),
  totaladjustmentsamt NUMERIC(33, 4),
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  billedtoidtype INT64,
  claimarflag INT64,
  deleteflag INT64,
  voidflag INT64,
  addprovider1providerkey INT64,
  addprovider2providerkey INT64,
  supervisorproviderkey INT64,
  paytoproviderkey INT64,
  addprovider1providerid INT64,
  addprovider2providerid INT64,
  supervisorproviderid INT64,
  paytoproviderid INT64,
  collectionstatus STRING,
  collectioncode STRING,
  collectioncodechangedate DATE,
  firstpatientliabilitydatekey DATE,
  firstzerobalancedatekey DATE,
  firstchargedebitdatekey DATE
)
;