CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_rprtpayerresponsetrending
(
  payerresponsetrendingkey INT64 NOT NULL,
  snapshotquarter STRING,
  snapshotdate DATETIME,
  snapshotyear INT64,
  dosquarter STRING,
  dosmonth DATETIME,
  dosyear INT64,
  coid STRING,
  poskey INT64,
  servicingproviderlastname STRING,
  servicingproviderfirstname STRING,
  servicingprovidernpi STRING,
  gldepartment STRING,
  specialtycategory STRING,
  specialtyname STRING,
  specialtytype STRING,
  iplan STRING,
  majorpayor STRING,
  financialclassname STRING,
  financialclassnumber INT64,
  cptcode STRING,
  cptname STRING,
  firstdenialcategory STRING,
  initialpayerresponsecategory STRING,
  adjcode STRING,
  adjname STRING,
  sourcesystem STRING,
  charges NUMERIC(33, 4),
  newdenialsamt NUMERIC(33, 4),
  newpaymentvariancesamt NUMERIC(33, 4),
  newclaimrejectionsamt NUMERIC(33, 4),
  newpayerreponseamt NUMERIC(33, 4),
  finaldenialsamt NUMERIC(33, 4),
  finalpaymentvariancesamt NUMERIC(33, 4),
  finalclaimrejectionsamt NUMERIC(33, 4),
  providerenrollmentamt NUMERIC(33, 4),
  finalpayerresponseamt NUMERIC(33, 4),
  dwlastupdateddate DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;