CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_rprtteradatacomastnbtsupplement
(
  teradatacomastnbtsupplementkey INT64 NOT NULL,
  coid STRING,
  coidstatusid INT64,
  companycode STRING,
  vpnum STRING,
  groupvicepresidentname STRING,
  hospitalcoid STRING,
  hospitalunitnum STRING,
  hospitalname STRING,
  jointventureind STRING,
  accountlocationcode STRING,
  consolidatorind STRING,
  consolidatorid INT64,
  taxid INT64,
  coidstartdate DATE,
  hbpprogramtypeid INT64,
  hbpprogramstartdate DATE,
  arsystemcode STRING,
  arsystemname STRING,
  samestoreind STRING,
  lobcode STRING,
  lobsubcode STRING,
  totaloperationind STRING,
  datasourcecode STRING,
  sourcesystemcodekey STRING,
  vicepresidentnum STRING,
  taxidname STRING,
  appprogramtypeid STRING,
  servicelinecode STRING,
  subservicelinecode STRING,
  vendorid STRING,
  profitcentercode STRING,
  sitecode STRING,
  startdate DATE,
  activesw STRING,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;