CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_rprtiplanaccuracytrending
(
  iplanaccuracytrendkey INT64 NOT NULL,
  snapshotdate DATE,
  dosyear INT64,
  dosmonth STRING,
  servicedatekey DATE,
  practiceid INT64,
  coid STRING,
  facilityidtype INT64,
  posname STRING,
  poscategoryname STRING,
  claimnumber INT64,
  originalpayer1iplan STRING,
  originalpayer1finclass INT64,
  originalpayer1id STRING,
  chargesbucket STRING,
  originalcharges NUMERIC(33, 4),
  voidflag INT64,
  daystochange INT64,
  newclaimnumber INT64,
  changedate DATE,
  newpayer1iplan STRING,
  newpayer1finclass INT64,
  newpayer1id STRING,
  claims INT64,
  originalpayerpendingflag STRING,
  conversionstoflag STRING,
  qualifytype STRING,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  originalclaimkey INT64,
  originalpayer1iplankey INT64,
  newclaimkey INT64,
  newpayer1iplankey INT64
)
;