CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_facterainpatientadjudicationinformation
(
  erainpatientadjustmentinformationkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  mia01 NUMERIC(31, 2),
  mia02 NUMERIC(33, 4),
  mia03 NUMERIC(31, 2),
  mia04 NUMERIC(33, 4),
  mia05 STRING,
  mia06 NUMERIC(33, 4),
  mia07 NUMERIC(33, 4),
  mia08 NUMERIC(33, 4),
  mia09 NUMERIC(33, 4),
  mia10 NUMERIC(33, 4),
  mia11 NUMERIC(33, 4),
  mia12 NUMERIC(33, 4),
  mia13 NUMERIC(33, 4),
  mia14 NUMERIC(33, 4),
  mia15 NUMERIC(31, 2),
  mia16 NUMERIC(33, 4),
  mia17 NUMERIC(33, 4),
  mia18 NUMERIC(33, 4),
  mia19 NUMERIC(33, 4),
  mia20 STRING,
  mia21 STRING,
  mia22 STRING,
  mia23 STRING,
  mia24 NUMERIC(33, 4),
  segment STRING NOT NULL,
  sourcefilename STRING,
  sourcefilecreateddate DATETIME NOT NULL,
  seq INT64,
  datecreated DATETIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deletedflag INT64,
  fullclaimnumber STRING,
  regionkey INT64,
  PRIMARY KEY (erainpatientadjustmentinformationkey) NOT ENFORCED
)
;