CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refiplan_history
(
  iplankey INT64 NOT NULL,
  financialclasskey INT64 NOT NULL,
  iplangroupcactuskey INT64 NOT NULL,
  iplangroupfinancialkey INT64 NOT NULL,
  iplanname STRING,
  iplanphone STRING,
  iplanphone2 STRING,
  iplanfax STRING,
  iplanemail STRING,
  iplanprimaryaddressline1 STRING,
  iplanprimaryaddressline2 STRING,
  iplanprimarygeographykey INT64 NOT NULL,
  iplanpayorid STRING,
  iplanerapayorid STRING,
  iplanfeeschedid INT64,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  inactive INT64,
  notes STRING,
  emcpayerid STRING,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL
)
;