CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refpatientinsurance
(
  patientinsurancekey INT64 NOT NULL,
  patientkey INT64,
  iplankey INT64,
  patientinsuranceorder INT64,
  patientinsurancestartdate STRING,
  patientinsuranceenddate STRING,
  patientinsurancegroupno STRING,
  patientinsurancegroupname STRING,
  patientinsurancesubscriberno STRING,
  patientinsurancecopay STRING,
  patientinsurancedeleteflag INT64,
  patientinsuranceguaranterpatientkey INT64,
  patientinsuranceguaranterrel INT64,
  patientinsuranceisguaranterpatient INT64,
  patientinsurancesequenceno INT64,
  patientinsuranceenceligibilitystatus STRING,
  patientinsuranceeligibilitymessage STRING,
  sourceprimarykey INT64,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL,
  PRIMARY KEY (patientinsurancekey, regionkey) NOT ENFORCED
)
;