CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_facteraservicepaymentinformation
(
  eraservicepaymentinformationkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  svc01 STRING,
  svc02 NUMERIC(33, 4),
  svc03 NUMERIC(33, 4),
  svc04 STRING,
  svc05 NUMERIC(31, 2),
  svc06 STRING,
  svc07 NUMERIC(31, 2),
  cptcode STRING,
  mod1 STRING,
  mod2 STRING,
  mod3 STRING,
  mod4 STRING,
  svcstartdate DATETIME,
  svcenddate DATETIME,
  svcallowedamt NUMERIC(33, 4),
  segment STRING,
  sourcefilename STRING,
  sourcefilecreateddate DATETIME NOT NULL,
  seq INT64,
  datecreated DATETIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deletedflag INT64,
  fullclaimnumber STRING,
  regionkey INT64
)
;