CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factsnapshotchargeline
(
  chargelinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  coid STRING,
  regionkey INT64,
  claimkey INT64,
  claimnumber INT64,
  gldepartment STRING,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid INT64,
  renderingproviderkey INT64,
  renderingproviderid INT64,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1iplankey INT64,
  iplan1id INT64,
  financialclasskey INT64,
  cptid INT64,
  cptorder INT64,
  cptcode STRING,
  cptcodekey INT64,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cpttypeofservice STRING,
  cptchargesamt NUMERIC(33, 4),
  cptchargesperunitamt NUMERIC(33, 4),
  cptunits NUMERIC(31, 2),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptdeleteflag INT64,
  dwlastupdatedatetime DATETIME,
  cptposkey STRING,
  claimlinechargekey INT64
)
;