CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_arcube
(
  claimnumber INT64 NOT NULL,
  ecwregionid INT64,
  coid STRING,
  coidname STRING,
  coidandcoidname STRING,
  groupname STRING,
  divisionname STRING,
  marketname STRING,
  lineofbusiness STRING,
  claimadjustmentsgreaterthantotalcharges STRING,
  claimagebyclaimfilestatuslastchangedate INT64,
  claimagebydateofservice INT64,
  claimagebyietcurrentdepartmentassigneddate INT64,
  claimagebylastbilleddate INT64,
  claimagebylastietclosedate INT64,
  claimagebylastliabilityownerchangedate INT64,
  claimagebylastpaymentdate INT64,
  claimagebylastpaymentoradjustmentdate INT64,
  claimagebylastreleasedate INT64,
  claimagebyvoidandrecreatedate INT64,
  claimagingbucketbydateofservice STRING,
  claimagingbucketbydateofservicesortorder INT64,
  claimagingbucketbylastliabilityownerchangedate STRING,
  claimagingbucketbylastliabilityownerchangedatesortorder INT64,
  claimagingbucketbylastpaymentoradjustmentdate STRING,
  claimagingbucketbylastpaymentoradjustmentdatesortorder INT64,
  claimarcategory STRING,
  claimarcategorysortorder INT64,
  claimarsubcategory STRING,
  claimarsubcategorysortorder INT64,
  claimbalancebucket STRING,
  claimbalancebucketsortorder INT64,
  claimbalancepercentadjudicated STRING,
  claimcascodesfromecw STRING,
  claimcascodesfromera STRING,
  claimcreditbalance STRING,
  claimdate DATE,
  claimdatemonth STRING,
  claimdateyear INT64,
  claimfilestatusid STRING,
  claimfilestatuslastchangedate DATE,
  claimfilestatuslastchangedatemonth STRING,
  claimfilestatuslastchangedateyear INT64,
  claimfilestatusname STRING,
  claimholdunbilledcategory STRING,
  claimholdunbilledstatus STRING,
  claimholdunbilledsubcategory STRING,
  claimietactive STRING,
  claimietactivecbo STRING,
  claimietactivepractice STRING,
  claimietcurrentdepartment STRING,
  claimietcurrentdepartmentassigneddate DATE,
  claimietlastclosedate DATE,
  claimietlastietcategory STRING,
  claimietlastietfieldname STRING,
  claimietv2active STRING,
  claimietv2activepractice STRING,
  claimietv2activecbo STRING,
  claimietv2lastietcreateddate DATE,
  claimietv2lastietcreateddatemonth STRING,
  claimietv2lastietcreateddateyear INT64,
  claimietv2lastieterrortypedescriptions STRING,
  claimietv2lastieterrorsubcategorynames STRING,
  claimietv2lastietfieldnames STRING,
  claimietv2lastietreportnames STRING,
  claimlastbilledcategory STRING,
  claimlastbilleddate DATE,
  claimlastbilleddatemonth STRING,
  claimlastbilleddateyear INT64,
  claimlastdenialdate DATE,
  claimlastdenialdatemonth STRING,
  claimlastdenialdateyear INT64,
  claimlastinsurancepaymentdate DATE,
  claimlastinsurancepaymentdatemonth STRING,
  claimlastinsurancepaymentdateyear INT64,
  claimlastnote STRING,
  claimlastpatientpaymentdate DATE,
  claimlastpatientpaymentdatemonth STRING,
  claimlastpatientpaymentdateyear INT64,
  claimoriginalclaimnumber INT64,
  claimoriginalclaimnumbercurrentfilestatus STRING,
  claimowner STRING,
  claimremarkcodes STRING,
  claimvoidandrecreatedate DATE,
  claimzerobalance STRING,
  dateofservice DATE,
  dateofservicemonth STRING,
  dateofserviceyear INT64,
  facilityid INT64,
  facilityname STRING,
  facilityplaceofservicecode INT64,
  ins1insurancepayerfinancialclassname STRING,
  ins1insurancepayerfinancialclassnum STRING,
  ins1insurancepayergroupname STRING,
  ins1insurancepayerid INT64,
  ins1insurancepayername STRING,
  ins1insuredsubscribernumber STRING,
  ins1insuredsubscribergroupnumber STRING,
  ins1insurancepriorauthnumber STRING,
  ins2insurancepayerfinancialclassname STRING,
  ins2insurancepayerfinancialclassnum STRING,
  ins2insurancepayergroupname STRING,
  ins2insurancepayerid INT64,
  ins2insurancepayername STRING,
  ins2insuredsubscribernumber STRING,
  ins2insuredsubscribergroupnumber STRING,
  ins2insurancepriorauthnumber STRING,
  ins3insurancepayerfinancialclassname STRING,
  ins3insurancepayerfinancialclassnum STRING,
  ins3insurancepayergroupname STRING,
  ins3insurancepayerid INT64,
  ins3insurancepayername STRING,
  ins3insuredsubscribernumber STRING,
  ins3insuredsubscribergroupnumber STRING,
  liabilityownerfinancialclassname STRING,
  liabilityownerfinancialclassnum STRING,
  liabilityownergovernmentindicator STRING,
  liabilityownerid INT64,
  liabilityownerindicator STRING,
  liabilityownerinsuredsubscribernumber STRING,
  liabilityownerinsuredsubscribergroupnumber STRING,
  liabilityownerlastchangedate DATE,
  liabilityownerlastchangedatemonth STRING,
  liabilityownerlastchangedateyear INT64,
  liabilityownername STRING,
  liabilityownerpayergroupname STRING,
  liabilityownerrelayhealthcpid STRING NOT NULL,
  patientdeceased STRING,
  patientfirstname STRING,
  patientid INT64,
  patientlastname STRING,
  patientmiddlename STRING,
  patientsendstatements STRING,
  patientunidentified STRING,
  practicegroupnpi STRING,
  practiceid INT64,
  practicename STRING,
  practicesiteid STRING,
  practicestate STRING,
  practicetaxid STRING,
  referringproviderid INT64,
  referringprovidername STRING,
  referringproviderupin STRING,
  relayhealthedienrollmenterror STRING,
  relayhealthfirstreleasedate DATE,
  relayhealthfirstreleasedatemonth STRING,
  relayhealthfirstreleasedateyear INT64,
  relayhealthfirstreleasedateins1 DATE,
  relayhealthfirstreleasedateins1month STRING,
  relayhealthfirstreleasedateins1year INT64,
  relayhealthfirstreleasedateins2 DATE,
  relayhealthfirstreleasedateins2month STRING,
  relayhealthfirstreleasedateins2year INT64,
  relayhealthfirstsubmissiondate DATE,
  relayhealthfirstsubmissiondatemonth STRING,
  relayhealthfirstsubmissiondateyear INT64,
  relayhealthfirstsubmissiondateins1 DATE,
  relayhealthfirstsubmissiondateins1month STRING,
  relayhealthfirstsubmissiondateins1year INT64,
  relayhealthfirstsubmissiondateins2 DATE,
  relayhealthfirstsubmissiondateins2month STRING,
  relayhealthfirstsubmissiondateins2year INT64,
  relayhealthholdcode STRING,
  relayhealthholdstatus STRING,
  relayhealthlast277responsecategorycode STRING,
  relayhealthlast277responsecategorydescription STRING,
  relayhealthlast277responsedate DATE,
  relayhealthlast277responsedatemonth STRING,
  relayhealthlast277responsedateyear INT64,
  relayhealthlast277responsepayername STRING,
  relayhealthlastreleaseclaimstatus STRING,
  relayhealthlastreleaseclaimtype STRING,
  relayhealthlastreleasedate DATE,
  relayhealthlastreleasedatemonth STRING,
  relayhealthlastreleasedateyear INT64,
  relayhealthlastreleasedateins1 DATE,
  relayhealthlastreleasedateins1month STRING,
  relayhealthlastreleasedateins1year INT64,
  relayhealthlastreleasedateins2 DATE,
  relayhealthlastreleasedateins2month STRING,
  relayhealthlastreleasedateins2year INT64,
  relayhealthlastsubmissiondate DATE,
  relayhealthlastsubmissiondatemonth STRING,
  relayhealthlastsubmissiondateyear INT64,
  relayhealthlastsubmissiondateins1 DATE,
  relayhealthlastsubmissiondateins1month STRING,
  relayhealthlastsubmissiondateins1year INT64,
  relayhealthlastsubmissiondateins2 DATE,
  relayhealthlastsubmissiondateins2month STRING,
  relayhealthlastsubmissiondateins2year INT64,
  relayhealthreleasecount INT64 NOT NULL,
  relayhealthreleasecountins1 INT64 NOT NULL,
  relayhealthreleasecountins2 INT64 NOT NULL,
  relayhealthsubmissioncount INT64 NOT NULL,
  relayhealthsubmissioncountins1 INT64 NOT NULL,
  relayhealthsubmissioncountins2 INT64 NOT NULL,
  renderingproviderid INT64,
  renderingprovidername STRING,
  renderingprovidernpi STRING,
  renderingprovidersamestoreindicator STRING,
  renderingproviderspecialty STRING,
  renderingprovidersubspecialty STRING,
  renderingprovidertaxonomycode STRING,
  renderingproviderupin STRING,
  servicingproviderid INT64,
  servicingprovidername STRING,
  servicingprovidernpi STRING,
  servicingproviderspecialty STRING,
  servicingprovidersubspecialty STRING,
  servicingprovidertaxonomycode STRING,
  servicingproviderupin STRING,
  f_adjustmentsadministration NUMERIC(33, 4),
  f_adjustmentsbaddebt NUMERIC(33, 4),
  f_adjustmentscapitation NUMERIC(33, 4),
  f_adjustmentscharity NUMERIC(33, 4),
  f_adjustmentscontractual NUMERIC(33, 4),
  f_adjustmentsdenial NUMERIC(33, 4),
  f_adjustmentsescheat NUMERIC(33, 4),
  f_adjustmentsinterest NUMERIC(33, 4),
  f_adjustmentsnsf NUMERIC(33, 4),
  f_adjustmentsrefund NUMERIC(33, 4),
  f_adjustmentsuninsured NUMERIC(33, 4),
  f_balanceinsuranceliability NUMERIC(33, 4),
  f_balanceonhold NUMERIC(33, 4),
  f_balancepatientliability NUMERIC(33, 4),
  f_billcountins1 INT64,
  f_billcountins1withvoids INT64,
  f_billcountins2 INT64,
  f_billcountins2withvoids INT64,
  f_billcountins3 INT64,
  f_billcountins3withvoids INT64,
  f_claimcount INT64 NOT NULL,
  f_paymentsinsurance NUMERIC(33, 4),
  f_paymentspatient NUMERIC(33, 4),
  f_totaladjustments NUMERIC(33, 4),
  f_totalbalance NUMERIC(33, 4),
  f_totalcharges NUMERIC(33, 4),
  f_totalpayments NUMERIC(33, 4),
  artivapoolnumber STRING,
  artivapooldesc STRING,
  collectionstatuscodelastchangedate STRING,
  collectionstatuscode STRING,
  collectionstatusname STRING,
  facilityprimaryaddressline1 STRING,
  facilityprimaryaddressline2 STRING,
  geographycity STRING,
  statekey STRING,
  geographyzipcode STRING,
  dos_month STRING,
  dos_year INT64,
  dos_year_month STRING,
  renderingprovidertaxid STRING,
  artivaaccountliabilityid STRING,
  artivaproviderptan STRING,
  cactuseffectivedate DATE,
  poolexcludeflag STRING,
  excludedtimelyfilingflag STRING,
  donotadjustflag STRING,
  date_of_injury DATE,
  claimlastnotecreateddate DATE,
  claimlastnotecreateddatemonth STRING,
  claimlastnotecreateddateyear INT64,
  claimlastnotecreatedby STRING,
  claimfirstbilleddate DATE,
  claimfirstbilleddatemonth STRING,
  claimfirstbilleddateyear INT64,
  numberofpatientstatements INT64 NOT NULL,
  claiminsurancefirstpaymentdate DATE,
  claiminsurancefirstpaymentdatemonth STRING,
  claiminsurancefirstpaymentdateyear INT64,
  adjustmentslastcreatedate DATE,
  adjustmentslastcreatedatemonth STRING,
  adjustmentslastcreatedateyear INT64,
  ins1insurancepayorid STRING,
  ins1insurancefirstbilleddate DATE,
  ins1insurancelastbilleddate DATE,
  ins2insurancepayorid STRING,
  ins2insurancefirstbilleddate DATE,
  ins2insurancelastbilleddate DATE,
  claimlastbilledmessage STRING,
  claimlastbilledtopatientdate DATE,
  claimlastbilledtopatientdatemonth STRING,
  claimlastbilledtopatientdateyear INT64,
  last_ecw_batched_date DATE,
  claimagingbucketbyclaimfilestatuslastchangedate STRING,
  ins1insurancetotalpayments NUMERIC(33, 4),
  ins2insurancetotalpayments NUMERIC(33, 4),
  hospitalcoid STRING,
  hospitalname STRING,
  morprovidername STRING,
  providerstartdatekey DATE,
  providertermdatekey DATE,
  specialtycategory STRING,
  specialtycode STRING,
  specialtyname STRING,
  specialtytype STRING,
  coidprogramtype STRING,
  coidlargepractice STRING,
  provideroriginalstartstatus STRING,
  provideroriginalstartdate DATE,
  appspecialtycategory STRING,
  coidsublob STRING,
  gldeptnum STRING,
  centerdescription STRING,
  claimfirstbilledtopatientdate DATE,
  claimfirstbilledtoinsurancedate DATE,
  claimlastbilledtoinsurancedate DATE,
  numberofinsurancebills INT64 NOT NULL,
  firsterapayername STRING,
  firsterapayericn STRING,
  lasterapayername STRING,
  lasterapayericn STRING,
  firsteracarc STRING,
  lasteracarc STRING,
  patientkeeperclaim STRING,
  utfartivautftype STRING,
  utfartivautfqualifydate STRING,
  utfartivaprimaryinitialtimelydays NUMERIC(29, 0),
  utfartivasecondaryinitialtimelydays NUMERIC(29, 0),
  utfartivafirstlevelappealdays NUMERIC(29, 0),
  utfartivasecondlevelappealdays NUMERIC(29, 0),
  atriskflag STRING,
  artvaliabilitypoolstartdate DATETIME,
  artivadaysincurrentpool INT64,
  startminustoday INT64,
  artivappipekey STRING,
  artivappiedikey NUMERIC(29, 0),
  artivappipetype STRING,
  artivappieditype STRING,
  artivaholdcodeid STRING,
  artivaruleid NUMERIC(29, 0),
  utfinitialsubmissiondays STRING,
  utfinitialsubmissionagebucket STRING,
  utfappealtype STRING,
  utfappealdays STRING,
  utfappealagebucket STRING,
  utfresultstepno1 STRING,
  utfresultscategory1 STRING,
  utfcondition1 STRING,
  utfresultstepno2 STRING,
  utfresultscategory2 STRING,
  utfcondition2 STRING,
  f_claimbalancecashvalueamt NUMERIC(33, 4),
  artivapsenrelayguid STRING,
  servicingproviderkey INT64,
  renderingproviderkey INT64,
  paytoproviderkey INT64,
  supervisorproviderkey INT64,
  addprovider1providerkey INT64,
  addprovider2providerkey INT64,
  sourcepatientacctnumber STRING,
  crossoverclaimdate DATE,
  virtualvisitflag STRING,
  virtualvisittype STRING,
  patientlegacymrn STRING,
  artivaappealsentdate DATE,
  artivadocumentationsentdate DATE
)
;