CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factclaimlinecharge
(
  claimlinechargekey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  cptstartservicedatekey DATE NOT NULL,
  cptendservicedatekey DATE NOT NULL,
  cptposkey INT64 NOT NULL,
  cpttypeofservicekey INT64 NOT NULL,
  cptcharges NUMERIC(31, 2),
  cptchargesperunit NUMERIC(31, 2),
  cptunits NUMERIC(31, 2),
  cptallowed NUMERIC(31, 2),
  cptallowedperunit NUMERIC(31, 2),
  cptpatientportion NUMERIC(31, 2),
  cpttotalpatientportion NUMERIC(31, 2),
  cptnoncoveredcharges NUMERIC(31, 2),
  cptbalance NUMERIC(31, 2),
  cptcalculatedbalance NUMERIC(31, 2),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptbilltoins INT64,
  cptbilltopt INT64,
  cptdeleteflag INT64,
  cptorder INT64,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  icd1 STRING,
  icd2 STRING,
  icd3 STRING,
  icd4 STRING,
  cliaid STRING,
  ndccode STRING,
  ndcunits STRING,
  ndcunitprice NUMERIC(33, 4),
  ndcuom STRING,
  cptcode STRING,
  icdcode1 STRING,
  icdcode2 STRING,
  icdcode3 STRING,
  icdcode4 STRING,
  anesthesiastarttime DATETIME,
  anesthesiaendtime DATETIME,
  anesthesiaphysicalstatusunitsmod1 INT64,
  anesthesiaphysicalstatusunitsmod2 INT64,
  anesthesiaphysicalstatusunitsmod3 INT64,
  anesthesiaphysicalstatusunitsmod4 INT64,
  anesthesiatimeunits INT64,
  anesthesiabaseunitvalue INT64,
  anesthesiaoxminutes INT64,
  anesthesiacmscptunits NUMERIC(31, 2),
  anesthesiacmstimeunits NUMERIC(31, 2),
  anesthesiacmsbaseunitvalue NUMERIC(31, 2),
  anesthesiacmsbaseunitvalueoverrideflag INT64,
  arclaimflag INT64,
  archivedrecord STRING NOT NULL
)
;