CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_facteraserviceadjustment
(
  eraserviceadjustmentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  cas01 STRING,
  cas02 STRING,
  cas03 NUMERIC(33, 4),
  cas04 NUMERIC(29),
  cas05 STRING,
  cas06 NUMERIC(33, 4),
  cas07 NUMERIC(29),
  cas08 STRING,
  cas09 NUMERIC(33, 4),
  cas10 NUMERIC(29),
  cas11 STRING,
  cas12 NUMERIC(33, 4),
  cas13 NUMERIC(29),
  cas14 STRING,
  cas15 NUMERIC(33, 4),
  cas16 NUMERIC(29),
  cas17 STRING,
  cas18 NUMERIC(33, 4),
  cas19 NUMERIC(29),
  segment STRING,
  sourcefilename STRING,
  sourcefilecreateddate DATETIME NOT NULL,
  seq INT64,
  datecreated DATETIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deletedflag INT64,
  fullclaimnumber STRING,
  regionkey INT64
)
;