CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factsnapshottransactionfinancialadjustment
(
  transactionfinancialadjustmentkey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  regionkey INT64,
  coid STRING,
  gldepartment STRING,
  claimkey INT64,
  claimnumber INT64,
  patientkey INT64,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid INT64,
  renderingproviderkey INT64,
  renderingproviderid INT64,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  claimdatemonthid INT64,
  servicedatekey DATE,
  servicedatemonthid INT64,
  iplan1iplankey INT64,
  iplan1id INT64,
  financialclasskey INT64,
  transactionid INT64,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiondatemonthid INT64,
  adjustmentcodekey INT64,
  adjustmentcode STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  transactiontype STRING,
  adjustmentid INT64,
  transactionsamemonthflag STRING NOT NULL
)
;