CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factnhxs
(
  claimkey INT64 NOT NULL,
  patientkey INT64 NOT NULL,
  guarantorpatientkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  cptcodekey INT64,
  cptunits NUMERIC(33, 4),
  cptmodifiers STRING,
  ecwiplan STRING,
  ecwiplanname STRING,
  nhxsclaimsubscriberid STRING,
  nhxspayerpatientid STRING,
  nhxsclaimid STRING,
  nhxsclaimnumber STRING,
  nhxspayor STRING,
  nhxsrenderingprovidernpi STRING,
  nhxspatientaccountnumber STRING,
  nhxsservicefromdate DATE,
  nhxsservicetodate DATE,
  nhxsprocedurecode STRING,
  nhxsmodifiercodes STRING,
  nhxsunittype STRING,
  nhxspayerallowedamount NUMERIC(33, 4),
  nhxspaymentamount NUMERIC(33, 4),
  nhxseobpayername STRING,
  nhxspayerclaimreceiveddate DATE,
  nhxseobpaymentdate DATE,
  nhxsproducttype STRING,
  nhxsreasoncodes STRING,
  nhxsreasoncodegroups STRING,
  nhxsremarkcodes STRING,
  nhxsheaderremarkcodes STRING,
  nhxsfeescheduleamount NUMERIC(33, 4),
  nhxsmedicareallowedamount NUMERIC(33, 4),
  nhxsallowedamount NUMERIC(33, 4),
  nhxsvariance NUMERIC(33, 4),
  nhxslatepaymentinterest NUMERIC(33, 4),
  nhxsaudittype STRING,
  nhxsnotauditabletype STRING,
  nhxscodingalerttype STRING,
  nhxseordate DATE,
  nhxsappealprintstatus STRING,
  nhxsprintdate STRING,
  nhxspayerclaimnumber STRING,
  nhxsclaimlineid STRING,
  nhxstag STRING,
  nhxsbillingprovidername STRING,
  nhxsclaimpayer STRING,
  nhxsfeeschedulenumber STRING,
  nhxsmedicarelocality STRING,
  nhxspatientresponsibilityamount NUMERIC(33, 4),
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  nhxskey INT64 NOT NULL
)
;