CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_factclaimpayment
(
  claimpaymentkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  encounterkey INT64 NOT NULL,
  iplankey INT64 NOT NULL,
  patientkey INT64 NOT NULL,
  paymenttypekey INT64 NOT NULL,
  contractualadjustmentamt NUMERIC(33, 4) NOT NULL,
  allowedamt NUMERIC(33, 4) NOT NULL,
  coinsuranceamt NUMERIC(33, 4) NOT NULL,
  memberbalanceamt NUMERIC(33, 4) NOT NULL,
  paymentamt NUMERIC(33, 4) NOT NULL,
  deductibleamt NUMERIC(33, 4) NOT NULL,
  withheldamt NUMERIC(33, 4) NOT NULL,
  msgcode STRING,
  createddatekey DATE NOT NULL,
  createdtime TIME,
  modifieddatekey DATE NOT NULL,
  modifiedtime TIME,
  checkamt NUMERIC(33, 4),
  checknumber STRING,
  checktypedesc STRING,
  posteddatekey DATE NOT NULL,
  checkdatekey DATE NOT NULL,
  eomb1 STRING,
  memo STRING,
  depositdatekey DATE NOT NULL,
  paymentfacilitykey INT64 NOT NULL,
  unpostedamt NUMERIC(33, 4),
  batchkey INT64 NOT NULL,
  deletedflag INT64 NOT NULL,
  eradetailid INT64,
  eraflag INT64,
  erafileid INT64,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  paymentlock INT64,
  paymentmodifieddatekey DATE,
  eraclaimstatusclp02 INT64,
  transactionnumber STRING,
  erapayeridentifier STRING,
  erapayername STRING,
  icn STRING,
  paymentassociatedtoclaimiplankey INT64,
  cmtbbatchid STRING,
  eboctreasurybatchnumber STRING,
  eboctreasurybatchcreatedby STRING,
  archivedrecord STRING NOT NULL
)
;