CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_juncclaimlinechargefirstlastkeymeasure
(
  claimlinechargekey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  lastclaimkey INT64,
  lastclaimnumber INT64,
  claimnumber INT64 NOT NULL,
  lastvoiddatekey DATE,
  coid STRING NOT NULL,
  regionkey INT64 NOT NULL,
  arclaimflag INT64 NOT NULL,
  claimvoidflag INT64 NOT NULL,
  claimdeleteflag INT64 NOT NULL,
  claimtotalbalanceamt NUMERIC(33, 4) NOT NULL,
  claimtotalchargesamt NUMERIC(33, 4) NOT NULL,
  cptcode STRING,
  cptcodekey INT64 NOT NULL,
  cptdeleteflag INT64 NOT NULL,
  cptorder INT64 NOT NULL,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  sourceaprimarykeyvalue INT64 NOT NULL,
  cptcharges NUMERIC(33, 4) NOT NULL,
  paymentamt NUMERIC(33, 4) NOT NULL,
  adjustmentamt NUMERIC(33, 4) NOT NULL,
  calculatedlinebalance NUMERIC(33, 4) NOT NULL,
  calculatedlinebalanceadjusted NUMERIC(33, 4) NOT NULL,
  financialadjustmentsamt NUMERIC(33, 4) NOT NULL,
  firstfinancialadjustmentnonzerosumdatekey DATE,
  lastfinancialadjustmentnonzerosumdatekey DATE,
  adjustmentrefundamt NUMERIC(33, 4) NOT NULL,
  firstadjrefundnonzerosumdatekey DATE,
  lastadjrefundnonzerosumdatekey DATE,
  adjustmentdenialamt NUMERIC(33, 4) NOT NULL,
  firstadjdenialnonzerosumdatekey DATE,
  lastadjdenialnonzerosumdatekey DATE,
  adjustmentbaddebtamt NUMERIC(33, 4) NOT NULL,
  firstadjbaddebtnonzerosumdatekey DATE,
  lastadjbaddebtnonzerosumdatekey DATE,
  adjustmentcharityamt NUMERIC(33, 4) NOT NULL,
  firstadjcharitynonzerosumdatekey DATE,
  lastadjcharitynonzerosumdatekey DATE,
  adjustmentuninsuredamt NUMERIC(33, 4) NOT NULL,
  firstadjuninsureddiscountnonzerosumdatekey DATE,
  lastadjuninsureddiscountnonzerosumdatekey DATE,
  adjustmentadministrationamt NUMERIC(33, 4) NOT NULL,
  firstadjadministrationnonzerosumdatekey DATE,
  lastadjadministrationnonzerosumdatekey DATE,
  adjustmentnsfamt NUMERIC(33, 4) NOT NULL,
  firstadjnsfnonzerosumdatekey DATE,
  lastadjnsfnonzerosumdatekey DATE,
  adjustmentescheatamt NUMERIC(33, 4) NOT NULL,
  firstadjescheatnonzerosumdatekey DATE,
  lastadjescheatnonzerosumdatekey DATE,
  adjustmentinterestamt NUMERIC(33, 4) NOT NULL,
  firstadjinterestnonzerosumdatekey DATE,
  lastadjinterestnonzerosumdatekey DATE,
  adjustmentcontractualamt NUMERIC(33, 4) NOT NULL,
  firstadjcontractualnonzerosumdatekey DATE,
  lastadjcontractualnonzerosumdatekey DATE,
  paymentcontracualadjustmentsamt NUMERIC(33, 4) NOT NULL,
  firstpaymentcontractualadjdatekey DATE,
  lastpaymentcontractualadjdatekey DATE,
  adjustmentotheramt NUMERIC(33, 4) NOT NULL,
  firstadjothernonzerosumdatekey DATE,
  lastadjothernonzerosumdatekey DATE,
  patientpaymentamt NUMERIC(33, 4) NOT NULL,
  insurancepaymentamt NUMERIC(33, 4) NOT NULL,
  maxallowedamt NUMERIC(33, 4) NOT NULL,
  firstinsuranceclaimpaymentdatekey DATE,
  lastinsuranceclaimpaymentdatekey DATE,
  firstinsuranceclaimlinepaymentcreateddatekey DATE,
  lastinsuranceclaimlinepaymentcreateddatekey DATE,
  firstpatientclaimpaymentdatekey DATE,
  lastpatientclaimpaymentdatekey DATE,
  firstpatientclaimlinepaymentcreateddatekey DATE,
  lastpatientclaimlinepaymentcreateddatekey DATE,
  initialdeniedchargesamt NUMERIC(33, 4) NOT NULL,
  firstdenialeradatekey DATE,
  firstdenialcarcrarccode STRING,
  firstdenialcarccodes STRING,
  firstdenialrarccodes STRING,
  firstdenialpayername STRING,
  firstdenialcarcrarctype STRING,
  firstdenialcarcisdenial STRING,
  firstdenialcarcrequiresrarc STRING,
  firstdenialrarcisdenial STRING,
  firstdenialcategory STRING,
  lastdenialeradatekey DATE,
  lastdenialcarcrarccode STRING,
  lastdenialcarccodes STRING,
  lastdenialrarccodes STRING,
  lastdenialpayername STRING,
  lastdenialcarcrarctype STRING,
  lastdenialcarcisdenial STRING,
  lastdenialcarcrequiresrarc STRING,
  lastdenialrarcisdenial STRING,
  lastdenialcategory STRING,
  firsteracarcrarccode STRING,
  firsteradatekey DATE,
  firsteracarccodes STRING,
  firsterararccodes STRING,
  firsterapayername STRING,
  firsteracategory STRING,
  firsteracarcrarctype STRING,
  firsteracarcisdenial STRING,
  firsteracarcrequiresrarc STRING,
  firsterararcisdenial STRING,
  deniallinecount INT64 NOT NULL,
  lasteracarcrarccode STRING,
  lasteradatekey DATE,
  lasteracarccodes STRING,
  lasterararccodes STRING,
  lasterapayername STRING,
  deniallasteradatekey DATE,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  firstinitialdenialflag INT64 NOT NULL,
  firstinsuranceclaimlinepaymentnonzerosumposteddatekey DATE,
  firstpatientclaimlinepaymentnonzerosumposteddatekey DATE,
  firstpaymentcontractualadjnonzerosumposteddatekey DATE,
  lasteracategory STRING,
  lasteracarcrarctype STRING,
  lasteracarcisdenial STRING,
  lasteracarcrequiresrarc STRING,
  lasterararcisdenial STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  secondtolastdenialeradatekey DATE,
  secondtolastdenialcarcrarccode STRING,
  secondtolastdenialcarccodes STRING,
  secondtolastdenialrarccodes STRING,
  secondtolastdenialpayername STRING,
  secondtolastdenialcarcrarctype STRING,
  secondtolastdenialcarcisdenial STRING,
  secondtolastdenialcarcrequiresrarc STRING,
  secondtolastdenialcategory STRING,
  secondtolastdenialrarcisdenial STRING,
  thirdtolastdenialeradatekey DATE,
  thirdtolastdenialcarcrarccode STRING,
  thirdtolastdenialcarccodes STRING,
  thirdtolastdenialrarccodes STRING,
  thirdtolastdenialpayername STRING,
  thirdtolastdenialcarcrarctype STRING,
  thirdtolastdenialcarcisdenial STRING,
  thirdtolastdenialcarcrequiresrarc STRING,
  thirdtolastdenialcategory STRING,
  thirdtolastdenialrarcisdenial STRING,
  fourthtolastdenialeradatekey DATE,
  fourthtolastdenialcarcrarccode STRING,
  fourthtolastdenialcarccodes STRING,
  fourthtolastdenialrarccodes STRING,
  fourthtolastdenialpayername STRING,
  fourthtolastdenialcarcrarctype STRING,
  fourthtolastdenialcarcisdenial STRING,
  fourthtolastdenialcarcrequiresrarc STRING,
  fourthtolastdenialcategory STRING,
  fourthtolastdenialrarcisdenial STRING,
  secondtolasteradatekey DATE,
  secondtolasteracarccodes STRING,
  secondtolasterararccodes STRING,
  secondtolasterapayername STRING,
  thirdtolasteradatekey DATE,
  thirdtolasteracarccodes STRING,
  thirdtolasterararccodes STRING,
  thirdtolasterapayername STRING,
  fourthtolasteradatekey DATE,
  fourthtolasteracarccodes STRING,
  fourthtolasterararccodes STRING,
  fourthtolasterapayername STRING,
  linebalancecashvalueamt NUMERIC(33, 4),
  firstprocesseddatekey DATE,
  firstchargevaluekey INT64,
  lastprocesseddatekey DATE,
  lastchargevaluekey INT64,
  primaryfirstallowedamount NUMERIC(33, 4),
  initialiplankey INT64,
  primaryeraallowedamt NUMERIC(33, 4),
  primaryerainsurancecontractualamt NUMERIC(33, 4),
  primaryerapatientresponsibilityamt NUMERIC(33, 4),
  primaryerapaymentadjustmentamt NUMERIC(33, 4),
  primaryerapaymentamt NUMERIC(33, 4),
  primaryeraposteddate DATE,
  primaryeraclaimstatus STRING,
  secondaryeraallowedamt NUMERIC(33, 4),
  secondaryerainsurancecontractualamt NUMERIC(33, 4),
  secondaryerapatientresponsibilityamt NUMERIC(33, 4),
  secondaryerapaymentadjustmentamt NUMERIC(33, 4),
  secondaryerapaymentamt NUMERIC(33, 4),
  secondaryeraposteddate DATE,
  secondaryeraclaimstatus STRING,
  archivedrecord STRING NOT NULL
)
;