CREATE TABLE IF NOT EXISTS edwpsc_staging.ecw_refdate
(
  datekey DATE NOT NULL,
  weekid INT64,
  weeknum INT64,
  weekdayflag INT64,
  weekofmonth INT64,
  weekenddate INT64,
  weekendflag INT64,
  weekdaysleft INT64,
  monthid INT64,
  monthiddescs STRING,
  monthiddescl STRING,
  monthnum INT64,
  monthnumdescs STRING,
  monthnumdescl STRING,
  monthdaysleft INT64,
  qtrid INT64,
  qtrdesc STRING,
  qtrnum INT64,
  qtrnumdescs STRING,
  qtrnumdescl STRING,
  semiannualid INT64,
  semiannualdesc STRING,
  yearid INT64,
  dayofweek INT64,
  dowdescs STRING,
  dowdescl STRING,
  dayofmonth INT64,
  dayofqtr INT64,
  dayofyear INT64,
  daysinweek INT64,
  daysinmonth INT64,
  daysinqtr INT64,
  daysinyear INT64,
  qtrdaysleft INT64,
  yeardaysleft INT64,
  bankdayflag INT64,
  federalbankholidayflag INT64,
  hcaholidayflag INT64,
  pedate DATE,
  pedatepriormonth DATE,
  qtrdescdss STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  weekinmonth INT64,
  weekinyear INT64,
  bankdays INT64,
  endofmonth DATE,
  cbobusinessdays INT64,
  pcweekdesc STRING,
  pcmonthid DATE,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (datekey) NOT ENFORCED
)
;