CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_refpractice
(
  practicekey INT64 NOT NULL,
  practicename STRING,
  practiceabbr STRING,
  practicespecialty STRING,
  practicerevlocid STRING,
  practicegroup INT64,
  practiceglprefix STRING,
  practiceadtparentid STRING,
  practiceservareaid STRING,
  practiceserviceareakey INT64,
  practicespecialtydept STRING,
  practicecenter STRING,
  practiceactiveflag STRING,
  practiceexternalname STRING,
  practicephone STRING,
  practicefax STRING,
  practicefacility STRING,
  practiceaddress1 STRING,
  practiceaddress2 STRING,
  practicecity STRING,
  practicestate STRING,
  practicezip STRING,
  practiceemergencyphone STRING,
  departmentid STRING,
  regionkey INT64,
  sourceaprimarykey STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  practiceprimarygeographykey INT64,
  practicefederaltaxid STRING,
  practicegroupnpi STRING,
  internaldepartmentid NUMERIC(29),
  PRIMARY KEY (practicekey) NOT ENFORCED
)
;