CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factclaim_history
(
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  coid STRING,
  regionkey INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  patientkey INT64,
  guarantorpatientkey INT64,
  servicingproviderkey INT64,
  renderingproviderkey INT64,
  paytoproviderkey INT64,
  supervisorproviderkey INT64,
  addprovider1providerkey INT64,
  addprovider2providerkey INT64,
  liabilitydatekey DATE,
  liabilityiplankey INT64,
  billedtoid STRING,
  billedtotype INT64,
  facilitykey INT64,
  claimstatuskey INT64,
  encounterkey INT64,
  encounterid INT64,
  encounterform STRING,
  visitnumber INT64,
  accountid INT64 NOT NULL,
  totalchargesamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalpatientbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  totalpatientbalanceminuspatientiplansamt NUMERIC(33, 4),
  totalpaymentsamt NUMERIC(33, 4),
  totalinsurancepaymentsamt NUMERIC(33, 4),
  totalpatientpaymentsamt NUMERIC(33, 4),
  totaladjustmentsamt NUMERIC(33, 4),
  totaluncoveredamt NUMERIC(33, 4),
  totalallowedamt NUMERIC(33, 4),
  totalpatientresponsibilityamt NUMERIC(33, 4),
  totalestimatedpatientbalanceamt NUMERIC(33, 4),
  totalpaymentsandadjustmentsamt NUMERIC(33, 4),
  voidflag INT64,
  deleteflag INT64,
  coidconfigurationkey INT64,
  claimcreatedbyuserkey INT64,
  claimqueueid INT64,
  referringproviderkey INT64,
  referringproviderid STRING,
  referringprovidertype STRING,
  copay NUMERIC(33, 4),
  arclaimflag INT64,
  voidedclaimreversedclaimnumber INT64,
  voidedclaimcopyclaimnumber INT64,
  voidedclaimoriginalclaimnumber INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourceachangedflag INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  claimlock STRING,
  claimtypeflag STRING,
  accidentindflag STRING,
  accidentstate STRING,
  accidenthour STRING,
  accidentrel STRING,
  symindflag STRING,
  symdatekey DATE,
  emprelated STRING,
  admitdatekey DATE,
  dischargedatekey DATE,
  splpgmid STRING,
  epsdtreferral STRING,
  epsdtrefsts STRING,
  crimerelatedflag STRING,
  docsentdatekey DATE,
  pwk06 STRING,
  pregindctorflag STRING,
  relinfodatekey DATE,
  relinfoind STRING,
  labchargesamt NUMERIC(33, 4),
  labindflag STRING,
  patientid STRING,
  patientinternalid INT64,
  servicingproviderid STRING,
  renderingproviderid STRING,
  paytoproviderid STRING,
  supervisorproviderid STRING,
  addprovider1providerid STRING,
  addprovider2providerid STRING,
  facilityid INT64,
  practiceid STRING,
  claimcreatedbyid STRING,
  deptcode STRING,
  payer1iplankey INT64,
  payer1iplanid INT64,
  payer1financialclasskey INT64,
  payer2iplankey INT64,
  payer2iplanid INT64,
  payer2financialclasskey INT64,
  payer3iplankey INT64,
  payer3iplanid INT64,
  payer3financialclasskey INT64,
  collectionstatus STRING,
  collectioncodechangedate STRING,
  collectioncode STRING,
  collectioncodechangedatedate DATE,
  collectionstatusaging INT64,
  serviceareakey INT64,
  billareakey INT64,
  claimbilledflag INT64,
  sourcebprimarykeyvalue STRING,
  holdcode STRING,
  payer1epicfinancialclass INT64,
  payer1epicfinancialclassdesc STRING,
  sourcecprimarykeyvalue STRING,
  totalholdbalanceamt NUMERIC(33, 4),
  prearflag INT64,
  totalprearbalanceamt NUMERIC(33, 4),
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL
)
;