CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factencountercptrouter
(
  encountercptrouterkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  visitnumber INT64,
  encounterkey INT64,
  encounterid INT64,
  patientinternalid INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptunits NUMERIC(31, 2),
  servicedatekey DATE,
  createdbyuserkey INT64,
  createddatetime DATETIME,
  createdbyusercomments STRING,
  chargefileddatetime DATETIME,
  accountid INT64,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  billingproviderkey INT64,
  billingproviderid STRING,
  patientkey INT64,
  patientid STRING,
  practicekey INT64,
  practiceid STRING,
  serviceareakey INT64,
  serviceareaid INT64,
  triggereddatekey DATE,
  hospitalaccountid INT64,
  sourceaprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;