CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factclaimfinancialadjustment
(
  claimfinancialadjustmentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  claimlineliabilityiplankey INT64,
  facilitykey INT64 NOT NULL,
  adjustmentcodekey INT64 NOT NULL,
  adjcode STRING,
  adjustmentcategorykey INT64,
  adjustmentamt NUMERIC(33, 4) NOT NULL,
  adjustmentdatekey DATE NOT NULL,
  unpostedtocptamt NUMERIC(33, 4) NOT NULL,
  unpostedamt NUMERIC(33, 4) NOT NULL,
  modifieddatekey DATE,
  modifiedtime TIME,
  createdbyuserkey INT64 NOT NULL,
  createddatekey DATE,
  deleteflag INT64 NOT NULL,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  iplankey INT64,
  PRIMARY KEY (claimfinancialadjustmentkey) NOT ENFORCED
)
;