CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factallclaimscube
(
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  claimadjustmentsgreaterthantotalcharges STRING,
  claimagebyclaimfilestatuslastchangedate INT64,
  claimagebydateofservice INT64,
  claimagebylastbilleddate INT64,
  claimagebylastliabilityownerchangedate INT64,
  claimagebylastpaymentdate INT64,
  claimagebylastpaymentoradjustmentdate INT64,
  claimagebyvoidandrecreatedate INT64,
  claimagingbucketbydateofservice STRING,
  claimagingbucketbydateofservicesortorder INT64,
  claimagingbucketbylastliabilityownerchangedate STRING,
  claimagingbucketbylastliabilityownerchangedatesortorder INT64,
  claimagingbucketbylastpaymentoradjustmentdate STRING,
  claimagingbucketbylastpaymentoradjustmentdatesortorder INT64,
  claimbalancebucket STRING,
  claimbalancebucketsortorder INT64,
  claimbalancepercentadjudicated STRING,
  claimcreditbalance STRING,
  claimdate DATE,
  claimfilestatusid STRING,
  claimfilestatuslastchangedate DATE,
  claimfilestatusname STRING,
  claimlastbilledcategory STRING,
  claimlastbilleddate DATE,
  claimlastinsurancepaymentdate DATE,
  claimlastnote STRING,
  claimlastpatientpaymentdate DATE,
  claimoriginalclaimnumber INT64,
  claimowner STRING,
  claimvoidandrecreatedate DATE,
  claimzerobalance STRING,
  claimrebilled STRING,
  claimbilled STRING,
  claimtype STRING,
  dateofservice DATE,
  facilityid STRING,
  facilityname STRING,
  facilityplaceofservicecode INT64,
  ins1insurancepayerfinancialclassname STRING,
  ins1insurancepayerfinancialclassnum STRING,
  ins1insurancepayerepicfinancialclassname STRING,
  ins1insurancepayerepicfinancialclassnum STRING,
  ins1insurancepayergroupname STRING,
  ins1insurancepayerid STRING,
  ins1insurancepayername STRING,
  ins1insuredsubscribernumber STRING,
  ins1insuredsubscribergroupnumber STRING,
  ins2insurancepayerfinancialclassname STRING,
  ins2insurancepayerfinancialclassnum STRING,
  ins2insurancepayerepicfinancialclassname STRING,
  ins2insurancepayerepicfinancialclassnum STRING,
  ins2insurancepayergroupname STRING,
  ins2insurancepayerid STRING,
  ins2insurancepayername STRING,
  ins2insuredsubscribernumber STRING,
  ins2insuredsubscribergroupnumber STRING,
  ins3insurancepayerfinancialclassname STRING,
  ins3insurancepayerfinancialclassnum STRING,
  ins3insurancepayerepicfinancialclassname STRING,
  ins3insurancepayerepicfinancialclassnum STRING,
  ins3insurancepayergroupname STRING,
  ins3insurancepayerid STRING,
  ins3insurancepayername STRING,
  ins3insuredsubscribernumber STRING,
  ins3insuredsubscribergroupnumber STRING,
  liabilityownerfinancialclassname STRING,
  liabilityownerfinancialclassnum STRING,
  liabilityownerepicfinancialclassname STRING,
  liabilityownerepicfinancialclassnum STRING,
  liabilityownergovernmentindicator STRING,
  liabilityownerid STRING,
  liabilityownerindicator STRING,
  liabilityownerinsuredsubscribernumber STRING,
  liabilityownerinsuredsubscribergroupnumber STRING,
  liabilityownerlastchangedate DATE,
  liabilityownername STRING,
  liabilityownerpayergroupname STRING,
  patientdeceased STRING,
  patientfirstname STRING,
  patientid INT64,
  patientepicinternalid INT64,
  patientmrn STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  patientsendstatements STRING,
  patientunidentified STRING,
  practicegroupnpi STRING,
  practiceid STRING,
  practicename STRING,
  practicestate STRING,
  practicetaxid STRING,
  referringproviderid STRING,
  referringprovidername STRING,
  referringproviderupin STRING,
  servicingproviderid STRING,
  servicingprovidername STRING,
  servicingprovidernpi STRING,
  servicingproviderspecialty STRING,
  servicingprovidersubspecialty STRING,
  servicingprovidertaxonomycode STRING,
  servicingproviderupin STRING,
  gldeptnum STRING,
  ins1insurancetotalpayments NUMERIC(33, 4),
  ins2insurancetotalpayments NUMERIC(33, 4),
  ins1insurancefirstbilleddate DATE,
  ins1insurancelastbilleddate DATE,
  ins2insurancefirstbilleddate DATE,
  ins2insurancelastbilleddate DATE,
  adjustmentsadministration NUMERIC(33, 4),
  adjustmentsbaddebt NUMERIC(33, 4),
  adjustmentscapitation NUMERIC(33, 4),
  adjustmentscharity NUMERIC(33, 4),
  adjustmentscontractual NUMERIC(33, 4),
  adjustmentsdenial NUMERIC(33, 4),
  adjustmentsescheat NUMERIC(33, 4),
  adjustmentsinterest NUMERIC(33, 4),
  adjustmentsnsf NUMERIC(33, 4),
  adjustmentsrefund NUMERIC(33, 4),
  adjustmentsuninsured NUMERIC(33, 4),
  balanceinsuranceliability NUMERIC(33, 4),
  balancepatientliability NUMERIC(33, 4),
  billcountins1 INT64,
  billcountins1withvoids INT64,
  billcountins2 INT64,
  billcountins2withvoids INT64,
  billcountins3 INT64,
  billcountins3withvoids INT64,
  claimcount INT64 NOT NULL,
  paymentsinsurance NUMERIC(33, 4),
  paymentspatient NUMERIC(33, 4),
  totaladjustments NUMERIC(33, 4),
  totalbalance NUMERIC(33, 4),
  totalcharges NUMERIC(33, 4),
  totalpayments NUMERIC(33, 4),
  collectioncode STRING,
  collectioncodechangedate DATE,
  diagnosiscode1 STRING,
  diagnosiscode2 STRING,
  holdcode STRING,
  PRIMARY KEY (claimkey) NOT ENFORCED
)
;