CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_reffacility
(
  facilitykey INT64 NOT NULL,
  facilityprimarygeographykey INT64,
  practicekey INT64,
  poskey INT64 NOT NULL,
  facilitybillinggeographykey INT64,
  facilityname STRING NOT NULL,
  facilitytype STRING,
  facilityprimaryaddressline1 STRING,
  facilityprimaryaddressline2 STRING,
  facilitytelephone STRING,
  facilityfax STRING,
  facilityemail STRING,
  facilitybillingaddressline1 STRING,
  facilitybillingaddressline2 STRING,
  facilitybillingtelephone STRING,
  facilitybillingfax STRING,
  facilitybillingemail STRING,
  facilitypracticetype STRING,
  facilitypracticeoption STRING,
  facilitypayableto STRING,
  facilitybankaccount STRING,
  facilityfederaltaxid STRING,
  facilitynotes STRING,
  facilityprimaryfacility INT64,
  facilitycliaid STRING,
  facilitycode STRING,
  facilitymammocertid STRING,
  facilityhpsaflag INT64,
  facilityhpsamodifier STRING,
  facilityvmid STRING,
  facilityhl7id STRING,
  facilitycolor INT64,
  facilityfeeschedule INT64,
  facilityidtype INT64,
  facilityptstmtfacoption INT64,
  facilityptstmtfacid INT64,
  facilityrestrictprintappts INT64,
  facilitynpi STRING,
  facilityimmstateid STRING,
  facilitytaxonomycode STRING,
  facilityrestrictprintstmts INT64,
  facilitystartedon DATETIME,
  facilitymerchantid STRING,
  facilityrevenuecode STRING,
  facilitypercent NUMERIC(32, 3),
  facilityoverridesalestax INT64,
  facilityimmlocationid STRING,
  facilitytimezonecode STRING,
  facilitymesscallerid STRING,
  facilitymessopernum STRING,
  facilitycreditcardoption STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (facilitykey) NOT ENFORCED
)
;