CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factclaimlinecharge
(
  claimlinechargekey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  facilitykey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptorder INT64,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cptposkey INT64,
  cpttypeofservicekey INT64,
  cptcharges NUMERIC(31, 2),
  cptchargesperunit NUMERIC(31, 2),
  cptunits NUMERIC(31, 2),
  cptallowed NUMERIC(31, 2),
  cptallowedperunit NUMERIC(31, 2),
  cptpatientportion NUMERIC(31, 2),
  cpttotalpatientportion NUMERIC(31, 2),
  cptnoncoveredcharges NUMERIC(31, 2),
  cptbalance NUMERIC(31, 2),
  cptcalculatedbalance NUMERIC(31, 2),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptbilltoins INT64,
  cptbilltopt INT64,
  icd1 STRING,
  icd2 STRING,
  icd3 STRING,
  icd4 STRING,
  cliaid STRING,
  ndccode STRING,
  ndcunits STRING,
  ndcunitprice NUMERIC(33, 4),
  ndcuom STRING,
  cptdeleteflag INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  etrid NUMERIC(29),
  PRIMARY KEY (claimlinechargekey) NOT ENFORCED
)
;