CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factencounteranesthesianote
(
  anesthesianotekey INT64 NOT NULL,
  anesthesiakey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  notetypecode STRING,
  notetypeabbreviation STRING,
  notetypename STRING,
  notereason STRING,
  noteproviderid INT64,
  noteproviderkey INT64,
  noteprovidername STRING,
  noteuserid INT64,
  noteuserkey INT64,
  noteusername STRING,
  patientid INT64,
  patientkey INT64,
  notecreatedatetime DATETIME,
  noteupdatedatetime DATETIME,
  notesignedflag INT64,
  notesigneddatetime DATETIME,
  encounterid INT64,
  encounterkey INT64,
  noteservicedatekey DATE,
  notewritersavedflag INT64,
  archivednoteflag INT64,
  notedeleteflag INT64,
  notedeletedatetime DATETIME,
  notedeleteuserid INT64,
  notedeleteuserkey INT64,
  notedeleteusername STRING,
  sourceaprimarykeyvalue INT64,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;