CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_juncclaimfirstlastkeymeasure
(
  claimkey INT64 NOT NULL,
  claimnumber INT64,
  coid STRING NOT NULL,
  visitnumber INT64,
  firstbillkey INT64,
  firstbilldatekey DATE,
  lastbillkey INT64,
  lastbilldatekey DATE,
  numberofbills INT64,
  firstpatientstatementbillkey INT64,
  firstpatientstatementbilldatekey DATE,
  lastpatientstatementbillkey INT64,
  lastpatientstatementbilldatekey DATE,
  numberofpatientstatements INT64,
  firstinsurancebillkey INT64,
  firstinsurancebilldatekey DATE,
  lastinsurancebillkey INT64,
  lastinsurancebilldatekey DATE,
  numberofinsurancebills INT64,
  firstinsuranceclaimpaymentkey INT64,
  firstinsuranceclaimpaymentdatekey DATE,
  lastinsuranceclaimpaymentkey INT64,
  lastinsuranceclaimpaymentdatekey DATE,
  totalinsuranceclaimpaymentamt NUMERIC(33, 4),
  firstpatientclaimpaymentkey INT64,
  firstpatientclaimpaymentdatekey DATE,
  lastpatientclaimpaymentkey INT64,
  lastpatientclaimpaymentdatekey DATE,
  totalpatientclaimpaymentamt NUMERIC(33, 4),
  lastclaimnotehistorykey INT64,
  lastclaimnote STRING,
  lastclaimnotecreatedbyuserkey INT64,
  lastclaimnotecreateddatekey DATE,
  lastclaimnotecreatedtime TIME,
  lastclaimstatusupdateddatekey DATE,
  lastclaimstatusupdatedkey INT64,
  lastclaimstatushistorychangedbyuserkey INT64,
  liabilityownertype INT64,
  lastpaymentcontractualadjustmentsdatekey DATE,
  lastadjustmentsdatekey DATE,
  totaladjustmentsrefundsamt NUMERIC(33, 4),
  totaladjustmentsdenialsamt NUMERIC(33, 4),
  totaladjustmentsbaddebtamt NUMERIC(33, 4),
  totaladjustmentscharityamt NUMERIC(33, 4),
  totaladjustmentsuninsuredamt NUMERIC(33, 4),
  totaladjustmentsadministrationamt NUMERIC(33, 4),
  totaladjustmentsnsfamt NUMERIC(33, 4),
  totaladjustmentsescheatamt NUMERIC(33, 4),
  totaladjustmentsinterestamt NUMERIC(33, 4),
  totaladjustmentscontractualamt NUMERIC(33, 4),
  totalpaymentcontracualadjustmentsamt NUMERIC(33, 4),
  totalfinancialadjustmentsamt NUMERIC(33, 4),
  claimdatekey DATE,
  servicedatekey DATE,
  liabilitydatekey DATE,
  liabilitylastbilledclaimdatekey DATE,
  lastbilltypekey INT64,
  unbilledstatuskey INT64,
  arclaimflag INT64,
  rhprimarymaxsubmissiondatekey DATE,
  rhprimaryminsubmissiondatekey DATE,
  rhprimarymaxreleasedatekey DATE,
  rhprimaryminreleasedatekey DATE,
  rhprimarysubmissioncount INT64,
  rhprimaryreleasecount INT64,
  rhsecondarymaxsubmissiondatekey DATE,
  rhsecondaryminsubmissiondatekey DATE,
  rhsecondarymaxreleasedatekey DATE,
  rhsecondaryminreleasedatekey DATE,
  rhsecondarysubmissioncount INT64,
  rhsecondaryreleasecount INT64,
  rhminreleasedatekey DATE,
  rhmaxreleasedatekey DATE,
  rhminsubmissiondatekey DATE,
  rhmaxsubmissiondatekey DATE,
  rhsubmissioncount INT64,
  rhreleasecount INT64,
  lastrh1201billclaimstatuskey STRING,
  lastrh1201releasestatuskey STRING,
  lastrh1201holdcode STRING,
  lastrh1201holdcodeprefixkey STRING,
  primaryiplankey INT64,
  liabilityiplankey INT64,
  secondaryiplankey INT64,
  tertiaryiplankey INT64,
  cpt1cptcodekey INT64,
  cpt2cptcodekey INT64,
  cpt3cptcodekey INT64,
  cpt4cptcodekey INT64,
  cpt5cptcodekey INT64,
  diag1diagnosiscodekey INT64,
  diag2diagnosiscodekey INT64,
  diag3diagnosiscodekey INT64,
  diag4diagnosiscodekey INT64,
  diag5diagnosiscodekey INT64,
  artivaliabilitypool STRING,
  artivaliabilitylastworkeddate DATE,
  artivaliabilitylastrevieweddate DATE,
  rh277lastresponsestatusctgycode STRING,
  rh277lastresponsestatuscode STRING,
  rh277lastresponseimportdatekey DATE,
  rh277lastresponserespondingpayer STRING,
  rh1301lastclaimdatewithedierror INT64,
  voidandrecreatedate DATE,
  voidedoriginalclaimstatuskey INT64,
  lastclaimnumber INT64,
  totalclaimnumberscnt INT64 NOT NULL,
  artivaliabilityfollowupdate DATE,
  totalbalanceamt NUMERIC(33, 4),
  totalchargesamt NUMERIC(33, 4),
  totalpatientbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  totalpaymentsamt NUMERIC(33, 4),
  totalinsurancepaymentsamt NUMERIC(33, 4),
  totalpatientpaymentsamt NUMERIC(33, 4),
  totalpaymentsandadjustmentsamt NUMERIC(33, 4),
  totaladjustmentsamt NUMERIC(33, 4),
  totalallowedamt NUMERIC(33, 4),
  lastadjustmentstransactiondatekey DATE,
  lastclaimkey INT64,
  lastvoiddatekey DATE,
  lastbillmessage STRING,
  primaryclaimpayerkey INT64,
  primarypayergroupnumber STRING,
  primarypayergroupname STRING,
  secondaryclaimpayerkey INT64,
  secondarypayergroupnumber STRING,
  secondarypayergroupname STRING,
  tertiaryclaimpayerkey INT64,
  tertiarypayergroupnumber STRING,
  tertiarypayergroupname STRING,
  firstinsurancewithvoidsbilldatekey DATE,
  deleteflag INT64,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  virtualvisit INT64,
  firstpatientliabilitydatekey DATE,
  firstzerobalancedatekey DATE,
  firstchargedebitdatekey DATE,
  PRIMARY KEY (claimkey) NOT ENFORCED
)
;