CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factsnapshotar
(
  arkey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  claimnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  gldepartment STRING,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  patientkey INT64,
  patientid INT64,
  patientinternalid INT64,
  accountid INT64,
  encounterid INT64,
  encounterform STRING,
  facilitykey INT64,
  facilityid INT64,
  renderingproviderkey INT64,
  renderingproviderid STRING,
  claimdatekey DATE,
  claimdatemonthid INT64,
  servicedatekey DATE,
  servicedatemonthid INT64,
  practicekey INT64,
  practiceid STRING,
  claimstatuskey INT64,
  claimstatusdesc STRING,
  financialclasskey INT64,
  liabilityfinancialclass INT64,
  billedfirstsubmitteddatekey DATE,
  billedlastsubmitteddatekey DATE,
  iplan1iplankey INT64,
  iplan1id STRING,
  iplan2iplankey INT64,
  iplan2id STRING,
  iplan3iplankey INT64,
  iplan3id STRING,
  liabilityiplankey INT64,
  liabilityid STRING,
  liabilitydate DATE,
  liabilityownertype INT64,
  lastpaymentdatekey DATE,
  firstinsurancepaymentdatekey DATE,
  lastinsurancepaymentdatekey DATE,
  lastadjustmentdatekey DATE,
  laststatusdatekey DATE,
  totalchargesamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalpatientbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  totalpaymentsamt NUMERIC(33, 4),
  totalpatientpaymentsamt NUMERIC(33, 4),
  totalinsurancepaymentsamt NUMERIC(33, 4),
  totaladjustmentsamt NUMERIC(33, 4),
  billedtoidtype INT64,
  claimbilledflag INT64,
  claimarflag INT64,
  deleteflag INT64,
  voidflag INT64,
  addprovider1providerkey INT64,
  addprovider1providerid STRING,
  addprovider2providerkey INT64,
  addprovider2providerid STRING,
  supervisorproviderkey INT64,
  supervisorproviderid STRING,
  paytoproviderkey INT64,
  paytoproviderid STRING,
  collectionstatus STRING,
  collectioncode STRING,
  collectioncodechangedate DATE,
  holdcode STRING,
  billareakey INT64,
  serviceareakey INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  firstpatientliabilitydatekey DATE,
  firstzerobalancedatekey DATE,
  firstchargedebitdatekey DATE
)
;