CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factriskanalysis
(
  riskloaddatekey DATE,
  claimcategory STRING,
  claimnumber INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  coidlob STRING,
  coidname STRING,
  deptcode STRING,
  marketname STRING,
  divisionname STRING,
  groupname STRING,
  renderingprovidernpi STRING,
  payerfinancialclass INT64,
  ppipayorfinancialclass STRING,
  cpid STRING,
  facilityid INT64,
  practicefederaltaxid STRING,
  epicholdcodeid STRING NOT NULL,
  epicholdcodedescription STRING NOT NULL,
  epicholdcodetype STRING NOT NULL,
  claimpayorid STRING,
  claimpayorname STRING,
  claimpayorauthorizationnumber STRING,
  servicedatekey DATE,
  claimage INT64,
  claimlastreleaseddate DATE,
  totalbalanceamt NUMERIC(33, 4),
  totalchargesamt NUMERIC(33, 4),
  renderingprovider STRING,
  providerkey INT64,
  cactusdivisionname STRING,
  providerfirstname STRING,
  providerlastname STRING,
  providermiddlename STRING,
  providernpi STRING,
  providerstartdate DATE,
  providernotificationdate DATE,
  providerlastrfcreceiveddate DATE,
  groupkey STRING,
  providergroupname STRING,
  groupdba STRING,
  groupenrollmentoperation STRING,
  provideraddresstype STRING,
  practiceaddressline1 STRING,
  practiceaddressline2 STRING,
  practicecity STRING,
  practicestate STRING,
  practicezip STRING,
  practicetaxid STRING,
  ppikey STRING,
  ppieffectivedate DATE,
  ppidepartmentflag STRING,
  ppicpidpayorname STRING,
  ppicpidpayorid STRING,
  payorsplitbylocationflag STRING,
  ppitype STRING,
  ppistatus STRING,
  ppistatusdescription STRING,
  ppiphase STRING,
  ppienrollmentaction STRING,
  ppileadgrouptaxid STRING,
  ppialternateeffectivedate DATE,
  ppistatusdate DATE,
  ppilastworkeddate DATE,
  ppiapplicationsenttopayordate DATE,
  ppiapplicationreceivedfrompayordate DATE,
  ppiapplicationsenttoproviderdate DATE,
  ppiapplicationreceivedfromproviderdate DATE,
  riskstatus STRING NOT NULL,
  risksubcategory STRING NOT NULL,
  psgriskstatus STRING NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;