CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_facttransactionsclaimpayment
(
  transactionsclaimpaymentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  facilitykey INT64,
  claimpaymentkey INT64,
  trrefid INT64,
  transactiontype STRING,
  transactionflag STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiontime TIME,
  transactionbyuserkey INT64,
  transactionperiod STRING,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  practicekey INT64,
  matchingtransactionnumber INT64,
  paymenttypekey INT64,
  epicpaymenttypekey INT64,
  debitcreditflag INT64,
  matchingtrrefid INT64,
  accountkey INT64,
  patientkey INT64,
  distributedbyuserkey STRING,
  undistributedbyuserkey STRING,
  etrid NUMERIC(29),
  matchingetrid NUMERIC(29),
  PRIMARY KEY (transactionsclaimpaymentkey) NOT ENFORCED
)
;