CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factsnapshottransactioncontractualadjustment
(
  transactioncontractualadjustmentkey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  regionkey INT64,
  practicekey INT64,
  practiceid STRING,
  coid STRING,
  gldepartment STRING,
  claimkey INT64,
  claimnumber INT64,
  visitnumber INT64,
  transactionnumber INT64,
  patientkey INT64,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  renderingproviderkey INT64,
  renderingproviderid STRING,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  claimdatemonthid INT64,
  servicedatekey DATE,
  servicedatemonthid INT64,
  iplan1iplankey INT64,
  iplan1id STRING,
  financialclasskey INT64,
  transactionid STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiondatemonthid INT64,
  transactiontype STRING,
  paymentfromiplanid STRING,
  paymentdetailid INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  transactionsamemonthflag STRING NOT NULL
)
;