CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factsnapshottransactioncharge
(
  transactionchargesmrykey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  regionkey INT64,
  practicekey INT64,
  practiceid STRING,
  coid STRING,
  gldepartment STRING,
  claimkey INT64,
  claimnumber INT64,
  visitnumber INT64,
  transactionnumber INT64,
  patientkey INT64,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  renderingproviderkey INT64,
  renderingproviderid STRING,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1iplankey INT64,
  iplan1id STRING,
  financialclasskey INT64,
  transactionamt NUMERIC(33, 4),
  transactiondatemonthid INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptunitchangeamt NUMERIC(33, 4),
  transactiontype STRING,
  cptid STRING,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptunitsonline NUMERIC(31, 2),
  cpttos STRING,
  cptchargeschangeamt NUMERIC(33, 4),
  cptstartdos DATETIME,
  cptenddos DATETIME,
  cptseqnum INT64,
  transactionid STRING,
  transactiondatekey DATE,
  claimdatemonthid INT64,
  servicedatemonthid INT64,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  transactionsamemonthflag STRING NOT NULL
)
;