CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factencounter
(
  encounterkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  facilitykey INT64,
  patientkey INT64,
  visitreason STRING,
  visitdate DATE,
  visitstarttime TIME,
  visitendtime TIME,
  visittypekey INT64,
  visitcopay NUMERIC(33, 4),
  visitcopaydue NUMERIC(33, 4),
  visitstatuskey INT64,
  encountertype STRING,
  deleteflag INT64,
  encounterlock INT64,
  visitarrivedtime TIME,
  statusaftercheckin STRING,
  claimrequired INT64,
  visittypeoverriden STRING,
  visitproviderkey INT64,
  referringproviderkey INT64,
  pcpproviderkey INT64,
  facilityresourcekey INT64,
  createdbyuserkey INT64,
  timein TIME,
  timeout TIME,
  departuretime TIME,
  patenccsnid INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  practicekey INT64,
  lastclaimkey INT64,
  encountertypekey INT64,
  gferequested INT64,
  gfecompleted INT64,
  gfedeclined INT64,
  PRIMARY KEY (encounterkey) NOT ENFORCED
)
;