CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factworkqueuechargereview
(
  regionkey INT64,
  regionname STRING,
  coid STRING NOT NULL,
  facilitykey INT64 NOT NULL,
  facilityname STRING NOT NULL,
  poscode STRING,
  encounterid INT64,
  encounterkey INT64,
  claimkey INT64 NOT NULL,
  patientmrn STRING,
  chargeslipnumber STRING NOT NULL,
  servicedate DATE,
  createddate DATE,
  workqueuetype STRING NOT NULL,
  workqueueid STRING,
  workqueuename STRING,
  enteredworkqueuedate DATE,
  daysinworkqueue INT64,
  totalbalanceamt NUMERIC(33, 4),
  cptbalanceamt NUMERIC(33, 4) NOT NULL,
  cptcode STRING NOT NULL,
  cptcodename STRING NOT NULL,
  chargeline INT64 NOT NULL,
  reviewedbyuserkey INT64 NOT NULL,
  liabilityfinancialclass INT64 NOT NULL,
  liabilityfinancialclassname STRING NOT NULL,
  liabilityiplankey INT64 NOT NULL,
  liabilityiplanname STRING NOT NULL,
  epicfinancialclass INT64,
  epicfinancialclassdesc STRING,
  servicingproviderkey INT64 NOT NULL,
  servicingprovidername STRING NOT NULL,
  activedeferredstatus STRING,
  deferreddate DATE,
  activedate DATE,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcebprimarykeyvalue INT64 NOT NULL,
  insertedby INT64,
  inserteddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL
)
;