CREATE TABLE IF NOT EXISTS edwpsc_staging.epic_factclaimlinefinancialadjustment
(
  claimlinefinancialadjustmentskey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  facilitykey INT64,
  claimadjustmentkey INT64,
  claimlinechargeskey INT64,
  adjustmentamt NUMERIC(33, 4),
  adjustmentcodekey INT64,
  adjcode STRING,
  adjustmentcategorykey INT64,
  cptid STRING,
  cptcode STRING,
  cptcodekey INT64,
  cptcharges NUMERIC(31, 2),
  claimadjustmentamt NUMERIC(33, 4),
  claimadjustmentdatekey DATE,
  claimadjustmentdeleteflag INT64,
  deleteflag INT64,
  createddatekey DATE,
  createdtime TIME,
  createdbyuserkey INT64,
  cptdeleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (claimlinefinancialadjustmentskey) NOT ENFORCED
)
;