CREATE TABLE IF NOT EXISTS edwpsc_staging.onbase_factapinvoice
(
  itemnum INT64,
  itemtypename STRING,
  amapprovaldate DATETIME,
  apapprovaldate DATETIME,
  cfoapprovaldate DATETIME,
  fdapprovaldate DATETIME,
  gcfoapprovaldate DATETIME,
  gpapprovaldate DATETIME,
  hrapprovaldate DATETIME,
  mmapprovaldate DATETIME,
  omapprovaldate DATETIME,
  pmapprovaldate DATETIME,
  vpapprovaldate DATETIME,
  invoicedate DATETIME,
  coid STRING,
  vendorname STRING,
  vendornumber INT64,
  amount NUMERIC(33, 4),
  invoicenumber221 STRING,
  vouchertype STRING,
  invoicetype STRING,
  apusername STRING,
  omusername STRING,
  pmusername STRING,
  mmusername STRING,
  vpusername STRING,
  gcfousername STRING,
  gpusername STRING,
  cfousername STRING,
  gvpusername STRING,
  hrusername STRING,
  amusername STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  onbaseapinvoicekey INT64 NOT NULL
)
;