CREATE TABLE IF NOT EXISTS edwpsc_staging.openconnect_factsourcecacprocharge
(
  cacprochargekey INT64 NOT NULL,
  messagedatetime DATETIME,
  batchdate DATE,
  documentid INT64,
  operatorid STRING,
  patientsourcemrn STRING,
  patientlastname STRING,
  patientfirstname STRING,
  patientdateofbirth DATE,
  visitnumber STRING,
  attendingid INT64,
  attendingname STRING,
  referringid INT64,
  referringname STRING,
  hospitalservice STRING,
  visitnumbercacpro STRING,
  hospitalizationdate DATE,
  proceduredate DATE,
  transactiontype STRING,
  cptunits INT64,
  performedbyproviderid INT64,
  orderedbycode INT64,
  procedurecode STRING,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  filename STRING,
  filedate DATE,
  fileimporteddate DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;