CREATE TABLE IF NOT EXISTS edwpsc_staging.openconnect_factsourcecernermasterlog
(
  cernermasterlogkey INT64 NOT NULL,
  facilityid STRING,
  department STRING,
  cdmcode STRING,
  cdmcodename STRING,
  patientnamefull STRING,
  patientlastname STRING,
  patientfirstname STRING,
  visitnumber STRING,
  accounttype STRING,
  batchdate DATE,
  batchnumber STRING,
  entry STRING,
  servicedate DATE,
  performingprovidername STRING,
  orderingprovidername STRING,
  postdate DATE,
  cptunits INT64,
  transactionamt NUMERIC(31, 2),
  procedurecode STRING,
  billitemid INT64,
  visitid STRING,
  proceduredatetime DATETIME,
  proceduredate DATE,
  estarrivedatetime DATETIME,
  dischdatetime DATETIME,
  financialclass STRING,
  tiergroup STRING,
  messageid STRING,
  filename STRING,
  filedate DATE,
  fileimporteddate DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;