CREATE TABLE IF NOT EXISTS edwpsc_staging.openconnect_juncfirstlastkeymeasure
(
  juncopenconnectfirstlastkeymeasurekey INT64 NOT NULL,
  openconnectmessagekey INT64 NOT NULL,
  messagecreateddate DATETIME,
  firststatusreason STRING,
  firststatusmessage STRING,
  firststatusdate DATETIME,
  firstcategory STRING,
  firstcategorydate DATE,
  laststatusreason STRING,
  laststatusmessage STRING,
  laststatusdate DATETIME,
  lastcategory STRING,
  lastcategorydate DATE,
  firstiserror INT64,
  firstiserrordate DATETIME,
  firstiserrorecw INT64,
  firstiserrorecwdate DATETIME,
  firstsuppressflag INT64,
  firstsuppressflagdate DATETIME,
  firstdftdatereceived DATETIME,
  lastdftdatereceived DATETIME,
  firstbatchdate DATE,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  firstpendingflag INT64,
  firstecwsuppressflag INT64,
  firstecwsuppressflagdate DATETIME,
  dwlastupdatedatetime DATETIME
)
;