CREATE TABLE IF NOT EXISTS edwpsc_staging.pk_factobservationnotehm
(
  pkobservationnotekey INT64 NOT NULL,
  pkregionname STRING,
  pkencounterkey INT64,
  pkencounterid INT64,
  notetypename STRING,
  notecreatedatetime DATETIME,
  noteupdatedatetime DATETIME,
  notedeleteflag INT64,
  notestatus STRING,
  noteproviderlastname STRING,
  noteproviderfirstname STRING,
  noteprovidernpi STRING,
  noteproviderusername STRING,
  providerlastname STRING,
  providerfirstname STRING,
  providernpi STRING,
  providerusername STRING,
  authorlastname STRING,
  authorfirstname STRING,
  authornpi STRING,
  authorusername STRING,
  observationdeleteflag INT64,
  observationcreatedatetime DATETIME,
  observationupdatedatetime DATETIME,
  sourceaprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  reporttitle STRING,
  originalpkencounterkey INT64,
  originalpkencounterid INT64,
  pkfinancialnumber STRING,
  noteproviderid INT64,
  providerid INT64,
  authorid INT64,
  documenttext STRING
)
;