CREATE TABLE IF NOT EXISTS edwpsc_staging.pk_factencounter
(
  pkencounterkey INT64 NOT NULL,
  pkregionname STRING,
  patientlastname STRING,
  patientfirstname STRING,
  patientmiddlename STRING,
  patientmrn STRING,
  source STRING,
  visitlocationunit STRING,
  visitlocationroom STRING,
  visitlocationfacility STRING,
  pkfinancialnumber STRING,
  appointmentadmitdate DATE,
  dischargedate DATE,
  createddate DATE,
  deleteflag INT64,
  status STRING,
  sourceaprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  encounterpos STRING,
  coid STRING,
  attendingproviderlastname STRING,
  attendingproviderfirstname STRING,
  attendingprovidernpi STRING,
  erproviderlastname STRING,
  erproviderfirstname STRING,
  erprovidernpi STRING,
  accountbasedencounterid INT64,
  practiceid STRING,
  postype STRING,
  primaryinsurancename STRING,
  secondaryinsurancename STRING
)
;