CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factrhclaimhistory
(
  rhclaimhistorykey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  coid STRING,
  regionkey INT64,
  importdatekey DATE,
  rhclaimhistoryclientid STRING,
  rhclaimhistorysubmissiondatekey DATE,
  rhclaimhistorybridgefilenumber STRING,
  rhclaimhistoryclaimid STRING,
  rhclaimhistorypatientcontrolnbr STRING,
  rhclaimhistoryoriginalclaimstatuscode STRING,
  rhclaimhistorypayerindicator STRING,
  rhclaimhistoryoriginalclaimamount STRING,
  rhclaimhistoryoriginalerrorcount STRING,
  rhclaimhistoryreleaseddatekey DATE,
  rhclaimhistoryclaimstate STRING,
  rhclaimhistoryholdcode STRING,
  rhclaimhistorycurrentclaimstatuscode STRING,
  rhclaimhistoryerrorcount STRING,
  rhclaimhistorytotalclaimamount STRING,
  rhclaimhistoryfilename STRING,
  sourceprimarykeyvalue STRING NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (rhclaimhistorykey) NOT ENFORCED
)
;