CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factencounterpayment
(
  encounterpaymentkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  clinic STRING,
  practice STRING,
  practicekey INT64,
  servicedatekey DATE,
  claimkey INT64,
  claimnumber INT64,
  encounterkey INT64,
  patientkey INT64,
  patientnumber INT64,
  paymentcategory STRING,
  paymentamt NUMERIC(33, 4),
  paymenttype STRING,
  claimdatekey DATE,
  visitstatus STRING,
  paymentcreatedatekey DATE,
  createdbyuserid STRING,
  createdbyuserkey INT64,
  claimcreatedflag STRING,
  claimbilledflag STRING,
  rebillflag STRING,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (encounterpaymentkey) NOT ENFORCED
)
;