CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factclaimfinancialadjustment
(
  claimfinancialadjustmentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  adjustmentcodekey INT64 NOT NULL,
  adjustmentamt NUMERIC(33, 4) NOT NULL,
  adjustmentdatekey DATE NOT NULL,
  unpostedtocptamt NUMERIC(33, 4) NOT NULL,
  unpostedamt NUMERIC(33, 4) NOT NULL,
  modifieddatekey DATE NOT NULL,
  modifiedtime TIME NOT NULL,
  createdbyuserkey INT64 NOT NULL,
  closingdatekey DATE,
  deleteflag INT64 NOT NULL,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  adjcode STRING,
  adjustmentcategorykey INT64,
  practicekey INT64,
  practicename STRING
)
;