CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factencounter
(
  encounterkey INT64 NOT NULL,
  claimkey INT64,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  patientkey INT64 NOT NULL,
  visitreason STRING,
  visitdate DATE NOT NULL,
  visitstarttime TIME,
  visitendtime TIME,
  visittypekey INT64 NOT NULL,
  visitcopay NUMERIC(33, 4),
  poa NUMERIC(33, 4),
  otherpaymentamt NUMERIC(33, 4),
  visitstatuskey INT64 NOT NULL,
  encountertype STRING,
  deleteflag INT64,
  encounterlock STRING,
  visitarrivedtime TIME,
  statusaftercheckin STRING,
  claimrequired INT64,
  visittypeoverriden STRING,
  claimnumber INT64,
  referringproviderkey INT64 NOT NULL,
  facilityresourcekey INT64 NOT NULL,
  timein TIME,
  timeout TIME,
  departuretime TIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  logdetailpk STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  practicekey INT64,
  practicename STRING,
  encountercategory STRING,
  createdbyuserkey INT64,
  quickvisitflag INT64,
  copaytype STRING,
  otherpaymenttype STRING,
  lastupdatedbyuserkey INT64,
  lastupdatedbyuserdatekey DATETIME,
  quickvisittype STRING,
  eligibilitystatuscode INT64,
  previouspaytype STRING,
  poapaymentnumber INT64,
  ispatienttelemedicineeligible BOOL,
  telemedicinetype INT64,
  telemedicinestatus INT64,
  PRIMARY KEY (encounterkey) NOT ENFORCED
)
;