CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factinvoicelinefinancialadjustment
(
  invoicelinefinancialadjustmentkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  practice STRING,
  invoicekey INT64,
  invoicenumber INT64,
  invoicelinenumber INT64,
  invoicelinechargekey INT64,
  adjustmentamt NUMERIC(33, 4),
  adjustmentdatekey DATE,
  adjustmentcode STRING,
  adjustmentcodekey INT64,
  createdbyuserkey INT64,
  adjustmentdesc STRING,
  transactionnumber INT64,
  batchkey INT64,
  checknumber STRING,
  checkdatekey DATE,
  checktypedesc STRING,
  paymentmsgcode STRING,
  depositdatekey DATE,
  paymentnumber INT64,
  treasurybatchnumber STRING,
  treasurybatchdepositdate DATE,
  treasurybatchpayername STRING,
  closingdatekey DATE,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (invoicelinefinancialadjustmentkey) NOT ENFORCED
)
;