CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_facttransactionsclaimpayment
(
  transactionsclaimpaymentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  facilitykey INT64,
  claimpaymentkey INT64,
  transactiontype STRING,
  transactionflag STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiontime TIME,
  transactionclosingdatekey DATE,
  transactionbyuserkey INT64,
  trrefid STRING,
  practicekey INT64,
  practicename STRING,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  posteddatekey DATE,
  PRIMARY KEY (transactionsclaimpaymentkey) NOT ENFORCED
)
;