CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factclaimlinechargeworklist
(
  regionkey INT64,
  coid STRING,
  practice STRING,
  worklist STRING,
  assignedtouserid STRING,
  assignedtouserkey INT64,
  worklisttype STRING,
  priority INT64,
  createdbyuserid STRING,
  createdbyuserkey INT64,
  createddatekey DATETIME,
  refreshedcount INT64,
  worklistclinic STRING,
  worklistvisittype STRING,
  worklistpayertype STRING,
  worklistpayerclass STRING,
  worklistbalancefrom NUMERIC(33, 4),
  worklistbalanceto NUMERIC(33, 4),
  worklistdaysfrom INT64,
  worklistdaysto INT64,
  worklistpatientfrom STRING,
  worklistpatientto STRING,
  worklistpayerfrom STRING,
  worklistpayerto STRING,
  isunassignedworklist BOOL,
  claimnumber INT64,
  claimkey INT64,
  claimlinechargekey INT64,
  arctrlnum INT64,
  actiondatekey DATE,
  displayui BOOL,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue INT64,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;