CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factclaimlinecharge
(
  claimlinechargekey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  cptstartservicedatekey DATE NOT NULL,
  cptendservicedatekey DATE NOT NULL,
  cptposkey INT64 NOT NULL,
  cpttypeofservicekey INT64 NOT NULL,
  cptcharges NUMERIC(31, 2),
  cptchargesperunit NUMERIC(31, 2),
  cptunits NUMERIC(31, 2),
  cptallowed NUMERIC(31, 2),
  cptallowedperunit NUMERIC(31, 2),
  cptpatientportion NUMERIC(31, 2),
  cpttotalpatientportion NUMERIC(31, 2),
  cptnoncoveredcharges NUMERIC(31, 2),
  cptbalance NUMERIC(31, 2),
  cptcalculatedbalance NUMERIC(31, 2),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptbilltoins INT64,
  cptbilltopt INT64,
  cptdeleteflag INT64,
  cptorder INT64,
  sourceaprimarykeyvalue STRING NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  icd1 STRING,
  icd1code STRING,
  icd2 STRING,
  icd2code STRING,
  icd3 STRING,
  icd3code STRING,
  icd4 STRING,
  icd4code STRING,
  cliaid STRING,
  ndccode STRING,
  ndcunits STRING,
  ndcunitprice NUMERIC(33, 4),
  ndcuom STRING,
  cptcode STRING,
  sourcebprimarykeyvalue STRING,
  practicename STRING,
  ndcsentonbillflag STRING,
  emcodeflag BOOL NOT NULL,
  PRIMARY KEY (claimlinechargekey) NOT ENFORCED
)
;