CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factinvoice
(
  invoicekey INT64 NOT NULL,
  coid STRING,
  regionkey INT64,
  practice STRING,
  invoicenumber INT64,
  companynumber INT64,
  invoicedate DATE,
  invoicetype STRING,
  totalchargesamt NUMERIC(33, 4),
  totalpaymentamt NUMERIC(33, 4),
  totaladjustmentamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalendingbalanceamt NUMERIC(33, 4),
  servicingproviderkey INT64,
  referringproviderkey INT64,
  companyiplankey INT64,
  lastupdatedbyuserkey INT64,
  closingdatekey DATE,
  internalnotes STRING,
  externalnotes STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (invoicekey) NOT ENFORCED
)
;