CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factsnapshotfinancialadjustmentline
(
  adjustmentlinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  claimnumber INT64,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  adjustmentcodekey INT64 NOT NULL,
  iplan1iplankey INT64 NOT NULL,
  practicekey INT64 NOT NULL,
  practiceid STRING,
  cptcodekey INT64 NOT NULL,
  gldepartmentnum STRING,
  patientid INT64,
  servicingproviderid INT64,
  renderingproviderid INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1id STRING,
  financialclasskey STRING,
  encounterid INT64,
  adjustmentlineid STRING NOT NULL,
  adjustmentid STRING NOT NULL,
  cptid STRING NOT NULL,
  cptcode STRING,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cptorder INT64,
  cptdeleletedline INT64,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  adjustmentlinecreatedate DATETIME,
  adjustmentlinemodifieddate DATETIME,
  adjustmentclaimcreatedate DATETIME,
  adjustmentclaimmodifieddate DATETIME,
  regionkey INT64,
  coid STRING,
  adjustmentcode STRING,
  adjustmentclaimamt NUMERIC(33, 4),
  adjustmentclaimunpostedcptamt NUMERIC(33, 4),
  adjustmentclaimunpostedamt NUMERIC(33, 4),
  cptunits NUMERIC(33, 4),
  cptchargesamt NUMERIC(33, 4),
  adjustmentlineamt NUMERIC(33, 4)
)
;