CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_factsnapshotpaymentline
(
  paymentlinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  iplan1iplankey INT64 NOT NULL,
  practicekey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  gldepartmentnum STRING,
  patientid INT64,
  servicingproviderid INT64,
  renderingproviderid INT64,
  facilityid INT64,
  practiceid STRING,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1id STRING,
  financialclasskey STRING,
  encounterid INT64,
  cptid STRING NOT NULL,
  paymentlineid STRING NOT NULL,
  paymentdetailid INT64 NOT NULL,
  paymentid INT64,
  checknumber STRING,
  checktype STRING,
  checkdate DATETIME,
  posteddatekey DATETIME,
  allowedamt NUMERIC(31, 2) NOT NULL,
  deductableamt NUMERIC(31, 2) NOT NULL,
  coinsuranceamt NUMERIC(31, 2) NOT NULL,
  memrespamt NUMERIC(31, 2) NOT NULL,
  paymentamt NUMERIC(31, 2) NOT NULL,
  contractualadjustmentamt NUMERIC(31, 2) NOT NULL,
  withheldamt NUMERIC(31, 2) NOT NULL,
  msgcode STRING NOT NULL,
  eraadjustmentamt NUMERIC(31, 2) NOT NULL,
  linetaxamt NUMERIC(31, 2) NOT NULL,
  paymentfromid INT64,
  paymenttypekey INT64,
  cptcode STRING,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cptorder INT64,
  cptdeleletedline INT64,
  cptunits NUMERIC(31, 2),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptchargesamt NUMERIC(31, 2),
  paymentlinecreatedate DATETIME,
  paymentlinemodifieddate DATETIME,
  paymentclaimcreatedate DATETIME,
  paymentclaimmodifieddate DATETIME,
  regionkey INT64,
  coid STRING
)
;