CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_refiplan
(
  iplankey INT64 NOT NULL,
  financialclasskey INT64 NOT NULL,
  iplangroupcactuskey INT64 NOT NULL,
  iplangroupfinancialkey INT64 NOT NULL,
  iplanname STRING,
  iplanphone STRING,
  iplanphone2 STRING,
  iplanfax STRING,
  iplanemail STRING,
  iplanprimaryaddressline1 STRING,
  iplanprimaryaddressline2 STRING,
  iplanprimarygeographykey INT64 NOT NULL,
  iplanpayorid STRING,
  iplanerapayorid STRING,
  iplanfeeschedid INT64,
  sourceprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  iplandeleteflag INT64,
  iplaninactive INT64,
  iplannotes STRING,
  iplanpractice STRING,
  regionkey INT64,
  iplantype STRING,
  iplanwcpricing STRING,
  iplanoccmedpricing STRING,
  pvfinancialclass STRING,
  pvfinancialclassdesc STRING,
  pvfinancialclassgrouped STRING,
  companysalesrepname STRING,
  emcpayerid STRING,
  paperpayerid STRING,
  companynumber INT64,
  companyname STRING,
  billingnotes STRING,
  epsbilltoname STRING,
  wcbilltotype STRING,
  wcbilltoname STRING,
  wcnotes STRING,
  wcinstructions STRING,
  iplanbilltype STRING,
  numberofemployeesrange STRING,
  accountrepuserkey INT64,
  subscriberflag BOOL,
  PRIMARY KEY (iplankey) NOT ENFORCED
)
;