CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_refpatient_history
(
  patientkey INT64 NOT NULL,
  patientdobdatekey DATE,
  patientattendingdoctorproviderkey INT64,
  patientguarantorpatientkey INT64,
  patientguarantorid INT64,
  patientstatementdatekey DATE,
  patientreferringproviderkey INT64,
  patientrenderingproviderkey INT64,
  patientprimaryproviderkey INT64,
  patientdeceaseddatekey STRING,
  patientrelatedinfodatekey STRING,
  patientfirstname STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  patientaccountnumberwithprefix STRING,
  patientprefixname STRING,
  patientsuffixname STRING,
  patientprimaryaddressline1 STRING,
  patientprimaryaddressline2 STRING,
  patientprimarygeographykey INT64,
  patientusertype INT64,
  patientinitials STRING,
  patientssn STRING,
  patientprimaryservicelocation INT64,
  patientphone STRING,
  patientmobilephone STRING,
  patientpager STRING,
  patientemail STRING,
  patientstatus STRING,
  patientemployername STRING,
  patientemployeraddressline1 STRING,
  patientemployeraddressline2 STRING,
  patientemployergeographykey INT64,
  patientemployerphone STRING,
  patientstudentstatus STRING,
  patientemployerstatus STRING,
  patientnostatements INT64,
  patientbillingalert INT64,
  patientrace STRING,
  patientmaritalstatus STRING,
  patientdeceased INT64,
  patientdeceasednotes STRING,
  patientlegacymrn STRING,
  patientethnicity STRING,
  patientrelatedinfo STRING,
  patientpharmacyname STRING,
  patientpharmacyno STRING,
  patientpharmacyfax STRING,
  patientcountrycode STRING,
  patientsex STRING,
  sourceaprimarykeyvalue INT64,
  practicekey INT64,
  practicename STRING,
  regionkey INT64,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATE,
  patienthearfrom STRING,
  patientemployernumber STRING,
  patientemployernotes STRING,
  patientlanguage STRING,
  patientpractice STRING,
  patientsourceguid STRING,
  patientsourceprimaryproviderguid STRING,
  empinumber STRING,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL
)
;