CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_rprtcovidclaim
(
  covidclaimkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING,
  dateofservicekey DATE,
  dateofservicemonthendkey DATE,
  claimdatekey DATE,
  patientaccountnum STRING,
  covidclaimnumber INT64 NOT NULL,
  providernpi STRING,
  groupnpi STRING,
  grouptaxid STRING,
  covidchargesamt NUMERIC(33, 4) NOT NULL,
  covidbalanceamt NUMERIC(33, 4) NOT NULL,
  covidpatbalanceamt NUMERIC(33, 4) NOT NULL,
  covidinsbalanceamt NUMERIC(33, 4) NOT NULL,
  covidinspaymentamt NUMERIC(33, 4) NOT NULL,
  covidpatpaymentamt NUMERIC(33, 4) NOT NULL,
  covidrefundsamt NUMERIC(33, 4),
  accounttotalbalanceamt NUMERIC(33, 4) NOT NULL,
  accountpatientbalanceamt NUMERIC(33, 4) NOT NULL,
  accountinsurancebalanceamt NUMERIC(33, 4) NOT NULL,
  accountnonzerobalclaimscnt INT64 NOT NULL,
  payer1iplanname STRING,
  payer1ifinancialclassname STRING,
  payer2iplanname STRING,
  payer3iplanname STRING,
  liabilityowner STRING,
  liabilityfinancialclassname STRING,
  practiceid STRING,
  patientcategory STRING,
  collectioncode STRING,
  firstdenialcategory STRING,
  coviddxprimary STRING,
  primarydx STRING,
  billableflag STRING NOT NULL,
  firstpatientstatementdatekey DATE,
  poskey INT64,
  dxb342flag STRING,
  cpid STRING,
  innetworkflag STRING NOT NULL,
  providername STRING,
  patientbalanceflag STRING NOT NULL,
  netpatientpaymentamt NUMERIC(33, 4),
  netpatientpaymentflag STRING NOT NULL,
  hrsapatientflag STRING NOT NULL,
  refunddate DATE,
  patientfirstname STRING,
  middleinitial STRING,
  patientlastname STRING,
  dobkey DATE,
  servicetype STRING NOT NULL,
  typeofid STRING NOT NULL,
  idnumber STRING,
  patientgender STRING,
  patientprimarystatekey STRING,
  patientprimaryaddressline1 STRING,
  patientprimaryaddressline2 STRING,
  patientprimarycity STRING,
  patientprimaryzipcode STRING,
  totaladjustmentscharityamt NUMERIC(33, 4),
  totaladjustmentsuninsuredamt NUMERIC(33, 4),
  firstinsbilldatekey DATE,
  firstpatbilldatekey DATE,
  inssubmitted STRING,
  patientstatementsent STRING,
  payer2ifinancialclassname STRING,
  payer3ifinancialclassname STRING,
  cpt99000flag STRING,
  covidtestflag STRING,
  cpt87635flag STRING,
  csmodifierflag STRING,
  csmodifieddatekey DATE,
  worklist STRING,
  emflag STRING,
  scodeflag STRING,
  voidedclaimoriginalclaimnumber INT64,
  patientmobilephone STRING,
  facilityname STRING,
  facilityprimaryaddressline1 STRING,
  facilityprimaryaddressline2 STRING,
  facilitycity STRING,
  facilitystate STRING,
  facilityzip STRING,
  cptcodes STRING,
  dxcodes STRING,
  rpartyname STRING,
  rpartyaddrline1 STRING,
  rpartyaddrline2 STRING,
  rpartycity STRING,
  rpartystate STRING,
  rpartyzip STRING,
  covidcreditbalanceflag STRING NOT NULL,
  claimstatusname STRING,
  daysfromservicedate INT64,
  agingbucket STRING NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  patientrace STRING,
  patientethnicity STRING,
  totalfinancialadjustmentsamt NUMERIC(33, 4),
  rhlastreleasedate DATETIME
)
;