CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgpatinfo
(
  practice STRING NOT NULL,
  pat_num INT64 NOT NULL,
  last_name STRING,
  first_name STRING,
  middle_name STRING,
  ssn STRING NOT NULL,
  marital_status STRING NOT NULL,
  pat_status STRING NOT NULL,
  birthday STRING NOT NULL,
  sex STRING NOT NULL,
  address1 STRING NOT NULL,
  address2 STRING NOT NULL,
  city STRING NOT NULL,
  state STRING NOT NULL,
  zip STRING NOT NULL,
  country STRING NOT NULL,
  pat_phone STRING NOT NULL,
  cell_phone STRING NOT NULL,
  email STRING NOT NULL,
  emp_num INT64 NOT NULL,
  emp_name STRING NOT NULL,
  emp_status STRING NOT NULL,
  emp_phone STRING NOT NULL,
  emp_phone_ext STRING NOT NULL,
  emp_notes STRING NOT NULL,
  pcp_phy_note STRING NOT NULL,
  ref_phy_note STRING NOT NULL,
  ref_hsp_note STRING NOT NULL,
  statement_date DATETIME NOT NULL,
  statement_flag STRING NOT NULL,
  valid_flag STRING NOT NULL,
  complete_flag STRING NOT NULL,
  pymt_plan_date DATETIME NOT NULL,
  last_svc_date DATETIME NOT NULL,
  hipaa_date DATETIME NOT NULL,
  clinic STRING NOT NULL,
  acpt_date DATETIME NOT NULL,
  legacy_notes STRING NOT NULL,
  hear_from STRING NOT NULL,
  crt_usernum INT64 NOT NULL,
  crt_userid STRING NOT NULL,
  crt_datetime DATETIME NOT NULL,
  last_upd_usernum INT64 NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  emailpromotional INT64 NOT NULL,
  batch_ltr_date DATETIME NOT NULL,
  batch_ltr_subkey STRING NOT NULL,
  batch_ltr_printed STRING NOT NULL,
  race STRING NOT NULL,
  poverty STRING NOT NULL,
  translation STRING NOT NULL,
  patinfopk STRING NOT NULL,
  patinfopk_txt STRING,
  primaryphysicianpk STRING,
  races INT64,
  ethnicities INT64,
  language INT64,
  communicationmethod INT64,
  wantsportalaccess BOOL,
  passwordsalt STRING,
  passwordhash STRING,
  smokingstatus INT64,
  primaryphysicianoptout BOOL,
  publicitycode STRING,
  publicitycodeeffectivedate DATE,
  protectionindicator STRING,
  protectionindicatordate DATE,
  immunizationregistrystatus STRING,
  immunregistrystatuseffectivedate DATE,
  smokingstatuscode INT64,
  publicitycodecontact STRING,
  protectionindicatorcontact STRING,
  vfccode STRING,
  preferredremindercommunicationmethod INT64,
  portaldatalastsent DATETIME,
  voicemailauth BOOL,
  voicemailauthdate DATE,
  birthdate DATE,
  county_parish STRING,
  preferredname STRING,
  allowvm_home BOOL,
  allowvm_cell BOOL,
  usesexchangepatientinfo BOOL,
  lastlogdetailpk STRING,
  wantsinhousedispensing BOOL,
  regionkey INT64 NOT NULL,
  races_description STRING,
  ethniciies_description STRING,
  language_description STRING,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL
)
;