CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgcrgdetail
(
  practice STRING NOT NULL,
  inv_num INT64 NOT NULL,
  line_num INT64 NOT NULL,
  log_num INT64 NOT NULL,
  status STRING NOT NULL,
  pat_num INT64 NOT NULL,
  svc_date DATETIME NOT NULL,
  payer_class STRING NOT NULL,
  payer_type STRING NOT NULL,
  payer_num INT64 NOT NULL,
  payer_name STRING,
  phy_num INT64 NOT NULL,
  phy_name STRING NOT NULL,
  group_id STRING NOT NULL,
  provider_id STRING NOT NULL,
  fed_tax_id STRING NOT NULL,
  billto_lastname STRING NOT NULL,
  billto_firstname STRING NOT NULL,
  billto_credential STRING NOT NULL,
  proc_code STRING NOT NULL,
  modifier STRING NOT NULL,
  cpt_code STRING NOT NULL,
  proc_desc STRING NOT NULL,
  svc_type STRING NOT NULL,
  type STRING NOT NULL,
  rev_code STRING,
  rvu NUMERIC(31, 2) NOT NULL,
  diag1 STRING NOT NULL,
  diag2 STRING NOT NULL,
  diag3 STRING NOT NULL,
  diag4 STRING NOT NULL,
  quantity INT64 NOT NULL,
  dosage NUMERIC(31, 2) NOT NULL,
  crg_amt NUMERIC(31, 2) NOT NULL,
  override_amt NUMERIC(31, 2) NOT NULL,
  ar_amt NUMERIC(31, 2) NOT NULL,
  crg_paid_amt NUMERIC(31, 2) NOT NULL,
  pat_paid_amt NUMERIC(31, 2) NOT NULL,
  payer_paid_amt NUMERIC(31, 2) NOT NULL,
  adj_code STRING NOT NULL,
  adj_amt NUMERIC(31, 2) NOT NULL,
  crg_adj_amt NUMERIC(31, 2) NOT NULL,
  crg_balance NUMERIC(31, 2) NOT NULL,
  payer_flag STRING NOT NULL,
  deleted STRING NOT NULL,
  rebill_flag STRING NOT NULL,
  status_date DATETIME NOT NULL,
  sent_date DATETIME NOT NULL,
  closing_date DATETIME NOT NULL,
  last_upd_usernum INT64 NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  crgdetailpk STRING NOT NULL,
  crgdetailpk_txt STRING NOT NULL,
  ub_rev_code STRING NOT NULL,
  descriptionsentinedi BOOL,
  crgheaderpk STRING,
  crgheaderpk_txt STRING,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;