CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgcrgheader
(
  practice STRING NOT NULL,
  inv_num INT64 NOT NULL,
  log_num INT64 NOT NULL,
  type STRING NOT NULL,
  status STRING NOT NULL,
  pat_num INT64 NOT NULL,
  pat_name STRING,
  pos STRING NOT NULL,
  clinic STRING NOT NULL,
  facility STRING NOT NULL,
  svc_date DATETIME NOT NULL,
  phy_num INT64 NOT NULL,
  phy_name STRING,
  ref_phy_num INT64 NOT NULL,
  ref_phy_name STRING NOT NULL,
  provider_id STRING NOT NULL,
  group_id STRING NOT NULL,
  fed_tax_id STRING NOT NULL,
  billto_lastname STRING NOT NULL,
  billto_firstname STRING NOT NULL,
  billto_credential STRING NOT NULL,
  auth_num STRING NOT NULL,
  withhold_code STRING NOT NULL,
  emc_pid STRING NOT NULL,
  payer_class STRING NOT NULL,
  payer_type STRING NOT NULL,
  payer_num INT64 NOT NULL,
  payer_name STRING,
  pricing STRING NOT NULL,
  protocol STRING NOT NULL,
  diag1 STRING NOT NULL,
  diag2 STRING NOT NULL,
  diag3 STRING NOT NULL,
  diag4 STRING NOT NULL,
  box19 STRING,
  outside_lab STRING NOT NULL,
  emp_related STRING NOT NULL,
  auto_accident STRING NOT NULL,
  auto_accident_state STRING NOT NULL,
  accident_flag STRING NOT NULL,
  first_doi DATETIME NOT NULL,
  current_doi DATETIME NOT NULL,
  total_charge NUMERIC(31, 2) NOT NULL,
  total_override NUMERIC(31, 2) NOT NULL,
  total_ar NUMERIC(31, 2) NOT NULL,
  total_paid NUMERIC(31, 2) NOT NULL,
  total_adj NUMERIC(31, 2) NOT NULL,
  crg_balance NUMERIC(31, 2) NOT NULL,
  copay_req NUMERIC(31, 2) NOT NULL,
  copay_paid NUMERIC(31, 2) NOT NULL,
  copay_type STRING NOT NULL,
  copay_notes STRING NOT NULL,
  curr_pay_amt NUMERIC(31, 2) NOT NULL,
  curr_pay_type STRING NOT NULL,
  curr_pay_notes STRING NOT NULL,
  payment_num INT64 NOT NULL,
  prev_payment_num INT64 NOT NULL,
  prev_billto_payer INT64 NOT NULL,
  prev_pay_amt NUMERIC(31, 2) NOT NULL,
  prev_pay_type STRING NOT NULL,
  prev_pay_notes STRING NOT NULL,
  first_bill_date DATETIME NOT NULL,
  fiscal_date DATETIME NOT NULL,
  edi_flag STRING NOT NULL,
  rebill_flag STRING NOT NULL,
  audit_trail STRING,
  category STRING NOT NULL,
  ref_clinic STRING NOT NULL,
  sent_date DATETIME NOT NULL,
  print_date DATETIME NOT NULL,
  closing_date DATETIME NOT NULL,
  prev_status STRING,
  prev_sent_date DATETIME,
  prev_first_bill_date DATETIME,
  new_inv_num INT64 NOT NULL,
  old_inv_num INT64 NOT NULL,
  crt_userid STRING NOT NULL,
  crt_usernum INT64 NOT NULL,
  crt_datetime DATETIME NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_usernum INT64 NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  sent_date_2nd DATETIME NOT NULL,
  payer_type_2nd STRING NOT NULL,
  payer_num_2nd INT64 NOT NULL,
  payer_name_2nd STRING,
  emc_pid_2nd STRING NOT NULL,
  group_id_2nd STRING NOT NULL,
  provider_id_2nd STRING NOT NULL,
  ndc_flag STRING NOT NULL,
  crgheaderpk STRING NOT NULL,
  selfpay_flag STRING NOT NULL,
  payer_subclass INT64 NOT NULL,
  edi_type STRING NOT NULL,
  logdetail_cache STRING NOT NULL,
  logdetailpk STRING,
  insurance_type STRING,
  suppresszerocharges BOOL NOT NULL,
  payer_resent INT64 NOT NULL,
  ccplanchargedate DATE,
  ccplannotifytype INT64,
  hasattachment BOOL NOT NULL,
  epsdtreferral BOOL,
  box17refphyqualifier STRING,
  payerclaimnum STRING,
  admitdate DATE,
  dischargedate DATE,
  attachmenttype STRING,
  billedicdtype INT64,
  secondarybilledicdtype INT64,
  wcattachmentheaderid STRING,
  clonedfromcrgheaderpk STRING,
  regionkey INT64 NOT NULL,
  statementnum INT64,
  statementdate DATETIME,
  admittime TIME,
  admittype INT64,
  admitsource STRING,
  dischargetime TIME,
  dischargestatus STRING,
  sysstarttime DATETIME,
  sysendtime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  crgheaderpk_txt STRING NOT NULL,
  logdetailpk_txt STRING
)
;