CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgphysician
(
  practice STRING NOT NULL,
  phy_num INT64 NOT NULL,
  pivot_provider_num STRING,
  description STRING NOT NULL,
  first_name STRING NOT NULL,
  middle_name STRING NOT NULL,
  last_name STRING NOT NULL,
  address1 STRING NOT NULL,
  address2 STRING NOT NULL,
  city STRING NOT NULL,
  state STRING NOT NULL,
  zip STRING NOT NULL,
  home_phone STRING NOT NULL,
  work_phone STRING NOT NULL,
  pager STRING NOT NULL,
  cell_phone STRING NOT NULL,
  active STRING NOT NULL,
  member_flag STRING NOT NULL,
  ref_phy_flag STRING NOT NULL,
  upin STRING NOT NULL,
  npi STRING,
  provider_type STRING NOT NULL,
  fed_tax_id STRING NOT NULL,
  taxonomy_code STRING NOT NULL,
  ssn STRING NOT NULL,
  license STRING NOT NULL,
  credential STRING NOT NULL,
  dea_number STRING NOT NULL,
  mc_provider_num STRING NOT NULL,
  pa_payee_num STRING NOT NULL,
  bill_to INT64 NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME,
  physicianpk STRING NOT NULL,
  wc_billing_num STRING NOT NULL,
  lastupdateservertime DATETIME,
  fax STRING NOT NULL,
  email STRING NOT NULL,
  onscheduler BOOL NOT NULL,
  regionkey INT64 NOT NULL,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64
)
;