CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgpatbilling
(
  practice STRING NOT NULL,
  pat_num INT64 NOT NULL,
  payer_num INT64 NOT NULL,
  bill_to STRING NOT NULL,
  short_name STRING,
  class STRING NOT NULL,
  type STRING NOT NULL,
  priority INT64 NOT NULL,
  pricing STRING NOT NULL,
  wc_pricing STRING NOT NULL,
  eps_pricing STRING NOT NULL,
  pbc_flag STRING NOT NULL,
  percentage NUMERIC(31, 2) NOT NULL,
  assignment_date DATETIME NOT NULL,
  assignment_flag STRING NOT NULL,
  eft_date DATETIME NOT NULL,
  exp_date DATETIME NOT NULL,
  policy_notes STRING NOT NULL,
  svc_copay NUMERIC(31, 2) NOT NULL,
  med_copay NUMERIC(31, 2) NOT NULL,
  member_id STRING,
  group_id STRING NOT NULL,
  auth_num STRING NOT NULL,
  crg_balance NUMERIC(31, 2) NOT NULL,
  prim_name STRING,
  prim_address1 STRING,
  prim_address2 STRING NOT NULL,
  prim_city STRING NOT NULL,
  prim_state STRING NOT NULL,
  prim_zip STRING NOT NULL,
  prim_country STRING NOT NULL,
  prim_attn STRING NOT NULL,
  prim_phone STRING NOT NULL,
  prim_phone_ext STRING NOT NULL,
  scnd_name STRING NOT NULL,
  scnd_address1 STRING,
  scnd_address2 STRING NOT NULL,
  scnd_city STRING NOT NULL,
  scnd_state STRING NOT NULL,
  scnd_zip STRING NOT NULL,
  scnd_country STRING NOT NULL,
  scnd_contact STRING NOT NULL,
  scnd_phone STRING NOT NULL,
  scnd_phone_ext STRING NOT NULL,
  emp_num INT64 NOT NULL,
  emp_name STRING NOT NULL,
  emp_address1 STRING NOT NULL,
  emp_address2 STRING NOT NULL,
  emp_city STRING NOT NULL,
  emp_state STRING NOT NULL,
  emp_zip STRING NOT NULL,
  emp_country STRING NOT NULL,
  emp_contact STRING NOT NULL,
  emp_phone STRING NOT NULL,
  emp_phone_ext STRING NOT NULL,
  emp_status STRING NOT NULL,
  ins_name STRING,
  ins_address1 STRING,
  ins_address2 STRING,
  ins_city STRING,
  ins_state STRING,
  ins_zip STRING,
  ins_country STRING,
  ins_phone STRING,
  ins_phone_ext STRING,
  ins_ssn STRING,
  ins_sex STRING,
  ins_birthday DATETIME,
  ins_relationship STRING,
  deleted STRING,
  active STRING,
  last_trans_date DATETIME,
  crt_usernum INT64,
  crt_userid STRING,
  crt_datetime DATETIME,
  last_upd_usernum INT64,
  last_upd_userid STRING,
  last_upd_datetime DATETIME,
  patbillingpk STRING,
  patbillingpk_txt STRING,
  lastupdateservertime DATETIME,
  insurance_type STRING,
  emp_employerpk STRING,
  emp_employerpk_txt STRING,
  prim_companypk STRING,
  prim_companypk_txt STRING,
  prim_insurancepk STRING,
  prim_insurancepk_txt STRING,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL
)
;