CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgardetail
(
  practice STRING NOT NULL,
  inv_num INT64 NOT NULL,
  proc_code STRING NOT NULL,
  modifier STRING NOT NULL,
  ar_ctrl_num INT64 NOT NULL,
  trans_num INT64 NOT NULL,
  log_num INT64 NOT NULL,
  pat_num INT64 NOT NULL,
  type STRING NOT NULL,
  payer_type STRING NOT NULL,
  payer_class STRING NOT NULL,
  payer_num INT64 NOT NULL,
  payer_name STRING,
  trans_date DATETIME NOT NULL,
  trans_type STRING NOT NULL,
  trans_amt NUMERIC(31, 2) NOT NULL,
  trans_desc STRING NOT NULL,
  db_acnt STRING NOT NULL,
  cr_acnt STRING,
  pymt_type STRING NOT NULL,
  check_num STRING NOT NULL,
  payment_num INT64 NOT NULL,
  reason STRING,
  reverse_flag STRING NOT NULL,
  delete_flag STRING NOT NULL,
  display_flag STRING NOT NULL,
  closing_date DATETIME NOT NULL,
  crt_userid STRING NOT NULL,
  crt_datetime DATETIME NOT NULL,
  payer_subclass INT64 NOT NULL,
  lastupdateservertime DATETIME,
  ardetailpk STRING NOT NULL,
  ardetailpk_txt STRING,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;