CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stginsurance
(
  practice STRING NOT NULL,
  short_name STRING NOT NULL,
  class STRING NOT NULL,
  type STRING NOT NULL,
  pricing STRING NOT NULL,
  bill_to STRING NOT NULL,
  emc_pid STRING NOT NULL,
  paper_pid STRING NOT NULL,
  policy_text STRING NOT NULL,
  svc_copay NUMERIC(33, 4) NOT NULL,
  med_copay NUMERIC(33, 4) NOT NULL,
  pbc_flag STRING NOT NULL,
  crr_name STRING NOT NULL,
  crr_address1 STRING NOT NULL,
  crr_address2 STRING NOT NULL,
  crr_city STRING NOT NULL,
  crr_state STRING NOT NULL,
  crr_zip STRING NOT NULL,
  crr_country STRING NOT NULL,
  crr_attn STRING NOT NULL,
  crr_contact STRING NOT NULL,
  crr_phone STRING NOT NULL,
  crr_phone_ext STRING NOT NULL,
  crr_fax STRING NOT NULL,
  grp_name STRING NOT NULL,
  grp_address1 STRING NOT NULL,
  grp_address2 STRING NOT NULL,
  grp_city STRING NOT NULL,
  grp_state STRING NOT NULL,
  grp_zip STRING NOT NULL,
  grp_country STRING NOT NULL,
  grp_attn STRING NOT NULL,
  grp_contact STRING NOT NULL,
  grp_phone STRING NOT NULL,
  grp_phone_ext STRING NOT NULL,
  grp_fax STRING NOT NULL,
  insuranceid INT64,
  insurancepk STRING NOT NULL,
  regionkey INT64,
  usebillingnpiforrte BOOL,
  active STRING,
  insurancepk_txt STRING,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64
)
;