CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgchartcodesdetail
(
  chartcodesdetailpk STRING NOT NULL,
  chartcodesdetailpk_txt STRING NOT NULL,
  chartcodesheaderpk STRING,
  chartcodesheaderpk_txt STRING,
  codetypeid INT64,
  code STRING NOT NULL,
  codedescription STRING,
  modifiers STRING,
  quantity INT64 NOT NULL,
  codequestionxml STRING,
  transscriptiontext STRING,
  status INT64 NOT NULL,
  reviewrequired BOOL NOT NULL,
  completedon DATETIME,
  reviewedon DATETIME,
  codequestionid INT64,
  completedby STRING,
  reviewedby STRING,
  createdby STRING,
  createdon DATETIME NOT NULL,
  lastupdatedby STRING,
  lastupdatedon DATETIME NOT NULL,
  questionid INT64,
  answerxml STRING,
  radiologyimagepath STRING,
  radiologyshielding INT64,
  radiologytransport INT64,
  radiologytransportother STRING,
  regionkey INT64 NOT NULL,
  ts BYTES,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;