CREATE TABLE IF NOT EXISTS edwpsc_staging.pv_stgarheader
(
  practice STRING NOT NULL,
  inv_num INT64 NOT NULL,
  proc_code STRING NOT NULL,
  modifier STRING NOT NULL,
  ar_ctrl_num INT64 NOT NULL,
  log_num INT64 NOT NULL,
  clinic STRING NOT NULL,
  type STRING NOT NULL,
  pat_num INT64 NOT NULL,
  pat_name STRING,
  phy_num INT64 NOT NULL,
  phy_name STRING NOT NULL,
  payer_type STRING NOT NULL,
  payer_class STRING NOT NULL,
  payer_num INT64 NOT NULL,
  payer_name STRING,
  proc_desc STRING NOT NULL,
  cpt_code STRING NOT NULL,
  pos STRING NOT NULL,
  svc_date DATETIME NOT NULL,
  inv_date DATETIME NOT NULL,
  closing_date DATETIME NOT NULL,
  crg_amt NUMERIC(31, 2) NOT NULL,
  ar_amt NUMERIC(31, 2) NOT NULL,
  adj_amt NUMERIC(31, 2) NOT NULL,
  paid_amt NUMERIC(31, 2) NOT NULL,
  crg_balance NUMERIC(31, 2) NOT NULL,
  end_balance NUMERIC(31, 2) NOT NULL,
  db_acnt STRING NOT NULL,
  cr_acnt STRING,
  rvu NUMERIC(31, 2) NOT NULL,
  rebill_flag STRING NOT NULL,
  old_rebill STRING NOT NULL,
  rev_adj_flag STRING NOT NULL,
  rev_adj_date DATETIME NOT NULL,
  crossover_code STRING NOT NULL,
  crossover_name STRING NOT NULL,
  release_flag STRING NOT NULL,
  action_date DATETIME NOT NULL,
  work_list STRING NOT NULL,
  crt_userid STRING NOT NULL,
  crt_datetime DATETIME NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  payer_subclass INT64 NOT NULL,
  lastupdateservertime DATETIME,
  crgdetailpk STRING,
  crgdetailpk_txt STRING,
  note STRING,
  rebill_icdtype INT64,
  arheaderpk STRING NOT NULL,
  arheaderpk_txt STRING,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;