export Job_Name='J_IM_Lawsn_Person_STG'
export JOBNAME='J_IM_Lawsn_Person_STG'





export AC_EXP_SQL_STATEMENT="select 'J_IM_Lawsn_Person_STG'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING

from
(
select
CMPY,
EMPL,
LST_NM,
FRST_NM,
MIDL_NM,
User_3_4,
EMPL_STTS,
DEPT,
JOB_CL
from
(
SELECT
fs1.CMPY,
fs1.EMPL,
fs1.LST_NM,
fs1.FRST_NM,
fs1.MIDL_NM,
fs1.User_3_4,
fs1.EMPL_STTS,
fs1.DEPT,
fs1.JOB_CL
FROM
(
SELECT
rs1.CMPY,
rs1.EMPL,
rs1.LST_NM,
rs1.FRST_NM,
rs1.MIDL_NM,
rs1.User_3_4,
rs1.EMPL_STTS,
rs1.IsActive,
rs1.PRCS_LVL,
rs1.Status_Rank,
rs1.HIRE_DT,
rs1.TERMN_DT,
rs1.DEPT,
rs1.JOB_CL,
ROW_NUMBER() OVER (PARTITION BY  rs1.User_3_4
ORDER BY  rs1.IsActive DESC) AS Row_Rank
FROM
(
SELECT
r1.CMPY,
r1.EMPL,
r1.LST_NM,
r1.FRST_NM,
r1.MIDL_NM,
r1.User_3_4,
r1.EMPL_STTS,
r1.IsActive,
r1.PRCS_LVL,
r1.Status_Rank,
r1.HIRE_DT,
r1.TERMN_DT,
r1.DEPT,
r1.JOB_CL
FROM
(
SELECT
s1.CMPY,
s1.EMPL,
s1.LST_NM,
s1.FRST_NM,
s1.MIDL_NM,
s1.User_3_4,
s1.EMPL_STTS,
s1.IsActive,
s1.PRCS_LVL,
s1.Status_Rank,
s1.HIRE_DT,
s1.TERMN_DT,
s1.DEPT,
s1.JOB_CL,
ROW_NUMBER() OVER  (PARTITION BY  s1.User_3_4
ORDER BY  s1.Status_Rank,
s1.TERMN_DT DESC,
s1.EFF_DT DESC,
s1.HIRE_DT DESC,
s1.PRCS_LVL DESC) AS Row_Rank
FROM
(
SELECT
t1.CMPY,
t1.EMPL,
t1.LST_NM,
t1.FRST_NM,
t1.MIDL_NM,
t2.User_3_4,
t1.EMPL_STTS,
0 AS IsActive,
t1.PRCS_LVL,
CASE
WHEN t1.EMPL_STTS = '08' THEN 1
WHEN t1.EMPL_STTS = '07' THEN 2
WHEN t1.EMPL_STTS = '99' THEN 3
END AS Status_Rank,
t1.HIRE_DT,
t1.TERMN_DT,
t3.DEPT,
t3.JOB_CL,
t3.EFF_DT
FROM  ORAFS.VW_ESAF_EMPLOYEE  t1
INNER JOIN
(
SELECT DISTINCT
CMPY,
EMPL,
CMPY_NUM AS User_3_4
FROM ORAFS.VW_ESAF_PERSONNEL_EMPLOYEE
) t2
ON t1.CMPY = t2.CMPY AND t1.EMPL = t2.EMPL
INNER JOIN
(
SELECT DISTINCT
s1.CMPY,
s1.POSN,
s2.JOB_CL,
s1.DEPT,
s1.EFF_DT
FROM ORAFS.VW_ESAF_PERSONNEL_POSITION  s1
JOIN ORAFS.VW_ESAF_JOB  s2
ON s1.CMPY = s2.CMPY
AND s1.JOB_CD = s2.JOB_CD
)t3
ON t1.CMPY = t3.CMPY AND t1.POSN = t3.POSN
WHERE  (t1.EMPL_STTS IN ('07', '08'))
OR  (t1.EMPL_STTS  = '99'
AND  to_char(t1.TERMN_DT ,'YYYY')  > 1800)
)  s1
)  r1
WHERE r1.Row_Rank = 1
UNION ALL
SELECT
r2.CMPY,
r2.EMPL,
r2.LST_NM,
r2.FRST_NM,
r2.MIDL_NM,
r2.User_3_4,
r2.EMPL_STTS,
r2.IsActive,
r2.PRCS_LVL,
r2.Status_Rank,
r2.HIRE_DT,
r2.TERMN_DT,
r2.DEPT,
r2.JOB_CL
FROM
(
SELECT
s2.CMPY,
s2.EMPL,
s2.LST_NM,
s2.FRST_NM,
s2.MIDL_NM,
s2.User_3_4,
s2.EMPL_STTS,
s2.IsActive,
s2.PRCS_LVL,
s2.Status_Rank,
s2.HIRE_DT,
s2.TERMN_DT,
s2.DEPT,
s2.JOB_CL,
ROW_NUMBER() OVER (PARTITION BY  s2.User_3_4  ORDER BY s2.Status_Rank,s2.HIRE_DT DESC,s2.EFF_DT DESC,s2.PRCS_LVL) AS Row_Rank
FROM
(
SELECT
t1.CMPY,
t1.EMPL,
t1.LST_NM,
t1.FRST_NM,
t1.MIDL_NM,
t2.User_3_4,
t1.EMPL_STTS,
1 AS IsActive,
t1.PRCS_LVL,
CASE
WHEN t1.EMPL_STTS = '01' THEN 1
WHEN t1.EMPL_STTS = '02' THEN 2
WHEN t1.EMPL_STTS = '03' THEN 3
WHEN t1.EMPL_STTS = '04' THEN 4
WHEN t1.EMPL_STTS = '05' THEN 5
WHEN t1.EMPL_STTS = '06' THEN 6
WHEN t1.EMPL_STTS = '99' THEN 99
END AS Status_Rank,
t1.HIRE_DT,
t1.TERMN_DT,
t3.DEPT,
t3.JOB_CL,
t3.EFF_DT
FROM  ORAFS.VW_ESAF_EMPLOYEE  t1
INNER JOIN
(
SELECT DISTINCT
CMPY,
EMPL,
CMPY_NUM AS User_3_4
FROM ORAFS.VW_ESAF_PERSONNEL_EMPLOYEE
) t2
ON t1.CMPY = t2.CMPY AND t1.EMPL = t2.EMPL
INNER JOIN
(
SELECT DISTINCT
s1.CMPY,
s1.POSN,
s2.JOB_CL,
s1.DEPT,
s1.EFF_DT
FROM ORAFS.VW_ESAF_PERSONNEL_POSITION  s1
JOIN ORAFS.VW_ESAF_JOB  s2
ON s1.CMPY = s2.CMPY
AND s1.JOB_CD = s2.JOB_CD
)t3
ON t1.CMPY = t3.CMPY AND t1.POSN = t3.POSN
WHERE  (t1.EMPL_STTS IN ('01', '02', '03', '04', '05', '06'))
OR  (t1.EMPL_STTS  = '99'
AND  to_char(t1.TERMN_DT ,'YYYY') = 1800)
)  s2
)  r2
WHERE r2.Row_Rank = 1
)  rs1
)  fs1
WHERE fs1.Row_Rank = 1
))" 

export AC_ACT_SQL_STATEMENT="select 'J_IM_Lawsn_Person_STG'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING from EDWIM_STAGING.LAWSN_PERSON;"


