#  @@START DMEXPRESS_EXPORTED_VARIABLES

export AC_EXP_TOLERANCE_PERCENT=0
export AC_EXP_TOLERANCE_AMT=0
export JOBNAME='J_IM_COVID19_Employee_Vaccine'

export ODBC_ACT_DB=$SQL_CAREMGMT_DB
export ODBC_ACT_USER=$SQL_CAREMGMT_USER
export ODBC_ACT_PASSWORD=$SQL_CAREMGMT_PASSWORD


export AC_EXP_SQL_STATEMENT="SELECT '${JOBNAME}' ||','||
CAST(COUNT(*) AS VARCHAR(20))||','
AS SOURCE_STRING
FROM EDWIM_Staging.COVID19_Vaccine_Extract;"


export AC_ACT_SQL_STATEMENT="SELECT '${JOBNAME}' +','+
CAST(COUNT(*) AS VARCHAR(20))+','
AS SOURCE_STRING
FROM dbo.Person_Employee;"


#  @@END DMEXPRESS_EXPORTED_VARIABLES
#  End of Exported variables section
#  
