export Job_Name='J_IM_Lawsn_ESAF_Personnel_Position'
export JOBNAME='J_IM_Lawsn_ESAF_Personnel_Position'


export AC_EXP_SQL_STATEMENT="select 'J_IM_Lawsn_ESAF_Personnel_Position'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING

from
(
SELECT
CMPY,
EFF_DT,
POSN,
DEPT,
JOB_CD,
LOC_CD,
LST_UPDT_DT,
LST_UPDT_USER_ID,
PERS_POSN_CHNG_RESN,
PERS_POSN_END_DT,
POSN_DESC,
POSN_STTS,
PRCS_LVL,
SUPV,
SUPV_LNK,
USER_LVL,
CREATE_DATE,
CREATE_TIME,
CREATE_USER,
SCHD
FROM
(
SELECT 
T1.CMPY,
CAST(T1.EFF_DT AS DATE) as EFF_DT,
T1.POSN,
T1.DEPT,
T1.JOB_CD,
T1.LOC_CD,
CAST(T1.LST_UPDT_DT AS DATE) as LST_UPDT_DT,
T1.LST_UPDT_USER_ID,
T1.PERS_POSN_CHNG_RESN,
CAST(T1.PERS_POSN_END_DT  AS DATE) as PERS_POSN_END_DT,
T1.POSN_DESC,
T1.POSN_STTS,
T1.PRCS_LVL,
T1.SUPV,
T1.SUPV_LNK,
T1.USER_LVL,
CAST(T1.CREATE_DATE AS DATE) as CREATE_DATE,
CAST(T1.CREATE_TIME  AS DATE) as CREATE_TIME,
T1.CREATE_USER,
T1.SCHD
FROM ORAFS.VW_ESAF_PERSONNEL_POSITION T1

UNION

SELECT 
T2.CMPY,
CAST(T2.EFF_DT  AS DATE) as EFF_DT,
T2.POSN,
T2.DEPT,
T2.JOB_CD,
T2.LOC_CD,
CAST(T2.LST_UPDT_DT  AS DATE) as LST_UPDT_DT,
T2.LST_UPDT_USER_ID,
T2.PERS_POSN_CHNG_RESN,
CAST(T2.PERS_POSN_END_DT  AS DATE) as PERS_POSN_END_DT,
T2.POSN_DESC,
T2.POSN_STTS,
T2.PRCS_LVL,
T2.SUPV,
T2.SUPV_LNK,
T2.USER_LVL,
CAST(T2.CREATE_DATE AS DATE) as CREATE_DATE,
CAST(T2.CREATE_TIME  AS DATE) as CREATE_TIME,
T2.CREATE_USER,
T2.SCHD
FROM ORACORP.VW_ESAF_PERSONNEL_POSITION T2
)S
)A" 

export AC_ACT_SQL_STATEMENT="select 'J_IM_Lawsn_ESAF_Personnel_Position'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING from EDWIM_Staging.Lawsn_eSAF_Personnel_Position ;"


