export Job_Name='J_IM_Lawsn_ESAF_Employee'
export JOBNAME='J_IM_Lawsn_ESAF_Employee'


export AC_EXP_SQL_STATEMENT="select 'J_IM_Lawsn_ESAF_Employee'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING

from
(
SELECT
CMPY,
EMPL,
CRET_DT,
DEPT,
EMPL_STTS,
FRST_NM,
HIRE_DT,
LST_NM,
MIDL_NM,
NKNM,
POSN,
PRCS_LVL,
SUPV,
TERMN_DT,
ADDR_1,
ADDR_2,
CITY,
ST,
ZIP
FROM
(
SELECT 
T1.CMPY,
T1.EMPL,
CAST(T1.CRET_DT AS DATE) as CRET_DT,
T1.DEPT,
T1.EMPL_STTS,
T1.FRST_NM,
CAST(T1.HIRE_DT  AS DATE) as HIRE_DT,
T1.LST_NM,
T1.MIDL_NM,
T1.NKNM,
T1.POSN,
T1.PRCS_LVL,
T1.SUPV,
CAST(T1.TERMN_DT  AS DATE) as TERMN_DT,
T1.ADDR_1,
T1.ADDR_2,
T1.CITY,
T1.ST,
T1.ZIP
FROM ORAFS.VW_ESAF_EMPLOYEE T1

UNION

SELECT 
T2.CMPY,
T2.EMPL,
CAST(T2.CRET_DT AS DATE) as CRET_DT,
T2.DEPT,
T2.EMPL_STTS,
T2.FRST_NM,
CAST(T2.HIRE_DT  AS DATE) as HIRE_DT,
T2.LST_NM,
T2.MIDL_NM,
T2.NKNM,
T2.POSN,
T2.PRCS_LVL,
T2.SUPV,
CAST(T2.TERMN_DT  AS DATE) as TERMN_DT,
T2.ADDR_1,
T2.ADDR_2,
T2.CITY,
T2.ST,
T2.ZIP
FROM ORACORP.VW_ESAF_EMPLOYEE T2
)S
)A" 

export AC_ACT_SQL_STATEMENT="select 'J_IM_Lawsn_ESAF_Employee'||','||cast(count(*) as varchar(20))||',' AS SOURCE_STRING from EDWIM_Staging.Lawsn_eSAF_Employee ;"


