-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/collection_charity_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.collection_charity_detail AS SELECT
    a.reporting_date,
    a.patient_dw_id,
    a.artiva_instance_code,
    a.approve_deny_date,
    a.charity_review_aging_date,
    a.appl_approval_level_num,
    a.charity_review_start_date,
    a.coid,
    a.company_code,
    a.pat_acct_num,
    a.iplan_id,
    a.appeal_ind,
    a.form_1099_returned_ind,
    a.charity_process_age_num,
    a.charity_approve_deny_ind,
    a.charity_approve_deny_user_id,
    a.approval_level_1_user_id,
    a.approval_level_1_date,
    a.approval_level_2_user_id,
    a.approval_level_2_date,
    a.approval_level_3_user_id,
    a.approval_level_3_date,
    a.approval_level_4_user_id,
    a.approval_level_4_date,
    a.approval_level_5_user_id,
    a.approval_level_5_date,
    a.bank_statement_returned_ind,
    a.appl_completed_user_id,
    a.credit_report_returned_ind,
    a.approval_level_num,
    a.charity_denial_amt,
    a.denial_reason_code,
    a.discount_amt,
    a.discount_pct,
    a.poverty_level_by_dos_ind,
    a.extenuating_circumstance_code,
    a.extenuating_circumstance_other_desc,
    a.charity_review_end_date,
    a.faa_returned_ind,
    a.faa_flag_date,
    a.faa_family_size_num,
    a.fed_1040_returned_ind,
    a.household_income_amt,
    a.unemployed_last_work_date,
    a.fed_poverty_guideline_met_ind,
    a.other_document_returned_ind,
    a.other_document_desc,
    a.charity_poverty_level_num,
    a.qmb_returned_ind,
    a.sa_approve_deny_flag,
    a.sa_family_size_num,
    a.sa_income_amt,
    a.sa_povery_level_num,
    a.sa_response_date,
    a.sa_sent_date,
    a.send_to_sa_value_ind,
    a.state_tax_returned_ind,
    a.w2_returned_ind,
    a.employer_wage_return_ind,
    a.resp_party_weekly_income_amt,
    a.resp_party_monthly_income_amt,
    a.resp_party_yearly_income_amt,
    a.spouse_weekly_income_amt,
    a.spouse_monthly_income_amt,
    a.spouse_yearly_income_amt,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.collection_charity_detail AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
