-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/collection_encounter_detail_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.collection_encounter_detail_eom AS SELECT
    a.patient_dw_id,
    a.reporting_date,
    substr(format_date('%Y%m', date_add(date_trunc(a.reporting_date, MONTH), interval 0 MONTH)), 1, 6) AS rptg_period,
    -1 * (a.day_interval_sid + 100) AS day_interval_sid,
    a.liability_sequence_number,
    a.artiva_instance_code,
    a.company_code,
    a.coid,
    a.unit_num,
    a.pat_acct_num,
    a.patient_type_code,
    a.account_status_code,
    a.lob_grp_code,
    a.iplan_id,
    a.payor_dw_id,
    a.discharge_age_month_sid,
    a.last_worked_age_month_sid,
    a.delinquent_days_age_sid,
    a.encounter_financial_class_code,
    a.liability_financial_class_code,
    a.hic_claim_num,
    a.claim_num,
    a.check_num_an,
    a.medical_record_num,
    a.early_out_hold_ind,
    a.vendor_id,
    a.prev_vendor_id,
    a.liability_phase_status_desc,
    a.prev_liability_phase_desc,
    a.phase_change_date,
    a.status_desc,
    a.prior_status_desc,
    a.denial_status_code,
    a.bad_debt_reason_code,
    a.encounter_date,
    a.wait_date,
    a.denial_date,
    a.claim_submit_date,
    a.final_bill_date,
    a.early_out_date,
    a.liability_last_billed_date,
    a.liability_last_worked_date,
    a.last_worked_age_days_cnt,
    a.prev_pool_assignment_id,
    a.prev_pool_date,
    a.current_pool_assignment_id,
    a.pool_responsible_dept_name,
    a.inclusion_flag,
    a.action_code,
    a.result_code,
    a.last_action_date,
    a.last_action_time,
    a.last_action_updt_by_user_id,
    a.service_code,
    a.delinquent_days_cnt,
    a.cc_activity_type_id,
    a.cc_prev_activity_type_id,
    a.total_billed_charge_amt,
    a.non_bill_charge_amt,
    a.encounter_balance_amt,
    a.original_balance_amt,
    a.current_balance_amt,
    a.liability_level_code,
    a.total_adjustment_amt,
    a.total_payment_amt,
    a.placement_amt,
    a.placement_date,
    a.placement_level_num,
    a.appeal_flag,
    a.appeal_source_system_code,
    a.denial_code,
    a.appeal_disp_code,
    a.appeal_level_num,
    a.appeal_seq_num,
    a.appeal_source_system_id,
    a.appeal_sent_date,
    a.appeal_follow_up_date,
    a.appeal_closing_date,
    a.appeal_amt,
    a.admission_date,
    a.discharge_date,
    a.last_claim_status_rspn_date,
    a.last_claim_status_rspn_code,
    a.last_claim_status_rspn_type_code,
    a.last_claim_status_rspn_pblm_code,
    a.last_claim_status_rspn_scat_id,
    a.user_alert_comment_text,
    a.user_alert_edit_date_time,
    a.alert_created_by_user_id,
    a.user_alert_expr_date,
    a.billing_history_ind,
    a.insgn_account_balance_amt,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.collection_encounter_detail AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
  WHERE a.day_interval_sid < 0
;
