-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/facility.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.facility AS SELECT
    a.coid,
    a.company_code,
    a.data_source_code,
    a.eff_from_date,
    a.eff_to_date,
    a.unit_num,
    a.facility_name,
    a.lob_code,
    a.lob_name,
    a.sub_lob_code,
    a.sub_lob_name,
    a.facility_status_code,
    a.financial_jv_code,
    a.own_managed_code,
    a.own_percentage,
    a.fiscal_year_end_month,
    a.medicare_year_end_month,
    a.medicare_provider_num,
    a.beds_licensed,
    a.beds_in_operation,
    a.income_category,
    a.income_category_code,
    a.cons_income_category_code,
    a.gl_consolidation_ind,
    a.gl_standard_chart_id,
    a.gl_consolidation_coid,
    a.gl_interco_coid,
    a.gl_interco_account,
    a.coid_prime_account,
    a.previous_owner_code,
    a.previous_owner_name,
    a.company_code_actual,
    a.company_code_payroll,
    a.company_code_irs,
    a.company_add_date,
    a.acquired_date,
    a.sold_date,
    a.open_date,
    a.close_date,
    a.incorporation_date,
    a.incorporation_state_code,
    a.federal_tax_id,
    a.legal_name,
    a.entity_code,
    a.time_zone,
    a.time_zone_actual,
    a.process_group,
    a.process_zone,
    a.pa_default_subunit_num,
    a.full_time_employees,
    a.part_time_employees,
    a.full_time_equivalents,
    a.state_code,
    a.city_tax_rate,
    a.state_tax_rate,
    a.local_tax_rate,
    a.lease_foot_quantity,
    a.billing_code,
    a.shipping_code,
    a.payroll_cycle_code,
    a.system_industry_code,
    a.naics_code,
    a.qmirs_only_flag,
    a.unit_prefix,
    a.web_address,
    a.mainframe_access_method,
    a.report_format,
    a.current_rdc,
    a.smart_processor,
    a.collection_processor,
    a.meditech_mnemonic,
    a.meditech_network,
    a.meditech_network_name,
    a.meditech_release,
    a.medarch_processor,
    a.teaching_facility_ind,
    a.urban_facility_ind,
    a.lawson_payroll_conversion_date,
    a.lawson_hr_conversion_date,
    a.lawson_hr_company_num,
    a.actual_reporting_level,
    a.ledger_type_code,
    a.pas_coid,
    a.pas_status,
    a.same_store_type_code,
    a.same_store_sub_type_code,
    a.company_code_operations,
    a.legal_entity_status_code,
    a.indenture_1993_debt_type_code,
    a.guarantor_status_ind,
    a.principal_property_status_ind,
    a.wholly_hca_owned_ind,
    a.mortgagor_status_ind,
    a.european_subsidiary_ind,
    a.indenture_2006_debt_type_code,
    a.partnership_control_code,
    a.abs_facility_ind
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.facility AS a
    CROSS JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b
  WHERE a.coid = b.co_id
   AND a.company_code = b.company_code
   AND b.user_id = session_user()
;
