-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/facility_iplan_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.facility_iplan_pf AS SELECT
    a.payor_dw_id,
    a.coid,
    a.company_code,
    a.iplan_id,
    a.plan_desc,
    a.payor_name,
    a.payor_id,
    a.major_payor_group_id,
    a.payor_sub_id,
    a.sub_payor_group_id,
    a.eff_from_date,
    a.eff_to_date,
    a.iplan_financial_class_code,
    a.iplan_inactive_date,
    a.payment_model_num,
    a.payor_auth_length_stay_days,
    a.length_of_stay_extension_num,
    a.verification_ind,
    a.precertification_ind,
    a.recertification_day_count,
    a.pro_review_ind,
    a.charge_benefit_code,
    a.op_coinsurance_code,
    a.emc_process_code,
    a.icd10_conversion_date,
    a.federal_tax_identifier,
    a.subunit_tax_identifier,
    a.govt_rpt_id,
    a.separate_ub82_ind,
    a.hold_claim_ind,
    a.ub92_format_code,
    a.b1500_format_code,
    a.b1500_coding_scheme_code,
    a.ancillary_chg_incl_room_ind,
    a.ancillary_maximum_amt,
    a.processor_id,
    a.processor_sub_id,
    a.accelerated_billing_code,
    a.bill_code,
    a.log_id,
    a.type_of_claim_code,
    a.health_plan_id,
    a.inpatient_npi,
    a.outpatient_npi,
    a.inpatient_taxonomy_code,
    a.outpatient_taxonomy_code,
    a.hosp_acquired_cond_ind,
    a.notice_of_adm_file,
    a.notice_of_adm_ind,
    a.admit_disch_date_flag,
    a.outpatient_pps_flag,
    a.outpatient_pps_flag_tricare,
    a.outpatient_apc_edit_ind,
    a.meditech_mnemonic,
    a.inpatient_provider_number,
    a.outpatient_provider_number,
    a.part_b_ind,
    a.part_b_ext_benf_ind,
    a.part_b_ext_full_op_benf_ind,
    a.bill_drug_waste_type,
    a.po_modifier_ind,
    a.uninsured_ind,
    a.payer_type_code,
    a.reimbursement_type_code,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.facility_iplan_pf AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
