-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/mcare_bad_debt_crossover_dtl.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.mcare_bad_debt_crossover_dtl AS SELECT
    a.reporting_date,
    a.patient_dw_id,
    a.company_code,
    a.coid,
    a.unit_num,
    a.pat_acct_num,
    a.admission_date,
    a.discharge_date,
    a.final_bill_date,
    a.reason_desc,
    a.account_payer_status_desc,
    a.project_name,
    a.account_status_code,
    a.patient_type_code,
    a.iplan_id_ins1,
    a.iplan_id_ins2,
    a.iplan_id_ins3,
    a.plan_desc_ins1,
    a.plan_desc_ins2,
    a.plan_desc_ins3,
    a.financial_class_code_ins1,
    a.financial_class_code_ins2,
    a.financial_class_code_ins3,
    a.bill_code_ins1,
    a.bill_code_ins2,
    a.bill_code_ins3,
    a.procedure_code,
    a.total_account_balance_amt,
    a.total_expt_payment_amt,
    a.total_payment_amt,
    a.total_variance_adjustment_amt,
    a.total_pat_responsibility_amt,
    a.primary_mcare_responsibility_amt,
    a.patient_payment_amt,
    a.primary_payment_amt,
    a.secondary_payment_amt,
    a.latest_primary_payment_date,
    a.ep_payment_create_date,
    a.ep_payment_effective_post_date,
    a.era_create_date,
    a.check_date,
    a.service_carc_claim_carc_flag,
    a.service_carc_ind,
    a.service_carc_denial_cd_23_ind,
    a.service_carc_denial_cd_45_ind,
    a.service_carc_denial_cd_97_ind,
    a.calc_claim_carc_23_45_97_ind,
    a.claim_carc_ind,
    a.claim_carc_denial_cd_23_ind,
    a.claim_carc_denial_cd_45_ind,
    a.claim_carc_denial_cd_97_ind,
    a.addl_service_carc_ind,
    a.service_carc_denial_cd_22_ind,
    a.service_carc_denial_cd_26_ind,
    a.service_carc_denial_cd_27_ind,
    a.service_carc_denial_cd_29_ind,
    a.service_carc_denial_cd_31_ind,
    a.service_carc_denial_cd_109_ind,
    a.calc_addl_claim_carc_ind,
    a.addl_claim_carc_ind,
    a.claim_carc_denial_cd_22_ind,
    a.claim_carc_denial_cd_26_ind,
    a.claim_carc_denial_cd_27_ind,
    a.claim_carc_denial_cd_29_ind,
    a.claim_carc_denial_cd_31_ind,
    a.claim_carc_denial_cd_109_ind,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.mcare_bad_debt_crossover_dtl AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
