-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/payor_audit_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.payor_audit_detail AS SELECT
    a.audit_record_sid,
    a.patient_dw_id,
    a.reporting_date,
    a.daily_month_code,
    a.account_create_timestamp,
    a.appeal_create_timestamp,
    a.doc_ctrl_num,
    a.last_appeal_update_timestamp,
    a.last_appeal_update_user_id,
    a.work_queue_desc,
    a.company_code,
    a.coid,
    a.unit_num,
    a.pat_acct_num,
    a.month_id,
    a.audit_create_date,
    a.audit_create_user_id,
    a.financial_class_code,
    a.major_payor_code,
    a.insurance_order_num,
    a.iplan_id,
    a.letter_date,
    a.category_desc,
    a.worklist_desc,
    a.workflow_type_desc,
    a.audit_start_date,
    a.audit_initiation_date,
    a.medical_rec_requestor_entity_desc,
    a.audit_type_desc,
    a.other_audit_desc,
    a.service_start_date,
    a.service_end_date,
    a.medical_record_due_date,
    a.audit_location_desc,
    a.audit_eligibility_desc,
    a.audit_fee_required_ind,
    a.previous_audit_status_desc,
    a.audit_work_queue_desc,
    a.audit_status_desc,
    a.audit_status_date,
    a.last_audit_status_update_date,
    a.last_audit_status_update_user_id,
    a.post_audit_type_desc,
    a.work_again_date,
    a.corporate_status_desc,
    a.corporate_status_date,
    a.letter_result_desc,
    a.final_audit_outcome_desc,
    a.final_audit_outcome_date,
    a.corp_doc_control_code,
    a.ssc_doc_control_code,
    a.missing_doc_cnt,
    a.audit_schedule_date,
    a.medical_rec_release_method_desc,
    a.medical_rec_tracking_num,
    a.medical_rec_release_request_date,
    a.medical_rec_sent_date,
    a.medical_rec_missing_notification_date,
    a.payor_reference_id,
    a.collected_audit_fee_amt,
    a.additional_project_name,
    a.recurring_account_sw,
    a.risk_amt,
    a.charge_reviewed_amt,
    a.current_total_charge_amt,
    a.current_total_charge_discrepancy_amt,
    a.expected_payor_payment_amt,
    a.current_payor_payment_discrepancy_amt,
    a.initial_payor_payment_amt,
    a.current_payor_payment_amt,
    a.pre_audit_drg_code,
    a.pre_audit_drg_desc,
    a.payor_drg_code,
    a.payer_drg_desc,
    a.claim_guid,
    a.post_audit_drg,
    a.post_audit_drg_desc,
    a.appeal_create_user_id,
    a.appeal_level_1_due_date,
    a.appeal_level_1_letter_sent_date,
    a.appeal_level_1_followup_date,
    a.appeal_level_1_response_date,
    a.appeal_level_1_decision_desc,
    a.appeal_level_2_due_date,
    a.appeal_level_2_letter_sent_date,
    a.appeal_level_2_followup_date,
    a.appeal_level_2_response_date,
    a.appeal_level_2_decision_desc,
    a.appeal_level_3_due_date,
    a.appeal_level_3_letter_sent_date,
    a.appeal_level_3_followup_date,
    a.appeal_level_3_response_date,
    a.appeal_level_3_decision_desc,
    a.appeal_level_4_due_date,
    a.appeal_level_4_letter_sent_date,
    a.appeal_level_4_followup_date,
    a.appeal_level_4_response_date,
    a.appeal_level_4_decision_desc,
    a.appeal_level_5_due_date,
    a.appeal_level_5_letter_sent_date,
    a.appeal_level_5_followup_date,
    a.appeal_level_5_response_date,
    a.appeal_level_5_decision_desc,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.payor_audit_detail AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpbs_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
