-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/reimbursement_discrepancy.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.reimbursement_discrepancy AS SELECT
    bv.company_code,
    bv.coid,
    bv.patient_dw_id,
    bv.payor_dw_id,
    bv.iplan_insurance_order_num,
    bv.eor_log_date,
    bv.log_id,
    bv.log_sequence_num,
    bv.eff_from_date,
    bv.pat_acct_num,
    bv.iplan_id,
    bv.length_of_stay_days_num,
    bv.eor_drg_code,
    bv.eor_hipps_code,
    bv.eor_payment_amt,
    bv.remittance_date,
    bv.ra_log_date,
    bv.ra_payment_date,
    bv.ra_drg_code,
    bv.ra_hipps_code,
    bv.ra_covered_days_num,
    bv.ra_total_charge_amt,
    bv.ra_non_covered_charge_amt,
    bv.ra_gross_reimbursement_amt,
    bv.ra_ded_coins_amt,
    bv.ra_payment_amt,
    bv.ra_contractual_allowance_amt,
    bv.ra_copay_amt,
    bv.ra_coinsurance_amt,
    bv.ra_net_billed_charge_amt,
    bv.ra_deductible_amt,
    bv.ra_total_deductible_amt,
    bv.ra_blood_deductible_amt,
    bv.ra_lab_payment_amt,
    bv.ra_therapy_payment_amt,
    bv.ra_primary_payor_payment_amt,
    bv.ra_outlier_payment_amt,
    bv.ra_capital_payment_amt,
    bv.ra_denied_charge_amt,
    bv.ra_net_apc_service_amt,
    bv.ra_net_fee_schedule_amt,
    bv.over_under_payment_amt,
    bv.actual_payment_amt,
    bv.discrepancy_origination_date,
    bv.discrepancy_day_count,
    bv.var_covered_days_num,
    bv.var_total_charge_amt,
    bv.var_non_covered_charge_amt,
    bv.var_net_billed_charge_amt,
    bv.var_gross_reimbursement_amt,
    bv.var_deductible_amt,
    bv.var_coinsurance_amt,
    bv.var_ded_coins_amt,
    bv.var_blood_deductible_amt,
    bv.var_insurance_payment_amt,
    bv.var_primary_payor_pmt_amt,
    bv.var_capital_payment_amt,
    bv.var_lab_payment_amt,
    bv.var_outlier_payment_amt,
    bv.var_therapy_payment_amt,
    bv.var_contractual_allowance_amt,
    bv.var_copay_amt,
    bv.var_covered_charge_amt,
    bv.var_net_apc_service_amt,
    bv.var_net_fee_schedule_amt,
    bv.inpatient_outpatient_ind,
    bv.primary_reason_assignment_cnt,
    bv.discrepancy_reason_code_1,
    bv.reason_assignment_date_1,
    bv.discrepancy_reason_code_2,
    bv.reason_assignment_date_2,
    bv.discrepancy_reason_code_3,
    bv.reason_assignment_date_3,
    bv.discrepancy_reason_code_4,
    bv.reason_assignment_date_4,
    bv.comments,
    bv.work_date,
    bv.last_racf_id,
    bv.last_racf_date,
    bv.data_source_code,
    bv.total_account_balance_amt,
    bv.ar_bill_thru_date,
    bv.cc_calc_id,
    bv.cc_account_activity_id,
    bv.cc_reason_id,
    bv.cc_account_payer_status_id,
    bv.last_update_date,
    bv.dw_last_update_date_time,
    bv.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.reimbursement_discrepancy AS bv
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS sf ON bv.coid = sf.co_id
     AND sf.user_id = session_user()
;
