-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/reimbursement_discrepancy_eom_hist.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.reimbursement_discrepancy_eom_hist AS SELECT
    a.company_code,
    a.coid,
    a.patient_dw_id,
    a.payor_dw_id,
    a.iplan_insurance_order_num,
    a.eor_log_date,
    a.log_id,
    a.log_sequence_num,
    a.discrepancy_resolved_date,
    a.eff_from_date,
    a.pat_acct_num,
    a.iplan_id,
    a.length_of_stay_days_num,
    a.eor_drg_code,
    a.eor_hipps_code,
    a.eor_payment_amt,
    a.remittance_date,
    a.ra_log_date,
    a.ra_payment_date,
    a.ra_drg_code,
    a.ra_hipps_code,
    a.ra_covered_days_num,
    a.ra_total_charge_amt,
    a.ra_non_covered_charge_amt,
    a.ra_gross_reimbursement_amt,
    a.ra_ded_coins_amt,
    a.ra_payment_amt,
    a.ra_contractual_allowance_amt,
    a.ra_copay_amt,
    a.ra_coinsurance_amt,
    a.ra_net_billed_charge_amt,
    a.ra_deductible_amt,
    a.ra_total_deductible_amt,
    a.ra_blood_deductible_amt,
    a.ra_lab_payment_amt,
    a.ra_therapy_payment_amt,
    a.ra_primary_payor_payment_amt,
    a.ra_outlier_payment_amt,
    a.ra_capital_payment_amt,
    a.ra_denied_charge_amt,
    a.ra_net_apc_service_amt,
    a.ra_net_fee_schedule_amt,
    a.over_under_payment_amt,
    a.actual_payment_amt,
    a.discrepancy_origination_date,
    a.discrepancy_day_count,
    a.resolve_reason_code,
    a.discrepancy_status_code,
    a.var_covered_days_num,
    a.var_total_charge_amt,
    a.var_non_covered_charge_amt,
    a.var_net_billed_charge_amt,
    a.var_gross_reimbursement_amt,
    a.var_deductible_amt,
    a.var_coinsurance_amt,
    a.var_ded_coins_amt,
    a.var_blood_deductible_amt,
    a.var_insurance_payment_amt,
    a.var_primary_payor_pmt_amt,
    a.var_capital_payment_amt,
    a.var_lab_payment_amt,
    a.var_outlier_payment_amt,
    a.var_therapy_payment_amt,
    a.var_contractual_allowance_amt,
    a.var_copay_amt,
    a.var_covered_charge_amt,
    a.var_net_apc_service_amt,
    a.var_net_fee_schedule_amt,
    a.inpatient_outpatient_ind,
    a.primary_reason_assignment_cnt,
    a.discrepancy_reason_code_1,
    a.reason_assignment_date_1,
    a.discrepancy_reason_code_2,
    a.reason_assignment_date_2,
    a.discrepancy_reason_code_3,
    a.reason_assignment_date_3,
    a.discrepancy_reason_code_4,
    a.reason_assignment_date_4,
    a.comments,
    a.work_date,
    a.last_racf_id,
    a.last_racf_date,
    a.data_source_code,
    a.total_account_balance_amt,
    a.ar_bill_thru_date,
    a.cc_calc_id,
    a.cc_account_activity_id,
    a.cc_reason_id,
    a.cc_account_payer_status_id,
    a.last_update_date,
    a.dw_last_update_date_time,
    a.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.reimbursement_discrepancy_eom_hist AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
  WHERE a.discrepancy_status_code = 'O'
;
