-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/remittance_claim.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.remittance_claim AS SELECT
    a.claim_guid,
    a.payment_guid,
    a.patient_dw_id,
    a.audit_date,
    a.coid,
    a.delete_ind,
    a.delete_date,
    a.unit_num,
    a.company_code,
    a.ssc_coid,
    a.payor_patient_id,
    a.pat_acct_num,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.patient_last_name
    END AS patient_last_name,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.patient_first_name
    END AS patient_first_name,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.patient_middle_initial
    END AS patient_middle_initial,
    a.mpi_ind,
    a.iplan_id,
    a.ep_calc_iplan_id,
    a.iplan_insurance_order_num,
    a.medical_record_num,
    a.payer_claim_control_number,
    a.stmt_cover_from_date,
    a.stmt_cover_to_date,
    a.received_date,
    a.mpi_corrected_discharge_date,
    a.patient_type_code_pos1,
    a.financial_class_code,
    a.total_charge_amt,
    a.mpi_calc_charge_amt,
    a.payment_amt,
    a.ep_calc_denial_amount,
    a.ep_calc_contractual_adj_amt,
    a.mpi_contractual_adj_amt,
    a.corrected_contractual_adj_amt,
    a.net_benefit_amt,
    a.covered_charge_amt,
    a.mpi_calc_payor_previous_payment_amt,
    a.ep_calc_noncovered_charge_amt,
    a.mpi_calc_non_covered_charge_amt,
    a.ep_calc_deductible_amt,
    a.mpi_calc_deductible_amt,
    a.ep_calc_blood_deductible_amt,
    a.ep_calc_coinsurance_amt,
    a.mpi_calc_coinsurance_amt,
    a.ep_calc_primary_payor_payment_amt,
    a.patient_liability_amount,
    a.capital_amt,
    a.ep_calc_discount_amt,
    a.disproportionate_share_amt,
    a.drg_disproportionate_share_amt,
    a.drg_amt,
    a.drg_code,
    a.mpi_calc_drg_code,
    a.mpi_calc_drg_grouper_code,
    a.federal_specific_drg_amt,
    a.hospital_specific_drg_amt,
    a.drg_weight_amt,
    a.hcpcs_charge_amt,
    a.hcpcs_payment_amt,
    a.indirect_medical_education_amt,
    a.indirect_teaching_amt,
    a.interest_amt,
    a.ep_calc_lab_charge_amt,
    a.ep_calc_lab_payment_amt,
    a.pps_opr_federal_specific_drg_amt,
    a.mpi_calc_non_billed_charge_amt,
    a.mpi_calc_net_benefit_amt,
    a.ep_calc_non_payable_professional_fee_amt,
    a.old_capital_amt,
    a.operating_outlier_amt,
    a.outlier_amt,
    a.outpatient_reimibursement_rate_amt,
    a.ep_calc_therapy_charge_amt,
    a.ep_calc_therapy_payment_amt,
    a.pps_capital_outlier_amt,
    a.ins_covered_day_cnt,
    a.ep_calc_covered_day_cnt,
    a.noncovered_day_cnt,
    a.cost_report_day_cnt,
    a.discharge_fraction_pct,
    a.lifetime_psychiatric_day_cnt,
    a.contractual_adj_amt_procedure_code,
    a.payment_amt_procedure_code,
    a.logging_flag,
    a.logging_type_code,
    a.mpi_calc_interim_bill_ind,
    a.claim_status_code,
    a.ep_calc_status_code,
    a.ep_calc_denial_code_ind,
    a.mpi_calc_denial_code_ind,
    a.type_of_claim_code,
    a.type_of_bill_code,
    a.ep_calc_balanced_ind,
    a.discount_applied_ind,
    a.ep_calc_plb_opay_rcvy_trx_ind,
    a.ep_calc_internal_denial_code,
    a.concuity_acct_ind,
    a.mia_switch_ind,
    a.moa_switch_ind,
    a.mia_pps_capital_exception_amt,
    a.casemix_ind,
    a.zero_default_iplan_ind,
    a.trx_tracking_not_released_ind,
    a.qmb_switch_ind,
    a.ep_calc_denial_code_1,
    a.ep_calc_denial_code_2,
    a.ep_calc_denial_code_3,
    a.ep_calc_denial_code_4,
    a.ep_calc_denial_code_5,
    a.ep_calc_denial_code_6,
    a.ep_calc_denial_code_7,
    a.ep_calc_denial_code_8,
    a.ep_calc_denial_code_9,
    a.ep_calc_denial_code_10,
    a.ep_calc_handling_ind,
    a.crossover_payor_name,
    a.ep_calc_payor_category_code,
    a.secondary_payor_flag,
    a.ep_calc_prim_itnl_pyr_code,
    a.ep_calc_secn_itnl_pyr_code,
    a.ep_calc_tert_itnl_pyr_code,
    a.corrected_priority_payor_sid,
    a.cob_carrier_sid,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.corrected_subscriber_last_name
    END AS corrected_subscriber_last_name,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.corrected_subscriber_first_name
    END AS corrected_subscriber_first_name,
    CASE
      WHEN session_user() = pn.userid THEN '***'
      ELSE a.corrected_subscriber_middle_name
    END AS corrected_subscriber_middle_name,
    a.corrected_subscriber_health_ins_num,
    a.remittance_subscriber_sid,
    a.remittance_oth_subscriber_sid,
    a.remittance_rendering_provider_sid,
    a.supplemental_amt_qlfr_code_1,
    a.supplemental_amt_1,
    a.supplemental_amt_qlfr_code_2,
    a.supplemental_amt_2,
    a.supplemental_amt_qlfr_code_3,
    a.supplemental_amt_3,
    a.supplemental_amt_qlfr_code_4,
    a.supplemental_amt_4,
    a.supplemental_amt_qlfr_code_5,
    a.supplemental_amt_5,
    a.supplemental_amt_qlfr_code_6,
    a.supplemental_amt_6,
    a.supplemental_amt_qlfr_code_7,
    a.supplemental_amt_7,
    a.supplemental_amt_qlfr_code_8,
    a.supplemental_amt_8,
    a.supplemental_amt_qlfr_code_9,
    a.supplemental_amt_9,
    a.supplemental_amt_qlfr_code_10,
    a.supplemental_amt_10,
    a.supplemental_amt_qlfr_code_11,
    a.supplemental_amt_11,
    a.supplemental_amt_qlfr_code_12,
    a.supplemental_amt_12,
    a.supplemental_amt_qlfr_code_13,
    a.supplemental_amt_13,
    a.supplemental_qty_qlfr_code_1,
    a.supplemental_qty_1,
    a.supplemental_qty_qlfr_code_2,
    a.supplemental_qty_2,
    a.supplemental_qty_qlfr_code_3,
    a.supplemental_qty_3,
    a.supplemental_qty_qlfr_code_4,
    a.supplemental_qty_4,
    a.supplemental_qty_qlfr_code_5,
    a.supplemental_qty_5,
    a.supplemental_qty_qlfr_code_6,
    a.supplemental_qty_6,
    a.supplemental_qty_qlfr_code_7,
    a.supplemental_qty_7,
    a.supplemental_qty_qlfr_code_8,
    a.supplemental_qty_8,
    a.supplemental_qty_qlfr_code_9,
    a.supplemental_qty_9,
    a.supplemental_qty_qlfr_code_10,
    a.supplemental_qty_10,
    a.supplemental_qty_qlfr_code_11,
    a.supplemental_qty_11,
    a.supplemental_qty_qlfr_code_12,
    a.supplemental_qty_12,
    a.supplemental_qty_qlfr_code_13,
    a.supplemental_qty_13,
    a.supplemental_qty_qlfr_code_14,
    a.supplemental_qty_14,
    a.rarc_code_1,
    a.rarc_code_2,
    a.rarc_code_3,
    a.rarc_code_4,
    a.rarc_code_5,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.remittance_claim AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
    LEFT OUTER JOIN (
      SELECT
          security_mask_and_exception.userid,
          security_mask_and_exception.masked_column_code
        FROM
          `hca-hin-dev-cur-parallon`.edw_sec_base_views.security_mask_and_exception
        WHERE security_mask_and_exception.userid = session_user()
         AND security_mask_and_exception.masked_column_code = 'PN'
    ) AS pn ON pn.userid = session_user()
;
