-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/remittance_payment.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.remittance_payment AS SELECT
    a.payment_guid,
    a.check_num_an,
    a.check_date,
    a.check_amt,
    a.interchange_sender_id,
    a.provider_level_adj_id,
    a.remittance_payor_sid,
    a.remittance_payee_sid,
    a.audit_date,
    a.delete_ind,
    a.delete_date,
    a.coid,
    a.company_code,
    a.unit_num,
    a.era_create_date,
    a.bill_process_date,
    a.ep_effective_post_date,
    a.ep_create_date,
    a.bill_charge_amt,
    a.covered_charge_amt,
    a.ep_non_covered_charge_amt,
    a.ep_coinsurance_amt,
    a.ep_contractual_adj_amt,
    a.ep_deductible_amt,
    a.ep_denial_amt,
    a.drg_amt,
    a.federal_specific_drg_amt,
    a.ep_calc_blood_deductible_amt,
    a.ep_calc_hcpcs_charge_amt,
    a.ep_calc_hcpcs_payment_amt,
    a.apc_amt,
    a.capital_amt,
    a.disproportionate_share_amt,
    a.indirect_teaching_amt,
    a.interest_amt,
    a.claim_payment_amt,
    a.ep_lab_charge_amt,
    a.ep_lab_payment_amt,
    a.ep_nonpayable_professional_fee_amt,
    a.outlier_amt,
    a.patient_liability_amt,
    a.ep_primary_insurance_payment_amt,
    a.ep_therapy_charge_amt,
    a.ep_therapy_payment_amt,
    a.ins_covered_day_cnt,
    a.ep_calc_covered_day_cnt,
    a.noncovered_day_cnt,
    a.claim_cnt,
    a.ep_discharge_cnt,
    a.cost_report_day_cnt,
    a.remittance_seq_num,
    a.ep_plb_key_num,
    a.boa_lockbox_num,
    a.interchange_receiver_id,
    a.interchange_sender_qualifier_code,
    a.interchange_sender_code,
    a.interchange_receiver_id_qualifier_code,
    a.interchange_receiver_code,
    a.transmission_sending_code,
    a.transmission_receiving_code,
    a.bill_type_code,
    a.payor_default_logging_type_code,
    a.ep_payor_batch_code,
    a.rac_ind,
    a.payor_live_ind,
    a.lab_transaction_breakout_ind,
    a.comment_transaction_ind,
    a.internal_denial_transaction_ind,
    a.discharge_date_replacement_ind,
    a.total_charges_replacement_ind,
    a.patient_type_replacement_ind,
    a.drg_replacement_ind,
    a.apply_secondary_rule_ind,
    a.apply_recover_rule_ind,
    a.apply_mother_baby_rule_ind,
    a.apply_total_charges_rule_ind,
    a.apply_noncovered_charges_rule_ind,
    a.apply_er_patient_rule_ind,
    a.apply_recover_true_up_rule_ind,
    a.apply_non_recover_true_up_rule_ind,
    a.calculated_covered_days_ind,
    a.alternate_sn_format_ind,
    a.plb_recovery_transaction_ind,
    a.duplicate_direct_payer_ind,
    a.not_post_payer_ind,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.remittance_payment AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
