-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/resolved_discrepancy_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_views.resolved_discrepancy_pf AS SELECT
    rd.company_code,
    rd.coid,
    rd.patient_dw_id,
    rd.payor_dw_id,
    rd.iplan_insurance_order_num,
    rd.eor_log_date,
    rd.log_id,
    rd.log_sequence_num,
    rd.discrepancy_resolved_date,
    rd.eff_from_date,
    rd.pat_acct_num,
    rd.iplan_id,
    rd.length_of_stay_days_num,
    rd.eor_drg_code,
    rd.eor_hipps_code,
    rd.eor_payment_amt,
    rd.remittance_date,
    rd.ra_log_date,
    rd.ra_payment_date,
    rd.ra_drg_code,
    rd.ra_hipps_code,
    rd.ra_covered_days_num,
    rd.ra_total_charge_amt,
    rd.ra_non_covered_charge_amt,
    rd.ra_gross_reimbursement_amt,
    rd.ra_ded_coins_amt,
    rd.ra_payment_amt,
    rd.ra_contractual_allowance_amt,
    rd.ra_copay_amt,
    rd.ra_coinsurance_amt,
    rd.ra_net_billed_charge_amt,
    rd.ra_deductible_amt,
    rd.ra_total_deductible_amt,
    rd.ra_blood_deductible_amt,
    rd.ra_lab_payment_amt,
    rd.ra_therapy_payment_amt,
    rd.ra_primary_payor_payment_amt,
    rd.ra_outlier_payment_amt,
    rd.ra_capital_payment_amt,
    rd.ra_denied_charge_amt,
    rd.ra_net_apc_service_amt,
    rd.ra_net_fee_schedule_amt,
    rd.over_under_payment_amt,
    rd.actual_payment_amt,
    rd.discrepancy_origination_date,
    rd.discrepancy_inactive_date,
    rd.discrepancy_day_count,
    rd.resolve_reason_code,
    rd.var_covered_days_num,
    rd.var_total_charge_amt,
    rd.var_non_covered_charge_amt,
    rd.var_net_billed_charge_amt,
    rd.var_gross_reimbursement_amt,
    rd.var_deductible_amt,
    rd.var_coinsurance_amt,
    rd.var_ded_coins_amt,
    rd.var_blood_deductible_amt,
    rd.var_insurance_payment_amt,
    rd.var_primary_payor_pmt_amt,
    rd.var_capital_payment_amt,
    rd.var_lab_payment_amt,
    rd.var_outlier_payment_amt,
    rd.var_therapy_payment_amt,
    rd.var_contractual_allowance_amt,
    rd.var_copay_amt,
    rd.var_covered_charge_amt,
    rd.var_net_apc_service_amt,
    rd.var_net_fee_schedule_amt,
    rd.inpatient_outpatient_ind,
    rd.primary_reason_assignment_cnt,
    rd.discrepancy_reason_code_1,
    rd.reason_assignment_date_1,
    rd.discrepancy_reason_code_2,
    rd.reason_assignment_date_2,
    rd.discrepancy_reason_code_3,
    rd.reason_assignment_date_3,
    rd.discrepancy_reason_code_4,
    rd.reason_assignment_date_4,
    rd.comments,
    rd.work_date,
    rd.last_racf_id,
    rd.last_racf_date,
    rd.data_source_code,
    rd.total_account_balance_amt,
    rd.ar_bill_thru_date,
    rd.cc_calc_id,
    rd.cc_account_activity_id,
    rd.cc_reason_id,
    rd.cc_account_payer_status_id,
    rd.last_update_date,
    rd.dw_last_update_date_time,
    rd.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs_base_views.resolved_discrepancy_pf AS rd
    INNER JOIN `hca-hin-dev-cur-parallon`.edwpf_base_views.secref_facility AS sf ON rd.coid = sf.co_id
     AND sf.user_id = session_user()
;
