--WEEKLY SUMMARY FOR POWER BI    				(UPDATED 11/03/2020)
SELECT 
    (CASE
        WHEN STUSER.CSUAACCESS1 = 'CLIENTCOLL' THEN 'CLIENT-TAM'
        ELSE 'TAMPA' END) AS PASID   --PLACEHOLDER UNTIL TABLE CHANGES INTEGRATE
    , 'TAM' AS CSUASSC		--PLACEHOLDER UNTIL TABLE CHANGES INTEGRATE
	,STUSER.CSUAACCESS1
	,ACCT_Lvl_STUSER.CSUAACCESS1 AS ACCT_Lvl_USER_CSUAACCESS1
    , STUSERAUDIT.CSUAMONTHLYREVIEWID, STUSERAUDIT.STUAMONTH, STUSERAUDIT.STUAYEAR, STUSERAUDIT.HCUAREVIEWPERIOD
    , STUSERAUDIT.STUARVWSTART, STUSERAUDIT.STUARVWEND, STUSERAUDIT.STUAID, STUSERAUDIT.STUAUSERID, STUSER.UAFULLNAME ,STUSERAUDITACCT.STUAAUSERID
--    , SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS) AS AuditEarnedPoints, SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS) as AuditPossiblePoints
   /* , (CASE
        WHEN SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS) IS NULL THEN 0
        ELSE SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS)
        END) AS AuditEarnedPoints
    , (CASE
        WHEN SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS) IS NULL THEN 0
        ELSE SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS)
        END) AS AuditPossiblePoints
		*/
	,	STUSERAUDITACCT.STUAAEARNEDPOINTS,STUSERAUDITACCT.STUAAPOSSIBLEPOINTS
    , STUSERAUDIT.STUAPHASE
    , (CASE 
        WHEN STUSERAUDIT.CSUASTATUS IS NULL THEN 'PENDING'
        ELSE STUSERAUDIT.CSUASTATUS
        END) AS CSUASTATUS
    , STUSERAUDIT.CSUAUSERRESPONSE
    , NULL AS PRIOR1_WEEK
    , NULL AS PRIOR1_SCORE
    , NULL AS PRIOR2_WEEK
    , NULL AS PRIOR2_SCORE
    , NULL AS PRIOR3_WEEK
    , NULL AS PRIOR3_SCORE   
    , NULL AS PRIOR4_WEEK
    , NULL AS PRIOR4_SCORE     
    , STUSERAUDIT.CSUASCORE, STUSERAUDIT.CSUAGOALPERCENT
    , NULL AS CurrWeekStrat
--    , (CASE
--        WHEN PW1.CSUASCORE IS NULL AND STUSERAUDIT.CSUASCORE = 0 THEN 'SAME'
--        WHEN PW1.CSUASCORE IS NULL AND STUSERAUDIT.CSUASCORE > 0 THEN 'IMPROVEMENT' --IF NO VALUE FOR PREVIOUS WEEK, THEN CURRENT WEEK IS CONSIDERED AN IMPROVEMENT
--        WHEN PW1.CSUASCORE IS NOT NULL AND STUSERAUDIT.CSUASCORE = PW1.CSUASCORE THEN 'SAME' 
--        WHEN PW1.CSUASCORE IS NOT NULL AND STUSERAUDIT.CSUASCORE > PW1.CSUASCORE THEN 'IMPROVEMENT'
--        ELSE 'DECLINE' END) AS CurrWeekStrat
    , STUSERAUDIT.CSUAREVIEWER, REVIEWER.UAFULLNAME AS REVIEWER, STUSERAUDIT.STUASUPERVISORID, SUPERVISOR.UAFULLNAME AS SUPERVISOR, STUSERAUDIT.CSUAREVIEWMTGDTE

	,STUSERAUDITACCT.STUAAAUDITID,
STUSERAUDITACCT.STUAAID,
STUSERAUDITACCT.CSUAASTATUS,
STUSERAUDITACCT.CSUAAFAHOSPNUM AS UNIT,
STUSERAUDITACCT.CSUAAENPTACCT AS ENPATACCT,
STUSERAUDITACCT.CSUAAPYIPLAN AS IPLAN,
HCPAYER.HCPYFINCLASS AS FINCLASS,
STUSERAUDITACCT.STUAASCORE ,
STUSERAUDITACCT.STUAACREATEDATE,
STUSERAUDITACCT.STUAACOMPLETEFLAG,
STUSERAUDITACCT.STUAACOMPLETEDATE,

STUSER.HCUADEPT,
ACCT_Lvl_STUSER.HCUADEPT AS ACCT_Lvl_USER_HCUADEPT,

STUSERAUDITACCT.CSUAOPTOUTREASON,
STUSERAUDITACCT.CSUAAOPTOUTWFPATH,
  (CASE 
        WHEN LEN(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT) > 150 THEN REPLACE(REPLACE((LEFT(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT,150)), char(10), ''), char(13), '') 
        ELSE REPLACE(REPLACE(STUSERAUDITACCT.CSUAAOPTOUTCOMMENT, char(10), ''), char(13), '') END) AS OPTOUTCOMMENT
		
FROM (((((((SQLUser.STUSERAUDIT STUSERAUDIT 
LEFT OUTER JOIN SQLUser.STUSERAUDITACCT STUSERAUDITACCT ON STUSERAUDIT.STUAID = STUSERAUDITACCT.STUAAAUDITID)

                      LEFT OUTER JOIN SQLUser.STUSER STUSER ON STUSERAUDIT.STUAUSERID = STUSER.USERID)
					  LEFT OUTER JOIN SQLUser.STUSER ACCT_Lvl_STUSER ON STUSERAUDITACCT.STUAAUSERID = ACCT_Lvl_STUSER.USERID)
                            LEFT OUTER JOIN SQLUser.STUSER REVIEWER ON STUSERAUDIT.CSUAREVIEWER = REVIEWER.USERID)
                                LEFT OUTER JOIN SQLUser.STUSER SUPERVISOR ON STUSERAUDIT.STUASUPERVISORID = SUPERVISOR.USERID)
								LEFT OUTER JOIN SQLUser.HCPAYER HCPAYER ON STUSERAUDITACCT.CSUAAPAYERID = HCPAYER.HCPYID)
								LEFT OUTER JOIN SQLUser.HCFACILITY HCFACILITY ON STUSERAUDITACCT.CSUAAFAHOSPNUM = HCFACILITY.CSFAHOSPNUM )
WHERE STUSERAUDIT.STUARVWEND >= '2020-11-01' --AND LEN(STUSERAUDIT.STUAUSERID) = 7
--GROUP BY STUSERAUDIT.STUAUSERID, STUSERAUDIT.STUAID