-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/collection_charity_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_base_views_dataset_name }}.collection_charity_detail
   OPTIONS(description='A daily pull from Artiva system, that has the Charity data for financial review with other EDW data.')
  AS SELECT
      collection_charity_detail.reporting_date,
      ROUND(collection_charity_detail.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      collection_charity_detail.artiva_instance_code,
      collection_charity_detail.approve_deny_date,
      collection_charity_detail.charity_review_aging_date,
      collection_charity_detail.appl_approval_level_num,
      collection_charity_detail.charity_review_start_date,
      collection_charity_detail.coid,
      collection_charity_detail.company_code,
      ROUND(collection_charity_detail.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      collection_charity_detail.iplan_id,
      collection_charity_detail.appeal_ind,
      collection_charity_detail.form_1099_returned_ind,
      collection_charity_detail.charity_process_age_num,
      collection_charity_detail.charity_approve_deny_ind,
      collection_charity_detail.charity_approve_deny_user_id,
      collection_charity_detail.approval_level_1_user_id,
      collection_charity_detail.approval_level_1_date,
      collection_charity_detail.approval_level_2_user_id,
      collection_charity_detail.approval_level_2_date,
      collection_charity_detail.approval_level_3_user_id,
      collection_charity_detail.approval_level_3_date,
      collection_charity_detail.approval_level_4_user_id,
      collection_charity_detail.approval_level_4_date,
      collection_charity_detail.approval_level_5_user_id,
      collection_charity_detail.approval_level_5_date,
      collection_charity_detail.bank_statement_returned_ind,
      collection_charity_detail.appl_completed_user_id,
      collection_charity_detail.credit_report_returned_ind,
      collection_charity_detail.approval_level_num,
      ROUND(collection_charity_detail.charity_denial_amt, 3, 'ROUND_HALF_EVEN') AS charity_denial_amt,
      collection_charity_detail.denial_reason_code,
      ROUND(collection_charity_detail.discount_amt, 3, 'ROUND_HALF_EVEN') AS discount_amt,
      ROUND(collection_charity_detail.discount_pct, 3, 'ROUND_HALF_EVEN') AS discount_pct,
      collection_charity_detail.poverty_level_by_dos_ind,
      collection_charity_detail.extenuating_circumstance_code,
      collection_charity_detail.extenuating_circumstance_other_desc,
      collection_charity_detail.charity_review_end_date,
      collection_charity_detail.faa_returned_ind,
      collection_charity_detail.faa_flag_date,
      collection_charity_detail.faa_family_size_num,
      collection_charity_detail.fed_1040_returned_ind,
      ROUND(collection_charity_detail.household_income_amt, 3, 'ROUND_HALF_EVEN') AS household_income_amt,
      collection_charity_detail.unemployed_last_work_date,
      collection_charity_detail.fed_poverty_guideline_met_ind,
      collection_charity_detail.other_document_returned_ind,
      collection_charity_detail.other_document_desc,
      collection_charity_detail.charity_poverty_level_num,
      collection_charity_detail.qmb_returned_ind,
      collection_charity_detail.sa_approve_deny_flag,
      collection_charity_detail.sa_family_size_num,
      ROUND(collection_charity_detail.sa_income_amt, 3, 'ROUND_HALF_EVEN') AS sa_income_amt,
      collection_charity_detail.sa_povery_level_num,
      collection_charity_detail.sa_response_date,
      collection_charity_detail.sa_sent_date,
      collection_charity_detail.send_to_sa_value_ind,
      collection_charity_detail.state_tax_returned_ind,
      collection_charity_detail.w2_returned_ind,
      collection_charity_detail.employer_wage_return_ind,
      ROUND(collection_charity_detail.resp_party_weekly_income_amt, 3, 'ROUND_HALF_EVEN') AS resp_party_weekly_income_amt,
      ROUND(collection_charity_detail.resp_party_monthly_income_amt, 3, 'ROUND_HALF_EVEN') AS resp_party_monthly_income_amt,
      ROUND(collection_charity_detail.resp_party_yearly_income_amt, 3, 'ROUND_HALF_EVEN') AS resp_party_yearly_income_amt,
      ROUND(collection_charity_detail.spouse_weekly_income_amt, 3, 'ROUND_HALF_EVEN') AS spouse_weekly_income_amt,
      ROUND(collection_charity_detail.spouse_monthly_income_amt, 3, 'ROUND_HALF_EVEN') AS spouse_monthly_income_amt,
      ROUND(collection_charity_detail.spouse_yearly_income_amt, 3, 'ROUND_HALF_EVEN') AS spouse_yearly_income_amt,
      collection_charity_detail.source_system_code,
      collection_charity_detail.dw_last_update_date_time
    FROM
      {{ params.param_pbs_core_dataset_name }}.collection_charity_detail
  ;
