-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/remittance_claim.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_base_views_dataset_name }}.remittance_claim
   OPTIONS(description='This table contains claim level information associated with the payment.')
  AS SELECT
      remittance_claim.claim_guid,
      remittance_claim.payment_guid,
      ROUND(remittance_claim.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      remittance_claim.audit_date,
      remittance_claim.coid,
      remittance_claim.delete_ind,
      remittance_claim.delete_date,
      remittance_claim.unit_num,
      remittance_claim.company_code,
      remittance_claim.ssc_coid,
      remittance_claim.payor_patient_id,
      ROUND(remittance_claim.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      remittance_claim.patient_last_name,
      remittance_claim.patient_first_name,
      remittance_claim.patient_middle_initial,
      remittance_claim.mpi_ind,
      remittance_claim.iplan_id,
      remittance_claim.ep_calc_iplan_id,
      remittance_claim.iplan_insurance_order_num,
      remittance_claim.medical_record_num,
      remittance_claim.payer_claim_control_number,
      remittance_claim.stmt_cover_from_date,
      remittance_claim.stmt_cover_to_date,
      remittance_claim.received_date,
      remittance_claim.mpi_corrected_discharge_date,
      remittance_claim.patient_type_code_pos1,
      remittance_claim.financial_class_code,
      ROUND(remittance_claim.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      ROUND(remittance_claim.mpi_calc_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_charge_amt,
      ROUND(remittance_claim.payment_amt, 3, 'ROUND_HALF_EVEN') AS payment_amt,
      ROUND(remittance_claim.ep_calc_denial_amount, 3, 'ROUND_HALF_EVEN') AS ep_calc_denial_amount,
      ROUND(remittance_claim.ep_calc_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_contractual_adj_amt,
      ROUND(remittance_claim.mpi_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS mpi_contractual_adj_amt,
      ROUND(remittance_claim.corrected_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS corrected_contractual_adj_amt,
      ROUND(remittance_claim.net_benefit_amt, 3, 'ROUND_HALF_EVEN') AS net_benefit_amt,
      ROUND(remittance_claim.covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS covered_charge_amt,
      ROUND(remittance_claim.mpi_calc_payor_previous_payment_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_payor_previous_payment_amt,
      ROUND(remittance_claim.ep_calc_noncovered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_noncovered_charge_amt,
      ROUND(remittance_claim.mpi_calc_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_non_covered_charge_amt,
      ROUND(remittance_claim.ep_calc_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_deductible_amt,
      ROUND(remittance_claim.mpi_calc_deductible_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_deductible_amt,
      ROUND(remittance_claim.ep_calc_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_blood_deductible_amt,
      ROUND(remittance_claim.ep_calc_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_coinsurance_amt,
      ROUND(remittance_claim.mpi_calc_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_coinsurance_amt,
      ROUND(remittance_claim.ep_calc_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_primary_payor_payment_amt,
      ROUND(remittance_claim.patient_liability_amount, 3, 'ROUND_HALF_EVEN') AS patient_liability_amount,
      ROUND(remittance_claim.capital_amt, 3, 'ROUND_HALF_EVEN') AS capital_amt,
      ROUND(remittance_claim.ep_calc_discount_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_discount_amt,
      ROUND(remittance_claim.disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS disproportionate_share_amt,
      ROUND(remittance_claim.drg_disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS drg_disproportionate_share_amt,
      ROUND(remittance_claim.drg_amt, 3, 'ROUND_HALF_EVEN') AS drg_amt,
      remittance_claim.drg_code,
      remittance_claim.mpi_calc_drg_code,
      remittance_claim.mpi_calc_drg_grouper_code,
      ROUND(remittance_claim.federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS federal_specific_drg_amt,
      ROUND(remittance_claim.hospital_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS hospital_specific_drg_amt,
      ROUND(remittance_claim.drg_weight_amt, 5, 'ROUND_HALF_EVEN') AS drg_weight_amt,
      ROUND(remittance_claim.hcpcs_charge_amt, 3, 'ROUND_HALF_EVEN') AS hcpcs_charge_amt,
      ROUND(remittance_claim.hcpcs_payment_amt, 3, 'ROUND_HALF_EVEN') AS hcpcs_payment_amt,
      ROUND(remittance_claim.indirect_medical_education_amt, 3, 'ROUND_HALF_EVEN') AS indirect_medical_education_amt,
      ROUND(remittance_claim.indirect_teaching_amt, 3, 'ROUND_HALF_EVEN') AS indirect_teaching_amt,
      ROUND(remittance_claim.interest_amt, 3, 'ROUND_HALF_EVEN') AS interest_amt,
      ROUND(remittance_claim.ep_calc_lab_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_lab_charge_amt,
      ROUND(remittance_claim.ep_calc_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_lab_payment_amt,
      ROUND(remittance_claim.pps_opr_federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS pps_opr_federal_specific_drg_amt,
      ROUND(remittance_claim.mpi_calc_non_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_non_billed_charge_amt,
      ROUND(remittance_claim.mpi_calc_net_benefit_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_net_benefit_amt,
      ROUND(remittance_claim.ep_calc_non_payable_professional_fee_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_non_payable_professional_fee_amt,
      ROUND(remittance_claim.old_capital_amt, 3, 'ROUND_HALF_EVEN') AS old_capital_amt,
      ROUND(remittance_claim.operating_outlier_amt, 3, 'ROUND_HALF_EVEN') AS operating_outlier_amt,
      ROUND(remittance_claim.outlier_amt, 3, 'ROUND_HALF_EVEN') AS outlier_amt,
      ROUND(remittance_claim.outpatient_reimibursement_rate_amt, 3, 'ROUND_HALF_EVEN') AS outpatient_reimibursement_rate_amt,
      ROUND(remittance_claim.ep_calc_therapy_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_therapy_charge_amt,
      ROUND(remittance_claim.ep_calc_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_therapy_payment_amt,
      ROUND(remittance_claim.pps_capital_outlier_amt, 3, 'ROUND_HALF_EVEN') AS pps_capital_outlier_amt,
      ROUND(remittance_claim.ins_covered_day_cnt, 2, 'ROUND_HALF_EVEN') AS ins_covered_day_cnt,
      remittance_claim.ep_calc_covered_day_cnt,
      remittance_claim.noncovered_day_cnt,
      remittance_claim.cost_report_day_cnt,
      ROUND(remittance_claim.discharge_fraction_pct, 4, 'ROUND_HALF_EVEN') AS discharge_fraction_pct,
      remittance_claim.lifetime_psychiatric_day_cnt,
      remittance_claim.contractual_adj_amt_procedure_code,
      remittance_claim.payment_amt_procedure_code,
      remittance_claim.logging_flag,
      remittance_claim.logging_type_code,
      remittance_claim.mpi_calc_interim_bill_ind,
      remittance_claim.claim_status_code,
      remittance_claim.ep_calc_status_code,
      remittance_claim.ep_calc_denial_code_ind,
      remittance_claim.mpi_calc_denial_code_ind,
      remittance_claim.type_of_claim_code,
      remittance_claim.type_of_bill_code,
      remittance_claim.ep_calc_balanced_ind,
      remittance_claim.discount_applied_ind,
      remittance_claim.ep_calc_plb_opay_rcvy_trx_ind,
      remittance_claim.ep_calc_internal_denial_code,
      remittance_claim.concuity_acct_ind,
      remittance_claim.mia_switch_ind,
      remittance_claim.moa_switch_ind,
      ROUND(remittance_claim.mia_pps_capital_exception_amt, 3, 'ROUND_HALF_EVEN') AS mia_pps_capital_exception_amt,
      remittance_claim.casemix_ind,
      remittance_claim.zero_default_iplan_ind,
      remittance_claim.trx_tracking_not_released_ind,
      remittance_claim.qmb_switch_ind,
      remittance_claim.ep_calc_denial_code_1,
      remittance_claim.ep_calc_denial_code_2,
      remittance_claim.ep_calc_denial_code_3,
      remittance_claim.ep_calc_denial_code_4,
      remittance_claim.ep_calc_denial_code_5,
      remittance_claim.ep_calc_denial_code_6,
      remittance_claim.ep_calc_denial_code_7,
      remittance_claim.ep_calc_denial_code_8,
      remittance_claim.ep_calc_denial_code_9,
      remittance_claim.ep_calc_denial_code_10,
      remittance_claim.ep_calc_handling_ind,
      remittance_claim.crossover_payor_name,
      remittance_claim.ep_calc_payor_category_code,
      remittance_claim.secondary_payor_flag,
      remittance_claim.ep_calc_prim_itnl_pyr_code,
      remittance_claim.ep_calc_secn_itnl_pyr_code,
      remittance_claim.ep_calc_tert_itnl_pyr_code,
      remittance_claim.corrected_priority_payor_sid,
      remittance_claim.cob_carrier_sid,
      remittance_claim.corrected_subscriber_last_name,
      remittance_claim.corrected_subscriber_first_name,
      remittance_claim.corrected_subscriber_middle_name,
      remittance_claim.corrected_subscriber_health_ins_num,
      remittance_claim.remittance_subscriber_sid,
      remittance_claim.remittance_oth_subscriber_sid,
      remittance_claim.remittance_rendering_provider_sid,
      remittance_claim.supplemental_amt_qlfr_code_1,
      ROUND(remittance_claim.supplemental_amt_1, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_1,
      remittance_claim.supplemental_amt_qlfr_code_2,
      ROUND(remittance_claim.supplemental_amt_2, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_2,
      remittance_claim.supplemental_amt_qlfr_code_3,
      ROUND(remittance_claim.supplemental_amt_3, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_3,
      remittance_claim.supplemental_amt_qlfr_code_4,
      ROUND(remittance_claim.supplemental_amt_4, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_4,
      remittance_claim.supplemental_amt_qlfr_code_5,
      ROUND(remittance_claim.supplemental_amt_5, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_5,
      remittance_claim.supplemental_amt_qlfr_code_6,
      ROUND(remittance_claim.supplemental_amt_6, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_6,
      remittance_claim.supplemental_amt_qlfr_code_7,
      ROUND(remittance_claim.supplemental_amt_7, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_7,
      remittance_claim.supplemental_amt_qlfr_code_8,
      ROUND(remittance_claim.supplemental_amt_8, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_8,
      remittance_claim.supplemental_amt_qlfr_code_9,
      ROUND(remittance_claim.supplemental_amt_9, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_9,
      remittance_claim.supplemental_amt_qlfr_code_10,
      ROUND(remittance_claim.supplemental_amt_10, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_10,
      remittance_claim.supplemental_amt_qlfr_code_11,
      ROUND(remittance_claim.supplemental_amt_11, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_11,
      remittance_claim.supplemental_amt_qlfr_code_12,
      ROUND(remittance_claim.supplemental_amt_12, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_12,
      remittance_claim.supplemental_amt_qlfr_code_13,
      ROUND(remittance_claim.supplemental_amt_13, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_13,
      remittance_claim.supplemental_qty_qlfr_code_1,
      ROUND(remittance_claim.supplemental_qty_1, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_1,
      remittance_claim.supplemental_qty_qlfr_code_2,
      ROUND(remittance_claim.supplemental_qty_2, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_2,
      remittance_claim.supplemental_qty_qlfr_code_3,
      ROUND(remittance_claim.supplemental_qty_3, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_3,
      remittance_claim.supplemental_qty_qlfr_code_4,
      ROUND(remittance_claim.supplemental_qty_4, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_4,
      remittance_claim.supplemental_qty_qlfr_code_5,
      ROUND(remittance_claim.supplemental_qty_5, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_5,
      remittance_claim.supplemental_qty_qlfr_code_6,
      ROUND(remittance_claim.supplemental_qty_6, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_6,
      remittance_claim.supplemental_qty_qlfr_code_7,
      ROUND(remittance_claim.supplemental_qty_7, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_7,
      remittance_claim.supplemental_qty_qlfr_code_8,
      ROUND(remittance_claim.supplemental_qty_8, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_8,
      remittance_claim.supplemental_qty_qlfr_code_9,
      ROUND(remittance_claim.supplemental_qty_9, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_9,
      remittance_claim.supplemental_qty_qlfr_code_10,
      ROUND(remittance_claim.supplemental_qty_10, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_10,
      remittance_claim.supplemental_qty_qlfr_code_11,
      ROUND(remittance_claim.supplemental_qty_11, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_11,
      remittance_claim.supplemental_qty_qlfr_code_12,
      ROUND(remittance_claim.supplemental_qty_12, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_12,
      remittance_claim.supplemental_qty_qlfr_code_13,
      ROUND(remittance_claim.supplemental_qty_13, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_13,
      remittance_claim.supplemental_qty_qlfr_code_14,
      ROUND(remittance_claim.supplemental_qty_14, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_14,
      remittance_claim.rarc_code_1,
      remittance_claim.rarc_code_2,
      remittance_claim.rarc_code_3,
      remittance_claim.rarc_code_4,
      remittance_claim.rarc_code_5,
      remittance_claim.source_system_code,
      remittance_claim.dw_last_update_date_time
    FROM
      {{ params.param_pbs_core_dataset_name }}.remittance_claim
  ;
