-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/resolved_discrepancy_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_base_views_dataset_name }}.resolved_discrepancy_pf AS SELECT
    resolved_discrepancy.company_code,
    resolved_discrepancy.coid,
    ROUND(resolved_discrepancy.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(resolved_discrepancy.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    resolved_discrepancy.iplan_insurance_order_num,
    resolved_discrepancy.eor_log_date,
    resolved_discrepancy.log_id,
    resolved_discrepancy.log_sequence_num,
    resolved_discrepancy.discrepancy_resolved_date,
    resolved_discrepancy.eff_from_date,
    ROUND(resolved_discrepancy.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    resolved_discrepancy.iplan_id,
    resolved_discrepancy.length_of_stay_days_num,
    resolved_discrepancy.eor_drg_code,
    resolved_discrepancy.eor_hipps_code,
    ROUND(resolved_discrepancy.eor_payment_amt, 3, 'ROUND_HALF_EVEN') AS eor_payment_amt,
    resolved_discrepancy.remittance_date,
    resolved_discrepancy.ra_log_date,
    resolved_discrepancy.ra_payment_date,
    resolved_discrepancy.ra_drg_code,
    resolved_discrepancy.ra_hipps_code,
    resolved_discrepancy.ra_covered_days_num,
    ROUND(resolved_discrepancy.ra_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_charge_amt,
    ROUND(resolved_discrepancy.ra_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_non_covered_charge_amt,
    ROUND(resolved_discrepancy.ra_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS ra_gross_reimbursement_amt,
    ROUND(resolved_discrepancy.ra_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS ra_ded_coins_amt,
    ROUND(resolved_discrepancy.ra_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_payment_amt,
    ROUND(resolved_discrepancy.ra_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS ra_contractual_allowance_amt,
    ROUND(resolved_discrepancy.ra_copay_amt, 3, 'ROUND_HALF_EVEN') AS ra_copay_amt,
    ROUND(resolved_discrepancy.ra_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ra_coinsurance_amt,
    ROUND(resolved_discrepancy.ra_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_billed_charge_amt,
    ROUND(resolved_discrepancy.ra_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_deductible_amt,
    ROUND(resolved_discrepancy.ra_total_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_total_deductible_amt,
    ROUND(resolved_discrepancy.ra_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ra_blood_deductible_amt,
    ROUND(resolved_discrepancy.ra_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_lab_payment_amt,
    ROUND(resolved_discrepancy.ra_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_therapy_payment_amt,
    ROUND(resolved_discrepancy.ra_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_primary_payor_payment_amt,
    ROUND(resolved_discrepancy.ra_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_outlier_payment_amt,
    ROUND(resolved_discrepancy.ra_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS ra_capital_payment_amt,
    ROUND(resolved_discrepancy.ra_denied_charge_amt, 3, 'ROUND_HALF_EVEN') AS ra_denied_charge_amt,
    ROUND(resolved_discrepancy.ra_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_apc_service_amt,
    ROUND(resolved_discrepancy.ra_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS ra_net_fee_schedule_amt,
    ROUND(resolved_discrepancy.over_under_payment_amt, 3, 'ROUND_HALF_EVEN') AS over_under_payment_amt,
    ROUND(resolved_discrepancy.actual_payment_amt, 3, 'ROUND_HALF_EVEN') AS actual_payment_amt,
    resolved_discrepancy.discrepancy_origination_date,
    resolved_discrepancy.discrepancy_inactive_date,
    resolved_discrepancy.discrepancy_day_count,
    resolved_discrepancy.resolve_reason_code,
    resolved_discrepancy.var_covered_days_num,
    ROUND(resolved_discrepancy.var_total_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_total_charge_amt,
    ROUND(resolved_discrepancy.var_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_non_covered_charge_amt,
    ROUND(resolved_discrepancy.var_net_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_net_billed_charge_amt,
    ROUND(resolved_discrepancy.var_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_reimbursement_amt,
    ROUND(resolved_discrepancy.var_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_deductible_amt,
    ROUND(resolved_discrepancy.var_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS var_coinsurance_amt,
    ROUND(resolved_discrepancy.var_ded_coins_amt, 3, 'ROUND_HALF_EVEN') AS var_ded_coins_amt,
    ROUND(resolved_discrepancy.var_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS var_blood_deductible_amt,
    ROUND(resolved_discrepancy.var_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_insurance_payment_amt,
    ROUND(resolved_discrepancy.var_primary_payor_pmt_amt, 3, 'ROUND_HALF_EVEN') AS var_primary_payor_pmt_amt,
    ROUND(resolved_discrepancy.var_capital_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_capital_payment_amt,
    ROUND(resolved_discrepancy.var_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_lab_payment_amt,
    ROUND(resolved_discrepancy.var_outlier_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_outlier_payment_amt,
    ROUND(resolved_discrepancy.var_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS var_therapy_payment_amt,
    ROUND(resolved_discrepancy.var_contractual_allowance_amt, 3, 'ROUND_HALF_EVEN') AS var_contractual_allowance_amt,
    ROUND(resolved_discrepancy.var_copay_amt, 3, 'ROUND_HALF_EVEN') AS var_copay_amt,
    ROUND(resolved_discrepancy.var_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS var_covered_charge_amt,
    ROUND(resolved_discrepancy.var_net_apc_service_amt, 3, 'ROUND_HALF_EVEN') AS var_net_apc_service_amt,
    ROUND(resolved_discrepancy.var_net_fee_schedule_amt, 3, 'ROUND_HALF_EVEN') AS var_net_fee_schedule_amt,
    resolved_discrepancy.inpatient_outpatient_ind,
    resolved_discrepancy.primary_reason_assignment_cnt,
    resolved_discrepancy.discrepancy_reason_code_1,
    resolved_discrepancy.reason_assignment_date_1,
    resolved_discrepancy.discrepancy_reason_code_2,
    resolved_discrepancy.reason_assignment_date_2,
    resolved_discrepancy.discrepancy_reason_code_3,
    resolved_discrepancy.reason_assignment_date_3,
    resolved_discrepancy.discrepancy_reason_code_4,
    resolved_discrepancy.reason_assignment_date_4,
    resolved_discrepancy.comments,
    resolved_discrepancy.work_date,
    resolved_discrepancy.last_racf_id,
    resolved_discrepancy.last_racf_date,
    resolved_discrepancy.data_source_code,
    ROUND(resolved_discrepancy.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
    resolved_discrepancy.ar_bill_thru_date,
    ROUND(resolved_discrepancy.cc_calc_id, 0, 'ROUND_HALF_EVEN') AS cc_calc_id,
    ROUND(resolved_discrepancy.cc_account_activity_id, 0, 'ROUND_HALF_EVEN') AS cc_account_activity_id,
    ROUND(resolved_discrepancy.cc_reason_id, 0, 'ROUND_HALF_EVEN') AS cc_reason_id,
    ROUND(resolved_discrepancy.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id,
    resolved_discrepancy.last_update_date,
    resolved_discrepancy.dw_last_update_date_time,
    resolved_discrepancy.source_system_code
  FROM
    {{ params.param_auth_base_views_dataset_name }}.resolved_discrepancy
;
