CREATE OR REPLACE TABLE {{ params.param_cr_core_dataset_name }}.cancer_patient_id_output_driver
(
  cancer_patient_id_output_driver_sk NUMERIC(29) NOT NULL OPTIONS(description='A unique identifier for each patient identifier output driver record'),
  cancer_patient_driver_sk NUMERIC(29) OPTIONS(description='Unique patient key for consolidated patient records'),
  cancer_patient_id_output_sk INT64 OPTIONS(description='A unique identifier for each output record.'),
  message_control_id_text STRING OPTIONS(description='Unique id for the message provided from EDW'),
  user_action_date_time DATETIME OPTIONS(description='Date that the user took action on the message.'),
  coid STRING OPTIONS(description='A five character code for each facility.'),
  company_code STRING OPTIONS(description='Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.'),
  patient_dw_id NUMERIC(29) OPTIONS(description='An internal EDW identifier for each encounter.'),
  pat_acct_num NUMERIC(29) OPTIONS(description='Account Number for the message'),
  medical_record_num STRING OPTIONS(description='MRN associated to the message'),
  patient_market_urn STRING OPTIONS(description='URN associated to the message'),
  last_name STRING OPTIONS(description='Patient Last Name'),
  first_name STRING OPTIONS(description='Patient First Name'),
  birth_date DATE OPTIONS(description='Patient Date of Birth'),
  gender_code STRING OPTIONS(description='Patient Gender'),
  social_security_num STRING OPTIONS(description='Domain to mask the Social Security Number during the Security View generation.'),
  address_line_1_text STRING OPTIONS(description='The first line of the address of the patient.'),
  address_line_2_text STRING OPTIONS(description='The second line of the address of the patient.'),
  city_name STRING OPTIONS(description='The name of the city corresponding to the patients address.'),
  state_code STRING OPTIONS(description='The two character state code on the address.'),
  zip_code STRING OPTIONS(description='The zip code of a patient.'),
  patient_type_code STRING OPTIONS(description='The patient type code - outpatient, inpatient.'),
  message_type_code STRING OPTIONS(description='The message type from the HL7 message.'),
  message_event_type_code STRING OPTIONS(description='The triggering event from the HL7 message.'),
  message_flag_code STRING OPTIONS(description='Identifies which type of segment the message corresponds to.'),
  message_origin_requested_date_time DATETIME OPTIONS(description='It will have TXA Origination Date Time from MDM message OR OBR requested Date Time from ORU Message '),
  message_signed_observation_date_time DATETIME OPTIONS(description='It will have TXA Transcription Date Time from MDM Message OR OBR Observation Date Time from ORU message '),
  message_ingestion_date_time DATETIME OPTIONS(description='The datetime the message was ingested into the cancer id model.'),
  message_created_date_time DATETIME OPTIONS(description='The datetime the message was created.'),
  document_type_id_text STRING OPTIONS(description='Identifies the subject area of document that was transmitted in the message.'),
  document_type_text STRING OPTIONS(description='Identifies the type of document that was transmitted in the message.'),
  document_type_coding_system_code STRING OPTIONS(description='Identifies the code corresponding to the coding system.'),
  first_insert_date_time DATETIME OPTIONS(description='Identifies when the message was first inserted.'),
  icd_oncology_type_code STRING OPTIONS(description='Identifies the version of ICD Oncology codes the code refers to.'),
  predicted_primary_icd_oncology_code STRING OPTIONS(description='ICD-O-3 that corresponds to the model_predicted_primary_site (ID 12).'),
  predicted_primary_icd_site_desc STRING OPTIONS(description='The site description for each ICD Oncology Code'),
  suggested_primary_icd_oncology_code STRING OPTIONS(description='ICD-O-3 that corresponds to the suggested_primary_site if suggested site is selected (ID 14).'),
  suggested_primary_icd_site_desc STRING OPTIONS(description='The site description for each ICD Oncology Code'),
  submitted_primary_icd_oncology_code STRING OPTIONS(description='ICD-O-3 that corresponds to the submitted_primary_site (ID 16).'),
  submitted_primary_icd_site_desc STRING OPTIONS(description='The site description for each ICD Oncology Code'),
  transition_of_care_num INT64 OPTIONS(description='Predetermined transition of care will be associated based on the key diagnosis words in the report.  IF the user indicated a Suggested Primary Site (ID 14) then the transition_of_care will be set to 4'),
  user_action_desc STRING OPTIONS(description='User selection from controlled list; Confirm, False Positive, Insufficient Details'),
  user_action_criticality_text STRING OPTIONS(description='Indicates if a lung nodule is greater than or equal to 6 millimeter'),
  user_3_4_id STRING OPTIONS(description='Identification of the user taking action in the application in the 3-4 ID format.'),
  report_assigned_date_time DATETIME OPTIONS(description='The datetime the report was assigned to the user.'),
  attending_physician_full_name STRING OPTIONS(description='Name of the attending physician.'),
  pcp_full_name STRING OPTIONS(description='Name of the primary care physician.'),
  pcp_phone_num STRING OPTIONS(description='The primary care physicians phone number'),
  facility_menmonic_cs STRING OPTIONS(description='Mnemonic that is associated to the sending facility of the message'),
  network_mnemonic_cs STRING OPTIONS(description='Mnemonic that is associated to the sending meditech network.'),
  model_predicted_sarcoma_ind STRING OPTIONS(description='Indicator for Sarcoma predicted by model'),
  submitted_sarcoma_ind STRING OPTIONS(description='Indicator for Sarcoma by submitted primary site'),
  suggested_sarcoma_ind STRING OPTIONS(description='Indicator for Sarcoma by suggested primary site'),
  benign_brain_tumor_type_ind STRING OPTIONS(description='Indicator for benign brain tumor type'),
  met_to_brain_tumor_type_ind STRING OPTIONS(description='Indicator for Met to brain tumor type'),
  other_tumor_type_ind STRING OPTIONS(description='Indicator for other tumor types'),
  source_system_code STRING NOT NULL OPTIONS(description='A one character code indicating the specific source system from which the data originated.'),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description='Timestamp of update or load of this record to the Enterprise Data Warehouse.')
)
CLUSTER BY cancer_patient_driver_sk, coid
OPTIONS(
  description='This table contains the output of the cancer patient identifier model on HDFS and linked consildated patient key'
);
