CREATE OR REPLACE TABLE {{ params.param_cr_core_dataset_name }}.cdm_procedure_detail
(
  patient_dw_id NUMERIC(29) NOT NULL OPTIONS(description=' Unique Identifier assigned by the Data Warehouse.'),
  procedure_code STRING NOT NULL OPTIONS(description=' A unique identifier for actions taken in a coordinated fashion required to complete an order.'),
  procedure_type_code STRING NOT NULL OPTIONS(description=' Distinguishes type of Procedure, ICD9 or HCPC'),
  procedure_seq_num NUMERIC(29) NOT NULL OPTIONS(description=' Sequence number generated by the DW.'),
  service_date DATE NOT NULL OPTIONS(description=' The date that the service represented by the patient charge code was provided to the patient.'),
  procedure_code_desc STRING OPTIONS(description=' Text that describes the actions taken in a coordinated fashion required to complete an order.'),
  procedure_type_code_desc STRING,
  coid STRING NOT NULL OPTIONS(description=' The company identifier which uniquely identifies a facility to corporate and all other facilities.'),
  company_code STRING NOT NULL OPTIONS(description=' Part of the unique identifier that identifies the company with which a facility is affiliated for application processing purposes.'),
  pat_acct_num NUMERIC(29) NOT NULL OPTIONS(description=' A unique number assigned by the hospital to the patient at time of registration.'),
  procedure_rank_num INT64 OPTIONS(description=' The precedence of a procedure in relation to other ICD9 procedures performed for a patient.'),
  facility_physician_num INT64 OPTIONS(description=' The billing system identification number assigned to a practitioner by a facility'),
  physician_npi NUMERIC(29) OPTIONS(description=' The National Provider Identifier (NPI) is a unique identification number assigned to the provider submitting the bill.'),
  physician_full_name STRING OPTIONS(description=' This is the full name of the physician person.'),
  physician_last_name STRING OPTIONS(description=' This is the physician last name'),
  physician_first_name STRING OPTIONS(description=' This is the physician first name'),
  source_system_code STRING NOT NULL OPTIONS(description=' A one character code indicating the specific source system from which the data originated.'),
  dw_last_update_date_time DATETIME NOT NULL OPTIONS(description=' Timestamp of update or load of this record to the Enterprise Data Warehouse.')
)
CLUSTER BY patient_dw_id
OPTIONS(
  description='Contains all procedures associated with an encounter.'
);
