-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/collection_doc_req_dtl.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.collection_doc_req_dtl AS SELECT
    collection_doc_req_dtl.doc_req_key_num,
    collection_doc_req_dtl.artiva_instance_code,
    collection_doc_req_dtl.reporting_date,
    collection_doc_req_dtl.patient_dw_id,
    collection_doc_req_dtl.iplan_id,
    collection_doc_req_dtl.company_code,
    collection_doc_req_dtl.coid,
    collection_doc_req_dtl.unit_num,
    collection_doc_req_dtl.pat_acct_num,
    collection_doc_req_dtl.status_code,
    collection_doc_req_dtl.encounter_balance_amt,
    collection_doc_req_dtl.total_billed_charge_amt,
    collection_doc_req_dtl.total_adjustment_amt,
    collection_doc_req_dtl.total_payment_amt,
    collection_doc_req_dtl.current_balance_amt,
    collection_doc_req_dtl.claim_submit_date,
    collection_doc_req_dtl.requested_date,
    collection_doc_req_dtl.response_due_date,
    collection_doc_req_dtl.approved_date,
    collection_doc_req_dtl.denied_date,
    collection_doc_req_dtl.create_date,
    collection_doc_req_dtl.sent_date,
    collection_doc_req_dtl.tracking_dtl_text,
    collection_doc_req_dtl.received_date,
    collection_doc_req_dtl.review_type_code,
    collection_doc_req_dtl.reason_text,
    collection_doc_req_dtl.othr_reason_text,
    collection_doc_req_dtl.mail_receipt_date,
    collection_doc_req_dtl.receipt_cnfm_num,
    collection_doc_req_dtl.cover_letter_reqr_ind,
    collection_doc_req_dtl.doc_delivery_method_text,
    collection_doc_req_dtl.mailed_address_sid,
    collection_doc_req_dtl.signed_by_comment_text,
    collection_doc_req_dtl.admit_order_ind,
    collection_doc_req_dtl.admit_order_aprv_ind,
    collection_doc_req_dtl.implant_inv_ind,
    collection_doc_req_dtl.implant_inv_aprv_ind,
    collection_doc_req_dtl.oth_dtl_ind,
    collection_doc_req_dtl.oth_dtl_aprv_ind,
    collection_doc_req_dtl.dchg_smry_ind,
    collection_doc_req_dtl.dchg_smry_aprv_ind,
    collection_doc_req_dtl.emrg_rpt_ind,
    collection_doc_req_dtl.emrg_rpt_aprv_ind,
    collection_doc_req_dtl.accd_dtl_ind,
    collection_doc_req_dtl.accd_dtl_aprv_ind,
    collection_doc_req_dtl.itm_bill_ind,
    collection_doc_req_dtl.itm_bill_aprv_ind,
    collection_doc_req_dtl.itm_bill_req_date,
    collection_doc_req_dtl.itm_bill_sent_date,
    collection_doc_req_dtl.first_letter_sent_date,
    collection_doc_req_dtl.second_letter_sent_date,
    collection_doc_req_dtl.third_letter_sent_date,
    collection_doc_req_dtl.sent_to_prepay_mc_ind,
    collection_doc_req_dtl.prepay_mc_sent_date,
    collection_doc_req_dtl.cplt_med_rec_ind,
    collection_doc_req_dtl.cplt_med_rec_aprv_ind,
    collection_doc_req_dtl.med_rec_req_date,
    collection_doc_req_dtl.med_rec_sent_date,
    collection_doc_req_dtl.user_id,
    collection_doc_req_dtl.user_dept_num,
    collection_doc_req_dtl.vendor_id,
    collection_doc_req_dtl.vendor_mail_comment_text,
    collection_doc_req_dtl.source_system_code,
    collection_doc_req_dtl.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs.collection_doc_req_dtl
;
