-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/discrepancy_inventory_analysis.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.discrepancy_inventory_analysis AS SELECT
    discrepancy_inventory_analysis.date_sid,
    discrepancy_inventory_analysis.patient_dw_id,
    discrepancy_inventory_analysis.payor_dw_id,
    discrepancy_inventory_analysis.iplan_insurance_order_num,
    discrepancy_inventory_analysis.log_id,
    discrepancy_inventory_analysis.ar_bill_thru_date,
    discrepancy_inventory_analysis.discrepancy_creation_date,
    discrepancy_inventory_analysis.patient_sid,
    discrepancy_inventory_analysis.payor_sequence_sid,
    discrepancy_inventory_analysis.unit_num_sid,
    discrepancy_inventory_analysis.eor_log_date,
    discrepancy_inventory_analysis.log_sequence_num,
    discrepancy_inventory_analysis.year_created_sid,
    discrepancy_inventory_analysis.cost_year_sid,
    discrepancy_inventory_analysis.cost_year_end_date,
    discrepancy_inventory_analysis.payor_financial_class_sid,
    discrepancy_inventory_analysis.payor_sid,
    discrepancy_inventory_analysis.patient_type_sid,
    discrepancy_inventory_analysis.discrepancy_age_month_sid,
    discrepancy_inventory_analysis.discharge_age_month_sid,
    discrepancy_inventory_analysis.scenario_sid,
    discrepancy_inventory_analysis.reason_code_1_sid,
    discrepancy_inventory_analysis.reason_code_2_sid,
    discrepancy_inventory_analysis.reason_code_3_sid,
    discrepancy_inventory_analysis.reason_code_4_sid,
    discrepancy_inventory_analysis.source_sid,
    discrepancy_inventory_analysis.cc_account_payer_status_id,
    discrepancy_inventory_analysis.coid,
    discrepancy_inventory_analysis.company_code,
    discrepancy_inventory_analysis.resolve_reason_code,
    discrepancy_inventory_analysis.discharge_date,
    discrepancy_inventory_analysis.ra_remit_date,
    discrepancy_inventory_analysis.reason_assignment_date_1,
    discrepancy_inventory_analysis.reason_assignment_date_2,
    discrepancy_inventory_analysis.reason_assignment_date_3,
    discrepancy_inventory_analysis.reason_assignment_date_4,
    discrepancy_inventory_analysis.account_balance_amt,
    discrepancy_inventory_analysis.primary_reason_code_change_cnt,
    discrepancy_inventory_analysis.discrepancy_days,
    discrepancy_inventory_analysis.discrepancy_resolved_date,
    discrepancy_inventory_analysis.discrepany_type_code,
    discrepancy_inventory_analysis.discrepancy_type_sid,
    discrepancy_inventory_analysis.same_store_sid,
    discrepancy_inventory_analysis.dollar_strtf_sid,
    discrepancy_inventory_analysis.var_beg_amt,
    discrepancy_inventory_analysis.var_new_amt,
    discrepancy_inventory_analysis.var_resolved_amt,
    discrepancy_inventory_analysis.var_othr_cor_amt,
    discrepancy_inventory_analysis.var_end_amt,
    discrepancy_inventory_analysis.exp_crnt_amt,
    discrepancy_inventory_analysis.exp_rate_amt,
    discrepancy_inventory_analysis.var_beg_cnt,
    discrepancy_inventory_analysis.var_new_cnt,
    discrepancy_inventory_analysis.var_resolved_cnt,
    discrepancy_inventory_analysis.var_othr_cor_cnt,
    discrepancy_inventory_analysis.var_end_cnt,
    discrepancy_inventory_analysis.exp_crnt_cnt,
    discrepancy_inventory_analysis.exp_rate_cnt,
    discrepancy_inventory_analysis.resolved_days,
    discrepancy_inventory_analysis.end_days,
    discrepancy_inventory_analysis.source_system_code,
    discrepancy_inventory_analysis.dw_last_update_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs.discrepancy_inventory_analysis
;
