-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/fact_rcom_ar_hospital_level_host.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.fact_rcom_ar_hospital_level_host AS SELECT
    fact_rcom_ar_hospital_level.unit_num_sid,
    fact_rcom_ar_hospital_level.scenario_sid,
    fact_rcom_ar_hospital_level.week_of_month_sid,
    fact_rcom_ar_hospital_level.date_sid,
    fact_rcom_ar_hospital_level.source_sid,
    fact_rcom_ar_hospital_level.company_code,
    fact_rcom_ar_hospital_level.coid,
    fact_rcom_ar_hospital_level.recoveries_wo_amt_cons65200,
    fact_rcom_ar_hospital_level.credit_coll_svc_amt_cons83320,
    fact_rcom_ar_hospital_level.allow_govt_receivable_fs05300,
    fact_rcom_ar_hospital_level.allow_uncoll_amt_fs05350,
    fact_rcom_ar_hospital_level.allow_uncoll_nonpat_amtfs05360,
    fact_rcom_ar_hospital_level.ip_revenue_routine_amt_fs50100,
    fact_rcom_ar_hospital_level.ip_rev_ancillary_amt_fs50200,
    fact_rcom_ar_hospital_level.op_ancillary_rev_amt_fs50400,
    fact_rcom_ar_hospital_level.other_operating_income_fs50900,
    fact_rcom_ar_hospital_level.mcare_cy_cont_ip_amt_fs60100,
    fact_rcom_ar_hospital_level.mcare_cy_cont_op_amt_fs60125,
    fact_rcom_ar_hospital_level.prior_yr_cont_ip_amt_fs60150,
    fact_rcom_ar_hospital_level.prior_yr_cont_op_amt_fs60175,
    fact_rcom_ar_hospital_level.mcaid_cy_cont_ip_amt_fs60200,
    fact_rcom_ar_hospital_level.mcaid_cy_cont_op_amt_fs60225,
    fact_rcom_ar_hospital_level.champ_cy_cont_ip_amt_fs60300,
    fact_rcom_ar_hospital_level.champ_cy_cont_op_amt_fs60325,
    fact_rcom_ar_hospital_level.bc_hmo_ppo_disc_ip_amt_fs60400,
    fact_rcom_ar_hospital_level.bc_hmo_ppo_disc_op_amt_fs60425,
    fact_rcom_ar_hospital_level.mcare_mgd_care_ip_amt_fs60450,
    fact_rcom_ar_hospital_level.mcare_mgd_care_op_amt_fs60460,
    fact_rcom_ar_hospital_level.mcaid_mgd_care_ip_amt_fs60475,
    fact_rcom_ar_hospital_level.mcaid_mgd_care_op_amt_fs60480,
    fact_rcom_ar_hospital_level.charity_ip_amt_fs60500,
    fact_rcom_ar_hospital_level.charity_op_amt_fs60525,
    fact_rcom_ar_hospital_level.other_deduction_ip_amt_fs60600,
    fact_rcom_ar_hospital_level.other_deduction_op_amt_fs60625,
    fact_rcom_ar_hospital_level.salaries_fdept_620_amt_fs65050,
    fact_rcom_ar_hospital_level.emp_ben_fdept_620_amt_fs65100,
    fact_rcom_ar_hospital_level.bad_debt_amt_fs65500,
    fact_rcom_ar_hospital_level.patient_receivable_amt_fs90000,
    fact_rcom_ar_hospital_level.reversal_for_05350_amt_fs90008,
    fact_rcom_ar_hospital_level.total_patient_rev_amt_fs90230,
    fact_rcom_ar_hospital_level.curr_year_cont_amt_fs90245,
    fact_rcom_ar_hospital_level.policy_adjustments_amt_fs90246,
    fact_rcom_ar_hospital_level.tot_ar_cost_fdept620_gla501000,
    fact_rcom_ar_hospital_level.mcare_clrng_gla110101_110179,
    fact_rcom_ar_hospital_level.mcare_clrng_gla110189_110197,
    fact_rcom_ar_hospital_level.mcaid_clrng_gla110201_110279,
    fact_rcom_ar_hospital_level.mcaid_clrng_gla110286_110297,
    fact_rcom_ar_hospital_level.cash_receipt_amt,
    fact_rcom_ar_hospital_level.credit_refund_amt,
    fact_rcom_ar_hospital_level.reg_accuracy_reg_entry_cnt,
    fact_rcom_ar_hospital_level.reg_accuracy_reg_changes_cnt,
    fact_rcom_ar_hospital_level.ins_gt_150_day_pct_amt,
    fact_rcom_ar_hospital_level.ins_gt_90_day_pct_amt,
    fact_rcom_ar_hospital_level.write_off_amt,
    fact_rcom_ar_hospital_level.unins_ip_gla508490_gla508499,
    fact_rcom_ar_hospital_level.unins_op_gla508990_gla508999,
    fact_rcom_ar_hospital_level.health_exchange_ip_amt_fs60490,
    fact_rcom_ar_hospital_level.health_exchange_op_amt_fs60495
  FROM
    `hca-hin-dev-cur-parallon`.edwpf_base_views.fact_rcom_ar_hospital_level
;
