-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/patient_account_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.patient_account_detail AS SELECT
    patient_account_detail.patient_dw_id,
    patient_account_detail.company_code,
    patient_account_detail.coid,
    patient_account_detail.sub_unit_num,
    patient_account_detail.pat_acct_num,
    patient_account_detail.medical_record_num,
    patient_account_detail.patient_type_code,
    patient_account_detail.financial_class_code,
    patient_account_detail.account_status_code,
    patient_account_detail.admission_type_code,
    patient_account_detail.admission_source_code,
    patient_account_detail.patient_full_name,
    patient_account_detail.social_security_num,
    patient_account_detail.birth_date,
    patient_account_detail.gender_code,
    patient_account_detail.marital_status_code,
    patient_account_detail.patient_person_dw_id,
    patient_account_detail.patient_address_dw_id,
    patient_account_detail.admission_date,
    patient_account_detail.discharge_date,
    patient_account_detail.final_bill_date,
    patient_account_detail.los_day_cnt,
    patient_account_detail.drg_code,
    patient_account_detail.principal_diag_code_icd9,
    patient_account_detail.principal_diag_desc_icd9,
    patient_account_detail.principal_diag_code_icd10,
    patient_account_detail.principal_diag_desc_icd10,
    patient_account_detail.service_code,
    patient_account_detail.accomodation_code,
    patient_account_detail.room_num,
    patient_account_detail.bill_gen_date,
    patient_account_detail.responsible_party_name,
    patient_account_detail.pat_relationship_code,
    patient_account_detail.agency_code,
    patient_account_detail.initial_turnover_date,
    patient_account_detail.stmt_issue_date,
    patient_account_detail.patient_allowance_amt,
    patient_account_detail.patient_adj_amt,
    patient_account_detail.non_billable_adj_amt,
    patient_account_detail.non_billable_charge_amt,
    patient_account_detail.patient_balance_amt,
    patient_account_detail.last_patient_pmt_amt,
    patient_account_detail.last_patient_pmt_date,
    patient_account_detail.pmt_arng_stmt_freq,
    patient_account_detail.pmt_arng_start_date,
    patient_account_detail.previous_due_amt,
    patient_account_detail.current_due_amt,
    patient_account_detail.patient_overdue_amt,
    patient_account_detail.patient_min_due_amt,
    patient_account_detail.total_patient_pmt_amt,
    patient_account_detail.total_charge_amt,
    patient_account_detail.total_account_balance_amt,
    patient_account_detail.total_pmt_amt,
    patient_account_detail.total_allowance_amt,
    patient_account_detail.total_write_off_amt,
    patient_account_detail.total_adj_amt,
    patient_account_detail.stmt_cnt,
    patient_account_detail.last_pmt_rcvd_date,
    patient_account_detail.recall_date,
    patient_account_detail.initial_bad_debt_prelist_date,
    patient_account_detail.bad_debt_reason_code,
    patient_account_detail.patient_turnover_date,
    patient_account_detail.agency_type_code,
    patient_account_detail.current_collection_series_num,
    patient_account_detail.previous_collection_series_num,
    patient_account_detail.pa_restore_date,
    patient_account_detail.source_system_code,
    patient_account_detail.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs.patient_account_detail
;
