-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/payment_compliance_credit_inventory.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.payment_compliance_credit_inventory AS SELECT
    payment_compliance_credit_inventory.patient_dw_id,
    payment_compliance_credit_inventory.reporting_date,
    payment_compliance_credit_inventory.credit_balance_refund_ind,
    payment_compliance_credit_inventory.credit_balance_refund_id,
    payment_compliance_credit_inventory.company_code,
    payment_compliance_credit_inventory.coid,
    payment_compliance_credit_inventory.payor_dw_id_ins1,
    payment_compliance_credit_inventory.unit_num,
    payment_compliance_credit_inventory.pat_acct_num,
    payment_compliance_credit_inventory.admission_type_code,
    payment_compliance_credit_inventory.account_status_code,
    payment_compliance_credit_inventory.refund_type_sid,
    payment_compliance_credit_inventory.credit_status_sid,
    payment_compliance_credit_inventory.payor_financial_class_code,
    payment_compliance_credit_inventory.iplan_id_ins1,
    payment_compliance_credit_inventory.iplan_id_ins2,
    payment_compliance_credit_inventory.iplan_id_ins3,
    payment_compliance_credit_inventory.patient_person_dw_id,
    payment_compliance_credit_inventory.patient_address_dw_id,
    payment_compliance_credit_inventory.member_id,
    payment_compliance_credit_inventory.logged_ind,
    payment_compliance_credit_inventory.refund_iplan_id,
    payment_compliance_credit_inventory.refund_special_code,
    payment_compliance_credit_inventory.refund_procedure_code,
    payment_compliance_credit_inventory.refund_gl_acct_num,
    payment_compliance_credit_inventory.refund_payor_dw_id,
    payment_compliance_credit_inventory.refund_payor_address_dw_id,
    payment_compliance_credit_inventory.refund_creation_date_time,
    payment_compliance_credit_inventory.refund_creation_user_id,
    payment_compliance_credit_inventory.refund_amt,
    payment_compliance_credit_inventory.total_charge_amt,
    payment_compliance_credit_inventory.total_account_balance_amt,
    payment_compliance_credit_inventory.total_cash_pay_amt,
    payment_compliance_credit_inventory.total_allow_amt,
    payment_compliance_credit_inventory.total_policy_adj_amt,
    payment_compliance_credit_inventory.total_write_off_amt,
    payment_compliance_credit_inventory.credit_balance_date,
    payment_compliance_credit_inventory.current_grv_amt,
    payment_compliance_credit_inventory.entered_date,
    payment_compliance_credit_inventory.discharge_date,
    payment_compliance_credit_inventory.admission_date,
    payment_compliance_credit_inventory.final_bill_date,
    payment_compliance_credit_inventory.bill_through_date,
    payment_compliance_credit_inventory.credit_bal_estb_date_time,
    payment_compliance_credit_inventory.last_update_date_time,
    payment_compliance_credit_inventory.last_update_user_id,
    payment_compliance_credit_inventory.approved_by_user_id,
    payment_compliance_credit_inventory.approved_date_time,
    payment_compliance_credit_inventory.auto_refund_create_date_time,
    payment_compliance_credit_inventory.resolved_date,
    payment_compliance_credit_inventory.eligible_transfer_ind,
    payment_compliance_credit_inventory.late_charge_ind,
    payment_compliance_credit_inventory.restore_date_time,
    payment_compliance_credit_inventory.restore_ind,
    payment_compliance_credit_inventory.source_system_code,
    payment_compliance_credit_inventory.dw_last_update_date_time
  FROM
    `hca-hin-dev-cur-parallon`.edwpbs.payment_compliance_credit_inventory
;
