-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/prctnr_fclt_ent_cdm.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.prctnr_fclt_ent_cdm AS SELECT
    a.ntwk_ssk_cs,
    a.fclt_ssk_cs,
    a.prctnr_ssk_cs,
    a.src_lst_upd_ts,
    a.company_code,
    a.coid,
    a.effv_fr_ts,
    a.effv_to_ts,
    a.prctnr_sk,
    a.pa_cd,
    a.pa_alphanumeric_cd,
    a.prctnr_fclt_role_cd,
    a.admt_prvlg_ind,
    a.ordr_prvlg_ind,
    a.er_phys_ind,
    a.eltrn_sig_ind,
    a.fclt_opt_in_ind,
    a.fclt_emp_ind,
    a.excl_flg,
    a.excl_fr_dt,
    a.co_sgn_rqrd_sw,
    a.on_staff_ind,
    a.licn_nbr,
    a.licn_st_cd,
    a.licn_nbr_exp_dt,
    a.dea_nbr,
    a.dea_nbr_exp_dt,
    a.nadea_nbr,
    a.nadea_nbr_exp_dt,
    a.adm_svc_cd,
    a.abs_svc_cd,
    a.prctnr_prvdr_nbr,
    a.prvdr_grp_nm,
    a.erx_nbr,
    a.enbl_erx_cd,
    a.epcs_enbl_ind,
    a.mobl_physn_ordr_ind,
    a.ee_rltn_cd,
    a.ste_addr_1_txt,
    a.ste_addr_2_txt,
    a.city_nm,
    a.st_cd,
    a.pstl_cd,
    a.fclt_ph_num,
    a.fclt_fax_num,
    a.fclt_pgr_num,
    a.fclt_pgr_type_cd,
    a.fclt_pgr_pin_txt,
    a.fclt_pgr_wait_num,
    a.fclt_ofc_mgr_nm,
    a.fclt_eml_txt,
    a.fclt_vnd_txt,
    a.fclt_gl_ac_txt,
    a.omit_oe_lkup_ind,
    a.vld_fr_ts,
    a.vld_to_ts,
    a.data_source_id,
    a.src_sys_ref_cd,
    a.src_sys_unq_key_txt,
    a.crt_run_id,
    a.lst_updt_run_id,
    a.dw_insrt_ts
  FROM
    `hca-hin-dev-cur-parallon`.edwcdm_base_views.prctnr_fclt_ent AS a
    INNER JOIN `hca-hin-dev-cur-parallon`.edwcdm_base_views.secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
