-- Translation time: 2024-01-12T17:51:56.897679Z
-- Translation job ID: daf02731-0647-4415-a27a-5b3d10f518dd
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_base_views/remittance_pf.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE VIEW IF NOT EXISTS `hca-hin-dev-cur-parallon`.edwpbs_base_views.remittance_pf AS SELECT
    remittance.company_code,
    remittance.coid,
    remittance.patient_dw_id,
    remittance.payor_dw_id,
    remittance.remittance_advice_num,
    remittance.ra_log_date,
    remittance.log_id,
    remittance.log_sequence_num,
    remittance.pat_acct_num,
    remittance.iplan_id,
    remittance.cc_ep_iplan_id,
    remittance.ar_bill_thru_date,
    remittance.payment_date,
    remittance.ra_reference_num,
    remittance.cc_remittance_header_id,
    remittance.cc_remittance_id,
    remittance.cc_replaced_by_remittance_id,
    remittance.ra_transaction_date,
    remittance.ra_drg_code,
    remittance.ra_hipps_code,
    remittance.ra_covered_days_num,
    remittance.ra_total_charge_amt,
    remittance.ra_non_covered_charge_amt,
    remittance.ra_net_billed_charge_amt,
    remittance.ra_deductible_amt,
    remittance.ra_coinsurance_amt,
    remittance.ra_net_benefit_amt,
    remittance.ra_insurance_payment_amt,
    remittance.ra_reversal_code,
    remittance.outlier_ind,
    remittance.cc_visit_cnt,
    remittance.cc_covered_days_visit_cnt,
    remittance.cc_discharge_fraction_pct,
    remittance.cc_reimbursement_rate_pct,
    remittance.cc_non_replaced_blood_unit_qty,
    remittance.cc_prescription_qty,
    remittance.cc_patient_responsible_amt,
    remittance.cc_patient_qualifier_code,
    remittance.cc_claim_status_code,
    remittance.cc_patient_status_code,
    remittance.cc_claim_filing_ind_code,
    remittance.cc_medicare_format_code,
    remittance.cc_claim_frequency_code,
    remittance.cc_payer_claim_control_num,
    remittance.cc_recieve_date,
    remittance.cc_service_start_date,
    remittance.cc_service_end_date,
    remittance.cc_coverage_expiration_date,
    remittance.cc_payer_patient_id,
    remittance.cc_payer_member_id,
    remittance.cc_source_type_id,
    remittance.active_ind,
    remittance.dw_last_update_date_time,
    remittance.source_system_code
  FROM
    `hca-hin-dev-cur-parallon`.edwpf_base_views.remittance
;
