#!/bin/ksh
# *****************************************************************************
# 
# Kornshell script generated by DMExpress for defining user variables 
# 
# Version: 7.1.0
# Date:    Tuesday, August 21, 2012 04:21:49 AM
# 
# Note:
# 1.       This script should be run using the Korn Shell (ksh) script interpreter. 
#
# 2.       You may modify this script as required and still reimport it into the 
#          DMExpress status window as long as DMExpress tags are maintained and 
#          the variables are defined using "export<space>name=value<endOfLine>" 
#          notation
#
# *****************************************************************************



export DB2_SRC_DB='ERP1DB'
export DB2_SRC_USER='DMXERP1'
export DB2_SRC_PASSWORD='dmxbasep'



##export NCR_EXP_DB='ncrqaconn'
##export NCR_EXP_USER='DMX_HRLOAD'
##export NCR_EXP_PASSWORD='j5gv3as9b6hcx'

export NCR_EXP_DB='ncrqaconn'
export NCR_EXP_USER='DMX_HRLOAD'
export NCR_EXP_PASSWORD='j5gv3as9b6hcx'

export DB2_HDW_DB='ERP1DB'
export DB2_HDW_USER='DMXERP1'
export DB2_HDW_PASSWORD='dmxbasep'

export DB2_EXP_DB='ERP1DB'
export DB2_EXP_USER='DMXERP1'
export DB2_EXP_PASSWORD='dmxbasep'

export DB2_SRC_SCHEMA='LPAHCA'

##export DB2_SRC_SCHEMA='LQAOAX5'

##export DB2_HDW_DB='ERQ1DB'
##export DB2_HDW_USER='DMXERQ1'
##export DB2_HDW_PASSWORD='t3mv39v'

##export DB2_EXP_DB='ERQ1DB'
##export DB2_EXP_USER='DMXERQ1'
##export DB2_EXP_PASSWORD='t3mv39v'


export DB2_DSNP_SRC_DB='dsnpdb'
export DB2_DSNP_SRC_USER='dmxdsnp'
export DB2_DSNP_SRC_PASSWORD='dmxbasep'

export DB2_DSNP_EXP_DB='dsnpdb'
export DB2_DSNP_EXP_USER='dmxdsnp'
export DB2_DSNP_EXP_PASSWORD='dmxbasep'

export DB2_DSNP_HDW_DB='dsnpdb'
export DB2_DSNP_HDW_USER='dmxdsnp'
export DB2_DSNP_HDW_PASSWORD='dmxbasep'

export NCR_HDW_DB='ncrqaconn'
export NCR_HDW_USER='DMX_HRLOAD'
export NCR_HDW_PASSWORD='j5gv3as9b6hcx'

export NCR_SERVER='qabox'

export NCR_ACT_DB='ncrqaconn'
export NCR_ACT_USER='DMX_HRLOAD'
export NCR_ACT_PASSWORD='j5gv3as9b6hcx'
export NCR_AC_DB='ncrqaconn'
export NCR_AC_USER='DMX_HRLOAD'
export NCR_AC_PASSWORD='j5gv3as9b6hcx'
export NCR_AC_SCHEMA='EDWHR_DMX_AC'
export NCR_AC_VIEW='EDWHR_DMX_AC_BASE_VIEWS'

export NCR_TGT_SCHEMA='EDWHR'
export NCR_STG_SCHEMA='EDWHR_STAGING'

export EDWHR_BASE_VIEWS='EDWHR_BASE_VIEWS'
export EDW_PUB_VIEWS='EDW_PUB_VIEWS'
export EDWHR_VIEWS='EDWHR_VIEWS'



export ORA_SRC_SCHEMA='HCAPRD'

#####ADDED BELOW VARIABLES FOR ORACLE CONNECTION ON 10/14/2016

#export ODS_HRDM_DB='ODSNASP2'
#export ODS_HRDM_USER='ODS_HRDM_READ'
#export ODS_HRDM_PASS='LDa_xvJ8S!'


#export ORA_EXP_DB='ODSNASP2'
#export ORA_EXP_USER='ODS_HRDM_READ'
#export ORA_EXP_PASSWORD='LDa_xvJ8S!'

#export ODBC_AC_DB='ODSNASP2'
#export ODBC_AC_USER='ODS_HRDM_READ'
#export ODBC_AC_PASSWORD='LDa_xvJ8S!'

#export ODBC_AC_DB='OMEGA'
#export ODBC_AC_USER='hcadev_read'
#export ODBC_AC_PASSWORD='h6mq8RXA'

export ODBC_AC_DB='ncrqaconn'
export ODBC_AC_USER='DMX_HRLOAD'
export ODBC_AC_PASSWORD='j5gv3as9b6hcx'

#export ORA_EXP_DB='OMEGA'
#export ORA_EXP_USER='hcadev_read'
#export ORA_EXP_PASSWORD='h6mq8RXA'

export ORA_EXP_DB='ALPHA'
export ORA_EXP_USER='hcaprd_read'
export ORA_EXP_PASSWORD='Ah8qnugE'



#export ORA_TAL_DB='ODSNASP2'
export ORA_TAL_DB='ODSNASP3'
export ORA_TAL_USER='taleo_load'
export ORA_TAL_PASSWORD='9SRwP@92G!'


#####ADDED BELOW VARIABLES FOR SQL SERVER XRDCWDDBSBIC01 ( HCAPS ) CONNECTION ON 03/May/2017 #####


export ODBC_HRDM_DB='HCAHPS_SQL_SERVER'
export ODBC_HRDM_USER='CorpSVC_HCAHPS_Read'
export ODBC_HRDM_PASSWORD='rYI;~j29'

export ODBC_EXP_DB='HCAHPS_SQL_SERVER'
export ODBC_EXP_USER='CorpSVC_HCAHPS_Read'
export ODBC_EXP_PASSWORD='rYI;~j29'




#####ADDED BELOW VARIABLES FOR SQL SERVER XRDCWQDBSHDW01 ( LAWSON ) CONNECTION ON 07/19/2017



export ODBC_LAW_DB='LAWSON_SQL_SERVER'
export ODBC_LAW_USER='CorpSvcEDWLoad'
export ODBC_LAW_PASSWORD='EdWhR1!'


export ODBC_EXP_DB='LAWSON_SQL_SERVER'
export ODBC_EXP_USER='CorpSvcEDWLoad'
export ODBC_EXP_PASSWORD='EdWhR1!'



export ORA_LAW_DB='OMEGA'
export ORA_LAW_USER='hcadev_read'
export ORA_LAW_PASS='h6mq8RXA'

export ORA_Table_DB='ODSNASD3'
export ORA_User_Table='HCADEV'
export ORA_Pass_Table='w4$pM!vM'

export ORA_LAW_MH_PROD_DB='ALPHA'
export ORA_LAW_MH_PROD_USER='hcaprd_read'
export ORA_LAW_MH_PROD_PASS='Ah8qnugE'


######ADDED BELOW VARIABLES FOR ORACLE SERVER ODSNASQ3 ( MISSION ) CONNETION ON 06/11/2019

#export ORA_MH_ORAMH_DB='ODSNASQ3'
#export ORA_MH_ORAMH_USER='ORA_HRAIT_MH'
#export ORA_MH_ORAMH_PASSWORD='Nash_preds2019'

export ORA_MH_ORAMH_DB='ODSNASP3'
export ORA_MH_ORAMH_USER='ORA_HRAIT_MH'
export ORA_MH_ORAMH_PASSWORD='Habitat_2020'

export ODBC_HRIS_DB='SQL_HRIS'
export ODBC_HRIS_USER='etl_hris'
export ODBC_HRIS_PASSWORD='HCAhealthcare1'


export DB2_HDW_LANDMARK_DB_PROD='LMPWHCA'
export DB2_HDW_LANDMARK_USER_PROD='dmxmrk'
export DB2_HDW_LANDMARK_PASSWORD_PROD='Yo58pnRgmVex0ovP'

export DB2_HDW_LANDMARK_DB='LMQWQA2'
export DB2_HDW_LANDMARK_USER='dmxmrk'
export DB2_HDW_LANDMARK_PASSWORD='Rtgtvpt6nYeXZKiH'

export ODBC_Data_Lake_DB='ODBC_DataLake'
export ODBC_Data_Lake_USER='CorpSvcEdwRpt'
export ODBC_Data_Lake_PWD='EDWRPT123!'

export DB2_LANDMARK_SCHEMA='lmwf'
