-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/collection_encounter_detail_crnt.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.collection_encounter_detail_crnt
   OPTIONS(description='A daily inventory pull from Artiva system, that has the collections related work orders which has current refreshed data.\rThis structure is the exact copy of the existing Edwpbs.Collection_Encounter_Detail')
  AS SELECT
      ROUND(a.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      a.reporting_date,
      a.day_interval_sid,
      a.liability_sequence_number,
      a.artiva_instance_code,
      a.company_code,
      a.coid,
      a.unit_num,
      ROUND(a.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      a.patient_type_code,
      a.account_status_code,
      a.lob_grp_code,
      a.iplan_id,
      ROUND(a.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
      a.discharge_age_month_sid,
      a.last_worked_age_month_sid,
      a.delinquent_days_age_sid,
      a.encounter_financial_class_code,
      a.liability_financial_class_code,
      a.hic_claim_num,
      a.claim_num,
      a.check_num_an,
      a.medical_record_num,
      a.early_out_hold_ind,
      a.vendor_id,
      a.prev_vendor_id,
      a.liability_phase_status_desc,
      a.prev_liability_phase_desc,
      a.phase_change_date,
      a.status_desc,
      a.prior_status_desc,
      a.denial_status_code,
      a.bad_debt_reason_code,
      a.encounter_date,
      a.wait_date,
      a.denial_date,
      a.claim_submit_date,
      a.final_bill_date,
      a.early_out_date,
      a.liability_last_billed_date,
      a.liability_last_worked_date,
      a.last_worked_age_days_cnt,
      a.prev_pool_assignment_id,
      a.prev_pool_date,
      a.current_pool_assignment_id,
      a.pool_responsible_dept_name,
      a.inclusion_flag,
      a.action_code,
      a.result_code,
      a.last_action_date,
      a.last_action_time,
      a.last_action_updt_by_user_id,
      a.service_code,
      a.delinquent_days_cnt,
      ROUND(a.cc_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_activity_type_id,
      ROUND(a.cc_prev_activity_type_id, 0, 'ROUND_HALF_EVEN') AS cc_prev_activity_type_id,
      ROUND(a.total_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_billed_charge_amt,
      ROUND(a.non_bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS non_bill_charge_amt,
      ROUND(a.encounter_balance_amt, 3, 'ROUND_HALF_EVEN') AS encounter_balance_amt,
      ROUND(a.original_balance_amt, 3, 'ROUND_HALF_EVEN') AS original_balance_amt,
      ROUND(a.current_balance_amt, 3, 'ROUND_HALF_EVEN') AS current_balance_amt,
      a.liability_level_code,
      ROUND(a.total_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_adjustment_amt,
      ROUND(a.total_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_payment_amt,
      ROUND(a.placement_amt, 3, 'ROUND_HALF_EVEN') AS placement_amt,
      a.placement_date,
      a.placement_level_num,
      a.appeal_flag,
      a.appeal_source_system_code,
      a.denial_code,
      a.appeal_disp_code,
      a.appeal_level_num,
      a.appeal_seq_num,
      ROUND(a.appeal_source_system_id, 0, 'ROUND_HALF_EVEN') AS appeal_source_system_id,
      a.appeal_sent_date,
      a.appeal_follow_up_date,
      a.appeal_closing_date,
      ROUND(a.appeal_amt, 3, 'ROUND_HALF_EVEN') AS appeal_amt,
      a.admission_date,
      a.discharge_date,
      a.last_claim_status_rspn_date,
      a.last_claim_status_rspn_code,
      a.last_claim_status_rspn_type_code,
      a.last_claim_status_rspn_pblm_code,
      a.last_claim_status_rspn_scat_id,
      a.user_alert_comment_text,
      a.user_alert_edit_date_time,
      a.alert_created_by_user_id,
      a.user_alert_expr_date,
      a.billing_history_ind,
      ROUND(a.insgn_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS insgn_account_balance_amt,
      ROUND(a.episode_id, 0, 'ROUND_HALF_EVEN') AS episode_id,
      ROUND(a.patient_id, 0, 'ROUND_HALF_EVEN') AS patient_id,
      a.notice_of_admission_date,
      a.notice_of_election_date,
      a.erisa_ind,
      a.hosp_dc_screening_status_flag,
      a.screening_letter_include_ind,
      a.elig_program_id,
      a.elig_screening_date,
      a.web_status_flag,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_pbs_base_views_dataset_name }}.collection_encounter_detail_crnt AS a
      INNER JOIN {{ params.param_auth_base_views_dataset_name }}.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
       AND upper(a.coid) = upper(b.co_id)
       AND b.user_id = session_user()
  ;
