-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/fact_rcom_pars_discrepancy.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.fact_rcom_pars_discrepancy AS SELECT
    a.date_sid,
    ROUND(a.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    ROUND(a.payor_dw_id, 0, 'ROUND_HALF_EVEN') AS payor_dw_id,
    a.iplan_insurance_order_num,
    a.eor_log_date,
    a.log_id,
    a.ar_bill_thru_date,
    a.log_sequence_num,
    a.discrepancy_creation_date,
    a.year_created_sid,
    ROUND(a.patient_sid, 0, 'ROUND_HALF_EVEN') AS patient_sid,
    a.payor_financial_class_sid,
    a.payor_sid,
    a.payor_sequence_sid,
    a.patient_type_sid,
    a.unit_num_sid,
    a.discrepancy_age_month_sid,
    a.discharge_age_month_sid,
    a.scenario_sid,
    ROUND(a.reason_code_1_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_1_sid,
    ROUND(a.reason_code_2_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_2_sid,
    ROUND(a.reason_code_3_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_3_sid,
    ROUND(a.reason_code_4_sid, 0, 'ROUND_HALF_EVEN') AS reason_code_4_sid,
    a.gross_rbmt_dcrp_type_sid,
    a.cont_alw_dcrp_type_sid,
    a.payment_dcrp_type_sid,
    a.charge_dcrp_type_sid,
    a.gross_rbmt_new_strf_sid,
    a.cont_alw_new_strf_sid,
    a.payment_new_strf_sid,
    a.charge_new_strf_sid,
    a.gross_rbmt_end_strf_sid,
    a.cont_alw_end_strf_sid,
    a.payment_end_strf_sid,
    a.charge_end_strf_sid,
    a.source_sid,
    a.coid,
    a.company_code,
    a.resolve_reason_code,
    a.discharge_date,
    a.ra_remit_date,
    a.reason_assignment_date_1,
    a.reason_assignment_date_2,
    a.reason_assignment_date_3,
    a.reason_assignment_date_4,
    ROUND(a.account_balance_amt, 3, 'ROUND_HALF_EVEN') AS account_balance_amt,
    ROUND(a.var_gross_rbmt_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_rbmt_beg_amt,
    ROUND(a.var_gross_rbmt_new_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_rbmt_new_amt,
    ROUND(a.var_gross_rbmt_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_rbmt_resolved_amt,
    ROUND(a.var_gross_rbmt_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_rbmt_othr_cor_amt,
    ROUND(a.var_gross_rbmt_end_amt, 3, 'ROUND_HALF_EVEN') AS var_gross_rbmt_end_amt,
    ROUND(a.exp_gross_rbmt_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_gross_rbmt_crnt_amt,
    ROUND(a.exp_gross_rbmt_rate_amt, 3, 'ROUND_HALF_EVEN') AS exp_gross_rbmt_rate_amt,
    a.var_gross_rbmt_beg_cnt,
    a.var_gross_rbmt_new_cnt,
    a.var_gross_rbmt_resolved_cnt,
    a.var_gross_rbmt_othr_cor_cnt,
    a.var_gross_rbmt_end_cnt,
    a.exp_gross_rbmt_crnt_cnt,
    a.exp_gross_rbmt_rate_cnt,
    ROUND(a.var_cont_alw_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_cont_alw_beg_amt,
    ROUND(a.var_cont_alw_new_amt, 3, 'ROUND_HALF_EVEN') AS var_cont_alw_new_amt,
    ROUND(a.var_cont_alw_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_cont_alw_resolved_amt,
    ROUND(a.var_cont_alw_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_cont_alw_othr_cor_amt,
    ROUND(a.var_cont_alw_end_amt, 3, 'ROUND_HALF_EVEN') AS var_cont_alw_end_amt,
    ROUND(a.exp_cont_alw_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_cont_alw_crnt_amt,
    ROUND(a.exp_cont_alw_rate_amt, 3, 'ROUND_HALF_EVEN') AS exp_cont_alw_rate_amt,
    a.var_cont_alw_beg_cnt,
    a.var_cont_alw_new_cnt,
    a.var_cont_alw_resolved_cnt,
    a.var_cont_alw_othr_cor_cnt,
    a.var_cont_alw_end_cnt,
    a.exp_cont_alw_crnt_cnt,
    a.exp_cont_alw_rate_cnt,
    ROUND(a.var_payment_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_payment_beg_amt,
    ROUND(a.var_payment_new_amt, 3, 'ROUND_HALF_EVEN') AS var_payment_new_amt,
    ROUND(a.var_payment_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_payment_resolved_amt,
    ROUND(a.var_payment_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_payment_othr_cor_amt,
    ROUND(a.var_payment_end_amt, 3, 'ROUND_HALF_EVEN') AS var_payment_end_amt,
    ROUND(a.exp_payment_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_payment_crnt_amt,
    ROUND(a.exp_payment_rate_amt, 3, 'ROUND_HALF_EVEN') AS exp_payment_rate_amt,
    a.var_payment_beg_cnt,
    a.var_payment_new_cnt,
    a.var_payment_resolved_cnt,
    a.var_payment_othr_cor_cnt,
    a.var_payment_end_cnt,
    a.exp_payment_crnt_cnt,
    a.exp_payment_rate_cnt,
    ROUND(a.var_charge_beg_amt, 3, 'ROUND_HALF_EVEN') AS var_charge_beg_amt,
    ROUND(a.var_charge_new_amt, 3, 'ROUND_HALF_EVEN') AS var_charge_new_amt,
    ROUND(a.var_charge_resolved_amt, 3, 'ROUND_HALF_EVEN') AS var_charge_resolved_amt,
    ROUND(a.var_charge_othr_cor_amt, 3, 'ROUND_HALF_EVEN') AS var_charge_othr_cor_amt,
    ROUND(a.exp_charge_crnt_amt, 3, 'ROUND_HALF_EVEN') AS exp_charge_crnt_amt,
    ROUND(a.var_charge_end_amt, 3, 'ROUND_HALF_EVEN') AS var_charge_end_amt,
    a.var_charge_beg_cnt,
    a.var_charge_new_cnt,
    a.var_charge_resolved_cnt,
    a.var_charge_othr_cor_cnt,
    a.exp_charge_crnt_cnt,
    a.var_charge_end_cnt,
    a.primary_reason_code_change_cnt,
    a.discrepancy_days,
    a.discrepancy_resolved_date,
    ROUND(a.cc_reason_id, 0, 'ROUND_HALF_EVEN') AS cc_reason_id,
    ROUND(a.cc_account_payer_status_id, 0, 'ROUND_HALF_EVEN') AS cc_account_payer_status_id
  FROM
    {{ params.param_pbs_base_views_dataset_name }}.fact_rcom_pars_discrepancy AS a
    CROSS JOIN {{ params.param_auth_base_views_dataset_name }}.secref_facility AS b
  WHERE upper(b.co_id) = upper(a.coid)
   AND upper(b.company_code) = upper(a.company_code)
   AND b.user_id = session_user()
;
