-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/pass_eom_lp.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.pass_eom_lp AS SELECT
    ROUND(pass_eom_lp.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
    pass_eom_lp.company_code,
    pass_eom_lp.coid,
    pass_eom_lp.unit_num,
    pass_eom_lp.processing_zone_code,
    pass_eom_lp.stack_code,
    pass_eom_lp.rptg_period,
    ROUND(pass_eom_lp.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
    pass_eom_lp.facility_name,
    CASE
      WHEN session_user() = z.userid THEN '***'
      ELSE pass_eom_lp.patient_full_name
    END AS patient_full_name,
    ROUND(pass_eom_lp.financial_class_code, 0, 'ROUND_HALF_EVEN') AS financial_class_code,
    pass_eom_lp.financial_class_desc,
    pass_eom_lp.patient_type_code,
    pass_eom_lp.derived_patient_type_code,
    pass_eom_lp.account_status_code,
    pass_eom_lp.admission_date,
    pass_eom_lp.discharge_date,
    pass_eom_lp.final_bill_date,
    pass_eom_lp.ar_bill_thru_date,
    pass_eom_lp.length_of_stay_days_num,
    ROUND(pass_eom_lp.collector_org_code, 0, 'ROUND_HALF_EVEN') AS collector_org_code,
    pass_eom_lp.collector_org_type_code,
    pass_eom_lp.collector_org_short_name,
    pass_eom_lp.log_id,
    pass_eom_lp.log_name,
    pass_eom_lp.ip_contract_model_code,
    pass_eom_lp.iplan_id_ins1,
    pass_eom_lp.payor_name_ins1,
    pass_eom_lp.release_ind_ins1,
    ROUND(pass_eom_lp.payor_balance_amt_ins1, 3, 'ROUND_HALF_EVEN') AS payor_balance_amt_ins1,
    ROUND(pass_eom_lp.payor_liability_amt_ins1, 3, 'ROUND_HALF_EVEN') AS payor_liability_amt_ins1,
    ROUND(pass_eom_lp.payor_payment_amt_ins1, 3, 'ROUND_HALF_EVEN') AS payor_payment_amt_ins1,
    ROUND(pass_eom_lp.payor_adjustment_amt_ins1, 3, 'ROUND_HALF_EVEN') AS payor_adjustment_amt_ins1,
    ROUND(pass_eom_lp.payor_contract_allow_amt_ins1, 3, 'ROUND_HALF_EVEN') AS payor_contract_allow_amt_ins1,
    ROUND(pass_eom_lp.pa_syst_adj_current_amt_ins1, 3, 'ROUND_HALF_EVEN') AS pa_syst_adj_current_amt_ins1,
    ROUND(pass_eom_lp.pa_new_actv_current_amt_ins1, 3, 'ROUND_HALF_EVEN') AS pa_new_actv_current_amt_ins1,
    pass_eom_lp.iplan_id_ins2,
    pass_eom_lp.payor_name_ins2,
    pass_eom_lp.release_ind_ins2,
    ROUND(pass_eom_lp.payor_balance_amt_ins2, 3, 'ROUND_HALF_EVEN') AS payor_balance_amt_ins2,
    ROUND(pass_eom_lp.payor_liability_amt_ins2, 3, 'ROUND_HALF_EVEN') AS payor_liability_amt_ins2,
    ROUND(pass_eom_lp.payor_payment_amt_ins2, 3, 'ROUND_HALF_EVEN') AS payor_payment_amt_ins2,
    ROUND(pass_eom_lp.payor_adjustment_amt_ins2, 3, 'ROUND_HALF_EVEN') AS payor_adjustment_amt_ins2,
    ROUND(pass_eom_lp.payor_contract_allow_amt_ins2, 3, 'ROUND_HALF_EVEN') AS payor_contract_allow_amt_ins2,
    ROUND(pass_eom_lp.pa_syst_adj_current_amt_ins2, 3, 'ROUND_HALF_EVEN') AS pa_syst_adj_current_amt_ins2,
    ROUND(pass_eom_lp.pa_new_actv_current_amt_ins2, 3, 'ROUND_HALF_EVEN') AS pa_new_actv_current_amt_ins2,
    pass_eom_lp.iplan_id_ins3,
    pass_eom_lp.payor_name_ins3,
    pass_eom_lp.release_ind_ins3,
    ROUND(pass_eom_lp.payor_balance_amt_ins3, 3, 'ROUND_HALF_EVEN') AS payor_balance_amt_ins3,
    ROUND(pass_eom_lp.payor_liability_amt_ins3, 3, 'ROUND_HALF_EVEN') AS payor_liability_amt_ins3,
    ROUND(pass_eom_lp.payor_payment_amt_ins3, 3, 'ROUND_HALF_EVEN') AS payor_payment_amt_ins3,
    ROUND(pass_eom_lp.payor_adjustment_amt_ins3, 3, 'ROUND_HALF_EVEN') AS payor_adjustment_amt_ins3,
    ROUND(pass_eom_lp.payor_contract_allow_amt_ins3, 3, 'ROUND_HALF_EVEN') AS payor_contract_allow_amt_ins3,
    ROUND(pass_eom_lp.pa_syst_adj_current_amt_ins3, 3, 'ROUND_HALF_EVEN') AS pa_syst_adj_current_amt_ins3,
    ROUND(pass_eom_lp.pa_new_actv_current_amt_ins3, 3, 'ROUND_HALF_EVEN') AS pa_new_actv_current_amt_ins3,
    ROUND(pass_eom_lp.patient_balance_amt, 3, 'ROUND_HALF_EVEN') AS patient_balance_amt,
    ROUND(pass_eom_lp.patient_liability_amt, 3, 'ROUND_HALF_EVEN') AS patient_liability_amt,
    ROUND(pass_eom_lp.patient_payment_amt, 3, 'ROUND_HALF_EVEN') AS patient_payment_amt,
    ROUND(pass_eom_lp.patient_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS patient_adjustment_amt,
    ROUND(pass_eom_lp.patient_contract_allow_amt, 3, 'ROUND_HALF_EVEN') AS patient_contract_allow_amt,
    ROUND(pass_eom_lp.total_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_billed_charge_amt,
    ROUND(pass_eom_lp.total_rb_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_rb_charge_amt,
    ROUND(pass_eom_lp.total_anc_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_anc_charge_amt,
    ROUND(pass_eom_lp.total_write_off_bad_debt_amt, 3, 'ROUND_HALF_EVEN') AS total_write_off_bad_debt_amt,
    ROUND(pass_eom_lp.total_write_off_other_amt, 3, 'ROUND_HALF_EVEN') AS total_write_off_other_amt,
    ROUND(pass_eom_lp.total_adjustment_amt, 3, 'ROUND_HALF_EVEN') AS total_adjustment_amt,
    ROUND(pass_eom_lp.total_contract_allow_amt, 3, 'ROUND_HALF_EVEN') AS total_contract_allow_amt,
    ROUND(pass_eom_lp.total_combined_adj_alw_amt, 3, 'ROUND_HALF_EVEN') AS total_combined_adj_alw_amt,
    ROUND(pass_eom_lp.total_payment_amt, 3, 'ROUND_HALF_EVEN') AS total_payment_amt,
    ROUND(pass_eom_lp.total_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS total_account_balance_amt,
    ROUND(pass_eom_lp.prelim_account_balance_amt, 3, 'ROUND_HALF_EVEN') AS prelim_account_balance_amt,
    ROUND(pass_eom_lp.eor_gross_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS eor_gross_reimbursement_amt,
    ROUND(pass_eom_lp.eor_contract_allow_amt, 3, 'ROUND_HALF_EVEN') AS eor_contract_allow_amt,
    ROUND(pass_eom_lp.eor_auto_post_amt, 3, 'ROUND_HALF_EVEN') AS eor_auto_post_amt,
    pass_eom_lp.discharge_to_eom_day_cnt,
    ROUND(pass_eom_lp.current_month_amt, 3, 'ROUND_HALF_EVEN') AS current_month_amt,
    pass_eom_lp.sub_unit_num,
    pass_eom_lp.sub_unit_name,
    pass_eom_lp.drg_code,
    pass_eom_lp.icd_version_ind,
    ROUND(pass_eom_lp.drg_payment_weight_amt, 5, 'ROUND_HALF_EVEN') AS drg_payment_weight_amt,
    pass_eom_lp.drg_code_hcfa,
    pass_eom_lp.drg_code_classic,
    pass_eom_lp.drg_code_pre_hac,
    pass_eom_lp.drg_code_pre_hac_tricare,
    pass_eom_lp.denial_code_ins1,
    ROUND(pass_eom_lp.financial_class_code_ins1, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins1,
    pass_eom_lp.denial_code_ins2,
    ROUND(pass_eom_lp.financial_class_code_ins2, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins2,
    pass_eom_lp.denial_code_ins3,
    ROUND(pass_eom_lp.financial_class_code_ins3, 0, 'ROUND_HALF_EVEN') AS financial_class_code_ins3,
    ROUND(pass_eom_lp.prorated_release_amt_ins1, 3, 'ROUND_HALF_EVEN') AS prorated_release_amt_ins1,
    ROUND(pass_eom_lp.prorated_release_amt_ins2, 3, 'ROUND_HALF_EVEN') AS prorated_release_amt_ins2,
    ROUND(pass_eom_lp.prorated_release_amt_ins3, 3, 'ROUND_HALF_EVEN') AS prorated_release_amt_ins3,
    pass_eom_lp.prorated_release_date_ins1,
    pass_eom_lp.prorated_release_date_ins2,
    pass_eom_lp.prorated_release_date_ins3,
    pass_eom_lp.logging_ind,
    pass_eom_lp.auto_post_ind,
    pass_eom_lp.unbill_pre_admit_ind,
    pass_eom_lp.insured_employer_name,
    pass_eom_lp.insured_role_code,
    pass_eom_lp.apr_severity_of_illness,
    pass_eom_lp.apr_risk_of_mortality
  FROM
    {{ params.param_pbs_base_views_dataset_name }}.pass_eom_lp
    LEFT OUTER JOIN (
      SELECT
          security_mask_and_exception.userid,
          security_mask_and_exception.masked_column_code
        FROM
          {{ params.param_sec_core_dataset_name }}.security_mask_and_exception
        WHERE security_mask_and_exception.userid = session_user()
         AND upper(security_mask_and_exception.masked_column_code) = 'PN'
    ) AS z ON session_user() = z.userid
;
