-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/prebill_denial_detail.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.prebill_denial_detail
   OPTIONS(description='PreBill Denial Inventory for Parallon Customers. This is will have a monthly data and daily data for 7 days rolling.')
  AS SELECT
      a.company_code,
      a.coid,
      a.rptg_date,
      a.account_id,
      ROUND(a.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      a.unit_num,
      a.facility_tax_id,
      a.med_rec_num,
      a.birth_date,
      a.admit_date,
      a.discharge_date,
      a.provider_num_code,
      a.work_group_id,
      a.work_group_name,
      ROUND(a.financial_class_code, 0, 'ROUND_HALF_EVEN') AS financial_class_code,
      ROUND(a.national_provider_id, 0, 'ROUND_HALF_EVEN') AS national_provider_id,
      a.iplan_ins1_id,
      a.iplan_id_ins1_name,
      a.iplan_ins2_id,
      a.iplan_id_ins2_name,
      a.pdu_initiated_date,
      a.status_code,
      a.status_desc,
      a.final_bill_date,
      a.bill_hold_start_date,
      a.bill_hold_end_date,
      a.xu_date,
      a.physician_advisor_vendor_name,
      a.denial_record_code,
      a.auth_code,
      a.auth_type_code,
      a.auth_date,
      a.initial_auth_status_code,
      a.current_deadline_date,
      a.certification_end_date,
      a.admitting_physician_name,
      a.attending_physician_name,
      ROUND(a.attending_physician_tax_id, 0, 'ROUND_HALF_EVEN') AS attending_physician_tax_id,
      a.service_code,
      a.admitting_dx_code,
      a.rebill_requested_date,
      a.review_reason1_desc,
      a.review_reason2_desc,
      a.review_reason3_desc,
      a.review_reason4_desc,
      a.denial_reason1_desc,
      a.denial_reason2_desc,
      a.denial_reason3_desc,
      a.denial_reason4_desc,
      a.root_cause1_desc,
      a.root_cause2_desc,
      a.root_cause3_desc,
      a.root_cause4_desc,
      a.pdu_iqreview1_ind,
      a.pdu_iqreview2_ind,
      a.pdu_iqreview3_ind,
      a.pdu_iqreview4_ind,
      a.agreed1_ind,
      a.agreed2_ind,
      a.agreed3_ind,
      a.agreed4_ind,
      a.sum_day_cnt,
      a.final_day_denied_cnt,
      ROUND(a.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      ROUND(a.expected_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS expected_reimbursement_amt,
      ROUND(a.actual_reimbursement_amt, 3, 'ROUND_HALF_EVEN') AS actual_reimbursement_amt,
      a.determination_reason_code,
      a.determination_reason_desc,
      a.alos_day_cnt,
      a.no_certification_required_cnt,
      a.ssc_certed_day_cnt,
      a.cm_certed_day_cnt,
      a.post_discharge_day_cnt,
      a.inhouse_final_denied_day_cnt,
      a.post_discharge_overturned_day_cnt,
      a.denial_revenue_day1_cnt,
      a.denial_revenue_day2_cnt,
      a.denial_revenue_day3_cnt,
      a.denial_revenue_day4_cnt,
      a.total_approved_day_cnt,
      a.total_denied_day_cnt,
      a.ptp_outcome_desc,
      a.ptp_requested_date,
      a.final_case_closure_date,
      a.clinical_submitted_note_desc,
      a.clinical_submitted_date,
      a.payor_response_desc,
      a.denial_reconsideration_response,
      a.reconsideration_submit_date,
      a.interqual_completed_ind,
      a.analyst_reviewed_date,
      a.analyst_payor_contact_date,
      a.analyst_work_again_date,
      a.analyst_worked_user_id,
      a.nurse_initial_review_date,
      a.nurse_payor_contact_date,
      a.nurse_work_again_date,
      a.nurse_worked_user_id,
      a.denial_initial_review_date,
      a.denial_payor_contact_date,
      a.denial_work_again_date,
      a.denial_worked_user_id,
      a.verified_user_id,
      a.verification_date,
      a.modified_date,
      a.modified_user_id,
      a.created_date,
      a.created_user_id,
      a.assigned_user_id,
      a.manual_review_reason_desc,
      a.ar_status_code,
      a.denial_probability_desc,
      a.pilot_acct_ind,
      a.pilot_acct_user_review_1_txt,
      a.pilot_acct_user_review_2_txt,
      a.pilot_acct_user_review_3_txt,
      a.pilot_acct_user_review_4_txt
    FROM
      {{ params.param_pbs_base_views_dataset_name }}.prebill_denial_detail AS a
      INNER JOIN {{ params.param_auth_base_views_dataset_name }}.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
       AND upper(a.coid) = upper(b.co_id)
       AND b.user_id = session_user()
  ;
