-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/remittance_payment.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.remittance_payment
   OPTIONS(description='This is the check payment information recevied by Electronic Payment team from each payor by facility/provider.It also includes Control elements associated with the payer')
  AS SELECT
      a.payment_guid,
      a.check_num_an,
      a.check_date,
      ROUND(a.check_amt, 3, 'ROUND_HALF_EVEN') AS check_amt,
      a.interchange_sender_id,
      a.provider_level_adj_id,
      a.remittance_payor_sid,
      a.remittance_payee_sid,
      a.audit_date,
      a.delete_ind,
      a.delete_date,
      a.coid,
      a.company_code,
      a.unit_num,
      a.era_create_date,
      a.bill_process_date,
      a.ep_effective_post_date,
      a.ep_create_date,
      ROUND(a.bill_charge_amt, 3, 'ROUND_HALF_EVEN') AS bill_charge_amt,
      ROUND(a.covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS covered_charge_amt,
      ROUND(a.ep_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_non_covered_charge_amt,
      ROUND(a.ep_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ep_coinsurance_amt,
      ROUND(a.ep_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS ep_contractual_adj_amt,
      ROUND(a.ep_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_deductible_amt,
      ROUND(a.ep_denial_amt, 3, 'ROUND_HALF_EVEN') AS ep_denial_amt,
      ROUND(a.drg_amt, 3, 'ROUND_HALF_EVEN') AS drg_amt,
      ROUND(a.federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS federal_specific_drg_amt,
      ROUND(a.ep_calc_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_blood_deductible_amt,
      ROUND(a.ep_calc_hcpcs_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_hcpcs_charge_amt,
      ROUND(a.ep_calc_hcpcs_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_hcpcs_payment_amt,
      ROUND(a.apc_amt, 3, 'ROUND_HALF_EVEN') AS apc_amt,
      ROUND(a.capital_amt, 3, 'ROUND_HALF_EVEN') AS capital_amt,
      ROUND(a.disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS disproportionate_share_amt,
      ROUND(a.indirect_teaching_amt, 3, 'ROUND_HALF_EVEN') AS indirect_teaching_amt,
      ROUND(a.interest_amt, 3, 'ROUND_HALF_EVEN') AS interest_amt,
      ROUND(a.claim_payment_amt, 3, 'ROUND_HALF_EVEN') AS claim_payment_amt,
      ROUND(a.ep_lab_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_lab_charge_amt,
      ROUND(a.ep_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_lab_payment_amt,
      ROUND(a.ep_nonpayable_professional_fee_amt, 3, 'ROUND_HALF_EVEN') AS ep_nonpayable_professional_fee_amt,
      ROUND(a.outlier_amt, 3, 'ROUND_HALF_EVEN') AS outlier_amt,
      ROUND(a.patient_liability_amt, 3, 'ROUND_HALF_EVEN') AS patient_liability_amt,
      ROUND(a.ep_primary_insurance_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_primary_insurance_payment_amt,
      ROUND(a.ep_therapy_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_therapy_charge_amt,
      ROUND(a.ep_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_therapy_payment_amt,
      ROUND(a.ins_covered_day_cnt, 2, 'ROUND_HALF_EVEN') AS ins_covered_day_cnt,
      a.ep_calc_covered_day_cnt,
      a.noncovered_day_cnt,
      a.claim_cnt,
      a.ep_discharge_cnt,
      a.cost_report_day_cnt,
      a.remittance_seq_num,
      a.ep_plb_key_num,
      ROUND(a.boa_lockbox_num, 0, 'ROUND_HALF_EVEN') AS boa_lockbox_num,
      a.interchange_receiver_id,
      a.interchange_sender_qualifier_code,
      a.interchange_sender_code,
      a.interchange_receiver_id_qualifier_code,
      a.interchange_receiver_code,
      a.transmission_sending_code,
      a.transmission_receiving_code,
      a.bill_type_code,
      a.payor_default_logging_type_code,
      a.ep_payor_batch_code,
      a.rac_ind,
      a.payor_live_ind,
      a.lab_transaction_breakout_ind,
      a.comment_transaction_ind,
      a.internal_denial_transaction_ind,
      a.discharge_date_replacement_ind,
      a.total_charges_replacement_ind,
      a.patient_type_replacement_ind,
      a.drg_replacement_ind,
      a.apply_secondary_rule_ind,
      a.apply_recover_rule_ind,
      a.apply_mother_baby_rule_ind,
      a.apply_total_charges_rule_ind,
      a.apply_noncovered_charges_rule_ind,
      a.apply_er_patient_rule_ind,
      a.apply_recover_true_up_rule_ind,
      a.apply_non_recover_true_up_rule_ind,
      a.calculated_covered_days_ind,
      a.alternate_sn_format_ind,
      a.plb_recovery_transaction_ind,
      a.duplicate_direct_payer_ind,
      a.not_post_payer_ind,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_pbs_base_views_dataset_name }}.remittance_payment AS a
      INNER JOIN {{ params.param_auth_base_views_dataset_name }}.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
       AND upper(a.coid) = upper(b.co_id)
       AND b.user_id = session_user()
  ;
