-- Translation time: 2023-09-22T18:46:04.447603Z
-- Translation job ID: ba460d1f-d301-46b6-9c47-810d266c2894
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwpbs_views/remittance_claim.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE OR REPLACE VIEW {{ params.param_pbs_views_dataset_name }}.remittance_claim
   OPTIONS(description='This table contains claim level information associated with the payment.')
  AS SELECT
      a.claim_guid,
      a.payment_guid,
      ROUND(a.patient_dw_id, 0, 'ROUND_HALF_EVEN') AS patient_dw_id,
      a.audit_date,
      a.coid,
      a.delete_ind,
      a.delete_date,
      a.unit_num,
      a.company_code,
      a.ssc_coid,
      a.payor_patient_id,
      ROUND(a.pat_acct_num, 0, 'ROUND_HALF_EVEN') AS pat_acct_num,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.patient_last_name
      END AS patient_last_name,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.patient_first_name
      END AS patient_first_name,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.patient_middle_initial
      END AS patient_middle_initial,
      a.mpi_ind,
      a.iplan_id,
      a.ep_calc_iplan_id,
      a.iplan_insurance_order_num,
      a.medical_record_num,
      a.payer_claim_control_number,
      a.stmt_cover_from_date,
      a.stmt_cover_to_date,
      a.received_date,
      a.mpi_corrected_discharge_date,
      a.patient_type_code_pos1,
      a.financial_class_code,
      ROUND(a.total_charge_amt, 3, 'ROUND_HALF_EVEN') AS total_charge_amt,
      ROUND(a.mpi_calc_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_charge_amt,
      ROUND(a.payment_amt, 3, 'ROUND_HALF_EVEN') AS payment_amt,
      ROUND(a.ep_calc_denial_amount, 3, 'ROUND_HALF_EVEN') AS ep_calc_denial_amount,
      ROUND(a.ep_calc_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_contractual_adj_amt,
      ROUND(a.mpi_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS mpi_contractual_adj_amt,
      ROUND(a.corrected_contractual_adj_amt, 3, 'ROUND_HALF_EVEN') AS corrected_contractual_adj_amt,
      ROUND(a.net_benefit_amt, 3, 'ROUND_HALF_EVEN') AS net_benefit_amt,
      ROUND(a.covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS covered_charge_amt,
      ROUND(a.mpi_calc_payor_previous_payment_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_payor_previous_payment_amt,
      ROUND(a.ep_calc_noncovered_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_noncovered_charge_amt,
      ROUND(a.mpi_calc_non_covered_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_non_covered_charge_amt,
      ROUND(a.ep_calc_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_deductible_amt,
      ROUND(a.mpi_calc_deductible_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_deductible_amt,
      ROUND(a.ep_calc_blood_deductible_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_blood_deductible_amt,
      ROUND(a.ep_calc_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_coinsurance_amt,
      ROUND(a.mpi_calc_coinsurance_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_coinsurance_amt,
      ROUND(a.ep_calc_primary_payor_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_primary_payor_payment_amt,
      ROUND(a.patient_liability_amount, 3, 'ROUND_HALF_EVEN') AS patient_liability_amount,
      ROUND(a.capital_amt, 3, 'ROUND_HALF_EVEN') AS capital_amt,
      ROUND(a.ep_calc_discount_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_discount_amt,
      ROUND(a.disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS disproportionate_share_amt,
      ROUND(a.drg_disproportionate_share_amt, 3, 'ROUND_HALF_EVEN') AS drg_disproportionate_share_amt,
      ROUND(a.drg_amt, 3, 'ROUND_HALF_EVEN') AS drg_amt,
      a.drg_code,
      a.mpi_calc_drg_code,
      a.mpi_calc_drg_grouper_code,
      ROUND(a.federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS federal_specific_drg_amt,
      ROUND(a.hospital_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS hospital_specific_drg_amt,
      ROUND(a.drg_weight_amt, 5, 'ROUND_HALF_EVEN') AS drg_weight_amt,
      ROUND(a.hcpcs_charge_amt, 3, 'ROUND_HALF_EVEN') AS hcpcs_charge_amt,
      ROUND(a.hcpcs_payment_amt, 3, 'ROUND_HALF_EVEN') AS hcpcs_payment_amt,
      ROUND(a.indirect_medical_education_amt, 3, 'ROUND_HALF_EVEN') AS indirect_medical_education_amt,
      ROUND(a.indirect_teaching_amt, 3, 'ROUND_HALF_EVEN') AS indirect_teaching_amt,
      ROUND(a.interest_amt, 3, 'ROUND_HALF_EVEN') AS interest_amt,
      ROUND(a.ep_calc_lab_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_lab_charge_amt,
      ROUND(a.ep_calc_lab_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_lab_payment_amt,
      ROUND(a.pps_opr_federal_specific_drg_amt, 3, 'ROUND_HALF_EVEN') AS pps_opr_federal_specific_drg_amt,
      ROUND(a.mpi_calc_non_billed_charge_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_non_billed_charge_amt,
      ROUND(a.mpi_calc_net_benefit_amt, 3, 'ROUND_HALF_EVEN') AS mpi_calc_net_benefit_amt,
      ROUND(a.ep_calc_non_payable_professional_fee_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_non_payable_professional_fee_amt,
      ROUND(a.old_capital_amt, 3, 'ROUND_HALF_EVEN') AS old_capital_amt,
      ROUND(a.operating_outlier_amt, 3, 'ROUND_HALF_EVEN') AS operating_outlier_amt,
      ROUND(a.outlier_amt, 3, 'ROUND_HALF_EVEN') AS outlier_amt,
      ROUND(a.outpatient_reimibursement_rate_amt, 3, 'ROUND_HALF_EVEN') AS outpatient_reimibursement_rate_amt,
      ROUND(a.ep_calc_therapy_charge_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_therapy_charge_amt,
      ROUND(a.ep_calc_therapy_payment_amt, 3, 'ROUND_HALF_EVEN') AS ep_calc_therapy_payment_amt,
      ROUND(a.pps_capital_outlier_amt, 3, 'ROUND_HALF_EVEN') AS pps_capital_outlier_amt,
      ROUND(a.ins_covered_day_cnt, 2, 'ROUND_HALF_EVEN') AS ins_covered_day_cnt,
      a.ep_calc_covered_day_cnt,
      a.noncovered_day_cnt,
      a.cost_report_day_cnt,
      ROUND(a.discharge_fraction_pct, 4, 'ROUND_HALF_EVEN') AS discharge_fraction_pct,
      a.lifetime_psychiatric_day_cnt,
      a.contractual_adj_amt_procedure_code,
      a.payment_amt_procedure_code,
      a.logging_flag,
      a.logging_type_code,
      a.mpi_calc_interim_bill_ind,
      a.claim_status_code,
      a.ep_calc_status_code,
      a.ep_calc_denial_code_ind,
      a.mpi_calc_denial_code_ind,
      a.type_of_claim_code,
      a.type_of_bill_code,
      a.ep_calc_balanced_ind,
      a.discount_applied_ind,
      a.ep_calc_plb_opay_rcvy_trx_ind,
      a.ep_calc_internal_denial_code,
      a.concuity_acct_ind,
      a.mia_switch_ind,
      a.moa_switch_ind,
      ROUND(a.mia_pps_capital_exception_amt, 3, 'ROUND_HALF_EVEN') AS mia_pps_capital_exception_amt,
      a.casemix_ind,
      a.zero_default_iplan_ind,
      a.trx_tracking_not_released_ind,
      a.qmb_switch_ind,
      a.ep_calc_denial_code_1,
      a.ep_calc_denial_code_2,
      a.ep_calc_denial_code_3,
      a.ep_calc_denial_code_4,
      a.ep_calc_denial_code_5,
      a.ep_calc_denial_code_6,
      a.ep_calc_denial_code_7,
      a.ep_calc_denial_code_8,
      a.ep_calc_denial_code_9,
      a.ep_calc_denial_code_10,
      a.ep_calc_handling_ind,
      a.crossover_payor_name,
      a.ep_calc_payor_category_code,
      a.secondary_payor_flag,
      a.ep_calc_prim_itnl_pyr_code,
      a.ep_calc_secn_itnl_pyr_code,
      a.ep_calc_tert_itnl_pyr_code,
      a.corrected_priority_payor_sid,
      a.cob_carrier_sid,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.corrected_subscriber_last_name
      END AS corrected_subscriber_last_name,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.corrected_subscriber_first_name
      END AS corrected_subscriber_first_name,
      CASE
        WHEN session_user() = pn.userid THEN '***'
        ELSE a.corrected_subscriber_middle_name
      END AS corrected_subscriber_middle_name,
      a.corrected_subscriber_health_ins_num,
      a.remittance_subscriber_sid,
      a.remittance_oth_subscriber_sid,
      a.remittance_rendering_provider_sid,
      a.supplemental_amt_qlfr_code_1,
      ROUND(a.supplemental_amt_1, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_1,
      a.supplemental_amt_qlfr_code_2,
      ROUND(a.supplemental_amt_2, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_2,
      a.supplemental_amt_qlfr_code_3,
      ROUND(a.supplemental_amt_3, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_3,
      a.supplemental_amt_qlfr_code_4,
      ROUND(a.supplemental_amt_4, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_4,
      a.supplemental_amt_qlfr_code_5,
      ROUND(a.supplemental_amt_5, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_5,
      a.supplemental_amt_qlfr_code_6,
      ROUND(a.supplemental_amt_6, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_6,
      a.supplemental_amt_qlfr_code_7,
      ROUND(a.supplemental_amt_7, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_7,
      a.supplemental_amt_qlfr_code_8,
      ROUND(a.supplemental_amt_8, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_8,
      a.supplemental_amt_qlfr_code_9,
      ROUND(a.supplemental_amt_9, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_9,
      a.supplemental_amt_qlfr_code_10,
      ROUND(a.supplemental_amt_10, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_10,
      a.supplemental_amt_qlfr_code_11,
      ROUND(a.supplemental_amt_11, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_11,
      a.supplemental_amt_qlfr_code_12,
      ROUND(a.supplemental_amt_12, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_12,
      a.supplemental_amt_qlfr_code_13,
      ROUND(a.supplemental_amt_13, 3, 'ROUND_HALF_EVEN') AS supplemental_amt_13,
      a.supplemental_qty_qlfr_code_1,
      ROUND(a.supplemental_qty_1, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_1,
      a.supplemental_qty_qlfr_code_2,
      ROUND(a.supplemental_qty_2, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_2,
      a.supplemental_qty_qlfr_code_3,
      ROUND(a.supplemental_qty_3, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_3,
      a.supplemental_qty_qlfr_code_4,
      ROUND(a.supplemental_qty_4, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_4,
      a.supplemental_qty_qlfr_code_5,
      ROUND(a.supplemental_qty_5, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_5,
      a.supplemental_qty_qlfr_code_6,
      ROUND(a.supplemental_qty_6, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_6,
      a.supplemental_qty_qlfr_code_7,
      ROUND(a.supplemental_qty_7, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_7,
      a.supplemental_qty_qlfr_code_8,
      ROUND(a.supplemental_qty_8, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_8,
      a.supplemental_qty_qlfr_code_9,
      ROUND(a.supplemental_qty_9, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_9,
      a.supplemental_qty_qlfr_code_10,
      ROUND(a.supplemental_qty_10, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_10,
      a.supplemental_qty_qlfr_code_11,
      ROUND(a.supplemental_qty_11, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_11,
      a.supplemental_qty_qlfr_code_12,
      ROUND(a.supplemental_qty_12, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_12,
      a.supplemental_qty_qlfr_code_13,
      ROUND(a.supplemental_qty_13, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_13,
      a.supplemental_qty_qlfr_code_14,
      ROUND(a.supplemental_qty_14, 0, 'ROUND_HALF_EVEN') AS supplemental_qty_14,
      a.rarc_code_1,
      a.rarc_code_2,
      a.rarc_code_3,
      a.rarc_code_4,
      a.rarc_code_5,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_pbs_base_views_dataset_name }}.remittance_claim AS a
      INNER JOIN {{ params.param_auth_base_views_dataset_name }}.secref_facility AS b ON upper(a.company_code) = upper(b.company_code)
       AND upper(a.coid) = upper(b.co_id)
       AND b.user_id = session_user()
      LEFT OUTER JOIN (
        SELECT
            security_mask_and_exception.userid,
            security_mask_and_exception.masked_column_code
          FROM
            {{ params.param_sec_base_views_dataset_name }}.security_mask_and_exception
          WHERE security_mask_and_exception.userid = session_user()
           AND upper(security_mask_and_exception.masked_column_code) = 'PN'
      ) AS pn ON pn.userid = session_user()
  ;
