
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.ECW_RprtMorStats AS target
USING {{ params.param_psc_stage_dataset_name }}.ECW_RprtMorStats AS source
ON target.SnapShotDate = source.SnapShotDate AND target.MorStatsKey = source.MorStatsKey
WHEN MATCHED THEN
  UPDATE SET
  target.SnapShotDate = source.SnapShotDate,
 target.MonthId = source.MonthId,
 target.MorStatsKey = source.MorStatsKey,
 target.id = source.id,
 target.MORCOID = TRIM(source.MORCOID),
 target.COIDNameOnly = TRIM(source.COIDNameOnly),
 target.COIDName = TRIM(source.COIDName),
 target.coidlob = TRIM(source.coidlob),
 target.coidSublob = TRIM(source.coidSublob),
 target.lobname = TRIM(source.lobname),
 target.MarketName = TRIM(source.MarketName),
 target.MarketKey = source.MarketKey,
 target.DivisionName = TRIM(source.DivisionName),
 target.DivisionKey = source.DivisionKey,
 target.GroupName = TRIM(source.GroupName),
 target.GroupKey = source.GroupKey,
 target.coidspecialty = TRIM(source.coidspecialty),
 target.centerdescription = TRIM(source.centerdescription),
 target.centerkey = source.centerkey,
 target.GLDepartmentNumber = TRIM(source.GLDepartmentNumber),
 target.SnapshotYearMonth = TRIM(source.SnapshotYearMonth),
 target.SecurityCOID = TRIM(source.SecurityCOID),
 target.COID = TRIM(source.COID),
 target.CoidLargePractice = TRIM(source.CoidLargePractice),
 target.CoidProgramType = TRIM(source.CoidProgramType),
 target.AppSpecialtyCategory = TRIM(source.AppSpecialtyCategory),
 target.ProviderOriginalStartStatus = TRIM(source.ProviderOriginalStartStatus),
 target.ProviderOriginalStartDate = TRIM(source.ProviderOriginalStartDate),
 target.COIDStartDateKey = TRIM(source.COIDStartDateKey),
 target.COIDTermDateKey = TRIM(source.COIDTermDateKey),
 target.HospitalCOID = TRIM(source.HospitalCOID),
 target.HospitalName = TRIM(source.HospitalName),
 target.ProviderName = TRIM(source.ProviderName),
 target.ProviderNPI = TRIM(source.ProviderNPI),
 target.SpecialtyCode = TRIM(source.SpecialtyCode),
 target.SpecialtyName = TRIM(source.SpecialtyName),
 target.SpecialtyType = TRIM(source.SpecialtyType),
 target.ProviderStartDateKey = TRIM(source.ProviderStartDateKey),
 target.ProviderTermDateKey = TRIM(source.ProviderTermDateKey),
 target.SpecialtyCategory = TRIM(source.SpecialtyCategory),
 target.cur_StatBusinessDayCnt2 = source.cur_StatBusinessDayCnt2,
 target.cur_StatBankDayCnt2 = source.cur_StatBankDayCnt2,
 target.cur_StatCalendarDayCnt3Mo = source.cur_StatCalendarDayCnt3Mo,
 target.cur_StatCalendarDayCnt2Mo = source.cur_StatCalendarDayCnt2Mo,
 target.cur_ytd_StatBusinessDayCnt2 = source.cur_ytd_StatBusinessDayCnt2,
 target.cur_ytd_StatBankDayCnt2 = source.cur_ytd_StatBankDayCnt2,
 target.cur_ytd_StatCalendarDayCnt3Mo = source.cur_ytd_StatCalendarDayCnt3Mo,
 target.cur_ytd_StatCalendarDayCnt2Mo = source.cur_ytd_StatCalendarDayCnt2Mo,
 target.cur_StatProviderFTECnt = source.cur_StatProviderFTECnt,
 target.cur_ytd_StatProviderFTECnt = source.cur_ytd_StatProviderFTECnt,
 target.cur_StatProviderHeadCnt = source.cur_StatProviderHeadCnt,
 target.cur_ytd_StatProviderHeadCnt = source.cur_ytd_StatProviderHeadCnt,
 target.cur_StatRVUCnt = source.cur_StatRVUCnt,
 target.cur_ytd_StatRVUCnt = source.cur_ytd_StatRVUCnt,
 target.cur_StatWRVUCnt = source.cur_StatWRVUCnt,
 target.cur_ytd_StatWRVUCnt = source.cur_ytd_StatWRVUCnt,
 target.cur_StatRegistrationCnt = source.cur_StatRegistrationCnt,
 target.cur_ytd_StatRegistrationCnt = source.cur_ytd_StatRegistrationCnt,
 target.cur_StatVisitsCnt = source.cur_StatVisitsCnt,
 target.cur_ytd_StatVisitsCnt = source.cur_ytd_StatVisitsCnt,
 target.cur_StatOfficeVisitCnt = source.cur_StatOfficeVisitCnt,
 target.cur_ytd_StatOfficeVisitCnt = source.cur_ytd_StatOfficeVisitCnt,
 target.cur_StatNonOfficeVisitCnt = source.cur_StatNonOfficeVisitCnt,
 target.cur_ytd_StatNonOfficeVisitCnt = source.cur_ytd_StatNonOfficeVisitCnt,
 target.cur_StatGrossPatientRevenueAmt = source.cur_StatGrossPatientRevenueAmt,
 target.cur_ytd_StatGrossPatientRevenueAmt = source.cur_ytd_StatGrossPatientRevenueAmt,
 target.cur_StatAvgDailyPatientRevenueAmt = source.cur_StatAvgDailyPatientRevenueAmt,
 target.cur_ytd_StatAvgDailyPatientRevenueAmt = source.cur_ytd_StatAvgDailyPatientRevenueAmt,
 target.cur_StatPatientCashNetRevenueAmt = source.cur_StatPatientCashNetRevenueAmt,
 target.cur_ytd_StatPatientCashNetRevenueAmt = source.cur_ytd_StatPatientCashNetRevenueAmt,
 target.cur_StatOtherRevenueAmt = source.cur_StatOtherRevenueAmt,
 target.cur_ytd_StatOtherRevenueAmt = source.cur_ytd_StatOtherRevenueAmt,
 target.cur_StatNetRevenueAmt = source.cur_StatNetRevenueAmt,
 target.cur_ytd_StatNetRevenueAmt = source.cur_ytd_StatNetRevenueAmt,
 target.cur_StatRevenueDeductionAmt = source.cur_StatRevenueDeductionAmt,
 target.cur_ytd_StatRevenueDeductionAmt = source.cur_ytd_StatRevenueDeductionAmt,
 target.cur_StatUncompensatedCareAmt = source.cur_StatUncompensatedCareAmt,
 target.cur_ytd_StatUncompensatedCareAmt = source.cur_ytd_StatUncompensatedCareAmt,
 target.cur_StatChargesAmt = source.cur_StatChargesAmt,
 target.cur_ytd_StatChargesAmt = source.cur_ytd_StatChargesAmt,
 target.cur_StatMedicareChargesAmt = source.cur_StatMedicareChargesAmt,
 target.cur_ytd_StatMedicareChargesAmt = source.cur_ytd_StatMedicareChargesAmt,
 target.cur_StatManagedMedicareChargesAmt = source.cur_StatManagedMedicareChargesAmt,
 target.cur_ytd_StatManagedMedicareChargesAmt = source.cur_ytd_StatManagedMedicareChargesAmt,
 target.cur_StatMedicaidChargesAmt = source.cur_StatMedicaidChargesAmt,
 target.cur_ytd_StatMedicaidChargesAmt = source.cur_ytd_StatMedicaidChargesAmt,
 target.cur_StatManagedMedicaidChargesAmt = source.cur_StatManagedMedicaidChargesAmt,
 target.cur_ytd_StatManagedMedicaidChargesAmt = source.cur_ytd_StatManagedMedicaidChargesAmt,
 target.cur_StatCommercialChargesAmt = source.cur_StatCommercialChargesAmt,
 target.cur_ytd_StatCommercialChargesAmt = source.cur_ytd_StatCommercialChargesAmt,
 target.cur_StatHealthcareExchangeChargesAmt = source.cur_StatHealthcareExchangeChargesAmt,
 target.cur_ytd_StatHealthcareExchangeChargesAmt = source.cur_ytd_StatHealthcareExchangeChargesAmt,
 target.cur_StatSelfpayChargesAmt = source.cur_StatSelfpayChargesAmt,
 target.cur_ytd_StatSelfpayChargesAmt = source.cur_ytd_StatSelfpayChargesAmt,
 target.cur_StatOtherChargesAmt = source.cur_StatOtherChargesAmt,
 target.cur_ytd_StatOtherChargesAmt = source.cur_ytd_StatOtherChargesAmt,
 target.cur_StatNetARAmt = source.cur_StatNetARAmt,
 target.cur_ytd_StatNetARAmt = source.cur_ytd_StatNetARAmt,
 target.cur_StatInsuranceBalanceAmt = source.cur_StatInsuranceBalanceAmt,
 target.cur_ytd_StatInsuranceBalanceAmt = source.cur_ytd_StatInsuranceBalanceAmt,
 target.cur_StatPatientBalanceAmt = source.cur_StatPatientBalanceAmt,
 target.cur_ytd_StatPatientBalanceAmt = source.cur_ytd_StatPatientBalanceAmt,
 target.cur_StatBalanceAmt = source.cur_StatBalanceAmt,
 target.cur_ytd_StatBalanceAmt = source.cur_ytd_StatBalanceAmt,
 target.cur_StatInsuranceCOHPEAmt = source.cur_StatInsuranceCOHPEAmt,
 target.cur_ytd_StatInsuranceCOHPEAmt = source.cur_ytd_StatInsuranceCOHPEAmt,
 target.cur_StatInsuranceCOHOtherAmt = source.cur_StatInsuranceCOHOtherAmt,
 target.cur_ytd_StatInsuranceCOHOtherAmt = source.cur_ytd_StatInsuranceCOHOtherAmt,
 target.cur_StatInsuranceUnbilledECWAmt = source.cur_StatInsuranceUnbilledECWAmt,
 target.cur_ytd_StatInsuranceUnbilledECWAmt = source.cur_ytd_StatInsuranceUnbilledECWAmt,
 target.cur_StatInsuranceUnbilledRHAmt = source.cur_StatInsuranceUnbilledRHAmt,
 target.cur_ytd_StatInsuranceUnbilledRHAmt = source.cur_ytd_StatInsuranceUnbilledRHAmt,
 target.cur_StatInsuranceUnbilledAmt = source.cur_StatInsuranceUnbilledAmt,
 target.cur_ytd_StatInsuranceUnbilledAmt = source.cur_ytd_StatInsuranceUnbilledAmt,
 target.cur_StatInsuranceUnbilledBalanceGT120Amt = source.cur_StatInsuranceUnbilledBalanceGT120Amt,
 target.cur_ytd_StatInsuranceUnbilledBalanceGT120Amt = source.cur_ytd_StatInsuranceUnbilledBalanceGT120Amt,
 target.cur_StatInsuranceUnbilledBalanceGT360Amt = source.cur_StatInsuranceUnbilledBalanceGT360Amt,
 target.cur_ytd_StatInsuranceUnbilledBalanceGT360Amt = source.cur_ytd_StatInsuranceUnbilledBalanceGT360Amt,
 target.cur_StatInsuranceBilledAmt = source.cur_StatInsuranceBilledAmt,
 target.cur_ytd_StatInsuranceBilledAmt = source.cur_ytd_StatInsuranceBilledAmt,
 target.cur_StatInsuranceBilledBalanceGT120Amt = source.cur_StatInsuranceBilledBalanceGT120Amt,
 target.cur_ytd_StatInsuranceBilledBalanceGT120Amt = source.cur_ytd_StatInsuranceBilledBalanceGT120Amt,
 target.cur_StatInsuranceBilledBalanceGT360Amt = source.cur_StatInsuranceBilledBalanceGT360Amt,
 target.cur_ytd_StatInsuranceBilledBalanceGT360Amt = source.cur_ytd_StatInsuranceBilledBalanceGT360Amt,
 target.cur_StatInsuranceBalanceGT120Amt = source.cur_StatInsuranceBalanceGT120Amt,
 target.cur_ytd_StatInsuranceBalanceGT120Amt = source.cur_ytd_StatInsuranceBalanceGT120Amt,
 target.cur_StatInsuranceBalanceGT360Amt = source.cur_StatInsuranceBalanceGT360Amt,
 target.cur_ytd_StatInsuranceBalanceGT360Amt = source.cur_ytd_StatInsuranceBalanceGT360Amt,
 target.cur_StatPatientBalanceGT120Amt = source.cur_StatPatientBalanceGT120Amt,
 target.cur_ytd_StatPatientBalanceGT120Amt = source.cur_ytd_StatPatientBalanceGT120Amt,
 target.cur_StatMedicareBalanceAmt = source.cur_StatMedicareBalanceAmt,
 target.cur_ytd_StatMedicareBalanceAmt = source.cur_ytd_StatMedicareBalanceAmt,
 target.cur_StatManagedMedicareBalanceAmt = source.cur_StatManagedMedicareBalanceAmt,
 target.cur_ytd_StatManagedMedicareBalanceAmt = source.cur_ytd_StatManagedMedicareBalanceAmt,
 target.cur_StatMedicaidBalanceAmt = source.cur_StatMedicaidBalanceAmt,
 target.cur_ytd_StatMedicaidBalanceAmt = source.cur_ytd_StatMedicaidBalanceAmt,
 target.cur_StatManagedMedicaidBalanceAmt = source.cur_StatManagedMedicaidBalanceAmt,
 target.cur_ytd_StatManagedMedicaidBalanceAmt = source.cur_ytd_StatManagedMedicaidBalanceAmt,
 target.cur_StatCommercialBalanceAmt = source.cur_StatCommercialBalanceAmt,
 target.cur_ytd_StatCommercialBalanceAmt = source.cur_ytd_StatCommercialBalanceAmt,
 target.cur_StatOtherBalanceAmt = source.cur_StatOtherBalanceAmt,
 target.cur_ytd_StatOtherBalanceAmt = source.cur_ytd_StatOtherBalanceAmt,
 target.cur_StatSelfpayBalanceAmt = source.cur_StatSelfpayBalanceAmt,
 target.cur_ytd_StatSelfpayBalanceAmt = source.cur_ytd_StatSelfpayBalanceAmt,
 target.cur_StatTrueSelfpayBalanceAmt = source.cur_StatTrueSelfpayBalanceAmt,
 target.cur_ytd_StatTrueSelfpayBalanceAmt = source.cur_ytd_StatTrueSelfpayBalanceAmt,
 target.cur_StatCopayDeductSelfpayBalanceAmt = source.cur_StatCopayDeductSelfpayBalanceAmt,
 target.cur_ytd_StatCopayDeductSelfpayBalanceAmt = source.cur_ytd_StatCopayDeductSelfpayBalanceAmt,
 target.cur_StatTotalARWithIet = source.cur_StatTotalARWithIet,
 target.cur_ytd_StatTotalARWithIet = source.cur_ytd_StatTotalARWithIet,
 target.cur_StatIetDaysToCloseDayCnt = source.cur_StatIetDaysToCloseDayCnt,
 target.cur_ytd_StatIetDaysToCloseDayCnt = source.cur_ytd_StatIetDaysToCloseDayCnt,
 target.cur_StatTotalARNoIet = source.cur_StatTotalARNoIet,
 target.cur_ytd_StatTotalARNoIet = source.cur_ytd_StatTotalARNoIet,
 target.cur_StatPtARWithIet = source.cur_StatPtARWithIet,
 target.cur_ytd_StatPtARWithIet = source.cur_ytd_StatPtARWithIet,
 target.cur_StatPatientCashCollectionsECWAmt = source.cur_StatPatientCashCollectionsECWAmt,
 target.cur_ytd_StatPatientCashCollectionsECWAmt = source.cur_ytd_StatPatientCashCollectionsECWAmt,
 target.cur_StatInsuranceCashCollectionsECWAmt = source.cur_StatInsuranceCashCollectionsECWAmt,
 target.cur_ytd_StatInsuranceCashCollectionsECWAmt = source.cur_ytd_StatInsuranceCashCollectionsECWAmt,
 target.cur_StatCashCollectionsECWAmt = source.cur_StatCashCollectionsECWAmt,
 target.cur_ytd_StatCashCollectionsECWAmt = source.cur_ytd_StatCashCollectionsECWAmt,
 target.cur_StatQMIRSCashCollectionsECWAmt = source.cur_StatQMIRSCashCollectionsECWAmt,
 target.cur_ytd_StatQMIRSCashCollectionsECWAmt = source.cur_ytd_StatQMIRSCashCollectionsECWAmt,
 target.cur_Stat12MOCashCollectionsAmt = source.cur_Stat12MOCashCollectionsAmt,
 target.cur_ytd_Stat12MOCashCollectionsAmt = source.cur_ytd_Stat12MOCashCollectionsAmt,
 target.cur_Stat12MOCashOpportunityAmt = source.cur_Stat12MOCashOpportunityAmt,
 target.cur_ytd_Stat12MOCashOpportunityAmt = source.cur_ytd_Stat12MOCashOpportunityAmt,
 target.cur_StatERACashCollectionsECWAmt = source.cur_StatERACashCollectionsECWAmt,
 target.cur_ytd_StatERACashCollectionsECWAmt = source.cur_ytd_StatERACashCollectionsECWAmt,
 target.cur_StatUpfrontCashCollectionsECWAmt = source.cur_StatUpfrontCashCollectionsECWAmt,
 target.cur_ytd_StatUpfrontCashCollectionsECWAmt = source.cur_ytd_StatUpfrontCashCollectionsECWAmt,
 target.cur_StatInitialDenialsECWAmt = source.cur_StatInitialDenialsECWAmt,
 target.cur_ytd_StatInitialDenialsECWAmt = source.cur_ytd_StatInitialDenialsECWAmt,
 target.cur_StatInitialDenialsBillableECWAmt = source.cur_StatInitialDenialsBillableECWAmt,
 target.cur_ytd_StatInitialDenialsBillableECWAmt = source.cur_ytd_StatInitialDenialsBillableECWAmt,
 target.cur_StatInitialDenialsNonBillableECWAmt = source.cur_StatInitialDenialsNonBillableECWAmt,
 target.cur_ytd_StatInitialDenialsNonBillableECWAmt = source.cur_ytd_StatInitialDenialsNonBillableECWAmt,
 target.cur_StatDenialWriteoffECWAmt = source.cur_StatDenialWriteoffECWAmt,
 target.cur_ytd_StatDenialWriteoffECWAmt = source.cur_ytd_StatDenialWriteoffECWAmt,
 target.cur_StatDenialWriteoffBillableECWAmt = source.cur_StatDenialWriteoffBillableECWAmt,
 target.cur_ytd_StatDenialWriteoffBillableECWAmt = source.cur_ytd_StatDenialWriteoffBillableECWAmt,
 target.cur_StatDenialWriteoffNonBillableECWAmt = source.cur_StatDenialWriteoffNonBillableECWAmt,
 target.cur_ytd_StatDenialWriteoffNonBillableECWAmt = source.cur_ytd_StatDenialWriteoffNonBillableECWAmt,
 target.cur_StatPEWriteoffAmt = source.cur_StatPEWriteoffAmt,
 target.cur_ytd_StatPEWriteoffAmt = source.cur_ytd_StatPEWriteoffAmt,
 target.cur_StatPEAccrualChangeAmt = source.cur_StatPEAccrualChangeAmt,
 target.cur_ytd_StatPEAccrualChangeAmt = source.cur_ytd_StatPEAccrualChangeAmt,
 target.cur_StatNetFinancialStatementImpactGrossAmt = source.cur_StatNetFinancialStatementImpactGrossAmt,
 target.cur_ytd_StatNetFinancialStatementImpactGrossAmt = source.cur_ytd_StatNetFinancialStatementImpactGrossAmt,
 target.cur_StatCashCollectionsAmt = source.cur_StatCashCollectionsAmt,
 target.cur_ytd_StatCashCollectionsAmt = source.cur_ytd_StatCashCollectionsAmt,
 target.cur_StatPtARNoIetAmt = source.cur_StatPtARNoIetAmt,
 target.cur_ytd_StatPtARNoIetAmt = source.cur_ytd_StatPtARNoIetAmt,
 target.cur_StatInsARWithIetAmt = source.cur_StatInsARWithIetAmt,
 target.cur_ytd_StatInsARWithIetAmt = source.cur_ytd_StatInsARWithIetAmt,
 target.cur_StatInsARNoIetAmt = source.cur_StatInsARNoIetAmt,
 target.cur_ytd_StatInsARNoIetAmt = source.cur_ytd_StatInsARNoIetAmt,
 target.cur_StatPcnr2MoPriorAmt = source.cur_StatPcnr2MoPriorAmt,
 target.cur_ytd_StatPcnr2MoPriorAmt = source.cur_ytd_StatPcnr2MoPriorAmt,
 target.cur_StatPcnr2MoPrior12MoAmt = source.cur_StatPcnr2MoPrior12MoAmt,
 target.cur_ytd_StatPcnr2MoPrior12MoAmt = source.cur_ytd_StatPcnr2MoPrior12MoAmt,
 target.cur_StatOfficePosChargesAmt = source.cur_StatOfficePosChargesAmt,
 target.cur_ytd_StatOfficePosChargesAmt = source.cur_ytd_StatOfficePosChargesAmt,
 target.cur_StatNonOfficePosChargesAmt = source.cur_StatNonOfficePosChargesAmt,
 target.cur_ytd_StatNonOfficePosChargesAmt = source.cur_ytd_StatNonOfficePosChargesAmt,
 target.cur_StatResolutionAR60Amt = source.cur_StatResolutionAR60Amt,
 target.cur_ytd_StatResolutionAR60Amt = source.cur_ytd_StatResolutionAR60Amt,
 target.cur_StatResolutionAR360Amt = source.cur_StatResolutionAR360Amt,
 target.cur_ytd_StatResolutionAR360Amt = source.cur_ytd_StatResolutionAR360Amt,
 target.cur_StatGrossCharges60Amt = source.cur_StatGrossCharges60Amt,
 target.cur_ytd_StatGrossCharges60Amt = source.cur_ytd_StatGrossCharges60Amt,
 target.cur_StatGrossCharges360Amt = source.cur_StatGrossCharges360Amt,
 target.cur_ytd_StatGrossCharges360Amt = source.cur_ytd_StatGrossCharges360Amt,
 target.cur_StatUpfrontCashOfficeAmt = source.cur_StatUpfrontCashOfficeAmt,
 target.cur_ytd_StatUpfrontCashOfficeAmt = source.cur_ytd_StatUpfrontCashOfficeAmt,
 target.cur_StatUpfrontCashNonOfficeAmt = source.cur_StatUpfrontCashNonOfficeAmt,
 target.cur_ytd_StatUpfrontCashNonOfficeAmt = source.cur_ytd_StatUpfrontCashNonOfficeAmt,
 target.cur_StatCalendarDayCnt = source.cur_StatCalendarDayCnt,
 target.cur_ytd_StatCalendarDayCnt = source.cur_ytd_StatCalendarDayCnt,
 target.cur_StatIetDaysToCloseIetCnt = source.cur_StatIetDaysToCloseIetCnt,
 target.cur_ytd_StatIetDaysToCloseIetCnt = source.cur_ytd_StatIetDaysToCloseIetCnt,
 target.cur_StatRefundAmt = source.cur_StatRefundAmt,
 target.cur_ytd_StatRefundAmt = source.cur_ytd_StatRefundAmt,
 target.cur_StatHealthcareExchangeBalanceAmt = source.cur_StatHealthcareExchangeBalanceAmt,
 target.cur_ytd_StatHealthcareExchangeBalanceAmt = source.cur_ytd_StatHealthcareExchangeBalanceAmt,
 target.cur_StatBudgetUncompCareAmt = source.cur_StatBudgetUncompCareAmt,
 target.cur_ytd_StatBudgetUncompCareAmt = source.cur_ytd_StatBudgetUncompCareAmt,
 target.cur_StatBudgetGrossPtRevAmt = source.cur_StatBudgetGrossPtRevAmt,
 target.cur_ytd_StatBudgetGrossPtRevAmt = source.cur_ytd_StatBudgetGrossPtRevAmt,
 target.cur_StatPEAtRiskAmt = source.cur_StatPEAtRiskAmt,
 target.cur_ytd_StatPEAtRiskAmt = source.cur_ytd_StatPEAtRiskAmt,
 target.cur_StatGrossPatientRevenueAmt3Mo = source.cur_StatGrossPatientRevenueAmt3Mo,
 target.cur_ytd_StatGrossPatientRevenueAmt3Mo = source.cur_ytd_StatGrossPatientRevenueAmt3Mo,
 target.cur_StatPatientCashNetRevenueAmt3Mo = source.cur_StatPatientCashNetRevenueAmt3Mo,
 target.cur_ytd_StatPatientCashNetRevenueAmt3Mo = source.cur_ytd_StatPatientCashNetRevenueAmt3Mo,
 target.cur_StatPatientCashNetRevenueAmt2Mo = source.cur_StatPatientCashNetRevenueAmt2Mo,
 target.cur_ytd_StatPatientCashNetRevenueAmt2Mo = source.cur_ytd_StatPatientCashNetRevenueAmt2Mo,
 target.cur_StatChargesAmt3Mo = source.cur_StatChargesAmt3Mo,
 target.cur_ytd_StatChargesAmt3Mo = source.cur_ytd_StatChargesAmt3Mo,
 target.InsertedBy = TRIM(source.InsertedBy),
 target.InsertedDTM = source.InsertedDTM,
 target.ModifiedBy = TRIM(source.ModifiedBy),
 target.ModifiedDTM = source.ModifiedDTM,
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (SnapShotDate, MonthId, MorStatsKey, id, MORCOID, COIDNameOnly, COIDName, coidlob, coidSublob, lobname, MarketName, MarketKey, DivisionName, DivisionKey, GroupName, GroupKey, coidspecialty, centerdescription, centerkey, GLDepartmentNumber, SnapshotYearMonth, SecurityCOID, COID, CoidLargePractice, CoidProgramType, AppSpecialtyCategory, ProviderOriginalStartStatus, ProviderOriginalStartDate, COIDStartDateKey, COIDTermDateKey, HospitalCOID, HospitalName, ProviderName, ProviderNPI, SpecialtyCode, SpecialtyName, SpecialtyType, ProviderStartDateKey, ProviderTermDateKey, SpecialtyCategory, cur_StatBusinessDayCnt2, cur_StatBankDayCnt2, cur_StatCalendarDayCnt3Mo, cur_StatCalendarDayCnt2Mo, cur_ytd_StatBusinessDayCnt2, cur_ytd_StatBankDayCnt2, cur_ytd_StatCalendarDayCnt3Mo, cur_ytd_StatCalendarDayCnt2Mo, cur_StatProviderFTECnt, cur_ytd_StatProviderFTECnt, cur_StatProviderHeadCnt, cur_ytd_StatProviderHeadCnt, cur_StatRVUCnt, cur_ytd_StatRVUCnt, cur_StatWRVUCnt, cur_ytd_StatWRVUCnt, cur_StatRegistrationCnt, cur_ytd_StatRegistrationCnt, cur_StatVisitsCnt, cur_ytd_StatVisitsCnt, cur_StatOfficeVisitCnt, cur_ytd_StatOfficeVisitCnt, cur_StatNonOfficeVisitCnt, cur_ytd_StatNonOfficeVisitCnt, cur_StatGrossPatientRevenueAmt, cur_ytd_StatGrossPatientRevenueAmt, cur_StatAvgDailyPatientRevenueAmt, cur_ytd_StatAvgDailyPatientRevenueAmt, cur_StatPatientCashNetRevenueAmt, cur_ytd_StatPatientCashNetRevenueAmt, cur_StatOtherRevenueAmt, cur_ytd_StatOtherRevenueAmt, cur_StatNetRevenueAmt, cur_ytd_StatNetRevenueAmt, cur_StatRevenueDeductionAmt, cur_ytd_StatRevenueDeductionAmt, cur_StatUncompensatedCareAmt, cur_ytd_StatUncompensatedCareAmt, cur_StatChargesAmt, cur_ytd_StatChargesAmt, cur_StatMedicareChargesAmt, cur_ytd_StatMedicareChargesAmt, cur_StatManagedMedicareChargesAmt, cur_ytd_StatManagedMedicareChargesAmt, cur_StatMedicaidChargesAmt, cur_ytd_StatMedicaidChargesAmt, cur_StatManagedMedicaidChargesAmt, cur_ytd_StatManagedMedicaidChargesAmt, cur_StatCommercialChargesAmt, cur_ytd_StatCommercialChargesAmt, cur_StatHealthcareExchangeChargesAmt, cur_ytd_StatHealthcareExchangeChargesAmt, cur_StatSelfpayChargesAmt, cur_ytd_StatSelfpayChargesAmt, cur_StatOtherChargesAmt, cur_ytd_StatOtherChargesAmt, cur_StatNetARAmt, cur_ytd_StatNetARAmt, cur_StatInsuranceBalanceAmt, cur_ytd_StatInsuranceBalanceAmt, cur_StatPatientBalanceAmt, cur_ytd_StatPatientBalanceAmt, cur_StatBalanceAmt, cur_ytd_StatBalanceAmt, cur_StatInsuranceCOHPEAmt, cur_ytd_StatInsuranceCOHPEAmt, cur_StatInsuranceCOHOtherAmt, cur_ytd_StatInsuranceCOHOtherAmt, cur_StatInsuranceUnbilledECWAmt, cur_ytd_StatInsuranceUnbilledECWAmt, cur_StatInsuranceUnbilledRHAmt, cur_ytd_StatInsuranceUnbilledRHAmt, cur_StatInsuranceUnbilledAmt, cur_ytd_StatInsuranceUnbilledAmt, cur_StatInsuranceUnbilledBalanceGT120Amt, cur_ytd_StatInsuranceUnbilledBalanceGT120Amt, cur_StatInsuranceUnbilledBalanceGT360Amt, cur_ytd_StatInsuranceUnbilledBalanceGT360Amt, cur_StatInsuranceBilledAmt, cur_ytd_StatInsuranceBilledAmt, cur_StatInsuranceBilledBalanceGT120Amt, cur_ytd_StatInsuranceBilledBalanceGT120Amt, cur_StatInsuranceBilledBalanceGT360Amt, cur_ytd_StatInsuranceBilledBalanceGT360Amt, cur_StatInsuranceBalanceGT120Amt, cur_ytd_StatInsuranceBalanceGT120Amt, cur_StatInsuranceBalanceGT360Amt, cur_ytd_StatInsuranceBalanceGT360Amt, cur_StatPatientBalanceGT120Amt, cur_ytd_StatPatientBalanceGT120Amt, cur_StatMedicareBalanceAmt, cur_ytd_StatMedicareBalanceAmt, cur_StatManagedMedicareBalanceAmt, cur_ytd_StatManagedMedicareBalanceAmt, cur_StatMedicaidBalanceAmt, cur_ytd_StatMedicaidBalanceAmt, cur_StatManagedMedicaidBalanceAmt, cur_ytd_StatManagedMedicaidBalanceAmt, cur_StatCommercialBalanceAmt, cur_ytd_StatCommercialBalanceAmt, cur_StatOtherBalanceAmt, cur_ytd_StatOtherBalanceAmt, cur_StatSelfpayBalanceAmt, cur_ytd_StatSelfpayBalanceAmt, cur_StatTrueSelfpayBalanceAmt, cur_ytd_StatTrueSelfpayBalanceAmt, cur_StatCopayDeductSelfpayBalanceAmt, cur_ytd_StatCopayDeductSelfpayBalanceAmt, cur_StatTotalARWithIet, cur_ytd_StatTotalARWithIet, cur_StatIetDaysToCloseDayCnt, cur_ytd_StatIetDaysToCloseDayCnt, cur_StatTotalARNoIet, cur_ytd_StatTotalARNoIet, cur_StatPtARWithIet, cur_ytd_StatPtARWithIet, cur_StatPatientCashCollectionsECWAmt, cur_ytd_StatPatientCashCollectionsECWAmt, cur_StatInsuranceCashCollectionsECWAmt, cur_ytd_StatInsuranceCashCollectionsECWAmt, cur_StatCashCollectionsECWAmt, cur_ytd_StatCashCollectionsECWAmt, cur_StatQMIRSCashCollectionsECWAmt, cur_ytd_StatQMIRSCashCollectionsECWAmt, cur_Stat12MOCashCollectionsAmt, cur_ytd_Stat12MOCashCollectionsAmt, cur_Stat12MOCashOpportunityAmt, cur_ytd_Stat12MOCashOpportunityAmt, cur_StatERACashCollectionsECWAmt, cur_ytd_StatERACashCollectionsECWAmt, cur_StatUpfrontCashCollectionsECWAmt, cur_ytd_StatUpfrontCashCollectionsECWAmt, cur_StatInitialDenialsECWAmt, cur_ytd_StatInitialDenialsECWAmt, cur_StatInitialDenialsBillableECWAmt, cur_ytd_StatInitialDenialsBillableECWAmt, cur_StatInitialDenialsNonBillableECWAmt, cur_ytd_StatInitialDenialsNonBillableECWAmt, cur_StatDenialWriteoffECWAmt, cur_ytd_StatDenialWriteoffECWAmt, cur_StatDenialWriteoffBillableECWAmt, cur_ytd_StatDenialWriteoffBillableECWAmt, cur_StatDenialWriteoffNonBillableECWAmt, cur_ytd_StatDenialWriteoffNonBillableECWAmt, cur_StatPEWriteoffAmt, cur_ytd_StatPEWriteoffAmt, cur_StatPEAccrualChangeAmt, cur_ytd_StatPEAccrualChangeAmt, cur_StatNetFinancialStatementImpactGrossAmt, cur_ytd_StatNetFinancialStatementImpactGrossAmt, cur_StatCashCollectionsAmt, cur_ytd_StatCashCollectionsAmt, cur_StatPtARNoIetAmt, cur_ytd_StatPtARNoIetAmt, cur_StatInsARWithIetAmt, cur_ytd_StatInsARWithIetAmt, cur_StatInsARNoIetAmt, cur_ytd_StatInsARNoIetAmt, cur_StatPcnr2MoPriorAmt, cur_ytd_StatPcnr2MoPriorAmt, cur_StatPcnr2MoPrior12MoAmt, cur_ytd_StatPcnr2MoPrior12MoAmt, cur_StatOfficePosChargesAmt, cur_ytd_StatOfficePosChargesAmt, cur_StatNonOfficePosChargesAmt, cur_ytd_StatNonOfficePosChargesAmt, cur_StatResolutionAR60Amt, cur_ytd_StatResolutionAR60Amt, cur_StatResolutionAR360Amt, cur_ytd_StatResolutionAR360Amt, cur_StatGrossCharges60Amt, cur_ytd_StatGrossCharges60Amt, cur_StatGrossCharges360Amt, cur_ytd_StatGrossCharges360Amt, cur_StatUpfrontCashOfficeAmt, cur_ytd_StatUpfrontCashOfficeAmt, cur_StatUpfrontCashNonOfficeAmt, cur_ytd_StatUpfrontCashNonOfficeAmt, cur_StatCalendarDayCnt, cur_ytd_StatCalendarDayCnt, cur_StatIetDaysToCloseIetCnt, cur_ytd_StatIetDaysToCloseIetCnt, cur_StatRefundAmt, cur_ytd_StatRefundAmt, cur_StatHealthcareExchangeBalanceAmt, cur_ytd_StatHealthcareExchangeBalanceAmt, cur_StatBudgetUncompCareAmt, cur_ytd_StatBudgetUncompCareAmt, cur_StatBudgetGrossPtRevAmt, cur_ytd_StatBudgetGrossPtRevAmt, cur_StatPEAtRiskAmt, cur_ytd_StatPEAtRiskAmt, cur_StatGrossPatientRevenueAmt3Mo, cur_ytd_StatGrossPatientRevenueAmt3Mo, cur_StatPatientCashNetRevenueAmt3Mo, cur_ytd_StatPatientCashNetRevenueAmt3Mo, cur_StatPatientCashNetRevenueAmt2Mo, cur_ytd_StatPatientCashNetRevenueAmt2Mo, cur_StatChargesAmt3Mo, cur_ytd_StatChargesAmt3Mo, InsertedBy, InsertedDTM, ModifiedBy, ModifiedDTM, DWLastUpdateDateTime)
  VALUES (source.SnapShotDate, source.MonthId, source.MorStatsKey, source.id, TRIM(source.MORCOID), TRIM(source.COIDNameOnly), TRIM(source.COIDName), TRIM(source.coidlob), TRIM(source.coidSublob), TRIM(source.lobname), TRIM(source.MarketName), source.MarketKey, TRIM(source.DivisionName), source.DivisionKey, TRIM(source.GroupName), source.GroupKey, TRIM(source.coidspecialty), TRIM(source.centerdescription), source.centerkey, TRIM(source.GLDepartmentNumber), TRIM(source.SnapshotYearMonth), TRIM(source.SecurityCOID), TRIM(source.COID), TRIM(source.CoidLargePractice), TRIM(source.CoidProgramType), TRIM(source.AppSpecialtyCategory), TRIM(source.ProviderOriginalStartStatus), TRIM(source.ProviderOriginalStartDate), TRIM(source.COIDStartDateKey), TRIM(source.COIDTermDateKey), TRIM(source.HospitalCOID), TRIM(source.HospitalName), TRIM(source.ProviderName), TRIM(source.ProviderNPI), TRIM(source.SpecialtyCode), TRIM(source.SpecialtyName), TRIM(source.SpecialtyType), TRIM(source.ProviderStartDateKey), TRIM(source.ProviderTermDateKey), TRIM(source.SpecialtyCategory), source.cur_StatBusinessDayCnt2, source.cur_StatBankDayCnt2, source.cur_StatCalendarDayCnt3Mo, source.cur_StatCalendarDayCnt2Mo, source.cur_ytd_StatBusinessDayCnt2, source.cur_ytd_StatBankDayCnt2, source.cur_ytd_StatCalendarDayCnt3Mo, source.cur_ytd_StatCalendarDayCnt2Mo, source.cur_StatProviderFTECnt, source.cur_ytd_StatProviderFTECnt, source.cur_StatProviderHeadCnt, source.cur_ytd_StatProviderHeadCnt, source.cur_StatRVUCnt, source.cur_ytd_StatRVUCnt, source.cur_StatWRVUCnt, source.cur_ytd_StatWRVUCnt, source.cur_StatRegistrationCnt, source.cur_ytd_StatRegistrationCnt, source.cur_StatVisitsCnt, source.cur_ytd_StatVisitsCnt, source.cur_StatOfficeVisitCnt, source.cur_ytd_StatOfficeVisitCnt, source.cur_StatNonOfficeVisitCnt, source.cur_ytd_StatNonOfficeVisitCnt, source.cur_StatGrossPatientRevenueAmt, source.cur_ytd_StatGrossPatientRevenueAmt, source.cur_StatAvgDailyPatientRevenueAmt, source.cur_ytd_StatAvgDailyPatientRevenueAmt, source.cur_StatPatientCashNetRevenueAmt, source.cur_ytd_StatPatientCashNetRevenueAmt, source.cur_StatOtherRevenueAmt, source.cur_ytd_StatOtherRevenueAmt, source.cur_StatNetRevenueAmt, source.cur_ytd_StatNetRevenueAmt, source.cur_StatRevenueDeductionAmt, source.cur_ytd_StatRevenueDeductionAmt, source.cur_StatUncompensatedCareAmt, source.cur_ytd_StatUncompensatedCareAmt, source.cur_StatChargesAmt, source.cur_ytd_StatChargesAmt, source.cur_StatMedicareChargesAmt, source.cur_ytd_StatMedicareChargesAmt, source.cur_StatManagedMedicareChargesAmt, source.cur_ytd_StatManagedMedicareChargesAmt, source.cur_StatMedicaidChargesAmt, source.cur_ytd_StatMedicaidChargesAmt, source.cur_StatManagedMedicaidChargesAmt, source.cur_ytd_StatManagedMedicaidChargesAmt, source.cur_StatCommercialChargesAmt, source.cur_ytd_StatCommercialChargesAmt, source.cur_StatHealthcareExchangeChargesAmt, source.cur_ytd_StatHealthcareExchangeChargesAmt, source.cur_StatSelfpayChargesAmt, source.cur_ytd_StatSelfpayChargesAmt, source.cur_StatOtherChargesAmt, source.cur_ytd_StatOtherChargesAmt, source.cur_StatNetARAmt, source.cur_ytd_StatNetARAmt, source.cur_StatInsuranceBalanceAmt, source.cur_ytd_StatInsuranceBalanceAmt, source.cur_StatPatientBalanceAmt, source.cur_ytd_StatPatientBalanceAmt, source.cur_StatBalanceAmt, source.cur_ytd_StatBalanceAmt, source.cur_StatInsuranceCOHPEAmt, source.cur_ytd_StatInsuranceCOHPEAmt, source.cur_StatInsuranceCOHOtherAmt, source.cur_ytd_StatInsuranceCOHOtherAmt, source.cur_StatInsuranceUnbilledECWAmt, source.cur_ytd_StatInsuranceUnbilledECWAmt, source.cur_StatInsuranceUnbilledRHAmt, source.cur_ytd_StatInsuranceUnbilledRHAmt, source.cur_StatInsuranceUnbilledAmt, source.cur_ytd_StatInsuranceUnbilledAmt, source.cur_StatInsuranceUnbilledBalanceGT120Amt, source.cur_ytd_StatInsuranceUnbilledBalanceGT120Amt, source.cur_StatInsuranceUnbilledBalanceGT360Amt, source.cur_ytd_StatInsuranceUnbilledBalanceGT360Amt, source.cur_StatInsuranceBilledAmt, source.cur_ytd_StatInsuranceBilledAmt, source.cur_StatInsuranceBilledBalanceGT120Amt, source.cur_ytd_StatInsuranceBilledBalanceGT120Amt, source.cur_StatInsuranceBilledBalanceGT360Amt, source.cur_ytd_StatInsuranceBilledBalanceGT360Amt, source.cur_StatInsuranceBalanceGT120Amt, source.cur_ytd_StatInsuranceBalanceGT120Amt, source.cur_StatInsuranceBalanceGT360Amt, source.cur_ytd_StatInsuranceBalanceGT360Amt, source.cur_StatPatientBalanceGT120Amt, source.cur_ytd_StatPatientBalanceGT120Amt, source.cur_StatMedicareBalanceAmt, source.cur_ytd_StatMedicareBalanceAmt, source.cur_StatManagedMedicareBalanceAmt, source.cur_ytd_StatManagedMedicareBalanceAmt, source.cur_StatMedicaidBalanceAmt, source.cur_ytd_StatMedicaidBalanceAmt, source.cur_StatManagedMedicaidBalanceAmt, source.cur_ytd_StatManagedMedicaidBalanceAmt, source.cur_StatCommercialBalanceAmt, source.cur_ytd_StatCommercialBalanceAmt, source.cur_StatOtherBalanceAmt, source.cur_ytd_StatOtherBalanceAmt, source.cur_StatSelfpayBalanceAmt, source.cur_ytd_StatSelfpayBalanceAmt, source.cur_StatTrueSelfpayBalanceAmt, source.cur_ytd_StatTrueSelfpayBalanceAmt, source.cur_StatCopayDeductSelfpayBalanceAmt, source.cur_ytd_StatCopayDeductSelfpayBalanceAmt, source.cur_StatTotalARWithIet, source.cur_ytd_StatTotalARWithIet, source.cur_StatIetDaysToCloseDayCnt, source.cur_ytd_StatIetDaysToCloseDayCnt, source.cur_StatTotalARNoIet, source.cur_ytd_StatTotalARNoIet, source.cur_StatPtARWithIet, source.cur_ytd_StatPtARWithIet, source.cur_StatPatientCashCollectionsECWAmt, source.cur_ytd_StatPatientCashCollectionsECWAmt, source.cur_StatInsuranceCashCollectionsECWAmt, source.cur_ytd_StatInsuranceCashCollectionsECWAmt, source.cur_StatCashCollectionsECWAmt, source.cur_ytd_StatCashCollectionsECWAmt, source.cur_StatQMIRSCashCollectionsECWAmt, source.cur_ytd_StatQMIRSCashCollectionsECWAmt, source.cur_Stat12MOCashCollectionsAmt, source.cur_ytd_Stat12MOCashCollectionsAmt, source.cur_Stat12MOCashOpportunityAmt, source.cur_ytd_Stat12MOCashOpportunityAmt, source.cur_StatERACashCollectionsECWAmt, source.cur_ytd_StatERACashCollectionsECWAmt, source.cur_StatUpfrontCashCollectionsECWAmt, source.cur_ytd_StatUpfrontCashCollectionsECWAmt, source.cur_StatInitialDenialsECWAmt, source.cur_ytd_StatInitialDenialsECWAmt, source.cur_StatInitialDenialsBillableECWAmt, source.cur_ytd_StatInitialDenialsBillableECWAmt, source.cur_StatInitialDenialsNonBillableECWAmt, source.cur_ytd_StatInitialDenialsNonBillableECWAmt, source.cur_StatDenialWriteoffECWAmt, source.cur_ytd_StatDenialWriteoffECWAmt, source.cur_StatDenialWriteoffBillableECWAmt, source.cur_ytd_StatDenialWriteoffBillableECWAmt, source.cur_StatDenialWriteoffNonBillableECWAmt, source.cur_ytd_StatDenialWriteoffNonBillableECWAmt, source.cur_StatPEWriteoffAmt, source.cur_ytd_StatPEWriteoffAmt, source.cur_StatPEAccrualChangeAmt, source.cur_ytd_StatPEAccrualChangeAmt, source.cur_StatNetFinancialStatementImpactGrossAmt, source.cur_ytd_StatNetFinancialStatementImpactGrossAmt, source.cur_StatCashCollectionsAmt, source.cur_ytd_StatCashCollectionsAmt, source.cur_StatPtARNoIetAmt, source.cur_ytd_StatPtARNoIetAmt, source.cur_StatInsARWithIetAmt, source.cur_ytd_StatInsARWithIetAmt, source.cur_StatInsARNoIetAmt, source.cur_ytd_StatInsARNoIetAmt, source.cur_StatPcnr2MoPriorAmt, source.cur_ytd_StatPcnr2MoPriorAmt, source.cur_StatPcnr2MoPrior12MoAmt, source.cur_ytd_StatPcnr2MoPrior12MoAmt, source.cur_StatOfficePosChargesAmt, source.cur_ytd_StatOfficePosChargesAmt, source.cur_StatNonOfficePosChargesAmt, source.cur_ytd_StatNonOfficePosChargesAmt, source.cur_StatResolutionAR60Amt, source.cur_ytd_StatResolutionAR60Amt, source.cur_StatResolutionAR360Amt, source.cur_ytd_StatResolutionAR360Amt, source.cur_StatGrossCharges60Amt, source.cur_ytd_StatGrossCharges60Amt, source.cur_StatGrossCharges360Amt, source.cur_ytd_StatGrossCharges360Amt, source.cur_StatUpfrontCashOfficeAmt, source.cur_ytd_StatUpfrontCashOfficeAmt, source.cur_StatUpfrontCashNonOfficeAmt, source.cur_ytd_StatUpfrontCashNonOfficeAmt, source.cur_StatCalendarDayCnt, source.cur_ytd_StatCalendarDayCnt, source.cur_StatIetDaysToCloseIetCnt, source.cur_ytd_StatIetDaysToCloseIetCnt, source.cur_StatRefundAmt, source.cur_ytd_StatRefundAmt, source.cur_StatHealthcareExchangeBalanceAmt, source.cur_ytd_StatHealthcareExchangeBalanceAmt, source.cur_StatBudgetUncompCareAmt, source.cur_ytd_StatBudgetUncompCareAmt, source.cur_StatBudgetGrossPtRevAmt, source.cur_ytd_StatBudgetGrossPtRevAmt, source.cur_StatPEAtRiskAmt, source.cur_ytd_StatPEAtRiskAmt, source.cur_StatGrossPatientRevenueAmt3Mo, source.cur_ytd_StatGrossPatientRevenueAmt3Mo, source.cur_StatPatientCashNetRevenueAmt3Mo, source.cur_ytd_StatPatientCashNetRevenueAmt3Mo, source.cur_StatPatientCashNetRevenueAmt2Mo, source.cur_ytd_StatPatientCashNetRevenueAmt2Mo, source.cur_StatChargesAmt3Mo, source.cur_ytd_StatChargesAmt3Mo, TRIM(source.InsertedBy), source.InsertedDTM, TRIM(source.ModifiedBy), source.ModifiedDTM, source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT SnapShotDate, MorStatsKey
      FROM {{ params.param_psc_core_dataset_name }}.ECW_RprtMorStats
      GROUP BY SnapShotDate, MorStatsKey
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.ECW_RprtMorStats');
ELSE
  COMMIT TRANSACTION;
END IF;
