
DECLARE DUP_COUNT INT64;

BEGIN TRANSACTION;

MERGE INTO {{ params.param_psc_core_dataset_name }}.EPIC_FactSnapShotInitialDenials AS target
USING {{ params.param_psc_stage_dataset_name }}.EPIC_FactSnapShotInitialDenials AS source
ON target.SnapShotDate = source.SnapShotDate AND target.ClaimKey = source.ClaimKey
WHEN MATCHED THEN
  UPDATE SET
  target.MonthID = source.MonthID,
 target.SnapShotDate = source.SnapShotDate,
 target.Coid = TRIM(source.Coid),
 target.ClaimNumber = source.ClaimNumber,
 target.ClaimKey = source.ClaimKey,
 target.RegionKey = source.RegionKey,
 target.ServicingProviderKey = source.ServicingProviderKey,
 target.RenderingProviderKey = source.RenderingProviderKey,
 target.PatientKey = source.PatientKey,
 target.PatientInternalID = source.PatientInternalID,
 target.VisitNumber = source.VisitNumber,
 target.ClaimStatusKey = source.ClaimStatusKey,
 target.FacilityKey = source.FacilityKey,
 target.Payer1IplanKey = source.Payer1IplanKey,
 target.ClaimServiceDate = source.ClaimServiceDate,
 target.ClaimServiceDateYear = source.ClaimServiceDateYear,
 target.ClaimServiceDateMonth = source.ClaimServiceDateMonth,
 target.ClaimBalance = source.ClaimBalance,
 target.ClaimCharge = source.ClaimCharge,
 target.VoidFlag = source.VoidFlag,
 target.DeleteFlag = source.DeleteFlag,
 target.ARClaimFlag = source.ARClaimFlag,
 target.FirstInsuranceBillDateKey = source.FirstInsuranceBillDateKey,
 target.LastBillDateKey = source.LastBillDateKey,
 target.NumberOfBills = source.NumberOfBills,
 target.LiabilityDate = source.LiabilityDate,
 target.ClaimDate = source.ClaimDate,
 target.LiabilityOwner = TRIM(source.LiabilityOwner),
 target.RHHoldCode = TRIM(source.RHHoldCode),
 target.ClaimLineChargeKey = source.ClaimLineChargeKey,
 target.CPTCodeKey = source.CPTCodeKey,
 target.CPTCode = TRIM(source.CPTCode),
 target.CPTServiceStartDate = source.CPTServiceStartDate,
 target.CPTServiceEndDate = source.CPTServiceEndDate,
 target.CPTDeleteFlag = source.CPTDeleteFlag,
 target.CPTModifier1 = TRIM(source.CPTModifier1),
 target.CPTModifier2 = TRIM(source.CPTModifier2),
 target.CPTModifier3 = TRIM(source.CPTModifier3),
 target.CPTModifier4 = TRIM(source.CPTModifier4),
 target.LineCharge = source.LineCharge,
 target.LineChargeFinal = source.LineChargeFinal,
 target.LineInsPayment = source.LineInsPayment,
 target.LineInsPaymentFirstDate = source.LineInsPaymentFirstDate,
 target.LineInsPaymentFlag = source.LineInsPaymentFlag,
 target.LinePatPayment = source.LinePatPayment,
 target.LinePatPaymentFlag = source.LinePatPaymentFlag,
 target.LineInsContractual = source.LineInsContractual,
 target.LineInsContractualFirstDate = source.LineInsContractualFirstDate,
 target.LineInsContractualFlag = source.LineInsContractualFlag,
 target.LineAdjustment = source.LineAdjustment,
 target.LineAdjustmentFlag = source.LineAdjustmentFlag,
 target.LineBalance = source.LineBalance,
 target.LineInBalanceFlag = source.LineInBalanceFlag,
 target.LineAdminAdj = source.LineAdminAdj,
 target.LineDenialAdj = source.LineDenialAdj,
 target.LineCharityAdj = source.LineCharityAdj,
 target.LineContractualAdj = source.LineContractualAdj,
 target.LineUninsuredDiscountAdj = source.LineUninsuredDiscountAdj,
 target.LineRefundAdj = source.LineRefundAdj,
 target.LineNSFAdj = source.LineNSFAdj,
 target.LineEscheatAdj = source.LineEscheatAdj,
 target.LineBadDebtAdj = source.LineBadDebtAdj,
 target.LineOtherAdj = source.LineOtherAdj,
 target.VoidDate = source.VoidDate,
 target.PriorClaimKey = source.PriorClaimKey,
 target.VoidFirstBilledClaimKey = source.VoidFirstBilledClaimKey,
 target.VoidFirstBilledClaimNumber = source.VoidFirstBilledClaimNumber,
 target.VoidFirstBilledDateKey = source.VoidFirstBilledDateKey,
 target.OnFirstBilledFlag = source.OnFirstBilledFlag,
 target.OnFirstBilledCharge = source.OnFirstBilledCharge,
 target.VoidFirstBilledClaimLineChargeKey = source.VoidFirstBilledClaimLineChargeKey,
 target.FirstDenialCarcRarcCode = TRIM(source.FirstDenialCarcRarcCode),
 target.FirstDenialERADate = source.FirstDenialERADate,
 target.FirstDenialCARCCodes = TRIM(source.FirstDenialCARCCodes),
 target.FirstDenialRARCCodes = TRIM(source.FirstDenialRARCCodes),
 target.FirstDenialPayerName = TRIM(source.FirstDenialPayerName),
 target.FirstDenialCategory = TRIM(source.FirstDenialCategory),
 target.InitialDeniedCharges = source.InitialDeniedCharges,
 target.FirstDenialFlag = source.FirstDenialFlag,
 target.LineDenialAdjFlag = source.LineDenialAdjFlag,
 target.FirstDenialCarcRarcType = TRIM(source.FirstDenialCarcRarcType),
 target.FirstDenialCARCIsDenial = TRIM(source.FirstDenialCARCIsDenial),
 target.FirstDenialCARCRequiresRarc = TRIM(source.FirstDenialCARCRequiresRarc),
 target.FirstDenialRARCIsDenial = TRIM(source.FirstDenialRARCIsDenial),
 target.LastDenialCarcRarcCode = TRIM(source.LastDenialCarcRarcCode),
 target.LastDenialERADate = source.LastDenialERADate,
 target.LastDenialCARCCodes = TRIM(source.LastDenialCARCCodes),
 target.LastDenialRARCCodes = TRIM(source.LastDenialRARCCodes),
 target.LastDenialPayerName = TRIM(source.LastDenialPayerName),
 target.LastDenialCategory = TRIM(source.LastDenialCategory),
 target.LastDenialCarcRarcType = TRIM(source.LastDenialCarcRarcType),
 target.LastDenialCARCIsDenial = TRIM(source.LastDenialCARCIsDenial),
 target.LastDenialCARCRequiresRarc = TRIM(source.LastDenialCARCRequiresRarc),
 target.LastDenialRARCIsDenial = TRIM(source.LastDenialRARCIsDenial),
 target.FirstERACarcRarcCode = TRIM(source.FirstERACarcRarcCode),
 target.FirstERADate = source.FirstERADate,
 target.FirstERACARCCodes = TRIM(source.FirstERACARCCodes),
 target.FirstERARARCCodes = TRIM(source.FirstERARARCCodes),
 target.FirstERAPayerName = TRIM(source.FirstERAPayerName),
 target.FirstERACategory = TRIM(source.FirstERACategory),
 target.FirstERACarcRarcType = TRIM(source.FirstERACarcRarcType),
 target.FirstERACARCIsDenial = TRIM(source.FirstERACARCIsDenial),
 target.FirstERACARCRequiresRarc = TRIM(source.FirstERACARCRequiresRarc),
 target.FirstERARARCIsDenial = TRIM(source.FirstERARARCIsDenial),
 target.LastERACarcRarcCode = TRIM(source.LastERACarcRarcCode),
 target.LastERADate = source.LastERADate,
 target.LastERACARCCodes = TRIM(source.LastERACARCCodes),
 target.LastERARARCCodes = TRIM(source.LastERARARCCodes),
 target.LastERAPayerName = TRIM(source.LastERAPayerName),
 target.LastERACategory = TRIM(source.LastERACategory),
 target.LastERACarcRarcType = TRIM(source.LastERACarcRarcType),
 target.LastERACARCIsDenial = TRIM(source.LastERACARCIsDenial),
 target.LastERACARCRequiresRarc = TRIM(source.LastERACARCRequiresRarc),
 target.LastERARARCIsDenial = TRIM(source.LastERARARCIsDenial),
 target.ArtivaPool = TRIM(source.ArtivaPool),
 target.ArtivaLiabilityLastReviewed = TRIM(source.ArtivaLiabilityLastReviewed),
 target.ArtivaLiabilityFollowupDate = TRIM(source.ArtivaLiabilityFollowupDate),
 target.LastAdjustmentCode = TRIM(source.LastAdjustmentCode),
 target.LastAdjustmentName = TRIM(source.LastAdjustmentName),
 target.LastAdjustmentCategory = TRIM(source.LastAdjustmentCategory),
 target.LastAdjustmentDate = source.LastAdjustmentDate,
 target.LineAdminAdjLastDate = source.LineAdminAdjLastDate,
 target.LineDenialAdjLastDate = source.LineDenialAdjLastDate,
 target.LineCharityAdjLastDate = source.LineCharityAdjLastDate,
 target.LineContractualAdjLastDate = source.LineContractualAdjLastDate,
 target.LineUninsuredDiscountAdjLastDate = source.LineUninsuredDiscountAdjLastDate,
 target.LineRefundAdjLastDate = source.LineRefundAdjLastDate,
 target.LineNSFAdjLastDate = source.LineNSFAdjLastDate,
 target.LineEscheatAdjLastDate = source.LineEscheatAdjLastDate,
 target.LineBadDebtAdjLastDate = source.LineBadDebtAdjLastDate,
 target.LineOtherAdjLastDate = source.LineOtherAdjLastDate,
 target.IETFlag = TRIM(source.IETFlag),
 target.IETCreateDate = TRIM(source.IETCreateDate),
 target.IETLastModifiedDate = TRIM(source.IETLastModifiedDate),
 target.DenialCount = source.DenialCount,
 target.DenialLastEraDate = source.DenialLastEraDate,
 target.ClaimCPTCode1 = TRIM(source.ClaimCPTCode1),
 target.ClaimCPTCode2 = TRIM(source.ClaimCPTCode2),
 target.ClaimCPTCode3 = TRIM(source.ClaimCPTCode3),
 target.ClaimCPTCode4 = TRIM(source.ClaimCPTCode4),
 target.ClaimCPTCode5 = TRIM(source.ClaimCPTCode5),
 target.GLDeptNumber = TRIM(source.GLDeptNumber),
 target.ProviderSpecialtyName = TRIM(source.ProviderSpecialtyName),
 target.ProviderSpecialtyType = TRIM(source.ProviderSpecialtyType),
 target.ProviderSpecialtyCategory = TRIM(source.ProviderSpecialtyCategory),
 target.InitialIplanKey = source.InitialIplanKey,
 target.InsertedBy = source.InsertedBy,
 target.InsertedDTM = source.InsertedDTM,
 target.ModifiedBy = source.ModifiedBy,
 target.ModifiedDTM = source.ModifiedDTM,
 target.DWLastUpdateDateTime = source.DWLastUpdateDateTime
WHEN NOT MATCHED THEN
  INSERT (MonthID, SnapShotDate, Coid, ClaimNumber, ClaimKey, RegionKey, ServicingProviderKey, RenderingProviderKey, PatientKey, PatientInternalID, VisitNumber, ClaimStatusKey, FacilityKey, Payer1IplanKey, ClaimServiceDate, ClaimServiceDateYear, ClaimServiceDateMonth, ClaimBalance, ClaimCharge, VoidFlag, DeleteFlag, ARClaimFlag, FirstInsuranceBillDateKey, LastBillDateKey, NumberOfBills, LiabilityDate, ClaimDate, LiabilityOwner, RHHoldCode, ClaimLineChargeKey, CPTCodeKey, CPTCode, CPTServiceStartDate, CPTServiceEndDate, CPTDeleteFlag, CPTModifier1, CPTModifier2, CPTModifier3, CPTModifier4, LineCharge, LineChargeFinal, LineInsPayment, LineInsPaymentFirstDate, LineInsPaymentFlag, LinePatPayment, LinePatPaymentFlag, LineInsContractual, LineInsContractualFirstDate, LineInsContractualFlag, LineAdjustment, LineAdjustmentFlag, LineBalance, LineInBalanceFlag, LineAdminAdj, LineDenialAdj, LineCharityAdj, LineContractualAdj, LineUninsuredDiscountAdj, LineRefundAdj, LineNSFAdj, LineEscheatAdj, LineBadDebtAdj, LineOtherAdj, VoidDate, PriorClaimKey, VoidFirstBilledClaimKey, VoidFirstBilledClaimNumber, VoidFirstBilledDateKey, OnFirstBilledFlag, OnFirstBilledCharge, VoidFirstBilledClaimLineChargeKey, FirstDenialCarcRarcCode, FirstDenialERADate, FirstDenialCARCCodes, FirstDenialRARCCodes, FirstDenialPayerName, FirstDenialCategory, InitialDeniedCharges, FirstDenialFlag, LineDenialAdjFlag, FirstDenialCarcRarcType, FirstDenialCARCIsDenial, FirstDenialCARCRequiresRarc, FirstDenialRARCIsDenial, LastDenialCarcRarcCode, LastDenialERADate, LastDenialCARCCodes, LastDenialRARCCodes, LastDenialPayerName, LastDenialCategory, LastDenialCarcRarcType, LastDenialCARCIsDenial, LastDenialCARCRequiresRarc, LastDenialRARCIsDenial, FirstERACarcRarcCode, FirstERADate, FirstERACARCCodes, FirstERARARCCodes, FirstERAPayerName, FirstERACategory, FirstERACarcRarcType, FirstERACARCIsDenial, FirstERACARCRequiresRarc, FirstERARARCIsDenial, LastERACarcRarcCode, LastERADate, LastERACARCCodes, LastERARARCCodes, LastERAPayerName, LastERACategory, LastERACarcRarcType, LastERACARCIsDenial, LastERACARCRequiresRarc, LastERARARCIsDenial, ArtivaPool, ArtivaLiabilityLastReviewed, ArtivaLiabilityFollowupDate, LastAdjustmentCode, LastAdjustmentName, LastAdjustmentCategory, LastAdjustmentDate, LineAdminAdjLastDate, LineDenialAdjLastDate, LineCharityAdjLastDate, LineContractualAdjLastDate, LineUninsuredDiscountAdjLastDate, LineRefundAdjLastDate, LineNSFAdjLastDate, LineEscheatAdjLastDate, LineBadDebtAdjLastDate, LineOtherAdjLastDate, IETFlag, IETCreateDate, IETLastModifiedDate, DenialCount, DenialLastEraDate, ClaimCPTCode1, ClaimCPTCode2, ClaimCPTCode3, ClaimCPTCode4, ClaimCPTCode5, GLDeptNumber, ProviderSpecialtyName, ProviderSpecialtyType, ProviderSpecialtyCategory, InitialIplanKey, InsertedBy, InsertedDTM, ModifiedBy, ModifiedDTM, DWLastUpdateDateTime)
  VALUES (source.MonthID, source.SnapShotDate, TRIM(source.Coid), source.ClaimNumber, source.ClaimKey, source.RegionKey, source.ServicingProviderKey, source.RenderingProviderKey, source.PatientKey, source.PatientInternalID, source.VisitNumber, source.ClaimStatusKey, source.FacilityKey, source.Payer1IplanKey, source.ClaimServiceDate, source.ClaimServiceDateYear, source.ClaimServiceDateMonth, source.ClaimBalance, source.ClaimCharge, source.VoidFlag, source.DeleteFlag, source.ARClaimFlag, source.FirstInsuranceBillDateKey, source.LastBillDateKey, source.NumberOfBills, source.LiabilityDate, source.ClaimDate, TRIM(source.LiabilityOwner), TRIM(source.RHHoldCode), source.ClaimLineChargeKey, source.CPTCodeKey, TRIM(source.CPTCode), source.CPTServiceStartDate, source.CPTServiceEndDate, source.CPTDeleteFlag, TRIM(source.CPTModifier1), TRIM(source.CPTModifier2), TRIM(source.CPTModifier3), TRIM(source.CPTModifier4), source.LineCharge, source.LineChargeFinal, source.LineInsPayment, source.LineInsPaymentFirstDate, source.LineInsPaymentFlag, source.LinePatPayment, source.LinePatPaymentFlag, source.LineInsContractual, source.LineInsContractualFirstDate, source.LineInsContractualFlag, source.LineAdjustment, source.LineAdjustmentFlag, source.LineBalance, source.LineInBalanceFlag, source.LineAdminAdj, source.LineDenialAdj, source.LineCharityAdj, source.LineContractualAdj, source.LineUninsuredDiscountAdj, source.LineRefundAdj, source.LineNSFAdj, source.LineEscheatAdj, source.LineBadDebtAdj, source.LineOtherAdj, source.VoidDate, source.PriorClaimKey, source.VoidFirstBilledClaimKey, source.VoidFirstBilledClaimNumber, source.VoidFirstBilledDateKey, source.OnFirstBilledFlag, source.OnFirstBilledCharge, source.VoidFirstBilledClaimLineChargeKey, TRIM(source.FirstDenialCarcRarcCode), source.FirstDenialERADate, TRIM(source.FirstDenialCARCCodes), TRIM(source.FirstDenialRARCCodes), TRIM(source.FirstDenialPayerName), TRIM(source.FirstDenialCategory), source.InitialDeniedCharges, source.FirstDenialFlag, source.LineDenialAdjFlag, TRIM(source.FirstDenialCarcRarcType), TRIM(source.FirstDenialCARCIsDenial), TRIM(source.FirstDenialCARCRequiresRarc), TRIM(source.FirstDenialRARCIsDenial), TRIM(source.LastDenialCarcRarcCode), source.LastDenialERADate, TRIM(source.LastDenialCARCCodes), TRIM(source.LastDenialRARCCodes), TRIM(source.LastDenialPayerName), TRIM(source.LastDenialCategory), TRIM(source.LastDenialCarcRarcType), TRIM(source.LastDenialCARCIsDenial), TRIM(source.LastDenialCARCRequiresRarc), TRIM(source.LastDenialRARCIsDenial), TRIM(source.FirstERACarcRarcCode), source.FirstERADate, TRIM(source.FirstERACARCCodes), TRIM(source.FirstERARARCCodes), TRIM(source.FirstERAPayerName), TRIM(source.FirstERACategory), TRIM(source.FirstERACarcRarcType), TRIM(source.FirstERACARCIsDenial), TRIM(source.FirstERACARCRequiresRarc), TRIM(source.FirstERARARCIsDenial), TRIM(source.LastERACarcRarcCode), source.LastERADate, TRIM(source.LastERACARCCodes), TRIM(source.LastERARARCCodes), TRIM(source.LastERAPayerName), TRIM(source.LastERACategory), TRIM(source.LastERACarcRarcType), TRIM(source.LastERACARCIsDenial), TRIM(source.LastERACARCRequiresRarc), TRIM(source.LastERARARCIsDenial), TRIM(source.ArtivaPool), TRIM(source.ArtivaLiabilityLastReviewed), TRIM(source.ArtivaLiabilityFollowupDate), TRIM(source.LastAdjustmentCode), TRIM(source.LastAdjustmentName), TRIM(source.LastAdjustmentCategory), source.LastAdjustmentDate, source.LineAdminAdjLastDate, source.LineDenialAdjLastDate, source.LineCharityAdjLastDate, source.LineContractualAdjLastDate, source.LineUninsuredDiscountAdjLastDate, source.LineRefundAdjLastDate, source.LineNSFAdjLastDate, source.LineEscheatAdjLastDate, source.LineBadDebtAdjLastDate, source.LineOtherAdjLastDate, TRIM(source.IETFlag), TRIM(source.IETCreateDate), TRIM(source.IETLastModifiedDate), source.DenialCount, source.DenialLastEraDate, TRIM(source.ClaimCPTCode1), TRIM(source.ClaimCPTCode2), TRIM(source.ClaimCPTCode3), TRIM(source.ClaimCPTCode4), TRIM(source.ClaimCPTCode5), TRIM(source.GLDeptNumber), TRIM(source.ProviderSpecialtyName), TRIM(source.ProviderSpecialtyType), TRIM(source.ProviderSpecialtyCategory), source.InitialIplanKey, source.InsertedBy, source.InsertedDTM, source.ModifiedBy, source.ModifiedDTM, source.DWLastUpdateDateTime);

SET DUP_COUNT = (
  SELECT COUNT(*)
  FROM (
      SELECT SnapShotDate, ClaimKey
      FROM {{ params.param_psc_core_dataset_name }}.EPIC_FactSnapShotInitialDenials
      GROUP BY SnapShotDate, ClaimKey
      HAVING COUNT(*) > 1
  )
);

IF DUP_COUNT <> 0 THEN
  ROLLBACK TRANSACTION;
  RAISE USING MESSAGE = CONCAT('Duplicates are not allowed in the table {{ params.param_psc_core_dataset_name }}.EPIC_FactSnapShotInitialDenials');
ELSE
  COMMIT TRANSACTION;
END IF;
