##########################
## Variable Declaration ##
##########################

CRNT_TS=`date +"%Y-%m-%d %H:%M:%S"`

export AC_EXP_SQL_STATEMENT="select '$Job_Name'||','||
cast(count(*) as varchar(20))||',' as SOURCE_STRING
FROM (SELECT 
(SELECT (COALESCE(MAX(PERCENTAGE_RANGE_SID),0)) FROM EDWHR_BASE_VIEWS.REF_PERCENTAGE_RANGE) + 
ROW_NUMBER() OVER (ORDER BY Y.PERCENTAGE_RANGE_DESC) AS PERCENTAGE_RANGE_SID
, Y.PERCENTAGE_RANGE_DESC
, 'M' AS SOURCE_SYSTEM_CODE
, CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME
FROM (
SEL STG.PERCENTAGE_RANGE_DESC
FROM 
(
SELECT 
DISTINCT(TRIM(WILLING_TRAVEL_PERCENTAGE)) AS PERCENTAGE_RANGE_DESC
FROM EDWHR_STAGING.EMPLOYEE_INFO 
WHERE TRIM(WILLING_TRAVEL_PERCENTAGE) IS NOT NULL AND TRIM(WILLING_TRAVEL_PERCENTAGE) NOT = ''
) STG

LEFT OUTER JOIN EDWHR_BASE_VIEWS.REF_PERCENTAGE_RANGE TGT
ON STG.PERCENTAGE_RANGE_DESC= TGT.PERCENTAGE_RANGE_DESC

WHERE TGT.PERCENTAGE_RANGE_DESC IS NULL
) Y)T
"


export AC_ACT_SQL_STATEMENT="select '$Job_Name'||','||
cast(count(*) as varchar(20))||',' as SOURCE_STRING 
FROM $NCR_TGT_SCHEMA.REF_PERCENTAGE_RANGE WHERE DW_Last_Update_Date_Time >='$CRNT_TS'";