SELECT CONCAT(count(*)) AS SOURCE_STRING
FROM
 (SELECT ROW_NUMBER() OVER(
 ORDER BY MET.CR_PATIENT_ID, INAV.NAV_PATIENT_ID, CPID.PATIENT_DW_ID ASC) AS CANCER_PATIENT_DRIVER_SK,
 MET.CR_PATIENT_ID AS CR_PATIENT_ID,
 INAV.NAV_PATIENT_ID AS CN_PATIENT_ID,
 CPID.PATIENT_DW_ID AS CP_PATIENT_ID,
 COALESCE(MET.COID, CPID.COID, INAV.COID) AS COID,
 COALESCE(MET.COMPANY_CODE, CPID.COMPANY_CODE, INAV.COMPANY_CODE) AS COMPANY_CODE,
 COALESCE(MET.NETWORK_MNEMONIC_CS, CPID.NETWORK_MNEMONIC_CS, INAV.NETWORK_MNEMONIC_CS) AS NETWORK_MNEMONIC_CS,
 COALESCE(MET.PATIENT_MARKET_URN_TEXT, CPID.PATIENT_MARKET_URN, INAV.EMPI_TEXT) AS PATIENT_MARKET_URN_TEXT,
 COALESCE(MET.MEDICAL_RECORD_NUM, CPID.MEDICAL_RECORD_NUM, INAV.MEDICAL_RECORD_NUM) AS MEDICAL_RECORD_NUM,
 EMPI.EMPI_TEXT,
 COALESCE(MET.PATIENT_FIRST_NAME, CPID.PATIENT_FIRST_NAME, INAV.PATIENT_FIRST_NAME) AS PATIENT_FIRST_NAME,
 COALESCE(MET.PATIENT_MIDDLE_NAME, INAV.PATIENT_MIDDLE_NAME) AS PATIENT_MIDDLE_NAME,
 COALESCE(MET.PATIENT_LAST_NAME, CPID.PATIENT_LAST_NAME, INAV.PATIENT_LAST_NAME) AS PATIENT_LAST_NAME,
 INAV.PREFERRED_NAME,
 COALESCE(MET.SOURCE_SYSTEM_CODE, CPID.SOURCE_SYSTEM_CODE, INAV.SOURCE_SYSTEM_CODE) AS SOURCE_SYSTEM_CODE,
 CURRENT_TIMESTAMP(0) AS DW_LAST_UPDATE_DATE_TIME
 FROM
 (SELECT CP.PATIENT_MARKET_URN_TEXT,
 CP.CR_PATIENT_ID ,
 CP.COID ,
 CP.COMPANY_CODE ,
 CP.MEDICAL_RECORD_NUM ,
 DF.FACILITY_MNEMONIC_CS ,
 DF.NETWORK_MNEMONIC_CS ,
 CP.PATIENT_FIRST_NAME AS PATIENT_FIRST_NAME ,
 CP.PATIENT_LAST_NAME AS PATIENT_LAST_NAME ,
 CP.PATIENT_MIDDLE_NAME AS PATIENT_MIDDLE_NAME ,
 CP.SOURCE_SYSTEM_CODE
 FROM EDWCR_BASE_VIEWS.CR_PATIENT CP
 INNER JOIN
 (SELECT FACILITY_MNEMONIC_CS,
 NETWORK_MNEMONIC_CS,
 COID,
 FACILITY_ACTIVE_IND
 FROM EDW_PUB_Views.Clinical_facility QUALIFY ROW_NUMBER() OVER(PARTITION BY COID
 ORDER BY FACILITY_ACTIVE_IND DESC)=1) DF ON CP.COID =DF.COID) MET
 FULL OUTER JOIN
 (SELECT PATIENT_MARKET_URN,
 CRIO.NETWORK_MNEMONIC_CS,
 MEDICAL_RECORD_NUM,
 PATIENT_DW_ID,
 CRIO.COID ,
 COMPANY_CODE ,
 CRIO .FIRST_NAME AS PATIENT_FIRST_NAME ,
 CRIO.LAST_NAME AS PATIENT_LAST_NAME ,
 DF1.FACILITY_MNEMONIC_CS,
 CRIO.SOURCE_SYSTEM_CODE
 FROM EDWCR_BASE_VIEWS.CANCER_PATIENT_ID_OUTPUT CRIO
 INNER JOIN
 (SELECT FACILITY_MNEMONIC_CS,
 NETWORK_MNEMONIC_CS,
 COID,
 FACILITY_ACTIVE_IND
 FROM EDW_PUB_Views.Clinical_facility QUALIFY ROW_NUMBER() OVER(PARTITION BY COID
 ORDER BY FACILITY_ACTIVE_IND DESC)=1) DF1 ON CRIO.COID =DF1.COID QUALIFY ROW_NUMBER() OVER (PARTITION BY COALESCE(PATIENT_MARKET_URN, MEDICAL_RECORD_NUM||FACILITY_MNEMONIC_CS, PATIENT_DW_ID)
 ORDER BY REPORT_ASSIGNED_DATE_TIME DESC)=1) CPID ON coalesce(MET.PATIENT_MARKET_URN_TEXT, MET.MEDICAL_RECORD_NUM||MET.FACILITY_MNEMONIC_CS) = COALESCE(CPID.PATIENT_MARKET_URN, CPID.MEDICAL_RECORD_NUM||CPID.FACILITY_MNEMONIC_CS)
 AND MET.NETWORK_MNEMONIC_CS = CPID.NETWORK_MNEMONIC_CS
 FULL OUTER JOIN
 (SELECT CP.NAV_PATIENT_ID,
 CPT.PATIENT_MARKET_URN,
 CPT.NETWORK_MNEMONIC_CS,
 CPT.MEDICAL_RECORD_NUM,
 CPT.COMPANY_CODE,
 CPT.EMPI_TEXT,
 CPT.COID,
 DF2.FACILITY_MNEMONIC_CS ,
 CP.FIRST_NAME AS PATIENT_FIRST_NAME ,
 CP.LAST_NAME AS PATIENT_LAST_NAME ,
 CP.MIDDLE_NAME AS PATIENT_MIDDLE_NAME ,
 CP.PREFERRED_NAME ,
 CP.SOURCE_SYSTEM_CODE
 FROM EDWCR_BASE_VIEWS.CN_PERSON CP
 LEFT OUTER JOIN EDWCR_BASE_VIEWS.CN_PATIENT CPT ON CP.NAV_PATIENT_ID = CPT.NAV_PATIENT_ID
 INNER JOIN
 (SELECT FACILITY_MNEMONIC_CS,
 NETWORK_MNEMONIC_CS,
 COID,
 FACILITY_ACTIVE_IND
 FROM EDW_PUB_Views.Clinical_facility QUALIFY ROW_NUMBER() OVER(PARTITION BY COID
 ORDER BY FACILITY_ACTIVE_IND DESC)=1) DF2 ON CPT.COID =DF2.COID
 LEFT OUTER JOIN EDWCR_BASE_VIEWS.CN_PATIENT_ADDRESS CPA ON CP.NAV_PATIENT_ID= CPA.NAV_PATIENT_ID
 LEFT OUTER JOIN EDWCR_BASE_VIEWS.CN_PATIENT_PHONE_NUM CPP ON CP.NAV_PATIENT_ID= CPP.NAV_PATIENT_ID QUALIFY ROW_NUMBER () OVER(PARTITION BY COALESCE(CPT.PATIENT_MARKET_URN, CPT.MEDICAL_RECORD_NUM||DF2.FACILITY_MNEMONIC_CS, CP.Nav_Patient_ID)
 ORDER BY CP.NAV_PATIENT_ID DESC)=1) INAV ON COALESCE(TRIM(MET.NETWORK_MNEMONIC_CS)||MET.PATIENT_MARKET_URN_TEXT, MET.MEDICAL_RECORD_NUM||MET.FACILITY_MNEMONIC_CS) = COALESCE(INAV.PATIENT_MARKET_URN, INAV.MEDICAL_RECORD_NUM||INAV.FACILITY_MNEMONIC_CS)
 AND MET.NETWORK_MNEMONIC_CS=INAV.NETWORK_MNEMONIC_CS
 LEFT OUTER JOIN (SEL PATIENT_MARKET_URN,
 NETWORK_MNEMONIC_CS,
 EMPI_TEXT
 FROM (SEL PATIENT_MARKET_URN,
 NETWORK_MNEMONIC_CS,
 E.EMPI_TEXT
 FROM EDWCR_VIEWS.CLINICAL_REGISTRATION CR
 INNER JOIN EDWCR_VIEWS.EMPI_ENCOUNTER_ID_XWALK E ON CR.PATIENT_DW_ID=E.ENCOUNTER_ID
 WHERE ENCOUNTER_ID_TYPE_NAME='PATIENT_DW_ID'
 AND EMPI_TEXT>0 ) A QUALIFY ROW_NUMBER() OVER(PARTITION BY PATIENT_MARKET_URN, NETWORK_MNEMONIC_CS
 ORDER BY EMPI_TEXT ASC)=1) EMPI ON COALESCE(MET.NETWORK_MNEMONIC_CS, CPID.NETWORK_MNEMONIC_CS, INAV.NETWORK_MNEMONIC_CS) = EMPI.NETWORK_MNEMONIC_CS
 AND COALESCE(MET.PATIENT_MARKET_URN_TEXT, CPID.PATIENT_MARKET_URN, INAV.EMPI_TEXT) =EMPI.PATIENT_MARKET_URN)B