SELECT CONCAT(count(*)) AS SOURCE_STRING
FROM
 (SELECT row_number() OVER (
 ORDER BY A1.Cancer_Patient_Driver_SK,
 A1.Cancer_Patient_Id_Output_SK ASC) AS Cancer_Patient_Id_Output_Driver_SK,
 A1.Cancer_Patient_Driver_SK,
 A1.Cancer_Patient_Id_Output_SK,
 A1.Message_Control_Id_Text,
 A1.User_Action_Date_Time,
 A1.Coid,
 A1.Company_Code,
 A1.Patient_DW_Id,
 A1.Pat_Acct_Num,
 A1.Medical_Record_Num,
 A1.Patient_Market_URN,
 A1.Last_Name,
 A1.First_Name,
 A1.Birth_Date,
 A1.Gender_Code,
 A1.Social_Security_Num,
 A1.Address_Line_1_Text,
 A1.Address_Line_2_Text,
 A1.City_Name,
 A1.State_Code,
 A1.Zip_Code,
 A1.Patient_Type_Code,
 A1.Message_Type_Code,
 A1.Message_Event_Type_Code,
 A1.Message_Flag_Code,
 A1.Message_Origin_Requested_Date_Time,
 A1.Message_Signed_Observation_Date_Time,
 A1.Message_Ingestion_Date_Time,
 A1.Message_Created_Date_Time,
 A1.Document_Type_Id_Text,
 A1.Document_Type_Text,
 A1.Document_Type_Coding_System_Code,
 A1.First_Insert_Date_Time,
 A1.ICD_Oncology_Type_Code,
 A1.Predicted_Primary_ICD_Oncology_Code,
 A1.Predicted_Primary_ICD_Site_Desc,
 A1.Suggested_Primary_ICD_Oncology_Code,
 A1.Suggested_Primary_ICD_Site_Desc,
 A1.Submitted_Primary_ICD_Oncology_Code,
 A1.Submitted_Primary_ICD_Site_Desc,
 A1.Transition_Of_Care_Num,
 A1.User_Action_Desc,
 A1.User_Action_Criticality_Text,
 A1.User_3_4_Id,
 A1.Report_Assigned_Date_Time,
 A1.Attending_Physician_Full_Name,
 A1.PCP_Full_Name,
 A1.PCP_Phone_Num,
 A1.Facility_Menmonic_CS,
 A1.Network_Mnemonic_CS,
 A1.Model_Predicted_Sarcoma_Ind,
 A1.Submitted_Sarcoma_Ind,
 A1.Suggested_Sarcoma_Ind,
 A1.Source_System_Code,
 A1.DW_Last_Update_Date_Time
 FROM
 (SELECT DISTINCT cpd.Cancer_Patient_Driver_SK,
 A.Cancer_Patient_Id_Output_SK,
 A.Message_Control_Id_Text,
 A.User_Action_Date_Time,
 A.Coid,
 A.Company_Code,
 A.Patient_DW_Id,
 A.Pat_Acct_Num,
 A.Medical_Record_Num,
 A.Patient_Market_URN,
 A.Last_Name,
 A.First_Name,
 A.Birth_Date,
 A.Gender_Code,
 A.Social_Security_Num,
 A.Address_Line_1_Text,
 A.Address_Line_2_Text,
 A.City_Name,
 A.State_Code,
 A.Zip_Code,
 A.Patient_Type_Code,
 A.Message_Type_Code,
 A.Message_Event_Type_Code,
 A.Message_Flag_Code,
 A.Message_Origin_Requested_Date_Time,
 A.Message_Signed_Observation_Date_Time,
 A.Message_Ingestion_Date_Time,
 A.Message_Created_Date_Time,
 A.Document_Type_Id_Text,
 A.Document_Type_Text,
 A.Document_Type_Coding_System_Code,
 A.First_Insert_Date_Time,
 A.ICD_Oncology_Type_Code,
 A.Predicted_Primary_ICD_Oncology_Code,
 A.Predicted_Primary_ICD_Site_Desc,
 A.Suggested_Primary_ICD_Oncology_Code,
 A.Suggested_Primary_ICD_Site_Desc,
 A.Submitted_Primary_ICD_Oncology_Code,
 A.Submitted_Primary_ICD_Site_Desc,
 A.Transition_Of_Care_Num,
 A.User_Action_Desc,
 A.User_Action_Criticality_Text,
 A.User_3_4_Id,
 A.Report_Assigned_Date_Time,
 A.Attending_Physician_Full_Name,
 A.PCP_Full_Name,
 A.PCP_Phone_Num,
 A.Facility_Menmonic_CS,
 A.Network_Mnemonic_CS,
 A.Model_Predicted_Sarcoma_Ind,
 A.Submitted_Sarcoma_Ind,
 A.Suggested_Sarcoma_Ind,
 A.Source_System_Code,
 A.DW_Last_Update_Date_Time
 FROM EDWCR_BASE_VIEWS.Cancer_Patient_Id_Output A
 INNER JOIN (Sel Cancer_Patient_Driver_SK,
 COID,
 cp_patient_id,
 Network_Mnemonic_CS
 FROM EDWCR_BASE_VIEWS.Cancer_Patient_Driver qualify row_number() over(PARTITION BY cp_patient_id, Network_Mnemonic_CS
 ORDER BY Cancer_Patient_Driver_SK ASC)=1) Cpd ON A.patient_dw_id=cpd.cp_patient_id
 AND a.Network_Mnemonic_CS =cpd.Network_Mnemonic_CS
 UNION SELECT DISTINCT cpd.Cancer_Patient_Driver_SK,
 A.Cancer_Patient_Id_Output_SK,
 A.Message_Control_Id_Text,
 A.User_Action_Date_Time,
 Coalesce(A.Coid, DF2.Coid) AS Coid,
 A.Company_Code,
 A.Patient_DW_Id,
 A.Pat_Acct_Num,
 A.Medical_Record_Num,
 A.Patient_Market_URN,
 A.Last_Name,
 A.First_Name,
 A.Birth_Date,
 A.Gender_Code,
 A.Social_Security_Num,
 A.Address_Line_1_Text,
 A.Address_Line_2_Text,
 A.City_Name,
 A.State_Code,
 A.Zip_Code,
 A.Patient_Type_Code,
 A.Message_Type_Code,
 A.Message_Event_Type_Code,
 A.Message_Flag_Code,
 A.Message_Origin_Requested_Date_Time,
 A.Message_Signed_Observation_Date_Time,
 A.Message_Ingestion_Date_Time,
 A.Message_Created_Date_Time,
 A.Document_Type_Id_Text,
 A.Document_Type_Text,
 A.Document_Type_Coding_System_Code,
 A.First_Insert_Date_Time,
 A.ICD_Oncology_Type_Code,
 A.Predicted_Primary_ICD_Oncology_Code,
 A.Predicted_Primary_ICD_Site_Desc,
 A.Suggested_Primary_ICD_Oncology_Code,
 A.Suggested_Primary_ICD_Site_Desc,
 A.Submitted_Primary_ICD_Oncology_Code,
 A.Submitted_Primary_ICD_Site_Desc,
 A.Transition_Of_Care_Num,
 A.User_Action_Desc,
 A.User_Action_Criticality_Text,
 A.User_3_4_Id,
 A.Report_Assigned_Date_Time,
 A.Attending_Physician_Full_Name,
 A.PCP_Full_Name,
 A.PCP_Phone_Num,
 A.Facility_Menmonic_CS,
 A.Network_Mnemonic_CS,
 A.Model_Predicted_Sarcoma_Ind,
 A.Submitted_Sarcoma_Ind,
 A.Suggested_Sarcoma_Ind,
 A.Source_System_Code,
 A.DW_Last_Update_Date_Time
 FROM EDWCR_BASE_VIEWS.Cancer_Patient_Id_Output A
 LEFT OUTER JOIN
 (SELECT FACILITY_MNEMONIC_CS,
 COID,
 FACILITY_ACTIVE_IND
 FROM EDWCR_BASE_VIEWS.CLINICAL_FACILITY QUALIFY ROW_NUMBER() OVER(PARTITION BY FACILITY_MNEMONIC_CS
 ORDER BY FACILITY_ACTIVE_IND DESC)=1) DF2 ON A.Facility_menmonic_cs =DF2.FACILITY_MNEMONIC_CS
 LEFT OUTER JOIN (Sel Cancer_Patient_Driver_SK,
 coid,
 COALESCE(patient_market_urn_text||Network_Mnemonic_CS, MEDICAL_RECORD_NUM||coid) AS PID,
 Network_Mnemonic_CS
 FROM EDWCR_BASE_VIEWS.Cancer_Patient_Driver qualify row_number() over(PARTITION BY COALESCE(patient_market_urn_text||Network_Mnemonic_CS, MEDICAL_RECORD_NUM||COID)
 ORDER BY Cancer_Patient_Driver_SK ASC)=1) Cpd ON COALESCE(A.patient_market_urn||A.Network_Mnemonic_CS, A.MEDICAL_RECORD_NUM||coalesce(A.coid, DF2.coid)) = Cpd.PID
 AND coalesce(A.Network_Mnemonic_CS, '-1')=coalesce(cpd.Network_Mnemonic_CS, '-1')
 WHERE (Zeroifnull(A.Patient_DW_ID),
 A.Network_Mnemonic_CS) NOT IN
 (SELECT Zeroifnull(A.Patient_DW_ID),
 A.Network_Mnemonic_CS
 FROM EDWCR_BASE_VIEWS.Cancer_Patient_Id_Output A
 INNER JOIN EDWCR_BASE_VIEWS.Cancer_Patient_Driver cpd ON A.patient_dw_id=cpd.cp_patient_id
 AND A.Network_Mnemonic_CS=cpd.Network_Mnemonic_CS) ) A1)STG