SELECT CONCAT(count(*), ',	') AS SOURCE_STRING
FROM
 (SELECT Hashbite_SSK
 FROM edwcr_staging.CN_PATIENT_BRCA_SCREENING_ASSESSMENT_STG
 WHERE Hashbite_SSK NOT IN
 (SELECT Hashbite_SSK
 FROM edwcr.CN_PATIENT_BRCA_SCREENING_ASSESSMENT) )A;