SELECT CONCAT(count(*)) AS SOURCE_STRING
FROM (Sel 'X' AS ccnt
 FROM (sel DISTINCT SOURCE AS Disease_Assess_Source_Name
 FROM EDWCR_Staging.PATIENT_HEME_DISEASE_ASSESSMENT_STG
 WHERE SOURCE IS NOT NULL ) SSC
 LEFT OUTER JOIN EDWCR_BASE_VIEWS.REF_DISEASE_ASSESS_SOURCE RTT ON SSC.Disease_Assess_Source_Name = RTT.Disease_Assess_Source_Name
 WHERE RTT.Disease_Assess_Source_Name IS NULL ) iq