
SELECT CONCAT(count(*), ',	') AS SOURCE_STRING
FROM
 (SELECT trim(TEST_TYPE_DESC) AS TEST_TYPE_DESC,
 trim(TEST_SUB_TYPE_DESC) AS TEST_SUB_TYPE_DESC,
 Source_System_Code AS Source_System_Code
 FROM EDWCR_staging.REF_TEST_TYPE_STG
 WHERE (trim(TEST_TYPE_DESC),
 trim(TEST_SUB_TYPE_DESC)) NOT IN (sel trim(TEST_TYPE_DESC),
 trim(TEST_SUB_TYPE_DESC)
 FROM EDWCR.REF_TEST_TYPE)
 AND DW_Last_Update_Date_Time <
 (SELECT MAX(Job_Start_Date_Time) AS Job_Start_Date_Time
 FROM EDWCR_DMX_AC.ETL_JOB_RUN
 WHERE Job_Name = 'J_CR_REF_TEST_TYPE') ) A;