-- Translation time: 2023-05-10T05:47:50.588331Z
-- Translation job ID: 92e92d81-1143-4781-91d8-614cfb5dfe89
-- Source: eim-ops-cs-datamig-dev-0002/sql_conversion/edwcr_migration_source/{{ params.param_cr_views_dataset_name }}/cr_patient_tumor.sql
-- Translated from: Teradata
-- Translated to: BigQuery

/***************************************************************************************
S E C U R I T Y   V I E W
****************************************************************************************/
CREATE OR REPLACE VIEW {{ params.param_cr_views_dataset_name }}.cr_patient_tumor AS SELECT
    a.tumor_id,
    a.cr_patient_id,
    a.tumor_grade_id,
    a.case_status_id,
    a.tumor_primary_site_id,
    a.definitive_chemo_summary_id,
    a.definitive_diagnostic_stage_summary_id,
    a.definitive_hormone_summary_id,
    a.definitive_immuno_summary_id,
    a.definitive_surgical_margin_summary_id,
    a.definitive_palliative_care_summary_id,
    a.radiation_boost_modality_id,
    a.radiation_hospital_id,
    a.radiation_site_id,
    a.chemo_declined_reason_id,
    a.hormone_declined_reason_id,
    a.immuno_declined_reason_id,
    a.radiation_declined_reason_id,
    a.primary_site_surgery_summary_id,
    a.treatment_therapy_schedule_id,
    a.definitive_radiation_modality_id,
    a.definitive_radiation_volume_summary_id,
    a.regional_lymph_node_summary_id,
    a.surgery_approach_hospital_id,
    a.primary_site_surgery_hospital_id,
    a.definitive_treatment_facility_id,
    a.secondary_treatment_facility_id,
    a.tertiary_treatment_facility_id,
    a.tumor_size_summary_id,
    a.class_case_id,
    a.sequence_primary_id,
    a.best_cs_summary_id,
    a.best_cs_tnm_id,
    a.tumor_size_num_text,
    a.definitive_chemo_date,
    a.definitive_radiation_date,
    a.definitive_immuno_date,
    a.definitive_hormone_date,
    a.definitive_radiation_treatment_end_date,
    a.first_surgery_chemo_elapsed_day_num,
    a.first_surgery_contact_elapsed_day_num,
    a.first_chemo_surgery_elapsed_day_num,
    a.length_to_chemo_day_num,
    a.length_to_hormone_day_num,
    a.length_to_immuno_day_num,
    a.length_to_surgery_day_num,
    a.length_to_radiation_day_num,
    a.length_to_transplant_day_num,
    a.length_to_first_treatment_day_num,
    a.first_surgery_date,
    a.radiation_elapsed_day_num,
    a.definitive_surgery_date,
    a.admission_date,
    a.survival_num,
    a.abstracted_by_text,
    a.managing_physician_code,
    a.medical_oncology_physician_code,
    a.radiation_oncology_physician_code,
    a.primary_surgeon_physician_code,
    a.cs_ss_factor_1_num_code,
    a.cs_ss_factor_2_num_code,
    a.cs_ss_factor_15_num_code,
    a.cs_ss_factor_16_num_code,
    a.cs_ss_factor_22_num_code,
    a.cs_ss_factor_23_num_code,
    a.cs_ss_factor_25_num_code,
    a.mltp_disciplinary_meet_1_present_date,
    a.mltp_disciplinary_meet_1_present_id,
    a.mltp_disciplinary_meet_2_present_date,
    a.mltp_disciplinary_meet_2_present_id,
    a.mltp_disciplinary_meet_3_present_date,
    a.mltp_disciplinary_meet_3_present_id,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    {{ params.param_cr_base_views_dataset_name }}.cr_patient_tumor AS a
;
