-- Translation time: 2023-05-10T05:47:50.588331Z
-- Translation job ID: 92e92d81-1143-4781-91d8-614cfb5dfe89
-- Source: eim-ops-cs-datamig-dev-0002/sql_conversion/edwcr_migration_source/{{ params.param_cr_views_dataset_name }}/ref_clinical_pharmaceutical.sql
-- Translated from: Teradata
-- Translated to: BigQuery

/***************************************************************************************
S E C U R I T Y   V I E W
****************************************************************************************/
CREATE OR REPLACE VIEW {{ params.param_cr_views_dataset_name }}.ref_clinical_pharmaceutical AS SELECT
    a.company_code,
    a.coid,
    a.clinical_phrm_mnem_cs,
    a.clinical_phrm_mnem,
    a.ndc,
    a.ndc_10_digit,
    a.fsv_id_num,
    a.fsv_generic_name,
    a.cvx_code,
    a.charge_code,
    a.usage_type_code,
    a.clinical_phrm_id_text,
    a.clinical_phrm_strength_amt,
    a.clinical_phrm_trade_name,
    a.generic_phrm_mnem_cs,
    a.therapeutic_cls_group_mnem_cs,
    a.general_name_group_mnem_cs,
    a.specific_name_group_mnem_cs,
    a.drug_type_mnem_cs,
    a.drug_admin_form_mnem_cs,
    a.drug_dispense_form_mnem_cs,
    a.drug_dispense_size_text,
    a.control_schedule_num,
    a.control_schedule_name,
    a.lab_test_group_mnemonic_cs,
    a.pci_group_sort_text,
    a.clinical_phrm_active_ind,
    a.alt_trade_name,
    a.order_size_text,
    a.bulk_form_mnem_cs,
    a.bulk_size_num,
    a.fluid_ind,
    a.check_interaction_ind,
    a.pre_mix_ind,
    a.additive_ind,
    a.pom_type_code,
    a.ingredient_ind,
    a.order_by_oe_ind,
    a.order_by_or_ind,
    a.extemp_prep_mnem_cs,
    a.special_storage_mnem_cs,
    a.unit_dose_pack_ind,
    a.charge_patient_ind,
    a.allow_order_code,
    a.keep_use_stat_ind,
    a.refill_label_ind,
    a.dose_label_ind,
    a.emergency_sheet_ind,
    a.billing_unit_of_measure_code,
    a.billing_multiplier_text,
    a.waste_code,
    a.emar_doc_code_1_mnem_cs,
    a.emar_doc_code_2_mnem_cs,
    a.emar_variance_limit_num,
    a.adjust_admin_minute_num,
    a.cosignature_for_doc_med_ind,
    a.cosignature_for_doc_iv_ind,
    a.multidose_container_ind,
    a.order_entry_code_mnem_cs,
    a.reassessment_emar_code_mnem_cs,
    a.reassessment_rule_mnem_cs,
    a.reassessment_once_per_admin_ind,
    a.reassessment_hour_interval_num,
    a.reassessment_minute_interval_num,
    a.reassessment_before_cutoff_num,
    a.reassessment_after_variance_num,
    a.auto_display_at_order_code,
    a.auto_display_at_admin_code,
    a.auto_display_at_verify_code,
    a.charge_type_mnem_cs,
    a.emr_id_text,
    a.disable_auto_verify_ind,
    a.order_unit_mnem_cs,
    a.dispense_unit_mnem_cs,
    a.last_update_date_time,
    a.last_update_user_mnem_cs,
    a.facility_mnemonic_cs,
    a.network_mnemonic_cs,
    a.source_system_code,
    a.dw_last_update_date_time
  FROM
    {{ params.param_cr_base_views_dataset_name }}.ref_clinical_pharmaceutical AS a
    INNER JOIN {{ params.param_auth_base_views_dataset_name }}.cr_secref_facility AS b ON a.company_code = b.company_code
     AND a.coid = b.co_id
     AND b.user_id = session_user()
;
