Select 'J_CR_PATIENT_TREATMENT_STG'||','|| CAST(SUM(TOT_COUNT) AS VARCHAR(20))||',' as SOURCE_STRING 
from 
(
SELECT COUNT(*) AS TOT_COUNT FROM EDWCR_Staging.CR_PATIENT_TREATMENT_stg
UNION ALL
SELECT COUNT(*) AS TOT_COUNT FROM EDWCR_Staging.CR_PATIENT_TREATMENT_STG1
)X