SELECT	
		CAST(DATEPART(yyyy,CPT.CSPERSISTTIMEDATE) as CHAR(4)) || $MVFMT(CAST(DATEPART(mm,CPT.CSPERSISTTIMEDATE) as CHAR(2)), '2"0"R') as Rptg_Period
        ,'TMP' AS Artiva_Instance
		,PAS.HCPSID AS SSC
		 
		,CPT.CSPERSISTTIMEFAC --Facility
		 
		,FAC.CSFACOIDNUM --COID #
		,FAC.CSFAHOSPNUM --Facility #
		
		,CPT.CSPERSISTTIMEKEY --Key to Persisten Time Table
		,CPT.CSPERSISTTIMEACBAL --Liability Balance
		,CPT.CSPERSISTTIMEACTCDS --Total Action Codes Applied On
		,CPT.CSPERSISTTIMEACTNOTW --Account Not Worked Only Viewed
		,CPT.CSPERSISTTIMEACTWRKD --Account Worked Indicator
		--,CPT.CSPERSISTTIMEDATE --Date User on Account
		 ,CAST(CPT.CSPERSISTTIMEDATE as VARCHAR(10)) as CPT_User_On_Acct_Date --Date User on Account
		 ,(CONVERT(INT, CPT.CSPERSISTTIMEDATE))  as CPT_User_On_Acct_Date_Int
		,CPT.CSPERSISTTIMEDEPT --User Dept
		,CPT.CSPERSISTTIMEENCNTR --Encounter ID Relational Field
		,CPT.CSPERSISTTIMEENTOTCH --Encounter Total Charges
		--,CPT.CSPERSISTTIMEETIME --Time User Left an Account
		,CAST(CPT.CSPERSISTTIMEETIME as VARCHAR(8)) as CPT_End_Time --Time User Left an Account
		,(CONVERT(INT, CPT.CSPERSISTTIMEETIME)) as CPT_End_Time_Int
		,CPT.CSPERSISTTIMEFICLASS --Financial Class
		,CPT.CSPERSISTTIMEHOLD --Hold Time (Seconds)
		,CPT.CSPERSISTTIMEHOSPNUM --Hospital Number
		,CPT.CSPERSISTTIMEID --Account ID (HCACID)
		,CPT.CSPERSISTTIMEIPLAN --Iplan
		,CPT.CSPERSISTTIMEPOOL --Pool of Liability
		,CPT.CSPERSISTTIMEPTNUM --Patient #
		,CPT.CSPERSISTTIMEPYID --Payor ID
		,CPT.CSPERSISTTIMEPYR --Current Payor ID of Account
		,CPT.CSPERSISTTIMESEQNUM --Sequence #
		--,CPT.CSPERSISTTIMESTIME --Time User Started on Account
		,CAST(CPT.CSPERSISTTIMESTIME as VARCHAR(8)) as CPT_Start_Time --Time User Started on Account
		,(CONVERT(INT, CPT.CSPERSISTTIMESTIME)) as CPT_Start_Time_Int
		--,CPT.CSPERSISTTIMETIME --Time Entry was Logged
		,CAST(CPT.CSPERSISTTIMETIME as VARCHAR(8)) as CPT_Log_Time --Time Entry was Logged
		,(CONVERT(INT, CPT.CSPERSISTTIMETIME)) as CPT_Log_Time_Int
		,CPT.CSPERSISTTIMETTIME --Total Time User on Account
		,(CPT.CSPERSISTTIMETTIME * 60) as CPT_User_On_Acct
		,CPT.CSPERSISTTIMEUSER --User Id on Account
		,substr(CPT.CSPERSISTTIMEUSER,1,7) as Agent_ID	
		,CPT.CSPERSISTTIMEVTIME --Total Time not Worked (Hours)
		,(CPT.CSPERSISTTIMEVTIME * 60) as CPT_Not_Worked_Min
		,CPT.CSPERSISTTIMEWKTIME --Total Time Worked (Hours)
		,(CPT.CSPERSISTTIMEWKTIME * 60) as CPT_Worked_Min
		,CPT.CSPERSISTTIMEWEBSTAT --??
	
		,STU.HCUADEPT --User's Department or Group
	    ,substr(STU.HCUADEPT,1,3) as Department
		,STU.UAFULLNAME --User's Full Name
		
		 ,GCP.GCDID --Dialer ID/Name
		 ,GCP.GCPOOLNUM --Pool Number (Key)
		 ,GCP.GCPDESC --Pool Description
		 ,GCP.GCPTYPE --Dialing Status of Pool
		 ,CASE
	        WHEN GCP.GCPTYPE = 'D' THEN 'Progressive'
	        WHEN GCP.GCPTYPE = 'N' AND GCP.GCDID = 'HCACTS' THEN 'Manual'
	        WHEN GCP.GCPTYPE = 'N' AND GCP.GCDID IS NULL THEN 'Non-Dialing'
    	END as Dialer_Type
		
		,HCP.CSPYFACILITYID --Facility ID
		,HCP.CSPYIPLAN --Iplan
		,HCP.CSPYIPDESC --Insurance Plan Descrption
		,HCP.CSPYTOPBAL --Top Balance Threshold 
		,HCP.CSPYHIGHBAL --High Balance Threshold
		,HCP.CSPYLOWBAL --Low Balance Threshold
		,HCP.CSPYULTRALOWBAL --Ultra Low Balance Threshold
		,CASE
			WHEN CPT.CSPERSISTTIMEACBAL < HCP.CSPYULTRALOWBAL THEN 'Ultra-Low'
			WHEN CPT.CSPERSISTTIMEACBAL >=HCP.CSPYULTRALOWBAL AND CPT.CSPERSISTTIMEACBAL <= HCP.CSPYLOWBAL THEN 'Low'
			WHEN CPT.CSPERSISTTIMEACBAL > HCP.CSPYLOWBAL AND CPT.CSPERSISTTIMEACBAL < HCP.CSPYHIGHBAL THEN 'Medium'
			WHEN CPT.CSPERSISTTIMEACBAL >= HCP.CSPYHIGHBAL AND CPT.CSPERSISTTIMEACBAL < HCP.CSPYTOPBAL THEN 'High'
			WHEN CPT.CSPERSISTTIMEACBAL >= HCP.CSPYTOPBAL THEN 'Top'
		END as Balance_Strat
		
		,CMP.CSMPID --Major Payer ID
		,CMP.CSMPDESC --Major Payer Group Description
				
FROM   SQLUser.CSPERSISTTIMEACCT CPT

LEFT JOIN SQLUser.STUSER STU
     ON CPT.CSPERSISTTIMEUSER = STU.USERID

LEFT JOIN SQLUser.HCFACILITY FAC
	ON CPT.CSPERSISTTIMEFAC = FAC.HCFAID

LEFT JOIN SQLUser.HCPAS PAS
	ON FAC.HCFAPASID = PAS.HCPSID
		
LEFT JOIN SQLUser.GCPOOL GCP
    ON CPT.CSPERSISTTIMEPOOL = GCP.GCPOOLNUM
	
LEFT JOIN SQLUser.HCPAYER HCP    
    ON CPT.CSPERSISTTIMEFAC = HCP.CSPYFACILITYID
    AND CPT.CSPERSISTTIMEIPLAN = HCP.CSPYIPLAN  
				
 LEFT JOIN SQLUser.CSMAJORPAYER CMP
    ON HCP.CSPYMAJORPYID = CMP.CSMPID

 WHERE CPT.CSPERSISTTIMEDATE  = DATEADD(DD,-1,CURRENT_DATE)
             AND (STU.HCUADEPT LIKE '902%' 
                    OR STU.HCUADEPT LIKE '602%'
					OR STU.HCUADEPT LIKE '913%' 
                    OR STU.HCUADEPT LIKE '613%'
					OR STU.HCUADEPT LIKE '916%' 
                    OR STU.HCUADEPT LIKE '616%'
)
ORDER BY  CPT.CSPERSISTTIMEKEY