# @@START DMEXPRESS_EXPORTED_VARIABLES

export AC_EXP_TOLERANCE_PERCENT=0
export AC_EXP_TOLERANCE_AMT=0
export JOBNAME='J_MHB_PATIENT_VITAL_AUDITS'

export AC_EXP_SQL_STATEMENT="SELECT 'J_MHB_PATIENT_VITAL_AUDITS' || ',' || CAST (COUNT (*) AS VARCHAR (20)) || ','
AS SOURCE_STRING FROM (

SEL * FROM EDWCI_STAGING.MHB_PATIENT_VITAL_AUDIT_WRK

)Q"

export AC_ACT_SQL_STATEMENT="SELECT 'J_MHB_PATIENT_VITAL_AUDITS' || ',' || CAST (COUNT (*) AS VARCHAR (20)) || ','
AS SOURCE_STRING FROM (

SEL * FROM
EDWCI.MHB_PATIENT_VITAL_AUDIT
WHERE DW_LAST_UPDATE_DATE_TIME (DATE) = CURRENT_DATE

)Q"

# @@END DMEXPRESS_EXPORTED_VARIABLES