#  @@START DMEXPRESS_EXPORTED_VARIABLES

export AC_EXP_TOLERANCE_PERCENT=0
export AC_EXP_TOLERANCE_AMT=0
export JOBNAME='J_MHB_Broadcast_Message_Detail'


export AC_ACT_SQL_STATEMENT="SELECT 'J_MHB_Broadcast_Message_Detail'||','||CAST(Count(*) AS VARCHAR (20))||','

AS SOURCE_STRING FROM
(
sel * from Edwci.MHB_Broadcast_Message_Detail  where dw_last_update_date_time(date)=current_date
 ) Q"

export AC_EXP_SQL_STATEMENT="SELECT 'J_MHB_Broadcast_Message_Detail'||','||CAST(Count(*) AS VARCHAR (20))||','
AS SOURCE_STRING FROM
(
SELECT 
RDC.RDC_SID AS RDC_SID
FROM EDWCI_STAGING.VWBroadcastMESSAGES A

INNER JOIN EDWCI_BASE_VIEWS.REF_MHB_REGIONAL_DATA_CENTER RDC
--ON OREPLACE(TRIM(A.DATABASENAME),'HEARTBEATDW_','')  = TRIM(RDC.RDC_DESC)
ON SUBSTR(TRIM(A.DATABASENAME),POSITION('_' IN TRIM(A.DATABASENAME))+1) = TRIM(RDC.RDC_DESC)

INNER JOIN EDWCI_BASE_VIEWS.MHB_USER USR
ON A.From_UserName = USR.USER_LOGIN_NAME 
AND USR.RDC_SID = RDC.RDC_SID
AND USR.Eff_To_Date = '9999-12-31'
 and USR.Active_DW_Ind = 'Y'
 
) Q"


#  @@END DMEXPRESS_EXPORTED_VARIABLES
#  End of Exported variables section
#   