/***************************************************************************************
S E C U R I T Y   V I E W
****************************************************************************************/

  CREATE OR REPLACE VIEW {{ params.param_hr_views_dataset_name }}.employee_action_detail AS SELECT
      a.employee_action_sid,
      a.eff_from_date,
      a.valid_from_date,
      a.valid_to_date,
      a.action_code,
      a.employee_sid,
      a.employee_num,
      a.action_sequence_num,
      a.action_from_date,
      a.action_to_date,
      a.from_auxiliary_status_code,
      a.from_dept_code,
      a.from_employee_pay_rate_amount,
      a.from_employee_work_schedule_code,
      a.from_job_code,
      a.from_location_code,
      a.from_overtime_plan_code,
      a.from_position_code,
      a.from_position_level_num,
      a.from_process_level_code,
      a.from_payment_frequency,
      a.from_payment_grade_code,
      a.from_payment_step_num,
      a.from_salary_class_code,
      a.from_schedule_code,
      a.from_standard_hour,
      a.from_supervisor_code,
      a.from_union_code,
      a.from_user_level,
      a.from_excemption_flag,
      a.from_expense_account_unit,
      a.from_expense_company,
      a.from_expense_sub_account_num,
      a.hr_code_desc,
      a.last_update_date,
      a.last_transfer_eff_date,
      a.reason_desc,
      a.to_payment_frequency,
      a.to_auxiliary_status_code,
      a.to_dept_code,
      a.to_employee_pay_rate_amt,
      a.to_employee_schedule_code,
      a.to_job_code,
      a.to_location_code,
      a.to_overtime_plan_code,
      a.to_position_code,
      a.to_position_level_num,
      a.to_process_level_code,
      a.to_pay_grade_code,
      a.to_pay_step_num,
      a.to_salary_class_code,
      a.to_schedule_code,
      a.to_standard_hour,
      a.to_supervisor_code,
      a.to_union_code,
      a.to_user_level,
      a.to_exemption_flag,
      a.to_expense_account_unit,
      a.to_expense_sub_account_num,
      a.transfer_termination_flag,
      a.to_expense_company_num,
      a.active_dw_ind,
      a.lawson_company_num,
      a.process_level_code,
      a.security_key_text,
      a.delete_ind,
      a.source_system_code,
      a.dw_last_update_date_time
    FROM
      {{ params.param_hr_base_views_dataset_name }}.employee_action_detail AS a
      INNER JOIN {{ params.param_hr_base_views_dataset_name }}.hr_secref_process_level AS c ON a.process_level_code = c.process_level_code
       AND a.lawson_company_num = c.lawson_company_num
       AND c.user_id = session_user()
  ;

