-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/apg_calc_output_old.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.apg_calc_output_old
(
  schema_id BIGNUMERIC(38) NOT NULL,
  apg_calc_output_id BIGNUMERIC(38) NOT NULL,
  calc_method_id NUMERIC(29) NOT NULL,
  calc_prfl_id NUMERIC(29),
  mon_acct_payer_calc_service_id BIGNUMERIC(38) NOT NULL,
  mon_acct_payer_calc_summary_id BIGNUMERIC(38) NOT NULL,
  cers_term_id BIGNUMERIC(38) NOT NULL,
  ce_service_id BIGNUMERIC(38) NOT NULL,
  ce_rule_id NUMERIC(29) NOT NULL,
  svc_date DATE,
  expt_pymt_amt NUMERIC(31, 2),
  code_grpr_vrsn_used STRING,
  adj_eapg_wgt NUMERIC(35, 6),
  eapg_pymt_amt NUMERIC(31, 2),
  eapg_wgt NUMERIC(35, 6),
  no_outlier_pymt_amt NUMERIC(31, 2),
  pymt_actn_cd STRING,
  pymt_pct NUMERIC(33, 4),
  pymt_amt NUMERIC(31, 2),
  svc_units_pd NUMERIC(29),
  proc_dscnt_pct_1 NUMERIC(33, 4),
  proc_dscnt_pct_2 NUMERIC(33, 4),
  proc_dscnt_pct_3 NUMERIC(33, 4),
  proc_max_units NUMERIC(29),
  proc_unit_calc_ind NUMERIC(29) DEFAULT NUMERIC '0',
  proc_rltv_wgt NUMERIC(35, 6),
  biltrl_dscnt_cd STRING,
  clm_prcs_cd STRING,
  sgnf_clinical_proc_csldtn_ind NUMERIC(29) DEFAULT NUMERIC '0',
  eapg_cd STRING,
  eapg_type STRING,
  eapg_category STRING,
  actn_cd STRING,
  chg_amt NUMERIC(31, 2),
  visit_id NUMERIC(29),
  modfr_cd_1 STRING,
  modfr_cd_2 STRING,
  modfr_cd_3 STRING,
  modfr_cd_4 STRING,
  modfr_cd_5 STRING,
  sgnf_proc_dscnt_cand_ind NUMERIC(29) DEFAULT NUMERIC '0',
  pkg_per_diem_ind NUMERIC(29) DEFAULT NUMERIC '0',
  pkg_ind NUMERIC(29) DEFAULT NUMERIC '0',
  schd_db_path STRING,
  proc_cd STRING,
  repeat_anclry_dscnt_ind NUMERIC(29) DEFAULT NUMERIC '0',
  sgnf_proc_csldtn_ind NUMERIC(29) DEFAULT NUMERIC '0',
  termnt_proc_dscnt_ind NUMERIC(29) DEFAULT NUMERIC '0',
  svc_units NUMERIC(29),
  user_key_1 STRING,
  user_key_2 STRING,
  visit_adj_eapg_wgt NUMERIC(35, 6),
  visit_no_outlier_pymt_amt NUMERIC(31, 2),
  visit_eapg_pymt_amt NUMERIC(31, 2),
  visit_full_eapg_wgt NUMERIC(35, 6),
  full_eapg_wgt NUMERIC(35, 6),
  clm_pymt_status_cd STRING,
  schd_eff_date DATE,
  schd_desc STRING,
  schd_exp_date DATE,
  rbmt_type_cd STRING,
  clm_pymt_amt NUMERIC(31, 2),
  creation_date DATETIME NOT NULL,
  creation_user STRING NOT NULL,
  modification_date DATETIME,
  modification_user STRING,
  rev_cd STRING,
  base_rate NUMERIC(31, 2),
  adjmt_fctr NUMERIC(34, 5),
  rule_type_id NUMERIC(29) NOT NULL,
  fee_file_id NUMERIC(29),
  state_file_id NUMERIC(29),
  covd_chg_amt NUMERIC(31, 2),
  recr_svc_ind NUMERIC(29),
  unassigned_cd STRING,
  agcy_edit_cd STRING,
  noncovd_chg_amt_rank1 NUMERIC(31, 2),
  noncovd_qty_rank1 NUMERIC(29),
  noncovd_chg_amt_rank2 NUMERIC(31, 2),
  noncovd_qty_rank2 NUMERIC(29),
  noncovd_chg_amt_rank3 NUMERIC(31, 2),
  noncovd_qty_rank3 NUMERIC(29),
  ancl_eapg_rt NUMERIC(31, 2),
  apec_otlr_cmpn_amt NUMERIC(31, 2),
  auto_rt_ehnc_splmt NUMERIC(31, 2),
  cost_to_chg_ratio NUMERIC(34, 5),
  eapg_wgt_cah NUMERIC(35, 6),
  grpr_vrsn NUMERIC(29),
  hosp_type STRING,
  jw_modfr_ind INT64,
  lab_pymt_amt NUMERIC(31, 2),
  li_adj_eapg_wgt NUMERIC(35, 6),
  li_alt_pymt_amt NUMERIC(31, 2),
  li_eapg_pymt_amt NUMERIC(31, 2),
  li_lab_pymt_amt NUMERIC(31, 2),
  li_proc_fee_amt NUMERIC(31, 2),
  li_rdst_chg_amt NUMERIC(31, 2),
  li_user_defn_adjmt_amt NUMERIC(31, 2),
  otlr_adj NUMERIC(34, 5),
  pape_pymt_amt NUMERIC(31, 2),
  prov_plcy_adj NUMERIC(34, 5),
  ttl_pymt_amt NUMERIC(31, 2),
  user_defn_adjmt_amt NUMERIC(31, 2),
  visit_apec_otlr_cmpn_amt NUMERIC(31, 2),
  visit_apec_pymt_amt NUMERIC(31, 2),
  visit_atp_cd STRING,
  visit_atp_pymt_amt NUMERIC(31, 2),
  pape_rt NUMERIC(31, 2),
  dw_last_update_date DATETIME,
  smart_act_red_fac_ind NUMERIC(29),
  hcd_dvc_addon_pymt_ind NUMERIC(29),
  smart_act_red_amt NUMERIC(31, 2),
  cost_otlr_pymt_amt NUMERIC(31, 2),
  li_cost_otlr_pymt_amt NUMERIC(31, 2),
  li_cost_otlr_thld_amt NUMERIC(31, 2),
  li_eapg_cost NUMERIC(31, 2),
  clm_rec_type_cd STRING,
  psych_base_rt NUMERIC(33, 4),
  rehab_base_rt NUMERIC(33, 4)
)
CLUSTER BY schema_id, apg_calc_output_id;
