-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/apg_grpr_output.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.apg_grpr_output_temp
(
  schema_id NUMERIC(29) NOT NULL,
  apg_grpr_output_id BIGNUMERIC(38) NOT NULL,
  coid STRING,
  pat_acct_num NUMERIC(29),
  charge_posting_date DATETIME,
  charge_code STRING,
  clm_rec_type_cd STRING,
  num_of_visits NUMERIC(29),
  eapg_cd STRING,
  eapg_category STRING,
  eapg_type STRING,
  pkg_ind NUMERIC(29) DEFAULT NUMERIC '0',
  sgnf_proc_dscnt_cand_ind NUMERIC(29) DEFAULT NUMERIC '0',
  sgnf_proc_csldtn_ind NUMERIC(29) DEFAULT NUMERIC '0',
  sgnf_clinical_proc_csldtn_ind NUMERIC(29) DEFAULT NUMERIC '0',
  pkg_per_diem_ind NUMERIC(29) DEFAULT NUMERIC '0',
  drug_304b_dscnt_ind NUMERIC(29) DEFAULT NUMERIC '0',
  actn_cd STRING,
  acuity_ind NUMERIC(29) DEFAULT NUMERIC '0',
  biltrl_dscnt_cd STRING,
  dvc_modfr_dscnt_cd STRING,
  dme_modfr_pres_cd STRING,
  visit_lines NUMERIC(29),
  max_units_allowed_svc NUMERIC(29),
  med_visit_diag_cd STRING,
  mue_max_units_allowed NUMERIC(29),
  visit_type_cd STRING,
  prvtv_svc_ind NUMERIC(29) DEFAULT NUMERIC '0',
  prof_svc_excl_ind NUMERIC(29) DEFAULT NUMERIC '0',
  recr_svc_ind NUMERIC(29) DEFAULT NUMERIC '0',
  repeat_anclry_dscnt_ind NUMERIC(29) DEFAULT NUMERIC '0',
  termnt_proc_dscnt_ind NUMERIC(29) DEFAULT NUMERIC '0',
  unassigned_cd STRING,
  svc_units NUMERIC(29),
  used_proc_cd STRING,
  svc_date DATE,
  visit_id NUMERIC(29),
  visit_prvtv_med_diag_pres_ind NUMERIC(29) DEFAULT NUMERIC '0',
  proc_cd_used_cnt NUMERIC(29),
  secn_diag_cd_used_cnt NUMERIC(29),
  prin_diag_cd_used STRING,
  visit_diag_cd_used STRING,
  secn_diag_cd_used STRING,
  code_grpr_vrsn_used STRING,
  mon_acct_chg_dtl_id BIGNUMERIC(38),
  mon_acct_code_id BIGNUMERIC(38),
  claim_code_id BIGNUMERIC(38),
  claim_charge_ub_id BIGNUMERIC(38),
  ce_patient_population_id NUMERIC(29),
  calc_meth_id NUMERIC(29) NOT NULL,
  mon_account_id BIGNUMERIC(38) DEFAULT NUMERIC '0' NOT NULL,
  creation_date DATETIME NOT NULL,
  creation_user STRING NOT NULL,
  modification_date DATETIME,
  modification_user STRING,
  chg_amt NUMERIC(31, 2),
  covd_chg_amt NUMERIC(31, 2),
  rev_cd STRING,
  modfr_cd_1 STRING,
  modfr_cd_2 STRING,
  modfr_cd_3 STRING,
  modfr_cd_4 STRING,
  modfr_cd_5 STRING,
  code_type STRING,
  calc_prfl_id NUMERIC(29),
  noncovd_chg_amt_rank1 NUMERIC(31, 2),
  noncovd_qty_rank1 NUMERIC(29),
  noncovd_chg_amt_rank2 NUMERIC(31, 2),
  noncovd_qty_rank2 NUMERIC(29),
  noncovd_chg_amt_rank3 NUMERIC(31, 2),
  noncovd_qty_rank3 NUMERIC(29),
  icd_vrsn_id NUMERIC(29),
  charge_claim_ind STRING,
  charge_code_ind STRING,
  extract_date DATETIME,
  jw_modfr_ind INT64,
  claim_id NUMERIC(29),
  pyr_id NUMERIC(29),
  dw_last_update_date DATETIME
)
CLUSTER BY schema_id, apg_grpr_output_id;
