-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_account_merge.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_account_merge
(
  patient_dw_id NUMERIC(29) NOT NULL,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  unit_num STRING,
  pat_acct_num NUMERIC(29),
  account_id BIGNUMERIC(38) NOT NULL,
  linked_pat_account_id BIGNUMERIC(38),
  patient_last_name STRING,
  patient_first_name STRING,
  patient_middle_name STRING,
  patient_name_suffix_text STRING,
  social_security_num STRING,
  medical_record_num STRING,
  admission_date_time DATETIME,
  discharge_date_time DATETIME,
  patient_birth_date DATE,
  patient_death_date DATE,
  admission_source_code STRING,
  admission_type_code STRING,
  financial_class_code STRING,
  gender_code STRING,
  hipps_code STRING,
  discharge_status_code INT64,
  billing_status_code STRING,
  special_bill_ind STRING,
  diag_code_admit STRING,
  cancel_bill_ind STRING,
  ca_extract_stop_ind STRING,
  reassignable_ind STRING,
  service_code STRING,
  final_bill_date DATE,
  ar_bill_thru_date DATE,
  visit_cnt INT64,
  patient_type_code STRING,
  cc_patient_type_id NUMERIC(29),
  account_status_code STRING,
  marital_status_code STRING,
  length_of_stay_days_num NUMERIC(32, 3),
  drg_code STRING,
  drg_type STRING,
  drg_version NUMERIC(29),
  cc_regroup_drg_code STRING,
  cc_regroup_drg_type STRING,
  cc_regroup_drg_version NUMERIC(29),
  cc_account_archive_ind STRING,
  birth_weight_amt INT64,
  pa_total_account_balance_amt NUMERIC(32, 3),
  total_charge_amt NUMERIC(32, 3),
  total_expected_reimb_amt NUMERIC(32, 3),
  total_patient_liability_amt NUMERIC(32, 3),
  total_payment_amt NUMERIC(32, 3),
  total_patient_payment_amt NUMERIC(32, 3),
  total_adjustment_amt NUMERIC(32, 3),
  total_billed_charges_amt NUMERIC(32, 3),
  financial_period_id NUMERIC(29),
  ipf_interrupted_stay_day INT64,
  pa_archive_ind STRING,
  pa_purge_ind STRING,
  updated_login_userid STRING,
  last_calc_date_time DATETIME,
  ins_maint_date DATE,
  icd10_drg_code STRING,
  icd10_drg_version_id NUMERIC(29),
  icd10_drg_severity_level_code STRING,
  pa_icd_version_desc STRING,
  create_date_time DATETIME,
  update_date_time DATETIME,
  dw_last_update_date_time DATETIME,
  source_system_code STRING,
  patient_noa_date DATE,
  archive_state_ind STRING
)
CLUSTER BY patient_dw_id;
