-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_account_payor_merge_stage.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_account_payor_merge_stage
(
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  iplan_order_num INT64 NOT NULL,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  unit_num STRING,
  pat_acct_num NUMERIC(29) NOT NULL,
  iplan_id INT64,
  employer_name STRING,
  insurance_group_name STRING,
  insurance_group_num_cd STRING,
  insured_name STRING,
  insured_gender_cd STRING,
  insured_birth_date DATE,
  payor_identification_num_cd STRING,
  authorization_cd STRING,
  billing_name STRING,
  billed_date DATE,
  billing_address_1 STRING,
  billing_address_2 STRING,
  billing_city_name STRING,
  billing_state_code STRING,
  billing_zip_code STRING,
  billing_phone_num_cd STRING,
  billing_contact_person_name STRING,
  billing_contact_email_name STRING,
  relation_to_insured_pat_cd STRING,
  drg_version STRING,
  pa_denial_date DATE,
  first_denial_date DATE,
  interest_stop_date DATE,
  work_queue_name STRING,
  rate_schedule_name STRING,
  calc_date DATE,
  calc_num INT64,
  calc_result_ind STRING,
  calc_base_choice_resolved_ind STRING,
  calc_lock_ind STRING,
  pa_autm_post_ind STRING,
  apc_group_ind STRING,
  eligible_ind STRING,
  account_calc_situation_ind STRING,
  allow_contract_code_change_ind STRING,
  change_claim_trigger_ind STRING,
  manual_trigger_ind STRING,
  life_check_eligible_ind STRING,
  pa_financial_class_code STRING,
  bill_reason_code STRING,
  external_appeal_code STRING,
  total_exp_payment_amt NUMERIC(32, 3),
  total_payment_amt NUMERIC(32, 3) NOT NULL,
  total_denial_amt NUMERIC(32, 3) NOT NULL,
  total_pat_responsibility_amt NUMERIC(32, 3) NOT NULL,
  est_pat_responsibility_amt NUMERIC(32, 3) NOT NULL,
  actual_pat_responsibility_amt NUMERIC(32, 3) NOT NULL,
  total_exp_contractual_amt NUMERIC(32, 3) NOT NULL,
  total_adjustment_amt NUMERIC(32, 3) NOT NULL,
  total_variance_adjustment_amt NUMERIC(32, 3) NOT NULL,
  current_exp_payment_amt NUMERIC(32, 3) NOT NULL,
  current_exp_contractual_amt NUMERIC(32, 3) NOT NULL,
  prof_covered_charge_amt NUMERIC(32, 3) NOT NULL,
  prof_exp_payment_amt NUMERIC(32, 3) NOT NULL,
  pa_prof_part_b_charge_amt NUMERIC(32, 3) NOT NULL,
  pa_blood_deductible_amt NUMERIC(32, 3) NOT NULL,
  sqstrtn_reduction_amt NUMERIC(32, 3) NOT NULL,
  pa_coinsurance_amt NUMERIC(32, 3) NOT NULL,
  autm_post_amt NUMERIC(32, 3) NOT NULL,
  coinsurance_amt NUMERIC(32, 3) NOT NULL,
  copay_amt NUMERIC(32, 3) NOT NULL,
  deductible_amt NUMERIC(32, 3) NOT NULL,
  covered_charge_instu_amt NUMERIC(32, 3) NOT NULL,
  cmpt_method_choice_id NUMERIC(29),
  calc_base_id NUMERIC(29),
  calc_base_survivor_id BIGNUMERIC(38),
  reason_id BIGNUMERIC(38),
  account_payor_status_id BIGNUMERIC(38),
  appeal_id BIGNUMERIC(38),
  cers_profile_id BIGNUMERIC(38),
  capping_method_id BIGNUMERIC(38),
  cers_term_id BIGNUMERIC(38),
  project_id BIGNUMERIC(38),
  account_payor_id BIGNUMERIC(38),
  creation_date DATE,
  update_date DATE,
  prepay_mgd_care_sw INT64,
  ip_provider_num STRING,
  op_provider_num STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME,
  billing_fax_num STRING,
  payer_type_code STRING
)
CLUSTER BY patient_dw_id, payor_dw_id, iplan_order_num;
