-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_denial_eow.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_denial_eow
(
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  report_run_date DATE NOT NULL,
  report_end_date DATE NOT NULL,
  iplan_insurance_order_num INT64 NOT NULL,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  unit_num STRING NOT NULL,
  pat_acct_num NUMERIC(29) NOT NULL,
  iplan_id INT64 NOT NULL,
  denial_status_code STRING,
  patient_type_code STRING,
  patient_financial_class_code INT64,
  payor_financial_class_code INT64,
  appeal_origination_date DATE,
  appeal_level_origination_date DATE,
  disposition_num INT64,
  appeal_level_num INT64,
  beginning_balance_amt NUMERIC(32, 3),
  beginning_balance_cnt INT64,
  beginning_appeal_amt NUMERIC(32, 3),
  new_denial_account_amt NUMERIC(32, 3),
  new_denial_account_cnt INT64,
  unworked_conversion_amt NUMERIC(32, 3),
  unworked_new_accounts_cnt INT64,
  not_true_denial_amt NUMERIC(32, 3),
  write_off_denial_account_amt NUMERIC(32, 3),
  overturned_account_amt NUMERIC(32, 3),
  corrections_account_amt NUMERIC(32, 3),
  appeal_closing_date DATE,
  trans_next_party_amt NUMERIC(32, 3),
  ending_balance_amt NUMERIC(32, 3),
  resolved_accounts_cnt INT64,
  total_charge_amt NUMERIC(32, 3),
  attending_physician_name_id STRING,
  account_balance_amt NUMERIC(32, 3),
  discharge_date DATE,
  service_code STRING,
  medical_record_num STRING,
  last_update_hca_3_4_id STRING,
  last_update_date DATE,
  work_again_date DATE,
  appeal_deadline_date DATE,
  denied_charges_amt NUMERIC(32, 3),
  cash_adjustment_amt NUMERIC(32, 3),
  ca_adjustment_amt NUMERIC(32, 3),
  root_cause STRING,
  root_cause_desc STRING,
  denial_code_category STRING,
  disposition_code STRING,
  appeal_num INT64,
  sequence_number INT64,
  appeal_code STRING,
  appeal_code_desc STRING,
  schema_id INT64,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME,
  vendor_cd STRING
)
CLUSTER BY patient_dw_id;
