-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_external_data_cdc.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_external_data_cdc
(
  concuity_schema STRING,
  unit_num STRING,
  pat_acct_num NUMERIC(29),
  iplan_id INT64,
  iplan_order_num INT64,
  esl_level_1_desc STRING,
  esl_level_2_desc STRING,
  esl_level_3_desc STRING,
  esl_level_4_desc STRING,
  esl_level_5_desc STRING,
  chois_product_line_code STRING,
  chois_product_line_desc STRING,
  drg_medical_surgical_ind STRING,
  apr_drg_code STRING,
  apr_drg_grouper_name STRING,
  apr_severity_of_illness_desc STRING,
  apr_risk_of_mortality_desc STRING,
  payer_type_code STRING,
  sub_payor_group_id STRING,
  cond_code_xf_xg_ind STRING,
  cond_code_nu_ind STRING,
  cond_code_ne_ind STRING,
  cond_code_ns_ind STRING,
  cond_code_np_ind STRING,
  cond_code_no_ind STRING,
  treatment_authorization_num STRING,
  denial_in_midas_status STRING,
  midas_date_of_denial DATE,
  all_days_approved_ind STRING,
  ptp_performed STRING,
  cm_xf_ind STRING,
  cm_xg_ind STRING,
  cm_last_xf_code_applied_date DATE,
  cm_last_xg_code_applied_date DATE,
  midas_acct_num STRING,
  last_appeal_date DATE,
  last_appeal_status STRING,
  last_appeal_employee_id STRING,
  last_appeal_employee_name STRING,
  status_cause_name STRING,
  last_conc_review_disp STRING,
  midas_principal_payer_auth_num STRING,
  midas_principal_pyr_auth_type STRING,
  cm_last_iq_revi_crit_met_desc STRING,
  cm_last_iq_review_version_desc STRING,
  cm_last_iq_review_subset_desc STRING,
  pdu_determination_reason_desc STRING,
  ins1_payor_balance_amt NUMERIC(32, 3),
  ins2_payor_balance_amt NUMERIC(32, 3),
  ins3_payor_balance_amt NUMERIC(32, 3),
  first_doc_request_mr_date DATE,
  last_doc_request_mr_date DATE,
  first_doc_sent_mr_date DATE,
  last_doc_sent_mr_date DATE,
  first_doc_request_ib_date DATE,
  last_doc_request_ib_date DATE,
  first_doc_sent_ib_date DATE,
  last_doc_sent_ib_date DATE,
  first_doc_request_date DATE,
  last_doc_request_date DATE,
  first_doc_sent_date DATE,
  last_doc_sent_date DATE,
  first_doc_received_date DATE,
  last_doc_received_date DATE,
  first_doc_approved_date DATE,
  last_doc_approved_date DATE,
  first_doc_denied_date DATE,
  last_doc_denied_date DATE,
  covid_positive_flag STRING,
  refund_amt NUMERIC(32, 3),
  refund_create_date DATE,
  refund_requested_by STRING,
  patient_refund_amt NUMERIC(32, 3),
  patient_refund_create_date DATE,
  patient_refund_requested_by STRING,
  credit_status STRING,
  discrepancy_source_desc STRING,
  reimbursement_impact_desc STRING,
  discrepancy_date_time DATETIME,
  request_date_time DATETIME,
  reprocess_reason_text STRING,
  status_desc STRING,
  split_bill_ind STRING,
  last_scrted_appl_date_time DATETIME,
  scripted_overpayment_desc STRING,
  last_letter_sent_date_time DATETIME,
  account_id BIGNUMERIC(38),
  account_payor_id BIGNUMERIC(38),
  org_id NUMERIC(29),
  first_ptp_completed_date DATETIME,
  first_strength_of_case STRING,
  last_ptp_completed_date DATETIME,
  last_strength_of_case STRING,
  total_ptp_closure_status_completed INT64,
  total_midnights INT64,
  total_inhouse_midnights NUMERIC(32, 3),
  gov_sec_tert_iplan STRING,
  takeback_follow_up_ltr_ind STRING,
  patient_refund_last_update_date_time DATETIME,
  payer_refund_last_update_date_time DATETIME,
  tmr_ma_ereq_auto_nonbillable_review_ind STRING,
  presentation_date DATE,
  artiva_claim_num STRING,
  dna_clinical_rationale_1 STRING,
  dna_clinical_rationale_2 STRING,
  dna_clinical_rationale_3 STRING,
  dna_clinical_rationale_4 STRING,
  dna_clinical_rationale_5 STRING,
  dna_clinical_rationale_6 STRING,
  dna_clinical_rationale_6_notes STRING,
  dna_ip_only_proc_waterpark_ind STRING,
  dna_ip_only_proc_user_ind STRING,
  psr_agree_disagree_flag STRING,
  first_psr_note_date_time TIMESTAMP,
  last_psr_note_date_time TIMESTAMP,
  dw_last_update_date_time DATETIME
)
CLUSTER BY concuity_schema, unit_num, pat_acct_num, iplan_id;