-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_eor_eapg_calculation_merge.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_eor_eapg_calculation_merge
(
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  insurance_order_num INT64 NOT NULL,
  eor_log_date DATE NOT NULL,
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL,
  eff_from_date DATE NOT NULL,
  apg_calc_num BIGNUMERIC(38) NOT NULL,
  adjustment_eapg_wgt NUMERIC(35, 6),
  adjustment_factor_qty NUMERIC(34, 5),
  agency_edit_code STRING,
  ancillary_eapg_rate_amt NUMERIC(32, 3),
  auto_rate_ehnc_splmt_amt NUMERIC(32, 3),
  base_rate_amt NUMERIC(32, 3),
  calc_method_id BIGNUMERIC(38),
  calc_profile_id BIGNUMERIC(38),
  ce_rule_id BIGNUMERIC(38),
  ce_service_id BIGNUMERIC(38),
  cers_term_id BIGNUMERIC(38),
  claim_payment_status_code STRING,
  claim_process_code STRING,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  cost_to_charge_ratio NUMERIC(34, 5),
  creation_date DATE,
  eapg_action_code STRING,
  eapg_bilateral_discount_code STRING,
  eapg_cah_wgt NUMERIC(35, 6),
  eapg_category_code STRING,
  eapg_code STRING,
  eapg_code_version_text STRING,
  eapg_payment_action_code STRING,
  eapg_unassigned_code STRING,
  eapg_type_code STRING,
  eapg_wgt NUMERIC(35, 6),
  fee_file_id BIGNUMERIC(38),
  full_eapg_wgt NUMERIC(35, 6),
  grouper_version_code STRING,
  hospital_type_text STRING,
  icd_version_desc STRING,
  iplan_id INT64,
  jw_modifier_ind STRING,
  lab_payment_amt NUMERIC(32, 3),
  li_adj_eapg_wgt NUMERIC(35, 6),
  li_alternate_payment_amt NUMERIC(32, 3),
  li_eapg_payment_amt NUMERIC(32, 3),
  li_lab_payment_amt NUMERIC(32, 3),
  li_procedure_fee_amt NUMERIC(32, 3),
  li_redistributed_charge_amt NUMERIC(32, 3),
  li_user_defined_adj_amt NUMERIC(32, 3),
  modifier_1_code STRING,
  modifier_2_code STRING,
  modifier_3_code STRING,
  modifier_4_code STRING,
  modifier_5_code STRING,
  no_outlier_payment_amt NUMERIC(32, 3),
  noncov_charge_rank_1_amt NUMERIC(32, 3),
  noncov_charge_rank_2_amt NUMERIC(32, 3),
  noncov_charge_rank_3_amt NUMERIC(32, 3),
  noncov_rank_1_qty INT64,
  noncov_rank_2_qty INT64,
  noncov_rank_3_qty INT64,
  outlier_adj_amt NUMERIC(34, 5),
  pape_outlier_component_amt NUMERIC(32, 3),
  pape_payment_amt NUMERIC(32, 3),
  pape_rate_amt NUMERIC(32, 3),
  pat_acct_num NUMERIC(29),
  payment_pct NUMERIC(33, 4),
  pkg_ind STRING,
  pkg_per_diem_ind STRING,
  procedure_code STRING,
  provider_policy_adj_amt NUMERIC(34, 5),
  reimbursement_type_code STRING,
  repeat_anclry_discount_code STRING,
  revenue_code STRING,
  service_date DATE,
  service_unit_paid_qty INT64,
  service_unit_qty INT64,
  sgnf_clnc_proc_csdt_ind STRING,
  sgnf_proc_csdt_ind STRING,
  sgnf_proc_dc_cand_ind STRING,
  state_file_id BIGNUMERIC(38),
  termn_proc_dc_ind STRING,
  total_charge_amt NUMERIC(32, 3),
  total_claim_payment_amt NUMERIC(32, 3),
  total_covered_charge_amt NUMERIC(32, 3),
  total_eapg_payment_amt NUMERIC(32, 3),
  total_expected_payment_amt NUMERIC(32, 3),
  total_payment_amt NUMERIC(32, 3),
  unit_num STRING,
  user_defined_adj_amt NUMERIC(32, 3),
  visit_adj_eapg_wgt NUMERIC(35, 6),
  visit_adj_pape_otlr_cmpnt_amt NUMERIC(32, 3),
  visit_adj_pape_payment_amt NUMERIC(32, 3),
  visit_atp_code STRING,
  visit_atp_payment_amt NUMERIC(32, 3),
  visit_eapg_payment_amt NUMERIC(32, 3),
  visit_full_eapg_wgt NUMERIC(35, 6),
  visit_id BIGNUMERIC(38),
  visit_no_outlier_payment_amt NUMERIC(32, 3),
  smart_act_red_fac_ind INT64,
  hcd_dvc_add_on_pymt_ind INT64,
  smart_actl_red_amt NUMERIC(32, 3),
  cost_otlr_pymt_amt NUMERIC(32, 3),
  li_cost_otlr_pymt_amt NUMERIC(32, 3),
  li_cost_otlr_thld_amt NUMERIC(32, 3),
  li_eapg_cost NUMERIC(32, 3),
  rehab_base_rate NUMERIC(35, 6),
  psych_base_rate NUMERIC(35, 6),
  clm_rec_type_code STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)
CLUSTER BY patient_dw_id;
