-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_eor_stg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_eor_stg
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  iplan_insurance_order_num INT64 NOT NULL,
  eor_log_date DATE NOT NULL,
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL,
  eff_from_date DATE NOT NULL,
  unit_num STRING NOT NULL,
  pat_acct_num NUMERIC(29),
  iplan_id INT64,
  financial_class_code NUMERIC(29),
  final_bill_date DATE,
  ar_bill_thru_date DATE,
  ar_bill_drop_date DATE,
  contract_begin_date DATE,
  eor_transaction_date DATE,
  bill_reason_code STRING,
  eor_drg_code STRING,
  cc_drg_code STRING,
  cc_drg_weight NUMERIC(35, 6),
  eor_hipps_code STRING,
  cc_cmg_code STRING,
  cc_cmg_weight NUMERIC(35, 6),
  eor_covered_days_num INT64,
  eor_total_charge_amt NUMERIC(32, 3),
  expected_insurance_payment_amt NUMERIC(32, 3),
  pat_resp_non_covered_chg_amt NUMERIC(32, 3),
  total_actual_pat_resp_amt NUMERIC(32, 3),
  eor_non_covered_charge_amt NUMERIC(32, 3),
  eor_cmptd_reimbursement_amt NUMERIC(32, 3),
  eor_deductible_amt NUMERIC(32, 3),
  eor_coinsurance_amt NUMERIC(32, 3),
  eor_copay_amt NUMERIC(32, 3),
  eor_insurance_payment_amt NUMERIC(32, 3),
  eor_contractual_allowance_amt NUMERIC(32, 3),
  eor_cost_of_service_amt NUMERIC(32, 3),
  month_13_ind STRING,
  outlier_code STRING,
  auto_post_amt NUMERIC(32, 3),
  auto_post_ind STRING,
  drg_table_id STRING,
  opps_ind STRING,
  inpatient_outpatient_ind STRING,
  visit_count INT64,
  eor_gross_reimbursement_amt NUMERIC(32, 3),
  eor_net_reimbursement_amt NUMERIC(32, 3),
  eor_non_bill_charge_amt NUMERIC(32, 3),
  sqstrtn_red_amt NUMERIC(32, 3),
  model_name STRING,
  project_desc STRING,
  eor_ipf_interrupted_day_stay NUMERIC(29),
  calc_success_ind STRING,
  latest_calc_ind STRING,
  interim_bill_ind STRING,
  financial_period_id NUMERIC(29),
  reason_id NUMERIC(29),
  calc_id BIGNUMERIC(38),
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)

CLUSTER BY company_code, coid, patient_dw_id, payor_dw_id;
