-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_eor_eapg_grouper_stg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_eor_eapg_grouper_stg
(
  patient_dw_id NUMERIC(29) NOT NULL,
  apg_grouper_num BIGNUMERIC(38) NOT NULL,
  action_code STRING,
  calc_method_id BIGNUMERIC(38),
  calc_profile_id BIGNUMERIC(38),
  charge_claim_ind STRING,
  charge_code_desc STRING,
  charge_ind_code STRING,
  charge_posted_date_time DATETIME,
  code_type STRING,
  coid STRING NOT NULL,
  company_code STRING,
  creation_date_time DATETIME NOT NULL,
  drug_304b_dc_ind STRING,
  eapg_action_code STRING,
  eapg_bilateral_discount_code STRING,
  eapg_category_code STRING,
  eapg_code STRING,
  eapg_code_version_text STRING,
  eapg_type_code STRING,
  eapg_unassigned_code STRING,
  eapg_visit_type_code STRING,
  icd_version_desc STRING,
  jw_modifier_ind STRING,
  med_visit_diag_code STRING,
  modifier_1_code STRING,
  modifier_2_code STRING,
  modifier_3_code STRING,
  modifier_4_code STRING,
  modifier_5_code STRING,
  non_cov_charge_rank_1_amt NUMERIC(32, 3),
  non_cov_charge_rank_2_amt NUMERIC(32, 3),
  non_cov_charge_rank_3_amt NUMERIC(32, 3),
  non_cov_rank_1_qty INT64,
  non_cov_rank_2_qty INT64,
  non_cov_rank_3_qty INT64,
  pat_acct_num NUMERIC(29) NOT NULL,
  pkg_ind STRING,
  pkg_per_diem_ind STRING,
  principal_diag_code STRING,
  proc_code_used_qty INT64,
  repeat_ancl_dc_ind INT64,
  revenue_code STRING,
  secn_diag_code_used_qty INT64,
  secn_diag_used_code_desc STRING,
  service_unit_qty INT64,
  service_date DATE,
  sgnf_clinc_proc_csdt_ind STRING,
  sgnf_proc_csdt_ind STRING,
  sgnf_proc_dc_cand_ind STRING,
  termn_proc_dc_ind STRING,
  total_charge_amt NUMERIC(32, 3),
  total_covered_charge_amt NUMERIC(32, 3),
  unit_num STRING,
  used_proc_code STRING,
  used_visit_diag_code_desc STRING,
  visit_cnt INT64,
  visit_id BIGNUMERIC(38),
  visit_line_qty INT64,
  visit_preventive_med_diag_ind STRING,
  source_system_code STRING,
  dw_last_update_date_time DATETIME
)
CLUSTER BY patient_dw_id, apg_grouper_num;
