-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_gr_eom.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_gr_eom
(
  patient_dw_id NUMERIC(29) NOT NULL,
  report_name STRING NOT NULL,
  period_end_date DATE NOT NULL,
  report_run_date_time DATETIME NOT NULL,
  reporting_period STRING NOT NULL,
  section_name STRING,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  facility_name STRING,
  unit_num STRING,
  pat_acct_num NUMERIC(29) NOT NULL,
  patient_name STRING,
  rate_schedule_name STRING,
  section_month STRING,
  cost_report_year STRING,
  account_status_code STRING,
  auto_posted_flag STRING,
  cmg_code STRING,
  drg_code STRING,
  ra_drg_code STRING,
  cmg_weight_amt NUMERIC(32, 3),
  drg_weight_amt NUMERIC(32, 3),
  prorated_drg_weight_amt NUMERIC(32, 3),
  exp_hipps_cmg_code STRING,
  ra_hipps_cmg_code STRING,
  var_drg_flag STRING,
  var_cmg_flag STRING,
  discharge_admit_date DATE,
  claim_submit_date DATE,
  ra_payment_date DATE,
  covered_days_los_cnt INT64,
  days_billed_cnt INT64,
  discharge_days_cnt INT64,
  ra_covered_days_cnt INT64,
  remit_cnt INT64,
  var_covered_days_cnt INT64,
  account_balance_amt NUMERIC(32, 3),
  accrued_capital_subtotal_amt NUMERIC(32, 3),
  accrued_operating_subtotal_amt NUMERIC(32, 3),
  accrued_payment_amt NUMERIC(32, 3),
  apc_charges_amt NUMERIC(32, 3),
  apc_payment_amt NUMERIC(32, 3),
  drg_arithmetic_los_amt NUMERIC(32, 3),
  capital_payment_subtotal_amt NUMERIC(32, 3),
  cmac_charge_amt NUMERIC(32, 3),
  cmac_payment_amt NUMERIC(32, 3),
  cmg_payment_amt NUMERIC(32, 3),
  coinsurance_deductible_amt NUMERIC(32, 3),
  computed_reimb_amt NUMERIC(32, 3),
  cost_outlier_payment_amt NUMERIC(32, 3),
  covered_charges_amt NUMERIC(32, 3),
  drg_payment_amt NUMERIC(32, 3),
  ect_payment_amt NUMERIC(32, 3),
  education_payment_amt NUMERIC(32, 3),
  fee_based_payment_amt NUMERIC(32, 3),
  idme_payment_amt NUMERIC(32, 3),
  lab_charge_amt NUMERIC(32, 3),
  lab_payment_amt NUMERIC(32, 3),
  lip_payment_amt NUMERIC(32, 3),
  non_covered_charges_amt NUMERIC(32, 3),
  operating_drg_payment_amt NUMERIC(32, 3),
  operating_dsh_amt NUMERIC(32, 3),
  operating_outlier_amt NUMERIC(32, 3),
  operating_cost_outlier_amt NUMERIC(32, 3),
  other_service_charge_amt NUMERIC(32, 3),
  other_service_payment_amt NUMERIC(32, 3),
  outlier_payment_amt NUMERIC(32, 3),
  payment_adj_amt NUMERIC(32, 3),
  ra_coinsurance_amt NUMERIC(32, 3),
  ra_contractual_amt NUMERIC(32, 3),
  ra_covered_charge_amt NUMERIC(32, 3),
  ra_deductible_amt NUMERIC(32, 3),
  ra_drg_amt NUMERIC(32, 3),
  ra_idme_amt NUMERIC(32, 3),
  ra_lab_payment_amt NUMERIC(32, 3),
  ra_operating_dsh_amt NUMERIC(32, 3),
  ra_operating_idme_amt NUMERIC(32, 3),
  ra_operating_outlier_amt NUMERIC(32, 3),
  ra_outlier_amt NUMERIC(32, 3),
  ra_therapy_payment_amt NUMERIC(32, 3),
  ra_total_capital_amt NUMERIC(32, 3),
  ra_total_payment_amt NUMERIC(32, 3),
  replace_device_reduction_amt NUMERIC(32, 3),
  rug_payment_amt NUMERIC(32, 3),
  sequestration_amt NUMERIC(32, 3),
  short_stay_outlier_payment_amt NUMERIC(32, 3),
  tech_add_on_amt NUMERIC(32, 3),
  tech_add_on_payment_amt NUMERIC(32, 3),
  therapy_charge_amt NUMERIC(32, 3),
  therapy_payment_amt NUMERIC(32, 3),
  total_charge_amt NUMERIC(32, 3),
  total_expected_payment_amt NUMERIC(32, 3),
  total_opr_cptl_payment_amt NUMERIC(32, 3),
  total_payment_amt NUMERIC(32, 3),
  transfer_payment_amt NUMERIC(32, 3),
  var_coinsurance_amt NUMERIC(32, 3),
  var_contractual_amt NUMERIC(32, 3),
  var_covered_charges_amt NUMERIC(32, 3),
  var_deductible_amt NUMERIC(32, 3),
  var_imed_educ_amt NUMERIC(32, 3),
  var_lab_payment_amt NUMERIC(32, 3),
  var_operating_dsh_amt NUMERIC(32, 3),
  var_operating_ime_amt NUMERIC(32, 3),
  var_operating_outlier_amt NUMERIC(32, 3),
  var_outlier_amt NUMERIC(32, 3),
  var_therapy_payment_amt NUMERIC(32, 3),
  var_total_capital_amt NUMERIC(32, 3),
  var_total_payment_amt NUMERIC(32, 3),
  dw_last_update_date_time DATETIME,
  source_system_code STRING
)

CLUSTER BY patient_dw_id, report_name, report_run_date_time;
