-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cc_patient_account_audit_stg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cc_patient_account_audit_stg
(
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  unit_num STRING,
  pat_acct_num NUMERIC(29) NOT NULL,
  iplan_id INT64,
  pat_acct_audit_id BIGNUMERIC(38),
  acct_payor_id BIGNUMERIC(38),
  claim_num STRING,
  record_id INT64,
  record_type_txt STRING,
  corp_control_txt STRING,
  ssc_control_txt STRING,
  corp_status_date DATE,
  audit_eligibility_txt STRING,
  audit_status_txt STRING,
  pre_audit_type_txt STRING,
  post_audit_type_txt STRING,
  other_audit_type_desc STRING,
  audit_status_date DATE,
  prev_audit_drg_nm STRING,
  post_audit_drg_nm STRING,
  payer_of_audit_txt STRING,
  audit_schedule_date DATE,
  expt_audit_fee_amt NUMERIC(31, 2),
  act_audit_fee_coll_amt NUMERIC(31, 2),
  audit_location_txt STRING,
  final_audit_outcome_txt STRING,
  work_again_date DATE,
  service_start_date DATE,
  service_end_date DATE,
  corp_status_desc STRING,
  addl_project_desc STRING,
  finding_letter_result_txt STRING,
  initiation_date DATE,
  letter_date DATE,
  response_date DATE,
  mr_trk_id STRING,
  mr_req_txt STRING,
  mr_rls_req_to_roi_date DATE,
  mr_rls_method_txt STRING,
  mr_rls_date DATE,
  mr_miss_notf_date DATE,
  miss_doc_req_txt STRING,
  payer_drg_code STRING,
  payer_ref_id STRING,
  risk_amt NUMERIC(31, 2),
  disc_amt NUMERIC(31, 2),
  refund_req_amt NUMERIC(31, 2),
  refund_amt NUMERIC(31, 2),
  refund_req_reason_txt STRING,
  refund_status_txt STRING,
  refund_status_date DATE,
  final_refund_outcome_txt STRING,
  creation_date DATE,
  creation_user_id STRING,
  modification_date DATE,
  modification_user_id STRING,
  map_to_record_type_txt STRING,
  map_to_record_id INT64,
  refund_prcs_tool_status_txt STRING,
  source_system_code STRING NOT NULL,
  dw_last_update_date_time DATETIME NOT NULL
)
CLUSTER BY patient_dw_id, payor_dw_id, pat_acct_audit_id;
