-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cers_term.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cers_term_temp
(
  id NUMERIC(29) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  cers_profile_id NUMERIC(29) NOT NULL,
  model_name STRING,
  effective_date_begin DATE NOT NULL,
  effective_date_end DATE,
  effective_date_method_id NUMERIC(29) NOT NULL,
  cers_profile_id_comparison NUMERIC(29),
  comparison_calc_method_id NUMERIC(29),
  comparison_calc_modifier NUMERIC(33, 4),
  is_model NUMERIC(29) NOT NULL,
  user_id_owner NUMERIC(29),
  inpatient_reimb_method_id NUMERIC(29) NOT NULL,
  outpatient_reimb_method_id NUMERIC(29) NOT NULL,
  asc_ranking_method_id NUMERIC(29),
  network_admin_fee_method_id NUMERIC(29),
  network_admin_fee_rate NUMERIC(31, 2),
  maximum_rank_to_calculate NUMERIC(29),
  is_validated NUMERIC(29) NOT NULL,
  date_validated DATE,
  validated_by NUMERIC(29),
  generate_contractuals NUMERIC(29) NOT NULL,
  generate_account_calc_detail NUMERIC(29) NOT NULL,
  drg_calculation_method_id NUMERIC(29),
  drg_type STRING,
  drg_breakout_transfer NUMERIC(29),
  drg_breakout_expired NUMERIC(29),
  drg_breakout_against_medadvice NUMERIC(29),
  gvt_base_rate NUMERIC(35, 6),
  gvt_capital_method_id NUMERIC(29),
  gvt_incl_dsh_ime_to_cost_outl NUMERIC(29),
  gvt_labor_rate NUMERIC(35, 6),
  gvt_wage_index NUMERIC(35, 6),
  gvt_nonlabor_index NUMERIC(35, 6),
  gvt_capital_federal_rate NUMERIC(35, 6),
  gvt_geographical_factor NUMERIC(35, 6),
  gvt_urban_add_on_factor NUMERIC(35, 6),
  gvt_cost_of_liv_addon_factor NUMERIC(35, 6),
  gvt_federal_percent NUMERIC(35, 6),
  gvt_hospital_rate NUMERIC(35, 6),
  gvt_new_capital_rate NUMERIC(35, 6),
  gvt_disp_share_oper_adj NUMERIC(37, 8),
  gvt_disp_share_capital_adj NUMERIC(37, 8),
  gvt_ind_med_edu_oper_adj NUMERIC(37, 8),
  gvt_ind_med_edu_capital_adj NUMERIC(37, 8),
  gvt_oper_cost_charge_ratio NUMERIC(35, 6),
  gvt_capital_cost_charge_ratio NUMERIC(35, 6),
  gvt_drg_threshold_adj NUMERIC(35, 6),
  gvt_labor_share NUMERIC(35, 6),
  gvt_short_stay_factor NUMERIC(35, 6),
  gvt_dispropor_share_reduc_adj NUMERIC,
  gvt_oper_cost_of_liv_adj NUMERIC(35, 6),
  ce_apc_profile_id NUMERIC(29),
  apc_federal_rate NUMERIC(35, 6),
  apc_wage_index NUMERIC(35, 6),
  apc_labor_percent NUMERIC(35, 6),
  apc_cost_charge_ratio NUMERIC(35, 6),
  apc_cost_threshold NUMERIC(35, 6),
  apc_cost_outlier_percent NUMERIC(35, 6),
  apc_pro_rata_adjustment NUMERIC(35, 6),
  apc_coinsurance_limit NUMERIC(31, 2),
  apc_deductible NUMERIC(31, 2),
  apc_is_deductible_met NUMERIC(29),
  ce_apg_profile_id NUMERIC(29),
  apg_maximum_groups NUMERIC(29),
  apg_federal_rate NUMERIC(31, 2),
  apg_wage_index NUMERIC(31, 2),
  apg_federal_percent NUMERIC(31, 2),
  apg_hospital_rate NUMERIC(31, 2),
  apg_case_mix_index NUMERIC(35, 6),
  apg_disp_share_adjustment NUMERIC(35, 6),
  apg_ind_med_edu_adjustment NUMERIC(35, 6),
  hipps_labor_share NUMERIC(35, 6),
  hipps_non_labor_share NUMERIC(35, 6),
  hipps_area_wage_index NUMERIC(35, 6),
  hipps_rural_adjustment NUMERIC(35, 6),
  hipps_low_income_patient_adj NUMERIC(35, 6),
  hipps_disp_share_adjustment NUMERIC(35, 6),
  hipps_transfer_adjustment NUMERIC(35, 6),
  hipps_loss_threshold NUMERIC(31, 2),
  hipps_outlier_percent NUMERIC(35, 6),
  hipps_cost_charge_ratio NUMERIC(35, 6),
  hipps_short_stay_limit NUMERIC(35, 6),
  date_created DATE NOT NULL,
  date_updated DATE,
  updated_by STRING NOT NULL,
  user_id_updater NUMERIC(29),
  status_id NUMERIC(29),
  apg_uses_similar_apg_calc NUMERIC(29),
  apg_federal_adjustment NUMERIC(31, 2),
  ce_profile_fee_schedule_id NUMERIC(29),
  cers_parent_term_id NUMERIC(29),
  gvt_include_scp NUMERIC(29) NOT NULL,
  gvt_scp_rate NUMERIC(35, 6),
  apc_fixed_threshold NUMERIC(31, 2),
  drg_version NUMERIC(29),
  ce_ipf_profile_id NUMERIC(29),
  ipf_labor_share_amount NUMERIC(35, 6),
  ipf_nonlabor_share_amount NUMERIC(35, 6),
  ipf_labor_share_percent NUMERIC(35, 6),
  ipf_wage_index NUMERIC(35, 6),
  ipf_teaching_adj_factor NUMERIC(35, 6),
  ipf_rural_adj_factor NUMERIC(35, 6),
  ipf_cola_adj_factor NUMERIC(35, 6),
  ipf_include_fsc_in_outlier NUMERIC(29),
  ipf_include_fsa_in_outlier NUMERIC(29),
  ipf_fixed_loss_amount NUMERIC(35, 6),
  ipf_cost_charge_ratio NUMERIC(35, 6),
  ipf_tefra_amount NUMERIC(35, 6),
  ipf_transition_calc_method NUMERIC(29),
  ipf_pps_federal_percent NUMERIC(35, 6),
  ipf_tefra_hospital_percent NUMERIC(35, 6),
  drg_expired_profile_id NUMERIC(29),
  drg_transfer_profile_id NUMERIC(29),
  drg_ama_profle_id NUMERIC(29),
  gvt_noscaasotc_adjustment NUMERIC(37, 8),
  is_xfer_drg_capped_to_std_rate NUMERIC(29) DEFAULT NUMERIC '1',
  prof_reimb_method_id NUMERIC(29),
  fac_pos NUMERIC(29),
  nfac_pos NUMERIC(29),
  ce_rbrvs_rvu_profile_id NUMERIC(29),
  ce_rbrvs_gpci_profile_id NUMERIC(29),
  ce_opps_profile_id NUMERIC(29),
  ce_abu_profile_id NUMERIC(29),
  ce_anesthesia_profile_id NUMERIC(29),
  cap_base_at_opps NUMERIC(29),
  ce_prof_fs_profile_id NUMERIC(29),
  irf_reimb_method_id NUMERIC(29),
  ce_irf_profile_id NUMERIC(29),
  irf_std_payment_conv_factor NUMERIC(35, 6),
  irf_labor_share NUMERIC(35, 6),
  irf_cbsa_wage_index NUMERIC(35, 6),
  irf_lip_adjustment NUMERIC(35, 6),
  irf_cost_to_charge_ratio NUMERIC(35, 6),
  irf_adj_threshold_amt NUMERIC(31, 2),
  irf_is_rural_facility NUMERIC(29),
  irf_rural_adjustment NUMERIC(35, 6),
  irf_is_teaching_facility NUMERIC(29),
  irf_teaching_adjustment NUMERIC(35, 6),
  snf_reimb_method_id NUMERIC(29),
  ce_snf_profile_id NUMERIC(29),
  snf_cbsa_wage_index NUMERIC(34, 5),
  snf_icd9_042_multiplier NUMERIC(33, 4),
  ce_interest_profile_id NUMERIC(29),
  ce_state_tax_profile_id NUMERIC(29),
  budget_neutrality_factor NUMERIC(33, 4),
  mult_surg_adj_type NUMERIC(29),
  ce_hierarchy_profile_id NUMERIC(29),
  ce_champus_mapping_profile_id NUMERIC(29),
  status_code_r NUMERIC(29),
  status_indicator_9 NUMERIC(29),
  xfer_add_los NUMERIC(29),
  inpatient_accrual_method_id NUMERIC(29),
  outpatient_accrual_method_id NUMERIC(29),
  inpatient_accrual_value NUMERIC(31, 2),
  outpatient_accrual_value NUMERIC(31, 2),
  ce_rbrvs_adjust_profile_id NUMERIC(29),
  ce_anes_adjust_profile_id NUMERIC(29),
  ce_rate_modifier_profile_id NUMERIC(29),
  is_prof_fs_rates_used NUMERIC(29),
  rbrvs_ranking_method_id NUMERIC(29),
  include_gaf NUMERIC(29),
  apc_non_labor_percent NUMERIC(35, 6),
  apc_cost_sharing_percent NUMERIC(31, 2),
  apc_bilateral_disc_fraction NUMERIC(35, 6),
  apc_terminated_proc_discount NUMERIC(35, 6),
  apc_is_rural_sole_comm_hosp NUMERIC(29),
  apc_rural_sch_adjustment NUMERIC(35, 6),
  apc_hosp_op_dept_er_svc NUMERIC(29),
  apc_hosp_op_dept_er_svc_val NUMERIC(31, 2),
  apc_birth_center NUMERIC(29),
  apc_birth_center_val NUMERIC(31, 2),
  apc_partial_hosp_program NUMERIC(29),
  apc_partial_hosp_program_val NUMERIC(31, 2),
  calc_base_choice_set_by_user STRING,
  calc_comp_method_set_by_user NUMERIC(29),
  cob_method_id NUMERIC(29),
  apc_code_source NUMERIC(29) NOT NULL,
  comparison_calc_level NUMERIC(29),
  gvt_newtech_profile_id NUMERIC(29),
  ce_coins_fs_profile_id NUMERIC(29),
  apc_exclude_outlier NUMERIC(29),
  apc_terminated_disc_fraction NUMERIC(35, 6),
  irf_outlier_percent NUMERIC(35, 6),
  exclude_chg_from_device_mapp NUMERIC(29),
  exclude_837_from_device_mapp NUMERIC(29),
  ce_atp_profile_id NUMERIC(29),
  tri_asa_labor_rel_portion NUMERIC(37, 8),
  tri_asa_nonlabor_rel_portion NUMERIC(37, 8),
  tri_wage_index NUMERIC(37, 8),
  tri_idme_adjustment_factor NUMERIC(37, 8),
  tri_child_hosp_labor_diff NUMERIC(31, 2),
  tri_child_hosp_nonlabor_diff NUMERIC(31, 2),
  tri_short_stay_mar_cost_factor NUMERIC(37, 8),
  ce_tricare_emer_rm_profile_id NUMERIC(29),
  tri_er_wage_index NUMERIC(37, 8),
  tri_er_labor_portion NUMERIC(37, 8),
  tri_er_nonlabor_portion NUMERIC(37, 8),
  tri_er_cost_share_percent NUMERIC(37, 8),
  tri_cost_to_charge_ratio NUMERIC(37, 8),
  tri_noscastc NUMERIC(37, 8),
  tri_labor_share_percent NUMERIC(37, 8),
  tri_nonlabor_share_percent NUMERIC(37, 8),
  tri_is_children_hospital NUMERIC(29),
  ce_tricare_apc_profile_id NUMERIC(29),
  tricare_apc_wage_index NUMERIC(35, 6),
  tricare_apc_cost_charge_ratio NUMERIC(35, 6),
  tricare_apc_is_sole_comm_hosp NUMERIC(29),
  tricare_apc_sch_adjustment NUMERIC(35, 6),
  ce_tri_drg_code_profile_id NUMERIC(29),
  tri_neonate_factor NUMERIC(35, 6),
  gvt_is_transfer_excluded NUMERIC(29) NOT NULL,
  gvt_is_outlier_excluded NUMERIC(29) NOT NULL,
  gvt_is_disregard_subterm NUMERIC(29),
  cost_share_calc_perc_selection NUMERIC(29),
  coins_calc_perc_selection NUMERIC(29),
  facility_reduced_pe NUMERIC(31, 2),
  non_facility_reduced_pe NUMERIC(31, 2),
  is_cob_capped NUMERIC(29),
  gvt_ime_component_id NUMERIC(29),
  gvt_sub_term_outlier_percent NUMERIC(31, 2),
  is_valuated NUMERIC(29),
  is_copay NUMERIC(29),
  copay_amt NUMERIC(32, 3),
  ce_valuation_profile_id NUMERIC(29),
  is_pt_resp_used_for_cob NUMERIC(29),
  gvt_readm_adj_fctr NUMERIC(34, 5) NOT NULL,
  gvt_vbj_adj_fctr BIGNUMERIC(48, 10) NOT NULL,
  apc_rural_hosp_ind INT64,
  drg_profile_id NUMERIC(29),
  icd_version_id NUMERIC(29),
  dsh_uncmps_care_addon NUMERIC(31, 2),
  dw_last_update_date DATETIME,
  implant_ccr NUMERIC(33, 4),
  low_vol_adj_fctr NUMERIC(35, 6),
  mdh_amt NUMERIC(31, 2)
)
CLUSTER BY id, schema_id;
