-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/claim_cdc_gg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.claim_cdc_gg_temp
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_acct_id BIGNUMERIC(38),
  patient_control_no STRING NOT NULL,
  admit_date DATE,
  admit_source STRING,
  admit_type STRING,
  date_billed DATE NOT NULL,
  days_covered NUMERIC(29),
  days_non_covered NUMERIC(29),
  days_coinsurance NUMERIC(29),
  days_lifetime_reserve NUMERIC(29),
  discharge_date DATE,
  drg STRING,
  bill_type STRING,
  px_coding_method STRING,
  pt_last_name STRING,
  pt_first_name STRING,
  pt_middle_name STRING,
  pt_name_suffix STRING,
  pt_address1 STRING,
  pt_address2 STRING,
  pt_city STRING,
  pt_state STRING,
  pt_zip STRING,
  pt_country STRING,
  pt_birthdate DATE,
  pt_gender STRING,
  pt_marital_status STRING,
  pt_status STRING,
  remark_1 STRING,
  remark_2 STRING,
  remark_3 STRING,
  remark_4 STRING,
  statement_from DATE,
  statement_to DATE,
  total_actual_payments NUMERIC(31, 2),
  total_charges NUMERIC(31, 2) NOT NULL,
  date_created DATE NOT NULL,
  date_updated DATE,
  claim_provider_id NUMERIC(29) NOT NULL,
  payer_name_billed_to STRING,
  source_rowid STRING,
  medical_record_number STRING,
  field_11 STRING,
  billed_to_payer_address1 STRING,
  billed_to_payer_address2 STRING,
  billed_to_payer_city STRING,
  billed_to_payer_state STRING,
  billed_to_payer_zip STRING,
  claim_type NUMERIC(29),
  mon_account_payer_id BIGNUMERIC(38),
  replaced_by_claim_id BIGNUMERIC(38),
  deleted_yn STRING NOT NULL,
  payer_rank NUMERIC(29),
  provider_no STRING,
  isansi837 NUMERIC(29),
  drg_type STRING,
  drg_version NUMERIC(29),
  accident_code STRING,
  accident_loc_state STRING,
  accident_date DATE,
  code_code_val1 STRING,
  code_code_val2 STRING,
  code_code_val3 STRING,
  code_code_val4 STRING,
  code_code_val5 STRING,
  code_code_val6 STRING,
  code_code_val7 STRING,
  code_code_val8 STRING,
  code_code_val9 STRING,
  icd_dcn_1 STRING,
  icd_dcn_2 STRING,
  icd_dcn_3 STRING,
  ic_dx_ver_qual STRING,
  pt_name_id STRING,
  pay_to_prov_name STRING,
  pay_to_prov_address STRING,
  pay_to_prov_csz STRING,
  pay_to_prov_id_code STRING,
  npi STRING,
  provider_id_other1 STRING,
  provider_id_other2 STRING,
  provider_id_other3 STRING,
  pay_to_prov_city STRING,
  pay_to_prov_state STRING,
  pay_to_prov_zip STRING,
  original_claim_id BIGNUMERIC(38),
  mon_practitioner_id NUMERIC(29) NOT NULL,
  service_facility_npi_qual STRING,
  service_facility_npi STRING,
  service_facility_rend_id_qual STRING,
  service_facility_rendering_id STRING,
  service_facility_name STRING,
  service_facility_address1 STRING,
  service_facility_address2 STRING,
  service_facility_city STRING,
  service_facility_state STRING,
  service_facility_zip STRING,
  drg_regrouped STRING,
  drg_type_regrouped STRING,
  drg_version_regrouped NUMERIC(29),
  mon_payer_id BIGNUMERIC(38),
  taxonomy_code STRING,
  covered_charges NUMERIC(31, 2),
  industry_identifier_code STRING,
  orig_patient_control_no STRING,
  drg_severity_level STRING,
  deactivation_override INT64,
  dw_last_update_date DATETIME,
  job_no INT64
)
CLUSTER BY id, schema_id;
