-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/cr_balance_refund_header.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.cr_balance_refund_header
(
  id INT64 NOT NULL,
  unit_num STRING NOT NULL,
  pat_acct_num NUMERIC(29) NOT NULL,
  total_acct_bal_amt NUMERIC(32, 3),
  total_charge_amt NUMERIC(32, 3),
  total_cash_pay_amt NUMERIC(32, 3),
  total_allow_amt NUMERIC(32, 3),
  total_policy_adj_amt NUMERIC(32, 3),
  total_write_off_amt NUMERIC(32, 3),
  financial_class INT64,
  payor_category_name STRING,
  ins_1_aa_iplan STRING,
  ins_2_aa_iplan STRING,
  ins_3_aa_iplan STRING,
  acct_status STRING,
  aa6_admit_date DATETIME,
  aa7_disch_date DATETIME,
  addr_name STRING,
  addr_1 STRING,
  addr_2 STRING,
  addr_city_state STRING,
  addr_state STRING,
  addr_zip STRING,
  addr_country STRING,
  refund_type INT64,
  refund_type_desc STRING,
  refund_amt NUMERIC(32, 3),
  refund_reason STRING,
  member_id STRING,
  refund_iplan STRING,
  last_activity_date DATETIME NOT NULL,
  ref_name STRING,
  ref_addr_1 STRING,
  ref_addr_2 STRING,
  ref_city STRING,
  ref_state STRING,
  ref_zip STRING,
  ref_country STRING,
  last_update_date_time DATETIME,
  last_update_user STRING,
  ref_special STRING,
  ref_proc_code STRING,
  ref_gl_acct STRING,
  logged_ind STRING,
  entered_date DATETIME NOT NULL,
  status STRING,
  approved_date_time DATETIME,
  approved_by_user STRING,
  transmitted_date DATETIME,
  patient_type STRING,
  bill_through_date DATETIME,
  auto_refund_create_date DATETIME,
  current_grv_amt NUMERIC(32, 3),
  final_billed_date DATETIME,
  eligible_transfer_ind STRING,
  late_charge_ind STRING,
  refund_create_date DATETIME,
  refund_create_user STRING,
  restore_date DATETIME,
  restore_ind STRING,
  extract_date DATETIME,
  credit_bal_date_established DATETIME
)
CLUSTER BY id, unit_num, pat_acct_num;
