-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/discrepancy_inventory.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.discrepancy_inventory_temp
(
  schema_id NUMERIC(29) NOT NULL,
  mon_account_payer_id BIGNUMERIC(38) NOT NULL,
  coid STRING,
  account_no STRING,
  payer_rank INT64,
  ssc_name STRING,
  facility_name STRING,
  sec_establishment_id NUMERIC(29),
  unit_num STRING,
  rate_schedule_name STRING,
  rate_schedule_eff_begin_date DATE,
  rate_schedule_eff_end_date DATE,
  patient_name STRING,
  patient_dob DATE,
  iplan_id INT64,
  insurance_provider_name STRING,
  payer_group_name STRING,
  billing_name STRING,
  billing_contact_name STRING,
  authorization_code STRING,
  payer_patient_id STRING,
  pa_financial_class STRING,
  payor_financial_class NUMERIC(29),
  reason_code STRING,
  billing_status STRING,
  pa_service_code STRING,
  pa_account_status STRING,
  cc_patient_type STRING NOT NULL,
  pa_discharge_status STRING,
  pa_patient_type STRING,
  cancel_bill_ind STRING,
  admit_source STRING,
  pa_drg STRING,
  attending_physician_id STRING,
  attending_physician_name STRING,
  service_date_begin DATETIME NOT NULL,
  discharge_date DATETIME,
  comparison_method STRING,
  project_name STRING,
  work_queue_name STRING,
  status_category_desc STRING,
  status_desc STRING,
  status_phase_desc STRING,
  calc_date DATE,
  overpayment_date DATETIME,
  overpayment_age INT64,
  underpayment_date DATETIME,
  underpayment_age INT64,
  non_fin_disc_date DATETIME,
  non_fin_disc_age INT64,
  variance_creation_date DATETIME,
  variance_creation_age INT64,
  variance_resolution_date DATETIME,
  variance_resolution_age INT64,
  first_activity_create_date DATETIME,
  last_activity_completion_date DATETIME,
  last_activity_completion_age INT64,
  last_reason_change_date DATETIME,
  last_status_change_date DATETIME,
  last_project_change_date DATETIME,
  last_owner_change_date DATETIME,
  activity_due_date DATETIME,
  activity_description STRING,
  activity_subject STRING,
  activity_owner STRING,
  total_charges NUMERIC(31, 2),
  pa_actual_los NUMERIC(31, 2),
  total_billed_charges NUMERIC(31, 2),
  total_expected_payment NUMERIC(31, 2),
  total_expected_adjustment NUMERIC(31, 2),
  total_pt_responsibility NUMERIC(31, 2),
  total_variance_adjustment NUMERIC(31, 2),
  total_payments NUMERIC(31, 2),
  total_denial_amount NUMERIC(31, 2),
  payor_due_amount NUMERIC(31, 2),
  ar_amount NUMERIC(31, 2),
  pa_total_account_bal NUMERIC(31, 2),
  user_completed_activity_date DATETIME,
  user_completed_activity_age INT64,
  user_completed_activity_subj STRING,
  user_completed_activity_desc STRING,
  user_completed_activity_ownr STRING,
  valid_overpymnt_activity_dt DATETIME,
  valid_overpymnt_activity_age INT64,
  valid_overpymnt_activity_subj STRING,
  valid_overpymnt_activity_desc STRING,
  valid_overpymnt_activity_ownr STRING,
  valid_underpymnt_activity_date DATETIME,
  valid_underpymnt_activity_age INT64,
  valid_underpymnt_activity_subj STRING,
  valid_underpymnt_activity_desc STRING,
  valid_underpymnt_activity_ownr STRING,
  stratification STRING,
  status_kpi STRING,
  validation_grp STRING,
  discrepancy_group STRING,
  credit STRING,
  payer_category STRING,
  model_issue STRING,
  credit_balance_age STRING,
  activity_kpi STRING,
  extract_date DATETIME,
  collection_amt NUMERIC(32, 3),
  collection_date DATETIME,
  source_system_code STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY schema_id, mon_account_payer_id;
