-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/edw_daily_denial_inventory.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.edw_daily_denial_inventory_temp
(
  schema_id INT64,
  mon_account_payer_id BIGNUMERIC(38),
  pass_type STRING,
  coid STRING,
  account_no STRING,
  ssc_id NUMERIC(29),
  rate_schedule_name STRING,
  ssc_name STRING,
  facility_name STRING,
  unit_num STRING,
  rate_schedule_eff_begin_date DATE,
  rate_schedule_eff_end_date DATE,
  patient_name STRING,
  patient_dob DATE,
  iplan_id INT64,
  insurance_provider_name STRING,
  payer_group_name STRING,
  billing_name STRING,
  billing_contact_person STRING,
  authorization_code STRING,
  payer_patient_id STRING,
  payer_rank INT64,
  pa_financial_class STRING,
  payor_financial_class NUMERIC(29),
  accounting_period STRING,
  major_payer_grp STRING,
  reason_code STRING,
  billing_status STRING,
  pa_service_code STRING,
  pa_account_status STRING,
  cc_patient_type STRING,
  pa_discharge_status STRING,
  pa_patient_type STRING,
  cancel_bill_ind STRING,
  admit_source STRING,
  admit_type STRING,
  pa_drg STRING,
  attending_physician_id STRING,
  attending_physician_name STRING,
  service_date_begin DATE,
  discharge_date DATE,
  comparison_method STRING,
  project_name STRING,
  work_queue_name STRING,
  status_category_desc STRING,
  status_desc STRING,
  status_phase_desc STRING,
  calc_date DATE,
  total_charges NUMERIC(32, 3),
  pa_actual_los NUMERIC(32, 3),
  total_billed_charges NUMERIC(32, 3),
  covered_charges NUMERIC(32, 3),
  total_expected_payment NUMERIC(32, 3),
  total_expected_adjustment NUMERIC(32, 3),
  total_pt_responsibility_actual NUMERIC(32, 3),
  total_variance_adjustment NUMERIC(32, 3),
  total_payments NUMERIC(32, 3),
  total_denial_amt NUMERIC(32, 3),
  payor_due_amt NUMERIC(32, 3),
  pa_total_account_bal NUMERIC(32, 3),
  ar_amount NUMERIC(32, 3),
  otd_amt_net NUMERIC(32, 3),
  writeoff_amt_net NUMERIC(32, 3),
  cash_adj_amt_net NUMERIC(32, 3),
  otd_to_date_amount_mtd NUMERIC(32, 3),
  writeoff_amt_mtd NUMERIC(32, 3),
  cash_adj_amt_mtd NUMERIC(32, 3),
  max_aplno INT64,
  max_seqno INT64,
  appeal_orig_amt NUMERIC(32, 3),
  current_appealed_amt NUMERIC(32, 3),
  current_appeal_balance NUMERIC(32, 3),
  appeal_date_created DATE,
  sequence_date_created DATE,
  close_date DATE,
  max_seq_deadline_date DATE,
  sequence_creator STRING,
  appeal_owner STRING,
  appeal_modifier STRING,
  disp_code STRING,
  disp_desc STRING,
  web_disp_code INT64,
  web_disposition_type STRING,
  root_code STRING,
  root_cause_description STRING,
  root_cause_dtl STRING,
  external_appeal_code STRING,
  apl_appeal_code STRING,
  apl_appeal_desc STRING,
  first_denial_date DATE,
  denial_age INT64,
  pa_denial_update_date DATE,
  first_activity_create_date DATE,
  last_activity_completion_date DATE,
  last_activity_completion_age INT64,
  last_user_activity_create_age INT64,
  last_reason_change_date DATE,
  last_status_change_date DATE,
  last_project_change_date DATE,
  last_owner_change_date DATE,
  activity_due_date DATE,
  activity_desc STRING,
  activity_subject STRING,
  activity_owner STRING,
  appeal_sent_activity_ownr STRING,
  appeal_initiation_date DATE,
  appeal_sent_activity_date DATE,
  appeal_sent_activity_age INT64,
  last_status_change_age INT64,
  activity_due_date_age INT64,
  latest_seq_creation_date_age INT64,
  latest_appeal_creation_date_age INT64,
  appeal_deadline_days_remaining INT64,
  appeal_sent_activity_subj STRING,
  appeal_sent_activity_desc STRING,
  extract_date DATE,
  payer_category STRING,
  source_system_code STRING,
  seq_no INT64,
  dw_last_update_date DATETIME,
  row_count INT64,
  expected_amt NUMERIC(32, 3),
  new_appeal_flag STRING,
  disposition_code_modified_date DATE,
  disposition_code_modified_by STRING,
  vendor_code STRING,
  sub_unit_num STRING,
  latest_iplan_change_date_pa DATE,
  remit_drg_code STRING,
  artiva_activity_due_date DATE,
  calc_base STRING,
  apl_lvl NUMERIC(29),
  apl_sent_dt DATE,
  prior_apl_rspn_dt DATE,
  last_remit_received_date DATETIME
)
CLUSTER BY schema_id, coid, account_no, iplan_id;
