-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/eor_discrepancy_wrk1.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.eor_discrepancy_wrk1
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  iplan_insurance_order_num INT64 NOT NULL,
  eor_log_date DATE NOT NULL,
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL,
  eff_from_date DATE NOT NULL,
  unit_num STRING,
  pat_acct_num NUMERIC(29) NOT NULL,
  iplan_id INT64,
  ar_bill_thru_date DATE,
  work_date DATE,
  cc_drg_code STRING,
  eor_hipps_code STRING,
  length_of_stay_days_num INT64,
  eor_payment_amt NUMERIC(32, 3),
  eor_contractual_allowance_amt NUMERIC(32, 3),
  eor_covered_days_num INT64,
  eor_deductible_coinsurance_amt NUMERIC(32, 3),
  eor_gross_reimbursement_amt NUMERIC(32, 3),
  eor_sqstrtn_red_amt NUMERIC(32, 3),
  eor_covered_charge_amt NUMERIC(32, 3),
  eor_non_covered_charge_amt NUMERIC(32, 3),
  eor_total_charge_amt NUMERIC(32, 3),
  eor_insurance_payment_amt NUMERIC(32, 3),
  eor_blood_deductible_amt NUMERIC(32, 3),
  eor_capital_payment_amt NUMERIC(32, 3),
  eor_coinsurance_amt NUMERIC(32, 3),
  eor_deductible_amt NUMERIC(32, 3),
  eor_total_actual_pat_resp_amt NUMERIC(32, 3),
  eor_lab_payment_amt NUMERIC(32, 3),
  eor_net_billed_charge_amt NUMERIC(32, 3),
  eor_outlier_payment_amt NUMERIC(32, 3),
  eor_primary_payor_payment_amt NUMERIC(32, 3),
  eor_therapy_payment_amt NUMERIC(32, 3),
  eor_copay_amt NUMERIC(32, 3),
  pa_total_account_balance_amt NUMERIC(32, 3),
  eor_net_apc_service_amt NUMERIC(32, 3),
  eor_net_fee_schedule_amt NUMERIC(32, 3),
  eor_total_variance_adj_amt NUMERIC(32, 3),
  eor_total_trans_payment_amt NUMERIC(32, 3),
  eor_hac_adj_amt NUMERIC(32, 3),
  total_denial_amt NUMERIC(32, 3),
  inpatient_outpatient_ind STRING,
  interim_bill_ind STRING,
  reason_code_3 STRING,
  reason_id NUMERIC(29),
  calc_id BIGNUMERIC(38),
  account_activity_id BIGNUMERIC(38),
  account_payer_status_id NUMERIC(29),
  status_phase_id NUMERIC(29),
  status_category_id NUMERIC(29),
  dw_last_update_date_time DATETIME,
  source_system_code STRING NOT NULL
)
CLUSTER BY patient_dw_id;
