-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/eor_amount_stg_calc_service.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.eor_amount_stg_calc_service
(
  company_code STRING,
  coid STRING,
  patient_dw_id NUMERIC(29),
  payor_dw_id NUMERIC(29),
  iplan_insurance_order_num STRING,
  eor_log_date DATETIME,
  log_id STRING,
  log_sequence_num INT64,
  eff_from_date DATE,
  reimbursement_method_type_code STRING,
  unit_num STRING,
  eor_pat_acct_num NUMERIC(29),
  eor_iplan_id INT64,
  dw_last_update_date_time DATETIME,
  source_system_code STRING,
  rate_schedule STRING,
  mon_account_id BIGNUMERIC(38),
  mon_payer_id BIGNUMERIC(38),
  schema_id NUMERIC(29),
  mon_account_payer_id BIGNUMERIC(38),
  map_misc_amt02 NUMERIC(32, 3),
  map_misc_amt01 NUMERIC(32, 3),
  map_copay NUMERIC(32, 3),
  map_coinsurance NUMERIC(32, 3),
  map_deductible NUMERIC(32, 3),
  map_covered_charges NUMERIC(32, 3),
  map_total_payments NUMERIC(32, 3),
  map_total_variance_adj NUMERIC(32, 3),
  map_total_exp_payment NUMERIC(32, 3),
  map_sequestration_amt NUMERIC(31, 2),
  mapcl_tot_exp_payment NUMERIC(32, 3),
  mapcl_base_exp_payment NUMERIC(32, 3),
  mapcl_exclusion_exp_payment NUMERIC(32, 3),
  mapcl_stoploss_exp_payment NUMERIC(32, 3),
  ma_total_charges NUMERIC(32, 3),
  ma_billed_charges NUMERIC(32, 3),
  ma_misc_amt01 NUMERIC(32, 3),
  gvt_capital_drg_pmt NUMERIC(32, 3),
  gvt_capital_outlier_pmt NUMERIC(32, 3),
  gvt_operating_fed_pmt NUMERIC(32, 3),
  gvt_ime_operating_drg_pmt NUMERIC(32, 3),
  gvt_outlier_payment NUMERIC(32, 3),
  gvt_dsh_operating_drg_pmt NUMERIC(32, 3),
  gvt_capital_cost_outlier NUMERIC(32, 3),
  gvt_newtech_add_on NUMERIC(32, 3),
  tot_expected_payment NUMERIC(32, 3),
  noncovered_charges NUMERIC(32, 3),
  gvt_drg_pmt NUMERIC(32, 3),
  gvt_cost_threshold NUMERIC(32, 3),
  ip_gvt_capital_cost NUMERIC(32, 3),
  ip_gvt_dsh_capital_drg_pmt NUMERIC(32, 3),
  ip_gvt_adj_capital_fed_pmt NUMERIC(32, 3),
  dsh_uncmps_care_addon_amt NUMERIC(31, 2),
  ipf_pps_out_per_diem_add_on NUMERIC(32, 3),
  ipf_pps_adj_per_diem NUMERIC(32, 3),
  quantity INT64,
  comp_flg_exp_payment NUMERIC(32, 3),
  comp_flg_apc_outlier_amount NUMERIC(32, 3),
  comp_flg_apc_coinsurance_amt NUMERIC(32, 3),
  comp_flg_apc_deductible_amt NUMERIC(32, 3),
  srv_mcrtherapy_exp_payment NUMERIC(32, 3),
  srv_hcd_exp_payment NUMERIC(32, 3),
  srv_mri_exp_payment NUMERIC(32, 3),
  srv_mri_hcd_imp_exp_payment NUMERIC(32, 3),
  srv_imp_exp_payment NUMERIC(32, 3),
  srv_lab_exp_payment NUMERIC(32, 3),
  srv_lab_service_charges NUMERIC(32, 3),
  srv_mcrlab_exp_payment NUMERIC(32, 3),
  srv_tricmac_exp_payment NUMERIC(32, 3),
  srv_ect_exp_payment NUMERIC(32, 3),
  srv_mcrlabtherapy_exp_payment NUMERIC(32, 3),
  calc_atp_exp_payment NUMERIC(32, 3),
  calc_atp_charge_amount NUMERIC(32, 3),
  calc_apc_outlier_payment NUMERIC(32, 3),
  calc_apc_exp_payment NUMERIC(32, 3),
  calc_apc_deductible_amount NUMERIC(32, 3),
  calc_apc_coinsurance_amount NUMERIC(32, 3),
  loa_count INT64,
  hac_adjmt_amt NUMERIC(32, 3),
  ra_remit_received_flag INT64,
  ra_deductible NUMERIC(32, 3),
  ra_coinsurance NUMERIC(32, 3),
  ra_copay NUMERIC(32, 3),
  ra_pat_resp_non_covered_amt NUMERIC(32, 3),
  calc_fee_schedule_adj NUMERIC(32, 3),
  gvt_device_offset_reduction NUMERIC(35, 6),
  gvt_scp_payment NUMERIC(31, 2),
  acct_subterm_amt NUMERIC(31, 2),
  passthrough_amount NUMERIC(31, 2),
  cob_amount NUMERIC(31, 2),
  low_vol_add_on_amt NUMERIC(31, 2),
  readm_adjmt_amt NUMERIC(31, 2),
  mdh_add_on_amt NUMERIC(31, 2),
  val_based_adjmt_amt NUMERIC(31, 2),
  gvt_operating_outlier_pmt NUMERIC(35, 6)
)
CLUSTER BY company_code, coid, patient_dw_id, payor_dw_id;
