-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/lu_date.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.lu_date
(
  date_id DATE,
  week_id INT64,
  week_num INT64,
  week_end_date INT64,
  month_id INT64,
  month_id_desc_s STRING,
  month_id_desc_l STRING,
  month_num INT64,
  month_num_desc_s STRING,
  month_num_desc_l STRING,
  qtr_id INT64,
  qtr_desc STRING,
  qtr_num INT64,
  qtr_num_desc_s STRING,
  qtr_num_desc_l STRING,
  year_id INT64,
  semi_annual_id INT64,
  semi_annual_desc STRING,
  day_of_week INT64,
  dow_desc_s STRING,
  dow_desc_l STRING,
  day_of_month INT64,
  day_of_qtr INT64,
  day_of_year INT64,
  days_in_week INT64,
  days_in_month INT64,
  days_in_qtr INT64,
  days_in_year INT64,
  month_days_left INT64,
  week_days_left INT64,
  qtr_days_left INT64,
  year_days_left INT64,
  week_day_flag INT64,
  week_end_flag INT64,
  federal_bank_holiday_flag STRING,
  hca_holiday_flag STRING,
  pe_date DATE,
  pe_date_prior_month DATE,
  week_of_month INT64,
  bank_day_flag INT64,
  qtr_desc_dss STRING,
  date_prev DATE,
  qtr_num_prev INT64,
  year_id_prev INT64,
  month_id_prev INT64,
  week_id_prev INT64,
  week_num_desc STRING,
  prev_month_day_date DATE,
  prev_qtr_day_date DATE,
  prev_year_day_date DATE,
  business_day INT64,
  business_day_mtd INT64,
  business_day_ytd INT64,
  ucc_business_day_sw INT64,
  ucc_open_hour_num INT64,
  psg_weighted_business_days_num NUMERIC(31, 2),
  projection_week_id STRING
)
PARTITION BY DATE_TRUNC(date_id, MONTH);