-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_transaction_cdc_gg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_transaction_cdc_gg
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_account_id BIGNUMERIC(38) NOT NULL,
  amount NUMERIC(31, 2) NOT NULL,
  mon_transaction_master_id BIGNUMERIC(38) NOT NULL,
  comments STRING,
  mon_payer_id BIGNUMERIC(38),
  transaction_date DATE NOT NULL,
  date_created DATE NOT NULL,
  date_updated DATE,
  user_id_acct_payer_owner NUMERIC(29),
  service_line_no NUMERIC(29),
  misc_char01 STRING,
  misc_char02 STRING,
  misc_char03 STRING,
  misc_char04 STRING,
  misc_char05 STRING,
  misc_char06 STRING,
  misc_char07 STRING,
  misc_char08 STRING,
  misc_char09 STRING,
  misc_char10 STRING,
  misc_date01 DATE,
  misc_date02 DATE,
  misc_date03 DATE,
  misc_date04 DATE,
  misc_date05 DATE,
  misc_amt01 NUMERIC(31, 2),
  misc_amt02 NUMERIC(31, 2),
  misc_amt03 NUMERIC(31, 2),
  misc_amt04 NUMERIC(31, 2),
  misc_amt05 NUMERIC(31, 2),
  misc_yn01 STRING,
  misc_yn02 STRING,
  misc_yn03 STRING,
  misc_yn04 STRING,
  misc_yn05 STRING,
  job_no NUMERIC(29),
  job_no_reprocess NUMERIC(29),
  mon_prof_charge_detail_id BIGNUMERIC(38),
  mon_practitioner_id NUMERIC(29) NOT NULL,
  mon_accounting_period_id NUMERIC(29),
  is_system_reversal NUMERIC(29) NOT NULL,
  is_user_redistributed NUMERIC(29),
  is_xns_redist_reversed NUMERIC(29),
  snapshot_mon_status_id NUMERIC(29),
  snapshot_mon_reason_id NUMERIC(29),
  snapshot_apl_appeal_id NUMERIC(29),
  snapshot_appeal_no NUMERIC(29),
  snapshot_appeal_seq_no NUMERIC(29),
  parent_transaction_id BIGNUMERIC(38),
  user_id_created_by NUMERIC(29),
  user_id_updated_by NUMERIC(29),
  effective_date DATE,
  is_valuated NUMERIC(29),
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id, mon_account_id, mon_transaction_master_id;
