-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_payer_cdc_gg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_payer_cdc_gg_temp
(
  id BIGNUMERIC(38) NOT NULL,
  mon_account_id BIGNUMERIC(38) NOT NULL,
  payer_rank NUMERIC(29) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  authorization_code STRING,
  contract_id NUMERIC(29),
  employer_name STRING,
  group_name STRING,
  insurance_group_no STRING,
  insured_name STRING,
  mon_payer_id BIGNUMERIC(38) NOT NULL,
  payer_identification_no STRING,
  rel_to_insured STRING,
  release_info STRING,
  total_expected_payment NUMERIC(31, 2),
  total_payments NUMERIC(31, 2),
  total_pt_responsibility NUMERIC(31, 2),
  mon_project_id NUMERIC(29),
  mon_reason_id NUMERIC(29),
  mon_status_id NUMERIC(29),
  billed_date DATE,
  expected_contractual NUMERIC(31, 2),
  total_adjustments NUMERIC(31, 2),
  date_created DATE NOT NULL,
  date_updated DATE,
  user_id_owner NUMERIC(29),
  current_expected_payment NUMERIC(31, 2),
  current_expected_contractual NUMERIC(31, 2),
  insureds_social_security_no STRING,
  billing_name STRING,
  billing_address1 STRING,
  billing_address2 STRING,
  billing_city STRING,
  billing_state STRING,
  billing_zip STRING,
  billing_phone STRING,
  billing_fax STRING,
  billing_contact_person STRING,
  billing_contact_email STRING,
  calculation_date DATE,
  is_eligible NUMERIC(29) NOT NULL,
  insureds_address1 STRING,
  insureds_address2 STRING,
  insureds_city STRING,
  insureds_state STRING,
  insureds_zip STRING,
  insureds_phone STRING,
  insureds_gender STRING,
  insureds_date_of_birth DATE,
  misc_char01 STRING,
  misc_char02 STRING,
  misc_char03 STRING,
  misc_char04 STRING,
  misc_char05 STRING,
  misc_char06 STRING,
  misc_char07 STRING,
  misc_char08 STRING,
  misc_char09 STRING,
  misc_char10 STRING,
  misc_date01 DATE,
  misc_date02 DATE,
  misc_date03 DATE,
  misc_date04 DATE,
  misc_date05 DATE,
  misc_amt01 NUMERIC(31, 2),
  misc_amt02 NUMERIC(31, 2),
  misc_amt03 NUMERIC(31, 2),
  misc_amt04 NUMERIC(31, 2),
  misc_amt05 NUMERIC(31, 2),
  misc_yn01 STRING,
  misc_yn02 STRING,
  misc_yn03 STRING,
  misc_yn04 STRING,
  misc_yn05 STRING,
  contract_code STRING,
  allow_contract_code_changes NUMERIC(29) NOT NULL,
  calc_lock NUMERIC(29) NOT NULL,
  calc_contract_name STRING,
  send_to_ce_for_payer_change NUMERIC(29),
  cers_profile_id NUMERIC(29),
  calculation_no NUMERIC(29),
  rate_schedule_name STRING,
  cers_term_id NUMERIC(29),
  total_denials NUMERIC(31, 2),
  calc_base NUMERIC(29),
  job_no NUMERIC(29),
  job_no_reprocess NUMERIC(29),
  professional_expected_payment NUMERIC(31, 2),
  prof_calc_base NUMERIC(29),
  interest_calc_date DATE,
  interest_amt NUMERIC(31, 2),
  state_tax_amt NUMERIC(31, 2),
  interest_stop_date DATE,
  interest_rate NUMERIC(31, 2),
  mon_status_id_old NUMERIC(29),
  status_set_by_job_no NUMERIC(29),
  status_set_by_rule_rank NUMERIC(29),
  status_set_by_rule_id NUMERIC(29),
  is_status_overridable NUMERIC(29),
  mon_project_id_old NUMERIC(29),
  project_set_by_job_no NUMERIC(29),
  project_set_by_rule_rank NUMERIC(29),
  project_set_by_rule_id NUMERIC(29),
  is_project_overridable NUMERIC(29),
  mon_reason_id_old NUMERIC(29),
  reason_set_by_job_no NUMERIC(29),
  reason_set_by_rule_rank NUMERIC(29),
  reason_set_by_rule_id NUMERIC(29),
  is_reason_overridable NUMERIC(29),
  owner_id_old NUMERIC(29),
  owner_set_by_job_no NUMERIC(29),
  owner_set_by_rule_rank NUMERIC(29),
  owner_set_by_rule_id NUMERIC(29),
  is_owner_overridable NUMERIC(29),
  wf_profile_id NUMERIC(29),
  wf_set_by_job_no NUMERIC(29),
  wf_set_by_rule_rank NUMERIC(29),
  wf_set_by_rule_id NUMERIC(29),
  wf_batchname STRING,
  wf_batchowner NUMERIC(29),
  calc_source STRING,
  covered_charges_inst NUMERIC(31, 2) NOT NULL,
  is_837_change_trigger NUMERIC(29),
  is_manual_trigger NUMERIC(29),
  calc_base_choice_set_by_user STRING,
  calc_base_choice_override_rs NUMERIC(29),
  calc_comp_method_set_by_user NUMERIC(29),
  calc_comp_method_override_rs NUMERIC(29),
  calc_base_survivor NUMERIC(29),
  calc_base_choice_resolved STRING,
  comp_method_choice NUMERIC(29),
  account_calc_situation STRING,
  cob_method_id NUMERIC(29),
  orig_rank_2_expected_payment NUMERIC(31, 2),
  date_account_component_updated DATE,
  coinsurance NUMERIC(31, 2),
  deductible NUMERIC(31, 2),
  copay NUMERIC(31, 2),
  calc_result NUMERIC(29),
  apl_appeal_id NUMERIC(29),
  apl_appeal_id_old NUMERIC(29),
  appeal_set_by_jobno NUMERIC(29),
  appeal_set_by_rule_id NUMERIC(29),
  appeal_set_by_rule_rank NUMERIC(29),
  appeal_ext_code_update_status NUMERIC(29),
  is_elig_for_lifecycle_check NUMERIC(29),
  total_variance_adjustment NUMERIC(31, 2),
  estimated_pt_responsibility NUMERIC(31, 2),
  actual_pt_responsibility NUMERIC(31, 2),
  patient_accouting_coinsurance NUMERIC(35, 6),
  external_appeal_code STRING,
  covered_charges_prof NUMERIC(31, 2),
  first_denial_date DATE,
  contract_provision_ind NUMERIC(29),
  patient_cap_met NUMERIC(31, 2),
  calc_copayment_amt NUMERIC(31, 2),
  dw_last_update_date DATETIME,
  group_stack STRING,
  org_id NUMERIC(29),
  ppmc_ind INT64
)
CLUSTER BY id, schema_id;
