-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_payer_calc_service_bkp.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_payer_calc_service_bkp
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_acct_payer_calc_summary_id BIGNUMERIC(38) NOT NULL,
  ce_service_id BIGNUMERIC(38) NOT NULL,
  ce_rule_id NUMERIC(29),
  ce_rule_type_id NUMERIC(29),
  service_date DATE,
  quantity NUMERIC(30, 1),
  asc_rank NUMERIC(29),
  expected_payment NUMERIC(31, 2),
  service_charges NUMERIC(31, 2),
  exclusion_charges NUMERIC(31, 2),
  noncovered_charges NUMERIC(31, 2),
  procedure_code_type STRING,
  procedure_code STRING,
  modifer_1 STRING,
  modifer_2 STRING,
  revenue_code STRING,
  cers_rate_id NUMERIC(29),
  calculation_method_id NUMERIC(29),
  rate_info_amount NUMERIC(31, 2),
  rate_info_from NUMERIC(29),
  rate_info_to NUMERIC(29),
  rate_info_use_exclusions NUMERIC(29),
  rate_info_stoploss_group_name STRING,
  rate_info_service_display STRING,
  gvt_adj_capital_fed_pmt NUMERIC(35, 6),
  gvt_capital_cost NUMERIC(35, 6),
  gvt_capital_cost_outlier NUMERIC(35, 6),
  gvt_capital_day_outlier NUMERIC(35, 6),
  gvt_capital_drg_pmt NUMERIC(35, 6),
  gvt_capital_fed_drg_pmt NUMERIC(35, 6),
  gvt_capital_fed_pmt NUMERIC(35, 6),
  gvt_capital_hosp_drg_pmt NUMERIC(35, 6),
  gvt_capital_hosp_pmt NUMERIC(35, 6),
  gvt_capital_outlier_pmt NUMERIC(35, 6),
  gvt_capital_threshold NUMERIC(35, 6),
  gvt_cost_outlier_pmt NUMERIC(35, 6),
  gvt_cost_threshold NUMERIC(35, 6),
  gvt_day_outlier_pmt NUMERIC(35, 6),
  gvt_drg_pmt NUMERIC(35, 6),
  gvt_drg_capital_threshold NUMERIC(35, 6),
  gvt_drg_operating_threshold NUMERIC(35, 6),
  gvt_dsh_capital_drg_pmt NUMERIC(35, 6),
  gvt_dsh_capital_outlier_pmt NUMERIC(35, 6),
  gvt_dsh_operating_drg_pmt NUMERIC(35, 6),
  gvt_dsh_operating_outlier_pmt NUMERIC(35, 6),
  gvt_ime_capital_drg_pmt NUMERIC(35, 6),
  gvt_ime_capital_outlier_pmt NUMERIC(35, 6),
  gvt_ime_operating_drg_pmt NUMERIC(35, 6),
  gvt_ime_operating_outlier_pmt NUMERIC(35, 6),
  gvt_operating_cost NUMERIC(35, 6),
  gvt_operating_cost_outlier NUMERIC(35, 6),
  gvt_operating_day_outlier NUMERIC(35, 6),
  gvt_operating_drg_pmt NUMERIC(35, 6),
  gvt_operating_fed_pmt NUMERIC(35, 6),
  gvt_operating_outlier_pmt NUMERIC(35, 6),
  gvt_operating_threshold NUMERIC(35, 6),
  gvt_outlier_payment NUMERIC(35, 6),
  gvt_short_stay_capital_pmt NUMERIC(35, 6),
  gvt_short_stay_operating_pmt NUMERIC(35, 6),
  gvt_short_stay_pmt NUMERIC(35, 6),
  gvt_xfer_drg_capital_pmt NUMERIC(35, 6),
  gvt_xfer_drg_operating_pmt NUMERIC(35, 6),
  gvt_xfer_drg_pmt NUMERIC(35, 6),
  gvt_xfer_in_capital_hosp_pmt NUMERIC(35, 6),
  gvt_xfer_in_capital_fed_pmt NUMERIC(35, 6),
  gvt_xfer_in_operating_pmt NUMERIC(35, 6),
  gvt_xfer_in_pmt NUMERIC(35, 6),
  gvt_xfer_in__dsh_capital_pmt NUMERIC(35, 6),
  gvt_xfer_in__dsh_operating_pmt NUMERIC(35, 6),
  gvt_xfer_in__ime_capital_pmt NUMERIC(35, 6),
  gvt_xfer_in__ime_operating_pmt NUMERIC(35, 6),
  hipps_average_los NUMERIC(31, 2),
  hipps_cmg_labor_adj_amount NUMERIC(31, 2),
  hipps_cmg_rural_adj_amount NUMERIC(31, 2),
  hipps_cmg_lip_adj_amount NUMERIC(31, 2),
  hipps_cost_to_charge_amount NUMERIC(31, 2),
  hipps_outlier_pmt NUMERIC(31, 2),
  hipps_payment NUMERIC(31, 2),
  hipps_payment_rate NUMERIC(31, 2),
  hipps_per_diem_amount NUMERIC(31, 2),
  hipps_short_stay_labor_adj_amt NUMERIC(31, 2),
  hipps_short_stay_lip_adj_amt NUMERIC(31, 2),
  hipps_short_stay_pmt NUMERIC(31, 2),
  hipps_short_stay_rural_adj_amt NUMERIC(31, 2),
  hipps_short_stay_wage_adj_amt NUMERIC(31, 2),
  hipps_thresh_amount NUMERIC(31, 2),
  hipps_thresh_labor_adj_amt NUMERIC(31, 2),
  hipps_thresh_lip_adj_amt NUMERIC(31, 2),
  hipps_thresh_rural_adj_amt NUMERIC(31, 2),
  hipps_thresh_wage_adj_amt NUMERIC(31, 2),
  hipps_transfer_adj_amt NUMERIC(31, 2),
  hipps_transfer_base_amt NUMERIC(31, 2),
  hipps_transfer_pmt NUMERIC(31, 2),
  apc STRING,
  ce_apc_group_id NUMERIC(29),
  apc_rank NUMERIC(29),
  apc_status_indicator_code STRING,
  ce_apc_status_indicator_id NUMERIC(29),
  apc_service_rank NUMERIC(29),
  apc_base_rate NUMERIC(31, 2),
  apc_weight NUMERIC(31, 2),
  apc_is_reimbursable NUMERIC(29),
  apc_is_discountable NUMERIC(29),
  apc_passthrough_ratio NUMERIC(31, 2),
  apc_passthrough_current_cost NUMERIC(31, 2),
  apc_passthrough_charge_amount NUMERIC(31, 2),
  apc_reimbursement_percent NUMERIC(35, 6),
  apc_coinsurance_amount NUMERIC(31, 2),
  apc_deductible_amount NUMERIC(31, 2),
  apc_program_payment_percent NUMERIC(35, 6),
  apc_preliminary_payment NUMERIC(31, 2),
  apc_outlier_percent NUMERIC(31, 2),
  apc_national_unadj_coinsurance NUMERIC(31, 2),
  apc_min_adjusted_coinsurance NUMERIC(31, 2),
  apc_hosp_coinsurance_reduction NUMERIC(31, 2),
  apc_maximum_units NUMERIC(29),
  apc_offset_amount NUMERIC(31, 2),
  apc_pro_rata_adjustment NUMERIC(31, 2),
  apc_outlier_amount NUMERIC(31, 2),
  apg STRING,
  ce_apg_id NUMERIC(29),
  apg_rank NUMERIC(29),
  apg_quantity_indicator NUMERIC(29),
  apg_service_rank NUMERIC(29),
  apg_is_consolidated NUMERIC(29),
  apg_is_packaged NUMERIC(29),
  apg_is_reimbursable NUMERIC(29),
  apg_inlier_threshold NUMERIC(31, 2),
  apg_outlier_threshold NUMERIC(31, 2),
  apg_base_rate NUMERIC(31, 2),
  apg_reimbursement_percent NUMERIC(35, 6),
  apg_weight NUMERIC(31, 2),
  ce_apg_category_id NUMERIC(29),
  apg_is_counted_for_max NUMERIC(29),
  apg_is_combined_for_max NUMERIC(29),
  apg_maximum_units NUMERIC(29),
  ipf_pps_wage_adj_per_diem NUMERIC(31, 2),
  ipf_pps_facility_adj_factor NUMERIC(33, 4),
  ipf_pps_patient_adj_factor NUMERIC(33, 4),
  cers_ipf_per_diem_schedule_id NUMERIC(29),
  ipf_pps_los_adj_factor NUMERIC(33, 4),
  ipf_pps_adj_per_diem NUMERIC(31, 2),
  ipf_pps_outlier_per_diem NUMERIC(31, 2),
  ipf_pps_out_perdiem_adj_fact NUMERIC(33, 4),
  ipf_pps_out_per_diem_add_on NUMERIC(31, 2),
  ipf_pps_trans_adj_out_pmt NUMERIC(31, 2),
  ipf_pps_trans_adj_per_diem_pmt NUMERIC(31, 2),
  gvt_xfer_per_diem NUMERIC(31, 2),
  gvt_xfer_special_pay_addon NUMERIC(31, 2),
  asc_discount_percent NUMERIC(31, 2),
  asc_interim_payment NUMERIC(31, 2),
  ce_apc_profile_id NUMERIC(29),
  asc_modifier_instance NUMERIC(29),
  charge_code STRING,
  cers_accrual_method_id NUMERIC(29),
  cers_accrual_value NUMERIC(31, 2),
  apc_bilateral_type NUMERIC(29),
  apc_gender STRING,
  apc_low_age NUMERIC(29),
  apc_high_age NUMERIC(29),
  apc_device_amount NUMERIC(31, 2),
  apc_cost_sharing_type NUMERIC(29),
  apc_cost_sharing_value NUMERIC(31, 2),
  total_quantity NUMERIC(31, 2),
  total_amount NUMERIC(31, 2),
  display_seq NUMERIC(29),
  cost_weight NUMERIC(35, 6),
  gvt_oper_cost_charge_ratio NUMERIC(31, 2),
  gvt_scp_payment NUMERIC(31, 2),
  apc_adj_labor_portion NUMERIC(31, 2),
  apc_adj_offset_amt NUMERIC(31, 2),
  apc_labor_percent NUMERIC(35, 6),
  apc_labor_portion NUMERIC(31, 2),
  apc_total_adj_offset NUMERIC(31, 2),
  apc_wage_index NUMERIC(35, 6),
  ipf_cola NUMERIC(31, 2),
  ipf_cost_charge_ratio NUMERIC(35, 6),
  ipf_fixed_loss_amount NUMERIC(31, 2),
  ipf_labor_share_amount NUMERIC(31, 2),
  ipf_labor_share_percent NUMERIC(35, 6),
  ipf_non_labor_share_amount NUMERIC(31, 2),
  ipf_pps_federal_percent NUMERIC(31, 2),
  ipf_rural_adjust_factor NUMERIC(31, 2),
  ipf_teaching_adjst_factor NUMERIC(31, 2),
  ipf_wage_index NUMERIC(35, 6),
  ipf_age_factor NUMERIC(31, 2),
  ipf_drg_adjust_factor NUMERIC(31, 2),
  ipf_length_of_stay NUMERIC(31, 2),
  ipf_comorbidity_factor NUMERIC(31, 2),
  ipf_pps_los_adjust_factor NUMERIC(31, 2),
  ipf_pps_facility_adjust_factor NUMERIC(31, 2),
  ipf_pps_patient_adjust_factor NUMERIC(31, 2),
  apc_coinsurance_limit NUMERIC(31, 2),
  apc_cost_to_charge_ratio NUMERIC(35, 6),
  apc_fixed_threshold NUMERIC(31, 2),
  apc_threshold_multiplier NUMERIC(31, 2),
  apc_maximum_coin_amount NUMERIC(31, 2),
  apc_unadjusted_payment_rate NUMERIC(31, 2),
  ipf_pre_los_adjusted_perdiem NUMERIC(31, 2),
  ipf_pps_adjustment_factor NUMERIC(31, 2),
  subterm_expected_payment NUMERIC(31, 2),
  gvt_newtech_add_on NUMERIC(35, 6),
  gvt_device_offset_reduction NUMERIC(35, 6),
  gvt_transfer_percent NUMERIC(35, 6),
  gvt_drg_covered_charge NUMERIC(35, 6),
  gvt_transfer_type_id NUMERIC(29),
  apc_sch_adjustment NUMERIC(31, 2),
  apc_bilateral_disc_formula NUMERIC(29),
  apc_benificiary_payment_pct NUMERIC(33, 4),
  apc_wage_adj_copayment_amount NUMERIC(31, 2),
  apc_rate_modifier_rank NUMERIC(29),
  apc_rate_modifier_percent NUMERIC(31, 2),
  apc_payment_before_rate_mod NUMERIC(31, 2),
  modifier_fb_rate NUMERIC(31, 2),
  modifier_fc_rate NUMERIC(31, 2),
  apc_threshold_adj_payment NUMERIC(31, 2),
  ipf_pps_education_payment NUMERIC(31, 2),
  ce_tricare_apc_profile_id NUMERIC(29),
  ce_tricare_apc_group_id NUMERIC(29),
  ce_tricare_apc_status_ind_id NUMERIC(29),
  tricare_cost_sharing_amount NUMERIC(31, 2),
  apc_nuc_rad_offset_reduction NUMERIC(31, 2),
  gvt_is_transfer_excluded NUMERIC(29),
  gvt_is_outlier_excluded NUMERIC(29),
  is_disregard_subterm NUMERIC(29),
  ce_tri_apc_comp_codeset_id NUMERIC(29),
  ce_apc_comp_codeset_id NUMERIC(29),
  ipf_per_diem_day NUMERIC(29),
  apc_composite_flag NUMERIC(29),
  pre_transplant_service_id NUMERIC(29),
  offset_apc_payment_rate NUMERIC(31, 2),
  apc_calculated_offset_value NUMERIC(32, 3),
  apc_device_codes STRING,
  copay_method_id NUMERIC(29),
  valuation_method_id NUMERIC(29),
  apc_device_proc_offset_rate NUMERIC(31, 2),
  per_diem_method_id NUMERIC(29),
  creation_date DATETIME NOT NULL,
  creation_user STRING,
  modification_date DATETIME,
  modification_user STRING,
  dsh_unadj_opr_addon_amt NUMERIC(31, 2),
  dsh_uncmps_care_addon_amt NUMERIC(31, 2),
  dw_last_update_date DATETIME,
  hac_adjmt_amt NUMERIC(31, 2),
  hac_adjmt_fctr NUMERIC(33, 4),
  low_vol_add_on_amt NUMERIC(31, 2),
  readm_adjmt_amt NUMERIC(31, 2),
  mdh_add_on_amt NUMERIC(31, 2),
  val_based_adjmt_amt NUMERIC(31, 2)
)
CLUSTER BY schema_id, mon_acct_payer_calc_summary_id;
