-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_payer_calc_tri_drg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_payer_calc_tri_drg_temp
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_acct_payer_service_id BIGNUMERIC(38) NOT NULL,
  mon_acct_payer_summary_id BIGNUMERIC(38) NOT NULL,
  total_billed_charges NUMERIC(35, 6),
  included_charges NUMERIC(35, 6),
  excluded_charges NUMERIC(35, 6),
  transfer_type_id NUMERIC(29),
  geometric_mean NUMERIC(31, 2),
  transfer_per_diem NUMERIC(35, 6),
  device_offset_reduction NUMERIC(35, 6),
  tot_tricare_drg_payment NUMERIC(35, 6),
  asa_labor_rel_portion NUMERIC(37, 8),
  asa_nonlabor_rel_portion NUMERIC(37, 8),
  wage_index NUMERIC(37, 8),
  idme_adjustment_factor NUMERIC(37, 8),
  base_drg_rate NUMERIC(35, 6),
  is_short_stay NUMERIC(29),
  short_stay_threshold NUMERIC(29),
  arithmetic_mean NUMERIC(31, 2),
  short_stay_mar_cost_factor NUMERIC(37, 8),
  cost_to_charge_ratio NUMERIC(37, 8),
  noscastc NUMERIC(37, 8),
  marginal_cost_factor NUMERIC(31, 2),
  neonate_factor NUMERIC(35, 6),
  weight NUMERIC(34, 5),
  fixed_loss_threshold NUMERIC(31, 2),
  is_children_hospital NUMERIC(29),
  date_created DATE NOT NULL,
  transfer_rate NUMERIC(35, 6),
  idme_addon_payment NUMERIC(35, 6),
  is_neonatal NUMERIC(29),
  drg_transfer_type_id NUMERIC(29),
  labor_share_percent NUMERIC(37, 8),
  nonlabor_share_percent NUMERIC(37, 8),
  child_hosp_labor_diff NUMERIC(31, 2),
  child_hosp_nonlabor_diff NUMERIC(31, 2),
  ce_tri_drg_code_id NUMERIC(29),
  standard_cost_outlier_pay NUMERIC(35, 6),
  standard_xfr_cost_outlier_pay NUMERIC(35, 6),
  special_xfr_cost_outlier_pay NUMERIC(35, 6),
  neonate_cost_outlier_pay NUMERIC(35, 6),
  short_stay_outlier_amount NUMERIC(35, 6),
  drg_payment NUMERIC(35, 6),
  base_drg_payment NUMERIC(35, 6),
  ce_tri_drg_code_profile_id NUMERIC(29),
  ce_tri_drg_code_profile_name STRING,
  comparison_calc_method_id NUMERIC(29),
  comparison_calc_modifier NUMERIC(33, 4),
  creation_date DATETIME,
  creation_user STRING,
  modification_date DATETIME,
  modification_user STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id;
