-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_acct_payer_calc_sum_cdc_gg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_acct_payer_calc_sum_cdc_gg
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_account_payer_id BIGNUMERIC(38) NOT NULL,
  calculation_no NUMERIC(29) NOT NULL,
  payer_rank NUMERIC(29),
  is_current NUMERIC(29) NOT NULL,
  mon_account_id BIGNUMERIC(38) NOT NULL,
  account_no STRING NOT NULL,
  is_model NUMERIC(29) NOT NULL,
  cers_term_id NUMERIC(29),
  mon_payer_id BIGNUMERIC(38) NOT NULL,
  billing_status STRING,
  drg_type STRING,
  drg STRING,
  hipps_code STRING,
  service_date_begin DATE,
  service_date_end DATE,
  length_of_stay NUMERIC(29),
  ce_patient_type_id NUMERIC(29),
  mon_patient_type_id NUMERIC(29),
  total_charges NUMERIC(31, 2),
  total_payments NUMERIC(31, 2),
  patient_convenience_charges NUMERIC(31, 2),
  total_expected_payment NUMERIC(31, 2),
  base_expected_payment NUMERIC(31, 2),
  exclusion_expected_payment NUMERIC(31, 2),
  cers_stoploss_id NUMERIC(29),
  stoploss_expected_payment NUMERIC(31, 2),
  pre_cob_expected_payment NUMERIC(31, 2),
  account_payer_payments NUMERIC(31, 2),
  account_payer_adjustments NUMERIC(31, 2),
  calculation_date DATE NOT NULL,
  created_by STRING NOT NULL,
  user_id_creator NUMERIC(29),
  noncovered_amount_pt_resp NUMERIC(31, 2),
  noncovered_amount_writeoff NUMERIC(31, 2),
  cers_term_id_compare NUMERIC(29),
  compare_expected_payment NUMERIC(31, 2),
  compare_base_expected_payment NUMERIC(31, 2),
  compare_exception_expected_pmt NUMERIC(31, 2),
  cers_stoploss_id_compare NUMERIC(29),
  compare_stoploss_expected_pmt NUMERIC(31, 2),
  cc_result STRING,
  patient_status STRING,
  admit_type STRING,
  admit_source STRING,
  stoploss_description STRING,
  job_no NUMERIC(29),
  ce_patient_population_id NUMERIC(29),
  is_model_calculated NUMERIC(29),
  claim_id BIGNUMERIC(38) NOT NULL,
  late_charge_claim_id STRING,
  ce_charge_model_id NUMERIC(29),
  mon_practitioner_id NUMERIC(29) NOT NULL,
  is_deleted NUMERIC(29),
  drg_version NUMERIC(29),
  ce_state_tax_profile_id NUMERIC(29),
  state_tax_amt NUMERIC(31, 2),
  ce_interest_profile_id NUMERIC(29),
  interest_amt NUMERIC(31, 2),
  interest_days NUMERIC(29),
  original_drg STRING,
  original_drg_version NUMERIC(29),
  original_drg_type STRING,
  cers_accrual_method_id NUMERIC(29),
  cers_accrual_value NUMERIC(31, 2),
  covered_charges NUMERIC(31, 2) NOT NULL,
  billed_charges NUMERIC(31, 2) NOT NULL,
  comp_method_choice NUMERIC(29),
  calc_base_choice_resolved STRING,
  is_survivor NUMERIC(29),
  amount_due NUMERIC(31, 2),
  date_amount_due_evaluated DATE,
  cob_method_id NUMERIC(29),
  length_of_service NUMERIC(29),
  org_id NUMERIC(29) NOT NULL,
  is_cob_capped NUMERIC(29),
  pre_trans_stoploss_id NUMERIC(29),
  pre_trans_stoploss_exp_pay NUMERIC(31, 2),
  post_trans_stoploss_id NUMERIC(29),
  post_trans_stoploss_exp_pay NUMERIC(31, 2),
  copay_amt NUMERIC(31, 2),
  ce_valuation_profile_id NUMERIC(29),
  drg_severity_level STRING,
  creation_date DATETIME,
  creation_user STRING,
  modification_date DATETIME,
  modification_user STRING,
  icd_vrsn_id NUMERIC(29),
  acct_subterm_amt NUMERIC(31, 2),
  svc_subterm_ttl_amt NUMERIC(31, 2),
  hist_srvr_ind NUMERIC(29),
  err_id BIGNUMERIC(38),
  unins_pct NUMERIC(33, 4),
  dly_dedtbl_amt NUMERIC(31, 2),
  dw_last_update_date DATE
)
CLUSTER BY id, schema_id, mon_account_payer_id;
