-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_cdc_gg.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_cdc_gg_temp
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  org_id_provider NUMERIC(29) NOT NULL,
  account_no NUMERIC(29) NOT NULL,
  date_created DATE NOT NULL,
  drg STRING,
  mon_account_linked_to BIGNUMERIC(38),
  pt_last_name STRING NOT NULL,
  pt_first_name STRING NOT NULL,
  pt_middle_name STRING,
  pt_name_suffix STRING,
  service_date_begin DATETIME NOT NULL,
  service_date_end DATETIME,
  total_charges NUMERIC(31, 2) NOT NULL,
  total_expected_reimb NUMERIC(31, 2),
  total_pt_responsibility NUMERIC(31, 2),
  total_payments NUMERIC(31, 2),
  pt_date_of_birth DATE,
  mon_patient_type_id NUMERIC(29),
  drg_type STRING,
  date_updated DATE,
  admit_source STRING,
  admit_type STRING,
  hipps_code STRING,
  patient_status STRING,
  billing_status STRING,
  date_last_sent_to_calc DATE,
  user_id_last_modified NUMERIC(29),
  patient_identifier STRING,
  financial_class STRING,
  attending_physician_name STRING,
  attending_physician_id STRING,
  referring_physician_name STRING,
  referring_physician_id STRING,
  pt_social_security_no STRING,
  pt_address_line1 STRING,
  pt_address_line2 STRING,
  pt_city STRING,
  pt_state STRING,
  pt_zip STRING,
  pt_phone_number STRING,
  medical_record_number STRING,
  is_professional NUMERIC(29) NOT NULL,
  professional_account_no STRING,
  rendering_physician_name STRING,
  rendering_physician_id STRING,
  rendering_physician_upin STRING,
  rendering_physician_specialty STRING,
  pt_gender STRING,
  onset_date DATE,
  admit_date DATE,
  discharge_date DATE,
  is_outside_lab NUMERIC(29),
  total_lab_charges NUMERIC(31, 2),
  misc_char01 STRING,
  misc_char02 STRING,
  misc_char03 STRING,
  misc_char04 STRING,
  misc_char05 STRING,
  misc_char06 STRING,
  misc_char07 STRING,
  misc_char08 STRING,
  misc_char09 STRING,
  misc_char10 STRING,
  misc_date01 DATE,
  misc_date02 DATE,
  misc_date03 DATE,
  misc_date04 DATE,
  misc_date05 DATE,
  misc_amt01 NUMERIC(31, 2),
  misc_amt02 NUMERIC(31, 2),
  misc_amt03 NUMERIC(31, 2),
  misc_amt04 NUMERIC(31, 2),
  misc_amt05 NUMERIC(31, 2),
  misc_yn01 STRING,
  misc_yn02 STRING,
  misc_yn03 STRING,
  misc_yn04 STRING,
  misc_yn05 STRING,
  total_pt_payments NUMERIC(31, 2),
  total_pt_adjustments NUMERIC(31, 2),
  drg_version NUMERIC(29),
  job_no NUMERIC(29),
  job_no_reprocess NUMERIC(29),
  drg_regrouped STRING,
  drg_type_regrouped STRING,
  drg_version_regrouped NUMERIC(29),
  is_reassignable NUMERIC(29) NOT NULL,
  mon_accounting_period_id NUMERIC(29),
  calc_today_flag STRING,
  billed_charges NUMERIC(31, 2) NOT NULL,
  is_archived NUMERIC(29),
  date_last_user_updated DATE,
  is_ca_extract_stopped NUMERIC(29) NOT NULL,
  is_account_change_trigger NUMERIC(29),
  is_charge_change_trigger NUMERIC(29),
  ipf_per_diem_begin_day INT64,
  drg_severity_level STRING,
  icd10_drg STRING,
  icd10_drg_vrsn NUMERIC(29),
  icd10_drg_severity_level STRING,
  primary_icd_vrsn_id NUMERIC(29),
  dw_last_update_date DATETIME,
  death_date DATE,
  noa_date DATE,
  ora_archive_state STRING
)
CLUSTER BY id, schema_id;
