-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_payer_calc_tri_apc.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_payer_calc_tri_apc
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  cers_term_id NUMERIC(29) NOT NULL,
  mon_acct_payer_calc_summary_id BIGNUMERIC(38) NOT NULL,
  ce_service_id BIGNUMERIC(38) NOT NULL,
  service_date DATE,
  code STRING NOT NULL,
  code_type STRING NOT NULL,
  modifier_1 STRING,
  modifier_2 STRING,
  modifier_3 STRING,
  modifier_4 STRING,
  modifier_5 STRING,
  modifier_6 STRING,
  apc_code STRING NOT NULL,
  quantity NUMERIC(29),
  charge_amount NUMERIC(31, 2),
  cers_rate_calc_method_id NUMERIC(29) NOT NULL,
  expected_payment NUMERIC(31, 2),
  total_quantity NUMERIC(29),
  total_amount NUMERIC(31, 2),
  ce_rule_id NUMERIC(29) NOT NULL,
  ce_tricare_apc_profile_id NUMERIC(29) NOT NULL,
  ce_tricare_apc_group_id NUMERIC(29) NOT NULL,
  ce_tricare_apc_status_ind_id NUMERIC(29) NOT NULL,
  tricare_status_indicator_code STRING NOT NULL,
  tricare_apc_composite_flag NUMERIC(29),
  original_status_ind_code STRING,
  tricare_apc_base_rate NUMERIC(31, 2),
  tricare_apc_rate_mod_rank NUMERIC(29),
  tricare_apc_rate_mod_percent NUMERIC(31, 2),
  tricare_apc_pay_before_ratemod NUMERIC(31, 2),
  low_age NUMERIC(29),
  high_age NUMERIC(29),
  gender STRING,
  patient_age NUMERIC(29),
  patient_gender STRING,
  tricare_apc_cost_charge_ratio NUMERIC(35, 6),
  tricare_apc_cost_sharing_type NUMERIC(29),
  tricare_apc_cost_sharing_value NUMERIC(36, 7),
  national_unadj_payment_rate NUMERIC(31, 2),
  revenue_code STRING,
  tricare_apc_outlier_percent NUMERIC(35, 6),
  tricare_apc_fixed_threshold NUMERIC(35, 6),
  tricare_threshold_multiplier NUMERIC(35, 6),
  tricare_apc_threshold_adj_pay NUMERIC(31, 2),
  adjusted_payment_amount NUMERIC(31, 2),
  tricare_apc_outlier_payment NUMERIC(31, 2),
  tricare_apc_sch_adjustment NUMERIC(35, 6),
  apc_packaged NUMERIC(29),
  service_rank NUMERIC(29),
  apc_fb_fc_offset_amount NUMERIC(31, 2),
  modifier_fb_rate NUMERIC(31, 2),
  modifier_fc_rate NUMERIC(31, 2),
  tricare_apc_labor_portion NUMERIC(31, 2),
  tricare_apc_non_labor_portion NUMERIC(31, 2),
  tricare_apc_labor_rate NUMERIC(35, 6),
  tricare_apc_non_labor_rate NUMERIC(35, 6),
  tricare_apc_wage_index NUMERIC(35, 6),
  tricare_bilateral_disc_formula NUMERIC(29),
  tricare_apc_bilateral_ind NUMERIC(29),
  tricare_cost_sharing_amount NUMERIC(31, 2),
  tri_apc_pay_rate_bef_discount NUMERIC(31, 2),
  highest_paying_record STRING,
  tri_apc_code_source NUMERIC(29),
  is_age_gender_mapped NUMERIC(29),
  tri_apc_bil_disc_fraction NUMERIC(35, 6),
  tri_apc_terminated_proc_disc NUMERIC(35, 6),
  device_charges NUMERIC(31, 2),
  allocated_charges NUMERIC(31, 2),
  tri_cont_enh_rad_offset_amt NUMERIC(31, 2),
  tri_cont_enh_nuclr_offset_amt NUMERIC(31, 2),
  is_radiology_cont_agent_code NUMERIC(29),
  is_nuclear_cont_agent_code NUMERIC(29),
  tri_offset_allocation_percent NUMERIC(31, 2),
  exp_pay_bef_nuc_rad_reduction NUMERIC(31, 2),
  coinsamt_bef_nuc_rad_reduction NUMERIC(31, 2),
  tri_offset_reduction_amount NUMERIC(31, 2),
  creation_date DATETIME,
  creation_user STRING,
  modification_date DATETIME,
  modification_user STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id;
