-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/mon_account_payer_apc_comp_dtl.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.mon_account_payer_apc_comp_dtl
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  mon_acct_payer_calc_summary_id BIGNUMERIC(38) NOT NULL,
  cers_add_on_service_id NUMERIC(29) NOT NULL,
  ce_service_id BIGNUMERIC(38) NOT NULL,
  ce_rule_id NUMERIC(29) NOT NULL,
  ce_rule_type_id NUMERIC(29) NOT NULL,
  ce_apc_profile_id NUMERIC(29) NOT NULL,
  ce_apc_comp_codeset_id NUMERIC(29),
  priority NUMERIC(29),
  description STRING,
  formula_id NUMERIC(29),
  service_date DATE NOT NULL,
  charge_detail_date DATE NOT NULL,
  ce_apc_group_id NUMERIC(29) NOT NULL,
  apc_code STRING NOT NULL,
  ce_status_indicator_id NUMERIC(29),
  exclude_mod1 STRING,
  exclude_mod2 STRING,
  set_type STRING,
  code_type STRING,
  code STRING,
  modifier1 STRING,
  modifier2 STRING,
  quantity NUMERIC(29),
  charge_amount NUMERIC(31, 2),
  status_code STRING,
  modifier STRING,
  apc_composite_flag NUMERIC(29),
  apc_status_indicator_code STRING,
  total_quantity NUMERIC(29),
  total_amount NUMERIC(31, 2),
  apc_national_coinsurance NUMERIC(31, 2),
  apc_minimum_coinsurance NUMERIC(31, 2),
  apc_maximum_units NUMERIC(29),
  device_code_a STRING,
  device_code_b STRING,
  device_code_charges NUMERIC(31, 2),
  packaged NUMERIC(29),
  apc_op_deductible NUMERIC(31, 2),
  national_unadj_payment_rate NUMERIC(31, 2),
  modifier_fb_rate NUMERIC(31, 2),
  modifier_fc_rate NUMERIC(31, 2),
  apc_labor_portion NUMERIC(31, 2),
  apc_non_labor_portion NUMERIC(31, 2),
  apc_sch_adjustment NUMERIC(35, 6),
  apc_bilateral_disc_formula NUMERIC(29),
  apc_benificiary_payment_pct NUMERIC(33, 4),
  apc_wage_adj_copayment_amount NUMERIC(31, 2),
  apc_deductible_amount NUMERIC(31, 2),
  apc_coinsurance_amount NUMERIC(31, 2),
  apc_threshold_adj_payment NUMERIC(31, 2),
  apc_outlier_payment NUMERIC(31, 2),
  original_status_ind_code STRING,
  apc_rural_sch_adjustment NUMERIC(31, 2),
  expected_payment NUMERIC(31, 2),
  apc_bilateral_indicator NUMERIC(29),
  cers_term_id NUMERIC(29),
  apc_fb_fc_offset_amount NUMERIC(31, 2),
  apc_base_rate NUMERIC(31, 2),
  apc_rate_modifier_rank NUMERIC(29),
  apc_rate_modifier_percent NUMERIC(31, 2),
  apc_payment_before_rate_mod NUMERIC(31, 2),
  apc_outlier_percent NUMERIC(31, 2),
  revenue_code STRING,
  modifier3 STRING,
  modifier4 STRING,
  modifier5 STRING,
  modifier6 STRING,
  apc_cont_enh_rad_offset_amt NUMERIC(31, 2),
  apc_cont_enh_nuclr_offset_amt NUMERIC(31, 2),
  is_radiology_cont_agent_code NUMERIC(29),
  is_nuclear_cont_agent_code NUMERIC(29),
  apc_offset_allocation_percent NUMERIC(31, 2),
  exp_pay_bef_nuc_rad_reduction NUMERIC(31, 2),
  coinsamt_bef_nuc_rad_reduction NUMERIC(31, 2),
  apc_offset_reduction_amount NUMERIC(31, 2),
  apc_code_source NUMERIC(29),
  apc_terminated_proc_discount NUMERIC(31, 2),
  apc_bilateral_disc_fraction NUMERIC(35, 6),
  apc_exclude_outlier NUMERIC(29),
  apc_is_deductible_met NUMERIC(29),
  apc_threshold_multiplier NUMERIC(35, 6),
  apc_cost_charge_ratio NUMERIC(35, 6),
  apc_wage_index NUMERIC(35, 6),
  apc_labor_percent NUMERIC(35, 6),
  apc_coinsurance_limit NUMERIC(31, 2),
  apc_fixed_threshold NUMERIC(35, 6),
  offset_rate NUMERIC(31, 2),
  calculated_offset_value NUMERIC(31, 2),
  offset_apc_payment_rate NUMERIC(31, 2),
  apc_code_orig STRING,
  discount_formula_orig STRING,
  apc_rural_hosp_ind INT64,
  creation_date DATE,
  creation_user STRING,
  modification_date DATE,
  modification_user STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id;
