-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/pat_acct_aud.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.pat_acct_aud_temp
(
  pat_acct_aud_id BIGNUMERIC(38) NOT NULL,
  mon_acct_pyr_id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  pat_acct_num NUMERIC(29),
  unit_num STRING,
  clm_num STRING,
  ins_plan STRING,
  rec_id INT64,
  rec_type STRING,
  corp_ctrl STRING,
  ssc_ctrl STRING,
  corp_stts_dt DATE,
  aud_elig STRING,
  aud_stts STRING,
  pre_aud_type STRING,
  post_aud_type STRING,
  othr_aud_type STRING,
  aud_stts_dt DATE,
  pre_aud_drg STRING,
  post_aud_drg STRING,
  pyr_of_aud STRING,
  aud_schd_date DATE,
  expt_aud_fees NUMERIC(31, 2),
  aud_fee_amt_coll NUMERIC(31, 2),
  aud_loc STRING,
  finl_aud_otcm STRING,
  wrk_agn_dt DATE,
  svc_strt_dt DATE,
  svc_end_dt DATE,
  corp_stts STRING,
  addl_proj_fld STRING,
  fndg_ltr_rslt STRING,
  intn_dt DATE,
  ltr_dt DATE,
  rspn_dt DATE,
  mr_trk_id STRING,
  mr_req STRING,
  mr_rls_req_to_roi DATE,
  mr_rls_meth STRING,
  mr_rls_dt DATE,
  mis_mr_notf_dt DATE,
  mis_doc_req STRING,
  pyr_drg STRING,
  pyr_ref_id STRING,
  dlr_at_risk NUMERIC(31, 2),
  dcrp_amt NUMERIC(31, 2),
  rfnd_req_amt NUMERIC(31, 2),
  rfnd_amt NUMERIC(31, 2),
  rfnd_req_rsn STRING,
  rfnd_stts STRING,
  rfnd_stts_dt DATE,
  finl_rfnd_otcm STRING,
  creation_dt DATE,
  creation_user STRING,
  modification_dt DATE,
  modification_user STRING,
  map_to_rec_type STRING,
  map_to_rec_id NUMERIC(29),
  rfnd_prcs_tool_stts STRING
)
CLUSTER BY pat_acct_aud_id, schema_id;
