-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/ra_claim_payment.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.ra_claim_payment
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  ra_group_header_id BIGNUMERIC(38) NOT NULL,
  mon_account_id BIGNUMERIC(38) NOT NULL,
  claim_status_code STRING,
  ttl_claim_charge_amount NUMERIC(31, 2),
  claim_payment_amount NUMERIC(31, 2),
  patient_responsible_amount NUMERIC(31, 2),
  claim_filing_indicat_code STRING,
  payer_claim_control_no STRING,
  facility_type_code STRING,
  claim_frequency_code STRING,
  patient_status_code STRING,
  drg_code STRING,
  drg_weight NUMERIC(33, 4),
  discharge_fraction NUMERIC(31, 2),
  covered_days_visits_count NUMERIC(29),
  pps_operat_outlier_amount NUMERIC(31, 2),
  lifetime_psychiat_day_count NUMERIC(29),
  claim_drg_amount NUMERIC(31, 2),
  remark_code STRING,
  claim_disproport_share_amnt NUMERIC(31, 2),
  claim_msp_pass_through_amnt NUMERIC(31, 2),
  claim_ppscapital_amount NUMERIC(31, 2),
  pps_capital_fsp_drg_amount NUMERIC(31, 2),
  pps_capital_hsp_drg_amount NUMERIC(31, 2),
  pps_capital_dsh_drg_amount NUMERIC(31, 2),
  old_captial_amount NUMERIC(31, 2),
  pps_capital_ime_amount NUMERIC(31, 2),
  pps_opert_hosp_spec_drg_amnt NUMERIC(31, 2),
  cost_report_day_count NUMERIC(29),
  pps_operat_fed_specif_drg_amnt NUMERIC(31, 2),
  claim_pps_capital_outlier_amnt NUMERIC(31, 2),
  claim_indirect_teaching_amount NUMERIC(31, 2),
  nonpay_prof_component_mia_amnt NUMERIC(31, 2),
  remark_code_mia1 STRING,
  remark_code_mia2 STRING,
  remark_code_mia3 STRING,
  remark_code_mia4 STRING,
  pps_capital_exception_amount NUMERIC(31, 2),
  reinbursment_rate NUMERIC(31, 2),
  claim_hcpcs_payable_amount NUMERIC(31, 2),
  remark_code_moa1 STRING,
  remark_code_moa2 STRING,
  remark_code_moa3 STRING,
  remark_code_moa4 STRING,
  remark_code_moa5 STRING,
  claim_esrd_payment_amount NUMERIC(31, 2),
  nonpay_prof_component_moa_amnt NUMERIC(31, 2),
  service_start_date DATE,
  service_end_date DATE,
  coverage_expiration_date DATE,
  received_date DATE,
  actual_covered_days NUMERIC(31, 2),
  actual_coinsured_days NUMERIC(31, 2),
  actual_lifetime_reserve_days NUMERIC(31, 2),
  est_lifetime_reserve_days NUMERIC(31, 2),
  actual_non_covered_days NUMERIC(31, 2),
  est_non_covered_days NUMERIC(31, 2),
  not_replaced_blood_units NUMERIC(31, 2),
  outlier_days NUMERIC(31, 2),
  prescription NUMERIC(31, 2),
  visits NUMERIC(31, 2),
  fed_payment_mandate1 NUMERIC(31, 2),
  fed_payment_mandate2 NUMERIC(31, 2),
  fed_payment_mandate3 NUMERIC(31, 2),
  fed_payment_mandate4 NUMERIC(31, 2),
  fed_payment_mandate5 NUMERIC(31, 2),
  date_created DATE,
  first_name STRING,
  last_name STRING,
  account_no STRING,
  customer_org_id NUMERIC(29),
  header_assigned_number NUMERIC(29),
  patient_id STRING,
  patient_code_qualifier STRING,
  member_id STRING,
  rendering_provider_lastname STRING,
  rendering_provider_firstname STRING,
  rendering_provider_middlename STRING,
  rendering_provider_value STRING,
  rendering_provider_type STRING,
  is_deleted NUMERIC(29),
  replaced_by_ra_id BIGNUMERIC(38),
  claim_id BIGNUMERIC(38),
  confidence_level NUMERIC(29),
  orig_account_no STRING,
  org_id NUMERIC(29),
  orig_org_id NUMERIC(29),
  source_type_id NUMERIC(29),
  mia_moa_type STRING,
  mon_account_payer_id BIGNUMERIC(38) NOT NULL,
  job_no NUMERIC(29),
  ra_number NUMERIC(29),
  drg_severity_level STRING,
  ra_835_profile_id NUMERIC(29),
  activation_status_date DATETIME,
  mon_payer_id NUMERIC(29),
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id;
