-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/ra_group_header.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.ra_group_header_temp
(
  id BIGNUMERIC(38) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  header_assigned_number NUMERIC(29) NOT NULL,
  job_no NUMERIC(29) NOT NULL,
  transact_set_control_no STRING NOT NULL,
  production_date DATE,
  payer_name STRING,
  payer_identifier STRING,
  provider_id STRING,
  facility_type_code STRING,
  fiscal_period_date DATE,
  claim_count NUMERIC(29),
  claim_charge_amount NUMERIC(31, 2),
  denied_charge_amount NUMERIC(31, 2),
  covered_charge_amount NUMERIC(31, 2),
  provider_payment_amount NUMERIC(31, 2),
  non_covered_chrg_amount NUMERIC(31, 2),
  contractual_adjust_amount NUMERIC(31, 2),
  interest_amount NUMERIC(31, 2),
  gramm_rodman_reduction_amnt NUMERIC(31, 2),
  msp_payer_amount NUMERIC(31, 2),
  blood_deductible_amount NUMERIC(31, 2),
  non_lab_charge_amount NUMERIC(31, 2),
  coinsurance_amount NUMERIC(31, 2),
  hcpcs_reported_charge_amnt NUMERIC(31, 2),
  hcpcs_payable_amount NUMERIC(31, 2),
  deductible_amount NUMERIC(31, 2),
  professional_component_amount NUMERIC(31, 2),
  msp_patient_liability_amount NUMERIC(31, 2),
  patient_reimbursement_amount NUMERIC(31, 2),
  pip_claim_count NUMERIC(31, 2),
  pip_adjustment_count NUMERIC(31, 2),
  drg_amount NUMERIC(31, 2),
  federal_specific_amount NUMERIC(31, 2),
  hospital_specific_amount NUMERIC(31, 2),
  capital_amount NUMERIC(31, 2),
  indirect_medical_educat_amnt NUMERIC(31, 2),
  outlier_day_count NUMERIC(31, 2),
  cost_outlier_amount NUMERIC(31, 2),
  average_drg_length_stay NUMERIC(31, 2),
  discharge_count NUMERIC(31, 2),
  cost_report_day_count NUMERIC(31, 2),
  covered_day_count NUMERIC(31, 2),
  non_covered_day_count NUMERIC(31, 2),
  msp_pass_through_amount NUMERIC(31, 2),
  average_drg_weight NUMERIC(31, 2),
  pps_capital_fsp_drg_amount NUMERIC(31, 2),
  pps_capital_hsp_drg_amount NUMERIC(31, 2),
  pps_dsh_drg_amount NUMERIC(31, 2),
  date_created DATE,
  total_disp_share_amount NUMERIC(31, 2),
  total_day_outlier_amount NUMERIC(31, 2),
  interchange_control_number STRING,
  group_control_number STRING,
  check_amount NUMERIC(31, 2),
  check_date DATE,
  check_number STRING,
  provider_name STRING,
  provider_npi STRING,
  provider_tin STRING,
  provider_code_qualifier STRING,
  payer_address STRING,
  payer_address2 STRING,
  payer_city STRING,
  payer_state STRING,
  payer_zip_code STRING,
  payer_contact_name STRING,
  payer_phone_number STRING,
  payer_phone_type STRING,
  payer_sec_phone_number STRING,
  payer_sec_phone_type STRING,
  trans_handling_code STRING,
  industry_identifier_code STRING,
  era_prcr_id STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY id, schema_id;
