-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/reimbursement_discrepancy_wrk1_rd_parallel.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.reimbursement_discrepancy_wrk1_rd_parallel
(
  company_code STRING NOT NULL,
  coid STRING NOT NULL,
  patient_dw_id NUMERIC(29) NOT NULL,
  payor_dw_id NUMERIC(29) NOT NULL,
  iplan_insurance_order_num INT64 NOT NULL,
  eor_log_date DATE NOT NULL,
  log_id STRING NOT NULL,
  log_sequence_num INT64 NOT NULL,
  eff_from_date DATE NOT NULL,
  unit_num STRING NOT NULL,
  pat_acct_num NUMERIC(29) NOT NULL,
  iplan_id INT64,
  length_of_stay_days_num INT64,
  eor_drg_code STRING,
  eor_hipps_code STRING,
  eor_payment_amt NUMERIC(32, 3),
  ar_bill_thru_date DATE NOT NULL,
  remittance_date DATE,
  work_date DATE,
  ra_log_date DATE,
  ra_payment_date DATE,
  ra_drg_code STRING,
  ra_hipps_code STRING,
  ra_covered_days_num INT64,
  ra_total_charge_amt NUMERIC(32, 3),
  ra_payment_amt NUMERIC(32, 3),
  ra_copay_amt NUMERIC(32, 3),
  ra_coinsurance_amt NUMERIC(32, 3),
  ra_contractual_allowance_amt NUMERIC(32, 3),
  ra_net_billed_charge_amt NUMERIC(32, 3),
  ra_gross_reimbursement_amt NUMERIC(32, 3),
  ra_non_covered_charge_amt NUMERIC(32, 3),
  ra_deductible_coinsurance_amt NUMERIC(32, 3),
  ra_deductible_amt NUMERIC(32, 3),
  ra_total_deductible_amt NUMERIC(32, 3),
  ra_blood_deductible_amt NUMERIC(32, 3),
  ra_lab_payment_amt NUMERIC(32, 3),
  ra_therapy_payment_amt NUMERIC(32, 3),
  ra_primary_payor_payment_amt NUMERIC(32, 3),
  ra_outlier_payment_amt NUMERIC(32, 3),
  ra_capital_payment_amt NUMERIC(32, 3),
  ra_denied_charge_amt NUMERIC(32, 3),
  ra_net_apc_service_amt NUMERIC(32, 3),
  ra_net_fee_schedule_amt NUMERIC(32, 3),
  discrepancy_origination_date DATE NOT NULL,
  actual_payment_amt NUMERIC(32, 3),
  pa_total_account_balance_amt NUMERIC(32, 3),
  over_under_payment_amt NUMERIC(32, 3),
  discrepancy_day_cnt INT64,
  var_covered_days_num INT64,
  var_copay_amt NUMERIC(32, 3),
  var_total_charge_amt NUMERIC(32, 3),
  var_covered_charge_amt NUMERIC(32, 3),
  var_non_covered_charge_amt NUMERIC(32, 3),
  var_net_billed_charge_amt NUMERIC(32, 3),
  var_gross_reimbursement_amt NUMERIC(32, 3),
  var_deductible_amt NUMERIC(32, 3),
  var_coinsurance_amt NUMERIC(32, 3),
  var_deductible_coinsurance_amt NUMERIC(32, 3),
  var_blood_deductible_amt NUMERIC(32, 3),
  var_insurance_payment_amt NUMERIC(32, 3),
  var_primary_payor_payment_amt NUMERIC(32, 3),
  var_capital_payment_amt NUMERIC(32, 3),
  var_lab_payment_amt NUMERIC(32, 3),
  var_outlier_payment_amt NUMERIC(32, 3),
  var_therapy_payment_amt NUMERIC(32, 3),
  var_contractual_allowance_amt NUMERIC(32, 3),
  var_net_apc_service_amt NUMERIC(32, 3),
  var_net_fee_schedule_amt NUMERIC(32, 3),
  inpatient_outpatient_ind STRING,
  reason_code_3 STRING,
  calc_id BIGNUMERIC(38),
  account_activity_id BIGNUMERIC(38),
  reason_id NUMERIC(29),
  account_payer_status_id NUMERIC(29),
  dw_last_update_date_time DATETIME,
  source_system_code STRING
)
CLUSTER BY patient_dw_id;
