-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/ssc_denials.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.ssc_denials_temp
(
  schema_id INT64 NOT NULL,
  mon_account_payer_id BIGNUMERIC(38) NOT NULL,
  pass_type STRING NOT NULL,
  coid STRING NOT NULL,
  account_no STRING NOT NULL,
  ssc_id NUMERIC(29),
  rate_schedule_name STRING,
  ssc_name STRING NOT NULL,
  facility_name STRING NOT NULL,
  unit_num STRING NOT NULL,
  rate_schedule_eff_begin_date DATE,
  rate_schedule_eff_end_date DATE,
  patient_name STRING,
  patient_dob DATE,
  iplan_id INT64,
  insurance_provider_name STRING,
  payer_group_name STRING,
  billing_name STRING,
  billing_contact_person STRING,
  authorization_code STRING,
  payer_patient_id STRING,
  payer_rank INT64,
  pa_financial_class STRING,
  payor_financial_class NUMERIC(29),
  accounting_period STRING,
  major_payer_grp STRING,
  reason_code STRING,
  billing_status STRING,
  pa_service_code STRING,
  pa_account_status STRING,
  cc_patient_type STRING,
  pa_discharge_status STRING,
  pa_patient_type STRING,
  cancel_bill_ind STRING,
  admit_source STRING,
  admit_type STRING,
  pa_drg STRING,
  attending_physician_id STRING,
  attending_physician_name STRING,
  service_date_begin DATE,
  discharge_date DATE,
  comparison_method STRING,
  project_name STRING,
  work_queue_name STRING,
  status_category_desc STRING,
  status_desc STRING,
  status_phase_desc STRING,
  calc_date DATE,
  total_charges STRING,
  pa_actual_los STRING,
  total_billed_charges STRING,
  covered_charges STRING,
  total_expected_payment STRING,
  total_expected_adjustment STRING,
  total_pt_responsibility_actual STRING,
  total_variance_adjustment STRING,
  total_payments STRING,
  total_denial_amt STRING,
  payor_due_amt STRING,
  pa_total_account_bal STRING,
  ar_amount STRING,
  otd_to_date_amount STRING,
  writeoff_amt STRING,
  cash_adj_amt STRING,
  max_aplno INT64,
  max_seqno INT64,
  appeal_orig_amt STRING,
  current_appealed_amt STRING,
  current_appeal_balance STRING,
  appeal_date_created DATE,
  sequence_date_created DATE,
  close_date DATE,
  max_seq_deadline_date DATE,
  sequence_creator STRING,
  appeal_owner STRING,
  appeal_modifier STRING,
  disp_code STRING,
  disp_desc STRING,
  web_disp_code INT64,
  root_code STRING,
  root_cause_description STRING,
  root_cause_dtl STRING,
  external_appeal_code STRING,
  apl_appeal_code STRING,
  apl_appeal_desc STRING,
  first_denial_date DATE,
  denial_age INT64,
  pa_denial_update_date DATE,
  first_activity_create_date DATE,
  last_activity_completion_date DATE,
  last_activity_completion_age INT64,
  last_user_activity_create_age INT64,
  last_reason_change_date DATE,
  last_status_change_date DATE,
  last_project_change_date DATE,
  last_owner_change_date DATE,
  activity_due_date DATE,
  activity_desc STRING,
  activity_subject STRING,
  activity_owner STRING,
  appeal_sent_activity_ownr STRING,
  appeal_sent_activity_date DATE,
  appeal_sent_activity_age INT64,
  appeal_sent_activity_subj STRING,
  appeal_sent_activity_desc STRING,
  stratification STRING,
  status_kpi STRING,
  followup_kpi STRING,
  appealsent_kpi STRING,
  deadline_kpi STRING,
  extract_date DATETIME,
  payer_category STRING,
  source_system_code STRING,
  dw_last_update_date DATETIME
)
CLUSTER BY schema_id, mon_account_payer_id, pass_type;
