-- Translation time: 2024-02-16T20:48:08.013760Z
-- Translation job ID: 825ffe95-5d09-4d28-9bed-a2d58826a821
-- Source: internal_metastore/db_hca-hin-dev-cur-parallon/schema_edwra_staging/users.memory
-- Translated from: Teradata
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS {{ params.param_parallon_ra_stage_dataset_name }}.users_temp
(
  user_id NUMERIC(29) NOT NULL,
  schema_id NUMERIC(29) NOT NULL,
  customer_org_id NUMERIC(29),
  first_name STRING,
  last_name STRING,
  usr_title STRING,
  address1 STRING,
  address2 STRING,
  city STRING,
  state STRING,
  zip STRING,
  email STRING,
  phone STRING,
  fax STRING,
  usr_password STRING,
  expire_password_flag NUMERIC(29),
  password_expire DATE,
  status STRING,
  mydays NUMERIC(29),
  manual_entry_fl NUMERIC(29),
  user_analytics_role_old STRING,
  is_active NUMERIC(29),
  login_id STRING,
  user_role STRING NOT NULL,
  force_password_change NUMERIC(29) NOT NULL,
  password_last_modified_date DATE NOT NULL,
  predefined_question STRING,
  answer_to_defined_question STRING,
  default_summary_id NUMERIC(29) NOT NULL,
  date_user_created DATE,
  created_by_user_id NUMERIC(29),
  action_emails NUMERIC(29) NOT NULL,
  monitor_role_old STRING,
  default_access STRING,
  cust_svc NUMERIC(29),
  org_id_affiliate NUMERIC(29),
  department STRING,
  admin_email NUMERIC(29) NOT NULL,
  weekly_collections_goal NUMERIC(29),
  monthly_collections_goal NUMERIC(29),
  calc_engine_role_old STRING,
  contracts_role_old STRING,
  directory_role_old STRING,
  reports_access_old STRING,
  account_view_profile_id NUMERIC(29),
  is_addedit_users NUMERIC(29),
  reports_role_old STRING,
  is_logged_in NUMERIC(29) NOT NULL,
  prof_calc_engine_role_old STRING,
  last_password1 STRING,
  last_password2 STRING,
  password_expires_days NUMERIC(29),
  is_support NUMERIC(29) NOT NULL,
  max_inactive_days_threshold NUMERIC(29) NOT NULL,
  modified_by_user_id NUMERIC(29),
  date_modified DATE,
  dual_access_ind INT64,
  ecp_login_id STRING,
  force_password_modified_date DATETIME,
  is_dashboard_viewer INT64,
  dw_last_update_date DATETIME
)
CLUSTER BY user_id, schema_id;
