create or replace view {{ params.param_hr_bi_views_dataset_name }}.factstepstatus as SELECT
    concat(trim(CAST(fact_step_status.submission_sid as STRING)), trim(CAST(fact_step_status.candidate_profile_sid as STRING))) AS stepstatus_uid,
    fact_step_status.candidate_profile_sid,
    fact_step_status.candidate_profile_num AS taleo_submission_id,
    fact_step_status.candidate_num AS taleo_candidate_id,
    fact_step_status.submission_sid,
    fact_step_status.recruitment_requisition_num_text AS taleo_requisition_num,
    fact_step_status.recruitment_requisition_sid,
    fact_step_status.lawson_requisition_sid AS lawson_requisition_num,
    fact_step_status.ghr_requisition_num,
    fact_step_status.requisition_sid,
    fact_step_status.tracking_step_id,
    fact_step_status.creation_date,
    EXTRACT(TIME FROM fact_step_status.creation_date_time) AS creation_time,
    fact_step_status.completion_date,
    EXTRACT(TIME FROM fact_step_status.completion_date_time) AS completion_time,
    fact_step_status.step_short_name,
    fact_step_status.step_name,
    fact_step_status.submission_status_name,
    fact_step_status.sub_status_desc,
    fact_step_status.moved_by_text,
    fact_step_status.sla_compliance_status_text,
    fact_step_status.step_status_start_date_time AS wf_status_start,
    fact_step_status.step_status_end_date_time  AS wf_status_end,
    fact_step_status.coid,
    concat(coalesce(fact_step_status.coid, '00000'), coalesce(fact_step_status.dept_num, '000')) AS coid_uid,
    fact_step_status.duration_days_cnt AS duration,
    fact_step_status.non_working_day_cnt AS non_working_days,
    fact_step_status.step_seq_num AS wf_row_rank,
    fact_step_status.step_reverted_ind,
    fact_step_status.source_system_code

  FROM
   {{ params.param_hr_base_views_dataset_name }}.fact_step_status 
