--WEEKLY SUMMARY FOR POWER BI    				(UPDATED 11/03/2020)
SELECT 
    (CASE
        WHEN STUSER.CSUAACCESS1 = 'CLIENTCOLL' THEN 'CLIENT-NSFW'
        ELSE 'NASHWEST' END) AS PASID   --PLACEHOLDER UNTIL TABLE CHANGES INTEGRATE
    , 'NASHWEST' AS CSUASSC		--PLACEHOLDER UNTIL TABLE CHANGES INTEGRATE
    , STUSERAUDIT.CSUAMONTHLYREVIEWID, STUSERAUDIT.STUAMONTH, STUSERAUDIT.STUAYEAR, STUSERAUDIT.HCUAREVIEWPERIOD
    , STUSERAUDIT.STUARVWSTART, STUSERAUDIT.STUARVWEND, STUSERAUDIT.STUAID, STUSERAUDIT.STUAUSERID, STUSER.UAFULLNAME
--    , SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS) AS AuditEarnedPoints, SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS) as AuditPossiblePoints
    , (CASE
        WHEN SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS) IS NULL THEN 0
        ELSE SUM(STUSERAUDITACCT.STUAAEARNEDPOINTS)
        END) AS AuditEarnedPoints
    , (CASE
        WHEN SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS) IS NULL THEN 0
        ELSE SUM(STUSERAUDITACCT.STUAAPOSSIBLEPOINTS)
        END) AS AuditPossiblePoints
    , STUSERAUDIT.STUAPHASE
    , (CASE 
        WHEN STUSERAUDIT.CSUASTATUS IS NULL THEN 'PENDING'
        ELSE STUSERAUDIT.CSUASTATUS
        END) AS CSUASTATUS
    , STUSERAUDIT.CSUAUSERRESPONSE
    , NULL AS PRIOR1_WEEK
    , NULL AS PRIOR1_SCORE
    , NULL AS PRIOR2_WEEK
    , NULL AS PRIOR2_SCORE
    , NULL AS PRIOR3_WEEK
    , NULL AS PRIOR3_SCORE   
    , NULL AS PRIOR4_WEEK
    , NULL AS PRIOR4_SCORE     
    , STUSERAUDIT.CSUASCORE, STUSERAUDIT.CSUAGOALPERCENT
    , NULL AS CurrWeekStrat
--    , (CASE
--        WHEN PW1.CSUASCORE IS NULL AND STUSERAUDIT.CSUASCORE = 0 THEN 'SAME'
--        WHEN PW1.CSUASCORE IS NULL AND STUSERAUDIT.CSUASCORE > 0 THEN 'IMPROVEMENT' --IF NO VALUE FOR PREVIOUS WEEK, THEN CURRENT WEEK IS CONSIDERED AN IMPROVEMENT
--        WHEN PW1.CSUASCORE IS NOT NULL AND STUSERAUDIT.CSUASCORE = PW1.CSUASCORE THEN 'SAME' 
--        WHEN PW1.CSUASCORE IS NOT NULL AND STUSERAUDIT.CSUASCORE > PW1.CSUASCORE THEN 'IMPROVEMENT'
--        ELSE 'DECLINE' END) AS CurrWeekStrat
    , STUSERAUDIT.CSUAREVIEWER, REVIEWER.UAFULLNAME AS REVIEWER, STUSERAUDIT.STUASUPERVISORID, 
	SUPERVISOR.UAFULLNAME AS SUPERVISOR, STUSERAUDIT.CSUAREVIEWMTGDTE
FROM ((((SQLUser.STUSERAUDIT STUSERAUDIT LEFT OUTER JOIN SQLUser.STUSERAUDITACCT STUSERAUDITACCT ON STUSERAUDIT.STUAID = STUSERAUDITACCT.STUAAAUDITID)
--    LEFT OUTER JOIN SQLUser.STUSERAUDIT PW1 ON STUSERAUDIT.STUAUSERID=PW1.STUAUSERID AND STUSERAUDIT.STUARVWEND = DATE(DATEADD(d,7,PW1.STUARVWEND)))
--       LEFT OUTER JOIN SQLUser.STUSERAUDITACCT PWACCT1 ON PW1.STUAID = PWACCT1.STUAAAUDITID)
--        LEFT OUTER JOIN SQLUser.STUSERAUDIT PW2 ON STUSERAUDIT.STUAUSERID=PW2.STUAUSERID AND STUSERAUDIT.STUARVWEND=DATE(DATEADD(d,14,PW2.STUARVWEND)))
--          LEFT OUTER JOIN SQLUser.STUSERAUDITACCT PWACCT2 ON PW2.STUAID = PWACCT2.STUAAAUDITID)
--            LEFT OUTER JOIN SQLUser.STUSERAUDIT PW3 ON STUSERAUDIT.STUAUSERID=PW3.STUAUSERID AND STUSERAUDIT.STUARVWEND=DATE(DATEADD(d,21,PW3.STUARVWEND)))
--              LEFT OUTER JOIN SQLUser.STUSERAUDITACCT PWACCT3 ON PW3.STUAID = PWACCT3.STUAAAUDITID)
--                LEFT OUTER JOIN SQLUser.STUSERAUDIT PW4 ON STUSERAUDIT.STUAUSERID=PW4.STUAUSERID AND STUSERAUDIT.STUARVWEND=DATE(DATEADD(d,28,PW4.STUARVWEND)))
--                  LEFT OUTER JOIN SQLUser.STUSERAUDITACCT PWACCT4 ON PW4.STUAID = PWACCT4.STUAAAUDITID)
                      LEFT OUTER JOIN SQLUser.STUSER STUSER ON STUSERAUDIT.STUAUSERID = STUSER.USERID)
                            LEFT OUTER JOIN SQLUser.STUSER REVIEWER ON STUSERAUDIT.CSUAREVIEWER = REVIEWER.USERID)
                                LEFT OUTER JOIN SQLUser.STUSER SUPERVISOR ON STUSERAUDIT.STUASUPERVISORID = SUPERVISOR.USERID)
--            , SQLUser.HCFACILITY HCFACILITY
WHERE STUSERAUDIT.STUARVWEND >= '2020-11-01' AND LEN(STUSERAUDIT.STUAUSERID) = 7
GROUP BY STUSERAUDIT.STUAUSERID, STUSERAUDIT.STUAID