CREATE TABLE IF NOT EXISTS edwpsc.`3m_factprofeeinventory`
(
  profeeinventory3mkey INT64 NOT NULL,
  cacaccountnumber STRING,
  visitnumber STRING,
  visittype STRING,
  facilityid STRING,
  location STRING,
  patientfirstname STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  admitdate DATETIME,
  dischargedate DATETIME,
  servicedatekey DATE,
  servicedatetime DATETIME,
  cacworklistname STRING,
  lookupkey STRING,
  codingstatus STRING,
  codingstatusdatetime DATETIME,
  comment STRING,
  docholdreason STRING,
  holddate DATE,
  holdby STRING,
  careprovider STRING,
  careproviderfirstname STRING,
  careproviderlastname STRING,
  careprovidermiddlename STRING,
  filename STRING,
  filedate DATE,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  coid STRING,
  practiceid STRING,
  openinventoryflag INT64,
  dwlastupdatedatetime DATETIME
)
;