CREATE TABLE IF NOT EXISTS edwpsc.artiva_inventorysnapshotdaily
(
  snapshotdate DATE,
  snapshotdatetime DATETIME NOT NULL,
  sourcesytem STRING NOT NULL,
  hcpatientaccountingnumber STRING,
  ecwclaimkey INT64,
  ecwclaimnumber INT64,
  ecwregionkey INT64,
  pvclaimkey INT64,
  pvclaimnumber INT64,
  pvregionkey INT64,
  hcenid STRING,
  hcacid STRING,
  hcbalance NUMERIC(32, 3),
  liabilitybalance NUMERIC(32, 3),
  primaryfinancialclass STRING NOT NULL,
  liabilityfinancialclass STRING NOT NULL,
  hclastloaddate STRING,
  hclastworkeddate STRING,
  psaccountcomplete NUMERIC(29),
  hccurrentpayerid STRING,
  lastpool STRING,
  hcsequencenumber NUMERIC(29),
  pspooldept STRING,
  pspooltype STRING,
  coid STRING,
  rownum INT64,
  hcmedicalrecordnumber STRING,
  hcdateofservice STRING,
  psecwclaimstatus STRING,
  psacprevpool STRING,
  psaclpoolstartdte DATE,
  hcfinalbilldate STRING,
  hcoriginalbalance NUMERIC(32, 3),
  hctotaladjustments NUMERIC(32, 3),
  hctotalpayments NUMERIC(32, 3),
  hctotalcharges NUMERIC(32, 3),
  hcstatuscode STRING,
  hcdenialcode STRING,
  hcdenialdate STRING,
  hchostbalance NUMERIC(32, 3),
  hcpayername STRING,
  hcactioncode STRING,
  hcresultcode STRING,
  hcworkdate STRING,
  hcvendorid STRING,
  psmiscvalue STRING,
  hcacpriphase STRING,
  hcacpristatus STRING,
  hcaccountphase STRING,
  hcclaimsubmissiondate STRING,
  last_action_code_time TIME,
  last_action_code_user_id STRING,
  last_action_date DATETIME,
  pschecknumber STRING,
  pvpracticename STRING,
  hcfadesc STRING,
  voidflag INT64,
  deleteflag INT64,
  arclaimflag INT64,
  liabilityiplankey INT64,
  liabilityownertype INT64,
  primaryiplankey INT64,
  waitdate STRING,
  totalpaymentamt NUMERIC(33, 4),
  totalinsurancepaymentamt NUMERIC(33, 4),
  pspyclmtype STRING,
  pspygrprptname STRING,
  last_action_code_time2 TIME,
  last_action_code_user_id2 STRING,
  last_action_date2 DATETIME,
  tieramt NUMERIC(33, 4),
  psentierthrshld STRING,
  pspoolconctrlnum STRING,
  dwlastupdatedatetime DATETIME NOT NULL
)
PARTITION BY snapshotdate
;