CREATE TABLE IF NOT EXISTS edwpsc.artiva_stghcpayer
(
  hcpyid STRING NOT NULL,
  hcpyname STRING,
  pspycapitation STRING,
  pspyclmtype STRING,
  pspycpid STRING,
  pspyemail STRING,
  pspygrpcacname STRING,
  pspygrpcacnum STRING,
  pspygrprptname STRING,
  pspygrprptnum STRING,
  pspypayorid STRING,
  pspypaysource STRING,
  pspypaytype STRING,
  pspypritimelydays NUMERIC(29),
  pspysectimelydays NUMERIC(29),
  hcpydeffup NUMERIC(29),
  pspyinactive STRING,
  pspycorrclm STRING,
  pspy1stlvlappldays NUMERIC(29),
  pspy2ndlvlappldays NUMERIC(29),
  pspycarratt STRING,
  pspycarrcont STRING,
  pspycarrname STRING,
  pspycarrph STRING,
  pspycarrphext STRING,
  pspygrpaddr1 STRING,
  pspygrpaddr2 STRING,
  pspygrpartname STRING,
  pspygrpartnum STRING,
  pspygrpatt STRING,
  pspygrpcity STRING,
  pspygrpcont STRING,
  pspygrpfax STRING,
  pspygrpname STRING,
  pspygrpphext STRING,
  pspygrpphone STRING,
  pspygrpstate STRING,
  pspygrpzip STRING,
  pspyprevcpid STRING,
  pspycpidchgdte STRING,
  pspyadd1 STRING,
  hcpycity STRING,
  hcpystate STRING,
  hcpyzip STRING,
  hcpyphone STRING,
  PRIMARY KEY (hcpyid) NOT ENFORCED
)
;