CREATE TABLE IF NOT EXISTS edwpsc.artiva_stgpspeapphist
(
  pspeapphamtfld1 STRING,
  pspeapphamtfld2 STRING,
  pspeapphamtvalfld1 NUMERIC(33, 4),
  pspeapphamtvalfld2 NUMERIC(33, 4),
  pspeapphaviid NUMERIC(29),
  pspeapphdesc STRING,
  pspeapphdte DATETIME,
  pspeapphdtefld1 STRING,
  pspeapphdtefld2 STRING,
  pspeapphdtevalfld1 DATETIME,
  pspeapphdtevalfld2 DATETIME,
  pspeapphfld1 STRING,
  pspeapphfld10 STRING,
  pspeapphfld2 STRING,
  pspeapphfld3 STRING,
  pspeapphfld4 STRING,
  pspeapphfld5 STRING,
  pspeapphfld6 STRING,
  pspeapphfld7 STRING,
  pspeapphfld8 STRING,
  pspeapphfld9 STRING,
  pspeapphfldval1 STRING,
  pspeapphfldval10 STRING,
  pspeapphfldval2 STRING,
  pspeapphfldval3 STRING,
  pspeapphfldval4 STRING,
  pspeapphfldval5 STRING,
  pspeapphfldval6 STRING,
  pspeapphfldval7 STRING,
  pspeapphfldval8 STRING,
  pspeapphfldval9 STRING,
  pspeapphkey NUMERIC(29) NOT NULL,
  pspeapphperfid STRING,
  pspeapphppiid NUMERIC(29),
  pspeapphtime DATETIME,
  pspeapphuserid STRING,
  PRIMARY KEY (pspeapphkey) NOT ENFORCED
)
;