CREATE TABLE IF NOT EXISTS edwpsc.artiva_stgpspegaf
(
  pspegaf501ataxid STRING,
  pspegafaltdesc STRING,
  pspegafartgrpprovid STRING,
  pspegafbillingtype STRING,
  pspegafbillop STRING,
  pspegafbillsys STRING,
  pspegafbustype STRING,
  pspegafdesc STRING,
  pspegafediddte DATETIME,
  pspegafedieraeftddte DATETIME,
  pspegafenrollop STRING,
  pspegafextintbilldte DATETIME,
  pspegafgroupid STRING,
  pspegafgrpprovact STRING,
  pspegafgrpprovid STRING,
  pspegafgrpprovname STRING,
  pspegafgrptaxid STRING,
  pspegafhcapsflg STRING,
  pspegafimgtype STRING,
  pspegafkey STRING NOT NULL,
  pspegafnotifydte DATETIME,
  pspegafnpi STRING,
  pspegafpracttype STRING,
  pspegafsspact STRING,
  pspegafsspdivision STRING,
  pspegafsspfrmdte DATETIME,
  pspegafsspid STRING,
  pspegafssporigasdte DATETIME,
  pspegafssporigdte DATETIME,
  pspegafssptermdte DATETIME,
  pspegafssptermflg STRING,
  pspegafssptermreas STRING,
  pspegafssptodte DATETIME,
  pspegafhighpri STRING,
  pspegafloaddte DATETIME,
  pspegafprilocst STRING,
  pspegafthonly STRING,
  PRIMARY KEY (pspegafkey) NOT ENFORCED
)
;