CREATE TABLE IF NOT EXISTS edwpsc.artiva_stghcaccount
(
  hcacid STRING,
  hcpaymentarrangementid STRING,
  hcauthorizationnumber STRING,
  hcbalance NUMERIC(32, 3),
  hcholdfrombad STRING,
  hcbilldate STRING,
  hcbilltype STRING,
  hcbrokenpromisecount NUMERIC(29),
  hcbrokenpromisedate STRING,
  hcnumberofcalls NUMERIC(29),
  hcamountofcreditcardpayment NUMERIC(32, 3),
  hccertificatenumber STRING,
  hcclaimsubmissiondate STRING,
  hcstatuscode STRING,
  hccontactdate STRING,
  hcnumberofcontacts NUMERIC(29),
  hccostaccounting NUMERIC(32, 3),
  hcpayercoveragefromdate STRING,
  hcpayercoveragetodate STRING,
  hccurrentpayerid STRING,
  hcdeniedbyuser STRING,
  hcdenialcode STRING,
  hcdenialdate STRING,
  hcdenialflag STRING,
  hcestimatedbillamount NUMERIC(32, 3),
  hcencounterid STRING,
  hcearlyoutdate STRING,
  hcexpectedpayment NUMERIC(32, 3),
  hcfacilityid STRING,
  hcfacilityupdateddate STRING,
  hcfinassistid NUMERIC(29),
  hcfinancialclass STRING,
  hcfirstpaydateforarrangement STRING,
  hcgroupname STRING,
  hcgroupnumber STRING,
  hchostbalance NUMERIC(32, 3),
  hcinsuredaddress1 STRING,
  hcinsuredaddress2 STRING,
  hcincludedinpmtarrangement STRING,
  hcinsuredcity STRING,
  hcinsureddateofbirth STRING,
  hcinsuredemploymentstatus STRING,
  hcinsuredgender STRING,
  hceligibilitystatus STRING,
  hcinsuredstate STRING,
  hcinsuredname STRING,
  hcinsuredid STRING,
  hcinternalcontrolnumber NUMERIC(29),
  hcinsuredzip STRING,
  hcinsuredpoename STRING,
  hcinsuredpoefulladdress STRING,
  hcinsuredpoephonenumber STRING,
  hcinsuredrelationtopatient STRING,
  hcinsuredssn STRING,
  hcleadaccountnumber STRING,
  hcletterseries STRING,
  hclastloaddate STRING,
  hclastcontactdate STRING,
  hclastcontacttime STRING,
  hclastpaymentamount NUMERIC(32, 3),
  hclastpaymentdate STRING,
  hcnumberofletterssent NUMERIC(29),
  hcletterseriesstartdate STRING,
  hcletterseriessuspended STRING,
  hcmanuallyprorateddate STRING,
  hcmedicaidpayerflag STRING,
  hcmembername STRING,
  hcmemberid STRING,
  hcmedicalrecordsrequested STRING,
  hcnextletter STRING,
  hcnextletterdate STRING,
  hcoriginalbalance NUMERIC(32, 3),
  hcoriginationdate STRING,
  hcaccountowneruserid STRING,
  hcacpayaddinfo STRING,
  hcpayeraddress1 STRING,
  hcpayeraddress2 STRING,
  hcpaymentamountonarrangement NUMERIC(32, 3),
  hcpaymentarrangementdate STRING,
  hcpayercoverage STRING,
  hcpayercity STRING,
  hcpayereffectivedate STRING,
  hcpayereligibilityphone STRING,
  hcpayereligibilitywebsite STRING,
  hcpayerid STRING,
  hcpayerfaxnumber STRING,
  hcpayerflagfield STRING,
  hcpayername STRING,
  hcnumberofpayments NUMERIC(29),
  hcpayerphonenumber STRING,
  hcpayerpolicyholder STRING,
  hcpayerstate STRING,
  hcpayerpostalcode STRING,
  hcaccountphase STRING,
  hcpayerpolicynumber STRING,
  hcpayerprecertnumber STRING,
  hcpromisedpaymentamount NUMERIC(32, 3),
  hcdatepromisetaken STRING,
  hcpromisedpaymentduedate STRING,
  hcprorateamount NUMERIC(32, 3),
  hcproratepercentofbalance NUMERIC(32, 3),
  hcnumberofpromisestaken NUMERIC(29),
  hcpatientsrelationtoinsured STRING,
  hcpatientstatementtreqdate STRING,
  hcreleasedate STRING,
  hcremainingactivedays NUMERIC(29),
  hcriskassessment NUMERIC(29),
  hcriskassessmentdate STRING,
  hcsequencenumber NUMERIC(29),
  hcaccountsetbalance NUMERIC(32, 3),
  hcnumberofaccountsinset NUMERIC(29),
  hctermdate STRING,
  hcaccounttieid STRING,
  hctotaladjustments NUMERIC(32, 3),
  hctotalallowances NUMERIC(32, 3),
  hctotalvarcharges NUMERIC(32, 3),
  hctotalcontractualadj NUMERIC(32, 3),
  hctotalpayments NUMERIC(32, 3),
  hctotalwriteoffs NUMERIC(32, 3),
  hctotaltime NUMERIC(32, 3),
  hcdateassignedtovendor STRING,
  hcminimumbalancepercentage NUMERIC(32, 3),
  hcvendorbatchid STRING,
  hcvendorclosedate STRING,
  hcamountcollectedbyvendor NUMERIC(32, 3),
  hcfeespaidtovendor NUMERIC(32, 3),
  hcvendorlastpaymentamount NUMERIC(32, 3),
  hcvendorlastpaymentdate STRING,
  hcminimumpayments NUMERIC(29),
  hcvendorid STRING,
  hcnetbackamount NUMERIC(32, 3),
  hcplacementackdate STRING,
  hcplacementamount NUMERIC(32, 3),
  hcplacementbatch STRING,
  hcplacementdate STRING,
  hcplacementlevel NUMERIC(29),
  hcnumberofvepayments NUMERIC(29),
  hcrecallacknowledgementdate STRING,
  hcrecallamount NUMERIC(32, 3),
  hcdaysinrecallreviewperiod NUMERIC(29),
  hcrecalldate STRING,
  hcrecallobjectiondate STRING,
  hcnumberofobjections NUMERIC(29),
  hcrecallreason STRING,
  hcrecallrequestdate STRING,
  hcreturnedamount NUMERIC(32, 3),
  hcreturndate STRING,
  hcreturnedreason STRING,
  hcvendorstatuscode STRING,
  hcvendorstatuscodedate STRING,
  hcaccountfollowupdate STRING,
  hcworkdate STRING,
  hcworkflow STRING,
  psbulkcheckamount NUMERIC(32, 3),
  pscheckdate STRING,
  pschecknumber STRING,
  psexpectedcheckarrivaldate STRING,
  psgin STRING,
  psinternalcontrolnumber STRING,
  psinsuranceclassforreports STRING,
  psinsurancedetailid NUMERIC(29),
  psecwinsuredid STRING,
  psinsuranceplannumber STRING,
  lastpool STRING NOT NULL,
  psmedicallicensenumber STRING,
  psnpi STRING,
  psbillinglockboxoverrideaddr1 STRING,
  psbillinglockboxoverrideaddr2 STRING,
  psbillinglockboxoverridecity STRING,
  psbillinglockboxoverridestate STRING,
  psbillinglockboxoverridezip STRING,
  pspayerstatus1 STRING,
  pspayerstatusdate STRING,
  pssourceofpayment STRING,
  psptan STRING,
  psreferralnumber STRING,
  psresubmissioncode STRING,
  psresubmissionindicator STRING,
  pspayerstatusrootcause STRING,
  pstaxid STRING,
  pstaxonomy STRING,
  pstotalofpstradjustamt NUMERIC(32, 3),
  pstotalofpstrwithheldamt NUMERIC(32, 3),
  psaccountcomplete NUMERIC(29),
  hcactioncode STRING,
  hcresultcode STRING,
  psacsubsecondqual STRING,
  psacsubsecondid STRING,
  psacpolnum STRING,
  psacpayersecondqual STRING,
  psacpayersecondid STRING,
  psacipoephext STRING,
  psacipoe STRING,
  psacinsurmnm STRING,
  psacinsurlnm STRING,
  psacinsuraltmidinit STRING,
  psacinsuraltlname STRING,
  psacinsuraltfname STRING,
  psacinsuractaltmid STRING,
  psacinsuractaltlnm STRING,
  psacinsuractaltfnm STRING,
  psacinstype STRING,
  psacinsdeleted STRING,
  psacecwinsid STRING,
  psacecwactinstype STRING,
  psacclmfilingind STRING,
  psacaltptmname STRING,
  psacaltptlname STRING,
  psacaltptfname STRING,
  hcaceovendid STRING,
  hcacpristatus STRING,
  hcacpriphase STRING,
  psdatebalancepopulated DATE,
  psacprevpool STRING,
  psaclpoolstartdte DATE,
  psaclookaheaddte DATE,
  psaclookaheaduser STRING,
  psacvepristat STRING,
  psvendorstatuscode STRING,
  psacextvepristat STRING,
  psextvendorstatuscode STRING,
  psextvendorstatuscodedate DATE,
  psacvelinkedind STRING,
  psachpsubcatid NUMERIC(29),
  psacmulticnflag STRING,
  psamiscvalue STRING,
  psaceraicn STRING,
  psacuntimelytype STRING,
  psacuntimelyqdate STRING,
  psachruid NUMERIC(29),
  psacintfinclass STRING,
  psacintpriority STRING,
  psacpasid STRING,
  psaccrosssubdte STRING,
  psacintvenplc STRING,
  psacpoolescltdacct STRING,
  psacapplsntdte STRING,
  psacdocsntdte STRING,
  psac277icn STRING
)
;