CREATE TABLE IF NOT EXISTS edwpsc.artiva_factgroup
(
  artivagrouprowkey INT64 NOT NULL,
  artivagroupkey STRING NOT NULL,
  groupid STRING,
  groupname STRING,
  groupdba STRING,
  grouptaxid STRING,
  groupnpi STRING,
  groupactiveflag STRING,
  groupenrollmentoperation STRING,
  groupstartdate DATE,
  groupenddate DATE,
  groupterminationdate DATE,
  groupterminationreason STRING,
  groupterminationflag STRING,
  groupbusinesstype STRING,
  grouppracticetype STRING,
  groupbillingtype STRING,
  grouphcapspractice STRING,
  group501ataxid STRING,
  groupsspdivision STRING,
  groupbillingsystem STRING,
  groupbillingoperation STRING,
  groupbillingexternaltointernaldate DATE,
  groupimagingtype STRING,
  grouporiginationdate DATE,
  groupprovidername STRING,
  groupprovideractiveflag STRING,
  grouperaeftdelaydate DATE,
  groupedidelaydate DATE,
  grouporiginalasofdate DATE,
  groupnotificationdate DATE,
  daysbetweengroupnotificationandstartdate INT64,
  grouphighpriorityflag STRING,
  grouplastloaddate DATE,
  groupprimarylocationstate STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (artivagroupkey) NOT ENFORCED
)
;