CREATE TABLE IF NOT EXISTS edwpsc.artiva_stgpsholdrulesutility
(
  pshrcpid STRING,
  pshrcpt STRING,
  pshrdiagnosis STRING,
  pshrecwrptgrp STRING,
  pshrfinclass STRING,
  pshrmodifier STRING,
  pshruactdte DATETIME,
  pshruactive STRING,
  pshrucpid STRING,
  pshrucrtdte DATETIME,
  pshrucrttime TIME,
  pshrucrtuser STRING,
  pshrudesc STRING,
  pshrudiagcd STRING,
  pshruenddte DATETIME,
  pshrufinclass STRING,
  pshruglobalflag STRING,
  pshrugroupid STRING,
  pshruholdcode STRING,
  pshrukey NUMERIC(29) NOT NULL,
  pshrulocationid STRING,
  pshrulstchangedte DATETIME,
  pshrumod STRING,
  pshrupayorid STRING,
  pshrupractid STRING,
  pshruproccd STRING,
  pshruproviderid STRING,
  pshrureasoncd STRING,
  pshrureldte DATETIME,
  pshruruletype STRING,
  pshrusource STRING,
  pshrusrvenddte DATETIME,
  pshrusrvstartdte DATETIME,
  pshrustatus STRING,
  pshrutotclmamt NUMERIC(31, 2),
  pshrutotclmonhold NUMERIC(29),
  PRIMARY KEY (pshrukey) NOT ENFORCED
)
;