CREATE TABLE IF NOT EXISTS edwpsc.artiva_stghcsubunit
(
  hcsuadr1 STRING,
  hcsuadr2 STRING,
  hcsucity STRING,
  hcsufacilityid STRING,
  hcsufaxph STRING,
  hcsufilterid STRING,
  hcsuid STRING,
  hcsuname STRING,
  hcsunum STRING,
  hcsuph STRING,
  hcsuspwf STRING,
  hcsust STRING,
  hcsutpwf STRING,
  hcsutz STRING,
  hcsuwebsite STRING,
  hcsuzip STRING,
  pssubilladdr1 STRING,
  pssubilladdr2 STRING,
  pssubillcity STRING,
  pssubillfax STRING,
  pssubillph STRING,
  pssubillst STRING,
  pssubillzip STRING,
  pssucliaid STRING,
  pssudeleteflg STRING,
  pssuevalcoidmstrerte STRING,
  pssufacnote STRING,
  pssufactype STRING,
  pssufedtaxid STRING,
  pssumammocertid STRING,
  pssuname STRING,
  pssunpi STRING,
  pssupayableto STRING,
  pssupos STRING,
  pssusiteassessdte DATETIME,
  pssustartdte DATETIME,
  pssutaxonomy STRING,
  pssucliniccode STRING,
  pssuclinicnpi STRING,
  pssuclinicnum STRING,
  pssuworkcmpfrm STRING
)
;