CREATE TABLE IF NOT EXISTS edwpsc.artiva_factholdrules
(
  artivaholdruleskey INT64 NOT NULL,
  holdruleid NUMERIC(29) NOT NULL,
  ppikey STRING,
  holdruleactiveflag STRING,
  holdcode STRING,
  holdcodedescription STRING,
  holdcodetype STRING,
  holdcodepriority NUMERIC(29),
  holdrulestatus STRING,
  holdrulename STRING,
  holdrulegrouptaxid STRING,
  holdrulegroupname STRING,
  holdruleproviderid STRING,
  holdruleproviderfullname STRING,
  holdruleprovidernpi STRING,
  holdrulepracticeid STRING,
  holdrulepracticename STRING,
  holdrulepracticeaddressline1 STRING,
  holdrulepracticeaddressline2 STRING,
  holdrulefacilityid STRING,
  holdrulefacilityname STRING,
  holdrulefacilityaddressline1 STRING,
  holdrulefacilityaddressline2 STRING,
  holdrulepayorid STRING,
  holdrulepayorname STRING,
  holdrulecpid STRING,
  holdrulecpiddescription STRING,
  holdrulefinancialclass STRING,
  holdruleecwreportinggroup STRING,
  holdruleservicestartdate DATE,
  holdruleserviceenddate DATE,
  holdrulecptcode STRING,
  holdrulemodifier STRING,
  holdrulediagnosiscode STRING,
  holdruleactivationdate DATE,
  holdruleenddate DATE,
  holdrulereleasedate DATE,
  holdrulelastchangeddate DATE,
  holdrulecreateddate DATE,
  holdrulecreatedby STRING,
  holdrulecreatedtime TIME,
  holdrulesource STRING,
  holdrulereason STRING,
  holdruleglobalflag STRING,
  holdruletotalclaimsonhold INT64,
  holdruletotalbalanceonhold NUMERIC(33, 4),
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  holdcoderiskreportflag STRING,
  PRIMARY KEY (artivaholdruleskey) NOT ENFORCED
)
;