CREATE TABLE IF NOT EXISTS edwpsc.artiva_stghcfacility
(
  hcfaid STRING NOT NULL,
  hcfadesc STRING,
  hcfaadr1 STRING,
  hcfaadr2 STRING,
  hcfacity STRING,
  hcfast STRING,
  hcfazip STRING,
  hcfafaxph STRING,
  hcfaph NUMERIC(29),
  psfasiteid STRING,
  psfagroupnpi STRING,
  psfataxonomy STRING,
  psfaspecialty STRING,
  psfaname STRING,
  psfacoidnum STRING,
  psfaorgid NUMERIC(29),
  psfaorgname STRING,
  psfaemail STRING,
  psfalockboxadr1 STRING,
  psfalockboxadr2 STRING,
  psfalockboxcty STRING,
  psfalockboxst STRING,
  psfalockboxzip STRING,
  psfaclosedflag STRING,
  psfaclosedte STRING,
  psfaclosetype STRING,
  hcfapasid STRING,
  hcpsdesc STRING,
  psfaietreroute STRING,
  psfaietactdte STRING,
  psfaautocharge STRING,
  psfaenvironment STRING,
  PRIMARY KEY (hcfaid) NOT ENFORCED
)
;