CREATE TABLE IF NOT EXISTS edwpsc.artiva_factect
(
  artivaectkey INT64 NOT NULL,
  ectid INT64 NOT NULL,
  ppikey STRING,
  ectrequesttype STRING,
  ectrequestdescription STRING,
  ectinitialchangeflag STRING,
  ectsource STRING,
  ectroute STRING,
  ectescalationlevel STRING,
  ectpriority STRING,
  ectcreateddate DATE,
  ectcreatedtime TIME,
  ectupdateddate DATE,
  ectexportdate DATE,
  ectcompletedflag STRING,
  ectnewmessagesflag STRING,
  ectnewdocumentsflag STRING,
  ectcloseddate DATE,
  ectclosedtime TIME,
  ectclosedmessage STRING,
  ectstatus STRING,
  ectassignedto STRING,
  ectoriginalsignaturerequiredflag STRING,
  ectcarrier STRING,
  ecttrackingnumber STRING,
  ectinstructions STRING,
  ectactiveflag STRING,
  ectcarriernoteflag STRING,
  ectclosedactiongroup STRING,
  ectclosedreason STRING,
  ectcloseduser STRING,
  ectdeletedflag STRING,
  ectescalationdate1 DATE,
  ectescalationdate2 DATE,
  ectinstructionscopiedflag STRING,
  ectmessage STRING,
  ectnotes STRING,
  ectguid STRING,
  ectportalid STRING,
  ectrequestcode STRING,
  ectupdatetype STRING,
  ectfirstescalationdays STRING,
  ectsecondescalationdays STRING,
  ectrequestlockedflag STRING,
  ectlastmessagedate DATE,
  ectlastmessagesource STRING,
  ectlastmessageuser STRING,
  ectlastmessagetext STRING,
  ectfirstmessagedate DATE,
  ectfirstmessagesource STRING,
  ectfirstmessageuser STRING,
  ectfirstmessagetext STRING,
  daysbetweenectcreatedandcloseddate INT64,
  daysbetweenectcreatedandcloseddateagingbucket STRING,
  dayssinceectupdateddate INT64,
  dayssinceectupdateddateagingbucket STRING,
  ecteffectivedateofchange DATE,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  ecttypeindicator STRING,
  dayssinceectcreateddate INT64,
  providerkey STRING,
  groupkey STRING,
  ppicpidpayorid STRING,
  ectpool STRING,
  ectlastpool STRING,
  ectstatuschangedate DATETIME,
  dayssinceectstatusdate INT64,
  dayssinceectstatusdateagingbucket STRING,
  PRIMARY KEY (artivaectkey) NOT ENFORCED
)
;