CREATE TABLE IF NOT EXISTS edwpsc.ccu_factsnapshotpkinventory
(
  ccupkinventoryhistorykey INT64 NOT NULL,
  snapshotdate DATE,
  ccupkinventorykey INT64 NOT NULL,
  sourceaprimarykeyvalue STRING,
  pkregionname STRING,
  accountid STRING,
  servicedate DATE,
  billingproviderfirstname STRING,
  billingproviderlastname STRING,
  billingproviderusername STRING,
  billingproviderusernumber STRING,
  billingprovidernpi STRING,
  billingproviderdeleteflag STRING,
  pkfinancialnumber STRING,
  billingareanumber STRING,
  billingdepartmentid STRING,
  coid STRING,
  patientmrn STRING,
  visitid STRING,
  visitlocation STRING,
  visittype STRING,
  reasonforvisit STRING,
  modifieddate DATE,
  ccugolivestatus STRING,
  ccugolivedate DATE,
  assignedtovendor STRING,
  vendorname STRING,
  vendorassigneddate DATE,
  owner STRING,
  sourcesystem STRING,
  inventorytype STRING,
  groupassignment STRING,
  loaddate DATE,
  dayssincemodifieddate INT64,
  dayssinceservicedate INT64,
  worked INT64,
  workeddate DATE,
  regionkey INT64,
  ccunoncustomerconfigkey INT64,
  editflag STRING,
  ccunoncustomernpiconfigkey INT64,
  procedurecategory1 STRING,
  procedurecategory2 STRING,
  cptcodes STRING,
  encounterid INT64,
  visittypekey INT64,
  billingareaname STRING,
  daysopen INT64,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dischargedate DATETIME,
  holdingbincategory STRING,
  cptmodifiers STRING,
  icdcodes STRING
)
PARTITION BY snapshotdate
;