CREATE TABLE IF NOT EXISTS edwpsc.ccu_factsnapshotpvinventory
(
  ccupvinventoryhistorykey INT64 NOT NULL,
  snapshotdate DATE,
  ccupvinventorykey INT64 NOT NULL,
  regionkey INT64,
  facilitykey INT64,
  coid STRING,
  assignedtovendor STRING,
  vendorname STRING,
  vendorassigneddate DATE,
  servicedate DATE,
  servicingproviderkey INT64,
  servicingproviderspecialty STRING,
  servicingproviderspecialtycategory STRING,
  vendorassigned STRING,
  claimlastupdateddate DATE,
  dayssinceclaimlastupdateddate INT64,
  claimnumber STRING,
  totalchargesamt NUMERIC(33, 4),
  totalbalanceamt NUMERIC(33, 4),
  totalinsurancebalanceamt NUMERIC(33, 4),
  holdcode STRING,
  encounterid INT64,
  sourcesystem STRING,
  owner STRING,
  inventorytype STRING,
  groupassignment STRING,
  claimkey INT64,
  visittypekey INT64,
  visitstatuskey INT64,
  patientkey INT64,
  loaddate DATE,
  worked INT64,
  workeddate DATE,
  ccunoncustomerconfigkey INT64,
  encounterkey INT64,
  sourcelastupdateddatetime DATETIME,
  ccunoncustomernpiconfigkey INT64,
  procedurecategory1 STRING,
  procedurecategory2 STRING,
  cptcodes STRING,
  daysopen INT64,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  cptmodifiers STRING,
  icdcodes STRING
)
PARTITION BY snapshotdate
;