CREATE TABLE IF NOT EXISTS edwpsc.ccu_factepiccodequality
(
  codequalitykey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  patientmrn STRING,
  patientinternalid INT64,
  visitnumber INT64,
  transactionnumber_combined STRING,
  regionkey INT64,
  coid STRING,
  servicedate DATE,
  claimcreatedate DATE,
  initialcoderprebilleditdate DATE,
  firstinsurancebilldate DATE,
  minfirstdenialeradate DATE,
  numberofinsurancebills INT64,
  coderprebilleditcount INT64,
  workqueue_name_initial_combined STRING,
  payer1iplanname STRING,
  qualitycategory STRING,
  totalchargesamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  contractualadjamt NUMERIC(33, 4),
  financialadjamt NUMERIC(33, 4),
  financialadjcategory_combined STRING,
  financialadjname_combined STRING,
  firstdenialcategories STRING,
  firstdenialcarccodes STRING,
  firstdenialrarccodes STRING,
  firstdenialpayername STRING,
  coder34id STRING,
  coder STRING,
  coderdept STRING,
  codercompany STRING,
  claimcount INT64,
  dwlastupdatedatetime DATE NOT NULL,
  sourcesystemcode STRING,
  hashnomatch INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  lastchangedby INT64,
  changeddate DATE
)
;