CREATE TABLE IF NOT EXISTS edwpsc.ccu_rprtepicclaimsummarydx
(
  systemname STRING,
  regionname STRING,
  dosprovidername STRING,
  providerspeciality STRING,
  dosprovideruname STRING,
  claimnumber INT64,
  encounterid INT64,
  encountercount INT64 NOT NULL,
  billingarea STRING,
  coidspecialty STRING,
  coid STRING NOT NULL,
  claimcoid STRING,
  regionkey INT64,
  encounterdate DATE,
  lasttoucheddateyyyymm STRING,
  emrdxsvsclaimdxs STRING NOT NULL,
  dxcodechange STRING NOT NULL,
  encounterdxcode STRING,
  claimdxcode STRING,
  lastchangedby34dept STRING,
  billingnotes STRING,
  patientaccountnumber STRING,
  financialnumber STRING,
  patientname STRING,
  encounterdateyyyymm STRING,
  encountercoidlob STRING,
  encountercoidsublob STRING,
  dwlastupdatedate DATE NOT NULL,
  visitnumber INT64,
  transactionnumbercombined STRING,
  patientinternalidcombined STRING,
  lasttoucheddate DATE,
  dwlastupdatedatetime DATE NOT NULL
)
;