CREATE TABLE IF NOT EXISTS edwpsc.ccu_factcodequality
(
  codequalitykey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  regionkey INT64,
  coid STRING,
  servicedate DATE,
  claimcreatedate DATE,
  initialcoderprebilleditdate DATE,
  firstinsurancebilldate DATE,
  minfirstdenialeradate DATE,
  numberofinsurancebills INT64,
  coderprebilleditcount INT64,
  psscactgrp_initial_combined STRING,
  pssccat_initial_combined STRING,
  psscsubcatdesc_initial_combined STRING,
  payer1iplanname STRING,
  qualitycategory STRING,
  totalchargesamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  contractualadjamt NUMERIC(33, 4),
  financialadjamt NUMERIC(33, 4),
  financialadjcategory_combined STRING,
  financialadjname_combined STRING,
  firstdenialcategories STRING,
  firstdenialcarccodes STRING,
  firstdenialrarccodes STRING,
  firstdenialpayername STRING,
  claimcreatedby34id STRING,
  claimcreatedbyuser STRING,
  claimcreatedbydept STRING,
  claimcreatedbycompany STRING,
  claimcount INT64,
  dwlastupdatedatetime DATE NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  lastchangedby INT64,
  changeddate DATE
)
;