CREATE TABLE IF NOT EXISTS edwpsc.ccu_rprtcodermanagerreference
(
  codermanagerreferencekey INT64 NOT NULL,
  employeenumber STRING,
  `34id` STRING,
  ecwusername STRING,
  sharepointusername STRING,
  employee STRING,
  managerii STRING,
  manageri STRING,
  reportrequired STRING,
  specialty STRING,
  hourlybenchmark FLOAT64,
  title STRING,
  status STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  sharepointdatemodified DATETIME,
  sharepointdatecreated DATETIME,
  `group` STRING,
  area STRING,
  directors STRING,
  manager STRING,
  termdate DATETIME,
  coderstatus STRING,
  subspecialty STRING,
  comments STRING,
  sharepointcreatedby STRING,
  sharepointmodifiedby STRING,
  lastname STRING,
  firstname STRING
)
;