CREATE TABLE IF NOT EXISTS edwpsc.ccu_factmedaxioninventory
(
  ccumedaxioninventorykey INT64 NOT NULL,
  sourcesystem STRING,
  owner STRING,
  regionkey INT64,
  coid STRING,
  ccugolivestatus STRING,
  ccugolivedate DATE,
  assignedtovendor STRING,
  vendorname STRING,
  vendorassigneddate DATE,
  practicekey INT64,
  facilitykey INT64,
  encounterid STRING,
  servicedate DATE,
  patientkey INT64,
  servicingproviderkey INT64,
  servicingproviderspecialty STRING,
  servicingproviderspecialtycategory STRING,
  visitstatusdescription STRING,
  encounterlockeddate DATE,
  inventorytype STRING,
  claimvsencounterflag STRING,
  sourcelastupdateddatetime DATETIME,
  groupassignment STRING,
  servicedateconsolidationdateflag STRING,
  pos STRING,
  encountermedaxionkey INT64,
  loaddate DATE,
  worked INT64,
  workeddate DATE,
  encounterlastmodifieddate DATE,
  dayssincemodifieddate INT64,
  dayssinceservicedate INT64,
  busincessdayssinceservicedate INT64,
  busincessdayssincelastmodified INT64,
  procedurecategory1 STRING,
  procedurecategory2 STRING,
  cptcodes STRING,
  ccunoncustomerconfigkey INT64,
  ccunoncustomernpiconfigkey INT64,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  cptmodifiers STRING,
  icdcodes STRING
)
;