CREATE TABLE IF NOT EXISTS edwpsc.ccu_factnonproductivty
(
  ccunonproductivitykey INT64 NOT NULL,
  nonproductivitydate DATE,
  user34 STRING,
  codername STRING,
  coderstatus STRING,
  chargesentered INT64,
  totaldenials INT64,
  totalclaims INT64,
  totalcptcodes INT64,
  encounterstatuschange NUMERIC(31, 2),
  productivitynotes STRING,
  systemoutages NUMERIC(31, 2),
  systemoutagedescriptions STRING,
  itrequestnumber STRING,
  meetings NUMERIC(31, 2),
  meetingsdescriptions STRING,
  education NUMERIC(31, 2),
  educationdescriptions STRING,
  chargeentry NUMERIC(31, 2),
  specialprojects NUMERIC(31, 2),
  dftinterfacechargeentry NUMERIC(31, 2),
  waitingoncharges NUMERIC(31, 2),
  meetingsnonconsolidated NUMERIC(31, 2),
  meetingsnonconsolidateddescriptions STRING,
  assistingpracticefrontofficetask NUMERIC(31, 2),
  assistingpracticedescriptions STRING,
  rebillpracticedenials NUMERIC(31, 2),
  formulanonproductivity NUMERIC(31, 2),
  nonproductiontimenotes STRING,
  createddate DATETIME,
  createdby STRING,
  modifieddate DATETIME,
  sourcesystem STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;