CREATE TABLE IF NOT EXISTS edwpsc.ccu_factsnapshotmedaxioninventory
(
  ccumedaxioninventoryhistorykey INT64 NOT NULL,
  snapshotdate DATE,
  ccumedaxioninventorykey INT64 NOT NULL,
  regionkey INT64,
  regionname STRING,
  coid STRING,
  claimkey INT64,
  patientmrn STRING,
  accountid STRING,
  servicedate DATE,
  createddate DATE,
  daysinworkqueue INT64,
  dayssinceservicedate INT64,
  totalbalanceamt NUMERIC(33, 4),
  liabilityiplankey INT64,
  liabilityfinancialclass INT64,
  liabilityfinancialclassname STRING,
  liabilityiplanname STRING,
  medaxionfinancialclass INT64,
  medaxionfinancialclassdesc STRING,
  servicingprovidername STRING,
  servicingproviderkey INT64,
  servicingprovidernpi STRING,
  facilityname STRING,
  claimnumber INT64,
  facilitykey INT64,
  visittypekey INT64,
  visitstatuskey INT64,
  encounterid STRING,
  encounterkey INT64,
  encounterlockflag STRING,
  ccugolivestatus STRING,
  ccugolivedate DATE,
  assignedtovendor STRING,
  vendorname STRING,
  vendorassigneddate DATE,
  owner STRING,
  groupassignment STRING,
  sourcesystem STRING,
  loaddate DATE,
  worked INT64,
  workeddate DATE,
  servicedatestr STRING,
  workqueueid STRING,
  workqueuetype STRING,
  workqueuename STRING,
  enteredworkqueuedate DATE,
  workqueuetab STRING,
  ccunoncustomernpiconfigkey INT64,
  ccunoncustomerconfigkey INT64,
  procedurecategory1 STRING,
  procedurecategory2 STRING,
  cptcodes STRING,
  workqueues STRING,
  daysopen INT64,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  cptmodifiers STRING,
  icdcodes STRING
)
PARTITION BY snapshotdate
;