CREATE TABLE IF NOT EXISTS edwpsc.ccu_rprtclaimsummarymeditech
(
  ccuclaimsummaryid INT64 NOT NULL,
  sourcesystemcode STRING NOT NULL,
  dosproviderkey INT64,
  dosprovideruname STRING,
  dosproviderlastname STRING,
  dosproviderfirstname STRING,
  visitnumber STRING,
  claimnumber_combined STRING,
  encounterid_combined STRING,
  encountercoid STRING,
  claimcoid STRING,
  encounterkey_combined STRING,
  claimkey_combined STRING,
  regionkey INT64,
  servicedatekey DATE,
  recentchangeddate DATE,
  encounterprocedurecodecombined STRING,
  claimprocedurecodecombined STRING,
  emrcptsvsclaimcpts STRING,
  unitqtychanged STRING,
  emrcodeestvalue NUMERIC(33, 4),
  claimcodeestvalue NUMERIC(33, 4),
  codechangeimpact NUMERIC(33, 4),
  lastchangedby34combined STRING,
  lastchangedbynamecombined STRING,
  lastchangedbydeptcombined STRING,
  lastchangedbycompanynamecombined STRING,
  comments STRING,
  patientmrncombined STRING,
  patientlastname STRING,
  patientfirstname STRING,
  codechangeimpactdirection STRING,
  inscopecategories STRING,
  lastchangedbydeptflag STRING,
  ccuflag STRING,
  encounterdateyyyymm STRING,
  claimfromservicedateyyyymm STRING,
  lasttoucheddateyyyymm STRING,
  encountercoidlob STRING,
  encountercoidsublob STRING,
  h2uflag STRING,
  dwlastupdatedatetime DATE NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;