CREATE TABLE IF NOT EXISTS edwpsc.cmt_facttreasurybatchdetail
(
  batchid STRING,
  batchdate DATETIME,
  depositdate DATETIME,
  checkreference STRING,
  amount NUMERIC(31, 2),
  bankaccount STRING,
  bankreference STRING,
  description STRING,
  bankname STRING,
  payername STRING,
  coid STRING,
  taxid INT64,
  lockboxnumber INT64,
  location STRING,
  locationid INT64,
  batchstate INT64,
  batchstatedesc STRING,
  transactiontype INT64,
  transactiontypedesc STRING,
  batchhistoryid INT64,
  userid STRING,
  historyreasonid INT64,
  historyreasondescription STRING,
  notes STRING,
  updatedate DATETIME,
  receivername STRING,
  paymentinformation STRING,
  regionid STRING,
  checkoreftnumber STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  batchdetailid INT64,
  dwlastupdatedatetime DATETIME
)
;