CREATE TABLE IF NOT EXISTS edwpsc.cmt_factbankfile
(
  bankfilekey INT64 NOT NULL,
  bankfileid INT64 NOT NULL,
  dataimportid INT64 NOT NULL,
  bankname STRING NOT NULL,
  depositdate DATETIME NOT NULL,
  account STRING NOT NULL,
  datatype STRING,
  baicode INT64 NOT NULL,
  amount NUMERIC(33, 4) NOT NULL,
  customerreference INT64,
  bankreference STRING,
  description STRING,
  appenddate DATETIME NOT NULL,
  createbatchid STRING,
  boadescid INT64 NOT NULL,
  payername STRING,
  entrydescription STRING,
  receiverid STRING,
  originatorid STRING,
  standardentryclasscode STRING,
  paymentinformation STRING,
  tracetypecode STRING,
  checkoreftflag STRING,
  checkoreftnumber STRING,
  payeridnumber STRING,
  originatingcompanysupplementalcode STRING,
  notes STRING,
  batchid STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (bankfilekey) NOT ENFORCED
)
;