CREATE TABLE IF NOT EXISTS edwpsc.ecw_factconcuitycalcdetail
(
  concuitycalcdetailkey INT64 NOT NULL,
  loadid INT64,
  loaddetail STRING,
  actiontaken STRING,
  actionstatus STRING,
  actiondatekey DATETIME,
  calcinitrequestid INT64,
  accountnumber STRING,
  unitnumber STRING,
  practitioner STRING,
  payercode STRING,
  totalexpectedpaymentamt NUMERIC(33, 4),
  detailtype STRING,
  amount NUMERIC(33, 4),
  rate NUMERIC(33, 4),
  servicedescription STRING,
  servicetype STRING,
  cptunits NUMERIC(33, 4),
  additionaldescription STRING,
  cptcode STRING,
  cptstartservicedatekey DATETIME,
  cptendservicedatekey DATETIME,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  quantity NUMERIC(33, 4),
  cptcharges NUMERIC(33, 4),
  baserate NUMERIC(33, 4),
  interestamt NUMERIC(33, 4),
  statetaxamt NUMERIC(33, 4),
  expectedpaymentamt NUMERIC(33, 4),
  active INT64,
  claimkey INT64,
  claimlinechargekey INT64,
  coid STRING,
  regionkey INT64,
  sourceprimarykeyvalue INT64,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;