CREATE TABLE IF NOT EXISTS edwpsc.ecw_allclaimscube
(
  claimnumber INT64 NOT NULL,
  ecwregionid INT64,
  coid STRING,
  coidname STRING,
  coidandcoidname STRING,
  groupname STRING,
  divisionname STRING,
  marketname STRING,
  lineofbusiness STRING,
  claimagebyclaimfilestatuslastchangedate INT64,
  claimagebydateofservice INT64,
  claimagebylastbilleddate INT64,
  claimagebylastreleasedate INT64,
  claimagingbucketbydateofservice STRING,
  claimagingbucketbydateofservicesortorder INT64,
  claimarcategory STRING,
  claimarsubcategory STRING,
  claimbalancebucket STRING,
  claimbalancebucketsortorder INT64,
  claimbalancepercentadjudicated STRING,
  claimcascodesfromecw STRING,
  claimcascodesfromera STRING,
  claimcreditbalance STRING,
  claimdate DATE,
  claimfilestatusid STRING,
  claimfilestatuslastchangedate DATE,
  claimfilestatusname STRING,
  claimietactive STRING,
  claimietactivecbo STRING,
  claimietactivepractice STRING,
  claimlastbilledcategory STRING,
  claimlastbilleddate DATE,
  claimlastinsurancepaymentdate DATE,
  claimlastpatientpaymentdate DATE,
  claimowner STRING,
  claimremarkcodes STRING,
  claimzerobalance STRING,
  dateofservice DATE,
  facilityid INT64,
  facilityname STRING,
  facilityplaceofservicecode INT64,
  ins1insurancepayerfinancialclassname STRING,
  ins1insurancepayerfinancialclassnum STRING,
  ins1insurancepayergroupname STRING,
  ins1insurancepayerid INT64,
  ins1insurancepayername STRING,
  ins1insurancepriorauthnumber STRING,
  ins2insurancepayerfinancialclassname STRING,
  ins2insurancepayerfinancialclassnum STRING,
  ins2insurancepayergroupname STRING,
  ins2insurancepayerid INT64,
  ins2insurancepayername STRING,
  ins2insurancepriorauthnumber STRING,
  ins3insurancepayerfinancialclassname STRING,
  ins3insurancepayerfinancialclassnum STRING,
  ins3insurancepayergroupname STRING,
  ins3insurancepayerid INT64,
  ins3insurancepayername STRING,
  liabilityownerfinancialclassname STRING,
  liabilityownerfinancialclassnum STRING,
  liabilityownergovernmentindicator STRING,
  liabilityownerid INT64,
  liabilityownerindicator STRING,
  liabilityownername STRING,
  liabilityownerpayergroupname STRING,
  patientfirstname STRING,
  patientid INT64,
  patientlastname STRING,
  patientmiddlename STRING,
  practicegroupnpi STRING,
  practiceid INT64,
  practicename STRING,
  practicesiteid STRING,
  practicestate STRING,
  practicetaxid STRING,
  referringproviderid INT64,
  referringprovidername STRING,
  referringproviderupin STRING,
  relayhealthedienrollmenterror STRING,
  relayhealthfirstreleasedate DATE,
  relayhealthfirstsubmissiondate DATE,
  relayhealthholdcode STRING,
  relayhealthholdstatus STRING,
  relayhealthlast277responsecategorycode STRING,
  relayhealthlast277responsecategorydescription STRING,
  relayhealthlast277responsedate DATE,
  relayhealthlast277responsepayername STRING,
  relayhealthlastreleasedate DATE,
  relayhealthlastsubmissiondate DATE,
  renderingproviderid INT64,
  renderingprovidername STRING,
  renderingprovidernpi STRING,
  renderingprovidersamestoreindicator STRING,
  renderingproviderspecialty STRING,
  renderingprovidersubspecialty STRING,
  renderingprovidertaxonomycode STRING,
  renderingproviderupin STRING,
  servicingproviderid INT64,
  servicingprovidername STRING,
  servicingprovidernpi STRING,
  servicingproviderspecialty STRING,
  servicingprovidersubspecialty STRING,
  servicingprovidertaxonomycode STRING,
  servicingproviderupin STRING,
  virtualvisitflag STRING,
  virtualvisittype STRING,
  dos_month STRING,
  dos_year INT64,
  dos_year_month STRING,
  adjustmentsadministration NUMERIC(33, 4),
  adjustmentsbaddebt NUMERIC(33, 4),
  adjustmentscapitation NUMERIC(33, 4),
  adjustmentscharity NUMERIC(33, 4),
  adjustmentscontractual NUMERIC(33, 4),
  adjustmentsdenial NUMERIC(33, 4),
  adjustmentsescheat NUMERIC(33, 4),
  adjustmentsinterest NUMERIC(33, 4),
  adjustmentsnsf NUMERIC(33, 4),
  adjustmentsrefund NUMERIC(33, 4),
  adjustmentsuninsured NUMERIC(33, 4),
  balanceinsuranceliability NUMERIC(33, 4),
  balanceonhold NUMERIC(33, 4),
  balancepatientliability NUMERIC(33, 4),
  claimcount INT64 NOT NULL,
  paymentsinsurance NUMERIC(33, 4),
  paymentspatient NUMERIC(33, 4),
  totaladjustments NUMERIC(33, 4),
  totalbalance NUMERIC(33, 4),
  totalcharges NUMERIC(33, 4),
  totalpayments NUMERIC(33, 4),
  patientkeeperclaim STRING
)
;