CREATE TABLE IF NOT EXISTS edwpsc.ecw_factietv2detail
(
  ietv2detailkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  coid STRING,
  ageindays INT64,
  resolved INT64,
  instructionsadditionaldetail STRING,
  type STRING,
  resolvedby STRING,
  resolveddatekey DATE,
  resolvedtime TIME,
  resolution STRING,
  claimcasecreatedatekey DATE,
  claimcasecreatetime TIME,
  daysatpractice INT64,
  fieldname STRING,
  lastmodifiedby STRING,
  lastmodifieddatekey DATETIME,
  lastmodifiedtime TIME,
  ismanual INT64,
  payername STRING,
  reportname STRING,
  errornumber INT64,
  subcategoryname STRING,
  errormessage STRING,
  placeofservicecode STRING,
  totalbalance NUMERIC(29),
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  claimerrortypedescription STRING,
  deleted BOOL,
  closurecategory STRING,
  latestquestiondate DATETIME,
  latestanswerdate DATETIME,
  closeddate DATETIME,
  isatcbo INT64,
  sourcedepartment STRING,
  latestquestion STRING,
  latestanswer STRING,
  claimqueryid STRING,
  claimcaseid STRING,
  claimaction STRING,
  subcategoryid INT64,
  claimstatus STRING,
  cptcode STRING,
  createdby STRING,
  subcategoryoriginid STRING,
  categoryname STRING,
  fullclaimnumber STRING,
  PRIMARY KEY (ietv2detailkey) NOT ENFORCED
)
;