CREATE TABLE IF NOT EXISTS edwpsc.ecw_factnbtglcoiddepartmentprovider
(
  nbtglcoiddepartmentproviderkey INT64 NOT NULL,
  glperiod STRING,
  coid INT64,
  providerdepartmentno INT64,
  coiddepartmentproviderrelationship STRING,
  coiddepartmentproviderspecialtycode STRING,
  coiddepartmentproviderspecialtydescription STRING,
  coiddepartmentproviderspecialtytype STRING,
  coiddepartmentrelationship STRING,
  coiddepartmentspecialtycode STRING,
  coiddepartmentspecialtydescription STRING,
  coiddepartmentspecialtytype STRING,
  coiddepartmentcompensationtype STRING,
  coiddepartmentisapproved BOOL,
  coiddepartmentisbudgetcc BOOL,
  coiddepartmentname STRING,
  coiddepartmentproviderassignedstartdate DATETIME,
  coiddepartmentproviderisapproved BOOL,
  coiddepartmentproviderlastupdatedate DATETIME,
  coiddepartmentproviderlastupdatedbyuserid STRING,
  coiddepartmentproviderstatus STRING,
  coiddepartmentproviderstatuschangedate DATETIME,
  coiddepartmentstartdate DATETIME,
  ancillarydepartmentno INT64,
  budgetstartdate DATETIME,
  communitystatus STRING,
  contractpaysconversiondate DATETIME,
  contractcompensationtype STRING,
  contractcurrentlypays STRING,
  contracteffectivedate DATETIME,
  contractexpirationdate DATETIME,
  fte NUMERIC(31, 2),
  ishospitalist BOOL,
  ismultipleproviderdepartment BOOL,
  newreplacement STRING,
  overheaddepartmentno INT64,
  practiceestablishedthrough STRING,
  productivityreason STRING,
  productivitylevelfuture STRING,
  productivityleveltoday STRING,
  productivitystatus STRING,
  datechangedtoproductivity DATETIME,
  technicallevel STRING,
  projectedterminationdate DATETIME,
  providerstrategydescription STRING,
  providerstrategytypereason STRING,
  terminationreason STRING,
  terminationresult STRING,
  terminationtype STRING,
  upin STRING,
  practiceid INT64,
  providerid INT64,
  coiddepartmentid INT64,
  coiddepartmentproviderid INT64,
  contractid INT64,
  ohallocation INT64,
  allocationtypedescription STRING,
  coiddepartmentproviderstatusid INT64,
  coiddepartmentcompensationtypeid INT64,
  providerdeviationstatusid STRING,
  providerdeviationstatusdescription STRING,
  morproviderstatusid INT64,
  morproviderstatus STRING,
  morproviderstatusdetailid INT64,
  morproviderstatusdetailname STRING,
  signonbonus NUMERIC(33, 4),
  relocationexpensebonus NUMERIC(33, 4),
  annualstayincentive NUMERIC(33, 4),
  coiddepartmentnbtspecialtycategoryid INT64,
  coiddepartmentnbtspecialtycategorydesc STRING,
  coiddepartmentprovidernbtspecialtycategoryid INT64,
  coiddepartmentprovidernbtspecialtycategorydesc STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (nbtglcoiddepartmentproviderkey) NOT ENFORCED
)
;