CREATE TABLE IF NOT EXISTS edwpsc.ecw_factnbtglcompanymaster
(
  nbtglcompanymasterkey INT64 NOT NULL,
  glperiod STRING,
  coid INT64,
  coidname STRING,
  consind BOOL,
  divisionno INT64,
  divisionname STRING,
  groupno INT64,
  groupname STRING,
  hbpaffiliationtypedescription STRING,
  hbpaffiliationtypeid INT64,
  hospitalno INT64,
  hospitalname STRING,
  jvflag BOOL,
  lob STRING,
  marketno INT64,
  marketname STRING,
  sublob STRING,
  coidstartdate DATETIME,
  hbpprogramstartdate DATETIME,
  arsystem STRING,
  coidstatusid INT64,
  coidstatus STRING,
  coidstatusdetailid INT64,
  coidstatusdetail STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (nbtglcompanymasterkey) NOT ENFORCED
)
;