CREATE TABLE IF NOT EXISTS edwpsc.ecw_rprtosc
(
  osckey INT64 NOT NULL,
  ecwclaimnumber STRING,
  accountnumber STRING,
  encounterid STRING,
  accountphase STRING,
  statuscode STRING,
  lastpoolaccountwasinatpoolbuild STRING,
  previouspoolkey STRING,
  lastpoolstartdate DATE,
  pooltype STRING,
  pooldept STRING,
  pooldescription STRING,
  poolsubgroup STRING,
  poolfunction STRING,
  poolsla INT64,
  payersequencenumber NUMERIC(29),
  payerid STRING,
  payername STRING,
  billdate STRING,
  claimsubmissiondate STRING,
  lastpoolstartage INT64 NOT NULL,
  subcataccountbalance BIGNUMERIC(41, 3) NOT NULL,
  responseage INT64 NOT NULL,
  subcategorystatuscode STRING,
  subcategorycode STRING,
  subcategorydescription STRING,
  subcategorysourcedept STRING,
  subcategorycreatedate STRING,
  subcategoryresponsedate STRING,
  subcategoryquestiondate STRING,
  servicedate STRING,
  ecwclaimstatus STRING,
  ecwclaimstatusdescription STRING,
  specialinternalagency STRING,
  placeofservice STRING,
  placeofservicedesc STRING,
  claimbalance BIGNUMERIC(41, 3) NOT NULL,
  renderingproviderfullname STRING,
  renderingprovidernpi STRING,
  ecwregion INT64,
  ecwgroup STRING,
  ecwdivision STRING,
  ecwmarket STRING,
  ecwcoid STRING,
  ecwpractice STRING,
  ecwfacility STRING,
  payorgroupname STRING,
  payorfinclass STRING,
  payorcpid STRING,
  payorcactusgroup STRING,
  payorprimarytimelydays NUMERIC(29),
  payorsecondarytimelydays NUMERIC(29),
  payordeffup NUMERIC(29),
  payorcorrclm STRING,
  payor1stlevelappealdays NUMERIC(29),
  payor2ndlevelappealdays NUMERIC(29),
  payorcapitationflag STRING,
  payorinactiveflag STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (osckey) NOT ENFORCED
)
;