CREATE TABLE IF NOT EXISTS edwpsc.ecw_fact53rdpatienttransaction
(
  patienttransactionkey INT64 NOT NULL,
  sourceprimarykeyvalue INT64,
  transactiontype STRING,
  method STRING,
  channel STRING,
  biller STRING,
  patientname STRING,
  practicename STRING,
  patientkey INT64,
  patientaccountnumber STRING,
  confirmationnumber STRING,
  paymentcreateddate DATE,
  paymentdate DATE,
  accounttype STRING,
  totalpaymentamount NUMERIC(33, 4),
  paymentstatus STRING,
  paymenttime STRING,
  settledtime STRING,
  addressline1 STRING,
  zip STRING,
  pmtaccounttype STRING,
  lastfourdigits STRING,
  avsresponse STRING,
  cvvresponse STRING,
  stdentryclass STRING,
  revreasonorccauth STRING,
  userid STRING,
  loginid STRING,
  customerid STRING,
  csrrep STRING,
  coid STRING,
  billerremittancefield1 STRING,
  billerremittancefield2 STRING,
  billerremittancefield3 STRING,
  billerremittancefield5 STRING,
  sourcefilename STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (patienttransactionkey) NOT ENFORCED
)
;