CREATE TABLE IF NOT EXISTS edwpsc.ecw_factrhexception
(
  rhexceptionkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  coid STRING,
  importdatekey DATE,
  rhexceptionclaimid STRING,
  rhexceptionlastname STRING,
  rhexceptionfirstname STRING,
  rhexceptionmi STRING,
  rhexceptionclaimdatekey DATE,
  rhexceptioncontrolnumber STRING,
  rhexceptiontotalamt NUMERIC(33, 4),
  rhexceptionpayorname STRING,
  rhexceptionattphys STRING,
  rhexceptionfieldname STRING,
  rhexceptionerrdata STRING,
  rhexceptiondescription STRING,
  rhexceptionstmtthrudatekey DATE,
  rhexceptionrootid STRING,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (rhexceptionkey) NOT ENFORCED
)
;