CREATE TABLE IF NOT EXISTS edwpsc.ecw_factclaim
(
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  coid STRING NOT NULL,
  regionkey INT64 NOT NULL,
  claimdatekey DATE NOT NULL,
  servicedatekey DATE NOT NULL,
  patientkey INT64 NOT NULL,
  guarantorpatientkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  paytoproviderkey INT64 NOT NULL,
  supervisorproviderkey INT64 NOT NULL,
  addprovider1providerkey INT64 NOT NULL,
  addprovider2providerkey INT64 NOT NULL,
  liabilitydatekey DATE NOT NULL,
  billedtoid INT64,
  billedtotype INT64,
  facilitykey INT64 NOT NULL,
  claimstatuskey INT64 NOT NULL,
  encounterkey INT64 NOT NULL,
  encounterid INT64 NOT NULL,
  totalchargesamt NUMERIC(33, 4) NOT NULL,
  totalbalanceamt NUMERIC(33, 4) NOT NULL,
  totalpatientbalanceamt NUMERIC(33, 4) NOT NULL,
  totalinsurancebalanceamt NUMERIC(33, 4) NOT NULL,
  totalpatientbalanceminuspatientiplansamt NUMERIC(33, 4) NOT NULL,
  totalpaymentsamt NUMERIC(33, 4) NOT NULL,
  totalinsurancepaymentsamt NUMERIC(33, 4) NOT NULL,
  totalpatientpaymentsamt NUMERIC(33, 4) NOT NULL,
  totaladjustmentsamt NUMERIC(33, 4) NOT NULL,
  totaluncoveredamt NUMERIC(33, 4) NOT NULL,
  totalallowedamt NUMERIC(33, 4) NOT NULL,
  totalpatientresponsibilityamt NUMERIC(33, 4) NOT NULL,
  totalestimatedpatientbalanceamt NUMERIC(33, 4) NOT NULL,
  totalpaymentsandadjustmentsamt NUMERIC(33, 4) NOT NULL,
  voidflag INT64 NOT NULL,
  deleteflag INT64 NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  claimcreatedbyuserkey INT64 NOT NULL,
  claimqueueid INT64,
  referringproviderkey INT64 NOT NULL,
  referringproviderid STRING,
  referringprovidertype STRING,
  copay NUMERIC(33, 4) NOT NULL,
  arclaimflag INT64 NOT NULL,
  payer1iplankey INT64 NOT NULL,
  voidedclaimreversedclaimnumber INT64,
  voidedclaimcopyclaimnumber INT64,
  voidedclaimoriginalclaimnumber INT64,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourceachangedflag INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  claimlock STRING,
  claimtypeflag INT64,
  accidentindflag STRING,
  accidentstate STRING,
  accidenthour STRING,
  accidentrel STRING,
  symindflag STRING,
  symdatekey DATE,
  emprelated STRING,
  admitdatekey DATE,
  dischargedatekey DATE,
  splpgmid STRING,
  epsdtreferral STRING,
  epsdtrefsts STRING,
  crimerelatedflag STRING,
  docsentdatekey DATE,
  pwk06 STRING,
  pregindctorflag STRING,
  relinfodatekey DATE,
  relinfoind STRING,
  labchargesamt NUMERIC(33, 4),
  labindflag STRING,
  patientid INT64,
  servicingproviderid INT64,
  renderingproviderid INT64,
  paytoproviderid INT64,
  supervisorproviderid INT64,
  addprovider1providerid INT64,
  addprovider2providerid INT64,
  facilityid INT64,
  practiceid INT64,
  claimcreatedbyid INT64,
  deptcode STRING,
  payer1iplanid INT64,
  payer1financialclasskey INT64,
  payer2iplankey INT64,
  payer2iplanid INT64,
  payer2financialclasskey INT64,
  payer3iplankey INT64,
  payer3iplanid INT64,
  payer3financialclasskey INT64,
  collectionstatus STRING,
  collectioncodechangedate STRING,
  collectioncode STRING,
  collectioncodechangedatedate DATE,
  collectionstatusaging INT64,
  fullclaimnumber STRING,
  practicekey INT64,
  fullclaimnumberoriginal STRING,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL,
  anesthesiaflag INT64,
  archivedrecord STRING NOT NULL,
  PRIMARY KEY (claimkey) NOT ENFORCED
)
;