CREATE TABLE IF NOT EXISTS edwpsc.ecw_factclaimlinefinancialadjustment
(
  claimlinefinancialadjustmentskey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  claimadjustmentkey INT64 NOT NULL,
  claimlinechargeskey INT64,
  adjustmentamt NUMERIC(33, 4),
  deleteflag INT64,
  createddatekey DATE,
  createdtime TIME,
  createdbyuserkey INT64,
  modifieddatekey DATE,
  modifiedtime TIME,
  modifiedbyuserkey INT64,
  sourceprimarykeyvalue INT64,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  cptid INT64,
  cptcode STRING,
  cptcodekey INT64,
  cptcharges NUMERIC(31, 2),
  cptdeleteflag INT64,
  adjustmentcodekey INT64,
  claimadjustmentamt NUMERIC(33, 4),
  claimadjustmentdatekey DATE,
  claimadjustmentdeleteflag INT64,
  adjcode STRING,
  adjustmentcategorykey INT64,
  archivedrecord STRING NOT NULL
)
;