CREATE TABLE IF NOT EXISTS edwpsc.ecw_factnbtprovider
(
  nbtproviderkey INT64 NOT NULL,
  snapshotdatekey DATE,
  monthid INT64,
  hcpdwid NUMERIC(29),
  gldepartmentnum STRING,
  coid STRING,
  companycode STRING,
  ancillarydeptnum STRING,
  assignedstartdatekey DATE,
  budgetcoid STRING,
  budgetohdeptnum STRING,
  budgetstartdatekey DATE,
  coiddeptname STRING,
  coiddeptstartdatekey DATE,
  coiddepttermdatekey DATE,
  coidstartdatekey DATE,
  communitystatus STRING,
  compensationtype STRING,
  srcsyscompensationtypekey INT64,
  contractexpirationdatekey DATE,
  contractrenewaldatekey DATE,
  developmenttypename STRING,
  srcsysdevelopmentkey INT64,
  birthdatekey DATE,
  effectivedatekey DATE,
  providerfirstname STRING,
  fte NUMERIC(32, 3),
  isbudgetind STRING,
  ishospitalistind STRING,
  ismultipleproviderdeptind STRING,
  providerlastname STRING,
  providermiddleinitial STRING,
  newreplacedind STRING,
  newreplacedname STRING,
  overheadallocation STRING,
  originalstartdatekey DATE,
  providernpi STRING,
  providerkey INT64,
  practiceaddress1 STRING,
  practiceaddress2 STRING,
  practicecity STRING,
  practicefax STRING,
  practicemanagerfirstname STRING,
  practicemanagerlastname STRING,
  practicename STRING,
  srcsyspracticenum INT64,
  practicephone STRING,
  practicestate STRING,
  practicezip STRING,
  projectedterminationdatekey DATE,
  providerheadcount INT64,
  srcsysproviderkey INT64,
  relationshipind INT64,
  socialsecuritynum STRING,
  specialtycode STRING,
  specialtyname STRING,
  specialtytype STRING,
  terminationreasonname STRING,
  terminationtypename STRING,
  terminationtypeid INT64,
  terminationresults STRING,
  upin STRING,
  status INT64,
  datasourcecode STRING,
  createddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (nbtproviderkey) NOT ENFORCED
)
PARTITION BY snapshotdatekey
;