CREATE TABLE IF NOT EXISTS edwpsc.ecw_factsnapshotfinancialadjustmentline
(
  adjustmentlinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  adjustmentcodekey INT64 NOT NULL,
  iplan1iplankey INT64 NOT NULL,
  practicekey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  claim_number INT64 NOT NULL,
  gldepartmentnum STRING,
  patientid INT64,
  servicingproviderid INT64,
  renderingproviderid INT64,
  facilityid INT64,
  practiceid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1id INT64,
  financialclasskey STRING,
  encounterid INT64,
  adjustmentlineid INT64 NOT NULL,
  adjustmentid INT64 NOT NULL,
  cptid INT64 NOT NULL,
  cptcode STRING,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cptorder INT64,
  cptdeleletedline INT64,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  adjustmentlinecreatedate DATETIME,
  adjustmentlinemodifieddate DATETIME,
  adjustmentclaimcreatedate DATETIME,
  adjustmentclaimmodifieddate DATETIME,
  regionkey INT64,
  coid STRING,
  adjustmentcode STRING,
  adjustmentclaimamt NUMERIC(33, 4),
  adjustmentclaimunpostedcptamt NUMERIC(33, 4),
  adjustmentclaimunpostedamt NUMERIC(33, 4),
  cptunits NUMERIC(33, 4),
  cptchargesamt NUMERIC(33, 4),
  adjustmentlineamt NUMERIC(33, 4),
  claimlinechargekey INT64
)
PARTITION BY snapshotdate
;