CREATE TABLE IF NOT EXISTS edwpsc.ecw_junceradetail
(
  ecweradetailkey INT64 NOT NULL,
  regionkey INT64,
  fileid INT64,
  paymentid INT64,
  payorname STRING,
  providername STRING,
  postedby INT64,
  postedbyuserkey INT64,
  posteddate DATETIME,
  st02 STRING,
  transactiontype STRING,
  transactionamount NUMERIC(33, 4),
  transactionmethod STRING,
  transactiondate STRING,
  transactionnumber STRING,
  deletedby INT64,
  deletedbyuserkey INT64,
  deleteddate DATETIME,
  deletedreason STRING,
  payorid INT64,
  payoriplankey INT64,
  providerid INT64,
  providerkey INT64,
  storderid INT64,
  gsorderid INT64,
  isaorderid INT64,
  postingmessage STRING,
  deleteflag INT64,
  sourceprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;