CREATE TABLE IF NOT EXISTS edwpsc.ecw_rprtaccountingvaluation
(
  snapshotdate DATE,
  groupname STRING,
  divisionname STRING,
  marketname STRING,
  coid STRING,
  coidname STRING,
  coidandcoidname STRING,
  servicingprovidername STRING,
  ins1payerfinancialclassnum INT64,
  ins1inspayerfinancialclassname STRING,
  ins1inspayergroupname STRING,
  resolvedclaimcharges NUMERIC(33, 4),
  resolvedcontractualadjustments NUMERIC(33, 4),
  resolvedadministrationadjustments NUMERIC(33, 4),
  resolveddenialadjustments NUMERIC(33, 4),
  resolvedinsurancepayments NUMERIC(33, 4),
  resolvedpatientpayments NUMERIC(33, 4),
  unresolvedclaimchargescredit NUMERIC(33, 4),
  unresolvedcontractualadjustmentscredit NUMERIC(33, 4),
  unresolvedadministrationadjustmentscredit NUMERIC(33, 4),
  unresolveddenialadjustmentscredit NUMERIC(33, 4),
  unresolvedinsurancepaymentscredit NUMERIC(33, 4),
  unresolvedpatientpaymentscredit NUMERIC(33, 4),
  unresolvedinsurancebalancecredit NUMERIC(33, 4),
  unresolvedpatientbalancecredit NUMERIC(33, 4),
  unresolvedclaimchargesdebit NUMERIC(33, 4),
  unresolvedcontractualadjustmentsdebit NUMERIC(33, 4),
  unresolvedadministrationadjustmentsdebit NUMERIC(33, 4),
  unresolveddenialadjustmentsdebit NUMERIC(33, 4),
  unresolvedinsurancepaymentsdebit NUMERIC(33, 4),
  unresolvedpatientpaymentsdebit NUMERIC(33, 4),
  unresolvedinsurancebalancedebit NUMERIC(33, 4),
  unresolvedpatientbalancedebit NUMERIC(33, 4),
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
PARTITION BY snapshotdate
;