CREATE TABLE IF NOT EXISTS edwpsc.ecw_rprtmorstats
(
  snapshotdate DATE,
  monthid INT64,
  morstatskey INT64 NOT NULL,
  id INT64,
  morcoid STRING,
  coidnameonly STRING,
  coidname STRING,
  coidlob STRING,
  coidsublob STRING,
  lobname STRING,
  marketname STRING,
  marketkey INT64,
  divisionname STRING,
  divisionkey INT64,
  groupname STRING,
  groupkey INT64,
  coidspecialty STRING,
  centerdescription STRING,
  centerkey INT64,
  gldepartmentnumber STRING,
  snapshotyearmonth STRING,
  securitycoid STRING NOT NULL,
  coid STRING,
  coidlargepractice STRING NOT NULL,
  coidprogramtype STRING NOT NULL,
  appspecialtycategory STRING NOT NULL,
  provideroriginalstartstatus STRING NOT NULL,
  provideroriginalstartdate STRING NOT NULL,
  coidstartdatekey STRING NOT NULL,
  coidtermdatekey STRING NOT NULL,
  hospitalcoid STRING NOT NULL,
  hospitalname STRING NOT NULL,
  providername STRING NOT NULL,
  providernpi STRING NOT NULL,
  specialtycode STRING NOT NULL,
  specialtyname STRING NOT NULL,
  specialtytype STRING NOT NULL,
  providerstartdatekey STRING NOT NULL,
  providertermdatekey STRING NOT NULL,
  specialtycategory STRING NOT NULL,
  cur_statbusinessdaycnt2 INT64,
  cur_statbankdaycnt2 INT64,
  cur_statcalendardaycnt3mo INT64,
  cur_statcalendardaycnt2mo INT64,
  cur_ytd_statbusinessdaycnt2 INT64,
  cur_ytd_statbankdaycnt2 INT64,
  cur_ytd_statcalendardaycnt3mo INT64,
  cur_ytd_statcalendardaycnt2mo INT64,
  cur_statproviderftecnt NUMERIC(33, 4),
  cur_ytd_statproviderftecnt NUMERIC(33, 4),
  cur_statproviderheadcnt NUMERIC(33, 4),
  cur_ytd_statproviderheadcnt NUMERIC(33, 4),
  cur_statrvucnt NUMERIC(33, 4),
  cur_ytd_statrvucnt NUMERIC(33, 4),
  cur_statwrvucnt NUMERIC(33, 4),
  cur_ytd_statwrvucnt NUMERIC(33, 4),
  cur_statregistrationcnt NUMERIC(33, 4),
  cur_ytd_statregistrationcnt NUMERIC(33, 4),
  cur_statvisitscnt NUMERIC(33, 4),
  cur_ytd_statvisitscnt NUMERIC(33, 4),
  cur_statofficevisitcnt NUMERIC(33, 4),
  cur_ytd_statofficevisitcnt NUMERIC(33, 4),
  cur_statnonofficevisitcnt NUMERIC(33, 4),
  cur_ytd_statnonofficevisitcnt NUMERIC(33, 4),
  cur_statgrosspatientrevenueamt NUMERIC(33, 4),
  cur_ytd_statgrosspatientrevenueamt NUMERIC(33, 4),
  cur_statavgdailypatientrevenueamt NUMERIC(33, 4),
  cur_ytd_statavgdailypatientrevenueamt NUMERIC(33, 4),
  cur_statpatientcashnetrevenueamt NUMERIC(33, 4),
  cur_ytd_statpatientcashnetrevenueamt NUMERIC(33, 4),
  cur_statotherrevenueamt NUMERIC(33, 4),
  cur_ytd_statotherrevenueamt NUMERIC(33, 4),
  cur_statnetrevenueamt NUMERIC(33, 4),
  cur_ytd_statnetrevenueamt NUMERIC(33, 4),
  cur_statrevenuedeductionamt NUMERIC(33, 4),
  cur_ytd_statrevenuedeductionamt NUMERIC(33, 4),
  cur_statuncompensatedcareamt NUMERIC(33, 4),
  cur_ytd_statuncompensatedcareamt NUMERIC(33, 4),
  cur_statchargesamt NUMERIC(33, 4),
  cur_ytd_statchargesamt NUMERIC(33, 4),
  cur_statmedicarechargesamt NUMERIC(33, 4),
  cur_ytd_statmedicarechargesamt NUMERIC(33, 4),
  cur_statmanagedmedicarechargesamt NUMERIC(33, 4),
  cur_ytd_statmanagedmedicarechargesamt NUMERIC(33, 4),
  cur_statmedicaidchargesamt NUMERIC(33, 4),
  cur_ytd_statmedicaidchargesamt NUMERIC(33, 4),
  cur_statmanagedmedicaidchargesamt NUMERIC(33, 4),
  cur_ytd_statmanagedmedicaidchargesamt NUMERIC(33, 4),
  cur_statcommercialchargesamt NUMERIC(33, 4),
  cur_ytd_statcommercialchargesamt NUMERIC(33, 4),
  cur_stathealthcareexchangechargesamt NUMERIC(33, 4),
  cur_ytd_stathealthcareexchangechargesamt NUMERIC(33, 4),
  cur_statselfpaychargesamt NUMERIC(33, 4),
  cur_ytd_statselfpaychargesamt NUMERIC(33, 4),
  cur_statotherchargesamt NUMERIC(33, 4),
  cur_ytd_statotherchargesamt NUMERIC(33, 4),
  cur_statnetaramt NUMERIC(33, 4),
  cur_ytd_statnetaramt NUMERIC(33, 4),
  cur_statinsurancebalanceamt NUMERIC(33, 4),
  cur_ytd_statinsurancebalanceamt NUMERIC(33, 4),
  cur_statpatientbalanceamt NUMERIC(33, 4),
  cur_ytd_statpatientbalanceamt NUMERIC(33, 4),
  cur_statbalanceamt NUMERIC(33, 4),
  cur_ytd_statbalanceamt NUMERIC(33, 4),
  cur_statinsurancecohpeamt NUMERIC(33, 4),
  cur_ytd_statinsurancecohpeamt NUMERIC(33, 4),
  cur_statinsurancecohotheramt NUMERIC(33, 4),
  cur_ytd_statinsurancecohotheramt NUMERIC(33, 4),
  cur_statinsuranceunbilledecwamt NUMERIC(33, 4),
  cur_ytd_statinsuranceunbilledecwamt NUMERIC(33, 4),
  cur_statinsuranceunbilledrhamt NUMERIC(33, 4),
  cur_ytd_statinsuranceunbilledrhamt NUMERIC(33, 4),
  cur_statinsuranceunbilledamt NUMERIC(33, 4),
  cur_ytd_statinsuranceunbilledamt NUMERIC(33, 4),
  cur_statinsuranceunbilledbalancegt120amt NUMERIC(33, 4),
  cur_ytd_statinsuranceunbilledbalancegt120amt NUMERIC(33, 4),
  cur_statinsuranceunbilledbalancegt360amt NUMERIC(33, 4),
  cur_ytd_statinsuranceunbilledbalancegt360amt NUMERIC(33, 4),
  cur_statinsurancebilledamt NUMERIC(33, 4),
  cur_ytd_statinsurancebilledamt NUMERIC(33, 4),
  cur_statinsurancebilledbalancegt120amt NUMERIC(33, 4),
  cur_ytd_statinsurancebilledbalancegt120amt NUMERIC(33, 4),
  cur_statinsurancebilledbalancegt360amt NUMERIC(33, 4),
  cur_ytd_statinsurancebilledbalancegt360amt NUMERIC(33, 4),
  cur_statinsurancebalancegt120amt NUMERIC(33, 4),
  cur_ytd_statinsurancebalancegt120amt NUMERIC(33, 4),
  cur_statinsurancebalancegt360amt NUMERIC(33, 4),
  cur_ytd_statinsurancebalancegt360amt NUMERIC(33, 4),
  cur_statpatientbalancegt120amt NUMERIC(33, 4),
  cur_ytd_statpatientbalancegt120amt NUMERIC(33, 4),
  cur_statmedicarebalanceamt NUMERIC(33, 4),
  cur_ytd_statmedicarebalanceamt NUMERIC(33, 4),
  cur_statmanagedmedicarebalanceamt NUMERIC(33, 4),
  cur_ytd_statmanagedmedicarebalanceamt NUMERIC(33, 4),
  cur_statmedicaidbalanceamt NUMERIC(33, 4),
  cur_ytd_statmedicaidbalanceamt NUMERIC(33, 4),
  cur_statmanagedmedicaidbalanceamt NUMERIC(33, 4),
  cur_ytd_statmanagedmedicaidbalanceamt NUMERIC(33, 4),
  cur_statcommercialbalanceamt NUMERIC(33, 4),
  cur_ytd_statcommercialbalanceamt NUMERIC(33, 4),
  cur_statotherbalanceamt NUMERIC(33, 4),
  cur_ytd_statotherbalanceamt NUMERIC(33, 4),
  cur_statselfpaybalanceamt NUMERIC(33, 4),
  cur_ytd_statselfpaybalanceamt NUMERIC(33, 4),
  cur_stattrueselfpaybalanceamt NUMERIC(33, 4),
  cur_ytd_stattrueselfpaybalanceamt NUMERIC(33, 4),
  cur_statcopaydeductselfpaybalanceamt NUMERIC(33, 4),
  cur_ytd_statcopaydeductselfpaybalanceamt NUMERIC(33, 4),
  cur_stattotalarwithiet NUMERIC(33, 4),
  cur_ytd_stattotalarwithiet NUMERIC(33, 4),
  cur_statietdaystoclosedaycnt NUMERIC(33, 4),
  cur_ytd_statietdaystoclosedaycnt NUMERIC(33, 4),
  cur_stattotalarnoiet NUMERIC(33, 4),
  cur_ytd_stattotalarnoiet NUMERIC(33, 4),
  cur_statptarwithiet NUMERIC(33, 4),
  cur_ytd_statptarwithiet NUMERIC(33, 4),
  cur_statpatientcashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_statpatientcashcollectionsecwamt NUMERIC(33, 4),
  cur_statinsurancecashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_statinsurancecashcollectionsecwamt NUMERIC(33, 4),
  cur_statcashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_statcashcollectionsecwamt NUMERIC(33, 4),
  cur_statqmirscashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_statqmirscashcollectionsecwamt NUMERIC(33, 4),
  cur_stat12mocashcollectionsamt NUMERIC(33, 4),
  cur_ytd_stat12mocashcollectionsamt NUMERIC(33, 4),
  cur_stat12mocashopportunityamt NUMERIC(33, 4),
  cur_ytd_stat12mocashopportunityamt NUMERIC(33, 4),
  cur_stateracashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_stateracashcollectionsecwamt NUMERIC(33, 4),
  cur_statupfrontcashcollectionsecwamt NUMERIC(33, 4),
  cur_ytd_statupfrontcashcollectionsecwamt NUMERIC(33, 4),
  cur_statinitialdenialsecwamt NUMERIC(33, 4),
  cur_ytd_statinitialdenialsecwamt NUMERIC(33, 4),
  cur_statinitialdenialsbillableecwamt NUMERIC(33, 4),
  cur_ytd_statinitialdenialsbillableecwamt NUMERIC(33, 4),
  cur_statinitialdenialsnonbillableecwamt NUMERIC(33, 4),
  cur_ytd_statinitialdenialsnonbillableecwamt NUMERIC(33, 4),
  cur_statdenialwriteoffecwamt NUMERIC(33, 4),
  cur_ytd_statdenialwriteoffecwamt NUMERIC(33, 4),
  cur_statdenialwriteoffbillableecwamt NUMERIC(33, 4),
  cur_ytd_statdenialwriteoffbillableecwamt NUMERIC(33, 4),
  cur_statdenialwriteoffnonbillableecwamt NUMERIC(33, 4),
  cur_ytd_statdenialwriteoffnonbillableecwamt NUMERIC(33, 4),
  cur_statpewriteoffamt NUMERIC(33, 4),
  cur_ytd_statpewriteoffamt NUMERIC(33, 4),
  cur_statpeaccrualchangeamt NUMERIC(33, 4),
  cur_ytd_statpeaccrualchangeamt NUMERIC(33, 4),
  cur_statnetfinancialstatementimpactgrossamt NUMERIC(33, 4),
  cur_ytd_statnetfinancialstatementimpactgrossamt NUMERIC(33, 4),
  cur_statcashcollectionsamt NUMERIC(33, 4),
  cur_ytd_statcashcollectionsamt NUMERIC(33, 4),
  cur_statptarnoietamt NUMERIC(33, 4),
  cur_ytd_statptarnoietamt NUMERIC(33, 4),
  cur_statinsarwithietamt NUMERIC(33, 4),
  cur_ytd_statinsarwithietamt NUMERIC(33, 4),
  cur_statinsarnoietamt NUMERIC(33, 4),
  cur_ytd_statinsarnoietamt NUMERIC(33, 4),
  cur_statpcnr2moprioramt NUMERIC(33, 4),
  cur_ytd_statpcnr2moprioramt NUMERIC(33, 4),
  cur_statpcnr2moprior12moamt NUMERIC(33, 4),
  cur_ytd_statpcnr2moprior12moamt NUMERIC(33, 4),
  cur_statofficeposchargesamt NUMERIC(33, 4),
  cur_ytd_statofficeposchargesamt NUMERIC(33, 4),
  cur_statnonofficeposchargesamt NUMERIC(33, 4),
  cur_ytd_statnonofficeposchargesamt NUMERIC(33, 4),
  cur_statresolutionar60amt NUMERIC(33, 4),
  cur_ytd_statresolutionar60amt NUMERIC(33, 4),
  cur_statresolutionar360amt NUMERIC(33, 4),
  cur_ytd_statresolutionar360amt NUMERIC(33, 4),
  cur_statgrosscharges60amt NUMERIC(33, 4),
  cur_ytd_statgrosscharges60amt NUMERIC(33, 4),
  cur_statgrosscharges360amt NUMERIC(33, 4),
  cur_ytd_statgrosscharges360amt NUMERIC(33, 4),
  cur_statupfrontcashofficeamt NUMERIC(33, 4),
  cur_ytd_statupfrontcashofficeamt NUMERIC(33, 4),
  cur_statupfrontcashnonofficeamt NUMERIC(33, 4),
  cur_ytd_statupfrontcashnonofficeamt NUMERIC(33, 4),
  cur_statcalendardaycnt INT64,
  cur_ytd_statcalendardaycnt INT64,
  cur_statietdaystocloseietcnt NUMERIC(33, 4),
  cur_ytd_statietdaystocloseietcnt NUMERIC(33, 4),
  cur_statrefundamt NUMERIC(33, 4),
  cur_ytd_statrefundamt NUMERIC(33, 4),
  cur_stathealthcareexchangebalanceamt NUMERIC(33, 4),
  cur_ytd_stathealthcareexchangebalanceamt NUMERIC(33, 4),
  cur_statbudgetuncompcareamt NUMERIC(33, 4),
  cur_ytd_statbudgetuncompcareamt NUMERIC(33, 4),
  cur_statbudgetgrossptrevamt NUMERIC(33, 4),
  cur_ytd_statbudgetgrossptrevamt NUMERIC(33, 4),
  cur_statpeatriskamt NUMERIC(33, 4),
  cur_ytd_statpeatriskamt NUMERIC(33, 4),
  cur_statgrosspatientrevenueamt3mo NUMERIC(33, 4),
  cur_ytd_statgrosspatientrevenueamt3mo NUMERIC(33, 4),
  cur_statpatientcashnetrevenueamt3mo NUMERIC(33, 4),
  cur_ytd_statpatientcashnetrevenueamt3mo NUMERIC(33, 4),
  cur_statpatientcashnetrevenueamt2mo NUMERIC(33, 4),
  cur_ytd_statpatientcashnetrevenueamt2mo NUMERIC(33, 4),
  cur_statchargesamt3mo NUMERIC(33, 4),
  cur_ytd_statchargesamt3mo NUMERIC(33, 4),
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
PARTITION BY snapshotdate
;