CREATE TABLE IF NOT EXISTS edwpsc.ecw_facttransactionsclaimlinefinancialadjustment
(
  transactionsclaimlinefinancialadjustmentkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  claimlinefinancialadjustmentskey INT64,
  transactiontype STRING,
  transactionflag STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiontime TIME,
  transactionbyuserkey INT64,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  trrefid INT64,
  claimlinechargeskey INT64,
  adjustmentcodekey INT64,
  adjustmentcategorykey INT64,
  firstdenialcategory STRING,
  archivedrecord STRING NOT NULL
)
;