CREATE TABLE IF NOT EXISTS edwpsc.ecw_refvendormmgt_history
(
  vendormmgtkey INT64 NOT NULL,
  sharepointid INT64 NOT NULL,
  vendorname STRING NOT NULL,
  title STRING,
  sharepointmodifieddate DATETIME,
  sharepointcreateddate DATETIME,
  createdbyname STRING,
  modifiedbyname STRING,
  requestdate DATETIME,
  requeststatusvalue STRING,
  requesttypevalue STRING,
  userfirstname STRING,
  userlastname STRING,
  user34 STRING,
  useremail STRING,
  groupvalue STRING,
  rolevalue STRING,
  submitteremail STRING,
  coderaapcorahimalicensenumber STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL,
  mdinvoicenumber STRING,
  mdinvoicename STRING,
  mddepartmentnumber STRING,
  mddepartment STRING,
  mddepartmentnumber2 STRING,
  md2invoicenum STRING,
  md2invoicename STRING,
  md2department STRING,
  md2departmentnumber STRING,
  md2departmentnumber2 STRING,
  secondgroup STRING,
  wfhvalue STRING,
  locationvalue STRING,
  deactivationcalendar DATETIME,
  esafsubmit DATETIME,
  groupchangecount STRING,
  groupchangelog STRING,
  esafcomplete DATETIME,
  templeavecalendar DATETIME,
  reactivationcalendar DATETIME,
  transfercalendar DATETIME
)
;