CREATE TABLE IF NOT EXISTS edwpsc.ecw_factsnapshotinitialdenials
(
  monthid INT64,
  snapshotdate DATE,
  coid STRING,
  claimnumber INT64,
  claimkey INT64,
  regionkey INT64,
  servicingproviderkey INT64,
  renderingproviderkey INT64,
  patientkey INT64,
  claimstatuskey INT64,
  claimservicedate DATE,
  claimservicedateyear INT64,
  claimservicedatemonth INT64,
  claimbalance NUMERIC(33, 4),
  claimcharge NUMERIC(33, 4),
  voidflag INT64,
  deleteflag INT64,
  arclaimflag INT64,
  facilitykey INT64,
  firstinsurancebilldatekey DATE,
  lastbilldatekey DATE,
  numberofbills INT64,
  liabilitydate DATE,
  claimdate DATE,
  liabilityowner STRING,
  rhholdcode STRING,
  claimlinechargekey INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptservicestartdate DATE,
  cptserviceenddate DATE,
  cptdeleteflag INT64,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  linecharge NUMERIC(29),
  linechargefinal NUMERIC(33, 4),
  lineinspayment NUMERIC(33, 4),
  lineinspaymentfirstdate DATE,
  lineinspaymentflag INT64,
  linepatpayment NUMERIC(33, 4),
  linepatpaymentflag INT64,
  lineinscontractual NUMERIC(33, 4),
  lineinscontractualfirstdate DATE,
  lineinscontractualflag INT64,
  lineadjustment NUMERIC(33, 4),
  lineadjustmentflag INT64,
  linebalance NUMERIC(33, 4),
  lineinbalanceflag INT64,
  lineadminadj NUMERIC(33, 4),
  linedenialadj NUMERIC(33, 4),
  linecharityadj NUMERIC(33, 4),
  linecontractualadj NUMERIC(33, 4),
  lineuninsureddiscountadj NUMERIC(33, 4),
  linerefundadj NUMERIC(33, 4),
  linensfadj NUMERIC(33, 4),
  lineescheatadj NUMERIC(33, 4),
  linebaddebtadj NUMERIC(33, 4),
  lineotheradj NUMERIC(33, 4),
  voiddate DATE,
  priorclaimkey INT64,
  voidfirstbilledclaimkey INT64,
  voidfirstbilledclaimnumber INT64,
  voidfirstbilleddatekey DATE,
  onfirstbilledflag INT64,
  onfirstbilledcharge NUMERIC(33, 4),
  voidfirstbilledclaimlinechargekey INT64,
  firstdenialcarcrarccode STRING,
  firstdenialeradate DATE,
  firstdenialcarccodes STRING,
  firstdenialrarccodes STRING,
  firstdenialpayername STRING,
  firstdenialcategory STRING,
  initialdeniedcharges NUMERIC(33, 4),
  firstdenialflag INT64,
  linedenialadjflag INT64,
  firstdenialcarcrarctype STRING,
  firstdenialcarcisdenial STRING,
  firstdenialcarcrequiresrarc STRING,
  firstdenialrarcisdenial STRING,
  firsteracarcrarccode STRING,
  firsteradate DATE,
  firsteracarccodes STRING,
  firsterararccodes STRING,
  firsterapayername STRING,
  firsteracategory STRING,
  firsteracarcrarctype STRING,
  firsteracarcisdenial STRING,
  firsteracarcrequiresrarc STRING,
  firsterararcisdenial STRING,
  artivapool STRING,
  artivaliabilitylastreviewed DATE,
  artivaliabilityfollowupdate DATE,
  lastadjustmentcode STRING,
  lastadjustmentname STRING,
  lastadjustmentcategory STRING,
  lastadjustmentdate DATE,
  lineadminadjlastdate DATE,
  linedenialadjlastdate DATE,
  linecharityadjlastdate DATE,
  linecontractualadjlastdate DATE,
  lineuninsureddiscountadjlastdate DATE,
  linerefundadjlastdate DATE,
  linensfadjlastdate DATE,
  lineescheatadjlastdate DATE,
  linebaddebtadjlastdate DATE,
  lineotheradjlastdate DATE,
  ietflag INT64,
  ietcreatedate DATE,
  ietlastmodifieddate DATE,
  denialcount INT64,
  deniallasteradate DATE,
  initialiplankey INT64
)
PARTITION BY snapshotdate
;