CREATE TABLE IF NOT EXISTS edwpsc.ecw_factsnapshotpaymentline
(
  paymentlinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  claimkey INT64,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  iplan1iplankey INT64 NOT NULL,
  practicekey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  claim_number INT64 NOT NULL,
  gldepartmentnum STRING,
  patientid INT64,
  servicingproviderid INT64,
  renderingproviderid INT64,
  facilityid INT64,
  practiceid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1id INT64,
  financialclasskey STRING,
  encounterid INT64,
  cptid INT64 NOT NULL,
  paymentlineid INT64 NOT NULL,
  paymentdetailid INT64 NOT NULL,
  paymentid INT64,
  checknumber STRING,
  checktype STRING,
  checkdate DATETIME,
  posteddatekey DATETIME,
  allowedamt NUMERIC(29) NOT NULL,
  deductableamt NUMERIC(29) NOT NULL,
  coinsuranceamt NUMERIC(29) NOT NULL,
  memrespamt NUMERIC(29) NOT NULL,
  paymentamt NUMERIC(29) NOT NULL,
  contractualadjustmentamt NUMERIC(29) NOT NULL,
  withheldamt NUMERIC(29) NOT NULL,
  msgcode STRING NOT NULL,
  eraadjustmentamt NUMERIC(29) NOT NULL,
  linetaxamt NUMERIC(29) NOT NULL,
  paymentfromid INT64,
  paymenttypekey INT64,
  cptcode STRING,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cptorder INT64,
  cptdeleletedline INT64,
  cptunits NUMERIC(29),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptchargesamt NUMERIC(29),
  paymentlinecreatedate DATETIME,
  paymentlinemodifieddate DATETIME,
  paymentclaimcreatedate DATETIME,
  paymentclaimmodifieddate DATETIME,
  regionkey INT64,
  coid STRING,
  claimlinechargekey INT64
)
PARTITION BY snapshotdate
;