CREATE TABLE IF NOT EXISTS edwpsc.ecw_juncreferral
(
  ecwreferralkey INT64 NOT NULL,
  regionkey INT64,
  patientid INT64,
  patientkey INT64,
  insid INT64,
  iplankey INT64,
  reffrom INT64,
  reffromproviderkey INT64,
  authno STRING,
  refdate DATETIME,
  reason STRING,
  diagnosis STRING,
  refstdate DATETIME,
  refenddate DATETIME,
  visitsallowed INT64,
  visitsused INT64,
  refto INT64,
  reftoproviderkey INT64,
  notes STRING,
  referraltype STRING,
  priority INT64,
  assignedto STRING,
  assignedtoid INT64,
  status STRING,
  authtype STRING,
  procedures STRING,
  fromfacility INT64,
  fromfacilitykey INT64,
  tofacility INT64,
  tofacilitykey INT64,
  speciality INT64,
  pos INT64,
  unittype STRING,
  frontofficeauth INT64,
  referralnumber STRING,
  apptdate DATETIME,
  clinicalnotes STRING,
  receiveddate DATETIME,
  refencid INT64,
  refencounterkey INT64,
  appttime STRING,
  extnhxapptblockid INT64,
  extnhxreftxid INT64,
  refreqid INT64,
  reffromp2pnpi STRING,
  reffromname STRING,
  reftop2pnpi STRING,
  reftoname STRING,
  uploadedtoptdocs INT64,
  deleteflag INT64,
  sourceprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;