CREATE TABLE IF NOT EXISTS edwpsc.ecw_refcoidstar
(
  coidstarkey INT64 NOT NULL,
  coid STRING,
  coidname STRING,
  coidspecialty STRING,
  coidcompanycode STRING,
  coidunitnumber STRING,
  pscrevcyclemgmt STRING,
  groupkey INT64,
  groupname STRING,
  divisionkey INT64,
  divisionname STRING,
  marketkey INT64,
  marketname STRING,
  statekey STRING,
  hcaps300 STRING,
  centerkey INT64,
  centerdescription STRING,
  serviceline STRING,
  coidlob STRING,
  coidsublob STRING,
  lobname STRING,
  sublobname STRING,
  traumaburnflag STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  coidwithleadingzero STRING,
  deleteflag STRING,
  divisioncode STRING,
  groupcode STRING,
  hospitalcoid STRING,
  hospitalname STRING,
  marketcode STRING,
  ppmsflag INT64
)
;