CREATE TABLE IF NOT EXISTS edwpsc.ecw_refpatient
(
  patientkey INT64 NOT NULL,
  patientdobdatekey DATE NOT NULL,
  patientattendingdoctorproviderkey INT64 NOT NULL,
  patientguarantorpatientkey INT64 NOT NULL,
  patientguarantorid INT64 NOT NULL,
  patientstatementdatekey DATE NOT NULL,
  patientreferringproviderkey INT64 NOT NULL,
  patientrenderingproviderkey INT64 NOT NULL,
  patientprimaryproviderkey INT64 NOT NULL,
  patientdeceaseddatekey STRING,
  patientrelatedinfodatekey STRING,
  patientfirstname STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  patientaccountnumberwithprefix STRING,
  patientprefixname STRING,
  patientsuffixname STRING,
  patientprimaryaddressline1 STRING,
  patientprimaryaddressline2 STRING,
  patientprimarygeographykey INT64 NOT NULL,
  patientusertype INT64,
  patientinitials STRING,
  patientssn STRING,
  patientprimaryservicelocation INT64,
  patientphone STRING,
  patientmobilephone STRING,
  patientpager STRING,
  patientemail STRING,
  patientstatus STRING,
  patientemployername STRING,
  patientemployeraddressline1 STRING,
  patientemployeraddressline2 STRING,
  patientemployergeographykey INT64 NOT NULL,
  patientemployerphone STRING,
  patientstudentstatus STRING,
  patientemployerstatus STRING,
  patientnostatements INT64,
  patientbillingalert INT64,
  patientrace STRING,
  patientmaritalstatus STRING,
  patientdeceased INT64,
  patientdeceasednotes STRING,
  patientlegacymrn STRING,
  patientethnicity STRING,
  patientrelatedinfo STRING,
  patientpharmacyname STRING,
  patientpharmacyno STRING,
  patientpharmacyfax STRING,
  patientcountrycode STRING,
  patientsex STRING,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourcebprimarykeyvalue INT64 NOT NULL,
  sourcebrecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  status INT64,
  regionkey INT64,
  empinumber STRING,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL,
  PRIMARY KEY (patientkey) NOT ENFORCED
)
;