CREATE TABLE IF NOT EXISTS edwpsc.ecw_factencountermedaxioncodingstatus
(
  medaxioncodingstatuskey INT64 NOT NULL,
  medaxionregionname STRING,
  medaxionlocation STRING,
  practicename STRING,
  department STRING,
  providername STRING,
  providertype STRING,
  servicedatekey DATE,
  casenumberfin STRING,
  patientmrn STRING,
  patientfirst3 STRING,
  patientlast3 STRING,
  patientdob DATE,
  facilitycoid STRING,
  poscode STRING,
  surgeonofrecordname STRING,
  codingcompleteddate DATE,
  codingcompleteddatetime DATETIME,
  codername STRING,
  emergencyflag INT64,
  asa STRING,
  auditnotestatus STRING,
  anesthesiastartintraop DATETIME,
  anesthesiastoppostop DATETIME,
  crossesmidnightflag INT64,
  pulsecaselink STRING,
  caseencountertype STRING,
  pulseencounterlink STRING,
  createddate STRING,
  lastsigneddate STRING,
  lastaction STRING,
  lastcoder STRING,
  lastqueue STRING,
  lastactiondatetime DATETIME,
  box19note STRING,
  cptcodetext STRING,
  syntheticcaseid STRING,
  rcmsyntheticencounterid STRING,
  firstfiledate DATE,
  lastfiledate DATE,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;