CREATE TABLE IF NOT EXISTS edwpsc.ecw_refpatientmeditechexpanse
(
  patientkey INT64 NOT NULL,
  regionkey INT64,
  patientdobdatekey DATE,
  patientguarantorpatientkey INT64,
  patientguarantorid STRING,
  patientattendingdoctorproviderkey INT64,
  patientreferringproviderkey INT64,
  patientrenderingproviderkey INT64,
  patientprimaryproviderkey INT64,
  patientfirstname STRING,
  patientlastname STRING,
  patientmiddlename STRING,
  patientprefixname STRING,
  patientsuffixname STRING,
  patientfullname STRING,
  patientprimaryaddressline1 STRING,
  patientprimaryaddressline2 STRING,
  patientprimarygeographykey INT64,
  patientinitials STRING,
  patientssn STRING,
  patientprimaryservicelocation INT64,
  patientphone STRING,
  patientmobilephone STRING,
  patientemail STRING,
  patientrace STRING,
  patientmaritalstatus STRING,
  patientlegacymrn STRING,
  patientethnicity STRING,
  patientsex STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (patientkey) NOT ENFORCED
)
;