CREATE TABLE IF NOT EXISTS edwpsc.ecw_facteraclaimpaymentinformation
(
  eraclaimpaymentinformationkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64 NOT NULL,
  clp01 STRING,
  clp02 STRING,
  clp03 NUMERIC(33, 4),
  clp04 NUMERIC(33, 4),
  clp05 NUMERIC(33, 4),
  clp06 STRING,
  clp07 STRING,
  clp08 STRING,
  clp09 STRING,
  clp10 STRING,
  clp11 STRING,
  clp12 NUMERIC(31, 2),
  clp13 NUMERIC(31, 2),
  clp14 STRING,
  segment STRING,
  sourcefilename STRING,
  sourcefilecreateddate DATETIME NOT NULL,
  seq INT64,
  datecreated DATETIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deletedflag INT64,
  fullclaimnumber STRING,
  regionkey INT64
)
;