CREATE TABLE IF NOT EXISTS edwpsc.ecw_factnbtproviderbynpi
(
  snapshotdatekey DATE,
  providersourcesystemkey STRING,
  gldepartmentnumber STRING,
  coid STRING,
  providerfirstname STRING,
  providerlastname STRING,
  providermiddlename STRING,
  providernpi STRING,
  providerupin STRING,
  companycode STRING,
  providerrelationshipname STRING,
  specialtyname STRING,
  specialtytype STRING,
  compensationtype STRING,
  budgetccindicator STRING,
  departmentname STRING,
  providerassignedstartdate DATE,
  isapprovedindicator STRING,
  gllastupdateddate DATE,
  gllastupdatedby STRING,
  providerstatusindicator STRING,
  statuschangedate DATE,
  providerstartdate DATE,
  ancillarydepartmentnumber STRING,
  budgetstartdate DATE,
  communitystatus STRING,
  contractpayconversiondate DATE,
  contractcompensationtype STRING,
  contractcurrentpay NUMERIC(32, 3),
  contracteffectivedate DATE,
  contractexpirationdate DATE,
  ftecount INT64,
  hospitalistindicator STRING,
  multipleproviderdepartmentindicator STRING,
  newreplacementname STRING,
  overheaddepartmentnumber STRING,
  practiceestablishedbyprocessname STRING,
  productivityreason STRING,
  productivitylevelfuture STRING,
  productivityleveltoday STRING,
  productivitystatus STRING,
  datechangedtoproductivity DATE,
  technicallevel STRING,
  projectedterminationdate DATE,
  strategyname STRING,
  strategytypename STRING,
  strategytypereason STRING,
  terminationreason STRING,
  terminationresult STRING,
  terminationtype STRING,
  morproviderstatusid INT64,
  datasourcecode STRING,
  sourcesystemcode STRING,
  countproviderindicator STRING,
  providerlastupdateddate DATE,
  providerlastupdatedby STRING,
  samestoreindicator STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
PARTITION BY snapshotdatekey
;