CREATE TABLE IF NOT EXISTS edwpsc.ecw_factmeditechorauth
(
  meditechorauthkey INT64 NOT NULL,
  meditechcocid STRING,
  accountnumber STRING,
  proceduredate DATE,
  proceduretime TIME,
  cptcode STRING,
  patientlastname STRING,
  patientfirstname STRING,
  patientmiddlename STRING,
  patientsex STRING,
  patientdob DATE,
  patienttypecode STRING,
  surgeonnpi STRING,
  surgeonname STRING,
  primaryinsurance STRING,
  primaryinsauthnumber STRING,
  secondarinsauthnumber STRING,
  financialclass STRING,
  financialclassdesc STRING,
  procedureesttime STRING,
  appointmentortype STRING,
  ptlocation STRING,
  appointmentstatus STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING NOT NULL,
  sourceaprimarykeyvalue STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  admitorderresponsetext STRING,
  coid STRING,
  facilityname STRING
)
;