CREATE TABLE IF NOT EXISTS edwpsc.ecw_factencounter
(
  encounterkey INT64 NOT NULL,
  claimkey INT64,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  patientkey INT64 NOT NULL,
  visitreason STRING,
  visitdate DATE NOT NULL,
  visitstarttime TIME,
  visitendtime TIME,
  visittypekey INT64 NOT NULL,
  visitcopay NUMERIC(33, 4),
  visitstatuskey INT64 NOT NULL,
  encountertype INT64,
  deleteflag INT64,
  encounterlock INT64,
  visitarrivedtime TIME,
  statusaftercheckin STRING,
  claimrequired INT64,
  visittypeoverriden STRING,
  claimnumber INT64,
  referringproviderkey INT64 NOT NULL,
  facilityresourcekey INT64 NOT NULL,
  timein TIME,
  timeout TIME,
  departuretime TIME,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  sourcepatientacctnumber STRING,
  appointmentcreateddate DATE,
  appointmentcreatedby INT64,
  gfestatus STRING,
  archivedrecord STRING NOT NULL
)
;