CREATE TABLE IF NOT EXISTS edwpsc.ecw_factchargelagsummary
(
  chargelagsummarykey INT64 NOT NULL,
  groupname STRING,
  divisionname STRING,
  marketname STRING,
  coidname STRING,
  coid STRING,
  lobcode STRING,
  sublobcode STRING,
  sublobname STRING,
  poscode STRING,
  gldeptnum STRING,
  fromservicepedate DATE,
  startentrydate DATE,
  glpostingpedate DATE,
  chargelagstartdate DATE,
  chargelagstartpedate DATE,
  chargelagbucket STRING,
  sourcesystemcode STRING,
  sourcesystemdesc STRING,
  flevel STRING,
  providername STRING,
  largepractice STRING,
  providerspecialtycategory STRING,
  providerspecialtytype STRING,
  providerspecialty STRING,
  lagdaytotalden NUMERIC(31, 2),
  lagdaytotalnum NUMERIC(31, 2),
  lag02den NUMERIC(31, 2),
  lag35den NUMERIC(31, 2),
  laggt5den NUMERIC(31, 2),
  laglt0den NUMERIC(31, 2),
  lagunknownden NUMERIC(31, 2),
  lag02num NUMERIC(31, 2),
  lag35num NUMERIC(31, 2),
  laggt5num NUMERIC(31, 2),
  laglt0num NUMERIC(31, 2),
  lagunknownnum NUMERIC(31, 2),
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;