CREATE TABLE IF NOT EXISTS edwpsc.ecw_rprtgoverneddenialstrending
(
  governeddenialstrendingkey INT64 NOT NULL,
  snapshotquarter STRING,
  snapshotdate DATETIME,
  snapshotyear INT64,
  dosquarter STRING,
  dosmonth DATETIME,
  dosyear INT64,
  coid STRING,
  samestoreflag STRING,
  servicingproviderlastname STRING,
  servicingproviderfirstname STRING,
  servicingprovidernpi STRING,
  specialtycategory STRING,
  specialtyname STRING,
  specialtytype STRING,
  iplan STRING,
  majorpayor STRING,
  financialclassname STRING,
  financialclassnumber INT64,
  firstdenialcategory STRING,
  adjcode STRING,
  adjname STRING,
  nonparflag STRING,
  adjcategory STRING,
  sourcesystem STRING,
  initialdeniedcharges NUMERIC(33, 4),
  charges NUMERIC(33, 4),
  finaldenials NUMERIC(33, 4),
  newdenialsamt NUMERIC(33, 4),
  newpaymentvariancesamt NUMERIC(33, 4),
  newclaimrejectionsamt NUMERIC(33, 4),
  initialpayerresponsecategory STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
PARTITION BY DATE(snapshotdate)
;