CREATE TABLE IF NOT EXISTS edwpsc.ecw_factsrtdiscounttracker
(
  srtdiscounttrackerkey INT64 NOT NULL,
  controlnumber STRING,
  partners STRING,
  discountperiod DATE,
  invoicedescription STRING,
  department STRING,
  owners STRING,
  initialquality STRING,
  finalauditscore NUMERIC(33, 4),
  invoicetotal NUMERIC(31, 2),
  totaldiscountpercent NUMERIC(33, 4),
  totaldiscountamount NUMERIC(31, 2),
  qualitydiscountpercent NUMERIC(31, 2),
  qadiscountapplied NUMERIC(31, 2),
  sladiscountpercent NUMERIC(33, 4),
  sladiscountapplied NUMERIC(31, 2),
  billedunits INT64,
  actualunits INT64,
  unitsnotworked INT64,
  invoicediscrepancyidentified INT64,
  invoicediscrepancyamount NUMERIC(31, 2),
  rate NUMERIC(31, 2),
  invoicetoapplydiscount DATE,
  notificationsent DATE,
  finalamountdue NUMERIC(31, 2),
  totalreceivedamount NUMERIC(31, 2),
  finalreceivedmonth DATE,
  discountreceived STRING,
  discountunderoverapplied NUMERIC(31, 2),
  invoicecorrectionsrequired STRING,
  discounttype STRING,
  poolcompletiontier STRING,
  accountspresentednum INT64,
  accountsworkednum INT64,
  accountsmissedforpoolcompletion INT64,
  discounttrackerkey INT64,
  sourceprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME NOT NULL,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64
)
;