CREATE TABLE IF NOT EXISTS edwpsc.ecw_factrhinventory
(
  snapshotdate DATE,
  datatype STRING,
  rhinvkey INT64 NOT NULL,
  rhclaimid STRING,
  claimkey STRING,
  rhcontrolno STRING,
  rhstatus STRING,
  rhclaimdate DATE,
  rhtotalamt NUMERIC(33, 4),
  rhholdcode STRING,
  rhholdruleenabled STRING,
  rhholdrulecreated DATETIME,
  rhholdrulelastupdate DATETIME,
  rhholdcodetranslated STRING,
  rhdupecount STRING,
  rhinvstatus STRING,
  rhhaserror STRING,
  rhhasexception STRING,
  rhhasedierror STRING,
  rhhasserviceorder STRING,
  rhhasunmappederror STRING,
  rhclaimlastbilledpaper STRING,
  ietopenprevbilled STRING,
  systemname STRING,
  ecwregionid STRING,
  coid STRING,
  coiddeptnumber STRING,
  coidname STRING,
  lobcode STRING,
  groupname STRING,
  divisonname STRING,
  marketname STRING,
  practicename STRING,
  renderingproviderfederaltaxid STRING,
  renderingprovidergroupnpi STRING,
  claimnumber STRING,
  patientname STRING,
  totalcharges NUMERIC(33, 4),
  totalbalance NUMERIC(33, 4),
  balancebucket STRING,
  totalpatientbalance NUMERIC(33, 4),
  totalinsurancebalance NUMERIC(33, 4),
  totalpayments NUMERIC(33, 4),
  totalinsurancepayments NUMERIC(33, 4),
  totalpatientpayments NUMERIC(33, 4),
  totaladjustments NUMERIC(33, 4),
  billtoindicatordescription STRING,
  billtoindicatorlastupdated STRING,
  billtoname STRING,
  billtoindicatorfinancialclass STRING,
  financialclass STRING,
  renderingprovidername STRING,
  renderingprovidernpi STRING,
  filestatusdesc STRING,
  claimstatuslastmodifieddate STRING,
  artivainsliablity1poolnumber STRING,
  artivainsliablity1poolname STRING,
  claimins1id STRING,
  claimins1name STRING,
  claimins1financialclass STRING,
  artivainsliablity2poolnumber STRING,
  artivainsliablity2poolname STRING,
  claimins2id STRING,
  claimins2name STRING,
  claimins2financialclass STRING,
  artivainsliablity3poolnumber STRING,
  artivainsliablity3poolname STRING,
  claimins3id STRING,
  claimins3name STRING,
  claimins3financialclass STRING,
  artivapatliablitypoolnumber STRING,
  artivapatliablitypoolname STRING,
  servicedate STRING,
  claimage STRING,
  claimagingbucket STRING,
  claimdate DATE,
  ietsubcategoryopen STRING,
  ietsublastcloseddate DATE,
  claimactionlastmodifieddate DATE,
  claimactionlastmodifiedusername STRING,
  pos STRING,
  voidedclaim STRING,
  deletedclaim STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (rhinvkey) NOT ENFORCED
)
PARTITION BY snapshotdate
;