CREATE TABLE IF NOT EXISTS edwpsc.ecw_factietv2masterfile
(
  fieldmessage STRING,
  category STRING,
  subcategoryid STRING,
  reporttype STRING,
  isactive BOOL,
  notesfieldname STRING,
  isnotesactive BOOL,
  userfriendlymessage STRING,
  isuserfriendlymessageactive BOOL,
  notes STRING,
  subcategoryoriginid STRING,
  subcategorydescription STRING,
  subcategoryactive BOOL,
  department STRING,
  iscreateclaimquery BOOL,
  subcategorytype STRING,
  claimerrortypename STRING,
  claimerrortypedescription STRING,
  categoryname STRING,
  sourceprimarykeyvalue INT64 NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  lastmodifiedactiveflagtoyes DATETIME,
  fieldname STRING,
  ietv2masterfilekey INT64 NOT NULL,
  PRIMARY KEY (ietv2masterfilekey) NOT ENFORCED
)
;