CREATE TABLE IF NOT EXISTS edwpsc.ecw_refprovidermasterlistmedicaid
(
  providermasterlistmedicaidkey INT64 NOT NULL,
  medicaidproviderid STRING,
  sourcesystem STRING,
  providername STRING,
  dbaname STRING,
  providertypecode STRING,
  providerspecialtycode STRING,
  taxonomycode STRING,
  servicelocationaddress1 STRING,
  servicelocationaddress2 STRING,
  servicelocationaddresscity STRING,
  servicelocationaddressstate STRING,
  servicelocationaddresszip STRING,
  enrollmenttype STRING,
  npitype STRING,
  npi STRING,
  npieffectivedate DATE,
  npienddate DATE,
  npistatus STRING,
  individualororganizational STRING,
  license STRING,
  currentmedicaidenrollmentstatus STRING,
  medicaidclaimseligibilityeffectivedate DATE,
  medicaidclaimseligibilityenddate DATE,
  nextrevalidationdate DATE,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  filename STRING NOT NULL,
  filedate STRING NOT NULL
)
;