CREATE TABLE IF NOT EXISTS edwpsc.ecw_cashvaluecurrentclaimlinecharge
(
  claimlinechargekey INT64,
  coid STRING,
  deptcode STRING,
  cptcodekey INT64,
  cptmodifier1 STRING,
  cptunits INT64,
  cptchargesamt NUMERIC(33, 4),
  calculatedlinebalance NUMERIC(33, 4),
  postedinsurancepaymentamt NUMERIC(33, 4),
  postedpatientpaymentamt NUMERIC(33, 4),
  postedcontractualadjustmentamt NUMERIC(33, 4),
  postedfinancialadjustmentamt NUMERIC(33, 4),
  copaycptorder INT64,
  claimkey INT64,
  claimnumber INT64,
  regionkey INT64,
  servicedatekey DATE,
  renderingproviderkey INT64,
  guarantorpatientkey INT64,
  patientbilltype STRING,
  payer1iplankey INT64,
  payer2iplankey INT64,
  liabilityownertype INT64,
  liabilityiplankey INT64,
  claimbilledflag INT64,
  firstinsurancebilldatekey DATE,
  lastinsurancebilldatekey DATE,
  bankdaysfromlastbilldate INT64,
  insurancebillcount INT64,
  firstpatientstatementbilldatekey DATE,
  lastpatientstatementbilldatekey DATE,
  patientstatementcount INT64,
  paymentexpectedredflagdaysthreshold INT64,
  paymentexpectedredflag INT64,
  denialprobability BIGNUMERIC(40, 2),
  insurancepaymentprobability BIGNUMERIC(40, 2),
  contractualexpectedamt NUMERIC(33, 4),
  allowedexpectedamt NUMERIC(33, 4),
  primaryinsurancepaymentexpectedamt NUMERIC(33, 4),
  primaryinsurancepaymentlagdays INT64,
  primaryinsurancepaymentexpecteddate DATE,
  secondaryinsurancepaymentexpectedamt NUMERIC(33, 4),
  secondaryinsurancepaymentlagdays INT64,
  secondaryinsurancepaymentexpecteddate DATE,
  patientpaymentprobability BIGNUMERIC(40, 2),
  patientpaymentexpectedamt NUMERIC(33, 4),
  patientpaymentlagdays INT64,
  patientpaymentexpecteddate DATE,
  linebalancecashvalueamt NUMERIC(33, 4),
  chargevaluekey INT64,
  dwlastupdatedatetime DATETIME NOT NULL
)
;