CREATE TABLE IF NOT EXISTS edwpsc.ecw_juncediinspayment
(
  ecwediinspaymentkey INT64 NOT NULL,
  regionkey INT64,
  payortype INT64,
  payorid INT64,
  payoriplankey INT64,
  providerid INT64,
  providerkey INT64,
  paymentamount NUMERIC(33, 4),
  checkno STRING,
  paymenttype STRING,
  paymentdate DATE,
  checkdate DATE,
  memo STRING,
  postedby INT64,
  postedbyuserkey INT64,
  posteddt DATE,
  postedtime TIME,
  modifieddate DATETIME,
  facilityid INT64,
  facilitykey INT64,
  paymentlock INT64,
  lockedby INT64,
  lockedbyuserkey INT64,
  unpostedamount NUMERIC(33, 4),
  paymentcode STRING,
  eomb1 STRING,
  creditcardtype INT64,
  closingid INT64,
  unpostedcpt NUMERIC(33, 4),
  checktaxamt NUMERIC(33, 4),
  checktotalamt NUMERIC(33, 4),
  eradetailid INT64,
  batchid INT64,
  parentpaymentid INT64,
  voidflag INT64,
  recreatedflag INT64,
  practiceid INT64,
  practicekey INT64,
  deleteflag INT64,
  sourceprimarykeyvalue INT64,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  patientkey INT64
)
;