CREATE TABLE IF NOT EXISTS edwpsc.ecw_factnbtglcoiddepartmentcurrent
(
  nbtglcoiddepartmentcurrentkey INT64 NOT NULL,
  glperiod STRING,
  coid INT64,
  providerdepartmentno INT64,
  overheaddepartmentno INT64,
  ancillarydepartmentno INT64,
  coiddepartmentname STRING,
  providerid INT64,
  coiddepartmentrelationshipid INT64,
  coiddepartmentrelationship STRING,
  specialtyid INT64,
  coiddepartmentspecialtycode STRING,
  practiceestablishedid INT64,
  practiceestablishedthrough STRING,
  budgetstartdate DATETIME,
  coiddepartmentisbudgetcc BOOL,
  coiddepartmentstartdate DATETIME,
  provideroriginalstartdate STRING,
  coiddepartmentproviderassignedstartdate DATETIME,
  communitystatus STRING,
  coiddepartmentcompensationtypeid INT64,
  coiddepartmentcompensationtype STRING,
  coiddepartmentfte NUMERIC(31, 2),
  upin STRING,
  newreplacementid INT64,
  newreplacementdescription STRING,
  providerstrategyid INT64,
  providerstrategydescription STRING,
  ishospitalist BOOL,
  ismultipleproviderdepartment BOOL,
  coiddepartmentproviderstatusid INT64,
  coiddepartmentproviderstatus STRING,
  practiceid INT64,
  developmenttypeid INT64,
  developmenttypedescription STRING,
  contracteffectivedate STRING,
  contractcompensationtype STRING,
  contractexpirationdate DATETIME,
  providerheadcount INT64,
  terminationdate STRING,
  ohallocation INT64,
  allocationtypedescription STRING,
  coidstartdate DATETIME,
  originalproviderstatusid INT64,
  originalproviderstatusdescription STRING,
  physicianstatusdetailid STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (nbtglcoiddepartmentcurrentkey) NOT ENFORCED
)
;