CREATE TABLE IF NOT EXISTS edwpsc.epic_factclaimbill
(
  claimbillkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  visitnumber INT64,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  invoicenumber STRING,
  invoicestatus STRING,
  billtypekey INT64 NOT NULL,
  iplankey INT64 NOT NULL,
  billmessage STRING,
  batchnumber STRING,
  billdatekey DATE NOT NULL,
  billtime TIME NOT NULL,
  sourceaprimarykeyvalue STRING NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourcebprimarykeyvalue STRING NOT NULL,
  sourcebrecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (claimbillkey) NOT ENFORCED
)
;