CREATE TABLE IF NOT EXISTS edwpsc.epic_factsnapshotchargeline
(
  chargelinekey INT64 NOT NULL,
  monthid INT64,
  snapshotdate DATE,
  coid STRING,
  regionkey INT64,
  practicekey INT64,
  practiceid STRING,
  claimkey INT64,
  claimnumber INT64,
  visitnumber INT64,
  transactionnumber INT64,
  gldepartment STRING,
  patientid INT64,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  renderingproviderkey INT64,
  renderingproviderid STRING,
  facilitykey INT64,
  facilityid INT64,
  claimdatekey DATE,
  servicedatekey DATE,
  iplan1iplankey INT64,
  iplan1id STRING,
  financialclasskey INT64,
  cptid INT64,
  cptorder INT64,
  cptcode STRING,
  cptcodekey INT64,
  cptstartservicedatekey DATE,
  cptendservicedatekey DATE,
  cpttypeofservice STRING,
  cptchargesamt NUMERIC(33, 4),
  cptchargesperunitamt NUMERIC(33, 4),
  cptunits NUMERIC(29),
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  cptdeleteflag INT64,
  cptposkey STRING,
  dwlastupdatedatetime DATETIME
)
PARTITION BY snapshotdate
;