CREATE TABLE IF NOT EXISTS edwpsc.epic_factencounteranesthesia
(
  anesthesiakey INT64 NOT NULL,
  regionkey INT64,
  anesthesialocationname STRING,
  episodeid INT64,
  servicedatekey DATE,
  casenumberfin INT64,
  patientkey INT64,
  patientmrn STRING,
  patientlastname STRING,
  patientfirstname STRING,
  procedurename STRING,
  anesthesiastarttime DATETIME,
  anesthesiaendtime DATETIME,
  anesthesiologist STRING,
  anesthesiastaff STRING,
  anesrecsignedflag INT64,
  anesrecsigneddatetime DATETIME,
  preopnoteflag INT64,
  preopnotesigneddatetime DATETIME,
  preopnoteprovidername STRING,
  postopnoteflag INT64,
  postopnotesigneddatetime DATETIME,
  postopnoteprovidername STRING,
  encounterclosedflag INT64,
  eventcanceledflag INT64,
  eventcanceledstatus STRING,
  eventcanceleddatetime DATETIME,
  logorcasename STRING,
  casecanceledflag INT64,
  casecanceledreason STRING,
  comments STRING,
  sourcerecordupdatedatetime DATETIME,
  anesthesia53encounterkey INT64,
  anesthesia53encounterid INT64,
  anesthesia52encounterkey INT64,
  anesthesia52encounterid INT64,
  epicpatientid STRING,
  caseid STRING,
  logid STRING,
  anesthesiologistproviderkey INT64,
  anesthesiologistproviderid INT64,
  preopnoteproviderid INT64,
  preopnoteproviderkey INT64,
  postopnoteproviderid INT64,
  postopnoteproviderkey INT64,
  caselockey INT64,
  loglockey INT64,
  sourceaprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;