CREATE TABLE IF NOT EXISTS edwpsc.epic_stgclaritytdltranfull
(
  tdl_id NUMERIC(29) NOT NULL,
  detail_type INT64,
  type INT64,
  post_date DATETIME,
  orig_post_date DATETIME,
  orig_service_date DATETIME,
  period STRING,
  tx_id NUMERIC(29),
  tran_type INT64,
  allowed_amount NUMERIC(31, 2),
  charge_slip_number STRING,
  type_of_service INT64,
  match_trx_id NUMERIC(29),
  match_proc_id NUMERIC(29),
  account_id NUMERIC(29),
  pat_id STRING,
  amount NUMERIC(31, 2),
  patient_amount NUMERIC(31, 2),
  insurance_amount NUMERIC(31, 2),
  performing_prov_id STRING,
  billing_provider_id STRING,
  original_cvg_id NUMERIC(29),
  proc_id NUMERIC(29),
  procedure_quantity NUMERIC(32, 3),
  modifier_one STRING,
  modifier_two STRING,
  modifier_three STRING,
  modifier_four STRING,
  dx_one_id NUMERIC(29),
  dx_two_id NUMERIC(29),
  dx_three_id NUMERIC(29),
  dx_four_id NUMERIC(29),
  dx_five_id NUMERIC(29),
  dx_six_id NUMERIC(29),
  serv_area_id NUMERIC(29),
  loc_id NUMERIC(29),
  dept_id NUMERIC(29),
  pos_id NUMERIC(29),
  action_cvg_id NUMERIC(29),
  user_id STRING,
  tx_num INT64,
  int_pat_id STRING,
  referral_source_id STRING,
  payment_source_c INT64,
  visit_number STRING,
  pat_enc_csn_id NUMERIC(29),
  action_user_id STRING,
  hsp_account_id NUMERIC(29),
  bill_area_id NUMERIC(29),
  sourcecprimarykeyvalue STRING,
  regionkey INT64,
  tx_comment STRING,
  dwlastupdated DATETIME,
  dist_user_id STRING,
  undist_user_id STRING,
  cur_payor_id INT64,
  dwlastupdatedatetime DATETIME
)
CLUSTER BY regionkey;