CREATE TABLE IF NOT EXISTS edwpsc.epic_facttransactionsclaimlinecharge
(
  transactionsclaimlinechargekey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  facilitykey INT64,
  claimlinechargekey INT64,
  cptcodekey INT64,
  trrefid INT64,
  transactiontype STRING,
  transactionflag STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiontime TIME,
  transactionperiod STRING,
  transactionbyuserkey INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  etrid NUMERIC(29),
  PRIMARY KEY (transactionsclaimlinechargekey) NOT ENFORCED
)
;