CREATE TABLE IF NOT EXISTS edwpsc.epic_factclaimpayment
(
  claimpaymentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  facilitykey INT64,
  encounterkey INT64,
  iplankey INT64,
  patientkey INT64,
  paymenttypekey INT64,
  contractualadjustmentamt NUMERIC(33, 4),
  allowedamt NUMERIC(33, 4),
  coinsuranceamt NUMERIC(33, 4),
  memberbalanceamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  deductibleamt NUMERIC(33, 4),
  withheldamt NUMERIC(33, 4),
  msgcode STRING,
  createddatekey DATE,
  createdtime TIME,
  modifieddatekey DATE,
  modifiedtime TIME,
  checkamt NUMERIC(33, 4),
  checknumber STRING,
  checktypedesc STRING,
  posteddatekey DATE,
  checkdatekey DATE,
  eomb1 STRING,
  memo STRING,
  depositdatekey DATE,
  paymentfacilitykey INT64,
  unpostedamt NUMERIC(33, 4),
  batchkey INT64,
  treasurybatchnumber STRING,
  treasurybatchdepositdate DATE,
  treasurybatchpayername STRING,
  paymentdescription STRING,
  deletedflag INT64,
  eradetailid INT64,
  eraflag INT64,
  erafileid INT64,
  paymentlock INT64,
  paymentmodifieddatekey DATE,
  eraclaimstatusclp02 INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  matchingtransactionnumber INT64,
  epicpaymenttypekey INT64,
  PRIMARY KEY (claimpaymentkey) NOT ENFORCED
)
;