CREATE TABLE IF NOT EXISTS edwpsc.epic_factworkqueuefollowup
(
  regionkey INT64,
  regionname STRING,
  coid STRING,
  facilityname STRING,
  claimkey INT64,
  claimlinechargekey INT64,
  patientmrn STRING,
  chargeslipnumber STRING,
  servicedate DATE,
  createddate DATE,
  invoicenumber STRING,
  visitnumber INT64,
  transactionnumber INT64,
  workqueuetype STRING,
  workqueueid STRING,
  workqueuename STRING,
  workqueuetab STRING,
  enteredworkqueuedate DATE,
  daysinworkqueue INT64,
  lastworkeddate DATE,
  daysfromlastworkeddate INT64,
  totalbalanceamt NUMERIC(33, 4),
  cptbalanceamt NUMERIC(33, 4),
  epicoutstandingamt NUMERIC(33, 4),
  cptcode STRING,
  cptcodename STRING,
  cptdeleteflag INT64,
  reviewedbyuserkey INT64,
  followupstatus STRING,
  isprimaryflag INT64,
  userdeferreddate DATE,
  systemdeferreddate DATE,
  completeddate DATE,
  liabilityfinancialclass INT64,
  liabilityfinancialclassname STRING,
  liabilityiplankey INT64,
  liabilityiplanname STRING,
  epicfinancialclass INT64,
  epicfinancialclassdesc STRING,
  servicingprovidername STRING,
  sourceaprimarykeyvalue INT64,
  insertedby INT64,
  inserteddtm DATETIME,
  encounterid INT64,
  encounterkey INT64,
  originallastworkeddate DATE,
  dwlastupdatedatetime DATETIME
)
;