CREATE TABLE IF NOT EXISTS edwpsc.epic_facttransactionsclaimcontractualadjustment
(
  transactionsclaimcontractualadjustmentkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  claimlineliabilityiplankey INT64,
  facilitykey INT64 NOT NULL,
  claimpaymentkey INT64 NOT NULL,
  adjustmentcodekey INT64,
  trrefid INT64,
  transactiontype STRING,
  transactionflag STRING NOT NULL,
  transactionamt NUMERIC(33, 4) NOT NULL,
  transactiondatekey DATE NOT NULL,
  transactiontime TIME NOT NULL,
  transactionbyuserkey INT64 NOT NULL,
  transactionperiod STRING,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  sourcebprimarykeyvalue STRING NOT NULL,
  sourcebrecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  matchingtransactionnumber INT64,
  debitcreditflag INT64,
  matchingtrrefid INT64,
  accountkey INT64,
  patientkey INT64,
  distributedbyuserkey STRING,
  undistributedbyuserkey STRING,
  etrid NUMERIC(29),
  matchingetrid NUMERIC(29),
  PRIMARY KEY (transactionsclaimcontractualadjustmentkey) NOT ENFORCED
)
;