CREATE TABLE IF NOT EXISTS edwpsc.epic_refprovider
(
  providerkey INT64 NOT NULL,
  providerfullname STRING,
  providerfirstname STRING,
  providermiddlename STRING,
  providerlastname STRING,
  providerprimaryaddressline1 STRING,
  providerprimaryaddressline2 STRING,
  providerprimaryaddressline3 STRING,
  providerprimarycity STRING,
  providerprimarystate STRING,
  providerprimaryzip STRING,
  providerphone STRING,
  providerfax STRING,
  provideremail STRING,
  providernpi STRING,
  providerupin STRING,
  providerprintname STRING,
  provideruserid STRING,
  providercliniciantitle STRING,
  provideractiveflag INT64,
  providertype STRING,
  providerspeciality STRING,
  providersex STRING,
  providerdob STRING,
  deleteflag INT64,
  regionkey INT64,
  provid STRING NOT NULL,
  serrefsrceid STRING,
  epicproviderid STRING,
  providercid STRING,
  providerinternalid STRING,
  sourceaprimarykey STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  providerprimarygeographykey INT64,
  providerusertype INT64,
  providerinitials STRING,
  providerdobdatekey DATE,
  providerssn STRING,
  providermobilephone STRING,
  providerpager STRING,
  providerprimaryservicelocation INT64,
  providerspecialitycode STRING,
  providercode STRING,
  providertaxid STRING,
  providertaxidtype STRING,
  providertaxidsuffix STRING,
  providertaxonomycode STRING,
  providerfacilitykey INT64,
  providerdeano STRING,
  providersplicno STRING,
  providerstlicno STRING,
  provideranelicno STRING,
  providerdoctortype STRING,
  providerroletype STRING,
  providergrpnpi STRING,
  providerinactive INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATETIME,
  PRIMARY KEY (providerkey) NOT ENFORCED
)
;