CREATE TABLE IF NOT EXISTS edwpsc.epic_factencountercpt
(
  encountercptkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  claimkey INT64,
  encounterkey INT64,
  encounterid INT64,
  patientinternalid INT64,
  cptcodekey INT64,
  cptcode STRING,
  cptunits INT64,
  cptcharges NUMERIC(31, 2),
  visitdate DATE,
  primaryflag INT64,
  deleteflag INT64,
  createdbyuserkey INT64,
  deletedbyuserkey INT64,
  deletedondatekey DATE,
  encounterstatus STRING,
  accountid INT64,
  servicingproviderkey INT64,
  servicingproviderid STRING,
  billingproviderkey INT64,
  billingproviderid INT64,
  patientkey INT64,
  patientid INT64,
  practicekey INT64,
  practiceid INT64,
  transactionid INT64,
  sourceaprimarykeyvalue INT64,
  sourcebprimarykeyvalue INT64,
  sourcecprimarykeyvalue STRING,
  sourcerecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;