CREATE TABLE IF NOT EXISTS edwpsc.epic_factclaimlinepayment
(
  claimlinepaymentkey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  transactionnumber INT64,
  visitnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  claimlineliabilityiplankey INT64,
  facilitykey INT64,
  claimlinechargeskey INT64,
  claimpaymentskey INT64,
  paymentdetailid INT64,
  invcptid INT64,
  paymentamt NUMERIC(33, 4),
  contractualadjustmentamt NUMERIC(33, 4),
  withheldamt NUMERIC(33, 4),
  deductibleamt NUMERIC(33, 4),
  coinsuranceamt NUMERIC(33, 4),
  allowedamt NUMERIC(33, 4),
  memberresponsibilityamt NUMERIC(33, 4),
  msgcode STRING,
  linetaxamt NUMERIC(33, 4),
  eraadjustmentamt NUMERIC(33, 4),
  paymenttypekey INT64,
  createddatekey DATE,
  createdtime TIME,
  createdbyuserkey INT64,
  modifieddatekey DATE,
  modifiedtime TIME,
  modifiedbyuserkey INT64,
  cptdeleteflag INT64,
  sourceaprimarykeyvalue INT64,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (claimlinepaymentkey) NOT ENFORCED
)
;