CREATE TABLE IF NOT EXISTS edwpsc.onbase_factremoteprintrequest
(
  documenthandle INT64,
  queuename STRING,
  itemname STRING,
  lifecyclename STRING,
  documenttype STRING,
  entrydate STRING,
  exitdate STRING,
  username STRING,
  userid STRING,
  status STRING,
  datestored STRING,
  itemstatus INT64,
  patientname STRING,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  servername STRING,
  region INT64,
  cliniccode STRING,
  patientaccountnumber STRING,
  workflowtransactionnumber INT64,
  workflowtransactionentrydate DATETIME,
  workflowtransactionexitdate DATETIME,
  workflowtransactiontype STRING,
  workflowtransactionname STRING,
  workflowtransactionusername STRING,
  workflowtransactionuserid STRING,
  onbaseremoteprintrequestkey INT64 NOT NULL
)
;