CREATE TABLE IF NOT EXISTS edwpsc.onbase_factworkqueue
(
  documenthandle INT64,
  itemname STRING,
  lifecyclename STRING,
  documenttype STRING,
  queuename STRING,
  entrydate DATE,
  entrytime STRING,
  exitdate DATE,
  exittime STRING,
  username STRING,
  userid STRING,
  providerlastname STRING,
  providerfirstname STRING,
  color STRING,
  npi STRING,
  decision STRING,
  status STRING,
  packettype STRING,
  effectivedate STRING,
  numberofdaysopen INT64,
  completeflag INT64,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  arqueue STRING,
  urgency STRING,
  payor STRING,
  startdate DATE,
  datestored STRING,
  itemstatus INT64,
  patientname STRING,
  wfscrub1 STRING,
  wfscrub2 STRING,
  coid STRING,
  erabatchnumber NUMERIC(29),
  cliniccode STRING,
  treasurybatchnumber STRING,
  dwlastupdatedatetime DATETIME,
  onbaseworkqueuekey INT64 NOT NULL
)
;