CREATE TABLE IF NOT EXISTS edwpsc.pk_factholdingbinedits
(
  editkey INT64 NOT NULL,
  saveddatetime DATETIME,
  saveddatekey DATE,
  savedbyuserid STRING,
  savedbyuserfirstname STRING,
  savedbyuserlastname STRING,
  codeeditexternalid STRING,
  codeeditcpt STRING,
  codeedittype STRING,
  codeeditmsg STRING,
  validityerror STRING,
  freetextcharges STRING,
  freetextdx STRING,
  importedcharge STRING,
  billingarea STRING,
  billingprovideruserid STRING,
  billingproviderfirstname STRING,
  billingproviderlastname STRING,
  servicedate DATE,
  submissiondate DATE,
  visittype STRING,
  department STRING,
  mrn STRING,
  accountid STRING,
  financialclass STRING,
  pkregionname STRING,
  sourceaprimarykeyvalue STRING,
  sourcebprimarykeyvalue STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  practiceid STRING,
  dwlastupdatedatetime DATETIME,
  PRIMARY KEY (editkey) NOT ENFORCED
)
;