CREATE TABLE IF NOT EXISTS edwpsc.pk_factbalancing
(
  pkbid INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  cptfoundinecw STRING NOT NULL,
  visitnumber STRING,
  batchnumber STRING,
  firstmessageid INT64,
  lastmessageid INT64,
  pmid INT64,
  firstdatereceived DATETIME,
  lastdatereceived DATETIME,
  firstclaimnumber INT64,
  lastclaimnumber INT64,
  firstmessagestatus INT64,
  lastmessagestatus INT64,
  lasterrormessage STRING,
  doctorid INT64,
  reconciledflag INT64,
  facilityid INT64,
  practiceidfromresults STRING,
  proceduredatefromhl7 STRING,
  dobfromhl7 STRING,
  patientfirstnamefromhl7 STRING,
  patientlastnamefromhl7 STRING,
  patientidfoundfromhl7 INT64,
  providernpifromhl7 STRING,
  provideridfoundfromhl7 INT64,
  procedurecodefromhl7 STRING,
  claimnumberfoundfromhl7lookup INT64,
  cptidfoundfromhl7lookup INT64,
  createdbyfromhl7lookup STRING,
  claimpatientidfound2fromresultslookup INT64,
  patientfirstnameresultslookup STRING,
  patientlastnameresultslookup STRING,
  patientdobresultslookup STRING,
  claimservicedtresultslookup DATETIME,
  claimnumberfound2fromresults INT64,
  cptidfound2fromresultslookup INT64,
  createdby2fromresultslookup STRING,
  createdbyid2fromresultslookup INT64,
  createdbyidfromhl7lookup INT64,
  claimnumber INT64,
  voidflagclaim INT64,
  deleteflagclaim INT64,
  patientid INT64,
  createdbyid INT64,
  inbalanceflag INT64,
  claimcreatedbysystemflag INT64,
  claimcreatedbyuserflag INT64,
  hashcpt NUMERIC(33, 4),
  facilitycodefromhl7 STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  providernamefromhl7 STRING,
  isignoredflag INT64,
  actionbyusername STRING,
  actiondatetime DATETIME,
  claimnumberfound3 INT64,
  reconmodifieddate DATETIME,
  reconuserid STRING,
  reconclaimid INT64,
  reconnotes STRING,
  messagecontrolid STRING,
  chargetransactionid STRING,
  pkregionname STRING,
  PRIMARY KEY (pkbid) NOT ENFORCED
)
;