CREATE TABLE IF NOT EXISTS edwpsc.pk_factskillednursingfacilitynote
(
  pkskillednursingfacilitynotekey INT64 NOT NULL,
  coid STRING,
  pkregionname STRING,
  notetypename STRING,
  source STRING,
  visitlocationfacility STRING,
  pkfinancialnumber STRING,
  pkencounterkey INT64,
  pkencounterid INT64,
  patientid INT64,
  patientlastname STRING,
  patientfirstname STRING,
  patientmiddlename STRING,
  patientmrn STRING,
  chargetransactionid INT64,
  notecreatedby STRING,
  notemodifiedby STRING,
  notecreateddate DATETIME,
  notedate DATETIME,
  signedstatus STRING,
  signeddate DATETIME,
  notelasteditdate DATETIME,
  deleteflag INT64,
  synccreatedtime DATETIME,
  syncmodifiedtime DATETIME,
  sourceaprimarykeyvalue INT64,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;