CREATE TABLE IF NOT EXISTS edwpsc.pk_factrejections
(
  pkrejectionskey INT64 NOT NULL,
  pkfinancialnumber STRING NOT NULL,
  pkregionname STRING,
  messageid INT64,
  controlid STRING,
  sendingfacility STRING,
  sitecode STRING,
  patientnumber STRING,
  patientlastname STRING,
  patientfirstname STRING,
  errorcreatedatetime DATETIME,
  errortype STRING,
  error STRING,
  dft_attendingprovidernpi INT64,
  dft_attendingproviderlastname STRING,
  dft_attendingproviderfirstname STRING,
  dft_performedbyproviderlastname STRING,
  dft_performedbyproviderfirstname STRING,
  dft_admitdatetime DATETIME,
  dft_dischargedatetime DATETIME,
  dft_servicedate DATE,
  dft_patientmrn STRING,
  dft_patientdob DATE,
  dft_fullmessage STRING,
  dft_chargeid STRING,
  resolvedflag INT64,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;