CREATE TABLE IF NOT EXISTS edwpsc.pk_facttransactionshistoric
(
  pktransactionhistorickey INT64 NOT NULL,
  pkregionname STRING,
  historicalstatus STRING,
  saveddate DATETIME,
  savedby STRING,
  savedbyfirstname STRING,
  savedbylastname STRING,
  billingarea STRING,
  billingprovider STRING,
  billingproviderfirstname STRING,
  billingproviderlastname STRING,
  servicedate DATETIME,
  submissiondate DATETIME,
  visittype STRING,
  department STRING,
  patientmrn STRING,
  roles STRING,
  accountid INT64,
  historicalfinancialclass STRING,
  cptcode STRING,
  sourceaprimarykeyvalue INT64,
  sourcebprimarykeyvalue INT64,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  heldforreview INT64,
  isdeleted INT64,
  dwlastupdatedatetime DATETIME
)
;