CREATE TABLE IF NOT EXISTS edwpsc.pk_factmips
(
  pkmipskey INT64 NOT NULL,
  pkregionname STRING,
  measure STRING,
  measurenumber INT64,
  measuredescription STRING,
  measuretitle STRING,
  responsesubmittedflag INT64,
  responsedeletedflag INT64,
  responseisbillingproviderflag INT64,
  createddatetime DATETIME,
  createdbyusername STRING,
  createdbyuserlastname STRING,
  createdbyuserfirstname STRING,
  modifieddatetime DATETIME,
  modifiedbyusername STRING,
  modifiedbyuserlastname STRING,
  modifiedbyuserfirstname STRING,
  chargetransactionid INT64,
  pkfinancialnumber STRING,
  patientlastname STRING,
  patientfirstname STRING,
  rolename STRING,
  sourceaprimarykeyvalue INT64,
  sourcebprimarykeyvalue INT64,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME
)
;