CREATE TABLE IF NOT EXISTS edwpsc.pv_facttransactionsclaimlinecontractualadjustment
(
  transactionsclaimlinecontractualadjustmentskey INT64 NOT NULL,
  claimkey INT64,
  claimnumber INT64,
  regionkey INT64,
  coid STRING,
  coidconfigurationkey INT64,
  servicingproviderkey INT64,
  claimpayer1iplankey INT64,
  facilitykey INT64,
  claimlinepaymentskey INT64,
  transactiontype STRING,
  transactionflag STRING,
  transactionamt NUMERIC(33, 4),
  transactiondatekey DATE,
  transactiontime TIME,
  transactionclosingdatekey DATE,
  transactionbyuserkey INT64,
  trrefid STRING,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  practicekey INT64,
  practicename STRING,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  posteddatekey DATE,
  paymentnumber INT64,
  PRIMARY KEY (transactionsclaimlinecontractualadjustmentskey) NOT ENFORCED
)
;