CREATE TABLE IF NOT EXISTS edwpsc.pv_facttransactionsclaimlinecharge
(
  transactionsclaimlinechargekey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  claimlinechargekey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  transactiontype STRING NOT NULL,
  transactionflag STRING NOT NULL,
  transactionamt NUMERIC(33, 4) NOT NULL,
  transactiondatekey DATE NOT NULL,
  transactiontime TIME NOT NULL,
  transactionclosingdatekey DATE,
  transactionbyuserkey INT64 NOT NULL,
  sourceaprimarykeyvalue STRING NOT NULL,
  sourcearecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  trrefid INT64,
  practicekey INT64,
  practicename STRING,
  PRIMARY KEY (transactionsclaimlinechargekey) NOT ENFORCED
)
;