CREATE TABLE IF NOT EXISTS edwpsc.pv_factbillvendorinventory
(
  billvendorinventorykey INT64 NOT NULL,
  regionkey INT64,
  practicename STRING,
  coid STRING,
  claimkey INT64,
  claimnumber INT64,
  claimdatekey DATE,
  totalchargeamt NUMERIC(31, 2),
  claimstatus INT64,
  claimstatusname STRING,
  claimstatuslastmodifieddate DATE,
  translateddatetime DATETIME,
  claimhistorylastmodifieddate DATE,
  ssibatchid INT64,
  claimreleasedate DATETIME,
  category277 STRING,
  status277 STRING,
  billedstatus STRING,
  holdcode STRING,
  destination STRING,
  batchidecw INT64,
  financialgroup STRING,
  currentpayername STRING,
  currentpayorindicator INT64,
  payer1iplankey INT64,
  payer1iplanid STRING,
  payer1financialclass STRING,
  payer2iplankey INT64,
  payer2iplanid STRING,
  payer2financialclass STRING,
  payer3iplankey INT64,
  payer3iplanid STRING,
  payer3financialclass STRING,
  facilitykey INT64,
  facilityid INT64,
  facilitycode STRING,
  providertaxid STRING,
  originalclaimkey INT64,
  originalclaimnumber INT64,
  deleteflag INT64,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcesystemcode STRING,
  dwlastupdatedatetime DATETIME,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  tracenumber STRING,
  trackstat STRING,
  billdate DATE,
  prilbilldate DATE,
  secbilldate DATE,
  seclbilldate DATE,
  terbilldate DATE,
  terlbilldate DATE,
  claimtype STRING,
  dest STRING,
  sourcecode STRING,
  payorid STRING,
  payorsubid STRING,
  billtrace STRING
)
;