CREATE TABLE IF NOT EXISTS edwpsc.pv_factclaimdiagnosis
(
  claimdiagnosiskey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  diagnosiscodekey INT64 NOT NULL,
  primarycode INT64 NOT NULL,
  icdorder INT64 NOT NULL,
  icdcode STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  snomedvalue STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  createddate DATETIME,
  createdbyuserkey INT64,
  PRIMARY KEY (claimdiagnosiskey) NOT ENFORCED
)
;