CREATE TABLE IF NOT EXISTS edwpsc.pv_factclaimsonhold
(
  claimsonholdkey INT64 NOT NULL,
  loaddatekey DATE,
  claimkey INT64,
  claimnumber INT64,
  claimbalance NUMERIC(33, 4),
  practicename STRING,
  regionkey INT64,
  artivaruleid NUMERIC(29, 0),
  artivaruledesc STRING,
  artivaruleowner STRING,
  artivarulecategoryid NUMERIC(29, 0),
  artivaholdcodeid STRING,
  artivaholdcodedescription STRING,
  artivaholdcodetype STRING,
  artivappiidpe NUMERIC(29, 0),
  artivappitypepe STRING,
  artivappiidedi NUMERIC(29, 0),
  artivappitypeedi STRING,
  artivappiphase STRING,
  artivarulecreatedate DATE,
  artivaruleactiveflag INT64,
  artivaruleglobalflag INT64,
  artivarulesource STRING,
  artivarulelastupdatedate DATE,
  artivarulelastupdatenote STRING,
  artivarulelastupdateby STRING,
  artivapsenrelayguid STRING,
  artivaholdcoderiskreportflag STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;