CREATE TABLE IF NOT EXISTS edwpsc.pv_factclaimlinechargeclosedatear
(
  claimlinechargekey INT64 NOT NULL,
  coid STRING NOT NULL,
  closingdatekey DATE NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimtype STRING,
  payer1iplankey INT64 NOT NULL,
  payer1iplanid INT64 NOT NULL,
  payer1financialclasskey INT64 NOT NULL,
  liabilityiplankey STRING NOT NULL,
  liabilityiplanid INT64 NOT NULL,
  liabilityfinancialclasskey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  practice STRING NOT NULL,
  cptstartservicedatekey DATE NOT NULL,
  cptendservicedatekey DATE NOT NULL,
  cptcode STRING NOT NULL,
  cptcodekey INT64 NOT NULL,
  cptposkey INT64 NOT NULL,
  cptorder INT64 NOT NULL,
  chargesamt NUMERIC(33, 4) NOT NULL,
  patbalanceamt NUMERIC(33, 4) NOT NULL,
  insbalanceamt NUMERIC(33, 4) NOT NULL,
  balanceamt NUMERIC(33, 4) NOT NULL,
  adjustmentamt NUMERIC(33, 4) NOT NULL,
  paymentamt NUMERIC(33, 4) NOT NULL,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  rebillflag STRING,
  crgdetailpk STRING,
  crgheaderpk STRING,
  arctrlnum INT64,
  arheaderpk STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME
)
;