CREATE TABLE IF NOT EXISTS edwpsc.pv_factinvoicelinepayment
(
  invoicelinepaymentkey INT64 NOT NULL,
  coid STRING,
  regionkey INT64,
  practice STRING,
  invoicenumber INT64,
  invoicelinenumber INT64,
  invoicelinechargekey INT64,
  paymentamt NUMERIC(33, 4),
  paymentdatekey DATE,
  paymenttype STRING,
  transactionnumber INT64,
  invoicekey INT64,
  batchkey INT64,
  closingdatekey DATE,
  createdbyuserkey INT64,
  invoicetransactiondesc STRING,
  invoicereason STRING,
  checknumber STRING,
  checkdatekey DATE,
  checktypedesc STRING,
  paymentmsgcode STRING,
  depositdatekey DATE,
  paymentnumber INT64,
  treasurybatchnumber STRING,
  treasurybatchdepositdate DATE,
  treasurybatchpayername STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (invoicelinepaymentkey) NOT ENFORCED
)
;