CREATE TABLE IF NOT EXISTS edwpsc.pv_factriskanalysis
(
  riskanalysiskey INT64 NOT NULL,
  riskloaddatekey DATETIME,
  claimcategory STRING NOT NULL,
  claimnumber INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  coidlob STRING,
  coiddeptnum STRING,
  coidname STRING,
  marketname STRING,
  divisionname STRING,
  groupname STRING,
  renderingprovidernpi STRING,
  payerfinancialclass STRING,
  cpid STRING,
  facilityid STRING,
  practicefederaltaxid STRING,
  artivaruleid NUMERIC(29),
  artivaruledesc STRING,
  artivarulecreatedate DATE,
  artivarulelastupdatedate DATE,
  artivaruleglobalflag INT64,
  artivaholdcodeid STRING,
  artivaholdcodedescription STRING,
  artivaholdcodetype STRING,
  claimpayorid STRING,
  claimpayorname STRING,
  claimpayorauthorizationnumber STRING,
  servicedatekey DATE,
  claimage INT64,
  claimlastreleaseddate DATE,
  totalbalanceamt NUMERIC(33, 4),
  totalchargesamt NUMERIC(33, 4),
  renderingprovider STRING,
  providerkey STRING,
  cactusdivisionname STRING,
  providerfirstname STRING,
  providerlastname STRING,
  providermiddlename STRING,
  providernpi STRING,
  providerstartdate DATE,
  providernotificationdate DATE,
  providerlastrfcreceiveddate DATE,
  groupkey STRING,
  providergroupname STRING,
  groupdba STRING,
  groupenrollmentoperation STRING,
  provideraddresstype STRING,
  practiceaddressline1 STRING,
  practiceaddressline2 STRING,
  practicecity STRING,
  practicestate STRING,
  practicezip STRING,
  practicetaxid STRING,
  ppikey STRING,
  ppieffectivedate DATE,
  ppidepartmentflag STRING,
  ppicpidpayorname STRING,
  ppicpidpayorid STRING,
  payorsplitbylocationflag STRING,
  ppitype STRING,
  ppistatus STRING,
  ppistatusdescription STRING,
  ppiphase STRING,
  ppienrollmentaction STRING,
  ppileadgrouptaxid STRING,
  ppialternateeffectivedate DATE,
  ppistatusdate DATE,
  ppilastworkeddate DATE,
  ppiapplicationsenttopayordate DATE,
  ppiapplicationreceivedfrompayordate DATE,
  ppiapplicationsenttoproviderdate DATE,
  ppiapplicationreceivedfromproviderdate DATE,
  riskstatus STRING,
  risksubcategory STRING,
  psgriskstatus STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;