CREATE TABLE IF NOT EXISTS edwpsc.pv_factsnapshotinitialdenials
(
  monthid INT64 NOT NULL,
  snapshotdate DATE,
  coid STRING NOT NULL,
  claimnumber INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  renderingproviderkey INT64 NOT NULL,
  patientkey INT64 NOT NULL,
  claimstatuskey INT64 NOT NULL,
  payer1iplankey INT64 NOT NULL,
  claimservicedate DATE NOT NULL,
  claimservicedateyear INT64,
  claimservicedatemonth INT64,
  claimbalance NUMERIC(33, 4) NOT NULL,
  claimcharge NUMERIC(33, 4) NOT NULL,
  voidflag INT64 NOT NULL,
  deleteflag INT64 NOT NULL,
  arclaimflag INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  firstinsurancebilldatekey DATE,
  lastbilldatekey DATE,
  numberofbills INT64,
  liabilitydate DATE NOT NULL,
  claimdate DATE NOT NULL,
  liabilityowner STRING,
  rhholdcode STRING,
  claimlinechargekey INT64 NOT NULL,
  cptcodekey INT64 NOT NULL,
  cptcode STRING,
  cptservicestartdate DATE,
  cptserviceenddate DATE,
  cptdeleteflag INT64 NOT NULL,
  cptmodifier1 STRING,
  cptmodifier2 STRING,
  cptmodifier3 STRING,
  cptmodifier4 STRING,
  linecharge NUMERIC(33, 4) NOT NULL,
  linechargefinal NUMERIC(33, 4) NOT NULL,
  lineinspayment NUMERIC(33, 4) NOT NULL,
  lineinspaymentfirstdate DATE,
  lineinspaymentflag INT64 NOT NULL,
  linepatpayment NUMERIC(33, 4) NOT NULL,
  linepatpaymentflag INT64 NOT NULL,
  lineinscontractual NUMERIC(33, 4) NOT NULL,
  lineinscontractualfirstdate DATE,
  lineinscontractualflag INT64 NOT NULL,
  lineadjustment NUMERIC(33, 4) NOT NULL,
  lineadjustmentflag INT64 NOT NULL,
  linebalance NUMERIC(33, 4) NOT NULL,
  lineinbalanceflag INT64 NOT NULL,
  lineadminadj NUMERIC(33, 4) NOT NULL,
  linedenialadj NUMERIC(33, 4) NOT NULL,
  linecharityadj NUMERIC(33, 4) NOT NULL,
  linecontractualadj NUMERIC(33, 4) NOT NULL,
  lineuninsureddiscountadj NUMERIC(33, 4) NOT NULL,
  linerefundadj NUMERIC(33, 4) NOT NULL,
  linensfadj NUMERIC(33, 4) NOT NULL,
  lineescheatadj NUMERIC(33, 4) NOT NULL,
  linebaddebtadj NUMERIC(33, 4) NOT NULL,
  lineotheradj NUMERIC(33, 4) NOT NULL,
  voiddate DATE,
  priorclaimkey INT64,
  voidfirstbilledclaimkey INT64,
  voidfirstbilledclaimnumber INT64,
  voidfirstbilleddatekey DATE,
  onfirstbilledflag INT64 NOT NULL,
  onfirstbilledcharge INT64,
  voidfirstbilledclaimlinechargekey INT64,
  firstdenialcarcrarccode STRING,
  firstdenialeradate DATE,
  firstdenialcarccodes STRING,
  firstdenialrarccodes STRING,
  firstdenialpayername STRING,
  firstdenialcategory STRING,
  initialdeniedcharges NUMERIC(33, 4) NOT NULL,
  firstdenialflag INT64 NOT NULL,
  linedenialadjflag INT64 NOT NULL,
  firstdenialcarcrarctype STRING,
  firstdenialcarcisdenial STRING,
  firstdenialcarcrequiresrarc STRING,
  firstdenialrarcisdenial STRING,
  lastdenialcarcrarccode STRING,
  lastdenialeradate DATE,
  lastdenialcarccodes STRING,
  lastdenialrarccodes STRING,
  lastdenialpayername STRING,
  lastdenialcategory STRING,
  lastdenialcarcrarctype STRING,
  lastdenialcarcisdenial STRING,
  lastdenialcarcrequiresrarc STRING,
  lastdenialrarcisdenial STRING,
  firsteracarcrarccode STRING,
  firsteradate DATE,
  firsteracarccodes STRING,
  firsterararccodes STRING,
  firsterapayername STRING,
  firsteracategory STRING,
  firsteracarcrarctype STRING,
  firsteracarcisdenial STRING,
  firsteracarcrequiresrarc STRING,
  firsterararcisdenial STRING,
  lasteracarcrarccode STRING,
  lasteradate DATE,
  lasteracarccodes STRING,
  lasterararccodes STRING,
  lasterapayername STRING,
  lasteracategory STRING,
  lasteracarcrarctype STRING,
  lasteracarcisdenial STRING,
  lasteracarcrequiresrarc STRING,
  lasterararcisdenial STRING,
  artivapool STRING NOT NULL,
  artivaliabilitylastreviewed STRING NOT NULL,
  artivaliabilityfollowupdate STRING NOT NULL,
  lastadjustmentcode STRING,
  lastadjustmentname STRING,
  lastadjustmentcategory STRING,
  lastadjustmentdate DATE,
  lineadminadjlastdate DATE,
  linedenialadjlastdate DATE,
  linecharityadjlastdate DATE,
  linecontractualadjlastdate DATE,
  lineuninsureddiscountadjlastdate DATE,
  linerefundadjlastdate DATE,
  linensfadjlastdate DATE,
  lineescheatadjlastdate DATE,
  linebaddebtadjlastdate DATE,
  lineotheradjlastdate DATE,
  ietflag STRING NOT NULL,
  ietcreatedate STRING NOT NULL,
  ietlastmodifieddate STRING NOT NULL,
  denialcount INT64 NOT NULL,
  deniallasteradate DATE,
  claimcptcode1 STRING,
  claimcptcode2 STRING,
  claimcptcode3 STRING,
  claimcptcode4 STRING,
  claimcptcode5 STRING,
  gldeptnumber STRING NOT NULL,
  providerspecialtyname STRING,
  providerspecialtytype STRING,
  providerspecialtycategory STRING,
  initialiplankey INT64,
  insertedby NUMERIC(29) NOT NULL,
  inserteddtm DATETIME NOT NULL,
  modifiedby NUMERIC(29) NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL
)
PARTITION BY snapshotdate
;