CREATE TABLE IF NOT EXISTS edwpsc.pv_factinvoicelinecharge
(
  invoicelinechargekey INT64 NOT NULL,
  regionkey INT64,
  coid STRING,
  practice STRING,
  invoicekey INT64,
  invoicenumber INT64,
  invoicelinenumber INT64,
  servicedatekey DATE,
  invoicedescription STRING,
  invoiceunits INT64,
  linechargesperunit NUMERIC(33, 4),
  linechargesamt NUMERIC(33, 4),
  linepaymentamt NUMERIC(33, 4),
  lineadjustmentamt NUMERIC(33, 4),
  linebalanceamt NUMERIC(33, 4),
  linecalculatedbalance NUMERIC(33, 4),
  transactiondatekey DATETIME,
  lastupdatedbyuserkey INT64,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  PRIMARY KEY (invoicelinechargekey) NOT ENFORCED
)
;