CREATE TABLE IF NOT EXISTS edwpsc.pv_factclaimlinepayment
(
  claimlinepaymentkey INT64 NOT NULL,
  claimkey INT64 NOT NULL,
  claimnumber INT64 NOT NULL,
  regionkey INT64 NOT NULL,
  coid STRING NOT NULL,
  coidconfigurationkey INT64 NOT NULL,
  servicingproviderkey INT64 NOT NULL,
  claimpayer1iplankey INT64 NOT NULL,
  facilitykey INT64 NOT NULL,
  claimlinechargeskey INT64,
  claimpaymentskey INT64,
  paymentdetailid STRING,
  allowedamt NUMERIC(33, 4),
  deductibleamt NUMERIC(33, 4),
  coinsuranceamt NUMERIC(33, 4),
  memberresponsibilityamt NUMERIC(33, 4),
  paymentamt NUMERIC(33, 4),
  contractualadjustmentamt NUMERIC(33, 4),
  withheldamt NUMERIC(33, 4),
  invcptid STRING,
  msgcode STRING,
  linetaxamt NUMERIC(33, 4),
  eraadjustmentamt NUMERIC(33, 4),
  createddatekey DATE,
  createdtime TIME,
  createdbyuserkey INT64,
  timestamp DATETIME,
  modifieddatekey DATE,
  modifiedtime TIME,
  modifiedbyuserkey INT64,
  closingdatekey DATE,
  sourceaprimarykeyvalue STRING,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue STRING,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  batchkey INT64,
  checknumber STRING,
  paymenttypedesc STRING,
  postedtoclaimdatekey DATE,
  deleteflag INT64,
  PRIMARY KEY (claimlinepaymentkey) NOT ENFORCED
)
;