CREATE TABLE IF NOT EXISTS edwpsc.pv_junceradetail
(
  pveradetailkey INT64 NOT NULL,
  regionkey INT64,
  fileid INT64,
  paymentid INT64,
  payorname STRING,
  providername STRING,
  postedby STRING,
  postedbyuserkey INT64,
  posteddate DATETIME,
  st02 STRING,
  transactiontype STRING,
  transactionamount NUMERIC(33, 4),
  transactionmethod STRING,
  transactiondate STRING,
  transactionnumber STRING,
  deletedby STRING,
  deletedbyuserkey INT64,
  deleteddate DATETIME,
  deletedreason STRING,
  payorid INT64,
  payoriplankey INT64,
  providerid INT64,
  providerkey INT64,
  storderid INT64,
  gsorderid INT64,
  isaorderid INT64,
  postingmessage STRING,
  deleteflag INT64,
  sourceaprimarykeyvalue STRING,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME
)
;