CREATE TABLE IF NOT EXISTS edwpsc.pv_refprovider_history
(
  providerkey INT64 NOT NULL,
  providerfirstname STRING,
  providerlastname STRING,
  providermiddlename STRING,
  providerusername STRING,
  providerprefixname STRING,
  providersuffixname STRING,
  providerprimaryaddressline1 STRING,
  providerprimaryaddressline2 STRING,
  providerprimarygeographykey INT64,
  providerusertype INT64,
  providerinitials STRING,
  providerdobdatekey DATE,
  providerssn STRING,
  providerprimaryservicelocation INT64,
  providerphone STRING,
  providermobilephone STRING,
  providerpager STRING,
  provideremail STRING,
  providerdeano STRING,
  providerfaxno STRING,
  providerspeciality STRING,
  providerspecialitycode STRING,
  providerprintname STRING,
  providercode STRING,
  providertaxid STRING,
  providertaxidtype STRING,
  providertaxidsuffix STRING,
  providernpi STRING,
  providerupin STRING,
  providertaxonomycode STRING,
  providerfacilitykey INT64,
  providersplicno STRING,
  providerstlicno STRING,
  provideranelicno STRING,
  providerdoctortype STRING,
  providerroletype STRING,
  providergrpnpi STRING,
  providertype STRING,
  providerinactive INT64,
  sourceaprimarykeyvalue INT64 NOT NULL,
  sourcearecordlastupdated DATETIME,
  sourcebprimarykeyvalue INT64,
  sourcebrecordlastupdated DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  regionkey INT64,
  providerpractice STRING,
  physicianguid STRING,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL
)
;