CREATE TABLE IF NOT EXISTS edwpsc.pv_rprtpvpreclaimreports
(
  clinic STRING,
  regionkey INT64,
  patientnumber INT64,
  lognum INT64,
  providername STRING,
  credential STRING,
  managingphyname STRING,
  practice STRING,
  logstatus STRING,
  visitdate DATE,
  primaryiplan STRING,
  primarypayertype STRING,
  patientlastname STRING,
  holdclaimyn STRING,
  diagnosiscount INT64,
  cptcountminuslabs INT64,
  emcode STRING,
  visitnotes STRING,
  firstjcode STRING,
  cpt1 STRING,
  cpt2 STRING,
  cpt3 STRING,
  cpt4 STRING,
  cpt5 STRING,
  type STRING,
  patientpayment NUMERIC(33, 4),
  reportname STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  transition STRING,
  clinicpatnumdocname STRING,
  tmcomplete STRING,
  ispatienttelemedicineeligible STRING,
  telemedicinetype STRING,
  telemedicinevisit STRING,
  finclass STRING,
  primaryfinclass STRING,
  arrivalstatus STRING,
  scodecarveoutflag STRING,
  virtualencflag STRING,
  quickvisitflag STRING,
  companyname STRING,
  protocol STRING,
  protocol1 STRING,
  protocol2 STRING,
  protocol3 STRING,
  protocol4 STRING,
  protocol5 STRING
)
;