CREATE TABLE IF NOT EXISTS edwpsc.pv_refpractice
(
  practicekey INT64 NOT NULL,
  practicename STRING,
  practiceprimaryaddressline1 STRING,
  practiceprimaryaddressline2 STRING,
  practiceprimarygeographykey INT64,
  practicetelephone STRING,
  practicefax STRING,
  practiceemail STRING,
  practicesiteid STRING,
  practicefederaltaxid STRING,
  practicecliaid STRING,
  practiceparenttin STRING,
  practicegroupnpi STRING,
  practicetaxonomycode STRING,
  practicelockboxno STRING,
  practicecob STRING,
  practiceprimarycoid STRING,
  practicestartdatekey DATE,
  practiceenddatekey DATE,
  practicespindowndatekey DATE,
  sourceprimarykeyvalue STRING NOT NULL,
  sourcerecordlastupdated DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  deleteflag INT64,
  regionkey INT64,
  practiceguid STRING,
  practiceid INT64,
  active BOOL,
  sysstarttime DATETIME NOT NULL,
  sysendtime DATETIME NOT NULL,
  PRIMARY KEY (practicekey) NOT ENFORCED
)
;