CREATE TABLE IF NOT EXISTS edwpsc.pv_refcompany
(
  companykey INT64 NOT NULL,
  practice STRING NOT NULL,
  cmpnum INT64 NOT NULL,
  cmpname STRING NOT NULL,
  cmpcontact STRING NOT NULL,
  authlist STRING NOT NULL,
  cmpaddress1 STRING NOT NULL,
  cmpaddress2 STRING NOT NULL,
  cmpcity STRING,
  cmpstate STRING NOT NULL,
  cmpzip STRING NOT NULL,
  cmpcountry STRING NOT NULL,
  cmpphone STRING NOT NULL,
  cmpphoneext STRING NOT NULL,
  cmpfax STRING NOT NULL,
  verified STRING NOT NULL,
  status STRING NOT NULL,
  groupname STRING NOT NULL,
  statementflag STRING NOT NULL,
  statementtype STRING NOT NULL,
  statementorder STRING NOT NULL,
  statementnotes STRING,
  wcpricing STRING NOT NULL,
  epspricing STRING NOT NULL,
  paymentterm STRING NOT NULL,
  printssn STRING NOT NULL,
  billingnotes STRING,
  alertnotes STRING,
  epscontact STRING NOT NULL,
  epsphone STRING NOT NULL,
  epsphoneext STRING NOT NULL,
  epsfax STRING NOT NULL,
  epsemail STRING NOT NULL,
  epsnotes STRING,
  epsbilltonum INT64 NOT NULL,
  epsbilltoname STRING NOT NULL,
  epsinstructions STRING,
  wccontact STRING NOT NULL,
  wcphone STRING NOT NULL,
  wcphoneext STRING NOT NULL,
  wcfax STRING NOT NULL,
  wcemail STRING NOT NULL,
  wcnotes STRING,
  wcbilltoflag STRING NOT NULL,
  wcbilltonum INT64 NOT NULL,
  wcbilltoname STRING NOT NULL,
  wcinstructions STRING,
  wcuhsflag STRING NOT NULL,
  wccmsflag STRING NOT NULL,
  transemail STRING,
  transemailpassword STRING,
  transfaxnum STRING,
  transfxto STRING,
  transuseemail INT64 NOT NULL,
  transusefx INT64 NOT NULL,
  transusemail INT64 NOT NULL,
  complete STRING NOT NULL,
  actiondate DATETIME NOT NULL,
  lastupduserid STRING,
  lastupddatetime DATETIME,
  companypk STRING NOT NULL,
  employerportalbaseurl STRING,
  accepticd10 BOOL NOT NULL,
  icd10effectivitydate DATE,
  printepsremittancecopy BOOL,
  regionkey INT64 NOT NULL,
  wcbilltoinsurancepk STRING,
  wcbilltocompanypk STRING,
  epsbilltocompanypk STRING,
  numberofemployeesrange STRING,
  companypktxt STRING,
  insertedby STRING,
  inserteddtm DATETIME,
  modifiedby STRING,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME,
  sourcesystemcode STRING,
  deleteflag INT64
)
;