CREATE TABLE IF NOT EXISTS edwpsc.pv_stglogbook
(
  log_num INT64 NOT NULL,
  practice STRING NOT NULL,
  pat_num INT64 NOT NULL,
  svc_date DATETIME NOT NULL,
  clinic STRING NOT NULL,
  last_name STRING,
  first_name STRING,
  birthday DATETIME,
  ssn STRING NOT NULL,
  phone STRING NOT NULL,
  phone_ext STRING NOT NULL,
  prv_status STRING NOT NULL,
  eps_status STRING NOT NULL,
  wc_status STRING NOT NULL,
  misc_status STRING NOT NULL,
  time_in DATETIME NOT NULL,
  scheduledtime DATETIME,
  scheduledmethod INT64,
  time_out DATETIME,
  hear_from STRING NOT NULL,
  crt_usernum INT64 NOT NULL,
  crt_userid STRING,
  crt_datetime DATETIME NOT NULL,
  last_upd_usernum INT64,
  last_upd_userid STRING,
  last_upd_datetime DATETIME,
  zippass_checkin DATETIME,
  logbookpk STRING NOT NULL,
  notes STRING,
  patappointmentpk STRING,
  kiosksessionpk STRING,
  kioskpin STRING,
  kioskstatus INT64,
  regionkey INT64 NOT NULL,
  visitstatusid INT64,
  eregstatus INT64,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL
)
;