CREATE TABLE IF NOT EXISTS edwpsc.pv_stgchartxrays
(
  chartxraypk STRING NOT NULL,
  chartxraypk_txt STRING NOT NULL,
  chartpk STRING NOT NULL,
  chartpk_txt STRING NOT NULL,
  description STRING,
  status INT64 NOT NULL,
  procedurecode STRING NOT NULL,
  modifiers STRING,
  questionid INT64,
  questionxml STRING,
  transcriptiontext STRING,
  completedby STRING,
  completedon DATETIME,
  completedbyuserpk STRING,
  reviewedby STRING,
  reviewedon DATETIME,
  reviewedbyuserpk STRING,
  suppressedon DATETIME,
  suppressedby STRING,
  createdby STRING,
  createdon DATETIME NOT NULL,
  lastupdatedby STRING,
  lastupdatedon DATETIME NOT NULL,
  lastupdatedbyuserpk STRING,
  orderedbyphysician STRING,
  orderedbyphysicianon DATETIME,
  orderedbyuserpk STRING,
  receivedbyuserpk STRING,
  radiologyimagepath STRING,
  radiologyshielding INT64,
  radiologytransport INT64,
  radiologytransportother STRING,
  datetimedeleted DATETIME,
  datesent DATETIME,
  facilitytype INT64 NOT NULL,
  placerordernumber STRING,
  providernote STRING,
  radiologyoverreadreviewedon DATETIME,
  radiologyoverreadreviewedby STRING,
  radiologyoverreadexpectexternalresults BOOL,
  providernoteaddedby STRING,
  providernoteaddedon DATETIME,
  sentby STRING,
  seeattacheddocument BOOL NOT NULL,
  physicianpk STRING,
  nonproviderordered BOOL,
  physiciandescription STRING,
  regionkey INT64 NOT NULL,
  ts BYTES,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;