CREATE TABLE IF NOT EXISTS edwpsc.pv_stgerafileclaimlinecarc
(
  carc_id INT64 NOT NULL,
  claimline_id INT64,
  claim_id INT64,
  payer_id INT64,
  fileid INT64,
  bpr_id INT64,
  trn_id INT64,
  carc01_category STRING,
  carc02_code STRING,
  carc03_amount STRING,
  carc04 STRING,
  carc05 STRING,
  carc06 STRING,
  carc07 STRING,
  carc08 STRING,
  carc09 STRING,
  carc10 STRING,
  carc11 STRING,
  carc12 STRING,
  carc13 STRING,
  carc14 STRING,
  carc15 STRING,
  carc16 STRING,
  carc17 STRING,
  carc18 STRING,
  carc19 STRING,
  carcsegment STRING,
  inserteddtm DATETIME NOT NULL,
  gs_id INT64,
  dwlastupdatedatetime DATETIME NOT NULL
)
;