CREATE TABLE IF NOT EXISTS edwpsc.pv_stglabcodeheader
(
  labrequestid INT64 NOT NULL,
  defaultcodes STRING NOT NULL,
  questionxml STRING,
  transcriptiontext STRING,
  completedby STRING,
  completedon DATETIME,
  completedbyuserpk STRING,
  reviewedby STRING,
  reviewedon DATETIME,
  reviewedbyuserpk STRING,
  createdby STRING,
  createdon DATETIME NOT NULL,
  lastupdatedby STRING,
  lastupdatedon DATETIME NOT NULL,
  lastupdatedbyuserpk STRING,
  orderedbyphysician STRING,
  orderedbyphysicianon DATETIME,
  orderedbyuserpk STRING,
  suppressedby STRING,
  suppressedon DATETIME,
  labcodeheaderpk STRING NOT NULL,
  labcodeheaderpk_txt STRING NOT NULL,
  physicianpk STRING,
  nonproviderordered BOOL,
  physiciandescription STRING,
  regionkey INT64 NOT NULL,
  ts BYTES,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL
)
;