CREATE TABLE IF NOT EXISTS edwpsc.pv_stgchart
(
  chartpk STRING NOT NULL,
  chartpk_txt STRING NOT NULL,
  clinicpk STRING NOT NULL,
  clinicpk_txt STRING NOT NULL,
  patinfopk STRING NOT NULL,
  patinfopk_txt STRING NOT NULL,
  logdetailpk STRING NOT NULL,
  logdetailpk_txt STRING NOT NULL,
  chartnumber INT64 NOT NULL,
  sectionnone INT64 NOT NULL,
  sectionreviewed INT64 NOT NULL,
  notes STRING,
  signoffdate DATETIME,
  signedoffby STRING,
  emcode STRING,
  emcodetime INT64,
  risk STRING,
  patienttype INT64 NOT NULL,
  createdby STRING,
  createdon DATETIME NOT NULL,
  lastupdatedby STRING,
  lastupdatedon DATETIME NOT NULL,
  signoffsealeddate DATETIME,
  signedoffsealedby STRING,
  emcodesuggested STRING,
  emcodeoverride BOOL,
  historian STRING,
  emcodemodifiers STRING,
  language INT64,
  smokingstatus INT64,
  signoffsealedbypk STRING,
  signoffbypk STRING,
  showalltabs BOOL,
  hxnotcompletedreason INT64,
  hxnotcompletedupdatedby STRING,
  hxnotcompletedupdatedon DATETIME,
  visitsummary STRING,
  smokingstatuscode INT64,
  transitionofcaretypeid INT64,
  transitionofcareother STRING,
  patientproviderinteractioncode INT64,
  transitionofcareimportreconciled BOOL,
  portaldatalastsent DATETIME,
  importsource STRING,
  importsourcecompletedby STRING,
  importsourcecompletedon DATETIME,
  historylevel INT64,
  cc_hpi_level INT64,
  ros_level INT64,
  pfsh_level INT64,
  physicallevel INT64,
  complexitylevel INT64,
  datareviewlevel INT64,
  timelevel INT64,
  diagnosislevel INT64,
  disablecomplexitythrottle BOOL,
  assignedproviderphysicianpk STRING,
  assignedproviderphysicianpk_txt STRING,
  assignedprovideruserprofilepk STRING,
  assignedprovidername STRING,
  nonproviderdischarge BOOL,
  nonprovidersignoff BOOL,
  cosignrequired BOOL,
  cosignedbypk STRING,
  cosigndate DATETIME,
  cosignedby STRING,
  regionkey INT64 NOT NULL,
  ts BYTES,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;