CREATE TABLE IF NOT EXISTS edwpsc.pv_stgeraservice
(
  practice STRING,
  era_date DATETIME,
  era_num INT64,
  st_ctrl_num STRING,
  pvd_num STRING,
  claim_num STRING,
  svc_code STRING,
  modifier STRING,
  ctrl_num INT64,
  line_num INT64,
  claim_status INT64,
  inv_num INT64,
  proc_code STRING,
  ar_ctrl_num INT64,
  modifier1 STRING,
  modifier2 STRING,
  modifier3 STRING,
  svc_date DATETIME,
  pos_code STRING,
  rndr_pvd_id STRING,
  status STRING,
  charge NUMERIC(31, 2),
  expected NUMERIC(31, 2),
  covered NUMERIC(31, 2),
  deductible NUMERIC(31, 2),
  copay NUMERIC(31, 2),
  paid_to_patient NUMERIC(31, 2),
  payment NUMERIC(31, 2),
  noncovered NUMERIC(31, 2),
  payment_posted NUMERIC(31, 2),
  adj_posted NUMERIC(31, 2),
  deduct_posted NUMERIC(31, 2),
  increased_ar NUMERIC(31, 2),
  balance NUMERIC(31, 2),
  reason STRING,
  last_upd_userid STRING,
  last_upd_datetime DATETIME,
  eraservicepk STRING,
  regionkey INT64,
  sourcephysicaldeleteflag INT64,
  dwlastupdatedatetime DATETIME
)
;