CREATE TABLE IF NOT EXISTS edwpsc.pv_stglogdetail
(
  log_num INT64 NOT NULL,
  practice STRING NOT NULL,
  clinic STRING,
  pat_num INT64 NOT NULL,
  svc_date DATETIME NOT NULL,
  type STRING NOT NULL,
  cmp_num INT64 NOT NULL,
  cmp_name STRING,
  protocol STRING,
  phy_num INT64 NOT NULL,
  phy_name STRING NOT NULL,
  em_code STRING,
  diag_codes STRING NOT NULL,
  status STRING,
  notes STRING,
  time_in DATETIME NOT NULL,
  time_out DATETIME,
  new_wc_flag STRING NOT NULL,
  copay_amt NUMERIC(31, 2) NOT NULL,
  copay_type STRING NOT NULL,
  copay_notes STRING NOT NULL,
  prev_pay_amt NUMERIC(31, 2) NOT NULL,
  prev_pay_type STRING NOT NULL,
  prev_pay_notes STRING NOT NULL,
  curr_pay_amt NUMERIC(31, 2) NOT NULL,
  curr_pay_type STRING NOT NULL,
  curr_pay_notes STRING NOT NULL,
  crg_num INT64 NOT NULL,
  pv_msg STRING NOT NULL,
  pv_date DATETIME,
  pv_datetime DATETIME NOT NULL,
  pv_status STRING,
  wc_notes STRING NOT NULL,
  no_pivot_flag STRING NOT NULL,
  poa_pymt_num INT64 NOT NULL,
  category STRING NOT NULL,
  ref_clinic STRING NOT NULL,
  crt_usernum INT64 NOT NULL,
  crt_userid STRING NOT NULL,
  crt_datetime DATETIME NOT NULL,
  last_upd_usernum INT64 NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  proc_codes STRING,
  quick_visit_type STRING NOT NULL,
  quick_visit_flag STRING NOT NULL,
  ref_phy_num INT64 NOT NULL,
  visit_locked STRING NOT NULL,
  ins_short_name STRING NOT NULL,
  rte_status INT64 NOT NULL,
  visitcharttype INT64,
  logdetailid INT64,
  roomnumber STRING,
  logdetailpk STRING NOT NULL,
  selfpay_flag STRING NOT NULL,
  clinicpk STRING,
  lastupdateservertime DATETIME,
  kioskpk STRING,
  referringphysicianpk STRING,
  patinfopk STRING,
  virtualvisittype INT64 NOT NULL,
  alternatelocation STRING,
  medpodid STRING,
  ischartsigned BOOL,
  preferredpharmacy_ncpdp STRING,
  wantsinhousedispensing BOOL,
  preferredpharmacy_confirmed BOOL,
  companypk STRING,
  appointmentid INT64,
  isemployerportalsent BOOL,
  regionkey INT64,
  managingphyname STRING,
  managingphynum INT64,
  ispatienttelemedicineeligible BOOL,
  telemedicinetype INT64,
  telemedicinestatus INT64,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64
)
;