CREATE TABLE IF NOT EXISTS edwpsc.pv_stglaborder
(
  practicepk STRING NOT NULL,
  locationid INT64 NOT NULL,
  laborderid INT64 NOT NULL,
  patientid INT64 NOT NULL,
  patientname STRING NOT NULL,
  patientdob DATETIME NOT NULL,
  gender STRING NOT NULL,
  ethnicityid INT64,
  requestedby INT64,
  requestedbyname STRING,
  priority INT64 NOT NULL,
  daterequested DATETIME NOT NULL,
  placerordernumber STRING NOT NULL,
  reflabordernumber STRING,
  reflabaccessionnumber STRING,
  specimendrawn INT64 NOT NULL,
  laborderstatus INT64 NOT NULL,
  enteredby STRING NOT NULL,
  changedby STRING,
  datein DATETIME NOT NULL,
  datechange DATETIME,
  chartpk STRING,
  labfacilitytype INT64 NOT NULL,
  notificationuserprofilepk STRING,
  datesent DATETIME,
  whopayslab INT64 NOT NULL,
  pscholdflag INT64 NOT NULL,
  showreconciledmessage INT64 NOT NULL,
  placergroupnumber STRING,
  patnamespace STRING,
  placernamespace STRING,
  fillernamespace STRING,
  pattypecode STRING,
  specimenactioncode STRING,
  orderingprovidername STRING,
  orderingproviderid STRING,
  orderingprovidernametypecode STRING,
  orderingprovideridtypecode STRING,
  abnresponsecode INT64,
  facilitycode STRING,
  interfacetype INT64,
  labfacilityid INT64,
  laborderpk STRING NOT NULL,
  labprocessingstatus INT64,
  regionkey INT64,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64
)
;