CREATE TABLE IF NOT EXISTS edwpsc.pv_stgchartcodesheader
(
  chartcodesheaderpk STRING NOT NULL,
  chartpk STRING NOT NULL,
  codetypeid INT64 NOT NULL,
  description STRING,
  defaultcodes STRING NOT NULL,
  questionid INT64,
  questionxml STRING,
  transcriptiontext STRING,
  reviewrequired BOOL NOT NULL,
  completedby STRING,
  completedon DATETIME,
  reviewedby STRING,
  reviewedon DATETIME,
  sortorder INT64,
  createdby STRING,
  createdon DATETIME NOT NULL,
  lastupdatedby STRING,
  lastupdatedon DATETIME NOT NULL,
  orderedbyphysician STRING,
  orderedbyphysicianon DATETIME,
  suppressedby STRING,
  suppressedon DATETIME,
  answerxml STRING,
  ndc STRING,
  orderedbyuserpk STRING,
  receivedbyuserpk STRING,
  completedbyuserpk STRING,
  reviewedbyuserpk STRING,
  lastupdatedbyuserpk STRING,
  radiologyoverreadreviewedon DATETIME,
  radiologyoverreadreviewedby STRING,
  physicianpk STRING,
  nonproviderordered BOOL,
  physiciandescription STRING,
  actiontype INT64,
  regionkey INT64,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64,
  sourcesystemcode STRING,
  insertedby STRING,
  modifiedby STRING
)
;