CREATE TABLE IF NOT EXISTS edwpsc.pv_stgpayment
(
  payment_num INT64 NOT NULL,
  batch_num INT64 NOT NULL,
  seq_num STRING NOT NULL,
  category STRING,
  practice STRING NOT NULL,
  clinic STRING NOT NULL,
  check_num STRING NOT NULL,
  check_date DATETIME NOT NULL,
  check_amt NUMERIC(31, 2) NOT NULL,
  remain_amt NUMERIC(31, 2) NOT NULL,
  deposit_date DATETIME NOT NULL,
  description STRING NOT NULL,
  payer_name STRING,
  payer_num INT64 NOT NULL,
  payer_class STRING NOT NULL,
  payer_type STRING NOT NULL,
  pymt_type STRING NOT NULL,
  last_upd_userid STRING NOT NULL,
  last_upd_datetime DATETIME NOT NULL,
  lock_by STRING NOT NULL,
  nonargl INT64 NOT NULL,
  erapostnum INT64 NOT NULL,
  paymentpk STRING NOT NULL,
  paymentpk_txt STRING,
  crt_datetime DATETIME,
  regionkey INT64 NOT NULL,
  sysstarttime DATETIME,
  inserteddtm DATETIME NOT NULL,
  modifieddtm DATETIME NOT NULL,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag BOOL NOT NULL
)
;