CREATE TABLE IF NOT EXISTS edwpsc.pv_stgworklist
(
  practice STRING,
  worklist STRING,
  assignedto STRING,
  worklisttype STRING,
  priority INT64,
  createdby STRING,
  createdon DATETIME,
  refreshedcount INT64,
  worklistpk STRING,
  processfrequency INT64,
  clinic STRING,
  visittype STRING,
  payertype STRING,
  payerclass STRING,
  balancefrom NUMERIC(31, 2),
  balanceto NUMERIC(31, 2),
  daysfrom INT64,
  daysto INT64,
  patientfrom STRING,
  patientto STRING,
  payerfrom STRING,
  payerto STRING,
  isunassignedworklist BOOL,
  refreshedamount NUMERIC(31, 2),
  refreshedon DATETIME,
  refreshedby STRING,
  lastupdatedon DATETIME,
  lastupdatedcount INT64,
  lastupdatedamount NUMERIC(31, 2),
  totalprocessingtimems INT64,
  nextrefreshdate DATE,
  regionkey INT64 NOT NULL,
  inserteddtm DATETIME,
  modifieddtm DATETIME,
  dwlastupdatedatetime DATETIME NOT NULL,
  sourcephysicaldeleteflag INT64
)
;