EXPORT DATA OPTIONS(
  uri='gs://{{ params.param_parallon_ra_data_bucket_name }}/{{ params.param_parallon_ra_outbound_file_path }}{{ params.file_prefix }}{{ params.ssc_name }}_*.txt',
  format='CSV',
  overwrite=true,
  header=false,
  field_delimiter='|') AS
SELECT
    v_edw_daily_denial_inventory.ssc_name,
    v_edw_daily_denial_inventory.facility_name,
    v_edw_daily_denial_inventory.coid,
    v_edw_daily_denial_inventory.unit_num,
    v_edw_daily_denial_inventory.rate_schedule_name,
    substr(CAST(v_edw_daily_denial_inventory.rate_schedule_eff_begin_date as STRING), 1, 10) AS rate_schedule_eff_begin_date,
    substr(CAST(v_edw_daily_denial_inventory.rate_schedule_eff_end_date as STRING), 1, 10) AS rate_schedule_eff_end_date,
    v_edw_daily_denial_inventory.account_no,
    v_edw_daily_denial_inventory.patient_name,
    substr(CAST(v_edw_daily_denial_inventory.patient_dob as STRING), 1, 10) AS patient_dob,
    v_edw_daily_denial_inventory.iplan_id,
    v_edw_daily_denial_inventory.insurance_provider_name,
    v_edw_daily_denial_inventory.payer_group_name,
    v_edw_daily_denial_inventory.billing_name,
    v_edw_daily_denial_inventory.billing_contact_person,
    v_edw_daily_denial_inventory.authorization_code,
    v_edw_daily_denial_inventory.payer_patient_id,
    v_edw_daily_denial_inventory.payer_rank,
    v_edw_daily_denial_inventory.pa_financial_class,
    v_edw_daily_denial_inventory.payor_financial_class,
    v_edw_daily_denial_inventory.accounting_period,
    v_edw_daily_denial_inventory.major_payer_grp,
    v_edw_daily_denial_inventory.reason_code,
    v_edw_daily_denial_inventory.billing_status,
    v_edw_daily_denial_inventory.pa_service_code,
    v_edw_daily_denial_inventory.pa_account_status,
    v_edw_daily_denial_inventory.cc_patient_type,
    v_edw_daily_denial_inventory.pa_discharge_status,
    v_edw_daily_denial_inventory.pa_patient_type,
    v_edw_daily_denial_inventory.cancel_bill_ind,
    v_edw_daily_denial_inventory.admit_source,
    v_edw_daily_denial_inventory.admit_type,
    v_edw_daily_denial_inventory.pa_drg,
    v_edw_daily_denial_inventory.attending_physician_id,
    v_edw_daily_denial_inventory.attending_physician_name,
    substr(CAST(v_edw_daily_denial_inventory.service_date_begin as STRING), 1, 10) AS service_date_begin,
    substr(CAST(v_edw_daily_denial_inventory.discharge_date as STRING), 1, 10) AS discharge_date,
    v_edw_daily_denial_inventory.comparison_method,
    v_edw_daily_denial_inventory.project_name,
    v_edw_daily_denial_inventory.work_queue_name,
    v_edw_daily_denial_inventory.status_category_desc,
    v_edw_daily_denial_inventory.status_desc,
    v_edw_daily_denial_inventory.status_phase_desc,
    substr(CAST(v_edw_daily_denial_inventory.calc_date as STRING), 1, 10) AS calc_date,
    v_edw_daily_denial_inventory.total_charges,
    v_edw_daily_denial_inventory.pa_actual_los,
    v_edw_daily_denial_inventory.total_billed_charges,
    v_edw_daily_denial_inventory.covered_charges,
    v_edw_daily_denial_inventory.total_expected_payment,
    v_edw_daily_denial_inventory.total_expected_adjustment,
    v_edw_daily_denial_inventory.total_pt_responsibility_actual,
    v_edw_daily_denial_inventory.total_variance_adjustment,
    v_edw_daily_denial_inventory.total_payments,
    v_edw_daily_denial_inventory.total_denial_amt,
    v_edw_daily_denial_inventory.payor_due_amt,
    v_edw_daily_denial_inventory.pa_total_account_bal,
    v_edw_daily_denial_inventory.ar_amount,
    v_edw_daily_denial_inventory.otd_to_date_amount_mtd AS otd_to_date_amount,
    v_edw_daily_denial_inventory.max_aplno,
    v_edw_daily_denial_inventory.max_seqno,
    v_edw_daily_denial_inventory.appeal_orig_amt,
    v_edw_daily_denial_inventory.current_appealed_amt,
    v_edw_daily_denial_inventory.current_appeal_balance,
    substr(CAST(v_edw_daily_denial_inventory.appeal_date_created as STRING), 1, 10) AS appeal_date_created,
    substr(CAST(v_edw_daily_denial_inventory.sequence_date_created as STRING), 1, 10) AS sequence_date_created,
    substr(CAST(v_edw_daily_denial_inventory.close_date as STRING), 1, 10) AS close_date,
    substr(CAST(v_edw_daily_denial_inventory.max_seq_deadline_date as STRING), 1, 10) AS max_seq_deadline_date,
    v_edw_daily_denial_inventory.sequence_creator,
    v_edw_daily_denial_inventory.appeal_owner,
    v_edw_daily_denial_inventory.appeal_modifier,
    v_edw_daily_denial_inventory.disp_code,
    v_edw_daily_denial_inventory.disp_desc,
    v_edw_daily_denial_inventory.web_disp_code,
    v_edw_daily_denial_inventory.root_code,
    v_edw_daily_denial_inventory.root_cause_description,
    v_edw_daily_denial_inventory.root_cause_dtl,
    v_edw_daily_denial_inventory.external_appeal_code,
    v_edw_daily_denial_inventory.apl_appeal_code,
    v_edw_daily_denial_inventory.apl_appeal_desc,
    substr(CAST(v_edw_daily_denial_inventory.first_denial_date as STRING), 1, 10) AS first_denial_date,
    v_edw_daily_denial_inventory.denial_age,
    substr(CAST(v_edw_daily_denial_inventory.pa_denial_update_date as STRING), 1, 10) AS pa_denial_update_date,
    substr(CAST(v_edw_daily_denial_inventory.first_activity_create_date as STRING), 1, 10) AS first_activity_create_date,
    substr(CAST(v_edw_daily_denial_inventory.last_activity_completion_date as STRING), 1, 10) AS last_activity_completion_date,
    v_edw_daily_denial_inventory.last_activity_completion_age,
    v_edw_daily_denial_inventory.last_user_activity_create_age,
    substr(CAST(v_edw_daily_denial_inventory.last_reason_change_date as STRING), 1, 10) AS last_reason_change_date,
    substr(CAST(v_edw_daily_denial_inventory.last_status_change_date as STRING), 1, 10) AS last_status_change_date,
    substr(CAST(v_edw_daily_denial_inventory.last_project_change_date as STRING), 1, 10) AS last_project_change_date,
    substr(CAST(v_edw_daily_denial_inventory.last_owner_change_date as STRING), 1, 10) AS last_owner_change_date,
    substr(CAST(v_edw_daily_denial_inventory.activity_due_date as STRING), 1, 10) AS activity_due_date,
    v_edw_daily_denial_inventory.activity_desc,
    v_edw_daily_denial_inventory.activity_subject,
    v_edw_daily_denial_inventory.activity_owner,
    v_edw_daily_denial_inventory.appeal_sent_activity_ownr,
    substr(CAST(v_edw_daily_denial_inventory.appeal_sent_activity_date as STRING), 1, 10) AS appeal_sent_activity_date,
    v_edw_daily_denial_inventory.appeal_sent_activity_age,
    v_edw_daily_denial_inventory.appeal_sent_activity_subj,
    v_edw_daily_denial_inventory.appeal_sent_activity_desc,
    v_edw_daily_denial_inventory.statusstratification AS stratification,
    v_edw_daily_denial_inventory.status_kpi,
    v_edw_daily_denial_inventory.followup_kpi,
    v_edw_daily_denial_inventory.appealsent_kpi,
    v_edw_daily_denial_inventory.deadline_kpi,
    v_edw_daily_denial_inventory.mon_account_payer_id,
    datetime_trunc(current_datetime('{{ params.timezone_str }}'), SECOND) AS extract_date,
    v_edw_daily_denial_inventory.payer_category,
    v_edw_daily_denial_inventory.writeoff_amt_net AS writeoff_amt,
    v_edw_daily_denial_inventory.cash_adj_amt_net AS cash_adj_amt
  FROM
    {{ params.param_parallon_ra_stage_dataset_name }}.v_edw_daily_denial_inventory
  WHERE v_edw_daily_denial_inventory.{{ params.filter_column}} IN UNNEST({{ params.filter_value_list }})
;