EXPORT DATA OPTIONS(
  uri='gs://{{ params.param_parallon_ra_data_bucket_name }}/{{ params.param_parallon_ra_outbound_file_path }}{{ params.file_prefix }}{{ params.ssc_name }}_*.txt',
  format='CSV',
  overwrite=true,
  header=false,
  field_delimiter='|') AS
SELECT
    v_edw_daily_discrepancy_inventory.ssc_name,
    v_edw_daily_discrepancy_inventory.facility_name,
    v_edw_daily_discrepancy_inventory.coid,
    v_edw_daily_discrepancy_inventory.unit_num,
    v_edw_daily_discrepancy_inventory.rate_schedule_name,
    format_date('%m/%d/%Y', v_edw_daily_discrepancy_inventory.rate_schedule_eff_begin_date) AS rate_schedule_eff_begin_date,
    format_date('%m/%d/%Y', v_edw_daily_discrepancy_inventory.rate_schedule_eff_end_date) AS rate_schedule_eff_end_date,
    v_edw_daily_discrepancy_inventory.account_no,
    v_edw_daily_discrepancy_inventory.patient_name,
    format_date('%m/%d/%Y', v_edw_daily_discrepancy_inventory.patient_dob) AS patient_dob,
    v_edw_daily_discrepancy_inventory.iplan_id,
    v_edw_daily_discrepancy_inventory.insurance_provider_name,
    v_edw_daily_discrepancy_inventory.payer_group_name,
    v_edw_daily_discrepancy_inventory.billing_name,
    v_edw_daily_discrepancy_inventory.billing_contact_name AS billing_contact_person,
    v_edw_daily_discrepancy_inventory.authorization_code,
    v_edw_daily_discrepancy_inventory.payer_patient_id,
    v_edw_daily_discrepancy_inventory.payer_rank,
    v_edw_daily_discrepancy_inventory.pa_financial_class,
    v_edw_daily_discrepancy_inventory.payor_financial_class,
    v_edw_daily_discrepancy_inventory.reason_code,
    v_edw_daily_discrepancy_inventory.billing_status,
    v_edw_daily_discrepancy_inventory.pa_service_code,
    v_edw_daily_discrepancy_inventory.pa_account_status,
    v_edw_daily_discrepancy_inventory.cc_patient_type,
    v_edw_daily_discrepancy_inventory.pa_discharge_status,
    v_edw_daily_discrepancy_inventory.pa_patient_type,
    v_edw_daily_discrepancy_inventory.cancel_bill_ind,
    v_edw_daily_discrepancy_inventory.admit_source,
    v_edw_daily_discrepancy_inventory.pa_drg,
    v_edw_daily_discrepancy_inventory.attending_physician_id,
    v_edw_daily_discrepancy_inventory.attending_physician_name,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.service_date_begin) AS service_date_begin,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.discharge_date) AS discharge_date,
    v_edw_daily_discrepancy_inventory.comparison_method,
    v_edw_daily_discrepancy_inventory.project_name,
    v_edw_daily_discrepancy_inventory.work_queue_name,
    v_edw_daily_discrepancy_inventory.status_category_desc,
    v_edw_daily_discrepancy_inventory.status_desc,
    v_edw_daily_discrepancy_inventory.status_phase_desc,
    format_date('%m/%d/%Y', v_edw_daily_discrepancy_inventory.calc_date) AS calc_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.overpayment_date) AS overpayment_date,
    v_edw_daily_discrepancy_inventory.overpayment_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.underpayment_date) AS underpayment_date,
    v_edw_daily_discrepancy_inventory.underpayment_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.non_fin_disc_date) AS non_fin_disc_date,
    v_edw_daily_discrepancy_inventory.non_fin_disc_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.variance_creation_date) AS variance_creation_date,
    v_edw_daily_discrepancy_inventory.variance_creation_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.variance_resolution_date) AS variance_resolution_date,
    v_edw_daily_discrepancy_inventory.variance_resolution_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.first_activity_create_date) AS first_activity_create_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.last_activity_completion_date) AS last_activity_completion_date,
    v_edw_daily_discrepancy_inventory.last_activity_completion_age,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.last_reason_change_date) AS last_reason_change_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.last_status_change_date) AS last_status_change_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.last_project_change_date) AS last_project_change_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.last_owner_change_date) AS last_owner_change_date,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.activity_due_date) AS activity_due_date,
    v_edw_daily_discrepancy_inventory.activity_description AS activity_desc,
    v_edw_daily_discrepancy_inventory.activity_subject,
    v_edw_daily_discrepancy_inventory.activity_owner,
    v_edw_daily_discrepancy_inventory.total_charges,
    v_edw_daily_discrepancy_inventory.pa_actual_los,
    v_edw_daily_discrepancy_inventory.total_billed_charges,
    v_edw_daily_discrepancy_inventory.total_expected_payment,
    v_edw_daily_discrepancy_inventory.total_expected_adjustment,
    v_edw_daily_discrepancy_inventory.total_pt_responsibility AS total_pt_responsibility_actual,
    v_edw_daily_discrepancy_inventory.total_variance_adjustment,
    v_edw_daily_discrepancy_inventory.total_payments,
    v_edw_daily_discrepancy_inventory.total_denial_amount AS total_denial_amt,
    ROUND(v_edw_daily_discrepancy_inventory.payor_due_amount, 2, 'ROUND_HALF_EVEN') AS payor_due_amt,
    v_edw_daily_discrepancy_inventory.ar_amount,
    v_edw_daily_discrepancy_inventory.pa_total_account_bal,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.user_completed_activity_date) AS user_completed_activity_date,
    v_edw_daily_discrepancy_inventory.user_completed_activity_age,
    v_edw_daily_discrepancy_inventory.user_completed_activity_subj,
    v_edw_daily_discrepancy_inventory.user_completed_activity_desc,
    v_edw_daily_discrepancy_inventory.user_completed_activity_ownr,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.valid_overpymnt_activity_dt) AS valid_overpymnt_activity_date,
    v_edw_daily_discrepancy_inventory.valid_overpymnt_activity_age,
    v_edw_daily_discrepancy_inventory.valid_overpymnt_activity_subj,
    v_edw_daily_discrepancy_inventory.valid_overpymnt_activity_desc,
    v_edw_daily_discrepancy_inventory.valid_overpymnt_activity_ownr,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.valid_underpymnt_activity_date) AS valid_underpymnt_activity_date,
    v_edw_daily_discrepancy_inventory.valid_underpymnt_activity_age,
    v_edw_daily_discrepancy_inventory.valid_underpymnt_activity_subj,
    v_edw_daily_discrepancy_inventory.valid_underpymnt_activity_desc,
    v_edw_daily_discrepancy_inventory.valid_underpymnt_activity_ownr,
    v_edw_daily_discrepancy_inventory.stratification,
    v_edw_daily_discrepancy_inventory.status_kpi,
    v_edw_daily_discrepancy_inventory.validation_grp,
    v_edw_daily_discrepancy_inventory.discrepancy_group,
    v_edw_daily_discrepancy_inventory.credit,
    v_edw_daily_discrepancy_inventory.payer_category,
    v_edw_daily_discrepancy_inventory.model_issue,
    v_edw_daily_discrepancy_inventory.credit_balance_age,
    v_edw_daily_discrepancy_inventory.activity_kpi,
    format_datetime('%m/%d/%Y %I:%M:%S %p', v_edw_daily_discrepancy_inventory.extract_date) AS extract_date,
    v_edw_daily_discrepancy_inventory.schema_id
  FROM
    {{ params.param_parallon_ra_stage_dataset_name }}.v_edw_daily_discrepancy_inventory
  WHERE v_edw_daily_discrepancy_inventory.{{ params.filter_column}} IN UNNEST({{ params.filter_value_list }})
;