SELECT
SQLUser.HCFACILITY.CSFAHOSPNUMBER as Unit_Number
, SQLUser.HCENCOUNTER.HCENPTACCT as Pat_Acct_Num
, SQLUser.HCACTIONHIST.HCACTHUSERID as Action_Code_User
, SQLUser.HCACTIONHIST.HCACTHRESID as Result_Code
, SQLUser.HCACTIONHIST.HCACTHTIM as Action_Code_Time
, SQLUser.HCACTIONHIST.HCACTHDTE as Action_Code_Date
,{fn right(SQLUser.HCACTIONHIST.HCACTPAYERID,5)} AS Iplan_ID
, SQLUser.HCACTIONHIST.HCACTHSTAT as Status_Code
, SQLUser.HCACTIONHIST.CSACTHPOOL as Pool
,SQLUser.HCACTIONHIST.HCACTHACTID as Action_Code 
,SQLUser.HCACTIONHIST.HCACTHID
FROM SQLUser.HCACTIONHIST
JOIN SQLUser.HCENCOUNTER
    ON SQLUser.HCENCOUNTER.HCENID = SQLUser.HCACTIONHIST.HCACTENCNTRID
JOIN SQLUser.HCFACILITY 
    ON SQLUser.HCFACILITY.HCFAID = SQLUser.HCENCOUNTER.HCENFACILITY
JOIN SQLUser.HCPAS
    ON SQLUser.HCPAS.HCPSID = SQLUser.HCFACILITY.HCFAPASID
LEFT JOIN SQLUser.HCACCOUNT 
    ON SQLUser.HCACCOUNT.HCACID = SQLUser.HCACTIONHIST.HCACTHACNUM

WHERE
SQLUser.HCACTIONHIST.HCACTHUSERID <> 'CONVERT'
AND SQLUser.HCACTIONHIST.HCACTHUSERID <> 'IMPORT'
AND SQLUser.HCACTIONHIST.HCACTHUSERID <> 'sys'
AND SQLUser.HCACTIONHIST.HCACTHUSERID <> 'SYS'
AND SQLUser.HCACTIONHIST.HCACTHUSERID <> 'ARTSCHED'
AND SQLUser.HCACTIONHIST.HCACTHUSERID <> 'ESSCBOT'